iree-org/iree

- .github/workflows/ci.yml
Tested using `ci-test` branch rebased on top of #136, successful run here: https://github.com/google/iree/commit/72eddf2f39807948524d0b05041d23c951e0cdeb/checks?check_suite_id=307931233
> Download and set up Vulkan SDK on CI.

- .github/workflows/ci.yml
Adds a basic CI that builds everything with cmake. Doesn't run any tests.
> Add CMake CI

- .github/workflows/ci.yml
> Run `apt-get update` on CI prior to `apt-get install`.

- .github/workflows/ci.yml
Not particularly concerned. I think it's just good hygiene and I'm about to fiddle with some other stuff here.
> Make GitHub action CI parameter expansion safer

- .github/workflows/cmake_build.yml
I think this is fast enough it can be a presubmit (< 10 minutes)
> Run CMake build on presubmit

- .github/workflows/cmake_build.yml
This makes it easier to do the same thing by manually running the script.
> Use cmake build script in cmake CI

- .github/workflows/bazel_build.yml
- .github/workflows/check_submodules.yml
- .github/workflows/synchronize_submodules.yml
I'm moving these in https://github.com/google/iree/pull/671. Because of weirdness in our automation. Workflow files have to be edited in a separate PR.
Depends on https://github.com/google/iree/pull/671
> Redirect workflows to new location of git scripts

- iree/hal/cts/BUILD
- iree/samples/simple_embedding/BUILD
- iree/tools/run_mlir_main.cc
Remove references to internal paths
> Remove references to internal paths

- .github/workflows/synchronize_submodules.yml
The if condition above means this won't be triggered if there's no diff.
> Remove obsolete comment

- .github/workflows/bazel_build.yml
> Bump Bazel version in GitHub actions workflow.

- .github/workflows/synchronize_submodules.yml
Reverts google/iree#1065
This did not have the desired effect.
> Revert "Give Synchronize Submodules Action Write Access"

- .github/workflows/update_submodules.yml
Reverts google/iree#1181. I meant to push this to my fork. I really wish it wasn't so easy for me to push to master...
> Revert "Try out per-repo filtering"

- .github/workflows/bazel_build.yml
Copybara weirdness reverted my removal of this with https://github.com/google/iree/commit/85eb8f39f3324631758323bf1dc14bfa0da2c803
> Re-revert jax install

- .github/workflows/bazel_to_cmake.yml
Depends on https://github.com/google/iree/pull/1549
> Remove --strict from bazel_to_cmake workflow.

- README.md
I kept getting 404s and thought I'd done something wrong. Turns out this can take a while...
> Add note that publishing can lag 20 minutes

- iree/vm/test/CMakeLists.txt
```
$ python3 .\build_tools\bazel_to_cmake\bazel_to_cmake.py
```
> Run bazel_to_cmake.py.

- docs/developer_overview.md
- iree/compiler/Dialect/IREE/Transforms/test/drop_compiler_hints.mlir
- iree/compiler/Dialect/VM/Transforms/test/mark_public_symbols_exported.mlir
Open to suggestions for a simpler file / set of passes that we expect to be more stable.
> Update docs on iree-opt to use a file and options that still exist.

- colab/mnist_tensorflow.ipynb
Also re-ran the notebook with TensorFlow 2.5.0 (on Windows).
Closes https://github.com/google/iree/pull/2331
PiperOrigin-RevId: 318519824
> Replace uses of TensorFlow DistributionStrategy experimental_run_v2 with run.

- .github/workflows/publish_docs.yml
- .github/workflows/synchronize_submodules.yml
https://github.com/google/iree/blob/main/.github/workflows/update_submodules.yml will also need updating.
> Update GitHub Actions workflows to reference new branch names.

- iree/hal/vulkan/timepoint_util.cc
- iree/hal/vulkan/timepoint_util.h
> Fix memory leak in timeline semaphore emulation.

- build_tools/docker/bazel/Dockerfile
- build_tools/docker/bazel_bindings/Dockerfile
- build_tools/docker/bazel_tensorflow/Dockerfile
- build_tools/docker/cmake/Dockerfile
Also includes some small fixes to the `Dockerfile`s.
> Adds the `IREE_LLVMAOT_LINKER_PATH` environment variable to IREE's Docker images.

- docs/GetStarted/getting_started_android_cmake.md
Add a getting started documentation for compiling and running IREE module with dylib-llvm-aot backend
> Add a documentation for android llvm aot

- CMakeLists.txt
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- experimental/CMakeLists.txt
- experimental/ModelBuilder/BUILD
- experimental/ModelBuilder/CMakeLists.txt
- experimental/ModelBuilder/ModelBuilder.cpp
- experimental/ModelBuilder/ModelBuilder.h
- experimental/ModelBuilder/test/BUILD
- experimental/ModelBuilder/test/BenchMatMulVectorColumnMajorLLVMIntrinsicsJIT.cpp
- experimental/ModelBuilder/test/BenchMatMulVectorJIT.cpp
- experimental/ModelBuilder/test/BenchMatVecVectorJIT.cpp
- experimental/ModelBuilder/test/CMakeLists.txt
- experimental/ModelBuilder/test/TestDotProdJIT.cpp
- experimental/ModelBuilder/test/TestMNISTJIT.cpp
- experimental/ModelBuilder/test/TestMatMulVulkan.cpp
- experimental/ModelBuilder/test/TestSimpleJIT.cpp
- experimental/ModelBuilder/test/TestSimpleJITVulkan.cpp
- experimental/ModelBuilder/test/TestSimpleMLIR.cpp
- experimental/ModelBuilder/test/TestVectorToGPU.cpp
- experimental/ModelBuilder/test/TestVectorTransfersJIT.cpp
Update bazel file to allow bazel_to_cmake to work. Add few workarounds
for dynamic library not working with the script.
> Add CMake build for ModelBuilder project

- docs/GetStarted/getting_started_android_cmake.md
> Update documentations for dylib-llvm-aot android

- .github/workflows/update_tf.yml
It's currently pointing at the wrong file.
> Fix typo in submodule bump action

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/scatter_update_test.py
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertHLOToVMLA.cpp
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/scatter.mlir
- iree/compiler/Dialect/VMLA/Conversion/VMLAToVM/ConvertVMLAToVM.cpp
- iree/compiler/Dialect/VMLA/IR/VMLAOps.td
- iree/compiler/Dialect/VMLA/vmla.imports.mlir
- iree/hal/vmla/op_kernels.h
- iree/hal/vmla/op_kernels_generic.h
- iree/hal/vmla/vmla_module.cc
Includes kernel implementation and required compiler work.
> Add scatter to VMLA

- iree/hal/cts/cts_test_base.h
There is an issue in SwiftShader requiring us to share the Vulkan
driver across test cases. But it turns out that this cannot be done
using static objects because static objects are destructed after
main(). It can cause unexpected problems when the driver also want
to perform clean up at that time.
> [vulkan] Use per-test-suite SetUp/TearDown for sharing driver

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/concat_test.py
> test for concat op on matrix with zero dim

- iree/compiler/Conversion/CodegenUtils/MatmulCodegenStrategy.h
Import to unroll vector transformation into iree MatMulCodegenStrategy
> Enable unroll pattern in MatMulCodegenStrategy

- experimental/ModelBuilder/MemRefUtils.h
Allow user-provided memory alignment inside `makeInitializedStridedMemrefDescriptor`.
Duplicate of #2426
> Allow user-provided memory alignment inside `makeInitializedStridedMemrefDescriptor`.

- experimental/ModelBuilder/MemRefUtils.h
- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/concat_test.py
* be537d5c Allow user-provided memory alignment inside `makeInitializedStridedMemrefDescr..
* a672e635 Merge pull request #2438 from ThomasRaoux/importVectorUnroll                    
* 34ec8599 Enable unroll pattern in MatMulCodegenStrategy.
> Merge main -> google

- .github/workflows/update_tf.yml
This makes the description more in line with LLVM integrates and makes
the commit being integrated explicit.
Tested:
Not really. I guess we'll just see what happens the next time it runs. #yolo
> Improve TF submodule bump action descriptions

- iree/tools/run_mlir_main.cc
part of https://github.com/google/iree/issues/2304
> Support iree-run-mlir to read input values from a file.

- .github/workflows/google_to_main.yml
This should provide a base point for periodic integrates.
Tested: no
> Add GitHub action to create PRs merging google -> main

- iree/base/dynamic_library_posix.cc
Emits actual message describing the error.
> Populate dlopen error message

- scripts/git/bazel_to_cmake.sh
- scripts/git/google_to_main.sh
- scripts/git/main_to_google.sh
- scripts/git/update_tf_submodule.sh
These scripts automate some common maintainer tasks. They use the
[gh cli](https://github.com/cli/cli).
> Add scripts for interacting with GitHub

- iree/hal/dylib/dylib_executable.cc
- iree/hal/dylib/memref_runtime.h
This fixes a segfault running resnet50 with dylib-llvm-aot backend.
> Pass push_constants to function argument

- docs/contributor_tips.md
- scripts/git/bazel_to_cmake.sh
- scripts/git/google_to_main.sh
- scripts/git/main_to_google.sh
- scripts/git/update_tf_submodule.sh
Contains some recommendations for tools and git setup for people
contributing to IREE. This is an opinionated guide that is largely just
*my* setup, but I know it overlaps significantly with other people's as
well and hopefully it can evolve into something more general.
> Add a doc for contributor tips

- .bazelrc
- build_tools/cmake/iree_copts.cmake
For consistency (and mysterious Google tooling reasons.....)
> Update link style for ifchange blocks.

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/saved_model_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/compiler/signature_def_saved_model_test.py
- integrations/tensorflow/bindings/python/pyiree/xla/compiler/xla_module_proto_test.py
- integrations/tensorflow/e2e/control_flow_test.py
- integrations/tensorflow/e2e/keras/train_vision_models_on_cifar.py
- integrations/tensorflow/e2e/mandelbrot_test.py
- integrations/tensorflow/e2e/tensorlist_test.py
IREE doesn't support `python2`.
> Remove python2 compatibility code.

- build_tools/docker/build_and_update_gcr.py
I messed this up in https://github.com/google/iree/pull/2583
> Fix Docker update dependency logic

- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertTensorOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertBufferViewOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/hal.imports.mlir
- iree/modules/hal/hal_module.cc
Fixes https://github.com/google/iree/issues/2305
> Print input/output values for each dispatch function in DEBUG mode

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Dialect/Shape/Plugins/XLA/XlaHloShapeBuilder.cpp
- iree/test/e2e/regression/dynamic_torch_index_select_high_rank.mlir
- iree/test/e2e/regression/dynamic_torch_index_select_negative.mlir
- iree/test/e2e/regression/dynamic_torch_index_select_scalar.mlir
- iree/test/e2e/regression/dynamic_torch_index_select_vector.mlir
Support dynamic mhlo.torch_index_select and add test.
> Support dynamic mhlo.torch_index_select and add test.

- docs/developing_iree/developer_overview.md
Re-create the PR based on https://github.com/google/iree/pull/2616
The previous one was against with wrong branch.
> Add debugging tips to developer_overview.md

- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86/integrations/build_kokoro.sh
For some reason https://github.com/google/iree/pull/2566 made the
integrations build run three times as long. Reverting until we can
figure out the root cause.
See https://github.com/google/iree/issues/2653
Confirmed presubmits now take 20 minutes
> Run integrations build as root

- iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir
This is leftover from #2635. Adjust the test to validate new lowering
> Test entry function conversion to LLVMIR

- experimental/ModelBuilder/MemRefUtils.h
This revision adds MemRef building functions that allow passing
an extra `shapeAlloc` argument to control allocation and padding.
When the function `makeInitializedStridedMemRefDescriptor` is called
with `shape = [128, 127]` and `shapeAlloc = [128, 128]`, it allocates
a memref with `128*128*sizeof(T)` bytes, `sizes = [128, 127]` and
`strides = [128, 1]`.
> [ModelBuilder] Add MemRefUtil helpers for padding.

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
This is useful to debug with IREE's tool starting from command-line level, and speedup debugging process.
https://github.com/google/iree/pull/2660 dumps traces at python level, the traces are split by invoked functions, but we would like to have more traces with dispatch function level, since IREE splits the function into multiple dispatch functions.
> Dump input values to a file.

- docs/design_docs/codegen_passes.md
Make the example better demonstrate some codegen aspects like
- Use large matrix sizes to make the indexing logic easier to follow
(since they wont be CSEed now)
- Add broadcast operation for pw ops example.
> Update the codegen pipeline example snippets 

- iree/compiler/Dialect/Flow/Transforms/FormStreams.cpp
- iree/compiler/Dialect/Flow/Transforms/test/form_streams.mlir
flow fragment support shapex.tie_shape argument outside of the fragment body
> flow fragment support shapex.tie_shape argument outside of the fragment body

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/pad.mlir
Also delete unused code.
Fixes https://github.com/google/iree/issues/2749
> Support pad op to take a splat constant as input.

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
* 7c105170 Add base check for tf.Tensor                                                    
* 8505e3d4 Merge pull request #2752 from GMNGeoffrey:main-to-google
> Merge google -> main

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
With the DialectConversion framework gaining the ability to
mergeBlocks, simplify the code to remove one-trip loops.
> Use mergeBlocks to simplifying inlining body of scf loops into its parent.

- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/base/api.cc
Fixes https://github.com/google/iree/issues/2801
> Use platform-specific, hopefully higher precision, system time.

- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/allocator_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/command_buffer_ops.mlir
- iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/test/control_flow_ops.mlir
- iree/compiler/Dialect/VM/IR/test/structural_ops.mlir
- iree/compiler/Dialect/VMLA/Conversion/VMLAToVM/test/conversion.mlir
The parser is expecting ' ...'  this PR fixes that.
> Fix vm variadic argument printer

- scripts/git/google_to_main.sh
- scripts/git/main_to_google.sh
Followup to https://github.com/google/iree/pull/2846
> Add missing close paren to merging script

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/Passes.h
- iree/compiler/Conversion/HLOToLinalg/ResolveShapeOps.cpp
This change was generated by clang-tidy.
> [NFC] Follow the style to add trivial braces around statements.

- iree/compiler/Dialect/VM/Analysis/RegisterAllocation.cpp
Taking pointers to SmallVector entries is not safe when the SmallVector
gets reallocated, which happens here when we have more nodes than the
predicted SmallVector size. Instead, use a DenseMap for storage and
don't modify it after initial creation.
> Fix UAF in RegisterAllocation

- integrations/tensorflow/e2e/math_test.py
Adding a test to prove ceiling works end-to-end matching changes in tensorflow repo.
> Added tf.ceil e2e test

- iree/hal/cts/command_queue_test.cc
- iree/hal/vulkan/serializing_command_queue.cc
- iree/hal/vulkan/serializing_command_queue.h
This commit re-lands #2431 by reverting #2465 and rolling in fixes.
> Re-land fix for SerializingCommandQueue and enable command queue tests

- experimental/ModelBuilder/test/BenchMatMulVectorGPU.cpp
ArrayRef
LICM is not fully supported in the lowering passes so add a control to
have it on or off form cli. Fix a bug in unroll call as ArrayRef
argument cannot be created on the fly.
> Add control to enable LICM from command line and fix a bug related to

- docs/get_started/getting_started_python.md
Fixes https://github.com/google/iree/issues/2937
> Update link to Using Colab doc.

- experimental/ModelBuilder/test/BenchMatMulVectorGPU.cpp
Map N to X dimension and M as Y dimension to get better memory access
pattern. Also re-enable walking tiles starting at size 32.
> Change the dimension mapping for matmul.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/test/tensor_folding.mlir
Fold `flow.tensor.update` when all operands are constant. /cc @benvanik for visibility.
> Fold flow.tensor.update when all operands are constant

- iree/samples/custom_modules/dialect/custom_opt.cc
- iree/samples/custom_modules/dialect/init_dialect.h
- iree/tools/init_compiler_modules.h
- iree/tools/init_iree_dialects.h
- iree/tools/init_mlir_dialects.h
- iree/tools/init_xla_dialects.h
- iree/tools/opt_main.cc
> Refactor for explicit dialect registration

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
The file implements compiler code and should roughly follow LLVM style.
> Fix format by changing to LLVM style

- iree/tools/benchmark_module_main.cc
- iree/tools/test/simple.mlir
Also fixed the test command.
Fixes https://github.com/google/iree/issues/2948
> Release inputs before closing the session.

- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/compiler/Dialect/Flow/Transforms/test/hlo_to_hlo_preprocessing.mlir
Part of #1583 and #1148. I think it can be a standalone pass. /cc @benvanik for visibility.
> Reorder BroadcastInDimOp and BinaryElementwiseOp

- iree/samples/vulkan/vulkan_inference_gui.cc
Startup logs look like this now:
```
iree\samples\vulkan\vulkan_inference_gui.cc:543] IREE runtime API version 0
iree\samples\vulkan\vulkan_inference_gui.cc:557] Creating Vulkan driver/device
iree\hal\vulkan\api.cc:289] Creating VulkanDevice...
iree\hal\vulkan\api.cc:299] Successfully created device 'GeForce RTX 2080 Ti'
iree\samples\vulkan\vulkan_inference_gui.cc:589] Loading simple_mul.mlir...
iree\samples\vulkan\vulkan_inference_gui.cc:601] Module loaded, have <3> exported functions:
iree\samples\vulkan\vulkan_inference_gui.cc:610]   0: 'simple_mul$raw' with <2> argument(s) and <1> result(s)
iree\samples\vulkan\vulkan_inference_gui.cc:610]   1: 'simple_mul' with <2> argument(s) and <1> result(s)
iree\samples\vulkan\vulkan_inference_gui.cc:610]   2: '__init' with <0> argument(s) and <0> …
```
> Log function metadata from bytecode module in vk sample.

- iree/compiler/Dialect/HAL/Target/LLVM/AOT/BUILD
- iree/compiler/Dialect/HAL/Target/LLVM/AOT/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/LLVM/AOT/LLVMAOTTarget.cpp
Add dynamic dialect registration for llvm AOT backend.
> Register dialects for dylib-llvm-aot target backend

- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/compiler/Dialect/Flow/Transforms/test/hlo_to_hlo_preprocessing.mlir
Followup from https://github.com/google/iree/pull/2991. /cc @benvanik for visibility.
> Reorder BroadcastInDimOp and ElementwiseOp

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
Fix set dynamic dim from MakeRankedShapeOp.
> Fix set dynamic dim from MakeRankedShapeOp.

- iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir
Add a test for set dynamic shape from MakeRankedShapeOp.
> Add a test for set dynamic shape from MakeRankedShapeOp.

- iree/hal/llvmjit/llvmjit_executable.cc
This improves debuggability here by outputting the actual erro messages
we get from LLVM.
> Forward error messages from JITing LLVM

- README.md
I always forget the commands for setting this up, and thought they'd be useful to others too.
> Add directions for re-cloning IREE to work on gh-pages

- iree/test/e2e/vulkan_specific/dot_general.mlir
- iree/test/e2e/xla_ops/dot_general.mlir
> Adding dot_general test to verify operation.

- integrations/tensorflow/e2e/BUILD
I tested that this is working on my machine in OSS and internally as well.
> Enable `fill_test.py` on `iree_vmla`

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Target/SPIRVCommon/SPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.h
Progress on https://github.com/google/iree/issues/1587
> Move references to HAL executables inside hal.device.switch ops.

- scripts/git/google_to_main.sh
- scripts/git/main_to_google.sh
- scripts/git/update_tf_submodule.sh
Add workaround for https://github.com/cli/cli/issues/1820 to our
integration scripting. There's something broken about detection for the
appropriate HEAD ref for the PR, so we set it explicitly.
> Workaround bug in gh cli

- CMakeLists.txt
- build_tools/cmake/external_cc_library.cmake
- build_tools/cmake/flatbuffer_c_library.cmake
- build_tools/cmake/flatbuffer_cc_library.cmake
- build_tools/cmake/iree_cc_binary.cmake
- build_tools/cmake/iree_cc_library.cmake
- build_tools/cmake/iree_cc_test.cmake
- build_tools/cmake/iree_copts.cmake
- build_tools/cmake/rebuild.sh
- docs/get_started/cmake_options_and_variables.md
Also tagging third-party dirs as SYSTEM (-Isystem).
> Forcing LLVM's rude forcing of /W4 and !NDEBUG off.

- scripts/update_op_coverage.py
> Add import utils to update_op_coverage.py

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
The `TestCase` class calls `__init__` before each unittest plus one additional time. With our current implementation this meant that we need to re-compile each model at least once for each backend, which greatly increased the runtime of tests like MobileBERT.
Thankfully this is still cleaner than what we had before.
> Use global variable to avoid recompilation

- integrations/tensorflow/e2e/README.md
> Update link to benchmarking doc in e2e readme.

- build_tools/bazel/iree.bazelrc
See https://github.com/tensorflow/tensorflow/commit/5aa11f9c5e7a6071f2d0a774c9e43d46be08ec78
> Add new Windows Bazel flags compatible with TensorFlow.

- iree/tools/iree-benchmark-module-main.cc
Follow up on comments in https://github.com/google/iree/pull/3377
> Use IREE_CHECK instead of assert.

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/einsum_dynamic_test.py
- integrations/tensorflow/e2e/einsum_static_test.py
- integrations/tensorflow/e2e/einsum_vector_test.py
Einsum isn't currently supported by IREE, but these tests should be helpful for enabling it.
> Add e2e tests for einsum

- scripts/get_e2e_artifacts.py
> Update get_e2e_artifacts to use new IREE flags

- integrations/tensorflow/e2e/slim_vision_models/BUILD
Removed comments since some of them regressed from fp errors to compiler errors, and vice versa.
> Update slim vision coverage

- iree/compiler/Dialect/VMLA/Conversion/ConversionTarget.cpp
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertHLOToVMLA.cpp
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/fft.mlir
- iree/compiler/Dialect/VMLA/IR/VMLAOps.td
(The actual Implementation for FftOp is still WIP)
> Create VMLA_FftOp and generate the lowering from VMLA_FftPseudoOp to it.

- integrations/tensorflow/e2e/iree_e2e_cartesian_product_test_suite.bzl
- integrations/tensorflow/e2e/keras/BUILD
Fixes a bug that crept into a merge, and adds error checking to prevent similar bugs from popping up.
> Fix keras BUILD file and add error checking.

- iree/compiler/Conversion/HLOToLinalg/test/fusion.mlir
- iree/compiler/Conversion/HLOToLinalg/test/pipeline_test.mlir
After patch https://reviews.llvm.org/D89002 landed some issues in IREE
can be closed. Doing so by adding the tests from those issues
Closes #3302
> Examples of fusions added to close some issues.

- docs/developing_iree/benchmarking.md
- docs/developing_iree/e2e_benchmarking.md
Mostly around controlling CPU configuration. Deleted some unnecessary
`chmod +x` and fixed some broken commands as well.
> Add more detail to Android benchmarking docs

- build_tools/cmake/iree_copts.cmake
> Fix link flags with tracing.

- integrations/tensorflow/e2e/BUILD
There was an issue #3507, and it's fixed in #3517
> Enable MobilerBert test on vulkan.

- scripts/get_e2e_artifacts.py
> Update test suites in get_e2e_artifacts.py

- iree/compiler/Conversion/LinalgToSPIRV/VectorToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/vector_to_gpu.mlir
Add patterns to lower some vector operations to a mix of standard
operations and vector operations that have a direct mapping to SPIR-V.
> Add patterns to vectorToGPU pass

- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/base/logging.cc
- iree/base/tracing.h
> Forward logging.cc log messages to Tracy.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/torch_index_select.mlir
Use extract_element op instead of load op, since it works in tensor's world. It will be lowered to a load op in iree-codegen-hlo-to-linalg-on-buffers pass.
> Move torch_index_select op lowering to Linalg on tensors.

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/CreateFuncsToInvokeExecOps.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineLargeConstantsPass.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/test/create_funcs_to_invoke_exec_ops.mlir
- iree/compiler/Translation/IREEVM.cpp
- iree/compiler/Translation/IREEVM.h
Fixes https://github.com/google/iree/issues/3384
> Add a translation to export all dispatch functions.

- bindings/python/build_defs.oss.bzl
- build_tools/bazel/iree.bazelrc
- iree/base/BUILD
This removes a ton of log spam from the Windows Bazel build.
> Rework windows Bazel config

- docs/developing_iree/developer_overview.md
- docs/developing_iree/testing_guide.md
Knew there would be some issues in https://github.com/google/iree/pull/3597 :P
> Fix CMake sample commands in documentation.

- scripts/utils.py
This replaces a custom regex-based solution
> Use bazel flags to silence logs

- docs/get_started/getting_started_windows_bazel.md
It would be nice to detect which version of msvc someone has, but I'm
not going to try to figure out how to do that :-D
> Add a note in Windows-Bazel guide for MSVC version config

- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_multipy.cmake
- docs/developing_iree/testing_guide.md
Follow-up to https://github.com/google/iree/commit/2e9aaa4dc0f44a18e739dba7a26f6366382a308f
> Switch : to / in more CMake tests names.

- experimental/ModelBuilder/test/BenchMatMulVectorGPU.cpp
- iree/compiler/Conversion/CodegenUtils/MatmulCodegenStrategy.cpp
> [ModelBuilder] Enable new unroll patterns for TransferRead and scf.for canonicalization

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/conv_test.py
- integrations/tensorflow/e2e/conv_transpose_test.py
- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertConvOps.cpp
- iree/compiler/Dialect/VMLA/IR/VMLAOps.td
- iree/hal/vmla/op_kernels.h
- iree/hal/vmla/op_kernels_generic.h
- iree/hal/vmla/op_kernels_test.cc
- iree/hal/vmla/vmla_module.cc
Includes conditionally disabling padding extraction.
> Support for transpose/dilated_lhs convolution for VMLA

- iree/compiler/Conversion/HLOToLinalg/test/pipeline_test.mlir
> Add test to verify support for fusion in Issue #3579

- iree/compiler/Dialect/Flow/Transforms/CreateBenchmarkFuncs.cpp
- iree/compiler/Dialect/Flow/Transforms/test/create_benchmark_funcs.mlir
If there are multiple blocks in a function, all the blocks should be
cloned with the correct mapping.
> Add support for creating benchmark functions that have multiple blocks.

- iree/compiler/Conversion/HLOToLinalg/Passes.cpp
Make sure all hal.load.tensor are unique
> Run CSE after FusionOnTensor

- .github/ISSUE_TEMPLATE/bug_report.md
Mainly to push people towards providing reproductions that don't
require using integrations.
> Create template for Bug Reports

- iree/compiler/Conversion/Common/LegalizeNumWorkgroupsFnPass.cpp
Allocas might end up in the function to compute the number of
workgroups as an artifact of the way the number of workgroups is
computed. These are eventually dead allocas, and can be removed. Add a
pattern to do this.
> Remove dead Alloca from function to compute number of workgroups.

- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
The `ConvertVMToEmitCPass` pass is restricted to a `vm.module` and was
not called nested.
> Fix vm-ir-to-c-module pass

- iree/compiler/Dialect/HAL/Target/LLVM/AOT/LinkerTool.cpp
- iree/hal/dylib/dylib_executable.cc
Found while testing https://github.com/google/iree/pull/3757
> Small fixes for LLVM AOT backend on Windows.

- .github/workflows/publish_docs.yml
- .github/workflows/update_llvm_dependent_submodules.yml
Issues and solution detailed in the links below.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
> Fix remaining github action environment failure issue

- .github/workflows/update_llvm_dependent_submodules.yml
Missing '|' to execute each command in sequence.
> Fixed yaml for synchronize submodules.

- WORKSPACE
- build_tools/docker/README.md
- build_tools/docker/bazel-python/Dockerfile
- build_tools/docker/bazel-tensorflow/Dockerfile
- build_tools/docker/cmake-python/Dockerfile
- build_tools/docker/manage_images.py
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-swiftshader/bindings/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-swiftshader/core/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-swiftshader/integrations/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-turing/integrations/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/android/arm64-v8a/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build_kokoro.sh
- integrations/tensorflow/e2e/keras/layers/BUILD
TensorFlow: `2.4.0.dev20200902 -> 2.5.0.dev20201116`
Numpy:  `1.18.5 -> 1.19.4`
Also updated the documentation for updating images / debugging unexpected behavior.
> Update tensorflow and numpy in docker

- third_party/half/LICENSE
- third_party/half/README.txt
- third_party/half/UPDATING.md
- third_party/half/half.hpp
Add half library to be able to use it for conversion between half and float in iree tools.
> Add Half library to third_party

- iree/base/wait_handle_impl.h
- iree/hal/metal/CMakeLists.txt
- iree/hal/metal/metal_command_buffer.mm
- iree/hal/metal/metal_kernel_library.mm
1. export iree::hal::metal::registration
2. there is no iree::base::memory
3. some syntax errors, e.g., undefined variable
> Fix MacOS builds after hack-and-slash PR

- .github/workflows/update_llvm_dependent_submodules.yml
Should fix usage https://github.com/google/iree/actions/runs/374897375
of disabled set-env and add-path commands.
> Upgrade PR action to v3

- docs/developing_iree/ccache.md
Mostly just to highlight the option for those who haven't used `watch` before :)
> Increase fidelity in ccache stat-monitoring example

- integrations/tensorflow/e2e/math/BUILD
Combined with https://github.com/tensorflow/tensorflow/commit/1f55ba5ab29a01edb76c3ef13946660c74040a68 fixes #4061.
> Enable tf.is_nan test with static shapes

- iree/testing/vulkan/iree-run-module-vulkan-gui-main.cc
Missed this on https://github.com/google/iree/pull/4130 since I wasn't building all targets (not tested on CI).
> Fix ImGui function in iree-run-module-vulkan-gui-main.

- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.h
- iree/compiler/Dialect/Flow/Transforms/FoldCompatibleDispatchRegions.cpp
- iree/compiler/Dialect/Flow/Transforms/test/fold_compatible_dispatch_regions.mlir
As discussed in https://github.com/google/iree/issues/3924
> Correct root op to be leaf op.

- .github/workflows/build_package.yml
- build_tools/cmake/configure_bazel.cmake
* Also reworks how cmake passes configuration to bazel, ensuring it builds with the same compiler.
> Configure the build_package workflow to use clang.

- docs/developing_iree/e2e_benchmarking.md
> Rename MobileNetV3 to MobileNetV3Small in docs

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/add.mlir
- iree/samples/emitc_modules/add.mlir
- Fix pass pipeline in conversion test
- Fix typo
> Fix emitc tests

- docs/get_started/index.md
Fixes https://github.com/google/iree/issues/4290
Untested, but the link is broken already, so #testinprod.
> Fix link to "Using IREE" page.

- iree/base/wait_handle_poll.c
Context: https://github.com/google/iree/pull/3743#discussion_r532778953
> Avoid `-Wreturn-type` in wait_handle_poll

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
SPIRVOpLowering is going away in upstream:
https://reviews.llvm.org/D94080
> [spirv] Replace SPIRVOpLowering with a local class

- iree/base/api.c
- iree/base/api.h
- iree/base/atomics.h
- iree/base/intrusive_list_ref_ptr.inc
- iree/base/intrusive_list_unique_ptr.inc
- iree/hal/api.c
- iree/task/list.h
> Rollup of required core changes for the HAL C rewrite

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM2.cpp
- iree/compiler/Conversion/LinalgToLLVM/LinalgBufferizePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/linalg_bufferize.mlir
Allow converting transfer ops on tensor to transfer ops on buffer.
> Add support for transfer ops bufferization

- bindings/python/pyiree/compiler2/core.py
- bindings/python/tests/compiler_core_test.py
> Pass iree-hal-target-backends argument properly.

- iree/compiler/Conversion/LinalgToSPIRV/test/batch_matmul_vectorization.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_gpu.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/linalg_tile_and_fuse.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/matmul_fused_vectorization.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/matmul_vectorization.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/pipeline_test.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/pipeline_test_cooperative_mat.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/split_dispatch_function.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/workgroup_memory_promotion.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/constant_ops.mlir
- iree/compiler/Dialect/VMLA/Conversion/HALToVMLA/test/interface_ops.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/broadcast_in_dim.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/concatenate.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/conv.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/dynamic_slice.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/fft.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/math_ops.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/reduce.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/reduce_window.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/reshape.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/scatter.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/slice.mlir
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/transpose.mlir
- iree/compiler/Dialect/VMLA/Conversion/StandardToVMLA/test/comparison_ops.mlir
- iree/compiler/Dialect/VMLA/Conversion/StandardToVMLA/test/constant_ops.mlir
- iree/compiler/Dialect/VMLA/Conversion/StandardToVMLA/test/math_ops.mlir
- iree/compiler/Dialect/VMLA/Transforms/test/transformation.mlir
- iree/test/e2e/models/unidirectional_lstm.mlir
- This is in preparation of https://reviews.llvm.org/D94200
> [NFC] Update IREE tests to use visibility keyword for functions

- CMakeLists.txt
- build_tools/third_party/mlir-hlo/CMakeLists.txt
> Switch CMake build to mlir-hlo submodule

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build_kokoro.sh
> [ci] More in NVIDIA driver info dump

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/common.cfg
> Fix kokoro build script redirection

- colab/mnist_training.ipynb
Didn't realize these could diverge.
> Fix colab-specific notebook name

- integrations/tensorflow/e2e/fft_test.py
- iree/compiler/Dialect/VMLA/Conversion/ConversionTarget.cpp
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertHLOToVMLA.cpp
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/test/fft.mlir
- iree/compiler/Dialect/VMLA/Conversion/VMLAToVM/ConvertVMLAToVM.cpp
- iree/compiler/Dialect/VMLA/IR/VMLAOps.td
- iree/compiler/Dialect/VMLA/Transforms/PreConversionLowering.cpp
- iree/compiler/Dialect/VMLA/Transforms/test/pre_conversion_lowering.mlir
- iree/compiler/Dialect/VMLA/vmla.imports.mlir
- iree/hal/vmla/op_kernels_fft.h
- iree/hal/vmla/op_module.cc
> E2E implementation of all remaining fft types

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/slice.mlir
- iree/compiler/Conversion/HLOToLinalg/test/subtensor.mlir
- Lower mhlo.slice op to subtensor op in HLOToLinalgOnTensors.cpp
- Lower subtensor op to subview op in HLOToLinalgOnBuffers.cpp
> Move mhlo.slice op lowering to tensors world.

- iree/compiler/Conversion/LinalgToSPIRV/VectorizeMemref.cpp
When vectorizing memref for GPU to use `vector<4xf32>` instead of
`f32`, we need to divide the `x` dimension by 4 so that we can
properly index into the buffer and avoid being out of bound.
Previously we divided by 1 because `vecMemrefElemSize` and
`writeElemSize` were always the same.
Also applied some refactoring to the pass.
> [codegen] Fix incorrect divisor for memref vectorization

- iree/hal/cts/BUILD
- iree/hal/cts/CMakeLists.txt
- iree/hal/cts/README.md
- iree/hal/cts/allocator_test.cc
- iree/hal/cts/buffer_mapping_test.cc
- iree/hal/cts/command_buffer_test.cc
- iree/hal/cts/semaphore_submission_test.cc
- iree/hal/cts/semaphore_test.cc
- iree/hal/device.c
More still to do (like https://github.com/google/iree/issues/4643), but this expands test coverage and starts to organize the tests by complexity and whether features are required or optional.
> Incremental improvements to the HAL CTS.

- bindings/tflite/testdata/BUILD
- bindings/tflite/testdata/CMakeLists.txt
Fixes https://github.com/google/iree/issues/4673
> Mark tflite testdata target as testonly.

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
- Move HLO -> HLO & Legalize workflow before LinalgOnTensors -> HLO
- Run canonicalization after HLO -> HLO.
- Create xla_ops tests.
> Add LinalgOnTensors xla_ops tests

- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/Target/VMLA/test/linking.mlir
Fixes https://github.com/google/iree/issues/4690
> Check push bindings when comparing HAL interface ops.

- iree/samples/vulkan/vulkan_inference_gui.cc
- iree/testing/vulkan/iree-run-module-vulkan-gui-main.cc
- iree/testing/vulkan/vulkan_gui_util.h
Following https://github.com/google/iree/pull/4702
Should just port these to pure C, or delete them. I like them though D:
> Fix issues with linking Vulkan GUI applications.

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
- Run DecomposeHLOClamp and enable `clamp.mlir` test for linalg-on-tensors path.
> Run createDecomposeHLOClampPass prior to createDispatchLinalgOnTensor

- iree/test/e2e/tosa_ops/ceil.mlir
- iree/test/e2e/tosa_ops/exp.mlir
- iree/test/e2e/tosa_ops/floor.mlir
- iree/test/e2e/tosa_ops/greater.mlir
- iree/test/e2e/tosa_ops/greater_equal.mlir
- iree/test/e2e/tosa_ops/log.mlir
- iree/test/e2e/tosa_ops/maximum.mlir
- iree/test/e2e/tosa_ops/minimum.mlir
log, exp, maximum, minimum, comparison, ceil and floor
> Add tests for lowerings from tosa to linalg

- iree/hal/BUILD
- iree/hal/CMakeLists.txt
> Remove unneeded ref_ptr dep.

- integrations/tensorflow/CMakeLists.txt
- integrations/tensorflow/iree_tf_compiler/BUILD
- integrations/tensorflow/iree_tf_compiler/iree-import-tflite-main.cpp
Required dialects were not import for the tflite importer.
> Fixed iree tflite import to include required dialects.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
The op is no longer used on the MHLO -> Linalg lowering. A linalg.fill
is used instead.
> Drop lowering for tensor::GenerateOp.

- bindings/python/pyiree/rt/status_utils.cc
> Python error messages print the full IREE status if available.

- iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp
Checking the current working directory for linker tools in addition to the environment path offers more flexibility when using this code from downstream projects and other build environments.
Also resolved a TODO to make the path check cross platform using LLVM utils and fixed "lld.ld" to "ld.lld".
> Check cwd for Unix linker tools before path.

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/hal_interface_bindings.mlir
- iree/test/e2e/regression/dynamic_abs.mlir
- iree/test/e2e/regression/dynamic_add.mlir
- iree/test/e2e/regression/dynamic_dot.mlir
This should fix https://github.com/google/iree/issues/4733.
> Populate dynamic shaped memref descriptor offset value

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark.yml
This phone is borked and needs manual intervention. See
https://github.com/google/iree/issues/4861
> Disable benchmark on phone with ADB auth issues

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
> [buildkite] Disable lost Pixel 4

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/test/e2e/models/fullyconnected.mlir
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
> Enable all tests that run on CPU with Linalg on tensors path with GPU as well.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/reduce_window.mlir
- iree/test/e2e/xla_ops/reduce_window.mlir
They were initialized to zero buffers. Fixes them to be the initial
value.
Fixes https://github.com/google/iree/issues/2136
> Fix the initialization issue in pooling ops.

- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
> Tighten up the GCC fix to just disable devirtualization.

- iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
This was causing random failure whith asan
Fixes https://github.com/google/iree/issues/4944
> Fix multi-threading issue when registering LLVMDialect translation

- build_tools/bazel_to_cmake/bazel_to_cmake.py
Follow-up on
https://github.com/google/iree/pull/4917#discussion_r583032192. Better
matches output suggested in https://github.com/google/iree/issues/4282.
Incidentally fixes a bug in printing I introduced with
https://github.com/google/iree/pull/4943/ where preview mode wouldn't
print the header and footer.
Also moves some stuff around (like moving more out of the try-except
block).
> [bazel_to_cmake] Distinguish noop from success

- build_tools/github_actions/build_dist.py
Part of https://github.com/google/iree/issues/4963
> Add `--keep_going` to distribution build

- iree/test/e2e/tosa_ops/reshape.mlir
Validates that tosa.reshapes numerically correct results.
> Added tosa.reshape execution test

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/test/e2e/tosa_ops/const.mlir
- iree/test/e2e/tosa_ops/if.mlir
- iree/test/e2e/tosa_ops/while.mlir
tosa.const, tosa.cond_if, and tosa.while were added to MLIR. Added requires lowerings and tests
for each op.
> Added TOSA const, if, and while passes to pipeline

- docs/developing_iree/profiling_vulkan_gpu.md
> Update vulkan profiling doc.

- iree/compiler/Conversion/LinalgToLLVM/ConvImg2ColMatmulConversion.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/test/conv_img2col.mlir
Part of https://github.com/google/iree/issues/4908
> Migrate linalg.conv to linalg.conv_2d_input_nhwc_filter_hwcf in Img2Col.

- build_tools/bazel/build_core.sh
- build_tools/cmake/test.sh
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
Those are disabled by default in CI until a CUDA system is setup.
> Enable some E2E tests for CUDA

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark.yml
The phone is updated to Android 11.
> [buildkite] Use S20 with Android 11

- iree/test/e2e/tosa_ops/transpose.mlir
Execution tests for the tosa.transpose operation using the linalg codegen
backend.
> Added tests for tosa.transpose

- docs/design_docs/cuda_backend.md
Add some basic doc for the CUDA backend and gives instruction to reproduce simple case.
> Start doc for CUDA backend

- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
> Fix CModuleTarget canonicalizer module

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
In LinalgBufferizePass, we first create memref counterparts for all
hal.interface.binding.subspan ops. So for flow.dispatch.tensor.store,
the target will always have a mapped-to value. If its value's
producer is a Linalg op, the Linalg op will perform operations
in place when converted to buffers. For such cases we can remove
the flow.dispatch.tensor.store op. Otherwise, we cannot, as we may
see the degenerated case where we immediately store after loading
a buffer.
> [CodeGen] Avoid eliminating output store unconditionally

- build_tools/github_actions/build_dist.py
Hopefully this is the last one 🙏 
https://github.com/google/iree/runs/2143948191?check_suite_focus=true#step:9:397
> Remove lingering rt package reference

- iree/compiler/Conversion/Common/Transforms.cpp
- iree/test/e2e/models/BUILD
- iree/test/e2e/models/CMakeLists.txt
> Revert "Enable MobileBert on GPU for the linalg on tensors path."

- iree/compiler/Dialect/Flow/Utils/WorkloadUtils.cpp
- iree/compiler/Dialect/HAL/Transforms/BUILD
- iree/compiler/Dialect/HAL/Transforms/CMakeLists.txt
- iree/compiler/Dialect/HAL/Transforms/MaterializeInterfaces.cpp
- iree/compiler/Dialect/HAL/Utils/BUILD
- iree/compiler/Dialect/HAL/Utils/CMakeLists.txt
- iree/compiler/Dialect/HAL/Utils/TypeUtils.cpp
- iree/compiler/Dialect/HAL/Utils/TypeUtils.h
- iree/compiler/Utils/BUILD
- iree/compiler/Utils/CMakeLists.txt
> Shuffling around/removing some HLO deps.

- iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp
Fixes https://github.com/google/iree/issues/4959
I don't fully understand the static/shared distinction between these platforms/toolchains, particularly while we still have some calls to functions like `floorf`, but our tests seem to build+run+pass on macOS and Linux with these changes.
> Adjust UnixLinkerTool flags used for Apple targets.

- .github/workflows/update_llvm_dependent_submodules.yml
> Set author to match committer for llvm submodule update action.

- iree/compiler/Conversion/HLOToLinalg/test/linalg_tensor_to_buffer.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/linalg_tile_and_fuse.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/split_dispatch_function.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/workgroup_memory_promotion.mlir
- iree/test/e2e/llvm_specific/conv.mlir
- iree/test/e2e/xla_ops/convolution.mlir
I fixed some testcases with verification prototype. The prototype is in https://reviews.llvm.org/D98390 .
I think this change should be merged before the verification is landed since it might interrupt building the entire IREE..
> Fixed some testcases with static verification prototype for linalg operations

- iree/compiler/Conversion/LinalgToNVVM/BUILD
- iree/compiler/Conversion/LinalgToNVVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToNVVM/KernelConfig.cpp
- iree/compiler/Conversion/LinalgToNVVM/KernelConfig.h
- iree/compiler/Conversion/LinalgToNVVM/Passes.cpp
- iree/compiler/Conversion/LinalgToNVVM/Passes.h
- iree/compiler/Conversion/LinalgToNVVM/TileAndDistribute.cpp
- iree/compiler/Conversion/LinalgToNVVM/test/BUILD
- iree/compiler/Conversion/LinalgToNVVM/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToNVVM/test/distribute_to_thread.mlir
- iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
Also start adding framework to query tile size and workgroup size for
different ops
> [CUDA codegen] Add pass to tile and distribute linalg ops to threads

- iree/compiler/Conversion/LinalgToLLVM/LinalgTileAndVectorizePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
This enables vectorization when problem size is dividable by tilling sizes. With this change I verified linalg-on-tensors matmul perofrmance is on bar with linalg-on-buffers.
> Canonicalize affine min before applying tile-and-vecotrize passes

- iree/compiler/Dialect/Vulkan/Utils/test/BUILD
- iree/compiler/Dialect/Vulkan/Utils/test/CMakeLists.txt
- iree/compiler/Dialect/Vulkan/Utils/test/target_env_conversion_linalg_on_tensors.mlir
Part of https://github.com/google/iree/issues/5155
> Add a target_env_conversion test for Linalg on tensors.

- iree/compiler/Dialect/Flow/IR/FlowOpUtils.cpp
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups_folding.mlir
We cannot just simply inline and replace all users for the
DispatchWorkgroupsOp if it is an argument that can be written;
for example, the region might perform work after loading a initial
constant from the argument and then write back.
> Don't inline block arguments that can be written

- iree/base/logging.h
- iree/hal/vulkan/BUILD
- iree/hal/vulkan/CMakeLists.txt
- iree/hal/vulkan/internal_vk_mem_alloc.cc
Progress on https://github.com/google/iree/issues/3848
> Drop absl logging and flat_hash_map.

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/canonicalize_interface_load_store.mlir
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
- iree/compiler/Conversion/LinalgToNVVM/test/pipeline_test.mlir
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.h
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups.mlir
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups_folding.mlir
- iree/compiler/Dialect/Flow/Transforms/DestructiveUpdateUtils.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/Flow/Transforms/test/outline_dispatch_regions2.mlir
- iree/compiler/Dialect/HAL/Target/CUDA/test/smoketest.mlir
- iree/compiler/Dialect/HAL/Transforms/test/materialize_interfaces.mlir
Use OffsetSizeAndStrideOpInterface for flow.dispatch.tensor.{load|store} ops to enable mixed static / dynamic operands.
> Add mixed static-dynamic arguments interface

- build_tools/embed_data/BUILD
- build_tools/embed_data/CMakeLists.txt
- build_tools/embed_data/generate_cc_embed_data_main.cc
- iree/hal/buffer_view.cc
- iree/modules/vmla/BUILD
- iree/modules/vmla/CMakeLists.txt
- iree/modules/vmla/op_kernels_generic.h
Progress on https://github.com/google/iree/issues/3848
> Drop absl flat_hash_set and some unused includes.

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
With the shape carrying op interface these no longer show up.
> Remove handling of shape dialect in flow->hal stream conversion.

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
- Forward buffer assigned to tensor.cast output to its input
> Handle tensor.cast bufferization in LinalgBufferizePass

- iree/task/task.c
> Adding a color to dispatch slice/shard trace zones.

- iree/compiler/Conversion/HLOToLinalg/FusionOfTensorOps.cpp
- This enables spliting the dispatch region into a parallel producer that is getting vectorized and a reduction consumer that is running without vectorization (for now).
> Disable fusing linalg generic ops with reduction iterators

- iree/compiler/Bindings/TFLite/Transforms/test/materialize_shape_support.mlir
- iree/compiler/Dialect/IREE/IR/IREEDialect.cpp
- iree/compiler/Dialect/IREE/IR/IREEOps.cpp
- iree/compiler/Dialect/IREE/IR/IREEOps.td
- iree/compiler/Dialect/IREE/IR/IREETypes.cpp
- iree/compiler/Dialect/IREE/IR/IREETypes.h
- iree/compiler/Dialect/IREE/IR/test/BUILD
- iree/compiler/Dialect/IREE/IR/test/CMakeLists.txt
- iree/compiler/Dialect/IREE/IR/test/list_ops.mlir
- iree/compiler/Dialect/VM/Conversion/IREEToVM/ConvertIREEToVM.cpp
- iree/compiler/Dialect/VM/Conversion/IREEToVM/test/BUILD
- iree/compiler/Dialect/VM/Conversion/IREEToVM/test/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/IREEToVM/test/list_ops.mlir
- iree/compiler/Dialect/VM/Conversion/TypeConverter.cpp
- iree/compiler/Dialect/VM/IR/VMBase.td
- iree/compiler/Dialect/VM/IR/VMDialect.cpp
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/VMTypes.cpp
- iree/compiler/Dialect/VM/IR/test/list_ops.mlir
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- iree/vm/bytecode_dispatch.c
- iree/vm/bytecode_module.c
- iree/vm/test/BUILD
- iree/vm/test/CMakeLists.txt
- iree/vm/test/list_ops.mlir
- iree/vm/test/list_variant_ops.mlir
This was only half plumbed through before and now it's about 85% plumbed.
Probably.
> Adding support for !vm.list<?> variant types.

- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
> Remove inliner from linalg on tensors pass form LLVM backend

- docs/get_started/getting_started_python.md
Fixes https://github.com/google/iree/issues/5092
> Mention supported pip versions in getting_started_python.

- iree/hal/allocator.h
- iree/hal/allocator_heap.c
- iree/modules/hal/hal_module.c
- iree/vm/builtin_types.h
- iree/vm/bytecode_module.c
This adds the flags and populates them but the first real usage will come in #5472.
> Small improvements to enable buffer aliasing/importing.

- iree/compiler/Dialect/Flow/Transforms/ConvertToFlowTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/test/convert_to_flow_tensor_ops.mlir
Fixes https://github.com/google/iree/issues/5476
> Add support for converting rank-reducing subtensor ops to Flow dialect

- iree/compiler/Conversion/Common/BUILD
- iree/compiler/Conversion/Common/CMakeLists.txt
- iree/compiler/Conversion/Common/FlattenMemRefSubspanPass.cpp
- iree/compiler/Conversion/Common/Passes.h
- iree/compiler/Conversion/Common/test/BUILD
- iree/compiler/Conversion/Common/test/CMakeLists.txt
- iree/compiler/Conversion/Common/test/flatten_memref_subspan.mlir
- iree/compiler/Conversion/LinalgToSPIRV/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/CMakeLists.txt
- iree/compiler/Conversion/LinalgToSPIRV/Passes.h
- iree/compiler/Conversion/LinalgToSPIRV/test/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/test/CMakeLists.txt
- iree/compiler/Conversion/init_conversions.h
> Moving FlattenMemRefSubspanPass to Common/.

- iree/base/api.h
- iree/base/internal/debugging.h
- iree/hal/local/event_pool.c
- iree/hal/local/executable_library_test.c
- iree/hal/local/inline_command_buffer.c
- iree/hal/local/task_command_buffer.c
- iree/hal/resource.h
- iree/task/executor.c
- iree/task/pool.c
- iree/task/scope.c
- iree/task/submission.c
- iree/task/task.c
- iree/task/topology.c
- iree/task/worker.c
This is just a starting point for the macros based on what was present;
code golf will happen to make them better as part of #2843.
> Exposing IREE_ASSERT as part of the public API.

- build_tools/mako/configuration.py
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/materialize_launch_configuration.mlir
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_elementwise.mlir
> Enable dispatching linalg.generic ops into workgroups and set tiling paramters for LLVM backend

- iree/test/microbenchmarks/mhlo_conv.mlir
- iree/test/microbenchmarks/mhlo_dot.mlir
- iree/test/microbenchmarks/mhlo_fft_abs.mlir
- Depthwise convolutions
- O(N^2) like matmul (or say matvec).
- RFFT
> Add more microbenchmarks to IREE.

- build_tools/mako/config/mobile-bert-pixel4.config
- build_tools/mako/config/mobile-bert-s20.config
- build_tools/mako/config/mobilenet-v2-pixel4.config
- build_tools/mako/config/mobilenet-v2-s20.config
- build_tools/mako/configuration.py
Fixes https://github.com/google/iree/issues/4752
> Add CPU multi-threaded benchmarks to Mako benchmark targets.

- iree/compiler/Conversion/CodegenUtils/FunctionUtils.h
- iree/compiler/Conversion/Common/LinalgRewriteDestructiveUpdatesPass.cpp
- iree/compiler/Conversion/Common/test/linalg_rewrite_destructive_updates.mlir
> NFC: delete unused operand_result_index attribute

- build_tools/mako/configuration.py
Fixes https://github.com/google/iree/issues/5634
> Only add operand-fusion to MobileNetV2.

- README.md
Thanks, @MaheshRavishankar and @asaadaldien!
Signed-off-by: xgupta <shivam98.tkg@rediffmail.com>
> [Talks] 2020-08-20: IREE CodeGen; MLIR ODM

- build_tools/mako/configuration.py
- iree/hal/dylib/registration/BUILD
- iree/hal/dylib/registration/CMakeLists.txt
- iree/hal/dylib/registration/driver_module.c
- iree/task/BUILD
- iree/task/CMakeLists.txt
- iree/task/api.c
- iree/task/api.h
Progress on #4298: cleaning up HAL driver registration.
> Adding iree_task_executor_create_from_flags.

- iree/compiler/Conversion/LinalgToLLVM/LinalgTileAndVectorizePass.cpp
Will need this as a prerequisite for generalized vectoriztion in [D101165](https://reviews.llvm.org/D101165)
> Add vector transfer canonicalization patterns

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/VectorizeMemrefLoadStorePass.cpp
- iree/compiler/Dialect/IREE/IR/IREEOps.td
It has done its service now. RIP. :)
> Retire iree.placeholder op

- iree/compiler/Conversion/HLOToLinalg/FusionOfTensorOps.cpp
This allow more fusion in MobileNet
> Integrate pattern to push reshape down.

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
The device is going to be offline for a while.
> Temporary disable S10 on CI

- iree/test/e2e/models/BUILD
- iree/test/e2e/models/CMakeLists.txt
Delete by accident in PR #5446
> Add back MobileBert and MobileNet tests accidentally deleted.

- iree/compiler/Dialect/HAL/Conversion/TypeConverter.cpp
* These were showing up in custom_modules_test.mlir when using the native ABI and failing the TensorType assert.
* I'm not sure this is the right place to be fixing this but seemed right to me.
> Convert buffer_view -> buffer in HAL type converter.

- bindings/tflite/testdata/BUILD
- bindings/tflite/testdata/CMakeLists.txt
> Disable native bindings when targeting the tflite bindings.

- .github/workflows/publish_website.yml
> Pass write access token to publish_website workflow.

- CMakeLists.txt
- bindings/tflite/CMakeLists.txt
- bindings/tflite/testdata/CMakeLists.txt
- docs/developers/get_started/cmake_options_and_variables.md
- iree/runtime/demo/BUILD
- iree/runtime/demo/CMakeLists.txt
- iree/runtime/testdata/BUILD
- iree/runtime/testdata/CMakeLists.txt
Fixes https://github.com/google/iree/issues/5799
Tested a configure + build all with
```
"-DIREE_BUILD_TESTS=ON",
"-DIREE_BUILD_COMPILER=OFF",
"-DIREE_ENABLE_MLIR=OFF",
"-DIREE_BUILD_PYTHON_BINDINGS=OFF",
"-DIREE_BUILD_SAMPLES=OFF",
```
> A few CMake config fixes.

- docs/website/mkdocs.yml
- docs/website/overrides/404.html
Demo: https://scotttodd.github.io/iree/404_page_that_does_not_exist
404.html forked from https://github.com/squidfunk/mkdocs-material/blob/master/material/404.html
> Fix website 404 relative paths and customize the 404.html page.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
See https://github.com/google/iree/issues/5809
Progress on https://github.com/google/iree/issues/5808
> Workaround conflicting concatenate lowerings with a PatternBenefit.

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
Changes to get the bufferization pass to handle some cases arisign
from padding and promotion.
Fixes #5821 , #5521
> Miscellaneous fixes to Bufferization pass.

- iree/compiler/Conversion/LinalgToNVVM/KernelConfig.cpp
- iree/compiler/Conversion/LinalgToNVVM/Passes.cpp
- iree/compiler/Conversion/LinalgToNVVM/TileAndDistribute.cpp
- iree/compiler/Conversion/LinalgToNVVM/test/pipeline_test.mlir
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
Add simple scalar support for convolution ops going through tiling and
distribute to threads.
> [CUDA codegen] Add basic support for convolution

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
The bug it exposed has been fixed in #5847
> Re-commit "Fix how to get the original shape in generic op launch config. #5603"

- docs/developers/get_started/getting_started_tensorflow.md
forget to remove in https://github.com/google/iree/commit/29fdc8c757340ce394dd1067e1f80d358656416c
> [NFC] Remove renaming TODO in getting_started_tensorflow.md

- iree/samples/vision/CMakeLists.txt
- iree/samples/vision/mnist_test.txt
A followup PR for https://github.com/google/iree/pull/5655#discussion_r629466909
> Add test for iree-run-mnist-module with the default image

- iree/compiler/Dialect/VM/Conversion/StandardToVM/BUILD
- iree/compiler/Dialect/VM/Conversion/StandardToVM/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/control_flow_ops.mlir
> Add std.assert -> vm.fail lowering.

- docs/website/docs/bindings/python.md
- docs/website/docs/building-from-source/android.md
- docs/website/docs/building-from-source/getting-started.md
- docs/website/docs/building-from-source/optional-features.md
- docs/website/docs/index.md
* Clarify unchecked "supported" platforms/configs (this is still fuzzy - open to suggestions)
* Rename "Linux" to "Linux and MacOS" in a few places
* Suggest `-DCMAKE_BUILD_TYPE=RelWithDebInfo` in CMake configure commands
> Clarify documentation and suggest using RelWithDebInfo.

- docs/website/overrides/404.html
A few people have been asking where several pages went :)
> Add an announcement to the 404 page about the website redesign.

- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
This makes us easier to track and add tests.
> [Cleanup] Refactor BUILD file.

- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
- iree/base/internal/wait_handle_test.cc
- iree/base/testing/dynamic_library_test.cc
Part of https://github.com/google/iree/issues/5715
> Fix leaks from not freeing status in tests

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
The toplogical sort of the inlined operations needs to account for
operations that are outside of the dispatch region but are not
inlined.
> Fix ordering of inlined operations to ignore ops that are not inlined.

- README.md
- docs/website/docs/index.md
* Given the increased focus/interest in more datacenter grade targets (CUDA/ROCM), include verbiage about datacenter use cases.
* Clarify that IREE is also a runtime.
> Clarify project description.

- iree/compiler/Conversion/LinalgToLLVMGPU/KernelConfig.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/VectorizationPass.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/test/distribute_to_thread.mlir
- iree/compiler/Conversion/LinalgToLLVMGPU/test/nvvm_pipeline_test.mlir
Serialize pure reduction and skip vectorization for linalg generic with
reduction loops.
Also pick the right root when linalg generic is fused with a fill op.
> [CUDA] Fix bugs in kernel config

- CMakeLists.txt
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- iree/compiler/Dialect/HAL/Target/ROCM/BUILD
- iree/compiler/Dialect/HAL/Target/ROCM/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.h
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTargetUtils.cpp
-Generate object + Link with bitcode
-ld.lld link object to generate code object
-Added Target Chip and Link Bitcode Option for ROCm
> Assemble, Linking BC, LLD Link in ROCm

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
Reverts google/iree#6041
The test failed after rebasing on main branch.
> Revert "Relax DispatchLinalgOnTensors pass to clone ops in differnt blocks."

- iree/compiler/Dialect/Flow/Transforms/ConvertToFlowTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/test/convert_to_flow_tensor_ops.mlir
The current conversion of subtensor and subtensor_insert assumed
incorrectly that the leading unit-dimensions can be dropped. These ops
can drop any of the unit dims. Update the conversion to flow ops to
handle these cases.
> Fix handling of rank-reduced version of subtensor and subtensor_insert

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
Resubmit https://github.com/google/iree/pull/6041
The issue was the order of inlining constants, replaced the `CHECK`s with `CHECK-DAG`s.
> Relax DispatchLinalgOnTensors pass to clone ops in differnt blocks.

- integrations/tensorflow/e2e/math/BUILD
- integrations/tensorflow/e2e/math/CMakeLists.txt
Depends on https://reviews.llvm.org/D103635
Fixes #6076
> Enable atanh test.

- iree/hal/cuda/graph_command_buffer.c
> Avoid variable size C array in CUDA hal

- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/compiler/Dialect/Flow/Transforms/test/hlo_to_hlo_preprocessing_canoncalize_dot_general.mlir
This also refactors some utils and fixes typos in the tests.
Fixes https://github.com/google/iree/issues/6105
> Extend TransposeGenericDotGeneral to handle ranks that more than three

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/LinalgToLinalg/Conv2D1x1ToMatmul.cpp
- iree/compiler/Conversion/LinalgToLinalg/Conv2DToImg2Col.cpp
- iree/compiler/Conversion/LinalgToSPIRV/ConcretizeTileAmongWorkgroupsPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToVector/VectorizeConv.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
The StructuredOpInterface was updated for more limited operations. Updated
uses within iree for the more limited operand set.
> [NFC] Updated for StructuredOpInterface refactor

- build_tools/kokoro/gcp_ubuntu/cmake/linux/riscv64/test.sh
- docs/developers/design_docs/cuda_backend.md
- docs/developers/developing_iree/benchmarking.md
- docs/developers/developing_iree/developer_overview.md
- docs/developers/developing_iree/profiling_vulkan_gpu.md
- docs/developers/get_started/getting_started_android_cmake.md
- docs/developers/get_started/getting_started_linux_bazel.md
- docs/developers/get_started/getting_started_linux_cmake.md
- docs/developers/get_started/getting_started_linux_vulkan.md
- docs/developers/get_started/getting_started_macos_bazel.md
- docs/developers/get_started/getting_started_macos_cmake.md
- docs/developers/get_started/getting_started_riscv_cmake.md
- docs/developers/get_started/getting_started_windows_bazel.md
- docs/developers/get_started/getting_started_windows_cmake.md
- docs/developers/get_started/getting_started_windows_vulkan.md
- docs/website/docs/building-from-source/android.md
- docs/website/docs/deployment-configurations/cpu-dylib.md
- docs/website/docs/deployment-configurations/gpu-vulkan.md
- iree/samples/models/simple_abs.mlir
- iree/tools/test/iree-benchmark-module.mlir
- iree/tools/test/iree-run-mlir.mlir
- iree/tools/test/iree-run-module.mlir
Reflect changes introduced in https://github.com/google/iree/pull/6030
> Update docs to add `input_type` flag

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
This is sort of stable as it has been running for
many commits. Committing now to avoid always
updating in the Buildkite UI.
> [ci] Commit pipeline steps for iree-benchmark

- bindings/tflite/model.c
> Check fread error in tflite bindings.

- bindings/python/iree/runtime/system_api_test.py
- bindings/python/tests/compiler_core_test.py
- integrations/tensorflow/iree_tf_compiler/TF/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TF/SavedModelToIreeABI.cpp
- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-tf-opt-main.cpp
- iree/compiler/Dialect/Flow/Transforms/ExportBenchmarkFuncs.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Conversion/IREEToHAL/ConvertIREEToHAL.cpp
- iree/compiler/Dialect/HAL/Conversion/IREEToHAL/ConvertIREEToHAL.h
- iree/compiler/Dialect/HAL/Conversion/StandardToHAL/ConvertStandardToHAL.cpp
- iree/compiler/Dialect/HAL/Conversion/StandardToHAL/test/structural_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/TypeConverter.cpp
- iree/compiler/Dialect/HAL/Transforms/ConvertToHAL.cpp
- iree/compiler/Dialect/Modules/Strings/IR/Dialect.cc
- iree/compiler/Dialect/Modules/TensorList/IR/TensorListDialect.cpp
- iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- iree/compiler/Translation/IREEVM.cpp
- iree/samples/custom_modules/custom_modules_test.cc
- iree/test/e2e/regression/BUILD
- iree/test/e2e/regression/CMakeLists.txt
- iree/test/e2e/xla_ops/convert.mlir
- iree/vm/ops.h
* TF passes changed to enable native ABI/disable SIP.
* HLO pass added to enable native ABI.
* IREEVM flags flipped.
> Flip flags to enable IREE native ABI.

- bindings/python/CMakeLists.txt
- bindings/python/iree/jax/CMakeLists.txt
- bindings/python/iree/jax/setup.py.in
- bindings/python/iree/jax/version.py.in
- build_tools/cmake/iree_python.cmake
* Will set it up to build in releases in a followup.
> Add proper package configuration for iree.jax Python package.

- integrations/tensorflow/iree_tf_compiler/iree-tf-opt-main.cpp
* There are a lot of problems with our TF reproducers. This at least gets the passes in place for ~the first half of it.
> Add some iree-tf-opt pass registrations.

- docs/website/docs/ml-frameworks/tensorflow-lite.md
Closes https://github.com/google/iree/issues/5455
> Add initial documentation for TFLite frontend

- iree/compiler/InputConversion/MHLO/BroadcastingToLinalgPatterns.cpp
- iree/compiler/InputConversion/MHLO/test/broadcasting.mlir
This doesn't do a lot yet as there are multi-part upstream changes that need to land in order for things to land on this op.
> Add a default lowering for mhlo.dynamic_reshape.

- iree/compiler/Translation/IREEVM.cpp
Only `translateFromMLIRToVMCModuleWithFlags()` is needed and we can call
`translateFromMLIRToVM()` directly as
`translateFromMLIRToVMBytecodeModuleWithFlags()` does.
> Drop `translateFromMLIRToVMCModule()`

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark.yml
- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
The phone is currently offline.
> Disable tests and benchmark on S20 phone.

- iree/samples/simple_embedding/README.md
Part of https://github.com/google/iree/issues/6327
> Add README to `iree/samples/simple_embedding`

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark.yml
- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
This reverts commit 4fa49ec6d90d49dbf29d72b64da47fca5fc40c73.
> Bring back testing and benchmarking on Mali GPU

- build_tools/docker/cmake-riscv/Dockerfile
- build_tools/docker/prod_digests.txt
- build_tools/kokoro/gcp_ubuntu/cmake/linux/riscv64/build_kokoro.sh
Add rv32 newlib toolchain
Part of https://github.com/google/iree/issues/6322
> Update cmake-riscv docker

- iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
The previous code was unconditionally accessing the bitcode module
without first checking the llvm::Expected success code. In debug builds
this caused an abort() because Expected expects that you check the result.
> Fixing CUDA bitcode linking.

- iree/compiler/Codegen/LLVMCPU/BUILD
- iree/compiler/Codegen/LLVMCPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/InputConversion/MHLO/Passes.cpp
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
Fixes https://github.com/google/iree/issues/6154
> Plumb sort op support through LLVM CPU pipeline.

- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtBase.td
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtInterfaces.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir
- iree/compiler/Dialect/LinalgExt/IR/test/roundtrip.mlir
- iree/compiler/Dialect/LinalgExt/Transforms/test/convert_to_loops.mlir
- iree/compiler/InputConversion/MHLO/test/convert_and_distribute_mhlo_to_linalg_ext.mlir
Also some minor changes
- move some checks to tablegen
- add some extra verifications to the Interface.
- move the ops to use declerative assembly format.
> Add linalg_ext.scatter operation.

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/ConvertConv2DToImg2ColPass.cpp
- iree/compiler/Dialect/Flow/Transforms/test/conv2d_to_img2col.mlir
This reverts commit c751d12 to rollforward https://github.com/google/iree/pull/6393, with build fixes.
> Rollforward "linalg.depthwise_conv2d -> img2col with batch_matvec".

- docs/website/docs/deployment-configurations/bare-metal.md
- docs/website/mkdocs.yml
Part of https://github.com/google/iree/issues/6327
> Add web doc for bare-metal codegen/run

- iree/compiler/Utils/BUILD
- iree/compiler/Utils/CMakeLists.txt
- iree/compiler/Utils/TracingUtils.cpp
- iree/compiler/Utils/TracingUtils.h
Fixes https://github.com/google/iree/issues/6404
Sample screenshot (bert + llvmaot):
> Fix compiler tracing instrumentation when using multithreading.

- build_tools/bazel/iree_tablegen_doc.bzl
- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- iree/compiler/Codegen/BUILD
- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Dialect/Flow/IR/BUILD
- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/HAL/IR/BUILD
- iree/compiler/Dialect/IREE/IR/BUILD
- iree/compiler/Dialect/LinalgExt/IR/BUILD
- iree/compiler/Dialect/LinalgExt/Transforms/BUILD
- iree/compiler/Dialect/Modules/Check/IR/BUILD
- iree/compiler/Dialect/Modules/VMVX/IR/BUILD
- iree/compiler/Dialect/Shape/IR/BUILD
- iree/compiler/Dialect/VM/IR/BUILD
- iree/compiler/Dialect/Vulkan/IR/BUILD
- iree/compiler/InputConversion/Common/BUILD
- iree/compiler/InputConversion/MHLO/BUILD
- iree/compiler/InputConversion/TOSA/BUILD
- iree/samples/custom_modules/dialect/BUILD
This encapsulates includes and dependencies within a rule.
> Migrate to td_library

- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertExecutableOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/executable_ops.mlir
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/Transforms/BUILD
- iree/compiler/Dialect/VM/Transforms/CMakeLists.txt
- iree/compiler/Dialect/VM/Transforms/DeduplicateRodata.cpp
- iree/compiler/Dialect/VM/Transforms/HoistInlinedRodata.cpp
- iree/compiler/Dialect/VM/Transforms/Passes.cpp
- iree/compiler/Dialect/VM/Transforms/Passes.h
- iree/compiler/Dialect/VM/Transforms/test/BUILD
- iree/compiler/Dialect/VM/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/VM/Transforms/test/deduplicate_rodata.mlir
(workaround for #1144 not existing to handle this generically)
> Adding vm.rodata deduplication.

- iree/vm/stack.c
They almost always then trace themselves, leading to additional overhead.
The VM trace functions are fully dynamic and have a much higher overhead
than a normal trace zone that can cache its source location.
> Hiding tracing zones for imported VM functions.

- bindings/python/iree/compiler/tf.py
- integrations/tensorflow/bindings/python/iree/tf/support/module_utils.py
- integrations/tensorflow/iree_tf_compiler/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp
Fixes https://github.com/google/iree/issues/6412
> Add support for saving mid level IR to a file.

- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/constant_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/variable_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/variable_ops.mlir
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Dialect/VM/IR/test/const_ops.mlir
- iree/compiler/Dialect/VM/IR/test/global_folding.mlir
- iree/compiler/Dialect/VM/IR/test/global_ops.mlir
- iree/compiler/Dialect/VM/Target/C/test/global_ops.mlir
- iree/compiler/Dialect/VM/Transforms/test/global_initialization.mlir
- iree/compiler/Dialect/VM/Transforms/test/ordinal_allocation.mlir
- iree/vm/test/global_ops.mlir
- iree/vm/test/global_ops_f32.mlir
- iree/vm/test/global_ops_i64.mlir
> Switching VM symbol ops to use assemblyFormat.

- iree/hal/local/elf/elf_module.c
Will now see something like this from the runtime:
```
D:\Dev\iree\iree\hal\local\elf\elf_module.c:481: UNAVAILABLE; ELF imports
one or more symbols (trying 'fmaf'); imports are not supported in the
platform-agnostic loader; while invoking native function
hal.executable.create; while calling import
```
(helps with #4717)
> Fail ELF loading when imports are found with a better error message.

- iree/tools/run_lit.ps1
> Correct double-quote escaping from PS->bash

- iree/base/internal/threading_win32.c
Thanks to @ImanHosseini for finding!
> Fixing Win32 dangling thread deadlock.

- build_tools/bazel/build_core.sh
- build_tools/cmake/test.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build.sh
- iree/hal/cuda/BUILD
- iree/hal/cuda/CMakeLists.txt
- iree/hal/cuda/api.h
- iree/hal/cuda/cuda_device.c
- iree/hal/cuda/cuda_device.h
- iree/hal/cuda/cuda_driver.c
- iree/hal/cuda/dynamic_symbol_tables.h
- iree/hal/cuda/registration/driver_module.c
- iree/hal/cuda/stream_command_buffer.c
- iree/hal/cuda/stream_command_buffer.h
- iree/samples/simple_embedding/BUILD
- iree/samples/simple_embedding/CMakeLists.txt
- iree/samples/simple_embedding/device_cuda.c
- added arena block pool in cuda device
- implemented cuda stream command buffer
- integrated deferred command buffer into cuda backend
- tested by simple embedding
> Integrate deferred command buffer into CUDA backend.

- docs/developers/best_practices.md
Trying to put some of our intuition and general IREE design goals down on [virtual] paper that we can point people at, inspired by pages like https://www.tensorflow.org/lite/performance/best_practices (for layout and general topics to cover). Some things in here like "track state within your model" are responses to existing practices for working with current-generation frameworks that we want people to untangle in their models.
I don't really have an upper limit on how long this document could be in mind. I'm starting this page on `docs/developers/`, but we could move it to `docs/website/` to have it accessible on https://google.github.io/iree/ if it is useful to enough people.
> Start "IREE Best Practices" document.

- iree/base/alignment.h
- iree/base/target_platform.h
- iree/vm/bytecode_dispatch_util.h
> Adds iree_unaligned_load+store to emulate unaligned access.

- docs/website/docs/bindings/python.md
- docs/website/docs/deployment-configurations/cpu-dylib.md
- docs/website/docs/deployment-configurations/gpu-vulkan.md
- docs/website/docs/ml-frameworks/tensorflow-lite.md
- docs/website/docs/ml-frameworks/tensorflow.md
Tested at https://scotttodd.github.io/iree/.
cc @ImanHosseini
> Fix broken doc links and warn about python packages on Windows.

- docs/website/docs/building-from-source/optional-features.md
- docs/website/docs/ml-frameworks/tensorflow.md
Broken links, similar issue with another page.  [which was fixed]
Not tested though, again not sure if they should be ./ or ../?
> Broken links

- iree/compiler/Dialect/LinalgExt/IR/BUILD
- iree/compiler/Dialect/LinalgExt/IR/CMakeLists.txt
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/Transforms/BUILD
- iree/compiler/Dialect/LinalgExt/Transforms/CMakeLists.txt
- iree/compiler/Dialect/LinalgExt/Transforms/ConvertToLoops.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/test/convert_to_loops.mlir
This is a step toward https://github.com/google/iree/issues/6477
> Implement generateScalarImplementation for linalg_ext.fft op.

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
Canonicalization patterns may apply to some ops and cause the root_op
marker to be dropped. Therefore it should be ran after all the tiling
patterns have be ran.
> Run canonicalization after tiling during flow dispatch creation

- iree/vm/BUILD
This buys us some time on https://github.com/google/iree/issues/357
> Updated commented out bytecode_op_table.h generation rule.

- iree/tools/utils/trace_replay.c
> Fix error in trace replay for vm.list (should be mapping not sequence).

- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
Closes https://github.com/google/iree/issues/6604
> Enable fft e2e tests on CUDA backend.

- iree/compiler/Codegen/LLVMGPU/BUILD
- iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorLowering.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- iree/compiler/Codegen/LLVMGPU/test/vectorization.mlir
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
Improve the order of transformation and enable transfer ops
optimizations.
> [CUDA] Re-organize vector transformations to improve codegen

- iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
This is the follow up on https://github.com/google/iree/pull/6478
> Considering duplicate operands in Linalg fusion.

- iree/compiler/Dialect/Flow/IR/BUILD
- iree/compiler/Dialect/Flow/IR/CMakeLists.txt
- iree/compiler/Dialect/Flow/IR/FlowBase.td
- iree/compiler/Dialect/Flow/IR/FlowDialect.cpp
- iree/compiler/Dialect/Flow/IR/FlowDialect.h
- iree/compiler/Dialect/Flow/IR/FlowTypes.cpp
- iree/compiler/Dialect/Flow/IR/FlowTypes.h
- iree/compiler/Dialect/HAL/IR/HALDialect.h
Future changes will add ODS-defined attributes and types.
> Setting up the flow dialect for AttrDef/TypeDef support.

- integrations/tensorflow/bindings/python/iree/tools/tf/setup.py.in
- integrations/tensorflow/bindings/python/iree/tools/tflite/setup.py.in
- integrations/tensorflow/bindings/python/iree/tools/xla/setup.py.in
* Allows the parts needed for console scripts to work.
* Fixes #6638
> Include recursive packages for tools.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
Regression in #6420. Was trying to make this work before deleting streams but am just going to leave it disabled for now.
> Disabling stream ties (again).

- iree/tools/utils/trace_replay.c
We now accept the following buffer view forms (mix/match as needed):
```yaml
- type: hal.buffer_view
shape: 4
element_type: f32
contents: 5 2 3 4
- type: hal.buffer_view
shape:
- 4
element_type: 50331680
contents: !!binary |
AACAQAAAIEEAAJBBAADgQQ==
```
And a special list item that is parsed as a tensor and expands to the same buffer view as above:
```yaml
- !hal.buffer_view 4xf32
- !hal.buffer_view 4xf32=2
- !hal.buffer_view 4xf32=2 2 2 2
```
> Improving trace yaml ergonomics by matching the command line parsers.

- colab/test_notebooks.py
- colab/tflite_text_classification.ipynb
- docs/website/docs/ml-frameworks/tensorflow-lite.md
Relates to https://github.com/google/iree/issues/6691
Not tested on CI (https://buildkite.com/iree/iree-samples) yet, since that's been broken since https://github.com/google/iree/pull/6611.
> Fix TFLite sample by setting input_type="tosa".

- iree/compiler/Dialect/VM/Analysis/ValueLiveness.cpp
> Making the ValueLiveness analysis annotation use cached AsmState.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/Transforms/ConvertConv2D1x1ToMatmulPass.cpp
- iree/compiler/Dialect/Flow/Transforms/ConvertConv2DToImg2ColPass.cpp
- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/ConvertTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/DeduplicateExecutables.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/ExpandVariableDynamicDims.cpp
- iree/compiler/Dialect/Flow/Transforms/ExportBenchmarkFuncs.cpp
- iree/compiler/Dialect/Flow/Transforms/FormStreams.cpp
- iree/compiler/Dialect/Flow/Transforms/HoistUnstreamableOps.cpp
- iree/compiler/Dialect/Flow/Transforms/InjectDispatchTracing.cpp
- iree/compiler/Dialect/Flow/Transforms/InsertConstantClones.cpp
- iree/compiler/Dialect/Flow/Transforms/InterchangeGenericOps.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineLargeConstants.cpp
- iree/compiler/Dialect/Flow/Transforms/PadLinalgOps.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/PromoteI1ToI8Pass.cpp
- iree/compiler/Dialect/Flow/Transforms/PromoteTensorLoads.cpp
- iree/compiler/Dialect/Flow/Transforms/SimplifyVariableAccesses.cpp
- iree/compiler/Dialect/Flow/Transforms/StripAndSplatConstantVariables.cpp
- iree/compiler/Dialect/Flow/Transforms/VerifyInputLegality.cpp
> Fully-qualifying mlir::FuncOp & co.

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/MatmulToMMT4dConversion.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/test/matmul_to_mmt4d.mlir
Optionally convert linalg.matmul -> linalg.mmt4d when inner most dims (M0, N0, K0) are compile constants
> linalg.matmul -> linalg.mmt4d conversion

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/DropExcludedExports.cpp
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/test/constant_ops.mlir
- iree/compiler/Dialect/VM/Target/C/test/global_ops.mlir
> Ensuring all struct fields have sizeof > 0.

- iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorize.cpp
- iree/compiler/Codegen/SPIRV/test/convert_to_spirv.mlir
- iree/compiler/Codegen/SPIRV/test/pipeline_matmul_vectorization.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_matmul.mlir
- iree/compiler/Codegen/Utils/Utils.cpp
Now we need to attach the configurations onto the ops themselves.
> [spirv] Port more tests over to dynamic pipelines

- build_tools/android/post_benchmarks_as_pr_comment.py
Fixes https://github.com/google/iree/issues/6518
> Query more base commits to show performance difference

- iree/test/e2e/models/BUILD
- iree/test/e2e/models/CMakeLists.txt
This reverts commit b217e66e67f78bb761d8320cacd3defaad3b84f2.
> Revert "Enable model test for CUDA now that they run fast (#6759)"

- iree/compiler/Codegen/LLVMGPU/BUILD
- iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
Pick configuration based on the problem size and skip using shared
memory for workgroup of a single warp.
> [CUDA] Add some basic logic to pick better configuration

- iree/compiler/Codegen/SPIRV/KernelDispatchUtils.cpp
If an op have more than three parallel dimensions, we want to
tile along the innermost ones. This happens for convolution ops,
where the first dimension is typically one for inference.
There is no need to tile along that.
This should fix the 3-4x performance regression on Adreno GPUs.
> [spirv] Tile along the last three partitioned (parallel) dimensions

- bindings/python/tests/testdata/generate_tflite.py
- integrations/tensorflow/bindings/python/iree/tf/support/module_utils.py
We've now updated the TF pip package so this should work.
This reverts commit 2b2ae4a158e9b1298fd708d7c428fb463b029674.
> Reapply "Update TFLite concrete function conversion codes"

- iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/control_flow_ops.mlir
> Changing std.assert lowering to go to vm.cond_fail.

- benchmarks/TFLite/CMakeLists.txt
32-bit float versions for MobileNetSSD, PoseNet and DeepLabV3
> Add several vision models for Tosa Benchmarking

- iree/samples/static_library/CMakeLists.txt
- iree/samples/static_library/static_library_demo_test.txt
> Add test for static_library_demo.

- .github/workflows/validate_and_publish_release.yml
Fix https://github.com/google/iree/runs/3480016077?check_suite_focus=true
> [snapshot release] Fix push command for the latest-snapshot branch

- bindings/python/iree/compiler/README.md
- bindings/python/tests/README.md
- colab/README.md
- docs/developers/design_docs/hal_driver_features.md
- docs/developers/get_started/generic_vulkan_env_setup.md
- iree/samples/simple_embedding/README.md
- iree/tools/android/run_module_app/README.md
Made corrections to the typos i found in the documentations.
> Fix typos in docs

- iree/test/e2e/regression/BUILD
- iree/test/e2e/regression/CMakeLists.txt
- iree/test/e2e/regression/dynamic_abs.mlir
- iree/test/e2e/regression/dynamic_add.mlir
- iree/test/e2e/regression/dynamic_dot.mlir
- iree/test/e2e/regression/dynamic_reduce_min.mlir
- iree/test/e2e/regression/dynamic_torch_index_select_high_rank.mlir
- iree/test/e2e/regression/dynamic_torch_index_select_negative.mlir
- iree/test/e2e/regression/dynamic_torch_index_select_scalar.mlir
- iree/test/e2e/regression/dynamic_torch_index_select_vector.mlir
That makes it easier to run on different backends. Keep the util tests
as lit test.
> Convert Dynamic shape tests to check_test

- .github/workflows/build_package.yml
- .github/workflows/schedule_snapshot_release.yml
- .github/workflows/validate_and_publish_release.yml
This currently tests that python packages can be pip installed, and that command line tools can be extracted and run with basic commands
Successful run: https://github.com/not-jenni/iree/runs/3536908833?check_suite_focus=true
Progress on https://github.com/google/iree/issues/6316
> Adds basic validation to make sure linux releases are stable

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
We're going to turn `-Wunused-variable` back on in the CI. Caught these
in preparation for that.
> Delete unused variables in EmitC

- iree/compiler/Codegen/SPIRV/AdrenoConfig.cpp
- iree/compiler/Codegen/SPIRV/test/config_adreno_matmul.mlir
This is just extending the current matmul configuration for
batch matmul.
> [spirv] Add batch matmul CodeGen configuration for Adreno GPUs

- docs/website/docs/building-from-source/getting-started.md
- docs/website/docs/building-from-source/optional-features.md
Per the announcement in
https://groups.google.com/g/iree-discuss/c/1mj0SoDzPa8 we are codifying
the configurations in which we support building from source.
> Explicitly note supported build configurations

- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
Previously we called the `iree_make_cstring_view` helper function, but function calls are not allowed in constant initializers in C.
Partial fix for #7026
> Fix initialization of string views

- iree/compiler/Dialect/VM/Target/C/test/constant_ops.mlir
> Check that negative constants are printed properly

- docs/developers/developing_iree/e2e_benchmarking.md
Flagfiles have been broken since
https://github.com/google/iree/pull/6318. Confused users are trying to
follow these instructions and getting errors.
See https://github.com/google/iree/issues/6688
> [doc] Remove references to flagfiles

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
To enable search we support having the config coming from the higher
level IR.
> [CUDA] Add support for config lowering coming from IR

- llvm-external-projects/iree-dialects/include/iree-dialects-c/Dialects.h
- llvm-external-projects/iree-dialects/lib/CAPI/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/CAPI/Dialects.cpp
- llvm-external-projects/iree-dialects/python/IREEDialectsModule.cpp
* Quite a few more things need to line up before generally usable.
* Building out some basic samples here (will eventually be upgraded to tests): https://github.com/google/iree-samples/blob/main/pydm/simple/basic_sample.py
> Plumb through an API to build PyDM->IREE pass pipelines.

- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
SwiftShader now supports multiple entry points in the same module
better.
> [spirv] Re-enable module linking

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
Current code only handles fusion of `linalg.fill`/`linalg.generic`
with `outs` of root operations, but this could be any op. These ops
would be simultaneoulsy added to the fusion group of consumer root
operation, but also marked as root. Fix that and also ensure an op
within a dispatch region is not added to another "nested" dispatch
region.
> Handle fusion of any named ops with outs of root ops.

- integrations/tensorflow/e2e/CMakeLists.txt
- integrations/tensorflow/e2e/keras/layers/CMakeLists.txt
Bazel files were updated internally. Updating the CMake files to match.
> Fixed Integrations CMake files to match bazel

- iree/compiler/Dialect/LinalgExt/IR/BUILD
- iree/compiler/Dialect/LinalgExt/IR/CMakeLists.txt
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtBase.td
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtDialect.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtDialect.h
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/test/BUILD
- iree/compiler/Dialect/LinalgExt/IR/test/CMakeLists.txt
- iree/compiler/Dialect/LinalgExt/IR/test/canonicalize.mlir
Also generates dialect information through table gen tools, so we can add the pattern to all LinalgExt ops.
> Add folding tensor.cast patterns to LinalgExt ops.

- iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- iree/compiler/InputConversion/MHLO/test/convert_mhlo_to_linalg_ext.mlir
It's a step toward https://github.com/google/iree/issues/5045
> Lowering mhlo.reverse to linalg_ext.reverse.

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
This reverts commit 0189f9fd85df0a54eb59366dac3388243cd38606.
> Revert "[CUDA] Refactor op configuration (#7167)"

- benchmarks/TFLite/CMakeLists.txt
- benchmarks/TensorFlow/CMakeLists.txt
Need to use embedded library to test this driver.
> benchmark: Update iree-translate flag for dylib-sync

- docs/developers/best_practices.md
Progress on https://github.com/google/iree/issues/7095
I don't expect these to be stable, so sorry for the extra maintenance burden... but I think it's time to put together sections like these to help users evaluate IREE for their own uses.
> Discuss compilation and runtime settings in best practices doc.

- iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
Fixes https://github.com/google/iree/issues/7229
> Support memref allocation ops in FlattenMemRefSubspanPass

- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
Operand fusion as supported in IREE today requires some extra steps in
bufferization to reuse the buffer between inputs/outputs of the fused
op. This PR refactors the requirements from operand fusion into a
separate analysis phase. When the operand fusion is generalized this
step can be dropped.
> Address bufferizations issues with operand fusion.

- build_tools/benchmarks/run_benchmarks_on_android.py
This is quite useful for invoking the script locally for perf
work on a specific CodeGen backend.
> Add option to filter drivers when benchmarking Android

- bindings/python/iree/runtime/vm.cc
- llvm-external-projects/iree-compiler-api/include/iree-compiler-c/Compiler.h
- llvm-external-projects/iree-compiler-api/lib/CAPI/Compiler.cpp
- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects-c/Dialects.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/ToIREE/TypeConverter.h
- llvm-external-projects/iree-dialects/lib/CAPI/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/CAPI/Dialects.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/Passes.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/RTL/LinkRTLPass.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/ToIREE/ConversionPass.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/ToIREE/LoweringPatterns.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/ToIREE/TypeConverter.cpp
- llvm-external-projects/iree-dialects/python/IREEDialectsModule.cpp
- llvm-external-projects/iree-dialects/python/iree/compiler/dialects/iree_pydm/importer/util.py
- llvm-external-projects/iree-dialects/python/iree/compiler/dialects/iree_pydm/rtl/__init__.py
- llvm-external-projects/iree-dialects/python/iree/compiler/dialects/iree_pydm/rtl/base.py
- llvm-external-projects/iree-dialects/test/iree_pydm/to_iree/constants.mlir
- llvm-external-projects/iree-dialects/test/iree_pydm/to_iree/integer_compare.mlir
- llvm-external-projects/iree-dialects/test/iree_pydm/to_iree/real_compare.mlir
- llvm-external-projects/iree-dialects/test/iree_pydm/to_iree/structural.mlir
- llvm-external-projects/iree-dialects/test/python/iree_pydm/rtl.py
* I haven't yet figured out the best way to e2e test this. For now, putting e2e tests in the samples repo: https://github.com/google/iree-samples/tree/main/pydm/simple
> [pydm] Plumb through RTL and finish conversions for basic program.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
The heuristic used earlier resulted in too much splitting resulting in
large number of tiny workgroups. For now we dont have a good way to
model the amount of work that each dispatch contains, so this change
just limits the number of workgroups.
> Address regressions with default heuristics on CPU.

- bindings/python/README.md
- docs/website/docs/bindings/python.md
Also removed a few stale TODOs.
cc @stellaraccident
> Add links to Python API references.

- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/Common/test/BUILD
- iree/compiler/Codegen/Common/test/CMakeLists.txt
- iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
This is the initial commit to use Linalg Comprehensive bufferize pass
from within IREE. The main work here is to bridge the memory model gap
of using `flow.dispatch.tensor.load/store` operations.
> Initial commit of bridge to use Linalg Comprehensive Bufferize Pass.

- build_tools/cmake/iree_setup_toolchain.cmake
> On OSX dont enable LLD and warn

- docs/website/docs/extensions/index.md
- docs/website/mkdocs.yml
I tried to keep this relatively high-level for now (mostly because
many of these mechanisms are not fully implemented) but it's such
a common question that we really need someplace to direct people to
for the 10,000ft view and capabilities we (will) provide.
There's just the single design overview for now but as we build and
document these mechanisms we can add user-facing docs for the ones
that people will encounter with samples/etc.
> Adding docs on the various extension mechanisms available in IREE.

- colab/test_notebooks.py
Something in https://github.com/google/iree/pull/7501 fixed this :D
> Remove expected failure for tflite notebook test.

- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
- iree/samples/static_library/static_library_demo.c
Fixes one more test disabled in #5715
> Fix memory leak in static library demo

- iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp
- iree/compiler/Dialect/Stream/Transforms/test/refine_usage.mlir
(wasn't caught until I rebased the final stream->hal WIP)
> Fixes stream type refinement across ties that change types.

- iree/compiler/Dialect/HAL/Transforms/ElideRedundantCommands.cpp
- iree/compiler/Dialect/HAL/Transforms/test/elide_redundant_commands.mlir
Super simple since we only generate barriers in one way today.
> Adding redundant command buffer barrier elision.

- iree/compiler/Dialect/Stream/IR/StreamOpFolders.cpp
- iree/compiler/Dialect/Stream/IR/test/async_folding.mlir
Chipping away at one TODO. I'm still ramping up on this new part of the compiler, so I haven't yet done a complete analysis on this or spotted cases where it could get practically applied.
> Add stream dialect ConvertSplatConstantsIntoSplats folder.

- iree/samples/custom_modules/custom_modules_test.cc
- iree/samples/custom_modules/module.cc
- iree/samples/custom_modules/module.h
It was working by chance before (and only on CPU).
> Fixing the custom_modules sample to use the proper HAL allocator.

- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
- iree/compiler/Dialect/Flow/Transforms/test/matmul_to_mmt4d.mlir
The main source of test coverage for this code is the e2e matmul tests.
> Support arbitrary shapes with mmt4d, by padding

- iree/test/e2e/regression/generate_e2e_matmul_tests.py
Explanation from the code comment:
```
#
```
Before, the 'small' e2e matmul tests use mmt4d in 40 out of 62 test
functions. Out of these 40, only one was mixed-shapes.
After, they use mmt4d in 49 out of 59 functions. 10 mixed-shapes cases
use mmt4d, 10 others don't.
So the increase in mmt4d test coverage is real and, accidentally, this
also reduces build latencies (62->59 matmul functions to build).
> e2e matmul tests: generate more "tame" mixed shapes

- iree/compiler/Dialect/Stream/Transforms/ConvertToStream.cpp
- iree/compiler/Dialect/Stream/Transforms/test/convert_to_stream.mlir
This ensures the proper transfers and imports/exports are added.
> Fixing stream conversion with custom ops taking tensors.

- iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
These are essentially no-op given that we'll flatten both the
source and target memref types.
> Handle reshape ops in FlattenMemRefSubspanPass

- iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp
- iree/compiler/Dialect/Stream/Transforms/RefineUsage.cpp
- iree/compiler/Dialect/Stream/Transforms/test/refine_usage.mlir
This was showing up in some internal tests - the repro added here covers the core case hit by those.
> Fixing lifetime transitions.

- iree/compiler/Translation/IREEVM.cpp
> Revert "Flipping `-iree-experimental-streams` flag to default true."

- iree/compiler/Codegen/LLVMGPU/BUILD
- iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUUtils.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUUtils.h
Refactoring based on previous review feedback
> [LLVMGPU][NFC] Minor refactor to helpers and kernel config

- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
#7646 should be addressed first.
> IREEComprehensiveBufferize: InitTensorOp Elimination

- iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- iree/compiler/Codegen/SPIRV/test/vectorize_matmul.mlir
Fixes https://github.com/google/iree/issues/7750
> [spirv] Allow vectorization with native size 2 and 1

- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
Changes the link mode if building a static library.
Fixes #7747.
> `LinkOnlyNeeded` if linking static libraries

- build_tools/buildkite/cmake/build_configurations.yml
- build_tools/cmake/build_runtime_small.sh
- iree/base/attributes.h
- iree/base/status.c
- iree/hal/allocator_heap.c
- iree/hal/buffer.c
- iree/hal/command_buffer_validation.c
- iree/hal/local/elf/elf_module.c
- iree/hal/local/sync_semaphore.c
- iree/hal/local/task_semaphore.c
- iree/modules/hal/module.c
- iree/tools/utils/yaml_util.c
- iree/vm/native_module.c
(makes testing of #6622 easier)
> Adding a size-optimized build config.

- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/set_android_scaling_governor.sh
- build_tools/benchmarks/set_pixel6_gpu_scaling_policy.sh
Did this yesterday to pull numbers; so just sending out.
> Support pinning down Pixel 6 Mali GPU frequency

- build_tools/cmake/iree_c_module.cmake
- iree/samples/emitc_modules/CMakeLists.txt
- iree/vm/test/emitc/CMakeLists.txt
> Add missing deps to iree c modules

- iree/vm/shims_emitc.h
Add shims in EmitC for all shims that are already defined in iree.
> Add all shims defined in iree to EmitC

- iree/compiler/Dialect/HAL/Target/LLVM/Builtins/Device.cpp
Reproduce:
cmake -B build -S . && cd build && cmake --build .
compiler: gcc7.5.0
sys: ubuntu16.04
> Fix compile GCC error

- iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp
- iree/compiler/Codegen/SPIRV/test/vectorize_load_store.mlir
This allows us to compose better with other affine expressions
generated and thus fold better.
> [spirv] Use AffineApplyOp to replace normal arithmetic ops

- iree/compiler/Dialect/Flow/Transforms/ConvertConv2D1x1ToMatmulPass.cpp
- iree/compiler/Dialect/Flow/Transforms/ConvertConv2DToImg2ColPass.cpp
- iree/compiler/Dialect/Flow/Transforms/ConvertToFlow.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/InjectDispatchTracing.cpp
- iree/compiler/Dialect/Flow/Transforms/InterchangeGenericOps.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
- iree/compiler/Dialect/Flow/Transforms/PadLinalgOps.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/VerifyInputLegality.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_elementwise.mlir
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_fusion.mlir
- iree/compiler/Dialect/Flow/Transforms/test/verify_input_ir.mlir
- iree/compiler/Dialect/HAL/Transforms/MaterializeResourceCaches.cpp
- iree/compiler/Dialect/HAL/Transforms/MemoizeDeviceQueries.cpp
- iree/compiler/Dialect/HAL/Transforms/ResolveEntryPointOrdinals.cpp
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Utils/BUILD
- iree/compiler/Utils/CMakeLists.txt
- iree/compiler/Utils/PassUtils.h
* Specifically, enables general purpose use of util.initializer and friends.
* Depends on https://reviews.llvm.org/D115645
> Adapt passes and pipelines to work generically on FunctionLike.

- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
Most of passes are moved before memrefs world. The
LLVMCPULowerExecutableTargetPass starts with tensors world. This PR
updates the tests to tensors version as input.
Also delete a dup test case (@test_exp_2), which is as same as
@test_exp_0.
> [NFC] Clean old lit tests up.

- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
Finally.. This should give us better number stability after pinning
down CPU and GPU frequency. 🙌
> Add Pixel 6 for Mali GPU benchmarking

- iree/compiler/Codegen/Common/test/canonicalize_interface_load_store.mlir
- iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
- iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
- iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
- iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMCPU/test/hal_interface_bindings.mlir
- iree/compiler/Codegen/LLVMCPU/test/hal_interface_constants.mlir
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMGPU/test/convert_to_nvvm.mlir
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
- iree/compiler/Codegen/SPIRV/test/convert_to_spirv.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_distribute.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_load_store.mlir
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/Transforms/MaterializeInterfaces.cpp
- iree/compiler/Dialect/Modules/VMVX/Conversion/HALToVMVX/ConvertHALToVMVX.cpp
The ordering always bothered me and 'offset' was misleading.
> Cleaning up/renaming the `hal.interface.constant.load` op.

- iree/compiler/Dialect/VM/Target/C/TranslateToCpp.cpp
Fixes changes made in https://github.com/llvm/llvm-project/commit/4a8cef157b758e3f3d85f9fa63ebc7b5ee02f488
> Update function names in TranslateToCpp.cpp

- iree/compiler/Dialect/Util/Transforms/FuseGlobals.cpp
- iree/compiler/Dialect/Util/Transforms/test/fuse_globals.mlir
> Fix to prevent globals with divergent stores from fusing.

- llvm-external-projects/iree-compiler-api/build_tools/smoketest.py
- llvm-external-projects/iree-compiler-api/python/CMakeLists.txt
- llvm-external-projects/iree-compiler-api/python/iree/compiler/version.py
- llvm-external-projects/iree-compiler-api/setup.py
Also adds some submodule revisions of note so that they can be queried at runtime.
> Generate a version.py for iree.compiler.

- iree/hal/cuda/native_executable.c
- iree/tools/iree-benchmark-trace-main.c
> Fixing iree-benchmark-trace.

- docs/website/overrides/404.html
The redesign was many months ago now.
> Refresh 404 page on the website.

- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertBufferOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/buffer_ops.mlir
Also fixing some bugs in the existing implementation around float
handling.
Fixes #7633.
> Adding support for loading/storing i64 into staging buffers.

- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__complex_dynamic_dim_count_nonzero.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__complex_dynamic_dim_l2_normalize.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__dynamic_dim_count_nonzero.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__complex_dynamic_dim_count_nonzero.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__complex_dynamic_dim_l2_normalize.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__digamma.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_accumulate_n.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_add_n.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_count_nonzero.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_digamma.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_mod.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__mod.run
sample failure logs:
* https://source.cloud.google.com/results/invocations/ccf8446b-6d1f-4f07-853d-fd2bd5bc7faa/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-swiftshader%2Fmain/log
* https://source.cloud.google.com/results/invocations/25d1643f-c839-4d0b-aa7f-bc3a4350d058/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-turing%2Fmain/log
relates to https://github.com/google/iree/issues/8083
> Disable suspected flaky tests.

- .github/workflows/schedule_candidate_release.yml
To ensure it is ready for the `iree-sample` daily test at 8am PST.
> Move scheduled release forward to 2am PST.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
1) Cleanup the way vector size is computed
2) Move checks for existing lowering config and for VMVX backend out of individual backends.
> Misc cleanup for CPU Kernel dispatch configuration.

- CMakeLists.txt
- build_tools/third_party/rocm/CMakeLists.txt
- experimental/rocm/CMakeLists.txt
- experimental/rocm/cts/CMakeLists.txt
- experimental/rocm/direct_command_buffer.c
- experimental/rocm/direct_command_buffer.h
- experimental/rocm/executable_layout.c
- experimental/rocm/executable_layout.h
- experimental/rocm/native_executable.c
- experimental/rocm/native_executable.h
- experimental/rocm/registration/CMakeLists.txt
- experimental/rocm/rocm_allocator.c
- experimental/rocm/rocm_device.c
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.h
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTargetUtils.cpp
- iree/hal/drivers/CMakeLists.txt
- iree/hal/drivers/init.c
- iree/tools/init_targets.cc
-Update ROCM HAL to have arena block
-Fix CLOptions on ROCm compiler
-Renamed ROCM Experimental flag to enable cts
> ROCm port update

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
This phone is not in the lab and no benchmark workloads run on it.
> Remove Galaxy S10 for correctness testing

- .gitmodules
- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
- build_tools/buildkite/cmake/build_configurations.yml
- iree/compiler/Bindings/TFLite/Transforms/WrapEntryPoints.cpp
- iree/compiler/Codegen/Common/DemoteF32ToF16.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileFuseAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUDistributeSharedMemoryCopy.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- iree/compiler/Codegen/SPIRV/SPIRVCopyToWorkgroupMemory.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTileAndDistribute.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- iree/compiler/Codegen/SPIRV/test/vectorize_elementwise_ops.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_matmul.mlir
- iree/compiler/Dialect/Flow/Transforms/StripSignednessPass.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/MetalSPIRV/MetalSPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp
- iree/compiler/Dialect/HAL/Target/VMVX/VMVXTarget.cpp
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/WebGPU/WebGPUTarget.cpp
- iree/compiler/Dialect/Stream/IR/StreamTypes.cpp
- iree/compiler/Dialect/Util/Transforms/FixedPointIterator.cpp
- iree/compiler/Dialect/Util/Transforms/TestFloatRangeAnalysis.cpp
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- third_party/mlir-hlo.branch-pin
* Reset third_party/llvm-project: c84b8be516bcc4d021ff804169d58a7b3104e050 (2022-01-15 19:52:30 +0000): [AArch64] clang support for Armv8.8/9.3 MOPS
> Integrate llvm-project at c84b8be516bcc4d021ff804169d58a7b3104e050

- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/TranslateToCpp.cpp
- iree/compiler/Dialect/VM/Target/C/test/control_flow.mlir
> Don't emit unused labels

- colab/edge_detection.ipynb
- colab/test_notebooks.py
- iree/samples/dynamic_shapes/README.md
- iree/samples/dynamic_shapes/dynamic_shapes.ipynb
- iree/samples/dynamic_shapes/test.sh
- iree/samples/variables_and_state/README.md
- iree/samples/variables_and_state/variables_and_state.ipynb
Might drop or rewrite the notebooks using TensorFlow soon anyways (https://github.com/google/iree/issues/8086)
> Fix iree-samples buildkite pipeline.

- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
Turns out that if you write passes that rely on canonicalization and CSE
it really helps if you actually run them.
> Running cleanup before -iree-stream-optimization-pipeline.

- integrations/tensorflow/test/iree_tfl_tests/llvmaot_posenet_i8.run
- iree/compiler/InputConversion/TOSA/Passes.cpp
Default passes include the performance improving tosa decomposition.
> Use default TosaToLinalg passes

- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__complex_cumprod.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__complex_cumsum.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__cumprod.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__cumsum.run
- iree/compiler/Codegen/Common/BufferizationAnalysis.h
- iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
Check if a value is part of the equivalence set before checking if it
has a leader.
> Fix error in bufferization analysis.

- iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Dialect/Stream/Transforms/EncodeTensors.cpp
- iree/compiler/Dialect/Util/IR/ClosureOpUtils.cpp
- iree/compiler/Dialect/Util/IR/UtilTypes.h
- iree/compiler/Dialect/VM/Analysis/RegisterAllocation.cpp
- iree/compiler/Dialect/VM/Analysis/RegisterAllocation.h
- iree/compiler/Dialect/VM/IR/VMBase.td
- iree/compiler/Dialect/VM/IR/VMDialect.h
- iree/hal/buffer_view.h
> Fixing various bit->byte rounding logic to reuse the one that works.

- iree/compiler/Codegen/Common/BufferizationAnalysis.cpp
- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
Currently IREEs bufferization pass silently ignores operations with
tensor operands or results that is not explicitly handled. Error out
on such cases to avoid miscompilations.
> Error out in bufferization on unhandled tensor operation.

- iree/compiler/Codegen/LLVMCPU/Passes.cpp
There might be corner cases here where the IREE bufferization does better. So just moving to upstream bufferization for the x86 codegen path.
> Move x86 GEMM codegeneration pipeline to use upstream bufferization.

- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
This is minor refactoring to allow to do more advanced improvements with
shared memory in the future
> [CUDA] Represent shared memory as alloc

- integrations/tensorflow/WORKSPACE
- iree/compiler/Codegen/Common/VectorizeMMT4d.cpp
- iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- iree/compiler/Codegen/Transforms/AffineMinDistributedSCFCanonicalization.cpp
- iree/compiler/Dialect/Flow/IR/FlowBase.td
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertCommandBufferOps.cpp
- iree/compiler/Dialect/HAL/IR/HALBase.td
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/Stream/Transforms/SpecializeDispatches.cpp
- iree/compiler/Dialect/Util/IR/UtilOps.cpp
- iree/compiler/Dialect/Util/IR/UtilOps.td
- iree/compiler/Dialect/VM/Conversion/MemRefToVM/ConvertMemRefToVM.cpp
- iree/compiler/Dialect/VM/IR/VMBase.td
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/PyDM/IR/PyDMDialect.td
* Reset third_party/llvm-project: 4ae83bb2b1e27628f6bd14d746aef964ed776d52 (2022-02-10 15:05:23 -0500): Update all LLVM documentation mentioning runtimes in LLVM_ENABLE_PROJECTS
> Integrate llvm-project at 4ae83bb2b1e27628f6bd14d746aef964ed776d52

- iree/base/internal/wait_handle_inproc.c
- iree/base/internal/wait_handle_poll.c
- iree/base/internal/wait_handle_win32.c
> Allowing NULL ptrs in iree_wait_set_free for ergonomics.

- iree/hal/utils/buffer_transfer.c
It's possible for buffers to not be host-visible and also have the
mapping bit set but iree_hal_device_transfer_mappable_range requires
that the buffers be host-visible.
> Only use iree_hal_device_transfer_mappable_range if host visible.

- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/Stream/IR/StreamOps.cpp
- iree/compiler/Dialect/Stream/IR/StreamOps.td
verifier form is deprecated and will be removed.
> Update to hasVerifier form (NFC)

- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
Remove dependency to workload_per_wg attribute and clean up the code to
distribute fro block to thread/warp.
> [CUDA] Refactor distribution to thread/warp

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
This change goes with the following llvm patch
https://github.com/nirvedhmeshram/llvm-project/commit/a6389bd2efab389203e70cab50d1254538deeb89
> Adding BatchMatmulOp to use tensorcore when possible

- bindings/python/iree/runtime/invoke.cc
> Remove unused variable

- iree/hal/cuda/cuda_device.c
- iree/hal/cuda/dynamic_symbol_tables.h
- iree/hal/cuda/graph_command_buffer.c
- iree/hal/cuda/stream_command_buffer.c
- iree/hal/cuda/stream_command_buffer.h
> Implements iree_hal_cuda_*_command_buffer_update_buffer.

- iree/compiler/Codegen/Common/FoldAffineMinInDistributedLoops.cpp
Upstream now have the issue fixed. :)
> NFC: Remove unused pattern and clarify comments in affine.min pass

- benchmarks/TFLite/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
This change should have no effect as the flag is already on by default
> Remove iree-enable-fusion-with-reduction-ops flag

- integrations/tensorflow/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- integrations/tensorflow/iree-dialects/test/iree_linalgext/tiling.mlir
- iree/compiler/Codegen/SPIRV/test/config_default_linalg_ext_ops.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_distribute_sort.mlir
- iree/compiler/Dialect/Flow/Transforms/test/test_partitionable_loops_interface.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/test/iree_linalgext/tiling.mlir
This is a follow up from https://github.com/google/iree/pull/8365 which
updates the asm form. We are in favor of putting extra attributes to the
beginning.
> Move extra attributes to the beginning which is right after op name.

- integrations/tensorflow/WORKSPACE
- iree/compiler/Codegen/Common/VectorizeConv.cpp
- iree/compiler/Codegen/Common/VectorizeMMT4d.cpp
- iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorToCooperativeOps.cpp
- iree/samples/static_library/CMakeLists.txt
* Reset third_party/llvm-project: 0389f2edf7c252e49323ae0ca6adfea9f2614f6d (2022-02-17 02:17:27 -0800): Revert "[compiler-rt] Implement  ARM atomic operations for architectures without SMP support"
> Integrate llvm-project at 0389f2edf7c252e49323ae0ca6adfea9f2614f6d

- build_tools/cmake/iree_hal_cts_test_suite.cmake
Now tests like `allocator_test` just depend on the runtime, even when other tests in the suite use executables (and thus depend on `iree-translate` and the compiler build). I noticed this when rebuilding pure-HAL tests was taking a while after an LLVM update :)
> Drop executable deps from CTS tests that don't use executables.

- iree/compiler/Codegen/LLVMGPU/Verifiers.cpp
https://github.com/google/iree/pull/8344
> Nit from PR #8344 missed due to autosubmit. 

- colab/tflite_text_classification.ipynb
Use to_host to copy DeviceArray back, update generated IR to match head
and clean some metadata.
> Update tflite example colab

- iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp
- iree/compiler/Codegen/Passes.h
- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/test/matmul_to_mmt4d.mlir
- iree/compiler/Dialect/HAL/Utils/InferCustomKernelsTargetInfoFromParent.cpp
- iree/compiler/Dialect/HAL/Utils/InferCustomKernelsTargetInfoFromParent.h
- iree/compiler/Utils/CustomKernelsTargetInfo.cpp
- iree/compiler/Utils/CustomKernelsTargetInfo.h
These were introduced recently. MLIR uses camelBack:
https://mlir.llvm.org/getting_started/DeveloperGuide/#style-guide
> Fix some variables to use camelBack

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/BUILD
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
- iree/samples/static_library/CMakeLists.txt
Fixes #8380.
Co-authored-by: Marius Brehler <marius.brehler@iml.fraunhofer.de>
> Fix failing conversion in static library sample

- integrations/tensorflow/WORKSPACE
- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/Interfaces/BUILD
- iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- iree/compiler/Codegen/Interfaces/CMakeLists.txt
* Integrate llvm-project at e2f627e5e3855309f3a7421f6786b401efb6b7c7
* Advance sub-projects:
tensorflow: 576057d1c6fcb61dec6c6d6319bbb129b5954113
mlir-hlo: 7878104a845708490cafdec74b5b28b9aabfc923
Piper CL: 430679467
* Integration fixes for D120182
* Includes cherry-pick [92cf9f14814a5e8308c431095fb2205202445676](https://github.com/llvm/llvm-project/commit/92cf9f14814a5e8308c431095fb2205202445676) for llvm-project
> Integrate llvm-project at e2f627e5e3855309f3a7421f6786b401efb6b7c7

- integrations/tensorflow/WORKSPACE
- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileFuseAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
- llvm-external-projects/iree-dialects/test/iree_linalgext/invalid.mlir
* llvm-project: 11d144c57642ff9a7f393bc6a4809f75007ff73f
* mlir-hlo: d2d4f1b25cb9f4c2d7a41ce29416443f25b0f27a
* tensorflow: eb295c98c515c75b2893766279345fc09aa2c3a4
extra changes:
-Update tile `tileConsumerAndFuseProducers` signature
> Integrate llvm-project and bump dependencies.

- iree/compiler/Bindings/TFLite/Transforms/WrapEntryPoints.cpp
- iree/compiler/Bindings/TFLite/Transforms/test/wrap_entry_points.mlir
Not sure if this ever worked?
Found while helping with https://github.com/google/iree/issues/8412
(still digging into this more, will expand test coverage)
> Fix default identifier handling in TFLite bindings WrapEntryPoints.

- integrations/tensorflow/iree_tf_compiler/TFL/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/test/import/BUILD
- integrations/tensorflow/iree_tf_compiler/TFL/test/import/add.mlir
- integrations/tensorflow/iree_tf_compiler/TFL/test/import/multi_add.mlir
This pass did not appear to be running and the tests that would have caught it were disabled.
Found while helping with https://github.com/google/iree/issues/8412
> Run TFLite ConvertFunctionMetadataPass on FuncOp.

- iree/test/e2e/regression/generate_e2e_matmul_tests.py
Improve the tradeoff of test coverage vs cost, from discussion in PR #8428 .
> test fewer shapes in e2e matmul tests

- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
The current check to avoid generation of no-op subviews, would also
not generate subviews when the rank of the result was lesser than the
source. That still needs to be a subview.
Also add some lit tests.
> Fix handling of no-op subviews for rank-reducing cases.

- iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
> Generate memref.assert_alignment ops

- iree/test/e2e/regression/linalg_quantized_matmul_vs_linalg_matmul.mlir
Testing dynamic shapes is interesting because the implementation of `-linalg-quantized-matmul-to-matmul` has to do nontrivial things specifically to handle them, so bugs could lurk there. Testing that initially run into issues which have since been resolved by PR #8397 .
> Add dynamic-shapes variant of the quantized_matmul-vs-matmul test

- iree/compiler/Dialect/Stream/IR/StreamTypes.cpp
- iree/compiler/Dialect/Stream/Transforms/test/pack_constants.mlir
- iree/compiler/InputConversion/TOSA/Passes.cpp
This is not a real fix for the issue but will let us test how critical this value is.
> Changing default stream alignment to 64B.

- iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp
- iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
It's a step toward https://github.com/google/iree/issues/8303
> Add a pattern to adapt linalg.generic inputs to outputs.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
Configurations: taskset 80 + dylib-sync on local Pixel 4
| Model            | Before  | After   |
| ---------------- | ------- | ------- |
| DeepLabV3        | 711 ms  | 188 ms  |
| MobileBertSquad  | 672 ms  | 673 ms  |
| MobileNetV2      | 103 ms  | 46.4 ms |
| MobileNetV3Small | 24.6 ms | 14.6 ms |
| MobileSSD        | 204 ms  | 166 ms  |
| PoseNet          | 545 ms  | 241 ms  |
Configurations: taskset f0 + dylib on local Pixel 4
| Model            | Before  | After   |
| ---------------- | ------- | ------- |
| DeepLabV3        | 358 ms  | 161 ms  |
| MobileBertSquad  | 376 ms  | 376 ms  |
| MobileNetV2      | 65.6 ms | 29.8 ms |
| MobileNetV3Small | 20.7 ms | 15.7 ms |
| MobileSSD        | 94 ms   | 79.9 ms |
| PoseNet          | 183 ms  | 121 ms  |
> Heuristically pick up tiling sizes to vectorize Linalg operations.

- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree-dialects/lib/Dialect/PyDM/Transforms/Optimize/LocalPropagateTypes.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/LowerGlobalTensors.cpp
- iree/compiler/Dialect/Flow/IR/PartitionableLoopsInterface.cpp
- iree/compiler/Dialect/Stream/Conversion/FlowToStream/ConvertFlowToStream.cpp
- iree/compiler/Dialect/Stream/Transforms/AnnotateDispatchArguments.cpp
- iree/compiler/Dialect/Stream/Transforms/FoldUniformOperands.cpp
- iree/compiler/Dialect/Stream/Transforms/FuseDispatchBindings.cpp
- iree/compiler/Dialect/Stream/Transforms/SpecializeDispatches.cpp
- iree/compiler/InputConversion/MHLO/LegalizeInputTypes.cpp
* Reset third_party/llvm-project: a54d028895c91da356a4aaf30e27a5a5b90dd313 (2022-03-09 17:04:18 -0500): Revert "[libc++] Remove extension to support allocator<const T>"
MHLO commit : f52e7dc1210dead4d3ff416696cad1c794332959
TF Commit : 58b667263ba5734ba175a7640f1a1d572e52bd3d
Piper CL : 433732413
> Integrate llvm-project at a54d028895c91da356a4aaf30e27a5a5b90dd313

- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
Fix bug due to some convolution ops not being distributed to threads
> [CUDA] Make sure all linalg ops are distributed to thread

- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
llvm integrate changed the syntax of this op
> Fix linalg.fill syntax in test pushed right before integrate

- .github/workflows/build_package.yml
I expect this will just work but need to check tomorrow.
Fixes: #7444
> Add Python 3.10 to release builds.

- iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
[TSan report](https://gist.github.com/bjacob/406a0b67469cc73a0cc893b3b3170e48)
> fix data race in `HALDispatchABI::getProcessorType`

- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
Fixes https://github.com/google/iree/issues/8500
> Enable alwaysAliasingWithDest in IREE comprehensive bufferization.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/LinalgTransformOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/peel.mlir
Co-authored-by:: Matthias Springer <springerm@google.com>
> Add peel_loop_op to transform dialect

- benchmarks/TFLite/CMakeLists.txt
Adds a quantized MobileBert model and updates the existing float MobileBert model.
> Add MobileBert Benchmarks

- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/ListenerGreedyPatternRewriteDriver.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
> Fix iree-dialects builds for MSVC.

- iree/compiler/Codegen/Common/ForOpCanonicalizationPass.cpp
- iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorToCooperativeOps.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
Switch to prefixed accessors preparing for upstream switch.
> Switch Vector dialect to prefixed accessors

- iree/task/BUILD
- iree/task/CMakeLists.txt
- iree/task/executor_demo.cc
- iree/task/executor_test.cc
- iree/task/task.c
I was hoping this would help diagnose #8683 but it doesn't seem to for me locally. Maybe the bots will have more luck triggering it (though we don't have stacks...).
> Adding some stress tests for the task executor.

- iree/tools/iree-e2e-matmul-test.c
* more refined taste in emoji choices.
* add an additional space to separate columns, so it's more clear that the emojis refer to what's on their left.
* align columns of the 'expected' and 'actual' matrices
* iree_max is a macro that evaluates args twice. dont pass expensive
function calls to it.
* use NULL not 0. Thanks to this advanced strong typing feature of the C
language, pointer unsafety bugs can be almost entirely eliminated.
> e2e matmul tests output formatting improvements

- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgTransform/Transforms/ExpertExpansion.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgTransform/Transforms/TransformInterpreter.cpp
- integrations/tensorflow/iree_tf_compiler/MHLO/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/SavedModelToIreeABI.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/BUILD
- iree/compiler/Codegen/Common/BufferizationAnalysis.cpp
- iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/Common/OptimizeVectorTransferPass.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUPipelining.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp
- iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/PDL.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Transforms/ExpertExpansion.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Transforms/TransformInterpreter.cpp
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/double-tiling.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/pad.mlir
* llvm-project: c531171d995728f55e5775d354a21dceed03edce
* mlir-hlo: 285a97eaf56c7e1a736a95692b011aa6050445d4
* tensorflow: 74f10638c01d2c76a06a5be92a88ada04be0fea5
Extra changes:
* Update vector member getters names
* Disable padding patterns due to interface changes
* Fix iree_tr_compiler bazel dependency
> Integrate llvm-project at c531171d995728f55e5775d354a21dceed03edce

- CMakeLists.txt
- build_tools/benchmarks/CMakeLists.txt
- build_tools/benchmarks/common/CMakeLists.txt
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/common_arguments.py
- build_tools/benchmarks/common/common_arguments_test.py
- build_tools/benchmarks/common/linux_device_utils.py
- build_tools/benchmarks/common/linux_device_utils_test.py
- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
- Add utils to get Linux device information.
- Move common arguments to its own module.
> Initiate the benchmark script for Linux

- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/TilingExternalModels.cpp
* Reset third_party/llvm-project: 567a979ea8099b221af9dae08f1f4973c8c2f003 (2022-04-01 15:27:32 +0200): fix bazel build after 369337e3c2
Extra changes:
* Fix linalg::makeTiledShape signature
> Integrate llvm-project at 567a979ea8099b221af9dae08f1f4973c8c2f003

- iree/compiler/Dialect/Util/Transforms/ApplyPatterns.cpp
Improves error messages for #8752.
> Adding an error message when iree-util-apply-patterns fails.

- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
Fixes https://github.com/google/iree/issues/8680
> [vulkan] Enable passing MHLO round test

- iree/compiler/Dialect/Flow/Transforms/InitializeEmptyTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/initialize_empty_tensor.mlir
Only dynamic sizes should be included in the size list.
Fixes #8717
> Fix for InitializeEmptyTensors

- iree/compiler/Dialect/Flow/Conversion/TensorToFlow/ConvertTensorToFlow.cpp
- iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/from_elements.mlir
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
This would have caught the bug fixed by #8772.
> [flow] Verify the dynamic dims for all ShapeAwareOp's

- iree/compiler/InputConversion/MHLO/MHLOToLinalgOnTensors.cpp
- iree/compiler/InputConversion/MHLO/test/BUILD
- iree/compiler/InputConversion/MHLO/test/CMakeLists.txt
- iree/compiler/InputConversion/MHLO/test/mhlo_to_linalg.mlir
Also add a test.
Fixes https://github.com/google/iree/issues/4985
> Remove redundant linalg.fill op in mhlo.concatenate -> Linalg lowering.

- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/PDL.cpp
llvm-project: 50de659adcc1
mlir-hlo: 8a045602c94dffa19c8367d8feb7c40d8f885b1f
tensorflow: ac02b22cd1cd0f2c7cf01d0f94c3dc0f53550d62
> Bump LLVM to 50de659adcc1

- iree/compiler/Codegen/Sandbox/BUILD
- iree/compiler/Codegen/Sandbox/CMakeLists.txt
- iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- iree/compiler/Codegen/Sandbox/Passes.h
- iree/compiler/Codegen/Sandbox/Passes.td
This follows the fixes in MLIR changes: https://github.com/llvm/llvm-project/commit/58d0da885ef46e3fdb5247295da7898b377c41e1
> Proper fixes for padding in IREE CodegenStrategy

- iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
> Modify elementwise fusion for changes in D123236.

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
Also fix wrong Pixel 6 name there..
> [ci] Publish source MLIR modules after benchmark compilation

- iree/base/internal/synchronization.c
- iree/base/internal/synchronization.h
The mix of atomic/futex and pthreads operations made it hard to know
when the pthread mutex should be locked and when atomics were ok. The
disabled synchronization path that no-op'ed also obscured the intended
behavior. Now we have the divergent code split up more cleanly so that
we can more easily inspect it for correctness.
iree_notification_await is left shared across the implementations to
preserve program behavior (that the condition is not checked with
a lock held) though we could probably tweak that if we wanted. Erring
on the side of keeping things the same for now.
Integrates the fix from #8876.
> Rearranging iree_notification_t code to make it easier to follow (and fixing a deadlock/hang when using pthreads).

- docs/developers/developing_iree/developer_overview.md
- iree/hal/local/executable_library_benchmark.md
- iree/samples/custom_modules/dialect/custom-translate-main.cc
- iree/tools/iree-run-mlir-main.cc
- iree/tools/iree_compile_lib.cc
- iree/tools/iree_translate_lib.cc
- llvm-external-projects/iree-compiler-api/python/iree/compiler/tools/core.py
- llvm-external-projects/iree-compiler-api/python/iree/compiler/tools/debugging.py
- scripts/ir_to_markdown.py
Following https://github.com/google/iree/pull/8860 (which includes https://reviews.llvm.org/D123495)
> Update -mlir-print-ir-* flag names in comments and scripts.

- iree/base/internal/threading_test.cc
- iree/base/internal/wait_handle_test.cc
Fixes the iree/base entries in #8453.
> Fix TSan failures in iree/base tests.

- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_suite.py
- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
Implement Linux benchmark tool, similar to `run_benchmarks_on_android.py`.
> Implement Linux benchmark tool

- build_tools/cmake/iree_benchmark_suite.cmake
- build_tools/cmake/iree_bytecode_module.cmake
This isn't strictly a NFC. `iree_benchmark_suite` was printing a custom `COMMENT` (build progress info label) that was a `;`-separated cmake list printed as a string. That was error-prone to forward down one function (to `iree_bytecode_module`), but below I found that this list was already being joined to form `_FRIENDLY_TARGET_NAME` so I just moved that up and used that. It's arguably less pretty than the original list but it's also good to be more explicit -- now the name as printed is an actual target name. And the old pretty form didn't give a hint about what directory was doing this work.
> Let `iree_benchmark_suite` use `iree_bytecode_module`.

- iree/compiler/Codegen/Common/DestructiveUpdateUtils.cpp
- iree/compiler/Codegen/Common/test/rewrite_linalg_destructive_updates.mlir
Current handling of destructive update rewrites does not handle cases
like argmax, where the max value itself might not have uses outside
the dispatch, but is required for internal use. This resulted in
excessive stack allocation. Making destructive update rewrite handle
such cases will reduce the stack size that is bounded by the tile size.
Ideally with vectorization this stack would also go away, but this
should prevent failures due to excessive stack usage.
Fixes #8411
> Handle values dead outside dispatches in RewriteDestructiveUpdate.

- docs/developers/best_practices.md
- docs/developers/developing_iree/benchmarking.md
- docs/developers/developing_iree/developer_overview.md
- docs/developers/get_started/building_with_bazel_linux.md
- docs/developers/get_started/building_with_bazel_macos.md
- docs/developers/get_started/building_with_bazel_windows.md
- docs/website/docs/bindings/c-api.md
- docs/website/docs/building-from-source/android.md
- docs/website/docs/building-from-source/riscv.md
- docs/website/docs/deployment-configurations/bare-metal.md
- docs/website/docs/extensions/index.md
Reflect https://github.com/google/iree/pull/8958
> Cleanup doc reference of iree/samples/ --> samples/

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/BUILD
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/comparison_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/list_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/list_ops_i64.mlir
* Add tests for list ops
* Add tests for list i64 ops
* Add tests for comparison ops
* Add tests for control flow ops
> Add tests for VM to EmitC conversions

- benchmarks/README.md
- build_tools/benchmarks/README.md
Add docs for benchmark suites and tools.
> Add docs for benchmark suites and tools.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
- samples/iree_static_library/CMakeLists.txt
Progress on https://github.com/google/iree/issues/8954
> [EmitC] Don't emit unused variables in import shims

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/test/dispatch_tensor_folding.mlir
Dispatch tensor load may ellide length-1 dimensions. The rank matching
version does not guarantee to drop the same length-1 dimensions and must
be tweaked.
> Fix dispatch load tensor result type inference in canonicalizer

- iree/compiler/Codegen/SPIRV/AppleConfig.cpp
- iree/compiler/Codegen/SPIRV/BUILD
- iree/compiler/Codegen/SPIRV/CMakeLists.txt
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/KernelConfig.h
-Add tuned apple M1 Config for spirv backend
> Add Apple M1 Config on spir-v

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
This commit revisits the pipeline to reorder passes better. We want to
convert things to CF (which was called STD dialect in the past) after all the
optimizations and analysis. It's easier to check IRs before converting
them to CF dialect.
Fixes https://github.com/google/iree/issues/9037
> Reorder passes before converting to LLVM dialect.

- .clang-format
- compiler/src/iree/compiler/Bindings/TFLite/Transforms/Passes.h
- compiler/src/iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
Follow-up to https://github.com/google/iree/pull/9022
> Run clang-format on compiler/.

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
This removes the special handling of global ops in the VMToEmitC conversion.
> [EmitC] Cleanup conversion of global ops

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tile-to-in-parallel.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tile-to-sequential-for.mlir
> Fix parser and test for LinalgExt ops

- iree/test/e2e/linalg_ext_ops/top-k.mlir
Addressing @hanhanW comment before https://github.com/google/iree/pull/9090 was merged.
> IREE LinalgExt TopK e2e test with repeat values. 

- compiler/src/iree/compiler/Codegen/Common/BufferizeCopyOnlyDispatchesPass.cpp
- compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/bufferize_copy_only_dispatches.mlir
- compiler/src/iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
> Use upstream bufferization to bufferize copy only dispatches.

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/GPUPipelining.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToNVVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/vector_to_gpu.mlir
- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
Cherry-pick the changes in order to patch iree changes ahead of integrate:
* 15bcc36eede13b24470e554dfa932f1fc40dd4ba
* 09fc685ce6808ae34de8e235bad686252eef3812
> Cherry-pick mlir changes related to nvgpu async op

- compiler/src/iree/compiler/Codegen/Common/test/insert_distribution_info.mlir
- compiler/src/iree/compiler/Codegen/Common/test/remove_trivial_loops.mlir
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/Dialect/test/lowering_config_attr.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/illegal_configuration.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute_scatter.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute_sort.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_to_cooperative_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/convert_to_hal.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/dump_executable_benchmarks.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/dump_executable_sources.mlir
The comma was not scaling to other fields see https://github.com/google/iree/pull/9114
> Remove comma between fields in LoweringConfig assemblyFormat

- compiler/src/iree/compiler/Dialect/HAL/IR/HALBase.td
- compiler/src/iree/compiler/Dialect/HAL/IR/HALTypes.cpp
- compiler/src/iree/compiler/Dialect/HAL/IR/HALTypes.h
- compiler/src/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
This functionality was moved into the stream resource constraints attr.
> Removing unused HAL buffer constraints attr.

- compiler/src/iree/compiler/Dialect/Stream/IR/StreamTypes.cpp
This changes the default max allocation size to INT64_MAX as part of
#8661. There's some rough edges around a program that is right on the
32-bit boundary but those are rare enough that until affinities are
plumbed through in #8042 it's ok to ignore.
Progress on #8661.
> Adding flags for controlling stream resource constraints.

- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/mhlo_to_mhlo_preprocessing_canoncalize_dot_general.mlir
> Propagate attribute in mhlo pre-processing of dot_general op

- compiler/src/iree/compiler/Dialect/VM/Target/C/TranslateToCpp.cpp
Adopts llvm/llvm-project@84fe39a.
> Add support for the EmitC cast op

- samples/vulkan/vulkan_inference_gui.cc
I really need to just delete/move this sample (https://github.com/google/iree/issues/8011).
> Fix data type in vulkan_inference_gui.

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/pipeline_tests.mlir
- compiler/src/iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
This is only available through flags because we may not want huge stack
allocation. It needs more exploration about if it is a good approach.
Adding an option to IREE to enable more performance work.
> Add a flag to enable hoist padding for DoubleTilingPadExpert pipeline.

- compiler/src/iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertExecutableOps.cpp
- compiler/src/iree/compiler/Dialect/HAL/Conversion/HALToVM/test/executable_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Target/VMVX/test/smoketest.mlir
- compiler/src/iree/compiler/Dialect/VM/Conversion/MemRefToVM/ConvertMemRefToVM.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/MemRefToVM/test/load_store_ops.mlir
- compiler/src/iree/compiler/Dialect/VM/IR/VMBase.td
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.h
- runtime/src/iree/vm/bytecode_disasm.c
- runtime/src/iree/vm/bytecode_dispatch.c
- runtime/src/iree/vm/bytecode_dispatch_util.h
- runtime/src/iree/vm/bytecode_module_benchmark.mlir
- runtime/src/iree/vm/bytecode_module_impl.h
- runtime/src/iree/vm/test/buffer_ops.mlir
Fixes #9157.
Progress on #8661.
> Extending vm.buffer offsets to 64 bits.

- build_tools/buildkite/scripts/update_pipeline_configurations.py
> Update pipelines correctly

- build_tools/buildkite/pipelines/trusted/postsubmit.yml
- build_tools/buildkite/pipelines/trusted/presubmit.yml
- build_tools/buildkite/pipelines/untrusted/test-pipeline.yml
- build_tools/buildkite/pipelines/untrusted/unregistered.yml
Demo of how to add a new pipeline and a test that it works. Note that
the new test-pipeline configuration runs as part of the "unregistered"
pipeline, since it's not yet registered with Buildkite. After
submission, I'll need to mark the newly-created pipeline as public and
give access to run it on presubmit, as noted in
https://github.com/google/iree/tree/152619e3e9/build_tools/buildkite#making-pipeline-public
Successful run: https://buildkite.com/iree/presubmit/builds/136
> Demo adding a new pipeline

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/PadDynamicAlloc.cpp
- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/pad_dynamic_alloc.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
Re-use the pass already ran by LLVMGPU pipelines.
> [SPIRV] Run pad alloc pass in spirv

- compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp
TEST: Builds on Clang15 with this fix
> Fix unused var for clang-15

- compiler/src/iree/compiler/API/test/compile-mhlo-test-main.c
- compiler/src/iree/compiler/Codegen/Passes.h
- runtime/src/iree/runtime/session.h
- runtime/src/iree/vm/context.h
> correct comment spelling

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DumpDispatchGraph.cpp
Issue: https://github.com/google/iree/issues/9272
Now it dumps the contents of each dispatch including linalg generic.
Example: [dispatch.pdf](https://github.com/google/iree/files/8846702/dispatch.pdf)
> Dump dispatch body content

- integrations/tensorflow/WORKSPACE
* llvm-project: dd2362a8bab3
* mlir-hlo: 9730add939ef043681fadfb225ec99be01072bce
* tensorflow: faed056f873754457b5c05aed5a9739fcd6bf35c
> Integrate llvm-project and bump dependencies

- tests/e2e/xla_ops/fft.mlir
Fixes https://github.com/google/iree/issues/7919
> Enable passing FFT tests

- runtime/src/iree/hal/drivers/local_task/task_semaphore.c
Verified with the repro in the issue.
Fixes #9392.
> Fixing race on semaphore timepoint cancellation.

- compiler/src/iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- integrations/tensorflow/WORKSPACE
Integrate llvm-project and bump dependencies
* llvm-project: ae10b8a58240
* mlir-hlo: fe72ce4d1ccd7ec45221f12df53ee3ecaf1e1503
* tensorflow: b850675007f209cf8e4fa7d9d948bc9a426313dc
[mhlo] fix a compilation error due to a renaming in the upstream
> Bump llvm 20220609 2

- compiler/src/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- compiler/src/iree/compiler/Dialect/Vulkan/IR/BUILD
- compiler/src/iree/compiler/Dialect/Vulkan/IR/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Vulkan/IR/VulkanAttributes.cpp
- compiler/src/iree/compiler/Dialect/Vulkan/IR/VulkanAttributes.h
- compiler/src/iree/compiler/Dialect/Vulkan/IR/VulkanAttributes.td
- compiler/src/iree/compiler/Dialect/Vulkan/IR/VulkanBase.td
- compiler/src/iree/compiler/Dialect/Vulkan/IR/test/target_env.mlir
- compiler/src/iree/compiler/Dialect/Vulkan/Utils/TargetEnvironment.cpp
- compiler/src/iree/compiler/Dialect/Vulkan/Utils/TargetTriple.cpp
StructAttr is deprecated and will be removed soon.
> NFC: Update Vulkan attributes to use AttrDef

- integrations/tensorflow/WORKSPACE
* llvm-project: 25c8a061c573
* mlir-hlo: efdd27d201bca052a6dd75a14e5fae1630b93a2c
* tensorflow: b2e47930ce1769f5eb70ebb8ce6332b556ee20c9
> Integrate llvm-project at 25c8a061c573 and bump dependencies.

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/TransformInterpreter.cpp
TransformState::applyTransform requires that the parent region is a
proper ancestor of the transform op to perform SSA liveness assertions.
In multithreaded state however, we cannot clone into `transformRegion` so
we build a new single-block region and clone the transform op into it.
This fixes assertion failures that are only visible when LLVM_ENABLE_ABI_BREAKING_CHECKS is defined.
> Fix transform dialect op cloning.

- compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/ProcessorOpInterfaces.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectExtensions/TransformDialectExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/PartitionableLoopsInterface.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilAttrs.cpp
- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/TransformInterpreter.cpp
* llvm-project: 4191de262f19
* mlir-hlo: 82295d4a47236b17da63692a89275952abbfdabc
* tensorflow: 7e779eb8abc4035eca086691ec36c19e02e6409b
> Integrate llvm-project at 4191de262f19 and bump dependencies.

- CITATION.cff
Based off of the suggestions in #9513.
> Add a CITATION.cff file.

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorLowering.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/warp_reduction.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- tests/e2e/regression/BUILD
- tests/e2e/regression/CMakeLists.txt
- tests/e2e/regression/large_reduction.mlir
Use vector distribution to implement warp reduction.
> [LLVMGPU] Add a lowering pipeline for warp reductions

- build_tools/benchmarks/comparisons/mobilebert_fp32_commands.py
- build_tools/benchmarks/comparisons/mobilenetv2_fp32_commands.py
- build_tools/benchmarks/comparisons/mobilenetv2_uint8_commands.py
- build_tools/benchmarks/comparisons/run_benchmarks.py
- build_tools/benchmarks/comparisons/setup_mobile.sh
* Add mobilenet f32 and uint8 (randomly chosen between it and int8);
* Expand setup script to build more;
- Needed to update a dir or two post local-task renaming;
- I haven't rerun this script from scratch (was updated as I went
along) as it builds quite a lot during but "it should work";
* Add noxnn variant for mobilebert to check hypothesis;
> Add mobilenet to benchmarks

- build_tools/cmake/build_riscv.sh
- build_tools/cmake/riscv.toolchain.cmake
- build_tools/embed_data/generate_embed_data_main.cc
* Update the riscv build default compilation optimization level to `-O3`
* Fix `generated_embed_data` default alignment to align with 512b
> Update riscv build default

- compiler/src/iree/compiler/Codegen/Common/FoldAffineMinInDistributedLoops.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/TransformOpInterface.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.cpp
This revision cherry-picks the following LLVM commits:
* 6759f5807b631e473e9346ef07ef3d0361710f53
* 7af43d43dc0c510f6e88f59721929b1a6fc33c18
* b8fe5e0547bd03f11edbebdc3f0922350cec779d
* 4c7225d19a9d1ff62c0ae39049ca3afe2a46c571
and provides the necessary fixes.
> Prefetch a few LLVM commits and fix incoming issues

- compiler/src/iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
Fixes https://github.com/google/iree/issues/9361
> Don't mark scatter illegal to avoid partial function application failing

- compiler/src/iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertAllocatorOps.cpp
- compiler/src/iree/compiler/Dialect/HAL/Conversion/HALToVM/test/allocator_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StandardToHAL/test/shape_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StandardToHAL/test/structural_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/ConvertStreamToHAL.cpp
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/test/cmd_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/test/resource_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/test/timepoint_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/test/transfer_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/UtilToHAL/test/global_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/IR/HALOps.cpp
- compiler/src/iree/compiler/Dialect/HAL/IR/HALOps.td
- compiler/src/iree/compiler/Dialect/HAL/IR/test/allocator_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/test/BUILD
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/test/smoketest_embedded.mlir
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/test/smoketest_system.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/HAL/hal.imports.mlir
- compiler/src/iree/compiler/Dialect/Stream/Transforms/VerifyLowerings.cpp
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.h
- runtime/src/iree/modules/hal/exports.inl
- runtime/src/iree/modules/hal/module.c
- runtime/src/iree/vm/bytecode_module_impl.h
Better late than never?
Fixes #7277.
> Taking care of tech debt from the stream dialect landing.

- runtime/src/iree/hal/drivers/vulkan/vulkan_driver.cc
This updates enumeration and selection by index to respect whether a device is hidden, based on some characteristics. Since we've had continuous problems with lavapipe as a compute device (and since, when accidentally using since it is often installed by default, it spews stderr warnings about only being for testing), I opted to make this the first heuristic for hiding a device.
Broken out of #9330.
> Refactor vulkan device creation to allow hidden devices and make lavapipe hidden.

- compiler/src/iree/compiler/Codegen/Common/BufferizationAnalysis.cpp
- compiler/src/iree/compiler/Codegen/Common/CleanupBufferAllocViewPass.cpp
- compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp
- compiler/src/iree/compiler/Codegen/Common/DestructiveUpdateUtils.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUPipelining.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVCreateFastSlowPath.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizePad.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/ConvertTensorToFlow.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformDialectExtensions/TransformDialectFlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/PadTensorToTensorInsertSlice.cpp
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StandardToHAL/ConvertShapeOps.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/SpecializeDispatches.cpp
- compiler/src/iree/compiler/Dialect/VM/Target/C/TranslateToCpp.cpp
In preparation for upstream flip.
> Flip accessors used to prefixed form (NFC)

- third_party/llvm-project.branch-pin
* [mlir][spirv] Fix bitcast input order for UnifyAliasedResourcePass
> [spirv] Cherry-pick MLIR fixes for UnifyAliasedResourcePass

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
> Disable warp reduction for non CUDA LLVMGPU backends

- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__complex_dynamic_dim_count_nonzero.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__complex_dynamic_dim_l2_normalize.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__dynamic_dim_count_nonzero.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__complex_dynamic_dim_count_nonzero.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__complex_dynamic_dim_l2_normalize.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__digamma.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_accumulate_n.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_add_n.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_count_nonzero.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_digamma.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_mod.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__mod.run
Fixes https://github.com/iree-org/iree/issues/5400
A few tests are still failing though.
SwiftShader: [full logs](https://source.cloud.google.com/results/invocations/10d9e5b2-f415-4fa5-abb0-bdb855b8dcc3/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-swiftshader%2Fpresubmit/log)
```
Failed Tests (2):
TENSORFLOW_TESTS :: iree_tf_tests/math/vulkan__dynamic_dim_accumulate_n.run
TENSORFLOW_TESTS :: iree_tf_tests/math/vulkan__dynamic_dim_add_n.run
```
NVIDIA Turing: [full logs](https://source.cloud.google.com/results/invocations/20c4bec6-ccce-4787-81ac-993068c1804a/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-turing%2Fpresubmit/log)
```
Failed Tests (2):
TENSORFLOW_TESTS :: iree_tf_tests/math/vulkan__dynamic_dim_mod.run
TENSORFLOW_TESTS :: iree_tf_tests/math/vulkan__mod.run
```
> Re-enable some passing TF tests.

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.h
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
- compiler/src/iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
> Remove export ops during EmitC conversion

- .github/workflows/build_package.yml
There's a misconfiguration on the runners.
Reverts iree-org/iree#9432
> Revert "Make release run on self-hosted GitHub runners"

- docs/website/docs/CNAME
Add CNAME for serving docs from iree.dev.
> Create CNAME for github serving

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCBuilders.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCBuilders.h
* Add utility function for `EMITC_STRUCT_MEMBER`
* Add utility function for `EMITC_STRUCT_PTR_MEMBER_ASSIGN`
* Add utility function for `EMITC_STRUCT_MEMBER_ASSIGN`
* Add utility function for `iree_vm_ref_release`
* Add utility function for `iree_ok_status`
* Add utility function for `EMITC_ARRAY_ELEMENT_ADDRESS`
> Add utility functions for VM to EmitC conversion

- compiler/src/iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
Subspans are different when the result types are different.
> [bufferize] check if the memref types are the same for subspans

- tests/e2e/xla_ops/BUILD
- tests/e2e/xla_ops/CMakeLists.txt
Part of https://github.com/iree-org/iree/issues/6601
> Enable passing fft tests for VMVX backend.

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/HAL/IR/test/attributes.mlir
- compiler/src/iree/compiler/Dialect/HAL/Target/VMVX/test/smoketest.mlir
- compiler/src/iree/compiler/InputConversion/MHLO/BroadcastingToLinalgPatterns.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/ForeachThreadToSequentialFor.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Utils.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/fuse-in-containing-op.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/fuse-operands.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling-to-foreach-thread-op.mlir
- tests/e2e/models/unidirectional_lstm.mlir
- tests/e2e/xla_ops/dynamic_update_slice.mlir
LLVM integrate
MLIR-MHLO: 7365a774d0c772e5a032ac0d36a1d532f17860f3
LLVM: ebb78a95cede526ece9b904e9ba623d4b963df60
Additionally cherry-picks the following IREE-local revert by dcaballe@:
* This reverts commit 1178992c72b002c3b2c87203252c566eeb273cc1
>     LLVM integrate to ebb78a95cede526ece9b904e9ba623d4b963df60 + cherry-pick

- docs/website/docs/CNAME
This reverts commit 562608470245bb4a0c7c775c24b96de685a44d17.
> Revert "Revert "Create CNAME for github serving" (#9732)"

- build_tools/benchmarks/common/benchmark_presentation.py
- build_tools/benchmarks/diff_local_benchmarks.py
- build_tools/benchmarks/post_benchmarks_as_pr_comment.py
Reads the baseline of compilation metrics from dashboard and includes in the comparison.
> Include the baseline compilation metrics in the report

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DumpDispatchGraph.cpp
Issue https://github.com/iree-org/iree/issues/9699.
There can be multiple entry points or a wrapper function. So draw all func ops.
> [flow] handle multiple func ops for dispatch graph

- tests/e2e/xla_ops/BUILD
- tests/e2e/xla_ops/CMakeLists.txt
Fixes https://github.com/iree-org/iree/issues/9617
> [spirv] Enable passing round.mlir test

- compiler/src/iree/compiler/Dialect/Modules/VMVX/README.md
Fix some broken documentation links
> Fixed document links in vmvx readme

- compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
> Use memref type with static identity layout around ConstantOp

- compiler/src/iree/compiler/Codegen/LLVMGPU/test/warp_reduction.mlir
Patch needed to get group reduction to work.
> Cherry-pick mlir commit 0660f3c5a0a083cef78f39b3105a9a8e27cf5095

- integrations/tensorflow/WORKSPACE
- third_party/llvm-project.branch-pin
* Reset third_party/llvm-project: bc432c96349c1b0a381b824f11b057ff0de0b571 (2022-07-15 04:37:28 +0000): [gn build] Port 7ced9fff9547
* Update MHLO and TensorFlow to track llvm/llvm-project@bc432c96349c
* tensorflow/mlir-hlo@7584a6c
* tensorflow/tensorflow@197cae8
> Integrate llvm-project at bc432c96349c

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
When the dispatch has no compute ops, fallback to use a workgroup
count of {1, 1, 1}. The current configuration selection already picks
the `CPUDefault` pipeline. With this change this will compile
dispatches that dont have compute ops to use a default sequential
lowering.
Fixes #9749
> Add fallback of setting workgroup count to {1, 1, 1}.

- integrations/tensorflow/WORKSPACE
* llvm-project: 32a425ec0c10
* mlir-hlo: 518b1598aaf391d3b6d22b3282fa0a5ea128182c
* tensorflow: 46152aac7417aa0d1506b782e055448f431e1629
> Integrate llvm-project at 32a425ec0c10 and bump dependencies.

- docs/website/docs/community/index.md
The custom dialect example was removed as also done upstream.
> Update information on IREE C++ Template

- compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td
- compiler/src/iree/compiler/Dialect/VM/IR/test/comparison_folding.mlir
- compiler/src/iree/compiler/Dialect/VM/IR/test/comparison_ops.mlir
- compiler/src/iree/compiler/Dialect/VM/IR/test/control_flow_folding.mlir
- runtime/src/iree/vm/test/comparison_ops_f32.mlir
Follow-up to https://github.com/google/iree/pull/7080, depends on https://github.com/iree-org/iree/pull/9799
Fixes https://github.com/google/iree/issues/5854
> Add vm.check.nearly_eq and vm.cmp.eq.f*.near pseudo ops.

- runtime/src/iree/task/task.c
* These atomics were already accessed with acquire/release order at various places.
* I audited the places where they were accessed other other memory orders and changed them as follows:
- Some places used seq_cst but that didn't seem necessary. Changed to acquire/release, and in one case relaxed (for the comparison-failure case in a compare_exchange as the loaded value was unused).
- Some places used relaxed but it wasn't immediately clear that that was sufficient ordering. Changed to acquire/release - we can keep them relaxed if that's performance-critical and you can see why relaxed was sufficient.
> Tweaks to atomics in `iree_task_*` - use acquire/release consistently.

- runtime/src/iree/task/scope.c
This is mostly changing some unnecessary seq_cst to acquire/release consistently with what other accesses were already doing.
One compare_exchange here was actually relying on ordering of the load operation in the compare-failure mode, so this is carefully changed to acquire, not relaxed.
Also added a comment justifying an existing relaxed access.
> Tweaks to atomics in `iree_task_scope_*` - use acquire/release consistently

- .github/CODEOWNERS
I'm tired of manually adding reviewers :stuck_out_tongue:
> Add @pzread to infra CODEOWNERS

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUAArch64VectorLowering.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
* llvm-project: 0a715c114686
* mlir-hlo: 343bfc439412f37751f21d157711b7cf50ad56ef
* tensorflow: 9ac476aeb38df3ed0d6dfd616a335c2a982a9574
> Integrate llvm-project at 0a715c114686 and bump dependencies.

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
This is in preparation of a subsequent commit that introduces
init_tensor elision.
> [NFC] Simplify bvm mapping in FlowExtensions.cpp

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCBuilders.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCBuilders.h
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.h
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/func_op.mlir
Additionally refactor type conversion.
> [EmitC] Add builders for `&` and `*` operators

- compiler/src/iree/compiler/Dialect/Util/IR/UtilTypes.h
Progress on #9896 (no more stream issues, can get to failures in executable translation).
> Adding support for complex types in size calculations.

- compiler/src/iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertExecutableOps.cpp
- compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.td
- compiler/src/iree/compiler/Dialect/Util/Conversion/ConversionPatterns.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilInterfaces.td
- compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.td
- compiler/src/iree/compiler/Dialect/Util/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Util/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Util/Transforms/PropagateSubrange.cpp
- compiler/src/iree/compiler/Dialect/Util/Transforms/test/propagate_subranges.mlir
- compiler/src/iree/compiler/Dialect/VM/Conversion/ImportUtils.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/ImportUtils.h
- compiler/src/iree/compiler/Dialect/VM/Conversion/TargetOptions.h
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/ConvertUtilToVM.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td
- compiler/src/iree/compiler/Dialect/VM/IR/test/comparison_folding.mlir
- compiler/src/iree/compiler/Dialect/VM/Transforms/Passes.cpp
These fix some issues, improve diagnostics, and improve the pass pipeline to remove more junk.
> Roll-up of improvements to the VM dialect.

- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
> Setting insertion point for memref subview expansion.

- build_tools/benchmarks/upload_benchmarks_to_dashboard.py
Now we have the website properly handling units, avoid
hardcoding it further.
> Fix benchmark website explanation

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
It has nothing to do with Samsung Galaxy. :)
> Fix capture artifact name for Moto Edge X30

- .github/workflows/ci.yml
- build_tools/cmake/build_tf_binaries.sh
- build_tools/cmake/run_tf_tests.sh
- integrations/tensorflow/symlink_binaries.sh
I've had to disable Vulkan tests due to
https://github.com/iree-org/iree/issues/9936
Part of https://github.com/iree-org/iree/issues/9855
> Build and test TF integrations

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
If we go down the vectorization path, all large n-D vectors would
be eventually broken down and unrolled to native 1-D vectors.
This can generate a large amount of instructions if we have shapes
like `vector<128x1x1x4xf32>`. Such vector shapes can be generated
from tensors with more parallel dimensions than we can distribute,
e.g., `tensor<128x8x256x4xf32>`. So this commit adjusts configuration
to also tile the remaining parallel dimensions not distributed
to avoid instruction bloat.
> [spirv] Tile parallel dimensions after thread distribution

- compiler/src/iree/compiler/Codegen/LLVMCPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
> Add Complex to LLVM lowering patterns to CPU backend.

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/ConvertToLoops.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/Tiling.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/TilingToForeachThreadOp.cpp
To satisfy dependencies also cherry-pick
- 08a1b07e7c19d14896f8be501c763ba8aff5b427
- 70e99f387a482bfe0ad2b7accc88e9e8b2a4a59d
- e99fae899710b041994cef4beb6764f8dfbe8ef0
- ea460b7ddb8adc9c9c48a968f1155d8757849d76
> Cherry pick 6f03a10e4fdb4f22651a9dcc5d6ab318724235e8

- integrations/tensorflow/iree_tf_compiler/TF/LowerGlobalTensors.cpp
> Early inc to avoid invalidation

- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Transforms/DumpExecutableBenchmarks.cpp
- compiler/src/iree/compiler/Dialect/HAL/Transforms/DumpExecutableSources.cpp
- compiler/src/iree/compiler/Dialect/HAL/Transforms/SerializeExecutables.cpp
- compiler/src/iree/compiler/Dialect/Util/Analysis/DFX/Solver.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/ConvertStatusOps.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/DebugDatabaseBuilder.cpp
- compiler/src/iree/compiler/Dialect/VM/Transforms/DeduplicateRodata.cpp
- compiler/src/iree/compiler/Dialect/VM/Transforms/GlobalInitialization.cpp
Deprecation warning was added here: https://reviews.llvm.org/D130140
> Using `llvm::Optional::value_or` instead of deprecated `getValueOr`.

- .github/workflows/ci.yml
Due to multiple PRs touching this file at once, the digests somehow
didn't get updated.
> Update docker digests in CI workflow

- integrations/tensorflow/iree_tf_compiler/TF/test/lower_global_tensors.mlir
This would fail with both ASAN and TSAN.
> Add test for #9978

- compiler/src/iree/compiler/Tools/BUILD
- compiler/src/iree/compiler/Tools/CMakeLists.txt
- compiler/src/iree/compiler/Tools/init_mlir_passes.h
- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: 955cc56af448301e2d353df90ca1f0c6a74118f2 (2022-07-28 14:36:53 +0300): [AMDGPU][GFX1030][DOC][NFC] Update assembler syntax description
> Integrate llvm-project at 955cc56af448301e2d353df90ca1f0c6a74118f2

- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: 58526b2d2be932e893218857cc47a16fb05cf1c0 (2022-07-28 14:58:14 -0700): [GlobalISel] Handle nullptr constants in dbg.value
> Integrate llvm-project at https://github.com/llvm/llvm-project/commit/58526b2d2be9

- compiler/src/iree/compiler/Codegen/LLVMGPU/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/warp_reduction.mlir
Add extra patterns to allow distribution to happen in more complex
cases.
> [llVMGPU] Add missing patterns to reduction lowering

- compiler/src/iree/compiler/Dialect/Util/IR/UtilTypes.cpp
- compiler/src/iree/compiler/Dialect/VM/Transforms/Conversion.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/HALToVMVX/BUILD
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/HALToVMVX/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/HALToVMVX/ConvertHALToVMVX.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/HALToVMVX/test/interface_ops.mlir
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/Conversion.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/Passes.cpp
It is now done as part of VMVX conversion.
> Move memref->buffer conversion out of VM conversion.

- compiler/src/iree/compiler/Codegen/LLVMGPU/VectorReductionToGPU.cpp
Add instrumentation to dump intermediate IR during reduction
distribution.
> [LLVMGPU] NFC add debug instrumentation to reduction distribution

- experimental/web/sample_dynamic/main.c
- experimental/web/sample_static/main.c
- samples/colab/tflite_text_classification.ipynb
Some fallout from https://github.com/iree-org/iree/pull/10017. The cost of code that isn't tested on presubmit :)
This should fix https://buildkite.com/iree/iree-samples/builds/438
> Fix samples after VM changes.

- .github/workflows/ci.yml
Unfortunately this means the whole workflow doesn't run and then we
don't get the required status check :'-(
Going to need to do something else
Reverts iree-org/iree#10057
> Revert "Ignore certain filepaths in CI"

- compiler/src/iree/compiler/Dialect/HAL/IR/HALOpFolders.cpp
- compiler/src/iree/compiler/Dialect/HAL/IR/HALOps.td
- compiler/src/iree/compiler/Dialect/HAL/IR/test/buffer_view_folding.mlir
- compiler/src/iree/compiler/Dialect/HAL/IR/test/buffer_view_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/VMVX/test/linking.mlir
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/materialize_builtins.mlir
- compiler/src/iree/compiler/Utils/ModuleUtils.cpp
> Small tweaks found during stream->hal->vm lowering.

- benchmarks/TFLite/CMakeLists.txt
- benchmarks/TFLite/linux-riscv.cmake
- benchmarks/TFLite/linux-x86_64.cmake
Fixes https://github.com/iree-org/iree/issues/9871
> Add quantized models x86_64 and riscv benchmark suites.

- runtime/src/iree/tooling/device_util.c
If a driver can't be initialized it means it has no devices. Errors when asking for specific devices from a driver will still
be propagated: `--list_devices` will always pass but `--list_devices=driver` will fail if the driver fails.
Fixes #10090.
> Gracefully ignore failed driver inits when listing all devices.

- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
This is a conservative solution to avoid having race conditions when
bufferization decides to emit shared memory copies.
> [LLVMGPU] Add barriers when bufferization inserts shared memory copy

- build_tools/cmake/ctest_all.sh
~ or ~
Better scripting with @GMNGeoffrey
~ or ~
One Does Not Simply Merge a Scripting PR With Only One Approval
~ or ~
Post-merge review comments from #10132.
> Script improvements

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilBase.td
- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: 72136d8ba266eea6ce30fbc0e521c7b01a13b378 (2022-08-19 21:02:07 +0700): [Test] Add test for miscompile described in PR57247
* Update third_party/mlir-hlo to 5e324a40db4aa956f7cbf24e9417557776e7a84f
* Update tensorflow to 8a7764be0d32a72ad6d93ff3216520af184e26a0
* Renamed `Confined` to `ConfinedAttr`
* Updated `flow.dispatch.tensor.{load|store}` op assembly to use `custom<DynamicIndexList>`
* Updated `operand_segment_sizes` to `DenseI32ArrayAttr`
> Integrate llvm/llvm-project@72136d8ba266

- tools/iree-run-module-main.cc
Be more explicit and provide an example.
> [iree-run-module] Clarify how to pass scalar inputs. NFC.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
Minor refactoring to allow for extending fusion heuristics for fusing
root with producers.
> NFC: Refactoring to make extending fusion heuristics in dispatch formation easier.

- .github/workflows/schedule_candidate_release.yml
Make it consistent with the rest of the release steps.
> Update the candidate commitish value with the last green commit

- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tile_on_tensor.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/double-tiling.mlir
* commit 2e34599bfd01e5b20e09bd6af590a52d6a63a64c
* commit 1ee0d60a9be5dcbe3234b81a1c93e6a206a88154
> Cherry-pick llvm/llvm-project@2e34599b and llvm/llvm-project@1ee0d60a

- runtime/src/iree/hal/drivers/webgpu/bind_group_cache.c
- runtime/src/iree/hal/drivers/webgpu/staging_buffer.c
> Fix compilation errors for hal/drivers/webgpu under Emscripten.

- build_tools/github_actions/runner/README.md
- build_tools/github_actions/runner/gcp/canary_update_instance_group.sh
- build_tools/github_actions/runner/gcp/create_templates.sh
- build_tools/github_actions/runner/gcp/update_instance_group.sh
> Update documentation and scripts for vagaries of MIG rolling updates

- build_tools/github_actions/runner/README.md
- build_tools/github_actions/runner/gcp/create_instance_group.sh
- build_tools/github_actions/runner/gcp/remove_idle_runners.sh
> Script the removal of idle runners

- runtime/src/iree/modules/vmvx/module.c
When mapping the 4D buffers using the 2D buffer-mapping macro, I needed to multiply the 3 inner dims sizes together to form the coalesced inner dim of the 2D shape.
Rationalizing this also allowed to write a better explanatory comment: not longer had to make excuses for an "abuse" of the 2D macro.
> Fix mapping of buffers in mmt4d module functions.

- compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingInterface.cpp
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_vmvx_launch_configuration.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_x86_64_launch_configuration.mlir
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/Tiling.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Fusion.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/foreach-thread-to-async.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/foreach-thread-to-scf-for.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
Integrate llvm-project and bump dependencies
* llvm-project: 7e19d53da449
* mlir-hlo: f3d138e80bcfd970e9226870230f65c45a2e3ca6
* tensorflow: b3b9a9f652e85bbfac257dd20ca72a51b7ddf317
This includes:
* update the eraseArguments to use a bitvector
* update the tiling interface accordingly
> Bump llvm 20220901

- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
Enable shared memory swizzle transformation as well as picking a good
unrolling order for tensorcore
> [LLVMGPU] Add shared memory swizzle transformation

- .github/CODEOWNERS
Adding @dcaballe to LLVMCPU related files
> Add dcaballe to LLVM CPU CODEOWNERS

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/distribute_foreach.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tile_on_tensor.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_vector_distribution.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/foreach-thread-to-async.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/foreach-thread-to-scf-for.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/fuse-operands.mlir
- tests/e2e/linalg_transform/BUILD
- tests/e2e/linalg_transform/CMakeLists.txt
- tests/transform_dialect/cpu/BUILD
- tests/transform_dialect/cpu/CMakeLists.txt
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
* Reset third_party/llvm-project: 2d52c6bfae801b016dd3627b8c0e7c4a99405549 (2022-09-05 16:36:24 +0200): [libc++] Granularize __tuple
* mlir-hlo: 440a6d36a76592979b0597568b868eb9a07cf842
* tensorflow: 5ceb98acd49ba18cc49001e30670074a604378dd
> Integrate llvm-project at 2d52c6bfae80 and bump dependencies.

- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: 4d700ffe67be03220487604785ee2049570ba6db (2022-09-08 07:31:07 +0200): [clang][Interp] Implement ImplicitValueInitExprs
* mlir-hlo: 45fa547c07469e7b96140ffb7c98540ca42c2cd4
* tensorflow: f40a206a32bac0291e140474bcf4dbcf0e31b395
> Integrate llvm-project at 4d700ffe67be and bump dependencies.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertConv2DToImg2Col.cpp
* Use getter methods when possible
* Give dimensions and symbols better names
> NFC: various clean ups to ConvertConv2DToImg2ColPass

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_mali_matmul.mlir
We don't need to require the batch dimension to be used in both operands; if there are more than one parallel dimensions used by only one of the operand, we can choose one of them as the batch dimension.
> [spirv] Relax batch matmul recognization for more cases

- compiler/src/iree/compiler/Codegen/Common/test/warp_reduction.mlir
- integrations/tensorflow/WORKSPACE
- tests/transform_dialect/cuda/reduction.mlir
* Reset third_party/llvm-project: 55e1441f7b5d01a37fc46eb1711f03ee69845316 (2022-09-09 16:43:15 +0700): Revert "[Clang] Use virtual FS in processing config files"
* mlir-hlo: 4fbf18d6d70ac21941d15572618407a33affc93a
* tensorflow: 60ada7df3b0e5c877049a6b8f02054ce715c7288
> Integrate llvm-project at 55e1441f7b5d and bump dependencies

- compiler/src/iree/compiler/Dialect/HAL/Analysis/BindingLayout.cpp
- compiler/src/iree/compiler/Dialect/HAL/Transforms/ElideRedundantCommands.cpp
- compiler/src/iree/compiler/Dialect/HAL/Transforms/FixupLegacySync.cpp
- compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/FuseDispatchBindings.cpp
Fixes https://github.com/iree-org/iree/issues/10329
> [NFC] Switch to use upstream bitEnumContains methods.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
> Fix insertion order of operations moved into dispatch.

- compiler/src/iree/compiler/Codegen/Common/GPUDistributeSharedMemoryCopy.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileTensor.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndPromote.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
Copy linalg::LinalgTilingPattern to iree-dialects and drop reliance on its existence in MLIR core
Copy linalg::LinalgVectorizationPattern to iree-dialects and drop reliance on its existence in MLIR core
> NFC - Copy patterns to iree-dialects and drop reliance on their existence in MLIR core

- build_tools/docker/docker_run.sh
`--mount` is the new recommended syntax. It is more verbose and
explicit. See https://docs.docker.com/storage/bind-mounts/.
The direct motivation here was trying to debug what turns out to be
unhelpful behavior if you use `--volume`: if you bind a directory, *even
a read-only one*, that does not exist, Docker will create the directory
as root. This was causing issues with binding the `.config/gcloud`
directory, which we do to allow using existing credentials when running
locally. I did not even imagine that a command with "readonly" in the
name would be writing to the filesystem, let alone as the root user. If
you end up with a `.config/gcloud` directory owned by root, basically
every `gcloud` command breaks.
The recommended fix is to not use `--volume` (see …
> Use `--mount` instead of `--volume` in `docker run`

- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
> Disable flaky test.

- build_tools/benchmarks/comparisons/mobilebert_fp32_commands.py
- build_tools/benchmarks/comparisons/setup_desktop.sh
- build_tools/benchmarks/comparisons/setup_mobile.sh
- build_tools/benchmarks/comparisons/simple_commands.py
- Fixes to model paths
- Add im2col + mmt4d variant to mobile CPU
- Add FP16, fuse padding with consumer variants to GPU
- Add no XNNPack variant to TFLite benchmarks
> Updates to IREE vs TFLite benchmarks

- compiler/src/iree/compiler/Codegen/Common/VectorizeConv.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DetachElementwiseFromNamedOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/InterchangeGenericOps.cpp
* Reset third_party/llvm-project: 8ae9cf550b60f25be8d7bb21ee61af2fce5e317b (2022-09-13 13:46:52 +0100): [LoopVectorize][X86] Add uniform shift costs checks for VF=1/2/4
> Integrate llvm-project at https://github.com/llvm/llvm-project/commit/8ae9cf550b60

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensorsViaRegionOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.h
- tests/transform_dialect/cpu/matmul.mlir
Add a flag to disable workload regions when generating dispatch regions via region ops.
> Add workload flag for dispatch region formation

- compiler/src/iree/compiler/Dialect/VMVX/Transforms/ResolveBufferDescriptors.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/test/resolve_buffer_descriptors.mlir
Previously the handling of the rank-reducing subview would process only the first "rank of the subview" strides, sizes, and offset whereas all the "rank of source" values contribute to the final information. The only difference when a rank-reducing subview is involved is some of these values are not replicated in the tuple of results.
E.g., consider the following mask of kept dimensions: [1, 0, 1] I.e., resDim0 == srcDim0 and resDim1 == srcDim2
Prior to this patch, we would compute:
- For the sizes: -- resDim0 with srcDim0: good
-- resDim1 with srcDim1: bad
- For the strides: -- resDim0 with srcDim0: good
-- resDim1 with srcDim1: bad
- For the offset: -- resOffset: fct(srcDim0, srcDim1): bad
With this patch, we would compute:
- For the sizes: -- resDim0 with srcDim0: good
-- resDim1 with …
> [ResolveBufferDescriptors] Fix the handling of rank-reducing subview

- compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/bufferize_copy_only_dispatches.mlir
- compiler/src/iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- compiler/src/iree/compiler/Codegen/Common/test/pad_dynamic_alloc.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduce_bank_conflicts.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/vector_to_gpu.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute_scatter.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/vectorize_matmul.mlir
- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree_tf_compiler/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/BUILD
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
- tests/transform_dialect/cpu/matmul.mlir
* Reset third_party/llvm-project: 42a90e6017b04f218a398b46c331fb5a8336433d (2022-09-16 09:32:02 -0700): [ModuleInliner] Remove a redundaunt variable (NFC)
MHLO : https://github.com/tensorflow/mlir-hlo/commit/f1a12aa82afd8444285e673574d5882c89ddef63
TF: https://github.com/tensorflow/tensorflow/commit/d5eb41b9711e2a7017ff16ce835d31e482884fed
> Integrate llvm-project at https://github.com/llvm/llvm-project/commit/42a90e6017b0

- compiler/src/iree/compiler/Dialect/HAL/Transforms/AssignTargetDevices.cpp
When specifying a backend that isn't registered, report registered
backends in error message to make easier to debug.
> Report registered backends on failure

- compiler/src/iree/compiler/Codegen/SPIRV/AMDConfig.cpp
These numbers are still mostly "placeholders", so that we have some defaults for AMD hardware to get started.
> [spirv] Update default AMD convolution and matmul configuration

- compiler/src/iree/compiler/Codegen/Common/GPUDistributeSharedMemoryCopy.cpp
- compiler/src/iree/compiler/Codegen/Common/test/distribute_gpu_shared_memory.mlir
- compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
When there are no enough remaining threads for a particular shape dimension size, try to use all remaining threads. But we still need to make sure all work can be distributed to these threads evenly.
Also added some debug prints in GPUDistributeSharedMemoryCopyPass to make debugging easier.
Fixes https://github.com/iree-org/iree/issues/10447
> Fix GPU shared memory vector copy possibility analysis

- compiler/src/iree/compiler/Dialect/VMVX/Transforms/ResolveBufferDescriptors.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/test/resolve_buffer_descriptors.mlir
Also adds some missing tests for alloca.
This allows the invocation listed in the bug to compile. Just spot-checking the code, there is a lot of work to do to make it good, but one step at a time.
Fixes #10427
> Teach ResolveBufferDescriptors how to handle memref.get_global.

- runtime/src/iree/base/internal/cpu.c
Tested on my M1 Mac. It turns out that the M1 supports dotprod but not i8mm. With dotprod, my laptop does 400 Gop/s (single-thread perf) on `mmt4d_benchmark`.
(arm64 kernels are currently disabled on Apple since #10449 but that's temporary. obviously, the 400 Gop/s is only observed by reverting that).
> detect cpu features on Apple/ARM64

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tensor_alloc.mlir
Fix performance regression after moving bufferization after vectorization. For performance reason we shouldn't promote when there are no re-use opportunity.
> Don't promote matmul for gemv kind of case

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUReduceBankConflicts.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduce_bank_conflicts.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tensor_alloc.mlir
Fix two bugs related to shared memory allocations. Handle the corner case where the promoted value has multiple use. Also prevent padding of alloc with dynamic dimension.
> [LLVMGPU] Fix bugs related to shared memory alloc

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transpose_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
Transition transpose shared mem pipeline to do vectorization before bufferization.
Based on https://github.com/iree-org/iree/pull/10217
Related to #10005
> LLVMGPU] Move bufferization after vectorization for shared mem transpose

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree-dialects/include/iree-dialects/Dialect/Input/InputOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/Input/InputOps.td
* llvm-project: 143f3bf8f422af962761b1bb1f2875a6d30b25eb
* mlir-hlo: 464d0a0b596db602ba91fd377d59eedd8aabcaeb
* tensorflow: 6171df5779f25395b5d16859b9489bd5f2ae7997
> Integrate llvm-project at llvm/llvm-project@143f3bf

- build_tools/cmake/iree_hal_cts_test_suite.cmake
Address post-merge comment in https://github.com/iree-org/iree/pull/10461
> Cleanup iree_hal_cts_test_suite function

- integrations/tensorflow/test/python/iree_tf_tests/layers/layers_test.py
Keras layers that do not support fully dynamic shapes are tested with a
dynamic batch size only.
Keras currently calls `set_shape` based on the shape of the `Input`
that is defined. However, this logic in Keras is being removed as it is
incorrect in some scenarios.
Because of this, the IREE "dynamic_dims" unit tests were actually
running with a fully static shape and not exercising operations with a
dynamic shape. Testing with dynamic shapes uncovered the fact that some
layers do not support it.
> Don't use fully dynamic shapes for Keras layers that don't support them

- compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
Fix for [issue 10253](https://github.com/iree-org/iree/issues/10253)
> Add i8 to i64 ExtUI lowering from arith to VM

- compiler/src/iree/compiler/Codegen/Common/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToLinalgOnTensors.cpp
- integrations/tensorflow/WORKSPACE
* llvm-project: 846709b287abe541fcad42e5a54d37a41dae3f67
* mlir-hlo: e43c5758bf97bca18957d93d2843ff93e67108de
* tensorflow: 9846685f4f3647f9e6f57b4242951d9b70522dbe
> Integrate llvm-project at llvm/llvm-project@846709b

- runtime/src/iree/base/status_cc.cc
- runtime/src/iree/base/status_cc.h
- runtime/src/iree/base/status_test.cc
- runtime/src/iree/testing/status_matchers.h
- runtime/src/iree/tooling/comparison.cc
- runtime/src/iree/tooling/comparison.h
- runtime/src/iree/tooling/comparison_test.cc
- runtime/src/iree/tooling/numpy_io_test.cc
- runtime/src/iree/tooling/vm_util.cc
- runtime/src/iree/tooling/vm_util.h
- runtime/src/iree/tooling/vm_util_test.cc
- runtime/src/iree/vm/bytecode_dispatch_test.cc
- tools/android/run_module_app/src/main.cc
- tools/iree-benchmark-module-main.cc
- tools/iree-check-module-main.cc
- tools/iree-run-mlir-main.cc
- tools/iree-run-module-main.cc
On Android/ARM64, Release config, size of `iree-run-module` (after stripping):
Before: 794424
After: 591472
> Don't `#include <ostream>` outside of test-only code.

- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: 19850cc2d8529df8982a2846583480582dc2ebe6 (2022-09-23 18:41:41 -0700): Revert "[RISCV] Lower BUILD_VECTOR to RISCVISD::VID_VL if it is floating-point type."
* tensorflow/tensorflow@00fd752b4932b73c8d04eb6e2543f6c7b2ac94e9
* tensorflow/mlir-hlo@b9ad408df1e514e6b232863499f34fdc4bbc2160
> Integrate llvm/llvm-project@19850cc2d852

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
This prepares the configuration deduction logic for plumbing NCHW flavor convolution support through.
> [spirv] NFC: Refactor convolution configuration deduction logic

- build_tools/github_actions/runner/gcp/create_image.sh
- build_tools/github_actions/runner/gcp/create_templates.sh
- build_tools/github_actions/runner/gcp/image_setup.sh
- build_tools/scripts/check_cuda.sh
This just adds some GPU-specific stuff to the same setup as the CPU
image.
Tested: Deployed on test runners ->
https://github.com/iree-org/iree/pull/10298
skip-ci
> Automate creation of GPU images

- integrations/tensorflow/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- integrations/tensorflow/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
- integrations/tensorflow/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
- integrations/tensorflow/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir
In preparation for LLVM integration.
> Sync iree-dialects under integrations/tensorflow

- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Utils.h
- compiler/src/iree/compiler/Dialect/HAL/Target/MetalSPIRV/MetalSPIRVTarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/TargetBackend.h
- compiler/src/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/WebGPU/WebGPUTarget.cpp
Follow-up to https://github.com/iree-org/iree/pull/10565 (and https://reviews.llvm.org/D134620 / https://github.com/llvm/llvm-project/commit/5ab6ef758f0f549fb39bf9b34a6a743e989b212a)
skip-ci
> Rename `spv.` to `spirv.` in code comments and error messages.

- compiler/src/iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- tests/e2e/linalg_ext_ops/pack.mlir
> Add bufferization support for LinalgExt::PackOp with padding mode.

- tests/e2e/linalg_ext_ops/pack.mlir
Change the reference to use pad + reshape + transpose to reduce cognitive overhead about reasoning about the reference code.
> Add e2e to tests for pack + pad.

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
Allow group reduction as long as we don't generate group bigger than the api limit.
> [LLVMGPU] Relax the condition to enable group reduction on cuda

- build_tools/scripts/download_file.py
Let `download_file.py` retry a few times for connection issues.
> Add retry to download_file.py

- compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
> Add i8 to i64 ExtSI lowering from arith to VM

- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
Please use just the second commit to see just the diff with https://github.com/iree-org/iree/pull/10537
> Propogating the ReassociateFpReduction flag of IREE Codegen to ConvertToLLVM.

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- CMakeLists.txt
- build_tools/scripts/git/check_submodule_init.py
- build_tools/scripts/git/runtime_submodules.txt
- build_tools/scripts/git/update_runtime_submodules.sh
Reduce CI build time by only updating a subset of submodules for the
non-compiler targets.
> Create a runtime submodule subset

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dispatch_region_formation.mlir
Split the op into two: clone_succeeding_op_into_dispatch_region and move_succeeding_op_into_dispatch_region
> Split clone_succeeding_op_into_dispatch_region

- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
This makes it more visible so that we don't fail silently for release builds.
> [spirv] Turn subspan op byte offset assertion into failure

- compiler/src/iree/compiler/Dialect/Util/IR/UtilTypes.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/test/buffer_folding.mlir
> Fix !util.buffer size discovery when nested inside of region ops.

- compiler/src/iree/compiler/Codegen/Common/BufferizationAnalysis.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/Common/TypePropagationPass.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorPad.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/AMDConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/AdrenoConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/AppleConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/MaliConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVEmulateI64.cpp
- compiler/src/iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DetachElementwiseFromNamedOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensorsViaRegionOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/InferNumericNarrowing.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/PadLinalgOps.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilExternalModels.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/ForeachThreadToSequentialFor.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/roundtrip.mlir
* Reset third_party/llvm-project: 5e9945f624bd280f93d0b141ce47d6be0158861a (2022-10-18 16:37:08 +0200): [libc] Fix missing bazel dependency
> Integrate llvm-project at https://github.com/llvm/llvm-project/commit/5e9945f624bd

- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/PadLinalgOps.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Passes/PadContractionToBlockSize.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/PadContractionToBlockSize.cpp
Fix IREE to drop `createPadScalarOp` uses and use the build method instead.
This also has local changes to MHLO (in iree-mlir-hlo repo). This has been submitted into MHLO repository too and is expected to resolve on the next integrate.
> Cherry pick D136493

- build_tools/cmake/iree_benchmark_suite.cmake
Following discussion [here on Discord](https://discord.com/channels/689900678990135345/689957613152239638/1034137764423274588).
> Elaborate on benchmark error message for missing import binaries.

- runtime/src/iree/hal/drivers/vulkan/vulkan_device.cc
Requires that `--vulkan_debug_utils=true` is specified in release. There's no fancy checking being done here for whether the vendor is AMD as the events are fairly cheap/harmless. Doesn't scale if all vendors have their own but that'd be a better problem to have than no programmatic control at all!
> Adding AMD-specific frame delineation markers.

- runtime/src/iree/hal/drivers/vulkan/native_executable.cc
This should match what is in tracy:
> Setting Vulkan pipeline names from entry point names.

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.h
- compiler/src/iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_to_cooperative_ops.mlir
This is mostly adjusting the configuration side to be flexible.
> [spirv] Enable cooperative matrix flow for batch matmul

- tests/e2e/linalg_ext_ops/unpack.mlir
Question - this test works uses pack to create the input for unpack. Isn't there a risk that the back-to-back pack -> unpack would get folded as an identity operation, and the e2e test would end up vacuous? What's the remedy, some "do not optimize" kind of trick or another method of generating the input for unpack?
> Cover all transposition cases of `linalg_ext.unpack`

- build_tools/github_actions/configure_ci.py
Fixes https://github.com/iree-org/iree/issues/10862
> Handle the case where PR trailers contain colons themselves

- compiler/src/iree/compiler/Modules/HAL/Inline/Transforms/Conversion.cpp
- compiler/src/iree/compiler/Modules/HAL/Loader/Conversion/StreamToHALLoader/test/cmd_ops.mlir
- compiler/src/iree/compiler/Modules/HAL/Loader/Transforms/Conversion.cpp
> Allowing affine dialect in inline HAL conversion.

- compiler/src/iree/compiler/Codegen/Common/GPUTileReduction.cpp
- compiler/src/iree/compiler/Codegen/Common/test/tile_reduction.mlir
In case we fuse reduce + broadcast the broadcast parallel loops needs to be tiled to serial loop.
> Add tiling for cases where a broadcast is fused with a group reduction

- compiler/src/iree/compiler/Codegen/Common/GPUPatterns.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUPatterns.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndPromote.cpp
- compiler/src/iree/compiler/Codegen/Utils/BUILD
- compiler/src/iree/compiler/Codegen/Utils/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
- compiler/src/iree/compiler/Codegen/Utils/GPUUtils.h
This is in preparation to be reused by the SPIR-V CodeGen pipeline.
> NFC: Move matmul C matrix promotion related code to Common/

- compiler/src/iree/compiler/Codegen/Common/GPUTileReduction.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileTensor.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/convert_mhlo_to_linalg_ext.mlir
- compiler/src/iree/compiler/InputConversion/MHLO/test/mhlo_to_mhlo_preprocessing.mlir
- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree_tf_compiler/TFL/LowerGlobalTensors.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/RetainCallOnceFuncs.cpp
* Reset third_party/llvm-project: cb84df210a477c1038b659c9de5d1a01fdb85b92 (2022-11-01 20:48:53 +0800): [sanitizer] Fix build error with current LoongArch Clang
* Updated tensorflow/mlir-hlo@eb49a65
* Updated tensorflow/tensorflow@616075d
> Integrate llvm/llvm-project@cb84df210a47

- tests/e2e/linalg_ext_ops/pack.mlir
- Use linalg.transpose op instead of linalg.generic op.
- Add `static_` prefix to static test cases.
- Unify the creation of golden values.
> Migrate to use linalg.transpose op and unify all the pack tests.

- compiler/src/iree/compiler/Codegen/Common/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
Cherry-pick improvements to the vector distribution and update the lambda interface. That will allow distributing loops with values coming from above.
> Cherry-pick llvm/llvm-project@91f62f0e

- build_tools/python_deploy/pypi_deploy.sh
> Document PyPI deploy script a bit

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
With latest improvements from vector distribution we don't need this workaround anymore
> Relax condition to enable group reduction

- .github/workflows/ci.yml
- build_tools/scripts/git/update_runtime_submodules.sh
Progress on https://github.com/iree-org/iree/issues/11009
Tested here: https://github.com/ScottTodd/iree/actions/runs/3380820232/jobs/5614038219
Post-submit only for now, so we can monitor it. I saw one build hang in the "Configuring MSVC" step: https://github.com/ScottTodd/iree/actions/runs/3380762369/jobs/5613916852
> Add build_runtime_windows CI job.

- compiler/src/iree/compiler/Dialect/Stream/Transforms/ScheduleAllocation.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/schedule_allocation.mlir
This will allow us to schedule copies (and other ops) together when operating on the same resources either when directed by the user at higher levels of the stack ("trust me this is safe") or by partitioning that can ensure the ops are mutually exclusive (non-overlapping ranges derived from analysis). This will be useful for collectives as we can group multiple collectives together operating on the same send and recv resources.
Progress on #7729.
Progress on #9580.
> Supporting concurrent in-place copies during stream allocation.

- compiler/src/iree/compiler/Codegen/Common/test/distribute_gpu_shared_memory.mlir
- compiler/src/iree/compiler/Codegen/Common/test/warp_reduction.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/distribute_foreach.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tile_on_tensor.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transpose_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_cooperative_matrix.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_to_cooperative_ops.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_fusion_with_transpose.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/set_encoding.mlir
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/layout_slices.mlir
- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree_tf_compiler/TF/DirectLoweringPatterns.cpp
- integrations/tensorflow/iree_tf_compiler/TF/LowerGlobalTensors.cpp
- integrations/tensorflow/iree_tf_compiler/TF/PropagateResourceCasts.cpp
* Reset third_party/llvm-project: 001d18664f8bcf63af64f10688809f7681dfbf0b (2022-11-02 15:03:52 -0400): [bolt] update bazel rules for f71d32a0eea4
> Integrate llvm-project at https://github.com/llvm/llvm-project/commit/001d18664f8b

- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
Previously multi-threaded compilation didn't propagate the flag to reassociate FP reductions. https://github.com/iree-org/iree/issues/10279#issuecomment-1302853763. This PR fixes that.
> Fix plumbing options to ConvertToLLVM

- build_tools/scripts/generate_release_index.py
This makes scanning it visually a bit nicer.
> Add some line breaks in package index

- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: 72f89556413f9c1fb1fb9138d6d53e13499ce545 (2022-11-09 21:46:54 +0000): [CodeGen][AArch64] Enable LDAPR under +RCPC
* mlir-hlo: 9cb709d1c1aacba9b6417a013e23895d49837576
* tensorflow: 80843f5d4e2a0ff1c3211f648da3c9194758bd91
Cherry-pick https://github.com/llvm/llvm-project/commit/39c80656
> Integrate llvm-project at 72f89556413f and bump dependencies 

- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/SPIRV/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/test/illegal_configuration.mlir
The verification logic is following the constraints in #10500.
> [spirv] Add verifier for lowering configurations

- runtime/src/iree/hal/drivers/webgpu/command_buffer.c
Tested slightly (_this code_ doesn't log warnings/errors)
> Use wgpuCommandEncoderClearBuffer when possible.

- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: e1b88c8a09be25b86b13f98755a9bd744b4dbf14 (2022-11-10 15:02:03 +0100): [clang] Only use major version in resource dir
* mlir-hlo: bd8b4cbc42adc952331538eb65c542b5f32fe98f
* tensorflow: 12b37bb070d1a941698e3987612a1900a9cc9229
Cherry-pick llvm/llvm-project@dc26c03
> Integrate llvm-project at e1b88c8a09be and bump dependencies

- build_tools/python/e2e_test_framework/definitions/common_definitions.py
- build_tools/python/e2e_test_framework/definitions/iree_definitions.py
Adds `@serializable` annotation to e2e test framework objects
> Annotate serializable on e2e test framework objects

- build_tools/python/benchmark_suites/iree/cuda_benchmarks.py
- build_tools/python/benchmark_suites/iree/module_execution_configs.py
- build_tools/python/e2e_test_framework/definitions/iree_definitions.py
Fix the `loader` in CUDA and Vulkan execution configs.
> Fix CUDA and Vulkan execution configs

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
The cast operations can be created during tiling. We have to fold it into the tiled op if possible. The pattern for LinAlg dialect is included, but the pattern for LinalgExt dialect is not included. This commit adds the pattern to the pass.
Fixes https://github.com/iree-org/iree/issues/11038
> Add LinalgExt canonicalization patterns to tile+distribute pass.

- compiler/src/iree/compiler/Codegen/Common/GPUTileReduction.cpp
- compiler/src/iree/compiler/Codegen/Common/test/tile_reduction.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/reduction_lowering.mlir
Use the loop based reduction tiling transformation. This will allow supporting unaligned and dynamic shapes.
> [GPU] Refactor reduction tiling pass

- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
- compiler/src/iree/compiler/Codegen/VMVX/test/lower_linalg_microkernels.mlir
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/ConvertVMVXToVM.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/test/BUILD
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/test/unpack.mlir
- compiler/src/iree/compiler/Dialect/VMVX/IR/VMVXOps.td
- compiler/src/iree/compiler/Dialect/VMVX/vmvx.imports.mlir
- runtime/src/iree/builtins/ukernel/BUILD
- runtime/src/iree/builtins/ukernel/CMakeLists.txt
- runtime/src/iree/builtins/ukernel/exported_flag_bits.h
- runtime/src/iree/builtins/ukernel/pack.c
- runtime/src/iree/builtins/ukernel/unpack.c
- runtime/src/iree/builtins/ukernel/unpack.h
- runtime/src/iree/builtins/ukernel/unpack_types.h
- runtime/src/iree/modules/vmvx/exports.inl
- runtime/src/iree/modules/vmvx/module.c
- tests/e2e/linalg_ext_ops/BUILD
- tests/e2e/linalg_ext_ops/CMakeLists.txt
Not yet optimized; so far only tested by e2e/linalg_ext_ops/unpack.mlir.
> initial `unpack` microkernel

- compiler/src/iree/compiler/Dialect/Flow/Transforms/SetEncoding.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/set_encoding.mlir
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/materialize_encoding.mlir
This PR contains the fixes needed to compile `fill` -> `matmul`
operations through the data tiling path. It needs
- Use of pattern to fold the fill with the pad to then allow folding
fill with `set_encoding` ops.
- Add utility methods and pattern wrappers to materialize the encoding
of `fill` and `empty` operations.
> Enhancements to allow compilation of matmul + fill through data tiling path.

- compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/Transforms.h
Depends on #11127, review bottom commit separately.
> NFC: Deduplicate code in bufferization transform op

- compiler/src/iree/compiler/Codegen/Common/GPUPipelining.cpp
- compiler/src/iree/compiler/Codegen/Common/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUDistribute.cpp
- compiler/src/iree/compiler/Codegen/Utils/BUILD
- compiler/src/iree/compiler/Codegen/Utils/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
- compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/OpOracle.cpp
- compiler/src/iree/compiler/Dialect/VM/Transforms/SinkDefiningOps.cpp
- llvm-external-projects/iree-dialects/lib/Transforms/ListenerCSE.cpp
This cherry picks D137857.
Also included are changes to MHLO that should get resolved on next integrate.
> Cherry pick https://github.com/llvm/llvm-project/commit/fc367dfa6770fda4adc4e5de79846f22e7e4e215

- compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp
- compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToLinalgOnTensors.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/broadcasting.mlir
- compiler/src/iree/compiler/InputConversion/MHLO/test/dynamic_shape.mlir
- llvm-external-projects/iree-dialects/lib/Transforms/ListenerCSE.cpp
This enables CSE of ops with a single block in IREE. The two patches are required for all tests to pass.
> Cherry pick D134306 and D138085

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
Fixes #11220. (thanks to Mahesh for figuring this out!)
> Fix stack use-after-free in MaterializeEncodingConversionTarget

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
Take advantage that we can now dynamically unpack handles to pdl::Operation to simplify the APIs.
This support was previously added in LLVM @ 6370f75ad70c508b52a3d98250bad51e8d8138b6.
> NFC - Apply minor API cleanups

- integrations/tensorflow/iree-dialects/BUILD
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Passes/Tiling.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Utils/Utils.cpp
- integrations/tensorflow/iree-dialects/lib/Transforms/ListenerCSE.cpp
- integrations/tensorflow/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
- integrations/tensorflow/iree-dialects/test/Dialect/iree_linalg_ext/vectorization.mlir
Created using `cp -r llvm-external-projects/iree-dialects integrations/tensorflow/`
> Copy iree-dialects/ to integrations/tensorflow

- compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
Uniform buffers are faster but generally have a much smaller capacity limits. GPUs would expect such buffers to have a bound size when declaring resource ops in the kernel, so converting them to a static shaped 1-D memref.
Fixes https://github.com/iree-org/iree/issues/11229
> Flatten uniform buffers to static 1-D MemRefs

- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
This commit moves separate the pre-processing passes that arent on by default, and are meant to be used in special cases.
> NFC: Minor refactoring of pass in Flow to separate optional pre-processing passes.

- compiler/src/iree/compiler/Dialect/VM/IR/test/BUILD
- compiler/src/iree/compiler/Dialect/VM/IR/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/VM/IR/test/arithmetic_speculation.mlir
- compiler/src/iree/compiler/Dialect/VM/IR/test/list_speculation.mlir
Document the existing behavior before making changes in https://github.com/iree-org/iree/pull/11190.
Issue: https://github.com/iree-org/iree/issues/11179
> [vm] Pre-commit VM op speculation tests. NFC.

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- integrations/tensorflow/WORKSPACE
LLVM_COMMIT=”65644125beb76066171ce586e13bdff918140c0e” MHLO_COMMIT=”f38edd55b54e8505d00838d414a447b517b65fe7” TF_COMMIT=”2b3836fc40b4bb8165a4d671f49464d91acc0af6”
> Integrate llvm-project at 65644125beb7 and bump dependencies

- .github/workflows/ci.yml
- CMakeLists.txt
- build_tools/cmake/build_e2e_test_artifacts.sh
Adds the job to build e2e test artifacts in CI.
> Build e2e test artifacts in CI

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
The perfect tiling case indicates that the tiling sizes is are multiple of inner_tile_size. In this context, The indices of input slice are all aligned to head. No extra data is needed when representing the tiled unpack op.
> Fix bugs in tiling unpack ops for perfect tiling cases.

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
Add a simple recurisve matching API for inputs and inits of a structured op that may be fed by another structured op. This currently expect a concrete position and additional work is needed to support "any position" or wildcarding. This API follows other fluent functions instead of special-casing input matchers to be constructor operands, i.e. one is expected to write `consumer.input(0, producer())` rather than `consumer(producer())`. This is expected to scale better in presence of wildcards and input/init mixes where depending on the position of the argument in the argument list is undesirable.
> Matcher API for inputs and inits/outputs

- integrations/tensorflow/test/iree_tf_tests/uncategorized/vulkan__broadcast_to.run
> Disable flaky vulkan tests.

- compiler/src/iree/compiler/Codegen/Common/TypePropagationPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/type_propagation.mlir
Also remove unnecessary legality checks within conversion patterns.   
The dialect conversion infra already filters out legal ops. By
construction all patterns are invoked only on illegal ops, so checks
within the pattern to make sure the op is illegal are redundant.
Fixes #11267
> Handle `tensor.extract` of i1 types in type legalization.

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_vmvx_launch_configuration.mlir
Fixes https://github.com/iree-org/iree/issues/10859
> Always vectorize LinAlg ops for VMVX backend.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
The way the patterns interact causes what is effectively folding to
count against the max iteration limit. The default of 10 is
insufficient when the input program has a lot of constants to fold.
In the future we could explore top-down traversal as an alternative.
Also added logging so when this pass fails we see something on stderr.
Fixes #11333.
> Letting FusionOfTensorOps apply patterns forever.

- compiler/src/iree/compiler/Pipelines/Pipelines.h
- compiler/src/iree/compiler/Tools/iree_compile_lib.cc
- tools/test/BUILD
- tools/test/CMakeLists.txt
- tools/test/compile_to_phase.mlir
> Fixing the --compile-to= flag and adding a test of all phases.

- .github/workflows/ci.yml
See https://github.com/iree-org/iree/issues/11350
> Disable build_test_all_windows job while it is failing.

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- build_tools/cmake/build_all.sh
- build_tools/cmake/build_and_test_asan.sh
- build_tools/cmake/build_and_test_tsan.sh
- build_tools/cmake/build_android.sh
- build_tools/cmake/build_benchmarks.sh
- build_tools/cmake/build_e2e_test_artifacts.sh
- build_tools/cmake/build_host_tools.sh
- build_tools/cmake/build_riscv.sh
- build_tools/cmake/build_runtime.sh
- build_tools/cmake/build_runtime_emscripten.sh
- build_tools/cmake/build_runtime_small.sh
- build_tools/cmake/build_tf_binaries.sh
- build_tools/cmake/build_tracing.sh
- build_tools/cmake/setup_build.sh
- build_tools/cmake/test_riscv.sh
- tests/riscv32/smoke.sh
This just combines some copypasta from various scripts into a single
file that can be sourced to reduce duplication a bit. I'm about to add
ccache setup stuff, which was the motivation here.
> Cleanup build scripting

- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
Old pass manager pieces are starting to be removed.
> Move CUDA llvm optimization to the new pass manager

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/run_mmperf.yml
- build_tools/github_actions/configure_ci.py
> Use new environment files for GitHub actions step outputs

- .github/workflows/ci.yml
- build_tools/cmake/build_all.sh
I'll disable and delete the Buildkite pipeline after this goes in.
Part of https://github.com/iree-org/iree/issues/9855
> Migrate the rest of the alternate configurations builds from Buildkite

- compiler/src/iree/compiler/Codegen/Dialect/test/lowering_config_attr.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/workgroup_specialization_pipeline_test.mlir
- compiler/src/iree/compiler/Tools/BUILD
- compiler/src/iree/compiler/Tools/CMakeLists.txt
- compiler/src/iree/compiler/Tools/init_mlir_passes.h
- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Passes/TileAndDecomposeWinogradPass.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/TileAndDecomposeWinogradPass.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
* Reset third_party/llvm-project: ca23b7ca476fb66771d1c6d02c6837938fde6c7e (2022-12-02 19:05:43 +0000): [AsmPrinter] .addrsig_sym: remove isTransitiveUsedByMetadataOnly
* Updated to tensorflow/tensorflow@a4ed969
* Updated to tensorflow/mlir-hlo@9e3d164
> Integrate llvm/llvm-project@ca23b7ca476fb

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
This commit addresses some of the remaining comments in #11422 around API simplification.
> Followup transform dialect integrate cleanups

- compiler/src/iree/compiler/Codegen/SPIRV/test/convert_to_spirv.mlir
Do some computation on the loaded value and return them. This makes the test robust and not subject to DCE.
> NFC: update convert_to_spirv.mlir tests to avoid dead code

- benchmarks/README.md
- build_tools/benchmarks/README.md
Add instructions to collect and diff compilation statistics locally.
> Update benchmark docs for compilation statistics

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- tests/transform_dialect/cuda/reduction_v3.mlir
- tests/transform_dialect/cuda/reduction_v3_codegen_spec.mlir
This is a cherry-pick of #11530 onto main.
> Relax block size constraints: dynamic reduction-v3 @peak

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- tests/transform_dialect/cuda/reduction_v2_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v3_codegen_spec.mlir
This PR cherry-picks the following LLVM commit:
f27514800cc50677d640deae555bf999653a4c6f
@hanhan for integrate.
> Use better Linalg transform op builders

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- integrations/tensorflow/test/iree_tf_tests/math/llvmcpu__complex_dynamic_dim_reduce_std.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmcpu__complex_dynamic_dim_reduce_variance.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmcpu__dynamic_dim_reduce_mean.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmcpu__dynamic_dim_reduce_std.run
- integrations/tensorflow/test/iree_tf_tests/math/llvmcpu__dynamic_dim_reduce_variance.run
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/foreach-thread-to-async.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/foreach-thread-to-scf-for.mlir
Also fixes some test cases due to #11196.
* e7328a9eb22307d80f86f668a75c2b082ee8636e
* be630f07de0c17bade67e6ab6a297db41003775d
* 1742882a3496f5a96eb67f665d9c622633f3ae3c
* e07149c91f4bb43c1413bc1fbe19dc6eff2fcde6
* e5dc99e642d05b1075b6c5480a5b3f0485a25038
* 17f36648e6d6f543af7a965b7ceab71a1cf69a6b
* a73455ac8e9bd02f843916c12c261cfd9ccb06a9
* d2b070d3c95c50579da83be97f79bd2c52f188c8
> Cherry-pick llvm-project commits

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.h
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- tests/transform_dialect/cuda/eltwise_reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_eltwise.mlir
- tests/transform_dialect/cuda/reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v2.mlir
- tests/transform_dialect/cuda/reduction_v2_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v2_uneven.mlir
- tests/transform_dialect/cuda/reduction_v3.mlir
- tests/transform_dialect/cuda/reduction_v3_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_partial_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_v2_codegen_spec.mlir
This removes a self-copy in reduction_v3 and cleans up the IR in general.
> Cherry-pick and use subview folding pattern

- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/Patterns.cpp
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/insert.mlir
Fixes https://github.com/iree-org/iree/issues/11515
Signed-Off By: Vivek Khandelwal<vivek@nod-labs.com>
> Add TensorToFlow conversion pattern for tensor.insert op

- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
* llvm/llvm-project@a583616918ec2984092c99363f200dd31642859a
* llvm/llvm-project@2ec98ffbf12163ee4ff9f4e674eba714bce24ec1
> Cherry-pick llvm-project changes and fix #11586

- build_tools/github_actions/runner/instance_deleter/main.py
From my experience just skimming the logs, this is helpful.
> Add some additional logging to instance deletion service

- docs/developers/design_docs/cuda_backend.md
Change func into func.func and move the example to use linalg input instead of hlo.
> Update CUDA example

- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree_tf_compiler/MHLO/EmitDefaultIREEABI.cpp
- integrations/tensorflow/test/iree_tf_tests/layers/llvmcpu__dynamic_dims_UpSampling1D.run
- integrations/tensorflow/test/iree_tf_tests/layers/llvmcpu__dynamic_dims_UpSampling3D.run
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/invalid.mlir
Integrate llvm-project @ 893a0ea948a6
* llvm-project: 893a0ea948a6
* mlir-hlo: 3097d03a5c9f730b6bd96482052f0ac21c0bdaca
* tensorflow: 86e94b8b6e158ef7682aabf34cbc48b5db7a134d
Carry over cherry-picks in llvm-project
* 4f8444cf1bf484bfbc989d8020778b504cda4d91
* 8ca31f96c9b2f6cda5da894515e0d09b61f6ebe3
* 5f628eb542ba42862a8a94920c5c882b82e408ab
* 0c82a09043fffdc024fc3dbbacf204a1cba6bbf9
Use nullptr when the type is unknown for json conversion
New cherry-picks from llvm-project
* 41e731f2a4328f37b5d4e14d912814493e206f32
* d0766c0861c6f9ab4ec286a695ae8e161f418b2f
* 6b76c4eafde8cc72133c752c05fa479c33221e61
update iterator_interchange syntax in invalid.mlir
enable TF llvmcpu__dynamic_dims_UpSampling[1D|3D] tests
> Bump llvm 221220

- integrations/tensorflow/WORKSPACE
Integrate llvm-project and bump dependencies.
* llvm-project: 35762d0739105b9e53ffc3093e65a287d904ee95
* mlir-hlo: 4feb626a4de1e17cbb5f5b10217cc5e919bdeb07
* tensorflow: 121a4afa7b73a0522f3ab23bf2b533a706f73a0d
> Bump llvm 20221227

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
This allows more cases to be vectorized.
> [LLVMGPU] Pick a K tile size always aligned

- compiler/pyproject.toml
Add missing python package dependency
> Add missing python package dependency

- runtime/src/iree/hal/drivers/cuda/cts/CMakeLists.txt
- runtime/src/iree/hal/drivers/local_sync/cts/CMakeLists.txt
Context:
* https://github.com/iree-org/iree/pull/8334
* https://github.com/iree-org/iree/issues/4680
> Enable some now-passing HAL CTS tests.

- build_tools/github_actions/runner/gcp/update_instance_groups.py
Now the `type` in instance group name can include `-` (`cpu-c2-16`). Update the regex pattern in `update_instance_groups.py`.
> Update the pattern to match new CPU benchmark MIG

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
> Adding lowering config for pooling

- build_tools/cmake/iree_cc_binary.cmake
- docs/developers/developing_iree/profiling_vulkan_gpu.md
- tools/android/run_module_app/AndroidManifest.xml.template
The context of this proposal is at https://github.com/iree-org/iree/pull/11742#discussion_r1063864928
This pull request is the correction of https://github.com/iree-org/iree/pull/11748.
This pull request updates the three files that the command `git grep "com.google"` lists.  These files are all about the Android apps and iOS apps names.
> Change com.google.iree into dev.iree

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/fuse-operands.mlir
* llvm-project: e10e93631541
* mlir-hlo: eaaad2f2c81612daf89ea5a7346c29ea07fe803e
* tensorflow: a982e10107520a1151818ec05640d94e453cb650
Disable fuse-operands.mlir test, which is tracked in https://github.com/iree-org/iree/issues/11765
> Integrate llvm-project at e10e93631541 and bump dependencies.

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/CPU/Common.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/CPU/Common.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/CPU/ReductionStrategy.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/CPU/ReductionStrategy.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/AbstractReductionStrategy.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/AbstractReductionStrategy.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/StagedReductionStrategy.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/StagedReductionStrategy.h
Improve doc for matchAndSetReductionStrategy.
Refactor strategy configuration and introduce a hardware model shim.
Add a primitive hook for known good reduction configurations.
> Refactor strategy configuration and add a primitive hook for known good reduction configurations.

- build_tools/github_actions/runner/gcp/update_instance_groups.py
Reverts iree-org/iree#11731
The regex pattern isn't correct.
> Revert "Update the pattern to match new CPU benchmark MIG"

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/TransformInterpreter.cpp
The current code results in a use-after-free. Fixes
https://github.com/iree-org/iree/pull/11788
> [TransformInterpreter] Avoid modifying a region while walking it

- docs/developers/developing_iree/profiling_with_tracy.md
Was it fixed in https://github.com/wolfpld/tracy/issues/384 ?
> Remove unneded patching doc

- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/CPU/ReductionStrategy.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/Common.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/Common.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/AbstractReductionStrategy.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/StagedReductionStrategy.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/StagedReductionStrategy.h
> NFC - Refactor and better document transform strategy builders

- build_tools/cmake/iree_copts.cmake
- experimental/web/testing/build_tests.sh
- runtime/src/iree/base/loop_emscripten.c
- runtime/src/iree/base/loop_emscripten.h
- runtime/src/iree/base/loop_emscripten.js
Reverts iree-org/iree#11507
This broke some builds: https://github.com/iree-org/iree/actions/runs/3896179886/jobs/6652503581 . Revert, then investigate and fix.
> Revert "Make loop_emscripten stateful and allow for multiple instances."

- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
This is part 2/9 of #11755: Finish the transition to `--iree-flow-enable-data-tiling`.
In the VMVX backend, when deciding whether an op can be rewritten as a microkernel call, we need to check if memref layouts inner dimeensions are contiguous row-major as expected by the microkernel.
When a dimension has dynamic size, that is hard to do as a static analysis. This PR makes us just assume that dynamic dims are contiguous, which is safe-ish for e2e workloads because bufferization only creates contiguous buffers, but is not 100% satisfactory, technically this pass in isolation is not correct on all possible inputs.
Issue #11633 tracks finding a better solution.
> Let `LowerLinalgMicrokernels` assume that dynamic dims are contiguous.

- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
- runtime/src/iree/builtins/ukernel/pack.c
This is part 3/9 of #11755: Finish the transition to `--iree-flow-enable-data-tiling`.
Currently (unless the defaultPadding is changed to a non-default value), dynamic-size set_encoding shapes get rounded up to the next multiple of 16. This causes padding by potentially more than one tile size. This invalidates an assumption that the `iree_uk_pack` ukernel was relying on, that at most one last tile along each dimension would require padding.
I wish the assumption could resume holding. This is tracked in Issue #11632.
> Relax the assumption of only one padding tile in `iree_uk_pack`

- compiler/src/iree/compiler/Dialect/Stream/Transforms/ScheduleAllocation.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/ImportUtils.h
> Cleaning up llvm::zip behavior in ScheduleAllocation.

- compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingInterface.cpp
- compiler/src/iree/compiler/Codegen/Common/VectorizePad.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVCreateFastSlowPath.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVEmulateI64.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/MetalSPIRV/MetalSPIRVTarget.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/ClosureOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Util/Transforms/Patterns.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/BroadcastingToLinalgPatterns.cpp
- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
- llvm-project: ac1ffd3caca1
- mlir-hlo: e802b722d88a2f80bd4fca6d82862d093fbc5401
- tensorflow: 3e2e312efcb74391897d7a948bd789e3a822b52f
cherry-pick llvm-project commits:
- 71c837f6d7d74e44f156ac60a47b1198727ba90f
- b4477dd8c5d1f9b27cc6d8f52106359e4f0afe66
- bdcba89356f8bf8ba0141875a150aba342a85416
- 4313b6f9ebc2556ff039249691a4dc619e32840c
> Integrate llvm-project at ac1ffd3caca1 and bump dependencies.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/CollapseDimensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FormDispatchRegions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/collapse_linalg_generic_on_tensors.mlir
Reverts iree-org/iree#11771 due to SIGSEGV on MobileSSD
> Revert "Add patterns to fold `tensor.empty` with `tensor.collapse_expand/shape`."

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
This is part 4/9 of https://github.com/iree-org/iree/issues/11755: Finish the transition to --iree-flow-enable-data-tiling.
This is needed to avoid calling the `materializeEncodingValueFn` in the host code computing workgroup counts, which, in the case of VMVX+ukernel, creates a `vmvx.query_tile_sizes` op, which lowers to a ukernel call, which is not OK in host code.
> Use default value 16 for dynamic tile sizes in workgroup count on VMVX+ukernel

- build_tools/cmake/ctest_all.sh
See error reported in https://github.com/iree-org/iree/issues/11077#issuecomment-1382620877
> Adjust Windows CI post data-tiling switch in #11522

- build_tools/python/benchmark_suites/iree/riscv_benchmarks.py
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
Sync RISC-V benchmark definitions from legacy to the new framework.
> Sync RISC-V benchmark definitions

- build_tools/github_actions/configure_ci.py
Run all benchmarks in the postsubmit workflow.
> Run all benchmarks in postsubmit

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.h
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/Common/test/reductions_codegen_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/Common.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp
- tests/transform_dialect/cuda/eltwise_reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/eltwise_reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v2_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v3_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_partial_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_v2_codegen_spec.mlir
- tests/transform_dialect/cuda/vecadd2d_codegen_spec.mlir
Also add a new pattern to lower transfer ops permutation maps.
> [NFC] Split rank_reducing patterns in transform dialect.

- .github/workflows/benchmark_execution.yml
- .github/workflows/ci.yml
- .github/workflows/run_convperf.yml
- .github/workflows/run_mmperf.yml
- .github/workflows/run_shark_tank.yml
The storage component is now GA.
> Remove usage of `gcloud alpha storage`

- build_tools/github_actions/runner/gcp/image_setup.sh
Your weekly reminder that even if you only changed one tiny thing you
might need to test again... *sigh*
> Add load-bearing = for flag parsing in ops-agent install

- .github/workflows/ci.yml
Missed this on https://github.com/iree-org/iree/pull/11906
Some outputs are using true/false, while others are using 0/1.
> Check for '1' instead of 'true' for write-caches output.

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
All allocations on the LLVM-CPU backend are statically bound. But the way they are lowered today, it might end up as an allocation that is dynamic within some inner loop. Hoist such allocations to the entry block, and use a statically defined stack allocation instead.
> Hoist statically bound allocations to the entry block of a function.

- .github/workflows/ci.yml
- build_tools/cmake/build_all.sh
Full project (compiler and runtime), tracing disabled, assertions on
This would have caught the issue fixed by https://github.com/iree-org/iree/pull/11962 earlier ([logs here](https://github.com/iree-org/iree/actions/runs/4010221786/jobs/6886491220))
> Add `-DCMAKE_BUILD_TYPE=Debug` CI job.

- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/StagedReductionStrategy.cpp
Address post commit comments from https://github.com/iree-org/iree/pull/11945
> [NFC] Address post commit review comments in transform dialect code

- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_promote_operands.mlir
This op promotes the given target's operands specified by the indices.
> Add promote operands op to transform dialect

- compiler/src/iree/compiler/Codegen/Common/FoldTensorExtractOp.td
- compiler/src/iree/compiler/Codegen/Common/WorkgroupSpecializationPass.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertDeviceOps.cpp
- compiler/src/iree/compiler/Dialect/HAL/IR/HALOpFolders.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- compiler/src/iree/compiler/InputConversion/TOSA/TosaToLinalgExt.cpp
- compiler/src/iree/compiler/Modules/HAL/Inline/IR/HALInlineOps.cpp
- integrations/tensorflow/WORKSPACE
LLVM_COMMIT=”734d113a6c88f216b9fe7b8b797006927e3167c6”
MHLO_COMMIT=”d649c4facac29bc7b64b2af842b8c2c13683ad52”
TF_COMMIT=”c21e91eb444462311c9cd136eeba86eba62a6818”
> Integrate llvm-project at 734d113a6c88 and bump dependencies

- build_tools/github_actions/runner/config/register.sh
- build_tools/github_actions/runner/gcp/create_instance_group.sh
- build_tools/github_actions/runner/gcp/create_templates.sh
Makes these scripts a bit more versatile. Still configuring everything
with environment variables, but you shouldn't need to edit the scripts
to use them anymore.
> Make more aspects of MIG creation configurable

- integrations/tensorflow/WORKSPACE
LLVM_COMMIT=”27aeb58ce4d12e15b966dba86738eb65a96703f7”
MHLO_COMMIT=”8c4494120daca5dd2654bfddac1e64f2a741d65b”
TF_COMMIT=”89a60b5149c6e430521d331535a49ac47358e014”
> Integrate llvm-project at 27aeb58ce4d1 and bump dependencies 

- compiler/src/iree/compiler/Codegen/Common/RematerializeParallelOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
Cleanup fixes after https://reviews.llvm.org/D142848 landed in IREE.
> Handle replacements of producer results with results of the fused operation.
