- build_tools/third_party/glslang/BUILD.overlay
> Remove nocopts attribute that is incompatible with Bazel 1.0.

- .gitmodules
We will use this for writing benchmarks of IREE. The dependency should be limited to the benchmarking code.
>  Add submodule for Google benchmark

- .gitmodules
See https://github.com/SDL-mirror/SDL. This is used by the (currently disabled) debugger at https://github.com/google/iree/tree/master/iree/tools/debugger and we may also use it for Vulkan samples.
> Add SDL2 submodule.

- .github/workflows/ci.yml
This moves everything to a single command because `bazel test` actually builds the specified targets as well.
As an added bonus, this should reduce the ~1hr CI time regression accidentally introduced in https://github.com/google/iree/commit/cee878f1e39c4517c4fed51517c20baf41cae20d, which changed the environment between the build and test commands.
Tested:
Since this is on ci-test branch, pushing triggered a run here https://github.com/google/iree/commit/a96c94c9b10dcee0f6c6492db5bf5fe594532952/checks?check_suite_id=319327075
> Make the CI test manual targets

- .github/workflows/ci.yml
These tests are currently marked notap so they get excluded anyway. Having the vulkan env variables set causes HAL tests to fail.
> Remove vulkan sdk from ci

- .github/workflows/ci.yml
This enables the TensorFlow and Python parts of the build, which required installing an up to date tf-nightly from pip and a specific version of Bazel that is supported by TensorFlow. Consequently, these changes add around 45 minutes to the CI runs (1h -> 1h45m).
`--define=iree_tensorflow=true` is set for the entire build. We could instead run builds/tests both with and without that flag set.
Sample run: https://github.com/google/iree/runs/330461202
> Test bindings/... and integrations/... on CI using Bazel.

- .github/workflows/ci.yml
3374b659a260ac59a23b03c9a3dc40651c64e185 fixed the OSS lit test runner so it runs all run lines, not just the first one. This means vulkan tests are actually getting run now and failing because they're not supported in the CI environment
> Disable Vulkan lit tests on GitHub CI

- .github/workflows/ci.yml
It's failing for mysterious reasons here but passing upstream. Disable it for now till we can find the issue.
> Disable simple_embedding_test in GitHub action CI

- .github/workflows/bazel_build.yml
- .github/workflows/cmake_build.yml
These are pretty independent and it's useful to have different statuses for them. Additionally, this would allow running the cmake build on presubmit, since it's sufficiently fast.
The README status badge is going to need to be updated, but because of weirdnesses in our sync to upstream, that will have to be a separate PR.
> Split Bazel and CMake builds into separate actions

- README.md
Remove unnecessary anchor tags from README.
Markdown already creates these tags.
> Remove unnecessary anchor tags from README.

- .github/workflows/bazel_build.yml
Due to different infrastructure, the set of tests we want to exclude from OSS CI is not the same as the ones we want to exclude from internal CI.
I'll remove the exclusion for the notap tag when all tests are also tagged noga
> Add a separate tag for excluding tests from GitHub actions

- .github/workflows/bazel_build.yml
- .github/workflows/cmake_build.yml
- .github/workflows/presubmit.yml
This should simplify things a bit and will hopefully be more robust so we get fewer errors during checkout.
Tested: presubmit (clang-format) and cmake actions still pass. Bazel action is suuuuper slow, so I'm not going to wait for it, but it at least gets to the point of starting the build.
> Use checkout action in workflows

- .github/workflows/bazel_build.yml
Vulkan is the default otherwise and it's not supported in the OSS CI
Tested:
I tried this out on my laptop, which doesn't have vulkan support and now I can run //integrations/tensorflow/e2e:exported_names_test
> Specify supported test backends in CI

- .github/workflows/bazel_build.yml
The samples/rt directory was deleted in https://github.com/google/iree/commit/9ea36a0987167464afa088e94b0dd8d3064813c3. Everything not tagged should build fine.
I also added the --keep_going flag while I was here, so it will be clearer what's failing.
Tested:
bazel query '//... except attr("tags", "noga", //...)' | xargs bazel test --test_env=IREE_VULKAN_DISABLE=1 --test_env=IREE_TEST_BACKENDS="tf,iree_interpreter" --define=iree_tensorflow=true --test_output=errors
> Build everything not tagged with noga in GitHub action CI

- .github/workflows/bazel_build.yml
- .github/workflows/cmake_build.yml
To work around a [bug in GitHub actions](https://github.community/t5/GitHub-Actions/Actions-Reporting-Wrong-Branch-on-Merges/td-p/36966), https://github.com/google/iree/pull/395 makes our CI status look at all push events. We don't want pushes to ci-test to get mixed up with pushes to master. To get the bazel build to run on unsubmitted code, people will have to edit the workflow definition as part of a PR (I don't see any other way around it :-/).
Tested:
The bazel build action doesn't run on this PR and the cmake one only runs with the event label pull_request.
> Don't run actions on pushes to ci-test

- .github/workflows/kokoro_labeler.yml
I'm writing an action to auto-label PRs from the copybara app with "kokoro:run" so we don't have to keep doing it manually. I need to be able to filter for just the service because otherwise the action would try to label all PRs. For PRs coming from the main repo, this would just be redundant (everyone else with write access is a collaborator, so kokoro will run automatically) and may make kokoro confused. For PRs coming from forks it would just fail because they don't have the token to apply labels (GitHub's actions work terribly with forks).
So yeah testing in prod. I don't have any way to get the copybara app to send PRs to my fork. I could just write the action and hope, but I have this suspicion that I'll get it wrong. This action is pretty harmless.
> A GitHub action that prints out the author of a PR

- .github/workflows/synchronize_submodules.yml
This will run after every push to master and synchronize the submodule state, using SUBMODULE_VERSIONS as the source of truth.
Due to constraints with the synchronization tooling from upstream, we cannot push a submodule update from upstream atomically. This will follow fast behind and synchronize the submodules.
There is the risk of races here with other things committing:
1. If this action doesn't finish pushing before another push occurs from elsewhere, it may fail (it will not force push). Since it will try again on the next push, this seems not too bad, and the price we must pay for using eventual consistency instead of atomic updates.
2. If this action completes a push and other automation is trying to push based on the previous HEAD, that automation may fail because the push would …
> Add action to automatically update submodules

- .github/labeler.yml
- .github/workflows/kokoro_labeler.yml
Per the giant comment in the workflow file, this does not present a security risk because it will only run on PRs coming from the main repo.
For security, Kokoro does not run automatically on all PRs (since that would grant RCE), but it does run automatically on PRs from collaborators and Google organization members. Unfortunately, GitHub apps appear to be impossible to register as either.
The labeler action requires a GITHUB_TOKEN with write access to the repository. PRs from forks run within the fork and only receive a token with read access (for security reasons). Thus the label step would fail. The entire job is conditioned on the PR author being the copybara app, so it simply shouldn't run on these other PRs.
> Add GitHub workflow that labels copybara app PRs to trigger kokoro

- .github/workflows/check_submodules.yml
This will confirm that submodule state between `git submodule status` and SUBMODULE_VERSIONS matches.
> Add action to check submodule state on PRs

- .github/workflows/bazel_build.yml
- .github/workflows/cmake_build.yml
- .github/workflows/synchronize_submodules.yml
- git_scripts/submodule_versions.py
This allows originating submodule changes from upstream. The submodule version check will fail on such a PR, but we can test what it will look like after the submodule sync action has made things consistent. Note that this may mean that if someone sends a PR that only updates submodules in the git state they'll get failing presubmits on build. The submodule check presubmit should mitigate the confusion there.
Depends on #471
> Make actions import from SUBMODULE_VERSIONS

- .github/workflows/synchronize_submodules.yml
This avoids push failures in the case where another commit has been added to master in the meantime. Just keeps the status posted to commits a bit cleaner. It will avoid spurious failures like https://github.com/google/iree/runs/394391825
Tested:
Merged this into my fork and confirmed that it aborts early with no submodule changes (https://github.com/GMNGeoffrey/iree/runs/396023603). Pushed a submodule change and confirmed it does synchronization correctly (https://github.com/GMNGeoffrey/iree/runs/396027641 -> https://github.com/GMNGeoffrey/iree/commit/20542cc3a16445819050f31d98fe25cb3fcb1cdd).
> Only run submodule synchronize push if there's a diff

- .github/workflows/presubmit.yml
- third_party/.clang-format
Should make the style check pass on https://github.com/google/iree/pull/696.
Reference: https://clang.llvm.org/docs/ClangFormatStyleOptions.html
> Exclude third_party/ from clang-format presubmit.

- .github/workflows/format.yml
This workflow isn't our only presubmit so rename it.
Also cleaned some other weirdnesses:
1. Switch to default pull_request triggering like we have for other checks. The default is `[opened, synchronize, reopen]`, and I think that works fine for us (Ben was just copying from somewhere else). See https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
2. Remove TODO to only check changed files, `git-clang-format` already does that.
The other option was to merge all presubmits into one workflow. The only savings there is in some boilerplate (they don't actually share any state between jobs), so I went with this as it gave us more flexibility to decide independently when to run different checks. (e.g. we could also run all the checks on …
> Cleanup format presubmit

- .github/workflows/bazel_to_cmake.yml
The action runs bazel_to_cmake.py in strict mode and confirms there are no diffs.
> Run bazel_to_cmake on presubmit

- .github/workflows/bazel_to_cmake.yml
- .github/workflows/check_submodules.yml
- .github/workflows/format.yml
These are cheap and it's useful to be able to see their state on master since we don't actually block submit on them. I think there's no real harm in having them on all pushes either. We can turn them back off it they get noisy or something.
> Run check workflows on push as well

- integrations/tensorflow/compiler/BUILD
- integrations/tensorflow/compiler/DialectRegistration.cpp
- integrations/tensorflow/compiler/dialect/tf_tensorlist/ir/BUILD
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/BUILD
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/CMakeLists.txt
- iree/compiler/Translation/BUILD
- iree/compiler/Translation/CMakeLists.txt
Decouple dialects from shared static registration.
This is necessary to merge https://github.com/google/iree/pull/919 because upstream the registration targets register dialects with static initialization.
We should probably go through and cleanup our registration across iree-opt, iree-tf-opt, python bindings, iree-translate, etc. to get some consistency, but this will at least allow us to move forward.
> Decouple dialects from shared static registration.

- .github/workflows/bazel_build.yml
Introduced in https://github.com/google/iree/commit/3cdfc638b5be92b5168c1cd93835a7593b4ce53a. This sets the default backends for tests that run on "all" backends. 
https://github.com/google/iree/commit/aed15812a515837f4aa76fa631a9d34f8751d95a made the env variable currently being used override the specification of the test which meant some tests started trying to run on unsupported platforms.
> Use IREE_DEFAULT_BACKENDS in GitHub action

- .github/workflows/bazel_build.yml
Bazel CI is going to require JAX for XLA integration. Added
install to build.
> Added pip install jax/jaxlib to bazel build

- .github/workflows/synchronize_submodules.yml
This allows the action to push to the protected master branch. For some reason (still discussing with GitHub support) we have to use the write access token when checking out the repository, not just when pushing, which is why https://github.com/google/iree/pull/1065 didn't work.
Note that the introduction of this token in GitHub secrets means that anyone with write access can push to the protected master branch, but only in a very convoluted fashion. We still avoid accidental pushes.
Tested:
Tried this out in a test branch (https://github.com/google/iree/tree/gcmn-test-submodule-sync)
> Use a custom token for synchronize submodules action

- .github/workflows/update_submodules.yml
The action creates a PR that bumps the TF submodule to HEAD and the LLVM submodule to match the commit used by TF.
This automates some of the toil of keeping the submodules up to date. The build cop is still responsible for reviewing and merging these PRs (including checking that the presubmit builds pass).
Note that if we have manually bumped the LLVM submodule hash and TF hasn't this could mean the PR moves the LLVM submodule back in history.
Tested:
Tried this out in my fork. Here is an example PR it creates: https://github.com/GMNGeoffrey/iree/pull/25
> Add GitHub action to automatically update submodules

- .github/workflows/update_submodules.yml
This would be really annoying and is totally unnecessary. I don't want a PR every day from everyone's fork :-D
Tested:
Tried this out in my fork, both filtering to my fork repository (https://github.com/GMNGeoffrey/iree/runs/522552789) and filtering to the main repository (https://github.com/GMNGeoffrey/iree/actions/runs/59835678)
> Don't run submodule update workflow on forks

- .github/workflows/bazel_build.yml
Reverts google/iree#1047
We found a way to avoid this dependency. See https://groups.google.com/forum/#!topic/iree-discuss/QN7calgcvr0
> Revert "Added pip install jax/jaxlib to bazel build"

- .github/workflows/bazel_build.yml
Switches to use a build/test tag filter approach similar to the Kokoro CI (https://github.com/google/iree/commit/2dd77cca30c7c0af60b2895b3d8de4f7f00b776a). I'd like to factor this all out into a script with better documentation and such, but just trying to unbreak the CI right now.
Tested: No
> Exclude vulkan driver check tests from Bazel CI

- .github/workflows/publish_docs.yml
This commit adds a GitHub action to automatically publish doc
changes to the `gh-pages` branch, which will be rendered nicely
on https://goole.google.io/iree. This includes both docs directly
checked into the docs/ directory and docs auto-generated from
TableGen definitions. For now the former only contains IREE
Design Roadmap; the hope is to refresh existing docs and publish
them one by one.
> Add GitHub Action to automatically publish docs

- .github/workflows/bazel_build.yml
This will replace IREE_DEFAULT_BACKENDS as part of https://github.com/google/iree/pull/1375, but we'll set both for now so that it can be submitted without further breakage (for annoying infra reasons, we can't submit workflow changes as part of the same PR).
Also finally added line breaks to this ridiculously long line. There's some yaml magic you can do with a chomp operator or something, but I just did boring old line continuations.
Tested: No. It's basically impossible.
> Set IREE_AVAILABLE_BACKENDS in Bazel CI

- .github/workflows/update_submodules.yml
Every 6 hours. We can always ignore them if they're not needed, but given that we have people in various timezones, it's better to get good coverage. Also the weekend ones can just be ignored, but if someone is around and cares to update it will already be prepped for them.
> Make automatic submodule updates more frequent

- iree/vm/context.c
- iree/vm/stack.c
- iree/vm/stack.h
Fixes build of `iree/vm:context` on https://github.com/google/iree/pull/1955
> Return void in iree_vm_stack_init.

- CONTRIBUTING.md
- README.md
- docs/repository_management.md
Update documentation for `google` default branch
This intermediate state is part of our migration to be GitHub-first.
Part of https://github.com/google/iree/issues/2279
> Update documentation for `google` default branch

- .github/workflows/lint.yml
- .github/workflows/synchronize_submodules.yml
- .github/workflows/update_submodules.yml
- .yamllint.yml
Linting is nice. The main motivation is that otherwise when adding a new action it's basically impossible to find if parsing just failed and that's why your action isn't running.
Since we've got so many long strings and command lines, I turned off line-length checking. I also disabled document-start check, since I have never seen a GitHub Actions workflow that has one. Everything is either an error or silent, as it should be.
> Add yaml lint check

- integrations/tensorflow/e2e/README.md
A few wording nits and stylistic fixes.
This PR is mostly to deliberately create a merge conflict because this file has also been edited on the `google` branch in https://github.com/google/iree/commit/0dc2f4f95fc24a7500b95406de5dee0851afa788 with conflicting changes.
> Wording edits to TF e2e test README

- build_tools/cmake/build_docs.sh
- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/keras/BUILD
- scripts/prepare_doc_publication.py
- scripts/update_e2e_coverage.py
`update_e2e_coverage.py` is branched from `update_op_coverage.py`, but uses `bazel query` to get the coverage metadata from the `integrations/tensorflow/e2e/...` `BUILD` files.
I manually tested that doc publication works according [the docs](https://github.com/google/iree/tree/gh-pages#making-complex-changes).
> Adds doc generation for a TensorFlow E2E coverage table.

- docs/GetStarted/getting_started_windows_vulkan.md
Actually tested this one, as part of
```
test:vk_swiftshader --test_env="VK_ICD_FILENAMES=D:\\dev\\projects\\iree\\build-swiftshader\\Windows\\vk_swiftshader_icd.json"
```
with `--config=vk_swiftshader` passed to `bazel test`.
> Fix Windows path used for test_env in docs.

- .github/workflows/publish_docs.yml
- build_tools/cmake/build_docs.sh
- scripts/update_e2e_coverage.py
Now we use `bazel query` to get e3e test status. We need to set
up the environment for Bazel.
> Fix publish_docs GitHub Action

- .github/workflows/update_tf.yml
Integration with TF and LLVM will be handled through the `google` branch, so this action should run there. Also renamed the workflow to "update_tf" since it's not actually updating all submodules.
> Change submodule update action to use google branch

- integrations/tensorflow/e2e/BUILD
These tests are newly passing on `iree_llvmjit` and `iree_vulkan`.
> Enables `resource_ops_test` and `sliding_window_test` on the CI.

- README.md
Gave the image alt text better names and made the column ordering match the ordering used everywhere else as well.
> Point build badges at `main` branch

- integrations/tensorflow/e2e/keras/BUILD
This prevents these targets from potentially running on remote servers that don't support non-hermetic tests.
> Add `"no-remote"` tags to "external" targets.

- CMakeLists.txt
- build_tools/cmake/iree_cross_compile.cmake
- build_tools/cmake/iree_macros.cmake
- docs/GetStarted/getting_started_android_cmake.md
Using Windows as the host platform for cross compiling IREE towards
Android requires more cmake arguments than Linux. LLVM is having
problem of detecting host triple when CMake is invoked with Android
toolchain file. This means we need to manually pass in certain
configurations to help it figure out the proper compiler toolchain
for host.
This commit also changes various `TARGET` function parameter names
to `EXECUTABLE` given that for referencing "targets" on host, which
is under another CMake invocation, we need to relying on the generated
executable artifacts. Using `EXECUTABLE` is more clear.
> [cmake] Support cross compilation towards Android with Windows host

- build_tools/bazel/build_tensorflow.sh
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/README.md
- integrations/tensorflow/e2e/batch_norm_test.py
- integrations/tensorflow/e2e/broadcasting_test.py
- integrations/tensorflow/e2e/control_flow_test.py
- integrations/tensorflow/e2e/depth_conv_test.py
- integrations/tensorflow/e2e/dynamic_mlp_relu_test.py
- integrations/tensorflow/e2e/dynamic_mlp_test.py
- integrations/tensorflow/e2e/fill_test.py
- integrations/tensorflow/e2e/iree_e2e_test_suite.bzl
- integrations/tensorflow/e2e/keras/BUILD
- integrations/tensorflow/e2e/keras/iree_vision_test_suite.bzl
- integrations/tensorflow/e2e/keras/lstm_static_test.py
- integrations/tensorflow/e2e/keras/lstm_test.py
- integrations/tensorflow/e2e/keras/train/iree_train_test_suite.bzl
- integrations/tensorflow/e2e/keras/train/model_train_test.py
- integrations/tensorflow/e2e/linspace_test.py
- integrations/tensorflow/e2e/mandelbrot_test.py
- integrations/tensorflow/e2e/math_test.py
- integrations/tensorflow/e2e/matrix_ops_test.py
- integrations/tensorflow/e2e/resource_ops_test.py
- integrations/tensorflow/e2e/ring_buffer_test.py
- integrations/tensorflow/e2e/sliding_window_test.py
- integrations/tensorflow/e2e/strings_test.py
- integrations/tensorflow/e2e/tensorlist_test.py
This change simplifies the target backend specification for `tf_test_utils.py` by:
- Removing `IREE_AVAILABLE_BACKENDS`
- Removing `IREE_OVERRIDE_BACKENDS`
- Removing backend specification from `tf_test_utils.compile_modules()`
- Removing backend specification from all of the `e2e/...` test files (backend specification is now done in the `e2e/...` `BUILD` files).
- Renaming `--override_backends` to `--target_backends`
`TODOs`, bugs and issues are all moved from the test files into the `BUILD` files for easier tracking.
> Simplifies backend specification for `tf_test_utils.py`.

- CMakeLists.txt
- docs/GetStarted/getting_started_android_cmake.md
`CROSS_TOOLCHAIN_FLAGS_NATIVE` is the CMake variable LLVM uses
to set toolchain parameters for the host build. We are passing in
host C/C++ compilers anyway and they are the same. Hide the
complicity internally.
This should be less ugly than the previous lengthy command. ;)
> [cmake] Handle CROSS_TOOLCHAIN_FLAGS_NATIVE internally

- build_tools/cmake/iree_cc_test.cmake
- build_tools/cmake/iree_copts.cmake
- build_tools/cmake/iree_lit_test.cmake
- build_tools/cmake/run_android_test.bat
- build_tools/cmake/run_android_test.ps1
- build_tools/cmake/run_android_test.sh
This commit adds test targets for pushing and running cross
compilation artifacts on Android devices. This makes testing
with Android devices easier: now we just need to run `ctest`
under the cross compilation build directory.
> [cmake] Support running tests on Android device with ctest

- .github/workflows/update_tf.yml
It's so annoying that these errors are not surfaced anywhere useful. At least now with https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml I've got schema-aware linting for these files.
> Fix syntax in TF submodule update action

- CMakeLists.txt
- build_tools/cmake/iree_copts.cmake
- build_tools/third_party/tensorflow/tensorflow/compiler/mlir/hlo/CMakeLists.txt
- build_tools/third_party/tensorflow/tensorflow/compiler/mlir/xla/CMakeLists.txt
With https://github.com/tensorflow/tensorflow/commit/619cc68ce1f2c7b616091ad2b3d5e994cd59db16, the HLO/LHLO dialects were moved to a new directory. This patch updates the CMakeLists accordingly.
> Refactor TensorFlow CMakeLists

- iree/test/e2e/structural/BUILD
- iree/test/e2e/structural/CMakeLists.txt
- iree/test/e2e/structural/fused_dispatch_region.mlir
* Since we are missing an easy way to generate such fusions, this solves the chicken and egg problem of getting something that we can iterate on.
* I specifically wrote this as a sequence that we are unlikely to ever see/fuse at the lowest levels in practice as a test of the infra.
* Also verifies that we can in fact send dispatch regions in to the frontend and everything works (up to codegen).
* Fails for llvm-ir when attempting to lower to buffers.
* Gives us something to progress towards on #2395.
> Add fused_dispatch_region test.

- experimental/ModelBuilder/test/TestVectorToGPU.cpp
- iree/compiler/Conversion/LinalgToSPIRV/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/CMakeLists.txt
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/CooperativeMatrixAnalysis.cpp
- iree/compiler/Conversion/LinalgToSPIRV/CooperativeMatrixAnalysis.h
- iree/compiler/Conversion/LinalgToSPIRV/MarkerUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/MarkerUtils.h
- iree/compiler/Conversion/LinalgToSPIRV/VectorToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_spirv.mlir
The new analysis will be responsible to decide if a chain of
operations should use cooperative matrix extension or not. This allows
removing markers which were not the correct way to handle this. The
analysis is very basic and will be improved in future commits.
> Replace cooperative matrix marker by an analysis class

- iree/hal/vulkan/BUILD
- iree/hal/vulkan/CMakeLists.txt
- iree/hal/vulkan/vulkan_device.cc
This will help with testing. If we wanted to enable/disable emulation based on device characteristics (on buggy drivers), we would want a different mechanism.
> Add flag to force timeline semaphore emulation enabled.

- integrations/tensorflow/e2e/keras/BUILD
- integrations/tensorflow/e2e/keras/iree_vision_test_suite.bzl
Allows for the concise specification of failing `(model, dataset, backend)` tuples in the `iree_vision_test_suite` macro. This allows us to enable the `(MobileNetV2, cifar10, iree_llvmjit)` test, despite `(MobileNetV2, imagenet, iree_llvmjit)` failing.
Edit: The `(MobileNetV2, cifar10, iree_llvmjit)` config is failing again. It has been added back to the list of failing configs, but it will be easy to remove it when it starts passing again.
> Updates `iree_vision_test_suite` to allow for divergences between dataset-backend coverage.

- iree/hal/vulkan/serializing_command_queue.cc
- iree/hal/vulkan/serializing_command_queue.h
SubmissionBatch contains `absl::Span<T>` members and thus must be copied if the data it wraps is expected to live beyond the scope of `CommandQueue::Submit()`: https://github.com/google/iree/blob/d7835cad52c4e74bc71f36a98567b144c92f3837/iree/hal/command_queue.h#L33-L48
https://github.com/google/iree/blob/d7835cad52c4e74bc71f36a98567b144c92f3837/iree/hal/command_queue.h#L82-L86
This was caught by ASAN's [`sanitize-address-use-after-scope`](https://github.com/google/sanitizers/wiki/AddressSanitizerUseAfterScope) running the tests in https://github.com/google/iree/pull/2196.
> Use persistent storage for SubmissionBatch in SerializingCommandQueue.

- iree/hal/cts/BUILD
- iree/hal/cts/CMakeLists.txt
- iree/hal/cts/command_queue_test.cc
Roughly forked from `hal/host:async_command_queue_test`, with generalizations made for testing across HAL backends. For example, I omitted error handling tests without a clear way to trigger or simulate failures that would be recognized by all backends.
> Add hal/cts:command_queue_test.

- kokoro/gcp_ubuntu/bazel/bindings/build_kokoro.sh
- kokoro/gcp_ubuntu/bazel/core/build_kokoro.sh
- kokoro/gcp_ubuntu/bazel/integrations/build_kokoro.sh
- kokoro/gcp_ubuntu/cmake/android/arm64-v8a/build_kokoro.sh
- kokoro/gcp_ubuntu/cmake/build_kokoro.sh
This should fix the issue where our CMake presubmits would sometimes take twice as long as they should.
Explanation:
The problem was that (for some reason) `bash` was evaluating `rm -rf "${KOKORO_ARTIFACTS_DIR?}/*"` to `rm -rf '/tmpfs/src/*'`. The additional single quotes would cause `rm` to fail with a directory not found error, which would be swallowed by the `-f` flag.
Removing the double quotes around the `/*` expansion removes the single quotes that appear when `bash` + `rm` evaluates it. This gives a permission denied error, which we fix by adding `sudo`.
> Fixes a bug where Kokoro's artifacts directory wasn't being deleted.

- iree/vm/context.c
If you just pass a VM bytecode module with no HAL module to `iree_vm_context_create_with_modules`, now the error message is:
```
Unable to resolve VM function 'hal.ex.shared_device'. Are all necessary modules registered?
```
(Encountered while setting up Java bindings)
> Add hint for some vm context function resolution errors.

- iree/hal/vulkan/serializing_command_queue.cc
- iree/hal/vulkan/serializing_command_queue.h
Reverts google/iree#2431
This commit is causing mysterious timeouts in some vulkan configurations. We'll continue to investigate, but to unblock integration, going to revert for now. Lack of GPU testing in OSS is hurting us :cry:
@ScottTodd confirmed that reverting eliminates the timeouts.
> Revert "Use persistent storage for SubmissionBatch in SerializingCommandQueue."

- experimental/ModelBuilder/VulkanWrapperPass.cpp
- experimental/ModelBuilder/test/BUILD
- experimental/ModelBuilder/test/BenchMatMulVectorGPU.cpp
- experimental/ModelBuilder/test/CMakeLists.txt
- experimental/ModelBuilder/test/TestMatMulVulkan.cpp
- experimental/ModelBuilder/test/TestVectorToGPU.cpp
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_spirv.mlir
* Refactor the performance testing for cooperative matrix and move it to
be ran on its own.
* expand the code to loop through different tiling size
to be able to find optimal size.
* Add a mode to check correctness against CPU calculation with smaller
matrices.
* Enable cooperative matrix pattern by default as it is now gatted by
cooperative matrix analysis.
* Change the signature createAddVulkanLaunchWrapperPass to give
better control to the model builder tests.
> Create cooperative matrix performance test

- iree/compiler/Dialect/HAL/Target/LLVM/internal/LLVMAOTTargetLinker.cpp
Check the return value of system and throw an error for non-zero to
avoid warnings about unused results.
> Avoid unused result warning

- .bazelrc
- iree/BUILD.bazel
We've been trying to figure out how to set this for a while and keep
running into warnings in third party code. I think this should take
care of it. We can add additional exclusions as necessary.
Closes #2389
> Treat warnings as errors and silence them in third party code

- integrations/tensorflow/e2e/keras/BUILD
This is required to function properly in open source.
> Use iree_py_binary in keras test binaries

- .github/workflows/lint.yml
- WORKSPACE
- build_tools/embed_data/BUILD
This should reduce errors we only see on import into Google's source repository, where buildifier formatting is enforced.
Includes reformatting the WORKSPACE file, since that wasn't formatted previously (and WORKSPACE files are not checked internally) and marking the source list as not sortable in embed_data/BUILD which is already excluded from sorting internally. Depends on https://github.com/google/iree/pull/2488 which removes usage of native py_binary, that I think would break things in open source anyway. Since that's actually a behavior change, split it into a separate PR.
> Add buildifier lint action

- iree/compiler/Dialect/HAL/Conversion/HALToVM/BUILD
- iree/compiler/Dialect/HAL/Conversion/HALToVM/CMakeLists.txt
- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertControlFlowOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertHALToVM.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/control_flow_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/Transforms/PublicAbiGeneration.cpp
- iree/compiler/Dialect/HAL/Transforms/test/public_abi_generation.mlir
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Dialect/VM/IR/test/control_flow_ops.mlir
Progress on exposing semaphores for bindings to use, per discussions relating to https://github.com/google/iree/issues/1285.
At the moment these `$async` functions just wrap the `$sync` functions and include wait/signal semaphore arguments. A future change can go through and invert this (`$sync` wrap `$async` and wait/signal local semaphores).
IR looks roughly like:
```mlir
func main$sync(buffer_view_args...) -> hal.buffer_view attributes { ... } {
// buffer_view handling
call @main
// buffer_view handling
}
func main$async(wait_semaphore, wait_value, buffer_view_args..., signal_semaphore, signal_value) -> hal.buffer_view {
hal.semaphore.await wait_semaphore, wait_value
call @main$sync
hal.semaphore.signal signal_semaphore, signal_value
}
```
Here is a more complete snippet: …
> Start creating $async functions as part of public ABI generation.

- build_tools/cmake/build_android.sh
This can serve as a temporary solution to unblock development
until the root case for https://github.com/google/iree/issues/2494
is discovered and fixed.
> [ci] Run cmake --build twice to temporary fix the flaky build

- build_tools/docker/bazel/Dockerfile
- build_tools/docker/build_and_update_gcr.py
Part of https://github.com/google/iree/issues/2495
Tested:
Pushed images with the `latest` tag and updated Kokoro to point at
them in this PR:
- https://source.cloud.google.com/results/invocations/c88b58e2-a6e9-479e-bf97-fddcb93b0fb1
- https://source.cloud.google.com/results/invocations/2a8af5a3-0387-425d-9597-cf6cd04fa4ad
- https://source.cloud.google.com/results/invocations/d6336b85-30a2-4c78-b25a-3126a482bab8
Will drop the "latest" tag commit before merging and then push a
prod image update after.
Did an actual upgrade of the requested Bazel version in
https://github.com/google/iree/pull/2496 and ran Kokoro with the
new images on that as well.
> Add Bazel 3.3.1 to docker images

- experimental/ModelBuilder/ModelRunner.cpp
Unlike MLIR, LLVM `createXXX` pass creation functions return a raw pointer.
Wraper this pointer into a unique_ptr to cleanup on scope exit.
> [ModelBuilder] Fix leak when using llvm::createLowerMatrixIntrinsicsPass

- integrations/tensorflow/bindings/python/pyiree/tf/support/BUILD
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
- integrations/tensorflow/e2e/README.md
- `BackendInfo` and all classes related to `CompiledModule` are all moved to `tf_utils.py` as they have functionality outside of testing.
- `_IreeModuleInstance` and `_TfModuleInstance` are both subsumed into `IreeCompiledModule` and `TfCompiledModule` respectively.
- This provides a simple high level API for compiling `tf.Module`s in Python via `IreeCompiledModule.compile(...)` and then directly using them for computation.
- The ability to create reinitialized instances is now provided via `ComiledModule.from_existing(module)`.
- A unit test of this functionality is also added.
> Moved CompiledModule and BackendInfo to `tf_utils.py`

- .github/workflows/publish_docs.yml
This was broken by the Bazel upgrade, but I didn't notice because it isn't covered by any presubmits. Sorry!
Part of https://github.com/google/iree/issues/2510
> Update Bazel version in docs workflow

- .bazelrc
- build_tools/cmake/iree_copts.cmake
- iree/compiler/Dialect/HAL/Transforms/PublicAbiGeneration.cpp
We've been passing with this enabled before, but were not enforcing it in open source builds.
> Enable -Wunused-variable warning.

- .bazelrc
Building with RBE will require upgrading to Bazel 3.0+ because of https://github.com/google/oss-fuzz/issues/3093. TF is already on 3.1.0, so we should probably upgrade anyway.
Tested:
`bazel test --config=rs --config=asan //iree/...`
Two vulkan failures:
https://source.cloud.google.com/results/invocations/fa1c4e13-305e-4467-aac5-97773a0ecf57
Reverted the type registration added to fix a leak in https://github.com/google/iree/commit/dde06c02c007578a25f5c584f7316c6466b8ff69 and confirmed an asan failure
`bazel test --config=rs --config=asan //iree/vm:list_test`
https://source.cloud.google.com/results/invocations/7dfc3bcc-b837-4139-9649-f4156dd782bf
> Add config to build with asan

- .bazelrc
A few misc cleanups to our bazelrc:
1. Avoid duplicate config expansion, which creates annoying warnings.
2. Turn visibility checking back on, since we're now using Ruy from its own repo.
3. Add a few more documentation comments and fix some column limits.
> Cleanup bazelrc

- integrations/tensorflow/e2e/BUILD
This test is now passing internally on Vulkan and @ScottTodd has tested it locally in OSS.
> Enables `tensorlist_test` on `vulkan`.

- integrations/tensorflow/e2e/BUILD
These tests are blocking https://github.com/google/iree/pull/2512. Looks like they started failing with https://github.com/google/iree/pull/2509.
> Disable Vulkan tests which are now failing.

- experimental/ModelBuilder/BUILD
- experimental/ModelBuilder/ModelRunner.cpp
This dep is not actually required.
Tested:
Removed from .bazelignore and ran all builds and tests.
No new failures.
Before: https://source.cloud.google.com/results/invocations/7acb7108-9f66-490b-a3d6-b6e57a3fe759/targets
After: https://source.cloud.google.com/results/invocations/0e9f5cd8-97c2-4f4c-8b51-545ceff0df65
> Remove ModelBuilder dep from ModelRunner

- .github/workflows/update_tf.yml
This will make PRs/commits with a title that's within standard
character limits but still linkified by GitHub. It matches the style
in the `scripts/git/update_tf_submodule.sh` script.
> Update TF submodule bump action to match script

- docs/contributor_tips.md
- scripts/git/bazel_to_cmake.sh
- scripts/git/git_update.sh
- scripts/git/google_to_main.sh
- scripts/git/main_to_google.sh
- scripts/git/update_tf_submodule.sh
- Factor update into a separate script. It's pretty verbose.
- Fetch the base branch for doing comparisons in merge scripts.
- Have uniform error handling for missing `gh`
- Some other consistency between the scripts.
- Turn of `set -x`. Current script messaging is better than that
gets us.
Example PRs created by these scripts (because testing in prod
is the only testing):
https://github.com/google/iree/pull/2554
https://github.com/google/iree/pull/2555
https://github.com/google/iree/pull/2553
> Clean up maintenance scripts

- .bazelrc
- build_tools/cmake/iree_copts.cmake
- iree/tools/vm_util.cc
Is there an equivalent of `--per_file_copt=-external/.*@-Werror` that we can use for CMake?
> Fix Werror specification and fix unused variable.

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/e2e/batch_norm_test.py
- integrations/tensorflow/e2e/broadcasting_test.py
- integrations/tensorflow/e2e/concat_test.py
- integrations/tensorflow/e2e/control_flow_test.py
- integrations/tensorflow/e2e/conv_test.py
- integrations/tensorflow/e2e/depth_conv_test.py
- integrations/tensorflow/e2e/dynamic_mlp_relu_test.py
- integrations/tensorflow/e2e/dynamic_mlp_test.py
- integrations/tensorflow/e2e/explicit_backend_test.py
- integrations/tensorflow/e2e/fill_test.py
- integrations/tensorflow/e2e/gather_test.py
- integrations/tensorflow/e2e/keras/lstm_static_test.py
- integrations/tensorflow/e2e/keras/lstm_test.py
- integrations/tensorflow/e2e/keras/train/model_train_test.py
- integrations/tensorflow/e2e/keras/vision_model_test.py
- integrations/tensorflow/e2e/linspace_test.py
- integrations/tensorflow/e2e/mandelbrot_test.py
- integrations/tensorflow/e2e/math_test.py
- integrations/tensorflow/e2e/matrix_ops_test.py
- integrations/tensorflow/e2e/resource_ops_test.py
- integrations/tensorflow/e2e/ring_buffer_test.py
- integrations/tensorflow/e2e/scatter_update_test.py
- integrations/tensorflow/e2e/simple_arithmetic_test.py
- integrations/tensorflow/e2e/simple_stateful_test.py
- integrations/tensorflow/e2e/sliding_window_test.py
- integrations/tensorflow/e2e/strings_test.py
- integrations/tensorflow/e2e/tensorlist_test.py
- `SavedModelTestCase` is renamed to `CompiledModuleTestCase`, since we have moved away from using `SavedModel`s as inputs to our e2e tests.
- Now `tf_test_utils.compile_module` and `CompiledModule.create` both take a `tf.Module` subclass as their input. Previously we allowed either a "`tf.Module` subclass" or a "function which returns a `tf.Module` subclass instance" to be passed under the name `ctor`. This also allows us to assume that `module_class` has a `__name__` attribute, which we can use when saving compilation/benchmarking artifacts.
> Simplify module compilation and rename `SavedModelTestCase`

- iree/base/atomics.h
- iree/modules/tensorlist/native_module.cc
* Reworks some atomic syntactic things (I *think* what I did is legal, but this is skating pretty far into compiler specific territory).
* Other misc fixes.
* Passes most tests in debug builds (appears to be just GPU tests failing -- I don't have a GPU in this container).
* Saw some evidence that release builds are segfaulting in iree-translate. Not yet triaged.
* This makes iree building in dockcross manylinux2014-x64 (needed to build portable pips).
Fixes #1269
> Fix compile issues for gcc 9.1.1.

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
* Found on gcc 9.1 Release build.
* With this fix, non-GPU tests pass on gcc 9.1 (GPU tests not verified).
Fixes #2570
> Fix bad stack access to ArrayRef.

- bindings/python/pyiree/rt/vm.cc
- iree/samples/simple_embedding/simple_embedding_test.cc
- iree/tools/run_module_main.cc
Lists were not being freed resulting in errors for some of our vulkan tests.
> Fixed vulkan errors with not destroyed lists and incorrect error check on pybindings

- packaging/python/common_setup.py
- packaging/python/setup_compiler.py
- packaging/python/setup_rt.py
- packaging/python/setup_tf.py
* This will do the right thing when building from a directory that contains multiple version/platform specific extension modules.
> Use the actual versioned extension suffix when building wheels.

- CMakeLists.txt
- build_tools/cmake/flatbuffer_c_library.cmake
This commit also defines iree_host_build_flatcc_cli when not
cross compiling so we can depend on it in iree_flatbuffer_c_library.
Also copy flatcc_cli from the proper place. They install it
in the source directory...
> Fix flatcc target name and binary path

- iree/hal/cts/semaphore_test.cc
Semaphore test is failing with SwiftShader / commit tests. Disabling
to unblock queue.
> Disabled Semaphore test

- iree/samples/simple_embedding/simple_embedding_test.cc
- iree/tools/run_module_main.cc
As the docs state this is only valid for lists initialized with
iree_vm_list_initialize.
> Fixing incorrect use of iree_vm_list_deinitialize.

- kokoro/gcp_ubuntu/simulate_kokoro.sh
This script simulates running Kokoro on your local machine.
Just sets up some env variables and a tmpdir.
Was useful for https://github.com/google/iree/issues/2565
> Add script for simulating Kokoro locally

- build_tools/cmake/iree_multipy.cmake
This gets the CMake Python tests closer to running/passing on Windows. There was no regression in https://github.com/google/iree/pull/2590, the old `iree_py_test.cmake` also had this issue.
`ctest -L bindings/python -V` output before:
```
353: Test command: D:\dev\projects\iree\build_tools\cmake\run_test.sh "C:/Users/Scott/scoop/shims/python3.exe" "D:/dev/projects/iree/bindings/python/pyiree/compiler/compiler_test.py"
353: Environment variables:
353:  PYTHONPATH=D:/dev/projects/iree-build-py/bindings/python:
353:  TEST_TMPDIR=bindings_python_pyiree_compiler_compiler_test_DEFAULT_test_tmpdir
353: Test timeout computed to be: 10000000
Process not started
D:/dev/projects/iree/build_tools/cmake/run_test.sh
[unknown error]
5/5 Test #353: bindings/python/pyiree/compiler:compiler_test__DEFAULT …
```
> Use ${IREE_HOST_SCRIPT_EXT} in CMake iree_py_test.

- kokoro/gcp_ubuntu/bazel/bindings/build_kokoro.sh
- kokoro/gcp_ubuntu/bazel/core/build_kokoro.sh
- kokoro/gcp_ubuntu/bazel/integrations/build_kokoro.sh
- kokoro/gcp_ubuntu/cmake/android/arm64-v8a/build_kokoro.sh
- kokoro/gcp_ubuntu/cmake/build_kokoro.sh
- kokoro/gcp_ubuntu/cmake/linux/x86-turing/build.sh
- kokoro/gcp_ubuntu/cmake/linux/x86-turing/build_kokoro.sh
- kokoro/gcp_ubuntu/docker_common.sh
This avoids everything having root permissions, created files being
owned by root, and other nastiness. This is made slightly more
complicated by Google linux machine's...creative... setup for user
management. All these scripts can be run locally provided the appropriate
env variables are set, which can be done with the script provided in
https://github.com/google/iree/pull/2588.
This was the root cause for https://github.com/google/iree/issues/2565.
The image we're using for the GPU builds doesn't have passwordless sudo
so we couldn't delete the Kokoro artifacts directory.
Fixes https://github.com/google/iree/issues/2565
> Avoid docker running as root

- build_tools/cmake/iree_multipy.cmake
- build_tools/manylinux_py_setup.py
* If not linking against libraries (as on Linux for deployment), build in MODULE mode.
* Include numpy in the python deps to install.
> A couple of python build tweaks.

- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/base/api.h
- iree/base/time.h
- iree/base/time_test.cc
- iree/hal/cts/semaphore_test.cc
Fixes https://github.com/google/iree/issues/2604
This loop in emulated timeline semaphores was never terminating with `deadline_ns == InfinitePast()`: https://github.com/google/iree/blob/7dd38828dae845aa2f48da76811e009781812944/iree/hal/vulkan/emulated_timeline_semaphore.cc#L115
> Fix time bug with new tests, re-enable SemaphoreTest cases.

- build_tools/cmake/run_android_test.sh
They can cause huge print spree in CI environments.
> [android] Ignore adb push status for the executable

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
- integrations/tensorflow/e2e/README.md
`CompiledModule` used to use a static `create` method to dynamically create `CompiledModule` subclasses of the correct type. This can be done just as well using the class on a `BackendInfo` value, and avoids using non-standard constructors.
`compile` and `from_existing` were spiritual successors of this method, and have been removed in favor of using the default constructor and a `create_reinitialized` method that passes `__init__` a `_` prefixed arg.
> Removes non-standard constructors from `CompiledModule`

- iree/test/e2e/xla_ops/iota.mlir
This op is supported in VMLA but doesn't have a test.
> Add iota.mlir test to e2e/xla_ops/

- .github/workflows/update_tf.yml
This sends me a lot of email and doesn't add much value, I think.
There is the option to use team reviewers. We could look at creating a
team for the build cops. It would be really nice to request review from
or tag someone dynamically based on our build cop rotation, but not sure
how to do that.
> Stop always sending TF update PRs to gcmn

- CMakeLists.txt
- build_tools/cmake/iree_check_test.cmake
- docs/get_started/cmake_options_and_variables.md
We don't want LLVM JIT as part of the IREE runtime when on Android.
This commit serves as the first step as disabling it by turning
off tests.
Along the way, made the compiler target backend names consistent
with what's used elsewhere.
Progress on https://github.com/google/iree/issues/2528
> [android] Disable LLVM JIT HAL driver related tests

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
The `iree_input__<backend>.mlir` files are all identical, and the `tf_input__<backend>.mlir` files are all identical up to constants in their function names. For example:
```mlir
<   func @__inference_simple_matmul_70(%arg0: tensor<128x3072xf32> {tf._user_specified_name = "a", tf_saved_model.index_path = [0]}, %arg1: tensor<3072x256xf32> {tf._user_specified_name = "b", tf_saved_model.index_path = [1]}) -> (tensor<128x256xf32> {tf_saved_model.index_path = []}) attributes {tf._input_shapes = [#tf.shape<128x3072>, #tf.shape<3072x256>], tf_saved_model.exported_names = ["simple_matmul"]} {
---
>   func @__inference_simple_matmul_670(%arg0: tensor<128x3072xf32> {tf._user_specified_name = "a", tf_saved_model.index_path = [0]}, %arg1: tensor<3072x256xf32> {tf._user_specified_name = "b", …
```
> Removed duplicate per-backend tf and iree input mlir files.

- build_tools/kokoro/gcp_ubuntu/docker_common.sh
I mixed up some paths here. These just happen to work right now because
/etc/group is also a valid /etc/passwd file, but that's not great. Also
I realized that `getent` already produces everything I need if invoked
without a specific group or user argument.
Tested:
Ran the simulate_kokoro script locally:
```shell
./build_tools/kokoro/gcp_ubuntu/simulate_kokoro.sh \
build_tools/kokoro/gcp_ubuntu/bazel/linux/x86/core/build_kokoro.sh \
"$PWD/.git"`
```
> Fix fake group and passwd files for Docker

- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
Also tested on Android, it's passing.
> Enable while.test mlir on vulkan-spirv backend.

- build_tools/third_party/sdl2/SDL_config_windows.h
It wasn't building cleanly with our existing Bazel overlay files and MSVC.
Fixes https://github.com/google/iree/issues/2456
> Disable SDL sensor support on Windows.

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToLLVM/MatMulVectorization.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/matmul_vectorization.mlir
Adds a pass to lower linalg.matmul into multi-level tiled vector ops. 
The tile sizes and vector ops configurable by `iree-codegen-linalg-to-llvm-matmul_*` flags
> Add matmul tile and vectorize lowering stratgy to LinalgToLLVM passes

- bindings/python/build_tools/python/generate_build.py
* Some python versions/installations use trampoline headers at the root.
> Include python headers even if nested.

- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86/integrations/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/docker_common.sh
Instead of mounting the user's existing Bazel cache, create a fake home
directory under the Kokoro root directory.
This is another attempt at https://github.com/google/iree/pull/2566
which had to be rolled back for the Bazel integrations build because it
made it three times slower. It turns out the root cause there is that
the docker container volumes are by default mounted in /tmpfs which on
Kokoro is a local-ssd. The home directory, on the other hand, is a
persistent SSD. The integrations job is running Bazel with 64 cores,
which means it's IO bound. The difference turns out to be substantial.
Fixes https://github.com/google/iree/issues/2653
Tested:
Ran simulate_kokoro on the core build locally to confirm this doesn't
break RBE cloud credentials.
The integrations presubmit on this PR …
> Avoid running docker builds as root

- iree/compiler/Dialect/Shape/IR/ShapeOps.cpp
Previously this could result in failed verification without further info.
> Report error message for type mismatch

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRTarget.cpp
This makes builds with MSVC pass; hopefully it isn't whackamole with clang.
> Working around duplicate func->llvm.func rewrites.

- build_tools/embed_data/generate_cc_embed_data.cc
- iree/vm/bytecode_module_impl.h
Android NDK does not have cstdalign.
> Fix stdalign include in Android

- build_tools/bazel/iree.bazelrc
* A number of warning flags need to be adapted.
* Since just starting to support it, nothing is defined.
> Add a config for gcc.

- bindings/python/pyiree/compiler/CMakeLists.txt
- bindings/python/pyiree/compiler/unix_version.lds
- bindings/python/pyiree/rt/CMakeLists.txt
- bindings/python/pyiree/rt/unix_version.lds
- build_tools/cmake/iree_multipy.cmake
* Keeps multiple extensions in the same process from interfering with each other.
* This was dropped at some point when porting and is required.
Fixes #2706
> Add linker scripts to cmake pyiree builds to hide symbols.

- integrations/tensorflow/e2e/keras/BUILD
This change enables the following previously failing configurations:
- `MobileNet, cifar10, iree_llvmjit`
- `MobileNet, cifar10, iree_vulkan`
- `MobileNetV2, cifar10, iree_llvmjit`
I tested that these are passing locally in OSS with `swiftshader` and internally.
> Enables newly passing `MobileNet` and `MobileNetV2` vision tests

- integrations/tensorflow/e2e/BUILD
`conv_test` is passing locally with swiftshader, internally and in the CI on an Nvidia GPU. Also added a note that `sliding_window_test` passes on SwiftShader (but fails on an Nvidia GPU).
> Enables `conv_test` on vulkan.

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/keras/BUILD
- integrations/tensorflow/e2e/keras/lstm_static_trace_test.py
- integrations/tensorflow/e2e/simple_arithmetic_trace_test.py
- integrations/tensorflow/e2e/strings_trace_test.py
This is a part of a larger shift toward integrating our testing infrastructure with generating artifacts for benchmarking. Part of how we are planning to doing this is by tracing the inputs and outputs to our `CompiledModules` during our tests, and then using those traces as inputs to `iree-benchmark-module`. The aim is for these traces to tell the benchmark module which (series of) inputs to use, and what outputs to check for while the benchmark is warming up.
This change focuses on prototyping what that shift will look like for our testing infra. A class `TracedModule` is added to capture the data described above, and only the functionality that the testing infra needs of it is developed here.
Changes:
- Adds a class `TracedModule` which wraps a `CompiledModule` to capture the inputs …
> Adds a class for tracing module calls and example tests.

- build_tools/cmake/run_android_test.sh
This reverts commit af3ed51fa104a9f03115823391f18391ea278ffc.
At the moment being verbose to help debugging issue is more important
than clean log.
> Revert "[android] Ignore adb push status for the executable (#2627)"

- docs/get_started/getting_started_android_cmake.md
- iree/hal/vulkan/dynamic_symbols.cc
Adreno Vulkan ICD implemenations does not directly expose
vkGetInstanceProcAddr; it has qglinternal::vkGetInstanceProcAddr
we can use though.
> [vulkan] Add a workaround for enabling tests on Adreno GPUs

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir
- iree/hal/dylib/dylib_executable.cc
- iree/hal/llvmjit/llvmjit_executable.cc
Pass push_constant as array of int32 values and zero-extend to int64 when filling indices.
> Use !llvm<i32*> instead of !llvm<i64*> to pass push_constant

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/README.md
- integrations/tensorflow/e2e/keras/BUILD
- scripts/update_e2e_coverage.py
`BackendInfo` is refactored from a wrapper around a set of `NamedTuple`s into it's own class. This allows for the name attribute to be overridden, which is necessary for supporting saving artifacts for duplicate backends (e.g. two copies of `"iree_vmla"`). It also provides a cleaner API for compiling modules and getting all `BackendInfo` configurations.
Changes this allows:
- Compilation artifacts and traces from duplicate target backends will not overwrite each other. Instead artifacts for each backend are saved with an index (e.g. `trace__iree_vmla_0.txt`, `trace__iree_vmla_1.txt` and so on).
- The reference backend will have `_ref` appended to it's name (e.g. `trace__tf_ref.txt` or `trace__iree_vmla_ref.txt`).
- `tf_also` is removed.
Example artifacts:
```
SimpleArithmeticModule
├── …
```
> Refactor BackendInfo, remove tf_also, fully support duplicate backends

- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader/continuous.cfg
- kokoro/gcp_ubuntu/bazel/bindings/common.cfg
- kokoro/gcp_ubuntu/bazel/bindings/google.cfg
- kokoro/gcp_ubuntu/bazel/bindings/main.cfg
- kokoro/gcp_ubuntu/bazel/bindings/presubmit.cfg
- kokoro/gcp_ubuntu/bazel/core/common.cfg
- kokoro/gcp_ubuntu/bazel/core/google.cfg
- kokoro/gcp_ubuntu/bazel/core/main.cfg
- kokoro/gcp_ubuntu/bazel/core/presubmit.cfg
- kokoro/gcp_ubuntu/bazel/integrations/common.cfg
- kokoro/gcp_ubuntu/bazel/integrations/google.cfg
- kokoro/gcp_ubuntu/bazel/integrations/main.cfg
- kokoro/gcp_ubuntu/bazel/integrations/presubmit.cfg
- kokoro/gcp_ubuntu/cmake/android/arm64-v8a/common.cfg
- kokoro/gcp_ubuntu/cmake/android/arm64-v8a/google.cfg
- kokoro/gcp_ubuntu/cmake/android/arm64-v8a/main.cfg
- kokoro/gcp_ubuntu/cmake/android/arm64-v8a/presubmit.cfg
- kokoro/gcp_ubuntu/cmake/common.cfg
- kokoro/gcp_ubuntu/cmake/google.cfg
- kokoro/gcp_ubuntu/cmake/linux/x86-turing/common.cfg
- kokoro/gcp_ubuntu/cmake/linux/x86-turing/google.cfg
- kokoro/gcp_ubuntu/cmake/linux/x86-turing/main.cfg
- kokoro/gcp_ubuntu/cmake/linux/x86-turing/presubmit.cfg
- kokoro/gcp_ubuntu/cmake/main.cfg
- kokoro/gcp_ubuntu/cmake/presubmit.cfg
Reverts google/iree#2757
Broke the `cmake/linux/x86-turing/main` build, which isn't run on presubmit. I must have missed something.
> Revert "Delete old Kokoro configs"

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/linalg_tensor_to_buffer.mlir
HLOToLinalgOnBuffers didnt handle the case of the same tensor SSA
value being used as operands in multiple hal.interface.store_tensor
ops. Fix for this is to maintain a separate map from
hal.interace.store_tensor -> iree.placeholder and use this to decide
if a copy is needed or not.
> Handle same tensor value being used in multiple hal.interface.store_tensor ops

- build_tools/cmake/build_android.sh
We are not seeing flakiness in cross compilation for a while. It seems
the issue was addressed somehow.
This reverts commit 028a883090f58129ae1dfaa67150f86bc1bc6ff6.
> Revert "invoking cmake --build twice (#2501)"

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
Adds mlir style dtype and shape information to the e2e test logs. If there are multiple inputs or outputs then they will be displayed as a comma separated list.
```
2. Method: calculate
Inputs: <class 'float'>, <class 'float'>, <class 'float'>, <class 'int'>, <class 'int'>
-0.743644786
0.1318252536
2.9336e-06
400
3000
Outputs: 400x400xf32
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ... 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ... 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ... 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ... 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ... 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ... 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ... 1. 1. 1. 1. 1. 1. 1. 1. 1. …
```
> Add shape and dtype information to e2e logs

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/depth_conv_test.py
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/conv.mlir
Lower 'mhlo.conv' with dpethwise convolution properties to 'linalg.generic' on Buffers.
Lowering depthwise convolution to linalg.generic op. The idea is to use the group convolution formulation to perform the separable depth wise convolution as the following, given an n-dimensional input x and filter w the direct convolution operation can be written as following expression that performs reduction over kernel dimensions k1..kn.  
``` 
y[n, d1, d2, ..., dn, ci * groupSize + co] = sum(x[n, d1 * stride1 + k1, d1 * stride2 + k2, ..., dn * striden + kn] * w[k1, k2, ..., kn, ci, co], k1, k2, ..., kn)
```
> Detect and lower depthwise conv to linalg.generic

- integrations/tensorflow/e2e/keras/BUILD
Although this only tests compilation because the output values are too small to compare, it's worth to enable the test.
> Enable MobileNet cifar10 test on vulkan-spirv.

- build_tools/cmake/build_android.sh
Flakiness has returned/never left.
https://source.cloud.google.com/results/invocations/b1905e8b-ef34-42a5-8d57-4cce7dd994c9
Reverts google/iree#2772
> Revert "Revert "invoking cmake --build twice (#2501)""

- iree/tools/init_mlir_passes.h
These create callls don't actually do anything anymore (if they ever
did). We have a new registration mechanism in MLIR thanks to
https://github.com/llvm/llvm-project/commit/2a6c8b2e9581.
This actually adds registration for a single affine pass we didn't
have before `AffineParallelizePass` because it uses the registration
for all Affine passes.
A diff of the sorted help text from iree-opt:
https://gist.githubusercontent.com/GMNGeoffrey/db6add0ca60759c2dcde0c3fa83ca1b9/raw/c5dd07006a1d36b459bf5e25edb65759ac5bd6f0/iree-opt%2520diff
> Use new registration for MLIR passes

- .github/workflows/publish_docs.yml
There is little benefit to have the doc refreshed on every commit;
we aren't gonna chnage them that frequently. Also because now we
use iree-opt to dump IR conversion examples, we need more cycles
for compilation. This reduces the burden of that.
> [doc] Change doc publication from every commit to every day

- build_tools/bazel/iree.bazelrc
I've turned on autoscaling for our pool. This should decrease the
upper bound on build times, especially with local builds. CI builds
are already dominated by VM setup and cloning time.
> Increase job count for RBE

- integrations/tensorflow/e2e/depth_conv_test.py
- integrations/tensorflow/e2e/keras/BUILD
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
The code incorrectly fetching groupSize & groupCount indices instead of values. This PR fixes that, adds an extra test case for depthwise conv and enable MobileNetV{1,2} e2e integration tests.
> Fix depthwise_conv groupSize and groupCount

- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/base/api.cc
Intermediate fix for https://github.com/google/iree/issues/2801
Documentation for std::chrono: https://en.cppreference.com/w/cpp/header/chrono, which is standard since C++11. I tested that this builds on Windows/MSVC and Linux/Clang.
> Switch from absl::GetCurrentTimeNanos() to std::chrono.

- iree/compiler/Dialect/IREE/IR/IREETypes.cpp
- iree/compiler/Dialect/Sequence/IR/SequenceTypes.cpp
- iree/compiler/Dialect/VM/IR/VMTypes.cpp
Support for subclass data on the base mlir::TypeStorage class is being
removed. This revision removes all references to subclass data from IREE
types.
> Remove references to TypeStorage subclass data

- iree/hal/cts/command_queue_test.cc
If one of the listed drivers is not available, this will correctly exclude it.
This should let us roll-forward https://github.com/google/iree/pull/2759
> Refactor HAL driver filtering in command_queue_test.

- scripts/git/google_to_main.sh
- scripts/git/main_to_google.sh
- scripts/git/summarize_changes.sh
This is getting complex enough for a wrapper.
This change also includes a pipe to awk to strip the trailing whitespace
that `git log` insists on creating. I couldn't find any way to get git
log to truncate without padding (See
https://git-scm.com/docs/git-log#Documentation/git-log.txt-emltltNgttruncltruncmtruncem)
> Extract commit summarization into a script

- iree/compiler/Conversion/CodegenUtils/MatmulCodegenStrategy.cpp
- iree/compiler/Conversion/LinalgToSPIRV/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/CMakeLists.txt
- iree/compiler/Conversion/LinalgToSPIRV/MatMulVectorizationTest.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Passes.h
- iree/compiler/Conversion/LinalgToSPIRV/test/matmul_vectorization.mlir
- iree/compiler/Conversion/init_conversions.h
Move the transformation doing LICM and transfer_op hoisting as we want
those to happen after unroll transformation. Also add a test file to be
able to unit test matmul vector lowering strategy for GPU.
> Move LICM and hoisting after staged transforms in matmul strategy

- build_tools/cmake/iree_copts.cmake
Required to bump the IREE submodule used in
https://github.com/iml130/iree-template-cpp. TensorFlow is otherwise
unable to find tablegenerated files.
> Extend IREE_COMMON_INCLUDE_DIRS for external dialects

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
- integrations/tensorflow/e2e/README.md
- Store compiled modules in `/tmp/iree/modules/ModuleName/backend_name/compiled.vmfb`
- Fall back to `compiled__backend_1__backend_2.vmfb` if `compile_tf_module` is called with multiple backends.
- Organize traces by their backend (e.g. `/tmp/iree/modules/ModuleName/backend_name/traces/trace_function/log.txt`).
- Add 'Generated Artifacts' section to E2E readme.
> Use a hierarchical directory structure for E2E test artifacts

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
Use `try`/`except` to to run `os.makedirs` to give it similar behavior to `mkdir -p`, which doesn't fail if the directory already exists.
This was the cause of this [post-submit failure](https://source.cloud.google.com/results/invocations/fdc5d110-9ddb-444a-8ab9-f151c6b17018/targets).
> Add `tf_utils._makedirs` to address race condition.

- bindings/python/pyiree/compiler/compiler.cc
- integrations/tensorflow/compiler/dialect/tf_strings/ir/dialect.cpp
- integrations/tensorflow/compiler/dialect/tf_strings/ir/types.h
- integrations/tensorflow/compiler/dialect/tf_tensorlist/ir/tf_tensorlist_types.h
- iree/compiler/Dialect/HAL/IR/HALTypes.h
- iree/compiler/Dialect/IREE/IR/IREEDialect.cpp
- iree/compiler/Dialect/IREE/IR/IREETypes.h
- iree/compiler/Dialect/IREE/Tools/StructAttrGen.cpp
- iree/compiler/Dialect/Modules/Strings/IR/Types.h
- iree/compiler/Dialect/Modules/TensorList/IR/TensorListTypes.h
- iree/compiler/Dialect/Sequence/IR/SequenceDialect.cpp
- iree/compiler/Dialect/Sequence/IR/SequenceTypes.h
- iree/compiler/Dialect/Shape/IR/ShapeDialect.cpp
- iree/compiler/Dialect/Shape/IR/ShapeTypes.h
- iree/compiler/Dialect/VM/IR/VMDialect.cpp
- iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- iree/compiler/Dialect/VM/IR/VMTypes.h
- iree/compiler/Dialect/VMLA/IR/VMLATypes.h
- iree/compiler/Dialect/Vulkan/IR/VulkanAttributes.h
- iree/samples/custom_modules/dialect/custom_dialect.h
The need/existence of these are being removed from upstream MLIR.
> Remove uses of kind on derived mlir Attribute and Type classes

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
This currently prints a misleading error message
`AssertionError: ['tf'] has length of 1`, which suggests that somehow
the lenght of this variable is the problem. We can just fail directly
without this.
> Avoid confusing error message in TF tests

- integrations/tensorflow/bindings/python/pyiree/xla/compiler/BUILD
This cannot be built or analyzed in OSS due to a missing grpc
dependency. It causes wildcard builds to fail during analysis.
> ERROR: 
[snip]/external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/BUILD:9:20:
no such target '//external:grpc_lib': target 'grpc_lib' not declared in
package 'external' defined by
[snip]/iree/WORKSPACE and referenced by
@org_tensorflow//tensorflow/compiler/xla/pjrt/distributed:protocol_proto_cc_impl'
TESTED=`bazel build --nobuild //...`
> Mark unanalyzable XLA target as manual

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/e2e/depth_conv_test.py
- integrations/tensorflow/e2e/dynamic_mlp_relu_test.py
- integrations/tensorflow/e2e/dynamic_mlp_test.py
- integrations/tensorflow/e2e/keras/lstm_static_test.py
- integrations/tensorflow/e2e/keras/lstm_test.py
- integrations/tensorflow/e2e/simple_stateful_test.py
The class names of the E2E modules are used to index into their benchmarking artifacts, so they need to be distinct. This is currently untested, and there was a collision between `depth_conv_test` and `conv_test` since they both used `Conv2dModule`. This fixes that and gives other modules more specific names as a stopgap.
Additional NFC: use `os.makedirs(exist_ok=True)` instead of `try`/`catch`.
> Standardize E2E module names.

- docs/design_docs/hal_driver_features.md
It mostly only covers Vulkan/SPIR-V target environment handling
at the moment.
> [doc] Add a doc for explaining HAL driver features

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/e2e/README.md
`Trace`s and `ModuleCall`s can be serialized to disk via a `serialize` method, and loaded via a static `load` method. These artifacts are saved under `.../ModuleName/backend_name/traces/trace_function/`.
> Adds python trace serialization and deserialization.

- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/compiler/Dialect/Flow/Transforms/test/hlo_to_hlo_preprocessing.mlir
- iree/compiler/Dialect/Flow/Transforms/test/hlo_to_hlo_preprocessing_extract_pad_from_conv.mlir
It's better to handle rewrites like this at the top layers instead of specializing codegen or runtime for it. 
This PR:
- Rewrite 1x1 convolutions as matrix-matrix multiplication.
- Add a flat to enable/disable the rewrite.
Not enabled by default because of #2882 
Bencmarking MobileNet V1 on VMLA (host)
iree-1x1-conv-to-dot = false
```
------------------------------------------------------------------------------
Benchmark                                    Time             CPU   Iterations
------------------------------------------------------------------------------
BM_RunModule/process_time/real_time       5956 ms         5956 ms            1
```
iree-1x1-conv-to-dot = true
```
------------------------------------------------------------------------------
Benchmark …
```
> Rewrites mhlo.conv -> mhlo.dot when convolution with 1x1x.. filters

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/e2e/BUILD
For each TF python test case, we are actually holding two contexts alive:
one in cls._tar_modules (via setUpClass()) and one in self._tar_modules
(via setUp()). The class one somehow is not properly released and
that causes issues with Vulkan driver DSO deallocation.
This commit changes to avoid using cls._tar_modules.
> Avoid creating duplicate VM contexts for TF Python tests

- iree/hal/cts/command_queue_test.cc
It's still timing out when using timeline semaphore emulation.
This reverts part of https://github.com/google/iree/pull/2902 and covers all platforms, unlike https://github.com/google/iree/pull/2908.
> Disable command_queue_test on Vulkan again.

- iree/compiler/Translation/IREEVM.cpp
Not covered by the build pipeline, as EmitC is not build by default.
> Add missing argument to translateFromMLIRToVM call

- iree/base/status_test.cc
Otherwise the test fails in optimized builds (or other builds which disable annotations).
I used macros instead of helper functions so we get line numbers for failed test checks.
> Update base:status_test to handle IREE_STATUS_FEATURE_ANNOTATIONS.

- iree/compiler/Conversion/CodegenUtils/MatmulCodegenStrategy.cpp
The current solution would not fold if the dimensions were no used by
ForOp or AffineMin. Add a fallback to try to optimize those cases.
> Improve AffineMinCanonicalization in MatmulCodegen strategy.

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
Follow-up to #2899. The global variables `_global_ref_module` and `_global_tar_modules` are used to store compiled IREE modules for the `TracedModuleTestCase`. Storing the variables on the `TracedModuleTestCase` `cls` causes the errors in #2900, and storing the variables on the `TracedModuleTestCase` instance (via `self`) doesn't work because `tf.test.TestCase` wipes these variables before each unittest.
This was tested by manually running an `x86-turing` presubmit, which [passed](https://source.cloud.google.com/results/invocations/53acf325-2a7a-4ed0-a607-1dfefec045c0/targets/iree%2Fgcp_ubuntu%2Fbazel%2Flinux%2Fx86-turing%2Fintegrations%2Fpresubmit/log).
> Avoid recompiling e2e modules with global variables

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/dot_general.mlir
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/test/e2e/vulkan_specific/dot_general.mlir
It is not trivial to handle general cases because transpose op and
reshape op will be inserted before and after the linalg.batch_matmul.
Therefore, only the trivial case is handled, which is formed as the
definition of linalg.batch_matmul in the tc file.
Hit an issue in LinalgTileAndFusePass on BatchMatmulOp. It seems to be
the same bug as pool/conv op, so handle it as the same way as pool/conv
op.
> Add support for trivial dot_general for vulkan-spirv backend.

- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
Only rewrites 1x1 conv -> when strides and dilation are 1. Otherwise its not a correct rewrite
> Only rewrite 1x1_conv -> dot only for unit strides & dilations

- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/FoldCompatibleDispatchRegions.cpp
Also group ops into one `isa<>` and sort them alphabetically.
> Make DotGeneral op live in their own dispatch function.

- build_tools/cmake/build_docs.sh
- scripts/update_e2e_coverage.py
There are some formatting differences between generating on Linux and generating on Windows, but this at least lets us run generation locally on Windows again for testing.
> Fix doc generation on Windows.

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/stream_ops.mlir
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/test/binaryop_test.mlir
- iree/compiler/Dialect/HAL/Target/LLVM/test/matmul_op.mlir
- iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.h
- iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/test/smoketest.mlir
- iree/compiler/Dialect/HAL/Transforms/MaterializeInterfaces.cpp
- iree/compiler/Dialect/HAL/Transforms/test/materialize_interfaces.mlir
The HAL transformation pass pipeline "materializes interfaces" then "translates executables" for each configured target ([source](https://github.com/google/iree/blob/d7f61a1510aeee066e34ebfadf13f7651aea4de4/iree/compiler/Dialect/HAL/Transforms/Passes.cpp#L46-L58)). As part of its executable translation, the VulkanSPIRV target "splits" dispatch functions using [SplitDispatchFunctionPass](https://github.com/google/iree/blob/d7f61a1510aeee066e34ebfadf13f7651aea4de4/iree/compiler/Conversion/LinalgToSPIRV/SplitDispatchFunctionPass.cpp), creating a schedule of `spv.EntryPoint` ops to dispatch in sequence when `recordDispatch()` is called ([source](https://github.com/google/iree/blob/d7f61a1510aeee066e34ebfadf13f7651aea4de4/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp#L321-L …
> Move hal.executable.entry_point ops into hal.executable.target.

- bindings/python/pyiree/rt/function_abi.cc
- bindings/python/pyiree/rt/system_api.py
- bindings/python/pyiree/rt/system_api_test.py
- bindings/python/pyiree/rt/vm_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
- integrations/tensorflow/e2e/README.md
Abseil flagfiles containing all of the data that `iree-benchmark-module` needs to run are generated for each `Trace` in our E2E tests. This allows for any module we test to be easily benchmarked on valid inputs. The process for benchmarking a vision model can thus be reduced to the following:
```shell
bazel test integrations/tensorflow/e2e/keras:vision_external_tests
bazel run iree/tools:iree-benchmark-module -- \
--flagfile=/tmp/iree/modules/ResNet50/cifar10/iree_vmla/traces/predict/flagfile 
bazel run iree/tools:iree-benchmark-module -- \
--flagfile=/tmp/iree/modules/ResNet50/cifar10/iree_llvmjit/traces/predict/flagfile 
```
Duplicate flags provided after the flagfile will take precedence. For example:
```shell
bazel run iree/tools:iree-benchmark-module -- \ …
```
> Add serialization for benchmarking e2e test modules with IREE

- iree/compiler/Conversion/HLOToLinalg/Passes.cpp
- iree/compiler/Conversion/HLOToLinalg/test/pipeline_test.mlir
Running fusion on tensor ops without folding unit extent dims can lead
to situations where the fused ops becomes illegal due to the bounds
computation failing. Remove the first fusion pass that runs before the
unit extents are canonicalized away.
Depends on LLVM patch : https://reviews.llvm.org/D85780
Closes #2882
> Remove the first FusionOfTensorOpsPass from HLO -> Linalg pipeline.

- experimental/ModelBuilder/ModelRunner.cpp
Bug found by Hanhan, when running with NDEBUG set we get an error
because Expected<> type is not checked before being used.
> [Model Runner] Fix error when using model runner with asserts off

- iree/base/api.h
> Removing usage of [[unlikely]].

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/linalg_tensor_to_buffer.mlir
Generalize the reshape handling in TensorToBuffer Pass to remove
restriction of tensor_reshape -> hal.interface.store.tensor is
converted to buffer only if the tensor_reshape has a single use.
Fixes #2882
> Handle multiple uses of a tensor_reshape before store.

- iree/compiler/Conversion/HLOToLinalg/BUILD
- iree/compiler/Conversion/HLOToLinalg/CMakeLists.txt
- iree/compiler/Conversion/HLOToLinalg/FusionOfTensorOps.cpp
- iree/compiler/Conversion/HLOToLinalg/Passes.cpp
- iree/compiler/Conversion/HLOToLinalg/Passes.h
- iree/compiler/Conversion/HLOToLinalg/test/fusion.mlir
- iree/compiler/Conversion/HLOToLinalg/test/pipeline_test.mlir
To reduce complexity of passes downstream, the linalg.tensor_reshape
operations can be fused with the hal.interface.load.tensor and
hal.interface.store.tensor operations. Add these patterns and the
patterns to fuse Linalg operations on tensors into a single pass.
> Fuse linalg.tensor_reshape operations with hal.interface* operations.

- iree/hal/vulkan/timepoint_util.cc
- iree/hal/vulkan/timepoint_util.h
This obviously is required to make sure that when later we acquire
the same TimePointFence, it's not in signaled state to start.
This bug is revealed by a non-deterministic crash on SwiftShader
where a command buffer can be destroyed in the middle of being
executed. This is because in IREE after queue submission we wait
on the TimePointSemaphore to signal to a specific value. Under
the hood, TimePointFence is used to query the status from GPU.
But it's always signaled and it causes IREE side to progress and
delete the command buffer (given it's already submitted and
executed seen by IREE). This triggers command buffer deletion
in SwiftShader, while it's still executing it.
> [vulkan] Reset TimePointFence status when releasing back to pool

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/__init__.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
Allows for low level usage of `pyiree` (e.g. in a colab notebook) without exposing the `SavedModel` roundtrip.
> Add function to hide SavedModel roundtrip

- build_tools/cmake/iree_copts.cmake
- iree/base/dynamic_library_test_library.cc
This addresses pages of pages of warnings on macOS like:
ld: warning: direct access in function 'foo' from file 'foo.file' to
global weak symbol 'bar' from file 'bar.file' means the weak symbol
cannot be overridden at runtime. This was likely caused by different
translation units being compiled with different visibility settings.
Besides, this has many benefits like avoiding symbol collision,
reducing library size, improving optimization, etc.
> Use hidden visibility for all symbols by default

- iree/compiler/Conversion/LinalgToSPIRV/SplitDispatchFunctionPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/split_dispatch_function.mlir
iree.placeholder can be interspeesed with other operations that are to
be split within SplitDispatchFunctionPass.
> Allow iree.placeholder as an op between splittable ops.

- iree/compiler/Conversion/HLOToHLO/DecomposeHLOClamp.cpp
- iree/compiler/Conversion/HLOToLinalg/FusionOfTensorOps.cpp
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/ResolveShapeOps.cpp
- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/VectorToGPUPass.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertFlowToHAL.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertHALToVM.cpp
- iree/compiler/Dialect/Shape/Conversion/ConvertShapeToShapex.cpp
- iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVMTest.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
This inserts the dialects required in conversion passes by overwriting `getDependentDialects()`.
Makes progress on #2958.
> Explicitly insert dialects in conversion passes

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/__init__.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_driver.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
Allows for specification of a `pass_pipeline` and `compiler_context`. Also moved the compiler context arg to the last position in the `tf.compiler` functions, since it is largely unused, and calls can be simplified when it can be omitted.
> Expand the tf_module_to_compiler_module API

- docs/get_started/getting_started_python.md
This link won't work on GitHub, but will on GitHub Pages. We have the same sort of half-broken link at [gh-pages/docs/developing_iree/index.md](https://github.com/google/iree/blob/gh-pages/docs/developing_iree/index.md).
Fixes https://github.com/google/iree/issues/2029
Fixes https://github.com/google/iree/issues/3014
> Fix hyperlink to getting started docs on python page.

- experimental/ModelBuilder/ModelBuilder.cpp
- experimental/ModelBuilder/test/BenchMatMulVectorGPU.cpp
Add fp16, and fp32 support in the matmul benchmark. Also prepare a fp32xfp32xfp32 mode that will not use cooperative matrix.
> Add more type support to model builder matmul benchmark.

- iree/hal/vulkan/extensibility_util.cc
- iree/hal/vulkan/extensibility_util.h
- iree/hal/vulkan/vulkan_device.cc
If we know that the extension is not available, avoid filling in
VkPhysicalDeviceTimelineSemaphoreFeatures and attach it to pNext
when creating the Vulkan device.
> [vulkan] Do not request timeline semaphore if not available

- iree/tools/test/simple.mlir
With #2904 and #2800, the issue on SwiftShader is resolved.
Fixes https://github.com/google/iree/issues/3007
> Enable simple.mlir test for iree-benchmark-module on vulkan

- iree/hal/vulkan/emulated_timeline_semaphore.h
Header and implementation file differ on parameter name.
> Fixed Emulator Timeline Semaphore parameter name

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/LinalgToLLVM/MatMulVectorization.cpp
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/VectorToGPUPass.cpp
- iree/compiler/Dialect/Flow/Transforms/IdentifyDispatchRegions.cpp
- iree/compiler/Dialect/Flow/Transforms/IdentifyDispatchRegions2.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertHALToVM.cpp
- iree/compiler/Dialect/HAL/Transforms/BUILD
- iree/compiler/Dialect/HAL/Transforms/CMakeLists.txt
- iree/compiler/Dialect/HAL/Transforms/InlineDeviceSwitches.cpp
- iree/compiler/Dialect/HAL/Transforms/MaterializeInterfaces.cpp
- iree/compiler/Dialect/Shape/Transforms/ConvertHLOToShapeDialectPass.cpp
- iree/compiler/Dialect/Shape/Transforms/FunctionSignatureExpansionPass.cpp
- iree/compiler/Dialect/Shape/Transforms/TieDynamicShapesPass.cpp
- iree/compiler/Dialect/VM/Transforms/Conversion.cpp
- iree/compiler/Dialect/VMLA/Conversion/VMLAToVM/ConvertVMLAToVM.cpp
- iree/compiler/Dialect/VMLA/Transforms/Conversion.cpp
- iree/compiler/Dialect/VMLA/Transforms/PreConversionLowering.cpp
Inserts dialects in transform and conversion passes to get rid of the
global dialect registration from MLIR usage. Makes progress on #2958.
> Explicitly insert dialects

- iree/compiler/Conversion/LinalgToSPIRV/CooperativeMatrixAnalysis.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_spirv.mlir
Make cooperative matrix analysis support cases where a cooperative matrix is passes to/returned by a scf.For operation.
> Improve cooperative matrix analyis to support cases with scf:ForOp

- experimental/ModelBuilder/test/BenchMatMulVectorGPU.cpp
Fix mattmul benchmark, the dimension were mapped backward.
> [ModelBuilder] Fix wrong dimension mapping for second level of tiling.

- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/test/e2e/xla_ops/dot_general.mlir
The distribution needs to be specified since the downstream passes do
not distribute loops anymore.
> Adding missing distribution options for BatchMatmul in tile+distribute

- experimental/ModelBuilder/test/BenchMatMulVectorGPU.cpp
- iree/compiler/Conversion/LinalgToSPIRV/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/CMakeLists.txt
- iree/compiler/Conversion/LinalgToSPIRV/Passes.h
- iree/compiler/Conversion/LinalgToSPIRV/VectorizeMemref.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/memref_vecrotization.mlir
- iree/compiler/Conversion/init_conversions.h
For memref accessed by vectortransfer op try to convert them to memref
of vector so that it can be accessed with vector load/store.
> Add pass to convert memref to memref of vector.

- iree/tools/CMakeLists.txt
Avoids a name conflict with the LLVMFileCheck lib introduced in
https://github.com/llvm/llvm-project/commit/5ffd940ac02a. AFAICT the
actual name here doesn't really matter. I decided to not give it the
LLVM prefix to avoid future conflicts.
Unbreaks the cmake build. The Bazel build is unbroken by
https://github.com/google/iree/commit/4e5f860d7822.
> Rename bundled LLVM FileCheck target

- iree/compiler/Conversion/LinalgToLLVM/MatMulVectorization.cpp
Add an option to enable L1 level tiling only which is useful for matrices with small reduction dimensions. 
This reduces the e2e runtime for MobileNetV2 by 3.2x.
```
BM_predict/process_time/real_time        329 ms          328 ms            2
```
```
BM_predict/process_time/real_time        101 ms          100 ms            6
```
> Add an option to only apply L1 level tiling for matmulOp

- scripts/check_tabs.sh
Otherwise the diff will list deleted files and then grep will fail
because the files don't exist, e.g.
https://github.com/google/iree/pull/3065/checks?check_run_id=1068022415
Tested:
Ran the script before (failing) and after (succeeding) on
https://github.com/google/iree/pull/3065, which deletes files.
> Filter out deleted files in tabs check

- iree/hal/vulkan/dynamic_symbol_tables.h
- iree/hal/vulkan/dynamic_symbols.cc
When querying dynamic symbols that are not attached to any Vulkan
instance, i.e., vkCreateInstance, vkEnumerateInstanceLayerProperties,
vkEnumerateInstanceExtensionProperties, and vkEnumerateInstanceVersion,
vkGetInstanceProcAddr are expecting a null instance as per the spec.
But at the moment we are trying to query these symbols with non-null
instance when DynamicSymbols::LoadFrom{Instance|Device}. The behavior
of that is not specified in the spec; and on certain Vulkan loaders/ICDs
(i.e., Android) they might not be supported well.
Also turned vkEnumerateInstanceVersion as optional given we are not
using it for anything at the moment.
> [vulkan] Avoid querying instanceless symbols with non-null instance

- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/test/identify_dispatch_regions2_hlo.mlir
This enforces broadcast to be cloned to their consumers  and prevents forming dispatch regions of only constant broadcast or regions with  broadcasted const outputs. 
Benchmark MobileNetV2 on Pixel4
Before:
```
BM_predict/process_time/real_time       93.2 ms         92.6 ms            8
```
After:
```
BM_predict/process_time/real_time …
```
> Mark mhlo.broadcast op as indexable to clone into its consumers.

- CMakeLists.txt
- build_tools/cmake/iree_cc_binary.cmake
- build_tools/cmake/iree_cc_library.cmake
- build_tools/cmake/iree_whole_archive_link.cmake
This commit extracts out as a function the functionality for going
through a target's direct library dependencies and recursively
linking ALWAYSLINK libraries as whole archive. It can be reused
for iree_cc_library so that wen we pack shared libraries we can
make sure ALWAYSLINK markers are respected and we have the necessary
global static objects for registering various functionalities.
This change is mostly NFC, except for exposing whole archive link
in iree_cc_library.
> [cmake] Extract whole archive link as a separate function

- CMakeLists.txt
- build_tools/cmake/iree_copts.cmake
- build_tools/cmake/iree_macros.cmake
- docs/get_started/cmake_options_and_variables.md
This is re-landing #2832 by cherry-picking the previous commit
d87ecb7c97ee5ca9d01054367a60c6631163780b and fix the issue with it.
So only need to review the second commit.
> [cmake] Add options for enabling Clang sanitizers

- iree/compiler/Dialect/HAL/Transforms/PublicAbiGeneration.cpp
- iree/samples/vulkan/vulkan_inference_gui.cc
The internals are still synchronous, but this at least shows that the ABI supports asynchronous calling behavior.
Only tested on Windows with native timeline semaphore support (NVIDIA).
Progress on https://github.com/google/iree/issues/1285
> Export async (timeline semaphore) ABI, call from Vulkan sample.

- iree/samples/vulkan/vulkan_inference_gui.cc
Follow-up to https://github.com/google/iree/pull/3089 . Tested with timeline semaphore emulation forced enabled, on Windows with native Vulkan support (NVIDIA).
> Use increasing semaphore signal values in Vulkan sample.

- iree/compiler/Dialect/HAL/Transforms/PublicAbiGeneration.cpp
- iree/compiler/Dialect/HAL/Transforms/test/public_abi_generation.mlir
This makes async the "default", with sync wrapping async, instead of the other way around. Now we can push semaphores down further into the compiler (e.g. to remove hal.ex.submit_and_wait).
Progress on https://github.com/google/iree/issues/1285
---
If the test is hard to read, here's a sample from simple.mlir's translation:
* Note how the `$sync` function creates a semaphore to pass into the `$async` function and waits for it to be incremented from `0` to `1` before returning. The `$async` function still waits and signals, but could instead pass the semaphores into the raw function for a `hal.submit`, removing the need for `hal.ex.submit_and_wait`.
Before:
```mlir
func @abs$sync(%arg0: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub, iree.module.export = "abs", …
```
> Refactor semaphore use in async and sync public ABI functions.

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/stream_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALOpFolders.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/test/command_buffer_folding.mlir
- iree/compiler/Dialect/HAL/IR/test/command_buffer_ops.mlir
- iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- iree/compiler/Dialect/HAL/Transforms/MaterializeResourceCaches.cpp
- iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- iree/compiler/Dialect/HAL/Transforms/ResolveEntryPointOrdinals.cpp
- iree/compiler/Dialect/HAL/Transforms/test/resolve_entry_point_ordinals.mlir
* `hal.device` can be retrieved from `hal.command_buffer`
* `hal.executable` can be retrieved from `@executable::@target::@entry_point` nested references
This adds a new `hal.command_buffer.device` op to help keep the IR tidy, with a new canonicalization pattern for when it refers to a device that was created in the same scope.
Since the new op is created within a `hal.device.switch`, the canonicalization is not used. However, since `MaterializeResourceCachesPass` does not yet support multiple devices, the lowerings still "work" as written today, without needing to add a runtime op for the device query.
Progress on https://github.com/google/iree/issues/1890
> Clean up HAL dispatch ops to not track redundant state.

- iree/compiler/Dialect/HAL/Target/LLVM/AOT/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/IR/LLVMIRTarget.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.h
- iree/compiler/Dialect/HAL/Target/VMLA/VMLATarget.cpp
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
Note: keeping these uses of `name()`:
https://github.com/google/iree/blob/45d971608fe91e119d7f9dbef5a0b6a1f9e0edd7/iree/compiler/Dialect/HAL/Target/TargetRegistry.cpp#L66-L68
https://github.com/google/iree/blob/45d971608fe91e119d7f9dbef5a0b6a1f9e0edd7/iree/compiler/Dialect/HAL/Transforms/LinkExecutables.cpp#L44-L47
> Split TargetBackend filter/name into two fields.

- iree/hal/cts/buffer_test.cc
- iree/hal/vulkan/vma_buffer.cc
MapMemory() already handles the offset. There is no need to
add the offset again when filling or copying.
> [vulkan] Fix VmaBuffer fill and copy

- iree/compiler/Conversion/LinalgToSPIRV/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/CMakeLists.txt
- iree/compiler/Conversion/LinalgToSPIRV/Passes.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Passes.h
- iree/compiler/Conversion/LinalgToVector/BUILD
- iree/compiler/Conversion/LinalgToVector/CMakeLists.txt
- iree/compiler/Conversion/LinalgToVector/LoadStoreVectorization.cpp
- iree/compiler/Conversion/LinalgToVector/Passes.h
- iree/compiler/Conversion/LinalgToVector/test/BUILD
- iree/compiler/Conversion/LinalgToVector/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToVector/test/vectorize_linalg_ops.mlir
- iree/compiler/Conversion/init_conversions.h
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- iree/test/e2e/vulkan_specific/BUILD
- iree/test/e2e/vulkan_specific/CMakeLists.txt
- iree/test/e2e/vulkan_specific/compare.mlir
- iree/test/e2e/vulkan_specific/log_plus_one.mlir
The convert op is the only one not covered, so we have an extra flag to
enable the pass. It needs an upstream fix in MLIR.
A Linalg generic op will be vectorized only if:
1) All the memory access is contiguous.
2) The shape of the last dim is a multiple of 4.
3) All the operands have only one use, which is the generic op.
This pass can also be extended to create large vectors. In the patch, it
only consider small vectors like 4xf32/4xi32.
> Add a pass to vectorize Linalg ops.

- iree/compiler/Dialect/HAL/Target/SPIRVCommon/SPIRVTarget.cpp
Parameter comments should match the name of the argument. See
http://clang.llvm.org/extra/clang-tidy/checks/bugprone-argument-comment.html
> Use local instead of parameter comment

- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertHLOToVMLA.cpp
- iree/compiler/Dialect/VMLA/Conversion/VMLAToVM/ConvertVMLAToVM.cpp
- iree/compiler/Dialect/VMLA/IR/VMLAOps.td
- iree/compiler/Dialect/VMLA/vmla.imports.mlir
- iree/hal/vmla/op_kernels.h
- iree/hal/vmla/op_kernels_generic.h
- iree/hal/vmla/vmla_module.cc
- iree/test/e2e/xla_ops/round.mlir
Adds a new vmla round operation mapping to mhlo's round operation.
> VMLA support for mhlo.round_nearest_nfz

- iree/vm/BUILD
- iree/vm/CMakeLists.txt
Follow up on https://github.com/google/iree/pull/3130
The test was fixed, but forgot to enable.
> Enable ASAN test on iree/vm:vm:native_module_test

- build_tools/cmake/iree_copts.cmake
Generally useful, and TF/MHLO now requires it for M_PI in a .td file.
> Set USE_MATH_DEFINES for Windows CMake builds.

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
This removes the unused functionality of creating a reinitialized copy of a `CompiledModule` it in favor of just reinitializing the module itself without copying.
> Replace `create_reinitialized` with `reinitialize` in tf_utils

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
I wrote the `RandomInitModule` with a `get()` function so that we can hopefully also use it to test TFLite.
> Fix `TfCompiledModule` reinitialization and test random initialization

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/README.md
- integrations/tensorflow/e2e/keras/BUILD
- scripts/update_e2e_coverage.py
This makes it very easy to benchmark IREE against TFLite, which will be elaborated in a future documentation update.
Our integrations tests no longer directly export `SavedModel`s, as the artifacts we need for benchmarking `TFLite` are saved under `/tmp/iree/modules/ModuleName/tflite/*.tflite`.
I also tested that `update_e2e_coverage.py` works with the added backend.
> Adds `TfLiteCompiledModule` and tests it in our integrations

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/matrix_ops_dynamic_test.py
- integrations/tensorflow/e2e/matrix_ops_static_test.py
This allows us to generate static matrix multiplication benchmarking artifacts for TFLite, LLVM JIT and Vulkan.
> Split `matrix_ops_test` into static and dynamic tests

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/concatenate.mlir
- iree/test/e2e/xla_ops/concatenate.mlir
This drops inefficient loops and can handle constants as input.
> Lower a mhlo.concatenate op to subview + linalg.fill/copy

- iree/compiler/Conversion/LinalgToVector/LoadStoreVectorization.cpp
The folder was added to upstream, we don't need to handle it specially.
> Remove special handling for vector.broadcast on constants.

- integrations/tensorflow/e2e/README.md
- Fixed broken Vulkan doc link
- Made `bazel` commands runnable
- Added spacing to example unittest
- Removed non-working `bazel` command examples
> Small improvements to E2E README

- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
Fixes https://github.com/google/iree/issues/1890 (except for Vulkan-SPIRV backend still using ordinal HAL dispatch ops due to how it splits dispatch ops)
> Switch flow.dispatch ops to use nested references to entry points.

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/BUILD
- integrations/tensorflow/e2e/BUILD
Allows running `bazel test integrations/...` in OSS without test failures.
> Tag OSS-failing 'nokokoro' targets as 'manual'

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/ConvImg2ColMatmulConversion.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/test/conv_img2col.mlir
- iree/test/e2e/llvmir_specific/BUILD
- iree/test/e2e/llvmir_specific/CMakeLists.txt
- iree/test/e2e/llvmir_specific/conv.mlir
Rewrites `linalg.conv -> linalg.generic + linalg.matmul` the `linalg.generic` packs input data into a layout `column-buffer` where the output of the convolution is just a matrix-matrix multiplication between this buffer and reshaped filter.
This is expected/planned to work for LLVM/CPU backends for now using stacked allocated buffer but will be generalized for Vulkan in future iterations.
>   Implement linalg.conv -> img2col packing + matmul rewrite

- iree/compiler/Conversion/LinalgToLLVM/ConvImg2ColMatmulConversion.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/conv_img2col.mlir
This fixes build break caused by #3216.
> Fix linalg::GenericOp constructor in img2col converter pattern

- colab/resnet.ipynb
- integrations/tensorflow/e2e/keras/vision_model_test.py
This addresses the following `tf.keras` warning:
```
`tf.keras.backend.set_learning_phase` is deprecated and will be 
removed after 2020-10-11. To update it, simply pass a True/False 
value to the `training` argument of the `__call__` method of your
layer or model.
```
> Remove `tf.keras.set_learning_phase` before it's deprecated

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
Adds a file `graph_path` to our `TfLiteCompiledModule` `Trace` serialization. This allows us to specify which TFLite-compiled module method the TFLite benchmark module should use when benchmarking a given trace.
```
/tmp/iree/modules/ModuleName
└── tflite
├── forward_pass.tflite
└── traces
└── predict
└── graph_path  # points to `/tmp/iree/modules/ModuleName/tflite/forward_pass.tflite`
```
The graph can be passed to `benchmark_model` like follows:
```shell
./third_party/tensorflow/bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model -- \
--graph="$(cat /tmp/iree/modules/ResNet50/cifar10/tflite/traces/predict/graph_path)"
```
Unfortunately we the use of `cat` here because `benchmark_module` does not support flagfiles.
> Add file pointing to correct tflite-graph for benchmarking

- iree/tools/BUILD
- iree/tools/CMakeLists.txt
- iree/tools/iree-benchmark-module-main.cc
- iree/tools/test/BUILD
- iree/tools/test/CMakeLists.txt
- iree/tools/test/benchmark_flags.txt
Benchmark and Absl fight. Right now, benchmark eats the `--help` flag
and so we lose all the help information for iree-benchmark-module.
This is not elegant, but it works and includes tests. A number of better
options are not available because both Absl and Benchmark bake behavior
into the only functions callable through their public API.
Fixes https://github.com/google/iree/issues/3247
> Fix help output for iree-benchmark-module

- docs/get_started/getting_started_android_cmake.md
Gives better error messages if the variables we expect are unset.
> Update Android doc to fail on undefined bash variable

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/README.md
- integrations/tensorflow/e2e/mobile_bert_squad_test.py
Open sources a test for MobileBert on the SQuAD task. 
Support for compiling `tf.Module`s with `tf.compat.v1.lite` was added to get TFLite to support compiling the model. The comparison `atol` is set to `1e0` because TFLite has a numerical difference of `~0.13` with TensorFlow on this model/input pair.
These tests don't run on the CI, so I tested them locally.
> Open source `mobile_bert_squad_test` with TFLite support

- integrations/tensorflow/e2e/gather_test.py
- iree/hal/vmla/op_kernels_generic.h
The code wasn't correctly iterating over batch dim. This PR explicitly split the outer most dim into (batch + parallel) and explicitly compute corresponding indices.
> Fix vmla::kernels::Gather::Execute handling of batching dims

- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertTensorOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/hal.imports.mlir
- iree/modules/hal/hal_module.cc
- iree/test/e2e/regression/trace_dispatch_tensors.mlir
Tested with command:
build/iree/tools/iree-run-mlir \
-iree-hal-target-backends=vmla \
-iree-flow-trace-dispatch-tensors \
-input-value="1x5xf32=1,-2,-3,4,-5" \
-input-value="1x5x3x1xf32=15,14,13,12,11,10,9,8,7,6,5,4,3,2,1"
iree/test/e2e/models/fullyconnected.mlir
The output looks like:
```
EXEC @main                                                                                                                                   === Input for main_ex_dispatch_0 ===
=== Input for main_ex_dispatch_0 ===
1x5x3x1xf32=...
=== Output for main_ex_dispatch_0 ===
5x3xf32=...
=== Input for main_ex_dispatch_1 ===
5x3xf32=...
3x5xf32=...
=== Output for main_ex_dispatch_1 ===
5x5xf32=...
...
```
> Add more information for each dump.

- integrations/tensorflow/e2e/BUILD
Enables `finite_test` on `iree_llvmjit` and `iree_vulkan` and `logical_ops_test` on `tflite`.
> Enable newly passing tests

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/__init__.py
- integrations/tensorflow/bindings/python/pyiree/tf/compiler/saved_model_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/compiler/signature_def_saved_model_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
This will make it easier to add support for multiple compilation paths to our TensorFlow integration tests.
List of changes:
- Rename `tf_load_saved_model` to `tf_saved_model_to_compiler_module`
- Rename `tf_load_signature_def_saved_model` to `tf_signature_def_saved_model_to_compiler_module`
- Rename `tf_compile_saved_model` to `compile_tf_saved_model`
- Add `compile_tf_signature_def_saved_model`
- Add `compile_tf_module`
- Rename `tf_utils.compile_tf_module` to `tf_utils._incrementally_compile_tf_module` and factor out `_incrementally_lower_compiler_module` and `_setup_mlir_crash_reproducer` for future code reuse.
- Remove support for compiling to multiple backends from `tf_utils`.
- This was unused and hacky because it didn't fit well into the artifact saving framework in …
> Refactor tf bindings compilation API

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/__init__.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/xla/compiler/__init__.py
- integrations/tensorflow/e2e/BUILD
Refactors `CompiledModule` and its subclasses to use the name constructors `create_from_class` and `create_from_instance`. This makes it easier to add additional compilation paths to our TensorFlow integration tests.
Additional changes:
- Clean up docstrings and make type info more accurate.
- Explicitly differentiate between `backend_name` and `backend_id`:
- `backend_name` is one of `[tf, tflite, iree_vmla, iree_llvmjit, iree_vulkan]`.
- `backend_id` uniquely identifies each instantiated backend at test time for the purpose of saving compilation artifacts.
- Use a `defaultdict` to match IREE's behavior of compiling all methods into one binary.
> Refactor 'CompiledModule' to use cls constructors

- _sass/custom/custom.scss
Changes the `max-width` of the `main-content` section of the page from `800px` to `860px` to accommodate for the added TFLite backend in the E2E ops coverage table.
Before:
After:
> Expand page width and padding for E2E coverage

- build_tools/bazel/run_binary_test.bzl
- docs/developing_iree/benchmarking.md
- docs/developing_iree/developer_overview.md
- docs/developing_iree/e2e_benchmarking.md
- docs/get_started/getting_started_android_cmake.md
- docs/get_started/getting_started_linux_vulkan.md
- docs/get_started/getting_started_windows_vulkan.md
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- iree/modules/check/iree-check-module-main.cc
- iree/testing/vulkan/iree-run-module-vulkan-gui-main.cc
- iree/tools/android/run_module_app/build_apk.sh
- iree/tools/iree-benchmark-module-main.cc
- iree/tools/iree-run-module-main.cc
- iree/tools/test/benchmark_flags.txt
- iree/tools/test/multiple_args.mlir
- iree/tools/test/repeated_return.mlir
- iree/tools/test/scalars.mlir
- iree/tools/test/simple.mlir
Fixes https://github.com/google/iree/issues/3248
> [NFC] Make flags more descriptive

- CMakeLists.txt
As a dependent project, these warnings are out of our direct control and are *very* spammy through MSVC.
Default behavior was changed (from implicit to explicit) with https://reviews.llvm.org/D87243.
Relates to https://github.com/google/iree/issues/3315
> Disable LLVM warnings when building with CMake.

- integrations/tensorflow/e2e/keras/BUILD
- integrations/tensorflow/e2e/keras/iree_vision_test_suite.bzl
- integrations/tensorflow/e2e/keras/vision_model_test.py
- scripts/update_e2e_coverage.py
Adds tests for the following models through `tf.keras.applications`:
- `DenseNet121`, `DenseNet169`, `DenseNet201`
- `InceptionResNetV2`, `InceptionV3`
- `NASNetLarge`, `NASNetMobile`
- `ResNet50V2`, `ResNet101`, `ResNet101V2`, `ResNet152`, `ResNet152V2`
- `VGG16`, `VGG19`
- `Xception`
Additional changes:
- `cifar10` and `imagenet` test suites are separated because `InceptionResNetV2`, `InceptionV3` and `Xception` do not support `cifar10` shapes.
- The `external_weights` macro keyword argument is renamed to `url` to match test flag.
- Added a `--use_external_weights` flag to make it clear whether or not external data is being used, and to allow testing `imagenet` shapes on random weights.
- The E2E coverage page only uses `imagenet` results because of the first point above and because …
> Expand keras vision model test coverage

- integrations/tensorflow/e2e/slim_vision_models/BUILD
- integrations/tensorflow/e2e/slim_vision_models/slim_vision_model_test.py
- scripts/update_e2e_coverage.py
- Enables all `mobilenet_v*` models, `nasnet_large` and `pnasnes_large`.
- Adds the ability to filter targets from out E2E coverage table. This is useful because slim vision has 37 versions of MobileNet that all pass on all backends, which isn't very interesting from a coverage standpoint. They all have different sizes however, so the targets could be useful for benchmarking a diverse set of input shapes and filter counts.
I left `amoebanet_a_n18_f448` in the build file because it may eventually be supported.
> Fix ill-configured slim vision model tests

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/BUILD
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/README.md
- integrations/tensorflow/e2e/iree_e2e_test_suite.bzl
- integrations/tensorflow/e2e/mobile_bert_squad_test.py
- scripts/update_e2e_coverage.py
Adds a named constructor `create_from_signature_def_saved_model` to compile and test SignatureDef SavedModels.
Also fixes #3258.
> Enable MobileBert on VMLA via SignatureDef SavedModels

- iree/tools/iree-benchmark-module-main.cc
Benchmarks invokes the registered functions multiple times (not only the benchmarking loop) resulting creating IREE driver, module...etc over and over. It also makes it impossible to use something like `simpleperf` with current LLVMAOT because traces will be scattered from different dylib executables.
> Benchmarking only iree_vm_invoke moving everything else outside registred function

- iree/tools/iree-benchmark-module-main.cc
Some resources (except context) were stored in local varialbe. Thus,
they were nil after returning from PrepareIREEVMFunction. Passing
the address instead (as context) to address the issue.
Also add a cleanup for inputs before resources are released.
> Fix resource preparation issue in iree-benchmark-module.

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Dialect/VM/Conversion/ImportUtils.h
- iree/compiler/Dialect/VMLA/Conversion/ConversionTarget.cpp
- iree/compiler/Dialect/VMLA/Conversion/ConversionTarget.h
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertConvOps.cpp
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertHLOToVMLA.cpp
- iree/compiler/Dialect/VMLA/Conversion/StandardToVMLA/BUILD
- iree/compiler/Dialect/VMLA/Conversion/StandardToVMLA/CMakeLists.txt
- iree/compiler/Dialect/VMLA/Conversion/StandardToVMLA/ConvertStandardToVMLA.cpp
- iree/compiler/Dialect/VMLA/IR/BUILD
These are currently shadowing the field in the base class that was
added in https://github.com/llvm/llvm-project/commit/8d67d187ba1b. 
These show up as clang-tidy warnings and are just generally not great.
This change doesn't fix all cases because I didn't have time to debug
issues I ran into changing some of the others, but at least moves us in
the right direction.
> Use existing ConversionPattern TypeConverter in some subclasses

- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/test/identify_dispatch_regions2_hlo.mlir
This will prevent cutting the IR in the middle between a reshape and its consumer or producer op that we isolate (e.g reshape + dot + reshape).
> Allow mhlo.reshape ops to exist within unfused ops region

- build_tools/docker/bazel-tensorflow/Dockerfile
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-swiftshader/integrations/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-turing/integrations/build_kokoro.sh
- integrations/tensorflow/bindings/python/pyiree/tf/compiler/BUILD
Adds a dependency to the `tensorflow/core:tensorflow_opensource` target, which contains the targets we need for SignatureDef SavedModels, MobileBERT and constant propagation. This will increase the build time of `//integrations/tensorflow/bindings/python/pyiree/tf/compiler`, and the run time of the swiftshader integrations kokoro job.
Adds `python2 -m pip install future` to `bazel-tensorflow`.
> Add dependency to :tensorflow_opensource in pyiree tf compiler

- scripts/prepare_doc_publication.py
Fixing this link, which was broken in #3339
> Fix short-term planning link in documentation ToC

- build_tools/docker/bazel-tensorflow/Dockerfile
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-swiftshader/integrations/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-turing/integrations/build_kokoro.sh
- integrations/tensorflow/bindings/python/pyiree/tf/compiler/BUILD
Reverts google/iree#3368
This broke the real GPU turing build.
```
$ docker run -it --rm --gpus all gcr.io/iree-oss/bazel-tensorflow-nvidia@sha256:995c0b3a392ed03c4530337dc14f7cc81660a024521abf1cfc2095fd6ef3f960
root@643cddba22b6:/# vulkaninfo
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /build/vulkan-tools-1.2.141.0~rc3/vulkaninfo/vulkaninfo.h:640:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
root@643cddba22b6:/# exit
```
> Revert "Add dependency to :tensorflow_opensource in pyiree tf compiler"

- iree/hal/metal/metal_direct_allocator.mm
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
This commit throws in a temporary workaround to enable a few
XLA MHLO end-to-end tests for the Metal HAL driver.
> [metal] Enable the initial batch of HLO op tests (7/n)

- iree/tools/iree-benchmark-module-main.cc
- iree/tools/test/BUILD
- iree/tools/test/CMakeLists.txt
- iree/tools/test/benchmark_flags.txt
- iree/tools/test/multiple_exported_functions.mlir
If the entry_function is set, the behavior is the same, ie, will
benchmark on the entry_function. Otherwise, will benchmark on all
exported functions which are expected to have no function inputs.
Fixes https://github.com/google/iree/issues/3388
> Add support for benchmarking all exported functions.

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/MarkerUtils.h
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_gpu.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/linalg_tile_and_fuse.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/workgroup_memory_promotion.mlir
- iree/compiler/Dialect/HAL/Target/SPIRVCommon/SPIRVTarget.cpp
This PR fixes the issues that were preventing conv/pool tile loop
distribution and lowering to loops from following the same approach as
matmul. With this PR the inter-tile loops can be eliminated and the
workitem loops can be converted to a simple `scf.if` reducing the
control flow overhead significantly. This also means that all the
tiling to workgroups patterns are now using the same pattern. These
can always be specialized later, but based on explicit needs.
This also means that the conv/pool operations also generate a function
to determine the number of workgroups to use during the launch,
cleaning up some of the fallback paths in the SPIRVTarget code.
Adding a test that was causing the correctness issues.
Closes #2134
> Reduce control flow overhead when tiling conv/pool ops.

- integrations/tensorflow/e2e/conv_test.py
- integrations/tensorflow/e2e/depth_conv_test.py
- integrations/tensorflow/e2e/gather_test.py
- integrations/tensorflow/e2e/logical_ops_test.py
- integrations/tensorflow/e2e/math_test.py
- integrations/tensorflow/e2e/matrix_ops_dynamic_test.py
- integrations/tensorflow/e2e/matrix_ops_static_test.py
- integrations/tensorflow/e2e/scatter_update_test.py
- integrations/tensorflow/e2e/tensorlist_test.py
Some of these tests were really hard to visually chunk because of a yapf heuristic that wraps nested functions with newlines. As far as I know there isn't a more fine-grained way to disable that heuristic. Thoughts?
> Add 'yapf: disable' to difficult-to-read tests

- iree/testing/vulkan/iree-run-module-vulkan-gui-main.cc
Using string literal can cause security issue, e.g., format string
attack. There are several options to leak memory, and a `%n` option to
overwrite memory.
> Use fmtstr instead of string::c_str().

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.h
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/MarkerUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/MarkerUtils.h
- iree/compiler/Conversion/LinalgToSPIRV/Passes.cpp
- iree/compiler/Conversion/LinalgToSPIRV/SplitDispatchFunctionPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/linalg_tile_and_fuse.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/split_dispatch_function.mlir
Use pattern to tile and fuse in IREE. Initial commit only fuses the
linalg.fill operation added in lowering to Linalg on buffers from MHLO
(HLOToLinalgOnBuffersPass) with the gemm/conv/pool operations. This
removes the need for splitting dispatch functions when multiple linalg
operations on buffers (SplitDispatchFunctionPass) exist in the
dispatch function.
> Add fusion on buffers to LinalgTileAndFuse Pass.

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/e2e/keras/vision_model_test.py
Tracks the specific comparison errors found during testing and propagates them to the `self.fail` statement so that it is easier to understand them without having access to the full logs.
Example message:
```
======================================================================
FAIL: test_predict (__main__.AppTest)
AppTest.test_predict
----------------------------------------------------------------------
Traceback (most recent call last):
File ".../integrations/tensorflow/e2e/keras/vision_model_test.py", line 158, in test_predict
self.compare_backends(predict, self._modules)
File .../integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 762, in compare_backends
self.fail(
File "/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/lib/python3.8/site-packages …
```
> Propagate comparison errors into e2e test failures

- CMakeLists.txt
- build_tools/cmake/iree_cc_binary.cmake
- build_tools/cmake/iree_cross_compile.cmake
- build_tools/embed_data/CMakeLists.txt
Fixes https://github.com/google/iree/issues/3457
* CMake targets shouldn't have executable suffixes (e.g. `.exe`) in them and `flatcc_cli.exe` was getting copied to `flatcc_cli` (dropping the extension where it matters).
* `iree_get_build_command` should take a target name, not an executable name (alias).
The generated commands are of the format:
```
C:/Program Files/CMake/bin/cmake.exe;--build;D:/dev/projects/iree-build-android/host;--target;iree-tblgen;-- config;$<CONFIG>
```
Where `--target iree-tblgen` can't find the target on my system, but `--target iree_tools_iree-tblgen` can.
I tried using `get_target_property(... ALIASED_TARGET)` but I get this error:
`get_target_property() called with non-existent target "iree-translate"`
> Fix CMake Android cross-compilation on Windows.

- iree/base/threading.c
Fixes builds on old MSVC versions (like mine).
> Use IREE_RESTRICT macro instead of regular `restrict` keyword.

- scripts/utils.py
You can't use `process.wait()` with pipes.
Fixes https://github.com/google/iree/issues/3499
> Avoid deadlock in get_e2e_artifacts

- iree/compiler/Translation/IREEVM.cpp
Just found this typo when revising options for exporting dispatch functions. :)
> [NFC] Fix error message in convertToHALModule

- iree/modules/hal/hal_module.cc
The tracing ops are expected to use for debugging. In this context,
setting default number of elements to dump larger is better.
> Make BufferViewTrace dump as many values as possible.

- integrations/tensorflow/e2e/BUILD
The patch in MLIR was landed on OSS side, so the test can be enabled. There is a numerical issue in vulkan, file #3507 to track it.
> Enable MobileBert test on llvmjit.

- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
The tile only pattern should not apply when there are dependent linalg
operations. The TileAndFuse should apply for those. Add this missing
condition.
> Add missing condition for aborting from Tile only pattern.

- build_tools/bazel/iree.bazelrc
- iree/base/BUILD
- iree/build_defs.oss.bzl
Reducing the number of these warnings:
```
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
```
---
Our tests using `googlemock` have compilation errors with `/experimental:preprocessor`:
```
ERROR: D:/dev/projects/iree/iree/hal/BUILD:103:8: C++ compilation of rule '//iree/hal:buffer_test' failed (Exit 2) C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winbase.h(9305): warning C5105: macro expansion producing 'defined' has undefined behavior
iree/hal/buffer_mapping_test.cc(55): error C4002: too many arguments for function-like macro invocation 'GMOCK_PP_INTERNAL_TAIL_CAT_I'
external/com_google_googletest/googlemock/include\gmock/internal/gmock-pp.h(64): note: in expansion of macro 'GMOCK_PP_TAIL' …
```
> Clean up and fix some Bazel flags on Windows.

- CMakeLists.txt
- docs/get_started/getting_started_android_cmake.md
The library needs to be linked statically, and `DyLIB` needs to be added
to `IREE_HAL_DRIVERS_TO_BUILD`.
> Update AOT doc and CMakeLists.txt on Android

- build_tools/bazel/run_binary_test.bzl
This avoids a bash requirement and an unnecessary copy. I'm not sure
why I originally thought a copy was necessary, but builds seem to pass.
Also changed the attr options to specify that `test_binary` should be
executable.
> Use a symlink instead of a copy for run_binary_test

- iree/hal/vulkan/BUILD
- iree/hal/vulkan/CMakeLists.txt
- iree/hal/vulkan/vulkan_driver.cc
Per the spec, VkApplicationInfo::apiVersion "must be the highest
version of Vulkan that the application is designed to use."
Targeting Vulkan 1.0 means we cannot use Vulkan 1.1/1.2 features.
This isn't strongly enforced on all Vulkan loaders/ICDs but I do
see issues raised due to this on, for example, Linux Mesa drivers.
> [vulkan] Bump target Vulkan API version

- iree/test/e2e/models/bert_encoder_unrolled_fake_weights.mlir
Makes it more representative of the real weights model.
> Adding noinline (and sym_visibility=private) to bert w/ fake weights.

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/__init__.py
- integrations/tensorflow/compiler/BUILD
- integrations/tensorflow/compiler/LegalizeTF.cpp
- integrations/tensorflow/compiler/test/legalize-tf.mlir
- integrations/tensorflow/e2e/BUILD
Without Tensorflow folders we were not able to progressively lower TF to XLA in cases where constant evaluation is required (e.g. constant axis for tf.Concatenate). Including all TF folders is not an option due to kernel build times, so by creating a custom legalize-tf pass for XLA that includes the XLA folders and alternates folding/lowering, we can legalize these cases without the TF folders.
Includes re-enabling linspace for VMLA.
> Added a TF2XLA Lowering that includes XLA folders

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Passes.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Passes.h
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_spirv.mlir
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- iree/test/e2e/vulkan_specific/BUILD
- iree/test/e2e/vulkan_specific/CMakeLists.txt
- iree/test/e2e/vulkan_specific/compare.mlir
- iree/test/e2e/vulkan_specific/log_plus_one.mlir
This reverts commit 0fa16645176b40fded1a61d99f07a9b9bd9349b5.
Causes some internal model failures. Reverting according to @MaheshRavishankar request.
> Revert "Add LoadStoreVectorizationPass to GPU pipeline as default (#3194)"

- integrations/tensorflow/compiler/BUILD
- integrations/tensorflow/compiler/CheckNoTF.cpp
- integrations/tensorflow/compiler/Passes.cpp
- integrations/tensorflow/compiler/Passes.h
- integrations/tensorflow/compiler/test/check-no-tf.mlir
- integrations/tensorflow/compiler/test/saved_model_adopt_exports.py
Added a pass that verifies that all TF has been lowered away. This guarantees
we terminate early when a TF operation should no longer exist.
> Added a pass to validate TF has been lowered away

- docs/developing_iree/contributor_tips.md
- docs/developing_iree/developer_overview.md
- docs/developing_iree/e2e_benchmarking.md
- docs/developing_iree/profiling.md
- docs/developing_iree/repository_management.md
- docs/get_started/getting_started_android_cmake.md
- docs/get_started/getting_started_linux_bazel.md
- docs/get_started/getting_started_linux_cmake.md
- docs/get_started/getting_started_linux_vulkan.md
- docs/get_started/getting_started_macos_bazel.md
- docs/get_started/getting_started_macos_cmake.md
- docs/get_started/getting_started_windows_cmake.md
- docs/get_started/getting_started_windows_vulkan.md
- docs/using_iree/using_colab.md
* recommend an out-of-tree CMake build directory `../iree-build/` instead of in-tree `build/`
* consistently use `.vmfb` as VM module flatbuffer file extensions
* make some docs use CMake examples instead of Bazel examples
* prefix all shell commands with `$`
* indent shell commands two spaces when continuing onto multiple lines
* consistently use `-` for LLVM flags and `--` for Abseil flags
* typo fixes
> Standardization pass through docs/ folder. 

- iree/compiler/Conversion/CodegenUtils/BUILD
- iree/compiler/Conversion/CodegenUtils/CMakeLists.txt
- iree/compiler/Conversion/CodegenUtils/ForOpCanonicalization.cpp
- iree/compiler/Conversion/CodegenUtils/ForOpCanonicalization.h
- iree/compiler/Conversion/LinalgToSPIRV/test/forop_canonicalization.mlir
- iree/compiler/Conversion/init_conversions.h
This is an ad hoc pass to clean up some unnecessary operations added
during progressing lowering. MLIR canonicalization currently cannot
clean it up, this is a temporary solution to allow those to be removed
on IREE side.
> Add a pass to canonicalize ops used as loop carried values by scf.for

- iree/test/e2e/models/resnet_fake_weights.mlir
We already have test coverage for this model architecture through [integrations/tensorflow/e2e/keras/vision_model_test.py](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/keras/vision_model_test.py), but this `.mlir` file is easier to inspect and work with when using CMake.
Generated by
1) Running resnet Colab notebook (https://github.com/google/iree/pull/3628) with an output `ARTIFACTS_DIR` (could also run the vision_model_test)
2) Using the `-iree-flow-strip-and-splat-constant-variables` pass from https://github.com/google/iree/pull/3629:
```
λ .\iree\tools\iree-opt.exe -iree-flow-strip-and-splat-constant-variables D:\dev\projects\iree-data\modules\ResNet/iree_input.mlir > %CD%/../iree-tmp/resnet_splats.mlir
```
3) Manually adding `RUN` and `CHECK` lines
> Add resnet_fake_weights.mlir test file.

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/StripAndSplatConstantVariables.cpp
- iree/compiler/Dialect/Flow/Transforms/test/strip_and_splat_constant_variables.mlir
- iree/test/e2e/models/mnist_fake_weights.mlir
This can be used to process large model files down to a reasonable size for check-in as tests or other in-tree examples for compilation.
A heuristic is used to set the replacement values hoping to avoid NaNs/INFs. We could add flags to give some control over that (some models are fine with all `0`, `0.5`, or `1` values, while others are more sensitive).
We can add similar passes for inserting certain `check` ops, converting inputs into constants (https://github.com/google/iree/pull/3624), and other steps that we've previously performed manually.
> Add a development pass for replacing flow.variables with splats.

- build_tools/third_party/swiftshader/build_vk_swiftshader.sh
I incorrectly assumed that `2>/dev/null` in `CYGPATH="$(which cygpath 2>/dev/null)"` dealt with the case that `cygpath` was not found.
> Fixup for #3634

- bindings/python/build_defs.oss.bzl
- build_tools/bazel/iree.bazelrc
- iree/base/BUILD
- Add `windows_enable_symlinks` and use non-experimental
`enable_runfiles`
- Tag targets that don't build on windows
- remove `host_copt` which is unnecessary with
`distinct_host_configuration=false` (side note, I'm skeptical of that
setting).
- select away some more unsupported linkopts
> Cleanup more log spam in Windows Bazel Config

- iree/compiler/Conversion/CodegenUtils/MatmulCodegenStrategy.cpp
MLIR APIs changed and this was merged after being tested based on an
older commit. Not much we could do differently here other than always
testing the merge commit instead of the head commit, but that comes
with its own set of issues.
> Unbreak usage of applyPatternsAndFoldGreedily

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Passes.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/matmul_vectorization.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/pipeline_test.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/pipeline_test_cooperative_mat.mlir
Add launch strategy for Mali GPU and a set of new transformation needed
and specify a good tile and workgroup size to use based on experiment.
Also enable hoisting of transfer_ops for the vector path.
> Add strategy for Mali GPU in vectorization path and enable hoisting

- .github/workflows/update_llvm_dependent_submodules.yml
- scripts/git/update_to_llvm_syncpoint.py
We need the tags to find the matching LLVM commit and in some git
configurations (e.g. in the GitHub actions) they won't be fetched by
default. This fixes the
[Synchronize LLVM Dependents workflow](https://github.com/google/iree/actions?query=workflow%3A%22Synchronize+LLVM+Dependents%22)
which has been broken for a bit in the case where it actually needs to
fetch a new version of llvm-bazel.
Tested:
Pushed to my fork
https://github.com/GMNGeoffrey/iree/runs/1334664578 created
https://github.com/GMNGeoffrey/iree/pull/60
> Explicitly fetch tags for llvm-bazel

- scripts/android-tracy-runnable-tutorial.sh
- scripts/android_tracy_tutorial.sh
Draft, comments welcome.
The idea is that a beginner would run it a few times, then it'd be
mostly useful as a tutorial to read steps from, not intended to be used
long term as a black box tool.
Just try running it (on a Debian linux desktop, with and Android device attached by ADB). It'll complain a bit that you need to define
environment variables IREE_ROOT and ANDROID_NDK, and once you do that,
it should figure all the rest, including building tracy UI, going
through the whole steps of compiling an android benchmark workload,
running that in tracy, setting up port forwarding, and finally telling
you to run a command to run your (newly built) tracy UI to connect
and show the trace.
> Add an "executable tutorial" going from zero to tracy on android

- build_tools/cmake/iree_cross_compile.cmake
This makes it so that these variables (which control sanitizers, use of
ccache, and cmake verbosity) apply also to the host build, not just to
the target build.
> Forward some more CMake variables to host builds.

- CMakeLists.txt
- build_tools/cmake/iree_copts.cmake
- build_tools/cmake/sanitizers.cmake
My concern with putting it only on IREE code and not say on LLVM code
is that we might end up getting inconsistent results, particularly
with symbols used in both IREE and non-IREE code --- ODR violations,
concern here is both with the undefined-behavior aspect of that and
with the more down to earch concern that we want consistent sanitizer
behavior in say std::string code that might be used on both sides.
> Put sanitizer flags in global CMake variables, affecting all code

- CMakeLists.txt
If enabled, this will try to detect ccache, and if found, CMake will
be told to use it. No-op if ccache is not found.
> Add a IREE_ENABLE_CCACHE build option. OFF by default.

- build_tools/bazel/iree.bazelrc
Some warnings still show up because they are from the host build.
> Silence remaining host-only warnings in Bazel build

- iree/compiler/Conversion/LinalgToSPIRV/test/split_dispatch_function.mlir
- iree/compiler/Dialect/Flow/Analysis/test/dispatchability.mlir
- iree/compiler/Dialect/Flow/IR/test/dispatch_regions.mlir
- iree/compiler/Dialect/Flow/IR/test/variable_ops.mlir
- iree/compiler/Dialect/Flow/Transforms/test/outline_dispatch_regions_ranked_dynamic.mlir
- iree/compiler/Dialect/HAL/IR/test/allocator_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/attributes.mlir
- iree/compiler/Dialect/HAL/IR/test/buffer_folding.mlir
- iree/compiler/Dialect/HAL/IR/test/buffer_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/buffer_view_folding.mlir
- iree/compiler/Dialect/HAL/IR/test/buffer_view_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/command_buffer_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/device_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/executable_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/experimental_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/variable_ops.mlir
- iree/compiler/Dialect/HAL/Transforms/test/inline_device_switches.mlir
- iree/compiler/Dialect/HAL/Transforms/test/resolve_entry_point_ordinals.mlir
- iree/compiler/Dialect/Shape/Transforms/test/expand_function_dynamic_dims.mlir
- iree/compiler/Dialect/Shape/Transforms/test/hoist_shape_calculations.mlir
- iree/compiler/Dialect/Shape/Transforms/test/materialize_shape_calculations.mlir
- iree/compiler/Dialect/VM/IR/test/assignment_ops.mlir
- iree/compiler/Dialect/VM/Transforms/test/sink_defining_ops.mlir
- iree/compiler/Dialect/Vulkan/IR/test/target_env.mlir
- iree/tools/iree-opt-main.cc
This dramatically simplifies iree-opt-main.cc
The only functional difference is inverting the default of
`allow-unregistered-dialect` to match `mlir-opt`, which seems like a
good change.
> Use simpler MlirOptMain in iree-opt

- docs/get_started/getting_started_macos_cmake.md
make the build path consistent
> fix a trivial problem in macos guide

- iree/test/e2e/regression/executable_benchmark.mlir
- iree/tools/iree-benchmark-module-main.cc
- iree/tools/test/benchmark_flags.txt
- iree/tools/test/multiple_args.mlir
- iree/tools/test/multiple_exported_functions.mlir
- iree/tools/test/repeated_return.mlir
- iree/tools/test/scalars.mlir
- iree/tools/test/simple.mlir
Now that we dynamically register benchmarks we don't need to worry about
the input getting loaded multiple times by the benchmark framework, so
we can support stdin.
Did a little bit of test cleanup while I was in there.
> Add support for stdin to iree-benchmark-module

- integrations/tensorflow/e2e/keras/keyword_spotting_streaming_test.py
Also generalizes the input shape specification to allow external streaming to be easily enabled after a keras bug is fixed.
> Simplify model initialization for kws streaming tests

- scripts/git/update_to_llvm_syncpoint.py
llvm-bazel does not guarantee that flag refs will be stable, so we need
to use `--force` to update them.
> Force fetch tags from llvm-bazel

- integrations/tensorflow/e2e/slim_vision_models/BUILD
This only affects the tests when they run internally.
> Add missing dependency on tensorflow_hub to slim_vision_tests

- integrations/tensorflow/e2e/keras/BUILD
- integrations/tensorflow/e2e/keras/keyword_spotting_streaming_test.py
A tensorflow bug prevents us from running these tests, but this will make it trivial to enable them once that bug is fixed, and allows me to monitor that by running the failing tests.
> Add (disabled) tests of KWS external streaming.

- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/FoldCompatibleDispatchRegions.cpp
After moving the op to tensors world, the ops can be fused with their
consumer. The patch also allows the ops to live with their producers in
the same dispatch function. This does not break any models. Go through
some models and lowering from TF, the input of the ops usually are from
constant or model input, which becomes a buffer in IREE.
Fixes https://github.com/google/iree/issues/3562
> Relax TorchIndexSelectOp to fuse with other ops.

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.h
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Utils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Utils.h
- iree/compiler/Conversion/LinalgToSPIRV/test/matmul_vectorization.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/workgroup_memory_promotion.mlir
Propogate tile sizes to use on root operation to all dependent
operations. This enables each operation can be tiled the same way if
needed.
Also modifies the allocation/deallocation callbacks to allocate
workgroup memory at the entry of the function and not explicitly
deallocate it. This better matches semantics of workgroup memory and
also avoid complications arising from having to hoist the allocation.
Depends on patch : https://reviews.llvm.org/D90582
> Miscellaneous fixes to address issues seen with vectorization.

- integrations/tensorflow/e2e/keras/keyword_spotting_streaming_test.py
- scripts/get_e2e_artifacts.py
Also adds the kws_streaming test suites to `get_e2e_artifacts.py`.
Directory structure:
```
/tmp/iree/modules/keyword_spotting
├── att_mh_rnn
│   ├── external_streaming
│   ├── internal_streaming
│   └── non_streaming
├── att_rnn
│   ├── external_streaming
│   ├── internal_streaming
│   └── non_streaming
├── cnn
│   ├── external_streaming
│   ├── internal_streaming
│   └── non_streaming
.
.
.
└── xception
├── external_streaming
├── internal_streaming
└── non_streaming
```
> Add directory structure for kws streaming artifacts.

- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/FoldCompatibleDispatchRegions.cpp
Reverts google/iree#3682
This breaks internal tests.
> Revert "Relax TorchIndexSelectOp to fuse with other ops."

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/matmul_fused_vectorization.mlir
This allow to generate efficient code when FillOp is tiled with an op
getting vectorized like MatMulOp.
> Add LinalgOp vectorization in TileAndFuse pass for SPIR-V

- iree/tools/iree-translate-main.cc
There are a couple of investigation TODOs in here that stem from
iree-translate differing from mlir-translate. They are not feasible
without reworking the tool. Instead I added additional documenation on
the differences for future readers and deleted the TODOs.
We could still reconsider the expanded role of iree-translate and reduce
it to a tool more akin to mlir-translate, creating a separate
iree-compiler tool to run full compilation passes without taking
translations to perform as command line flags. But that's larger in
scope than these TODOs.
Closes https://github.com/google/iree/issues//2958
> Clarify behavior of iree-translate

- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertHALToVM.cpp
- iree/compiler/Dialect/HAL/Transforms/IdentifyConstantPools.cpp
- iree/compiler/Dialect/HAL/Transforms/LinkExecutables.cpp
- iree/compiler/Dialect/HAL/Transforms/MaterializeInterfaces.cpp
- iree/compiler/Dialect/HAL/Transforms/MaterializeResourceCaches.cpp
- iree/compiler/Dialect/HAL/Transforms/SerializeExecutables.cpp
- iree/compiler/Dialect/HAL/Transforms/TranslateExecutables.cpp
- iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
- iree/compiler/Dialect/VM/Conversion/TypeConverter.h
- iree/compiler/Dialect/VM/Transforms/Conversion.cpp
- iree/compiler/Dialect/VMLA/Conversion/VMLAToVM/ConvertVMLAToVM.cpp
This commit moves command-line option interaction into pass
registration and makes passes themselves cleaner.
> Avoid reading command-line flags in various VM related passes

- build_tools/bazel/deep_copy.bzl
- integrations/tensorflow/e2e/iree_e2e_cartesian_product_test_suite.bzl
Previously if one tried to reuse the failing configurations from another
test suite it would behave unexpectedly due to variable mutation.
> Add 'deep_copy' to bazel to allow variable reuse

- iree/compiler/Conversion/LinalgToSPIRV/Passes.cpp
This fixes crashes when running the whole pipeline because of pass
manager target op mismatch.
> [spirv] Use addNestedPass<FuncOp>() for passes working on functions

- scripts/prepare_doc_publication.py
- scripts/update_e2e_coverage.py
The "[Tensorflow End to End Coverage](https://google.github.io/iree/tf-e2e-coverage)" page has grown quite a bit over the past few months, and #3753 exasperated that significantly. This change splits the TensorFlow coverage into four groups:
- TensorFlow Base APIs
- TensorFlow Keras Layers
- Language and Speech Models
- Vision Models
and stores them under a parent page like "Getting Started".
The "tensorflow" column is also removed from the table to reduce visual clutter, as it passes by definition.
Depends on #3759.
> Separate tensorflow coverage into multiple pages

- scripts/update_e2e_coverage.py
Accidently added a comma in a string concatenation block. This comma will cause the documentation publication to fail.
> Remove comma in string concatenation

- iree/hal/vulkan/CMakeLists.txt
- iree/hal/vulkan/internal_vk_mem_alloc.cc
Sample logs with warning spam: https://source.cloud.google.com/results/invocations/e8a4e187-8f85-4ef2-af9f-de137633ee23/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fmain/log
There are still some warnings from `Wthread-safety-analysis`, but they are much less spammy (see [new logs](https://source.cloud.google.com/results/invocations/16651c8d-151a-400d-8826-b87a47a52932/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fpresubmit/log)). Refactoring (like setting up a dedicated CMakeLists.txt for VMA) could help there.
> Silence some CMake/Linux warnings in VMA.

- WORKSPACE
- build_tools/docker/bazel-tensorflow-nvidia/Dockerfile
- build_tools/docker/bazel-tensorflow-vulkan/Dockerfile
- build_tools/docker/cmake-python-nvidia/Dockerfile
- build_tools/docker/cmake-python-vulkan/Dockerfile
- build_tools/docker/manage_images.py
- build_tools/docker/rbe-toolchain/Dockerfile
- build_tools/docker/vulkan/Dockerfile
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-swiftshader/bindings/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-swiftshader/core/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-swiftshader/integrations/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/bazel/linux/x86-turing/integrations/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/android/arm64-v8a/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build_kokoro.sh
This commit changes to download the Vulkan SDK tarball instead of
installing it from APT repo so that we can still get it for the
RBE toolchain. LunarG APT repo dropped support for Ubuntu 16.04
for recent SDK versions.
This commit also creates a base Vulkan SDK image so that other
docker images can copy the SDK from it.
Trimmed down to only install Vulkan components for NVIDIA.
The NVIDIA Vulkan ICD is pinned down to a very specific version
to match what's used in the VM image and for future-proofness.
Fixes https://github.com/google/iree/issues/3550
> Update Vulkan SDK within CI docker images

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/e2e/batch_norm_test.py
- integrations/tensorflow/e2e/keras/BUILD
- integrations/tensorflow/e2e/keras/layers/BUILD
- integrations/tensorflow/e2e/slim_vision_models/BUILD
Our input generation was only using positive numbers, which left a blind spot in our testing.
Thankfully this only affects a few targets:
- `NASNetLarge` on `iree_vmla` (for both `keras` and `slim` tests)
- `NASNetMobile` on `iree_vmla` (for both `keras` and `slim` tests)
- `MaxPoolXD` on `iree_llvmjit` (in the new keras layers tests)
I also added `equal_nan` to `np.allclose` and `np.array_equal` since we want to have identical behavior to tensorflow there as well. This required updating the `bazel-*`docker images to upgrade `numpy`.
_Note: After the tests pass on the CI, I will update the `:prod` tag and the digests to match._
> Test negative numbers in our e2e tests

- iree/compiler/Conversion/LinalgToSPIRV/test/workgroup_memory_promotion.mlir
- iree/compiler/Dialect/Flow/IR/test/variable_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/constant_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/variable_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/variable_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/variable_ops.mlir
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/control_flow_ops.mlir
- iree/compiler/Dialect/VM/Transforms/test/mark_public_symbols_exported.mlir
This is in prep for proposed MLIR change to disallow this. See
https://llvm.discourse.group/t/rfc-symbol-definition-declaration-x-visibility-checks/2140
> Update tests to eliminate public function declarations.

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
We will need all the information the target environment for
deducing op launch configuration. This avoids each op to
query it again from the IR.
> [spirv] Pass spirv::TargetEnv to OpLaunchConfig functions

- iree/compiler/Dialect/Flow/Transforms/DeduplicateExecutables.cpp
Bug in https://github.com/google/iree/pull/3702 caught by ClangTidy.
> Fix return during loop in executable deduping.

- experimental/ModelBuilder/ModelBuilder.cpp
- experimental/ModelBuilder/VulkanWrapperPass.cpp
This is in prep for a proposed MLIR change to disallow public
declarations. See
https://llvm.discourse.group/t/rfc-symbol-definition-declaration-x-visibility-checks/2140
> Update ModelBuilder to mark function declarations private.

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/math_dyn_test.py
- iree/compiler/Dialect/Shape/IR/Folders.cpp
- iree/compiler/Dialect/Shape/Plugins/XLA/XlaHloShapeBuilder.cpp
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertHLOToVMLA.cpp
Added direct lowering from HLO to VMLA with shape dialect additions. Includes
an additional canonicalizer to bypass index cast. Includes a dynamic version of
math_test for verifying dynamic support.
> Address dynamic shape issue for ceil

- .github/workflows/synchronize_submodules.yml
Issues and solution detailed in the links below.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
> Fix submodule action by changing how environment variables are set

- iree/base/wait_handle.h
Fixes these errors: https://source.cloud.google.com/results/invocations/f1a13a65-8f08-4f9e-9bfc-747e190f82f7/targets/iree%2Fgcp_ubuntu%2Fcmake%2Fandroid%2Farm64-v8a%2Fmain/log
```
FAILED: iree/base/CMakeFiles/iree_base_wait_handle.dir/wait_handle_posix.c.o
/usr/src/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android29 --gcc-toolchain=/usr/src/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/usr/src/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DABSL_FLAGS_STRIP_NAMES=0 -I../third_party/abseil-cpp -isystem ../ -isystem . -isystem ../third_party/llvm-project/llvm/include -isystem third_party/llvm-project/llvm/include -isystem ../third_party/llvm-project/mlir/include -isystem …
```
> Disable WAIT_TYPE_SYNC_FILE until include issues on CI are resolved.

- iree/base/wait_handle.h
- iree/base/wait_handle_posix.c
Following https://github.com/google/iree/pull/3884 now that I have Android building locally.
> Fix-forward sync.h include on Android.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/slice.mlir
- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.h
- iree/compiler/Dialect/Flow/Transforms/FoldCompatibleDispatchRegions.cpp
- iree/compiler/Dialect/Flow/Transforms/test/fold_compatible_dispatch_regions.mlir
- iree/test/e2e/regression/slice_add.mlir
- Move mergable checks to DispatchConfig.
- Add a new trait for root only ops.
- Add slice + add tests.
> Relax SliceOp to being able to be a root op.

- integrations/tensorflow/e2e/math/BUILD
These tests were added after https://github.com/google/iree/commit/4e47a49bb3ab7babe00e90b5f4caefa26aff8320 and weren't disabled by [this workaround](https://github.com/google/iree/commit/4e47a49bb3ab7babe00e90b5f4caefa26aff8320#diff-b5c02b6f6cb05d26b20ce205afa4ff98861d4347fa7755577d49d061ed595943R22).
> Disable added llvmjit tests with github issue

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/reduce_test.py
- iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertReductionOps.cpp
- iree/compiler/Dialect/VMLA/Conversion/VMLAToVM/ConvertVMLAToVM.cpp
- iree/compiler/Dialect/VMLA/IR/VMLAOps.td
- iree/compiler/Dialect/VMLA/vmla.imports.mlir
- iree/hal/vmla/op_kernels.h
- iree/hal/vmla/op_kernels_generic.h
- iree/hal/vmla/vmla_module.cc
Handles the tf.math.reduce_any and tf.math.reduce_all operations.
Added a reduce_test.py file to check all reductions.
> Add and/or reduce support to VMLA

- integrations/tensorflow/e2e/math/BUILD
This passes on Swiftshader but fails on real Turing GPUs.
https://source.cloud.google.com/results/invocations/aead115c-3aab-4499-9a91-efa304f85a5e/
> Mark mod as failing on Vulkan

- integrations/tensorflow/e2e/math/BUILD
This is required internally at the moment. We could consider setting PY3
in the iree_py* rules as well.
> Explicitly set python_version in new Python tests

- iree/compiler/Conversion/LinalgToSPIRV/VectorizeMemref.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/memref_vecrotization.mlir
This allows better code generation for f16 cases as it can allow skipping costly back and forth casting.
> Improve memref vectorization to not use larger type if not needed

- integrations/tensorflow/e2e/math/BUILD
While it's good to not have a thousand test targets with one function
each, these tests are also pretty slow at the moment (in particular
with swiftshader they can be quite slow). This shards the tests into
approximately 5 functions per instance, which gives a reasonable
tradeoff between startup overhead and test latency.
> Shard TF math tests

- colab/edge_detection.ipynb
- colab/mnist_tensorflow.ipynb
- colab/resnet.ipynb
- integrations/tensorflow/bindings/python/pyiree/tf/support/BUILD
- integrations/tensorflow/bindings/python/pyiree/tf/support/module_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/module_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_utils_test.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/trace_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/trace_utils_test.py
- integrations/tensorflow/e2e/README.md
These files were becoming long catch-alls so I split them up:
- `ModuleCall`, `Trace` and `TracedModule` are moved from `tf_test_utils` into `trace_utils`.
- `compare_traces` is removed from `Trace` and in favor of accessing it from `trace_utils.compare_traces`.
- `check_same` is moved into `tf_utils`.
- `_FunctionWrapper` and `CompiledModule` (sub)classes are moved into `module_utils` along with `BackendInfo`.
- The tests are split up to match these changes.
> Refactor trace_utils and module_utils out of tf_test_utils/tf_utils

- .github/workflows/publish_docs.yml
This addresses the "The `add-path` command is disabled. Please upgrade
to using Environment Files or opt into unsecure command execution by
setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to
`true`." issue.
> [doc] Use v3 Ninja setup to unbreak doc publication

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/e2e/keras/layers/BUILD
- integrations/tensorflow/e2e/keras/layers/layers_test.py
- Removes the disabled `*Cell` layers from tests, as they don't fit into the framework.
- Requires that at least one `UnitTestSpec` has all-default values for any provided unreqiured kwargs. This allows us to get test coverage for the most common use-cases of each layer, even if the full api is unsupported.
- Adds `static_signature` to `tf_function_unit_test` to allow valid input-generation shapes for fully dynamic `input_signatures`.
I tried adding support for testing multiple layers like I did in the `tf.math` tests, but the initialization cost of creating `tf.keras.Model`s was too great for there to be any benefit in doing so. I also tried caching `SavedModel`s and using `tf.keras.models.clone_model`, but both were equally as slow.
> Use UnitTestSpec in tf.keras.layers tests

- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- scripts/get_e2e_artifacts.py
`get_saved_model` doesn't actually do anything anymore, and no-one has been missing it for some months now.
> Remove no-longer-functional flag

- build_tools/bazel/build_tensorflow.sh
- integrations/tensorflow/bindings/python/pyiree/tf/support/module_utils.py
We aren't uploading reproducer artifacts anywhere, and using the crash reproducer suppresses C++ stack traces. By disabling the reproducer on CI we should get more helpful error logs when the compiler crashes. As before, developers can run tests locally to generate reproducer artifacts.
> Disable MLIR crash reproducer on CI in python tests.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/CMakeLists.txt
- iree/compiler/Dialect/VM/Target/C/CMakeLists.txt
- iree/tools/CMakeLists.txt
Required after IREE_COMMON_INCLUDE_DIRS were (finally!) dropped with
pull request #3874.
> Fixup EmitC include directories

- docs/get_started/getting_started_linux_cmake.md
Update Linux CMake to also include an LLVM AOT example (based on the Android example)
> Update Linux docs to include an LLVM AOT example

- iree/compiler/Conversion/LinalgToSPIRV/VectorizeMemref.cpp
We need to make sure memrefType has non-0 rank before accesing
its shape with `.back()`.
> Fix VectorizeMemref out-of-bound access

- build_tools/docker/manage_images.py
All subprocess calls are replaced with `subprocess.run` via `run_command` (which has better default kwargs, handles dry runs and prints the shell command for each invocation).
> Use subprocess.run and types in manage_images.py

- integrations/tensorflow/compiler/dialect/tf_tensorlist/conversion/BUILD
- integrations/tensorflow/compiler/dialect/tf_tensorlist/conversion/convert_flow_to_hal.cc
- integrations/tensorflow/compiler/dialect/tf_tensorlist/conversion/convert_tf_to_tf_tensorlist.cc
- integrations/tensorflow/compiler/dialect/tf_tensorlist/conversion/convert_tf_to_tf_tensorlist.td
- integrations/tensorflow/compiler/dialect/tf_tensorlist/conversion/test/convert_flow_to_hal.mlir
- integrations/tensorflow/compiler/dialect/tf_tensorlist/conversion/test/convert_tf_to_tf_tensorlist.mlir
- integrations/tensorflow/compiler/dialect/tf_tensorlist/ir/test/ops.mlir
- integrations/tensorflow/compiler/dialect/tf_tensorlist/ir/tf_tensorlist_ops.td
- integrations/tensorflow/e2e/tensorlist_test.py
- iree/compiler/Dialect/Modules/TensorList/Conversion/test/convert_hal_to_vm.mlir
- iree/compiler/Dialect/Modules/TensorList/IR/TensorListOps.cpp
- iree/compiler/Dialect/Modules/TensorList/IR/TensorListOps.td
- iree/compiler/Dialect/Modules/TensorList/IR/test/ops.mlir
- iree/compiler/Dialect/Modules/TensorList/tensorlist.imports.mlir
- iree/modules/tensorlist/native_module.cc
- iree/modules/tensorlist/tensorlist_test.cc
- iree/modules/tensorlist/tensorlist_test.mlir
Tensorlist needed a refactor on inputs. To handle support incomplete / unfilled entries for reserve
we need to track tensor information on the tensorlist (shape, element type) and support allocation
when not provided a hal buffer. This was solved by adding type information to the reserve op,
adding allocator attributes to concat and stack.
This included removing unneeded operators from the stack/concat operators.
> Tensorlist refactor to remove shape input and support empty reserve behavior

- build_tools/mako/benchmark_modules_on_android.sh
- build_tools/mako/compile_android_modules.sh
- Make compile_android_modules.sh to take the variable as target.
- Remove `"` from numbers because they are NUMERIC.
- Add `xtrace` to scripts to make debug easier.
> Fix compile and benchmark scripts for benchmarking automation.

- iree/compiler/Dialect/HAL/Target/LLVM/AOT/internal/BUILD
- iree/compiler/Dialect/HAL/Target/LLVM/AOT/internal/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/LLVM/AOT/internal/UnixLinkerTool.cpp
Change default behavior when `IREE_LLVMAOT_LINKER_PATH` isn't set for unix host and target systems:
- For unix host & target search for system linker path.
- For android target set up linker path using `ANDROID_NDK` variable.
> Auto discover unix linker path and setup Android NDK linker

- build_tools/mako/benchmark_modules_on_android.sh
This allows us to get more sample points in one run, and can get more
stable results.
Ignore the report of mean/median/stddev because Mako can deal with them.
> Set repetitions of benchmark to 10.

- iree/hal/dylib/registration/driver_module.cc
- iree/hal/llvmjit/registration/driver_module.cc
- iree/hal/metal/registration/driver_module.cc
- iree/hal/vmla/registration/driver_module.cc
- iree/hal/vulkan/registration/driver_module.cc
Should fix:
`format specifies types 'unsigned int' but the argument has type 'iree_hal_driver_id_t' (aka 'unsigned long long') [-Werror,-Wformat]`
> Fix printf format for uint64_t from PRIXPTR to PRIu64.

- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.h
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/test/executable_ops.mlir
This revision introduces a tiled tensor.load/store interface abstraction that is expected to help bridge the tensor - buffer gap after "linalg on tensor"-based transformations.
At this time, only the vanilla core OffsetSizeAndStrideOpInterface verification is implemented.
Further type verification and canonicalizations are left for the future, on a per-need basis.
> Introduce hal.interface.tensor.load/store.tile

- docs/developing_iree/ccache.md
Reviewers note: Looking around our getting-started docs, I got the impression that we're only ever using the `Ninja` generator, including on Windows and Mac. Please confirm that's correct: this doc relies on this assumption.
> add ccache doc

- integrations/tensorflow/bindings/python/pyiree/tf/compiler/__init__.py
- integrations/tensorflow/bindings/python/pyiree/tf/compiler/test/saved_model_adopt_exports.py
- integrations/tensorflow/compiler/BUILD
- integrations/tensorflow/compiler/ConvertToMHLO.cpp
- integrations/tensorflow/compiler/Passes.cpp
- integrations/tensorflow/compiler/Passes.h
- integrations/tensorflow/compiler/README.md
- integrations/tensorflow/compiler/dialect/tf_strings/conversion/BUILD
- integrations/tensorflow/compiler/dialect/tf_strings/ir/BUILD
- integrations/tensorflow/compiler/dialect/tf_tensorlist/conversion/BUILD
- integrations/tensorflow/compiler/dialect/tf_tensorlist/ir/BUILD
- integrations/tensorflow/compiler/iree-tf-import-main.cc
* Step 1/n of refactoring Python bindings to be based on a pure executable dep for TensorFlow interop.
* All tests pass except Vulkan (no GPU on this VM).
> Extract standalone "iree-tf-import" tool.

- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Dialect/Flow/Utils/BUILD
- iree/compiler/Dialect/Flow/Utils/CMakeLists.txt
- iree/compiler/Dialect/Flow/Utils/DispatchUtils.cpp
This is a minimal sketch of a prototype pass to connect Linalg on tensors to CPU execution. This does not require dispatch region reordering and can connect to end-to-end execution once the 2 missing passes are upstreamed.
At the same time, this allows working on a common pass ordering sketch to allow reordering dispatch region creation as necessary.
> Sketch an experimental Linalg on tensors LLVM compiler

- .github/workflows/update_llvm_dependent_submodules.yml
Untested.
The goal with this is to be able to update the PRs generated by `iree-github-actions-bot` on demand in addition to on a schedule, for cases when the LLVM commit or https://github.com/google/llvm-bazel update between the scheduled runs. Reusing the bot-generated PRs instead of running https://github.com/google/iree/blob/main/scripts/git/update_llvm_dependent_submodules.sh directly will reduce PR noise on the repository and save a few steps for maintainers.
See documentation: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> Add workflow_dispatch trigger to update submodules action.

- bindings/python/pyiree/compiler2/README.md
- bindings/python/pyiree/compiler2/__init__.py
- bindings/python/pyiree/compiler2/core.py
- bindings/python/pyiree/compiler2/tf.py
- bindings/python/pyiree/compiler2/tools.py
- bindings/python/tests/README.md
- bindings/python/tests/compiler_core_test.py
- bindings/python/tests/compiler_tf_test.py
* Builds on the iree-tf-import work submitted prior.
* Creates a temporary pyiree.compiler2 module to eventually replace pyiree.compiler and pyiree.tf.compiler.
* Stays somewhat close to the original API but shaves off a lot of rough edges that accumulated over time.
* Will introduce more logging and debugability in a follow-on once more is wired up.
* No build support yet: just running tests individually at the moment with IREE_TOOL_PATH set to find the compiled tools.
> Step 2/n: Implementing new compiler python API.

- build_tools/docker/base/Dockerfile
- build_tools/mako/compile_android_modules.sh
This didn't actually update the docker images and makes our docker files out of sync with the images being used. The base image is used
by basically all of our production images, so it has far-reaching
effects (not just Android).
Reverts google/iree#4110
> Revert "Remove explicitly setting IREE_LLVMAOT_LINKER_PATH in build scripts"

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/LinalgTileAndDistributeOnTensorsPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/test/tile_and_distribute_on_tensors.mlir
- iree/compiler/Conversion/init_conversions.h
The TileAndDistributeOnTensors pass performs tiling and distribution to a 3-D grid of processors identified by their WorkgroupIdOp in a range of [0, WorkgroupSizeOp).
This results in a parametric tiling that currently does not allow further canonicalizations.
PiperOrigin-RevId: 345629018
> Add a primitive Linalg TileAndDistributeOnTensors pass.

- bindings/python/build_tools/python/generate_build.py
- bindings/python/pyiree/compiler2/core.py
- bindings/python/pyiree/compiler2/tf.py
- bindings/python/pyiree/compiler2/tools.py
- bindings/python/pyiree/rt/system_api.py
- bindings/python/setup.py
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- build_tools/docker/utils.py
- build_tools/manylinux_py_setup.py
- colab/start_colab_kernel.py
- configure_bazel.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/module_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py
- integrations/tensorflow/bindings/python/pyiree/tf/support/trace_utils.py
- scripts/get_e2e_artifacts.py
- scripts/git/submodule_versions.py
- scripts/git/update_to_llvm_syncpoint.py
- scripts/git/utils.py
- scripts/update_e2e_coverage.py
- scripts/update_op_coverage.py
- scripts/utils.py
Note: It's probably easiest to review each commit separately.
Changes:
- Remove remaining %-string substitutions (`absl.logging` excluded).
- Replace all `subprocess.check_*` calls with the recommended `subprocess.run(check=True,...)`.
- Add TODO(#4131) for the following:
- `python>=3.7: Use postponed type annotations.`
- `python>=3.7: Consider using a dataclass.`
- `python>=3.7: Use capture_output=True.`
- `python>=3.7: Replace 'universal_newlines' with 'text'.`
- `python>=3.7: Remove redundant OrderedDict.`
> Use recommended python3.6 APIs and document 3.7 upgrades

- iree/compiler/Dialect/Flow/Transforms/LegalizeInputTypes.cpp
- iree/compiler/Dialect/Flow/Transforms/test/legalize_input_types.mlir
Assume that all Linalg ops on tensors have legal input types for now.
This allows IREE to ingest Linalg on tensor ops from the frontend and pipe it through.
This is necessary to use Linalg on tensors as a programming model for IREE without relying on HLO.
> Let Linalg on tensor ops pass LegalizeInputTypes

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
This is a direct copy of the pipeline at
https://buildkite.com/iree/iree-android-arm64-v8a/steps with the 
modification being the addition of a license header. I'd like to make
further edits (like some line wrapping), but will hold off on that
until this is actually getting tested. After this is checked in, I'll
change the pipeline configured in the BuildKite UI to just load the
pipeline from this file per the instructions at
https://buildkite.com/docs/pipelines/defining-steps#dynamic-pipelines.
Note that this workflow only runs post-submit (or when manually
triggered by a project member), so this level of dynamic execution is
safe. If we start running BuildKite pipelines on presubmit we should
investigate some checks to ensure they've been reasonably vetted.
> Check in BuildKite pipeline for android tests

- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/test/e2e/xla_ops/convolution.mlir
Added a refactor to normalize convolution values. This is designed to decompose and simplify
convolutions for use with IREE's compiler passes. The different dimension orders are not
usually constructed via the TF compilation pass but are technically legal.
> Refactor and normalization of mhlo convolutions

- docs/get_started/getting_started_python.md
- Add build instructions (default without TensorFlow).
- Add note on `-fPIC` for `pyenv` and others.
- Add leading `$ ` to match the rest of the getting started docs.
- Make the commands more `cwd` independent.
> Add build instructions to python getting started

- bindings/python/pyiree/rt/system_api.py
`f"{variable:!r}"` is not equivalent to `f"{repr(variable)}"` in general. 
PEP 498 says that `!r` and others are supported for compatibility with `str.format()`, but doesn't mention that it inherits `str.format`'s limitations (or that there are any). For example:
```python
array = [0, 1, 2]
print(f"{repr(array)}")  # [0, 1, 2]
print(f"{array:!r}")  # TypeError: unsupported format string passed to list.__format__
```
Given this it seems like `!r` should probably be avoided.
> Remove all !r from python f-strings

- iree/vm/bytecode_dispatch.c
This was not caught by CI because it needs to build with
`#define IREE_DISPATCH_LOGGING 1`, which logs more information for
dispatches. The macro takes `const iree_vm_function_t *` type as
argument, so we have to pass by pointer.
> Pass pointer of iree_vm_func_t to IREE_DISPATCH_LOG_CALL.

- iree/compiler/Dialect/Flow/Transforms/DispatchConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/test/fold_compatible_dispatch_regions.mlir
- iree/test/e2e/structural/BUILD
- iree/test/e2e/structural/CMakeLists.txt
- iree/test/e2e/structural/gather_add.mlir
This patch relaxes the torch_index_select opt to live with consumers in
a dispatch function.
> Make TorchIndexSelectOp being able to fuse with consumers.

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/common.cfg
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/google.cfg
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/main.cfg
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/presubmit.cfg
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/common.cfg
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/google.cfg
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/main.cfg
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/presubmit.cfg
- build_tools/kokoro/gcp_ubuntu/simulate_kokoro.sh
Creates CI configs that use the images added in #4176 to test the tensorflow 
integrations on swiftshader and nvidia GPU.
> Add Kokoro config for integrations tests

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/LinalgBufferizePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/test/linalg_bufferize.mlir
- iree/compiler/Conversion/init_conversions.h
This rervision adds a specific bufferization pass that takes advantage of IREE-specific
knowledge and refrains from using upstream bufferization for now.
This is aimed as a step towards connecting pieces and getting a functional prototype.
Some layering aspects are still off at this time.
> Add a primitive Linalg bufferization pass

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build_kokoro.sh
Kokoro makes you specify this path at least five times, which does not make it less error prone.
Fixes a mistake in https://github.com/google/iree/pull/4183. Will re-run the manual presubmits to verify that things work as expected.
Edit: Found #4195, which I'm getting around temporarily by moving all of the PR files into an `iree/` sub directory and then using `/src/github/iree/` as the base for an out-of-tree build.
> Fix mis-copied path in kokoro config

- iree/compiler/Conversion/CodegenUtils/FunctionUtils.cpp
- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/IR/LLVMIRTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMBaseTarget.cpp
- iree/compiler/Dialect/HAL/Target/SPIRVCommon/SPIRVTarget.cpp
- iree/compiler/Dialect/VM/Transforms/MarkPublicSymbolsExported.cpp
- iree/compiler/Dialect/VMLA/Transforms/Conversion.cpp
- This is in preparation of upstream MLIR changes.
> [NFC] Eliminate use of SymbolTable::getSymbolVisibility()

- iree/hal/metal/registration/driver_module.cc
it seems this is a trivial typo preventing the driver from been compiled
> fix a trivial typo in metal driver

- build_tools/cmake/bazel.bat.in
- build_tools/cmake/bazel.sh.in
- build_tools/cmake/configure_bazel.cmake
Tested that this builds locally and works as intended [on the CI](https://source.cloud.google.com/results/invocations/5611aaf1-7b17-48bb-b163-18f0417579e9/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-swiftshader%2Fpresubmit/log). Unable to personally test the behavior on windows.
> Make cmake-bazel output color for the CI

- CMakeLists.txt
This fixes the generation of target and driver booleans. So far,
building IREE e.g. with `-DIREE_HAL_DRIVERS_TO_BUILD="VMLA"` resulted in
the generation of the boolean `IREE_TARGET_BACKEND_"VMLA":BOOL=ON`. The
quotation marks are not desired here and later on checks expect
`IREE_TARGET_BACKEND_VMLA`.
> Strip quotes from target and driver string

- build_tools/cmake/configure_bazel.cmake
- integrations/tensorflow/CMakeLists.txt
- integrations/tensorflow/compiler/BUILD
- integrations/tensorflow/compiler/iree-tf-opt-main.cpp
- integrations/tensorflow/compiler/test/CMakeLists.txt
- iree/tools/run_lit.sh
* Also adds the handful of lit tests in integrations/tensorflow.
* Strips down iree-tf-opt to its minimum requirements (it is on the critical build path).
* Applies more patches to run_lit.sh (really need to get rid of that soon).
> Build iree-tf-opt as part of the cmake build when tests are enabled.

- iree/testing/gtest_main.cc
For consistency with other usage throughout the project and to isolate
some of the shimming we have to do internally due to different include
paths.
> Make gtest_main include gtest shim

- .clang-format
- iree/hal/vulkan/api.h
- iree/hal/vulkan/debug_reporter.h
- iree/hal/vulkan/direct_command_buffer.h
- iree/hal/vulkan/direct_command_queue.h
- iree/hal/vulkan/dynamic_symbols.h
- iree/hal/vulkan/emulated_timeline_semaphore.h
- iree/hal/vulkan/extensibility_util.h
- iree/hal/vulkan/handle_util.h
- iree/hal/vulkan/internal_vk_mem_alloc.h
- iree/hal/vulkan/native_descriptor_set.h
- iree/hal/vulkan/native_event.h
- iree/hal/vulkan/native_timeline_semaphore.h
- iree/hal/vulkan/pipeline_cache.h
- iree/hal/vulkan/pipeline_executable.h
- iree/hal/vulkan/pipeline_executable_layout.h
- iree/hal/vulkan/serializing_command_queue.h
- iree/hal/vulkan/status_util.h
- iree/hal/vulkan/timepoint_util.h
- iree/hal/vulkan/vma_allocator.h
- iree/hal/vulkan/vma_buffer.h
- iree/hal/vulkan/vulkan_device.h
- iree/hal/vulkan/vulkan_driver.h
The internal formatter does not respect `.clang-format` files for...
reasons. This method works without having to use the style file. It's
also nice for humans to have the comment about what's going on. It's a
bit verbose, unfortunately.
> Replace style file with directives to not sort vulkan_headers.h

- .github/workflows/lint.yml
"eoan" is Ubuntu 19.04 and these containers are Ubuntu 18.04. This is
causing failures in the action complaining that "The repository does
not have a Release file." (e.g. 
https://github.com/google/iree/pull/4301/checks?check_run_id=1601595431)
We could replace with "bionic", but this
actually doesn't seem to be necessary at all. It's been in place since
https://github.com/google/iree/commit/1206452e7816 and
https://github.com/google/iree/commit/6f203bbd5b99 when we were running
with the "latest" ubuntu containers, which probably explains why they
were pointing at a different version.
> Remove apt repository for wrong Ubuntu version

- integrations/tensorflow/compiler/Passes.cpp
- integrations/tensorflow/compiler/dialect/tf_strings/conversion/convert_tf_strings_to_strings.cc
- integrations/tensorflow/compiler/dialect/tf_strings/conversion/convert_tf_to_tf_strings.cc
- integrations/tensorflow/compiler/dialect/tf_strings/conversion/convert_tf_to_tf_strings.td
- integrations/tensorflow/compiler/dialect/tf_strings/conversion/test/tf_strings_to_strings.mlir
- integrations/tensorflow/compiler/dialect/tf_strings/conversion/test/tf_to_tf_strings.mlir
- integrations/tensorflow/compiler/dialect/tf_strings/ir/ops.td
- integrations/tensorflow/e2e/strings_test.py
- iree/compiler/Dialect/Modules/Strings/Conversion/ConversionPatterns.cc
- iree/compiler/Dialect/Modules/Strings/IR/Ops.td
Gather operations added to the strings and tf_strings dialect with
lowerings from TensorFlow to tf_strings and tf_string to strings.
This includes tests for each and an end-to-end test. Right now the
python test does not validate values (missing conversion from
StringTensor to Numpy equivalent) but prints instead. Close enough
for current support.
> Support for TF.Gather including intermediate dialect work

- build_tools/cmake/external_cc_library.cmake
- build_tools/cmake/iree_cc_library.cmake
This was causing issues where flags like /LTCG were getting interpreted
as libraries that couldn't be found.
> Splitting link options from link libraries in cmake.

- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_lit_test.cmake
Follow-up to https://github.com/google/iree/pull/4279, aiming to fix [failing benchmarks](https://buildkite.com/iree/iree-android-benchmark/builds/1177) and re-enable skipped tests: [before](https://buildkite.com/iree/iree-android-arm64-v8a/builds/3351), [after](https://buildkite.com/iree/iree-android-arm64-v8a/builds/3352).
> Relax and document IREE_BUILD_COMPILER checks in cmake functions.

- scripts/git/update_to_llvm_syncpoint.py
The terminology here was a bit sloppy and caused some confusion.
Differentiate between rev, ref, commit, named commit option, etc.
> Clean up naming in LLVM sync script

- .github/workflows/update_llvm_dependent_submodules.yml
- scripts/git/update_llvm_dependent_submodules.sh
- scripts/git/update_to_llvm_syncpoint.py
This updates the MLIR-HLO submodule in a similar manner to the TF
submodule, just with slightly less parsing because the LLVM commit
information is in its own file.
> Add scripting to update mlir-hlo to match LLVM commit

- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- iree/modules/strings/BUILD
- iree/modules/strings/CMakeLists.txt
- iree/modules/tensorlist/BUILD
- iree/modules/tensorlist/CMakeLists.txt
- iree/tools/compilation.bzl
- iree/vm/BUILD
- iree/vm/CMakeLists.txt
Also adds the testonly option to the iree_bytecode_modules that are only used for testing
> Update bazel_to_cmake to support testonly for iree_bytecode_module

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
`iree/compiler/Dialect/Flow/Transforms/Passes.cpp` calls
`addHLOToLinalgOnTensorsPasses()`. This function is declared in
`iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensorPasses.h`,
belonging to the target HLOToLinalgOnTensors. However, it is defined in
`iree/compiler/Conversion/HLOToLinalg/Passes.cpp`, belonging to the
target HLOToLinalg. This blocks updating the iree submodule in
https://github.com/iml130/iree-template-cpp.
> Add missing dep on HLOToLinalg

- scripts/git/update_llvm_dependent_submodules.sh
This respects the existing `FORK_REMOTE` env variable and doesn't
require a `gh` config setting that some people have been having issues
with.
The syntax for specifying the remote here is a pain to work with, see
https://github.com/cli/cli/issues/1985
> Get remote name in a more portable way in gh scripting

- .github/workflows/update_llvm_dependent_submodules.yml
- scripts/git/update_llvm_dependent_submodules.sh
This avoids needing to reconfigure the same thing in two different
syntaxes. The `gh` CLI is available on GitHub action runners and
respects the `GITHUB_TOKEN` env variable for auth.
Tested:
Ran on my fork. https://github.com/GMNGeoffrey/iree/actions/runs/453306027 created https://github.com/GMNGeoffrey/iree/pull/66
> Use existing script in submodule synchronize action

- build_tools/bazel/iree.bazelrc
- iree/task/executor.c
- iree/task/list_test.cc
This is turned on in the internal build configuration and having it off
here means we only hit those failures on integrate.
> Turn -Wunused-variable back on

- CMakeLists.txt
- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- build_tools/cmake/iree_run_binary_test.cmake
- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/vm/BUILD
- iree/vm/CMakeLists.txt
It's good to test that these benchmarks run. It's really annoying to run
a billion iterations of them every time you try to run tests. This
literally takes longer than all the other tests combined. Instead, make
these binaries and invoke them for testing with
`--min_benchmark_time=0`.
This introduces CMake and Bazel -> CMake support for `run_binary_test`,
which runs the specified executable target with the specified args.
Punted on support for data dependencies, since these are not required
for this use case and I think we still haven't figured out how to do
that for CMake tests.
> Avoid running slow benchmarks as part of testing

- build_tools/cmake/iree_run_binary_test.cmake
These tests were broken by https://github.com/google/iree/pull/4364
(https://buildkite.com/iree/iree-android-arm64-v8a/builds/3408#2703aa49-1075-4199-96bb-233f94d8727b).
Temporarily disabling to get things green so we avoid regressions while
I test out the fix.
> Disable run_binary_test on Android

- CMakeLists.txt
- iree/tools/CMakeLists.txt
Now that the VM generated op definitions are checked in, we can avoid
this weird special casing.
I think there should be more cleanup around `IREE_ENABLE_MLIR` in
general, but deferring that for another change.
Tested:
Built and tested with compiler and mlir disabled
> Remove special handling for runtime -> compiler dep

- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
- iree/hal/local/arena.c
- iree/hal/local/arena.h
This will be used to provide storage for command buffers and other
builder types (submissions/etc) in the local HAL backend.
> Adding a new arena type with a shared thread-safe block pool.

- build_tools/third_party/pffft/BUILD.overlay
- build_tools/third_party/pffft/CMakeLists.txt
- iree/hal/vmla/op_kernels_fft.h
This is more portable to our google internal source control, where
pffft has a slightly weird directory path.
> Include pffft.h without directory prefix

- build_tools/cmake/iree_copts.cmake
- build_tools/cmake/iree_python.cmake
- iree/compiler/Dialect/HAL/Target/MetalSPIRV/SPIRVToMSL.cpp
- iree/vm/list_test.cc
- iree/vm/module_abi_packing.h
- iree/vm/ref_test.cc
* Enables them for python bindings.
* Configures SPIRV-Cross to use assertions instead.
* Fix a number of non load bearing typeid() name lookups in the VM.
> Globally disable RTTI and exceptions in IREE.

- bindings/python/tests/compiler_tf_test.py
- integrations/tensorflow/compiler/iree-import-tflite-main.cpp
- integrations/tensorflow/compiler/iree-import-xla-main.cpp
- integrations/tensorflow/compiler/iree-tf-import-main.cpp
* I've just made this non optional for now. Anyone wanting to inspect this can trivially pipe it back through the MLIR API for further work and better output.
* Fixes: #4441
> Importers should print the generic op form.

- bindings/python/tests/compiler_xla_test.py
- integrations/tensorflow/compiler/iree-import-xla-main.cpp
* We would like to eliminate the need to do this, but it makes the setup work for now.
* Fixes #4444
> Annotate XLA imported module @main functions with iree.module.export.

- build_tools/cmake/iree_cc_library.cmake
In Bazel, in cc_library, copts and linkopts apply only to the library
itself, not its dependents. In a header-only cc_library, copts and linkopts
are ignored.
Note: I checked locally by adding a `if()` with a `message()` in this CMake code: there are currently no `INTERFACES` with `COPTS` or `LINKOPTS`.
> Let iree_cc_library mirror Bazel cc_library more faithfully.

- .github/workflows/update_llvm_dependent_submodules.yml
Unfortunately `gh` will not update an existing PR as written, and in
fact there's no way to do so (https://github.com/cli/cli/issues/1349).
That means the description of https://github.com/google/iree/pull/4424
is wrong. Until that's fixed we need to use a separate mechanism for
creating the PR in the action. We can potentially do something clever to
increase code reuse, but for now, I'm reverting my change.
This reverts commit 52ebf7b003419f5970871fe69dc731e7beea7d37.
> Revert "Use existing script in submodule action (#4358)"

- .github/workflows/synchronize_submodules.yml
Instead of adding a new commit that fixes up the submodules, rewrite
the HEAD commit so that they are correct. This action was originally
intended for rare cases where Copybara messed up integrations. These
"rare cases" now happen multiple times a day and are cluttering the
repository history with useless commits. We have already decided it's
ok to rewrite the google branch history to fix up Copybara failures to
create merge commits, so this doesn't change things much. It also
us to expand this action to create those merge commits as well.
Somewhat incidentally, I noticed that this action doesn't actually need
to initialize the submodules themselves. It only really deals in
hashes, which are already recorded. Dropping this makes it ~10x faster.
This has a couple disadvantages:
- If …
> Force push when synchronizing submodules

- build_tools/cmake/iree_cc_library.cmake
Linkopts are inherited by dependent rules, thanks @GMNGeoffrey!
> revert the part of PR #4453 about linkopts

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM2.cpp
- iree/compiler/Conversion/LinalgToLLVM/LinalgBufferizePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/LinalgRewriteDestructiveUpdatesPass.cpp
- iree/compiler/Dialect/Flow/Transforms/DestructiveUpdateUtils.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/test/e2e/regression/dynamic_linalg_matmul_on_tensors.mlir
This revision pipes dynamic shapes through IREE on tensors all the way to LLVM.
Peculiarities of TieShapeOp require some genuflexions to traverse IR and recover proper
indices for the memref shapes in bufferization.
This creates an asymmetry that it would be welcome to remove in the future, once we have core support for ranked shapes types and subshape operations as discussed in
https://llvm.discourse.group/t/linalg-and-shapes/2421.
PiperOrigin-RevId: 350429972
> Add support for dynamic shapes in IREE on Linalg on tensors.

- iree/compiler/Conversion/LinalgToLLVM/Passes.h
This is potentially fixing windows build failure
> Fix type mismatch between definition and declaration.

- build_tools/cmake/iree_cc_library.cmake
- iree/tools/android/run_module_app/CMakeLists.txt
Linking as whole archive is neither necessary any more nor supported.
> Drop WHOLEARCHIVE leftovers

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
- integrations/tensorflow/e2e/CMakeLists.txt
- integrations/tensorflow/e2e/keras/CMakeLists.txt
- integrations/tensorflow/e2e/keras/train/CMakeLists.txt
- integrations/tensorflow/e2e/keras/train/classification_training_test.py
- integrations/tensorflow/e2e/keras/train/regression_training_test.py
- Explicitly convert inputs to `f32`.
- Compare model weights and biases across backends.
- Add CMake configuration for testing in OSS.
I am adding these tests in OSS before we figure out the long-term structure for the e2e CMake build since they cannot be enabled internally at this time.
> Enable SGD training tests

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM2.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
This revision shows how to enable fusion incrementally in the context of dispatch region formation on linalg on tensors.
The dispatch pattern is temporarily modified to only apply to MatmulOp and is extended to only fuse the first producer.
This is meant to be refactored and extended in real-world scenarios, the current revision exercises proper DispatchWorkgroupOp operand and BBarg formation in the context of fusion.
PiperOrigin-RevId: 351352845
> Add basic support for fusion in dispatch region formation.

- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
* Pending resolution of https://reviews.llvm.org/D94847
* See #4539
> Temporarily disable debug info printing in XLA importer.

- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions2.cpp
- iree/test/e2e/regression/dynamic_linalg_matmul_on_tensors_fuse_0.mlir
- iree/test/e2e/regression/dynamic_linalg_matmul_on_tensors_fuse_1.mlir
- iree/test/e2e/regression/dynamic_linalg_matmul_on_tensors_fuse_2.mlir
A bug is exhibited in core buffer hoisting passes, so we temporarily disable them.
PiperOrigin-RevId: 351352838
> Add e2e tests that also exercise fusion.

- iree/compiler/Dialect/VMLA/vmla.imports.mlir
- iree/hal/vmla/BUILD
- iree/hal/vmla/op_kernels.h
- iree/hal/vmla/op_kernels_ruy.h
- iree/hal/vmla/op_module.cc
- iree/test/e2e/xla_ops/dot.mlir
- iree/test/e2e/xla_ops/partial/BUILD
- iree/test/e2e/xla_ops/partial/CMakeLists.txt
- iree/test/e2e/xla_ops/partial/dot_int.mlir
Just i32i32.i32 for now. Other cases proved to be far more complicated
than expected. This includes making our template parameters indicate
the full versatility of ruy's matmul.
> Add VMLA support for integer matmul

- iree/compiler/Conversion/Common/BUILD
- iree/compiler/Conversion/Common/CMakeLists.txt
- iree/compiler/Conversion/Common/LaunchConfig.cpp
- iree/compiler/Conversion/Common/LaunchConfig.h
- iree/compiler/Conversion/Common/Passes.h
- iree/compiler/Conversion/Common/RemoveDeadMemAllocsPass.cpp
- iree/compiler/Conversion/Common/Transforms.cpp
- iree/compiler/Conversion/Common/Transforms.h
- iree/compiler/Conversion/Common/test/BUILD
- iree/compiler/Conversion/Common/test/CMakeLists.txt
- iree/compiler/Conversion/Common/test/remove_dead_allocs.mlir
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.cpp
- iree/compiler/Conversion/LinalgToLLVM/LinalgTileAndDistributePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/tile_and_distribute.mlir
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/test/e2e/linalg_tensor_ops/BUILD
Current implementation of the Linalg on tensors path is only tested
with static tile sizes specified at command line. In this PR
- Use `flow.dispatch.workgroup.size` to represent the dynamic tile
size used
- After conversion to HAL, where `flow.dispatch.workgroup.size` gets
replaced by `hal.interface.workgroup.size`, use LaunchConfig to set
the value of `hal.interface.workgroup.size` to a static value.
- This effectively replace the first level of tiling done by the
existing codegen paths. The rest of the codegen can then be used
with this path.
Also included all minor fixes needed to plumb everything through.
> Integrate Linalg on tensors path to rest of CPU backend (Part 1)

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM2.cpp
Bumping the pattern makes the pattern in IREE trigger before a similar
pattern in MLIR core that is added to the pattern list by
`populateStdToLLVMConversionPatterns`.
Fixes #4409
> Bump benefit of pattern to convert from func -> llvm.func in ConvertToLLVM2

- iree/compiler/Dialect/VMLA/Transforms/PreConversionLowering.cpp
- iree/compiler/Dialect/VMLA/Transforms/test/pre_conversion_lowering.mlir
- iree/compiler/Dialect/VMLA/vmla.imports.mlir
- iree/hal/vmla/op_module.cc
- iree/test/e2e/xla_ops/partial/dot_int.mlir
Adds support for i8 x i8 and i16 x i16. In both cases, the accumulator
and destination type is i32. This is the simple case, whereas if the
destination type were smaller, we'd probably want (need?) to do some
rescaling as part of the op. Ruy implements such rescaling, but I think
it would need to come as additional parameters to the op.
Includes adding support in the mhlo.dot[_general] lowering for differing
input/output element types.
> Add VMLA support for mixed-type integer matmuls

- iree/base/internal/file_io_win32.cc
- iree/hal/local/task_command_buffer.c
- iree/testing/vulkan/iree-run-module-vulkan-gui-main.cc
* Use `IREE_RESTRICT` for older MSVC versions.
* Update iree-run-module-vulkan-gui-main.cc
* Include <atomic> for std::atomic use in GetTempFile.
Tested CMake build of `all` (vmla+vulkan only) on my Windows machine, with samples and Vulkan enabled.
> More fixes after HAL C changes.

- build_tools/mako/compile_android_modules.sh
Attempted fix for failing iree-android-benchmark runs: https://buildkite.com/iree/iree-android-benchmark/builds/1733#3de7c616-bd4d-45d2-8dc1-50a51fbdd047, failing after https://github.com/google/iree/pull/4584.
cc @hanhanW
> Revert removing explicit linker path in compile_android_modules.sh.

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark.yml
The GitHub configuration for the pipeline in the BuildKite GUI still
only triggers automatically on pushes to `main`, but this allows
manually triggering on pull requests (using the somewhat esoteric
BuildKite method of setting branch to `pull/<pr_number>/head`) or other
branches and actually having something run. The final step to upload
to Mako is still skipped, to avoid polluting the dashboard.
Tested:
Ran the benchmark pipeline on presubmit for this PR.
> Allow benchmark pipeline to be run on presubmit

- iree/base/wait_handle_impl.h
- iree/hal/buffer.c
- iree/hal/command_buffer_validation.c
- iree/hal/local/local_executable.h
- iree/hal/local/task_command_buffer.c
Unfortunately not caught by any of our open source builds.
---
```
typedef size_t iree_host_size_t;
typedef uint64_t iree_device_size_t;
```
`iree_device_size_t` should use `% " PRIu64 "` instead of `%zu`
---
`ppoll` is available since Android API 21 (or 28 for `ppoll64`? seeing conflicting docs)
---
`iree_hal_buffer_calculate_range` outputs into a `iree_device_size_t`, which isn't directly compatible with
```
typedef struct {
uint8_t* data;
iree_host_size_t data_length;
} iree_byte_span_t;
```
> Android build fixes for HAL rewrite branch.

- iree/vm/bytecode_dispatch.c
- iree/vm/test/list_ops.mlir
I stumbled upon this while scrolling through the code.
> Fix vm.list.get.i64 in the interpreter

- bindings/python/pyiree/jax/frontend.py
- bindings/python/pyiree/jax/frontend_test.py
Since pytrees are allowed to have methods, the shape and dtypes of their children is insufficient to uniquely identify their intended behavior. This change allows multiple `flax.optim` optimizers to be passed to the same `update` function.
> Handle compiling pytrees with methods in jax frontend

- docs/get_started/getting_started_android_cmake.md
The command as written was causing the following error on my system:
```
ninja: error: 'iree/base/iree-build-host/install/bin/generate_cc_embed_data', needed by 'iree/base/testing/dynamic_library_test_library_embed.cc', missing and no known rule to make it
```
> Fix relative path error in Android getting started

- bindings/python/pyiree/jax/README.md
Compilation completes without error without `-static-libstdc++`, but `iree-run-module` gives the following error when attempting to run the `.vmfb` on device:
```
F iree/tools/iree-run-module-main.cc:163] Check failed: ::iree::IsOk(_status163) iree/iree/base/dynamic_library_posix.cc:47: UNAVAILABLE
```
Also moved setting `IREE_LLVMAOT_LINKER_PATH` so that it doesn't persist in the environment to cause future host build/compilation errors.
> Add necessary linker flag to jax-android example

- build_tools/cmake/iree_check_test.cmake
I misconfigured this as part of https://github.com/google/iree/pull/4584, leading to issues spotted on https://github.com/google/iree/issues/4617. The flatcc cli is still required for the runtime, which is what I originally filed that issue for, but compiler tools like `iree-translate` should not be.
See also https://github.com/google/iree/blob/7d0108f0d565956c51c446dd52062fa1e50ca4e3/build_tools/cmake/iree_lit_test.cmake#L39-L43
> Skip check tests on host builds when IREE_BUILD_COMPILER is OFF.

- iree/compiler/Conversion/LinalgToLLVM/LinalgBufferizePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Shape/Transforms/Passes.h
- iree/compiler/Dialect/Shape/Transforms/TieDynamicShapesPass.cpp
- iree/compiler/Dialect/Shape/Transforms/test/tie_dynamic_shapes_no_recurse.mlir
Required suppressing shapex.tie_shape insertion in two places:
- Add support for TieDynamicShapesPass to optionally not recurse into
certain regions. Used in `iree/compiler/Dialect/Flow/Transforms/Passes.cpp`
- Remove TieDynamicShapesPass from the backend when using linalg on
tensors. See `iree/compiler/Conversion/LinalgToLLVM/Passes.cpp`.
Now that there are no shapex.tie_shape simplify LinalgLLVMBufferizePass.
> Remove shapex.tie_shape from the inside of flow.dispatch.workgroups.

- iree/compiler/Dialect/Flow/IR/BUILD
- iree/compiler/Dialect/Flow/IR/CMakeLists.txt
- iree/compiler/Dialect/Flow/IR/FlowDialect.cpp
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.h
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups_folding.mlir
Linalg tends to create `std.dim` ops because it is upstream code.
However, inside a `flow.dispatch.workgroups` region, we should be using
`flow.dispatch.shape` to get the shape of the dispatch tensors.
This plays nicer with the way that flow.dispatch.workgroups is meant to
be used, and results in much nicer IR as it lets everything fold away.
Example IR before/after this change, as seen by the
LinalgLLVMBufferizePass
https://gist.github.com/silvasean/60b80d442cde72ca4a39f6198a7075dc
The new code results in no dim ops at the LinalgLLVMBufferizePass, so we
can consider removing support for them there. I don't do that in this
patch since I'm not sure if there are other considerations in flight.
I believe that by running dim op canonicalization to a fixed point we
can guarantee that they …
> Canonicalize `std.dim` into `flow.dispatch.shape` when relevant.

- iree/compiler/Conversion/LinalgToLLVM/LinalgTileAndDistributePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/matmul_vectorization.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/tile_and_distribute.mlir
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/test/executable_ops.mlir
- iree/compiler/Dialect/HAL/Target/SPIRVCommon/SPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- iree/compiler/Dialect/HAL/Target/VMLA/VMLATarget.cpp
- iree/compiler/Dialect/HAL/Transforms/TranslateExecutables.cpp
While the code-generated through the linalg on tensors path works for
any number of workgroups used by the runtime, there is advantage to
expose the maximum number of workgroups that are actually needed to
perform the entire computation represented by the
`flow.dispatch.workgroup`. The runtime can then chose to
underprovision based on resource availability.
This is done by adding a region to `hal.executable.entry_point` op
that returns the maximum number of workgroups given the workload of
the dispatched computation.
Current implementation limitations are that it is assumed that the
workload is described in terms of [x, y, z]. Due to this only those
dispatch regions in flow dialect that have workload described in terms
of [x, y, z] are handled.
A consequence of allowing backends to …
> Add region to `hal.executable.entry_point` that computes number of  workgroups.

- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/test/add.mlir
- iree/compiler/Dialect/VM/Target/C/test/empty_module.mlir
- iree/vm/BUILD
- iree/vm/CMakeLists.txt
- iree/vm/bytecode_dispatch.c
- iree/vm/c_funcs.h
- iree/vm/ops.h
This moves the native integer arithmetic ops from the bytecode
dispatcher to a header. The header only implementations can be used
within the dispatcher as well as by EmitC emitted code, avoiding to
duplicate the implementations.
> Relocate integer arithmetic ops from dispatcher

- iree/samples/emitc_modules/CMakeLists.txt
- iree/vm/test/emitc/CMakeLists.txt
Follow up to #4658. Some deps to the renamed target `iree::vm::ops` were not properly updated.
> Fix deps on renamed target iree::vm::ops

- integrations/tensorflow/WORKSPACE
This is the new way to configure TF that should allow them to change
things without breaking all dependent projects (like the issue we've
had with tf_toolchains becoming a requirement).
https://github.com/tensorflow/tensorflow/blob/b4bf78ffecff336746e3b6f2411e02087ab70aa6/WORKSPACE
explains the motivation.
> Configure TF workspace via recursive workspace files

- experimental/bindings/java/build.gradle
Add Gradle tasks to configure and make host tools with CMake before compiling the Android Java bindings.
> Add Gradle tasks to configure and make host tools with CMake before compiling the Android Java bindings.

- integrations/tensorflow/CMakeLists.txt
- integrations/tensorflow/iree_tf_compiler/BUILD
- integrations/tensorflow/iree_tf_compiler/TFL/BUILD
- integrations/tensorflow/iree_tf_compiler/TFL/ConvertMetadata.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/Passes.h
- integrations/tensorflow/iree_tf_compiler/TFL/StripMetadata.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/VerifyFullyConverted.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/test/BUILD
- integrations/tensorflow/iree_tf_compiler/TFL/test/CMakeLists.txt
- integrations/tensorflow/iree_tf_compiler/TFL/test/convert_metadata.mlir
- integrations/tensorflow/iree_tf_compiler/TFL/test/strip_metadata.mlir
- integrations/tensorflow/iree_tf_compiler/TFL/test/verify_fully_converted.mlir
- integrations/tensorflow/iree_tf_compiler/iree-import-tflite-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-opt-tflite-main.cpp
This makes iree-import-tflite run some passes to get into a good IREE input form with no remaining tflite/tf attrs. The output of iree-import-tflite can load without any tf dialects linked into the binary, meaning that iree-opt/iree-translate/etc can all consume them. It yields IR like:
```mlir
// $ iree-import-tflite iree_tf_compiler/test/TFL/multi_add.tflite
func @main(
%arg0: tensor<1x8x8x3xf32> {iree.identifier = "input0"},
%arg1: tensor<1x8x8x3xf32> {iree.identifier = "input1"}
) -> (
tensor<1x8x8x3xf32> {iree.identifier = "output0"},
tensor<1x8x8x3xf32> {iree.identifier = "output1"}
) attributes { iree.module.export }
%0 = "tosa.add"(%arg0, %arg1) : (tensor<1x8x8x3xf32>, tensor<1x8x8x3xf32>) -> tensor<1x8x8x3xf32>
%1 = "tosa.add"(%0, %arg0) : (tensor<1x8x8x3xf32>, …
```
> Adding tflite import passes and metadata conversion.

- iree/vm/bytecode_dispatch.c
- iree/vm/ops.h
This moves casting from the bytecode dispatcher to the shared
implementation which now only consumes and returns int32_t. This
simplifies the printer in the CModuleTarget (as it eliminates the need
to support unsigned int) and avoids implicit casts.
Tested together with #4723 and #4725.
> Refactor vm/ops.h's functions to consume int32_t

- iree/compiler/Translation/IREEVM.cpp
Additional arguments were added to `translateFromMLIRToVM()`, but not to the call within `translateFromMLIRToVMCModule()`.
> Fix passing binding options

- scripts/git/fix_copybara_merge.sh
This should be usable by build cops as-is, but the next step would be
integrating it to run on commits to the google branch to automatically
fix them up.
> Add a script to fix Copybara failed merges

- bindings/python/pyiree/rt/function_abi.cc
- bindings/python/pyiree/rt/host_types.cc
- bindings/python/pyiree/rt/host_types.h
* Fixes #3381
* While many programs didn't suffer from this, any time references to the array memory escape to the generational collector, a subsequent collection has a high likelihood of freeing the device prior to the buffer allocated against it.
* JAX internally seems to have a heuristic that caches a bunch of things and manually invokes the generational gc.
* There were many other things I would like to improve about this code but I held off and just did a targeted bug fix.
* The prior attempt (#3450) failed because with multiple results, it would have tried to get a weak reference to a tuple, which is not permitted. This more manual intervention stitches the keep-alive onto the actual objects that need it.
> Retain the backing device with python mapped array memory.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/compare.mlir
This generalizes the conversion pattern to handle op attributes.
> Unify patterns in the vm to emitc conversion

- iree/compiler/Conversion/CodegenUtils/MarkerUtils.cpp
- iree/compiler/Conversion/CodegenUtils/MarkerUtils.h
- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/CodeGenOptionUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/CodeGenOptionUtils.h
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Passes.cpp
- iree/compiler/Conversion/LinalgToSPIRV/Passes.h
- iree/compiler/Conversion/init_conversions.h
- iree/test/e2e/linalg_tensor_ops/BUILD
- iree/test/e2e/linalg_tensor_ops/CMakeLists.txt
The GPU path needs to 
1) Use the pass manager that works on IREE::HAL::ExecutableTargetOp, so that the LinalgTileAndFuse pass can be run on this op. This allows the pass to set the workgroup count region on the IREE::HAL::EntryPointOp.
2) The `linalg.copy` operation introduced by bufferize pass needs to have the right marker so that the ConvertToGPU pass can distribute the op to within threads in a thread block.
This allows execution of matmul on GPU with the linalg on tensors path.
> Fixes to enable executing matmul on GPU.

- build_tools/mako/benchmark_modules_on_android.sh
In the past, we only could run CPU on single thread. After 8d74bfa
landed, we are able to run on multiple threads, and it's turned on by
default. The PR forces it to run on single thread to keep the same
behavior.
Fixes https://github.com/google/iree/issues/4686
> Force CPU benchmark to run on single thread.

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/tensor_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertBufferOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertBufferViewOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/allocator_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/buffer_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/buffer_view_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALBase.td
- iree/compiler/Dialect/HAL/IR/HALOpFolders.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/HALTypes.cpp
- iree/compiler/Dialect/HAL/IR/HALTypes.h
- iree/compiler/Dialect/HAL/IR/test/allocator_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/buffer_view_folding.mlir
- iree/compiler/Dialect/HAL/IR/test/buffer_view_ops.mlir
- iree/compiler/Dialect/HAL/Transforms/test/public_abi_generation.mlir
- iree/compiler/Dialect/HAL/hal.imports.mlir
- iree/compiler/Dialect/Modules/TensorList/Conversion/test/convert_to_hal.mlir
- iree/modules/hal/hal_module.cc
Long time pending cleanup - at some point I switched the hal.allocator.compute_* to be done in IR and TODO'ed getting rid of the buffer view variants. This required changing some op attributes to operands which is a good change for generality anyway. The read/write/copy buffer ops have also been dropped as they were never implemented and staging buffers are the reliable (and more efficient) way and that's something we control on the compiler-side.
> Removing deprecated runtime HAL exports and canonicalizing away others.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
- mhlo.const -> const
- Enable batch_norm_inference for linalg-on-tensors pass
> Convert mhlo.const -> const when running ConvertHLOToLinalgOnTensorsPass

- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
Using heap allocations without a free leads to memory leaks. Only
stack allocations are allowed with dispatch regions on CPU side.
> Use stack allocation on CPU side for Linalg on tensors path.

- iree/compiler/Conversion/LinalgToVector/VectorizeConv.cpp
- iree/compiler/Conversion/LinalgToVector/test/vectorize_linalg_conv.mlir
The previous restriction is artificial, just to get started.
Allowing conv with output height != 1 will allow us to support
more cases.
> [codegen] Enable vectorizing convolution with output height != 1

- iree/compiler/Conversion/CodegenUtils/ForOpCanonicalization.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/forop_canonicalization.mlir
This commit adds an ad-hoc pattern to convert scf.for
loop-carried values from `vector<8xf16>` to `vector<4xf32>`
by inserting `vector.bitcast` around scf.for boundaries.
Those loop-carried values will be lowered into SPIR-V
local variables. This pattern allows packing f16 values
into f32 variables tightly so that we can generate shader
conformant SPIR-V.
> [CodeGen] Pack scf.for vector<8xf16> loop-carried values

- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
Reverse results in an iree-translate compiler crash during compilation.
> Disabling failing reverse linalg-on-tensors test.

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir
Operations like linalg.tensor_reshape and linalg.init_tensor need to
be cloned within the created dispatch region operation always. This
makes the logic of legalizing the flow.dispatch.workgroups op more
involved since it needs to account for
1) The values that are defined outside of the dispatch region needs to
account for operations that will be cloned.
2) The cloned operations need to be inserted at the point where it can
use the mapped values from within the dispatch op for its operations.
> Adapt dispatch region creation to always clone metadata-like/simple operations

- CMakeLists.txt
The upstream CMake minimum was bumped with llvm/llvm-project@afa1afd.
This allows to remove dead code setting policies to NEW, see the
upstream commit llvm/llvm-project@480643a.
> Bump CMake minimum to 3.13.4 and remove dead code

- integrations/tensorflow/.bazelrc
- integrations/tensorflow/iree_tf_compiler/BUILD
This makes it possible to build the IREE TF integrations using TF's
toolchains and RBE instance (given the appropriate permissions):
```shell
~/src/iree/integrations/tensorflow$ bazel build \
--config=rbe_linux_cuda_clang_py36 \
--config=tensorflow_testing_rbe_linux \
...
```
This allows building our TF integrations in an only moderately-absurd
amount of time on my workstation (10 minutes for a clean build):
https://source.cloud.google.com/results/invocations/6ffa186a-4b52-46c6-b49c-194281ea405d
and decently fast rebuilds (20s after `bazel clean`):
https://source.cloud.google.com/results/invocations/246478f0-5b6b-4ad3-94f8-49e7e435936e
It also works in monolithic mode (`--config=monolithic`).
This does not yet change how any CI is configured. It just makes the
configs available.
This also …
> Make IREE TF integrations use TF toolchains

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/conversion_ops.mlir
- iree/vm/bytecode_dispatch.c
- iree/vm/ops.h
- iree/vm/test/BUILD
- iree/vm/test/CMakeLists.txt
- iree/vm/test/conversion_ops.mlir
- iree/vm/test/emitc/CMakeLists.txt
- iree/vm/test/emitc/module_test.cc
Further adds tests for `vm.trunc` ops to the VM.
Co-authored-by: Marius Brehler <marius.brehler@iml.fraunhofer.de>
> Add EmitC support for conversion ops

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/VectorizeMemref.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_spirv.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/memref_vecrotization.mlir
- iree/compiler/Conversion/LinalgToVector/VectorizeConv.cpp
- iree/compiler/Conversion/LinalgToVector/test/vectorize_linalg_conv.mlir
This extends the convolution vectorization to further
allow input channel < 4, which is what we typically see
for the first convolution in vision models.
To enable lowering such vectorization to SPIR-V, we need
to add an additional pattern to scalarize the resultant
vector.transfer_read. Also we need to make sure the
`VectorizeMemref` pass does not inappropriately generate
`iree.placeholder` with `memref<... x vector<3xT>>`.
> [CodeGen] Allow vectorizing conv with input channel < 4

- iree/vm/test/arithmetic_ops_i64.mlir
Takes over the i32 tests to test the i64 integer arithmetic ops.
> Extend i64 integer arithmetic vm tests

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/hal_interface_bindings.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/hal_interface_constants.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/hal_interface_workgroup_info.mlir
This will make it possible to version the ABI independent of the lowerings.
The initial work here is strictly to refactor the accesses - future changes will
change the ABI to match that described in #3580.
Progress on #3580.
> Abstracting out LLVM HAL ABI use to HALDispatchABI utility.

- bindings/python/pyiree/rt/function_abi.cc
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/CallingConventionUtils.cpp
- iree/vm/bytecode_dispatch.c
- iree/vm/bytecode_module_benchmark.cc
- iree/vm/invocation.c
- iree/vm/module.c
- iree/vm/module.h
- iree/vm/module_abi_packing.h
- iree/vm/native_module_test.h
- iree/vm/shims.h
This makes it easier to write simple 1:1 shim functions/wrappers without needing to special case characters or void/empty args/results.
Progress on #4736.
> Swapping `[]` -> `CD` and `.` -> `_` in the VM calling convention.

- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
Dropped with commit d5219c9, but required by targets created via EmitC.
> Re-add dropped printIncludes

- integrations/tensorflow/.bazelrc
- integrations/tensorflow/iree_tf_compiler/BUILD
This breaks local Bazel builds with mysterious missing cppmap
dependency errors. It didn't break any bots because the only bot that
invokes this does so through a weird CMake wrapper that uses its own
bazelrc.
Reverts google/iree#4711
> Revert "Make IREE TF integrations use TF toolchains"

- integrations/tensorflow/iree_tf_compiler/iree-import-tflite-main.cpp
LLVM integrate removed dialect registration from the tflite import tool.
> Fixed tflite import tools dialect registration

- integrations/tensorflow/iree_tf_compiler/iree-import-tflite-main.cpp
* When this tool was first created, it didn't run any passes, and I think this is why I didn't add the CL options. Or I just forgot. Either way - fixed now.
* Fixes #4847
> Add pass manager CL options to iree-import-tflite.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/pad.mlir
- iree/compiler/Conversion/HLOToLinalg/test/pad_tensor.mlir
- iree/test/e2e/xla_ops/pad.mlir
- Lower mhlo.pad to linalg.pad_tensor
- Lower linalg.pad_tensor to fill + subview + copy
- Drop support for interior padding cases.
Fixes https://github.com/google/iree/issues/1604
This depends on https://reviews.llvm.org/D96343
> Adapt mhlo.pad lowering to Linalg on tensors.

- iree/base/CMakeLists.txt
- iree/hal/local/arena.c
- iree/modules/hal/hal_module.c
- iree/tools/iree-benchmark-module-main.cc
- iree/vm/bytecode_dispatch.c
- iree/vm/list.c
- iree/vm/list_test.cc
- iree/vm/module.h
- iree/vm/module_abi_packing.h
- iree/vm/type_def.h
The new C HAL module was the first user of this function - now there
are tests. The new shims also assumed that arguments were not retained
(as doing so requires cleanup) but the dispatch code was double-retaining
them. I'm surprised things worked as well as they did like that o_o
Fixes #4852.
Before:
After:
> Making iree_vm_list_resize work and switching ref cconv behavior

- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/test/calling_convention.mlir
Also fixes a small bug that leads to a superfluous comma in a function that takes no arguments but has a return value.
> Add test for EmitC calling convention.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/assignment_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/assignment_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/shift_ops_i64.mlir
- iree/vm/bytecode_dispatch.c
- iree/vm/bytecode_dispatch_util.h
- iree/vm/ops.h
- iree/vm/test/emitc/CMakeLists.txt
- iree/vm/test/emitc/module_test.cc
* Adds support (and tests!) to convert i64 integer arithmetics,
assignment, const and shift ops from VM to EmitC. In addition to the
`vm.module(iree-convert-vm-to-emitc` pipeline tests, this also extends
the module test (`iree-vm-ir-to-c-module`).
* Adds common ExtI64 dispatch op macros
* Refactors the bytcode dispatcher to use shared implementations
> Extend i64 VM/EmitC support

- scripts/update_op_coverage.py
These are WIP linalg on tensor tests; explicitly ignore them for now.
> [doc] Fix unrecognized tests in HLO op coverage generation

- iree/compiler/Dialect/VM/IR/BUILD
- iree/compiler/Dialect/VM/IR/CMakeLists.txt
- iree/compiler/Dialect/VM/IR/VMBase.td
- iree/compiler/Dialect/VM/IR/VMDialect.cpp
- iree/compiler/Dialect/VM/IR/VMDialect.h
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Dialect/VM/IR/VMTypes.cpp
- iree/compiler/Dialect/VM/IR/VMTypes.h
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- iree/compiler/Dialect/VM/Transforms/OrdinalAllocation.cpp
- iree/compiler/Dialect/VM/Transforms/test/ordinal_allocation.mlir
This is a follow up on #4805 and replaces the dictionary attribute with a dedicated struct attribute.
This also fixes an issue in the calculation of the module state size introduced in #4805.
> Implement custom attribute type for vm ordinal counts

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark.yml
The phone has been poked and is fixed.
Reverts https://github.com/google/iree/pull/4862
This reverts commit 646e999b1f499a26d7793d238f87d7231defa6fd.
Part of https://github.com/google/iree/issues/4861
> Revert "Disable benchmark on phone with ADB auth issues"

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/comparison_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/conversion_ops_i64.mlir
- iree/vm/bytecode_dispatch.c
- iree/vm/ops.h
- iree/vm/test/emitc/CMakeLists.txt
- iree/vm/test/emitc/module_test.cc
* Adds VM to EmitC conversions (and tests) for comparison and conversion
ops.
* Adds shared implementations and refactors the bytecode dispatcher to
use those.
> Further extend i64 VM/EmitC support

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/Transforms.cpp
- iree/compiler/Conversion/Common/Transforms.h
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
If all linalg operations are in a basic block some basic propagation
of buffers to use can allow computing the result of linalg operations
in place when converted to buffers. This eliminates majority of
intermediate stack allocations that were introduced by bufferization
for IREEs use cases.
Also adding support for lowering subtensor operation.
This enables running dot_general through linalg on tensors path.
> Avoid unnecessary intermediate memory allocation by preprocessing linalg operations.

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir
- iree/test/e2e/models/fullyconnected.mlir
Operations like linalg.tensor_reshape and linalg.fill are better
always fused into dispatch regions of their consumers since they can
be handled to become a no-op (almost) during codegen.
Also better document the current (simple) classification of linalg
operations that drives the dispatch region creation.
This change enables the use of linalg on tensors path for compiling
and execution fullyconnected.mlir.
> Make operations like linalg.tensor_reshape and linalg.fill always fuse with its consumers.

- bindings/python/pyiree/compiler2/core.py
I tried to use this matching the enum value/llvm flag value and realized it didn't work.
> Allow '-' in OutputFormat enum parsing

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/assignment_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/assignment_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/comparison_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/comparison_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/conversion_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/conversion_ops_i64.mlir
This doesn't change any functionality, but makes the generated IR much easier to read.
> Omit creation of args attribute when not necessary in emitc conversion

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
Marks the VM dialect as illegal in the VMToEmitC conversion and only
marks the VM ops as legal which are handled in the CModuleTarget.
> Explicitly mark VM dialect illegal

- iree/compiler/Conversion/LinalgToLLVM/LinalgTileAndVectorizePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/matmul_vectorization.mlir
This improves and the performance of matmuls for linalg on tensors (1.3x slower comparing to linalg-on-buffers pass)
IR snippet: https://gist.github.com/asaadaldien/efb712e4b1cc7ab4620b3a22809f0a74
This PR:
```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
BM_dot_384x128x128/process_time/real_time      0.529 ms        0.528 ms         1335
```
Baseline linalg-on-buffers:
```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations …
```
>  Add an optional promot workgroup memory to stack memory step.

- .github/workflows/lint.yml
- build_tools/bazel_to_cmake/bazel_to_cmake.py
In the normal case, this should give the user all the info they need
without spilling across their terminal. Verbosity control is still
present to allow more info when desired. In particular, I left the
GitHub action at the previous verbosity, since that's run in a
non-interactive environment.
Example output from various verbosity levels is at
https://gist.github.com/GMNGeoffrey/76c91ce79a9277ca205ac2eaedfb3fa4
Fixes https://github.com/google/iree/issues/4282
> Make bazel_to_cmake quieter by default

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
Put one template argument per line instead. Merge conflicts here are
annoying to resolve and diffs are hard to read. It's also just easier
to read this way anyway. This is commonly done upstream for the same
reasons. I wonder if we could find a clang-format option to format
template type lists one per line after they spill over.
> Disable clang-format in template type list

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/test/add.mlir
- iree/compiler/Dialect/VM/Target/C/test/calling_convention.mlir
- iree/compiler/Dialect/VM/Target/C/test/global_ops.mlir
- iree/vm/bytecode_dispatch.c
- iree/vm/ops.h
- iree/vm/test/BUILD
- iree/vm/test/CMakeLists.txt
- iree/vm/test/emitc/CMakeLists.txt
- iree/vm/test/emitc/module_test.cc
- iree/vm/test/global_ops.mlir
This adds support for int32 global ops to the c module target.
> Add support for global.i32 ops in the c module target

- iree/hal/cuda/status_util.h
`::util::Status` does not exist and this does not check for OkStatus
> Make Cuda status comment correct

- build_tools/bazel_to_cmake/bazel_to_cmake.py
- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
This reverts commit eac0c0490e52f93454c6a64460db794f8c3329a6.
This reverts commit c7d964e8d4ec5e9672db149b71f9db36b131163a.
> Use iree_cmake_extra_content to set compiler flags

- build_tools/bazel_to_cmake/bazel_to_cmake.py
* All of the BUILD files it was guarding no longer exist.
> Remove skip_bazel_to_cmake marker file support.

- docs/get_started/getting_started_android_cmake.md
Add additional host configuration flags in the getting started doc to address build errors similar to
https://github.com/google/iree/issues/4915
> Update Android cmake doc for host config options.

- build_tools/cmake/iree_check_test.cmake
- build_tools/mako/compile_android_modules.sh
- iree/compiler/Dialect/HAL/Target/LLVM/internal/AndroidLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/BUILD
- iree/compiler/Dialect/HAL/Target/LLVM/internal/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/LLVM/internal/LinkerTools.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp
- iree/tools/iree-check-module-main.cc
There's some common things between them but that's mostly incidental at
this point. Once we have some more platforms working we can see if there
are attributes/etc we can apply everywhere (ensuring they're ignored when
not used on a particular tool/etc). For now, this stuff is whack-a-mole
and having them shared makes it harder to iterate on any one target.
With this our .so's for android end up with no imports and strictly the
functions we generate - an unstripped simple_mul is <500 bytes (most of
which is the source path names and junk in .comment).
Progress on #4606 - needs testing, script updates, and checks that things
like tracy still have symbols.
> Forking UnixLinkerTool into AndroidLinkerTool.

- bindings/python/pyiree/jax/README.md
- docs/get_started/getting_started_linux_cmake.md
- docs/get_started/getting_started_riscv_cmake.md
Redo of https://github.com/google/iree/pull/4761 after GitHub silliness.
Note that the `docs/get_started/getting_started_riscv_cmake.md` changes slightly overlap with https://github.com/google/iree/pull/4940.
Fixes https://github.com/google/iree/issues/4606 (now that https://github.com/google/iree/pull/4719 is also merged)
> Update docs following LLVM AOT linker cleanup.

- iree/compiler/Dialect/HAL/Transforms/BUILD
- iree/compiler/Dialect/HAL/Transforms/CMakeLists.txt
- iree/tools/CMakeLists.txt
* Calling `registerLLVMDialectTranslation()`, added with ce85ce5, makes
a dep on MLIRTargetLLVMIR mandatory.
* With `createLowerAffinePass()` added as pass as part of db62c35, a
dependency on MLIRAffineToStandard is required.
> Add missing deps

- .github/workflows/build_package.yml
- build_tools/github_actions/build_dist.py
- configure_bazel.py
* Previously when invokved via cmake, cmake ensured that everything lined up without ambiguity, and we have lost that coupling.
* Practically, this was failing on the release CI, which only has gcc but was selecting a clang config during configure.
* Also took the chance to pin the CC/CXX vars in the action env so that it is obvious when this mismatches by looking at the configured.bazelrc file.
* Should fix #4961
* If it passes presubmit, I'll just submit to unbreak the releases and can rework later.
> Do more exotic compiler selection and pinning in configure_bazel.py.

- iree/compiler/Dialect/HAL/Target/LLVM/BUILD
- iree/compiler/Dialect/HAL/Target/LLVM/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.h
- iree/compiler/Dialect/HAL/Target/LLVM/internal/AndroidLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/BUILD
- iree/compiler/Dialect/HAL/Target/LLVM/internal/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/LLVM/internal/LinkerTools.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/WasmLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/WindowsLinkerTool.cpp
Progress on https://github.com/google/iree/issues/4019. I can generate .wasm files using `iree-translate -iree-hal-target-backends=dylib-llvm-aot -iree-llvm-target-triple=wasm32-unknown-unknown -iree-llvm-keep-linker-artifacts` and can inspect the .wasm artifacts using `wasm-decompile` and the other tools from https://github.com/WebAssembly/wabt. I haven't yet been able to actually call a function from a generated .wasm file and inspect its output though, so we could be missing some configuration.
This PR also includes some supporting changes in the other linker tools, mostly playing cross-platform development whack-a-mole until the code is robust enough. As one side effect, I can now use `UnixLinkerTool` from Windows, by passing `-iree-llvm-target-triple=x86_64-linux-gnu`, which …
> Initial WasmLinkerTool implementation and supporting cleanup.

- build_tools/bazel/iree.bazelrc
- build_tools/cmake/iree_copts.cmake
Fix release builds to build without asserts and turn off annoying
deprecation warnings.
The former is fallout from https://github.com/google/iree/pull/4836 and
the latter is something we've noticed being really annoying recently.
The setting of deprecation to no-error (explicitly inviting warning
spam) is something we seem to have inherited from Google's internal
build. My best guess is that people mostly only see these in the code
they're changing because everything is cached or something. If we want
to surface these warnings, we should set up clang-tidy. Spamming the
logs for anyone building anything in the project is not the way.
> No deprecation warnings and no release asserts

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndFusePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_gpu.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/linalg_tile_and_fuse.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/workgroup_memory_promotion.mlir
- Delete all linalg::ConvOp from the patterns in LinalgToSPIRV/
- Adapt linalg.conv tests to linalg. conv_2d_input_nhwc_filter_hwcf.
- Drop promotion support for conv_1d and conv_3d.
- Add conv_1d and conv_3d tests to convert_to_gpu.mlir
Part of https://github.com/google/iree/issues/4908
> Migrate linalg.conv to linalg.conv_nd ops in GPU pipeline

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/concatenate.mlir
- iree/compiler/Conversion/HLOToLinalg/test/subtensor_insert.mlir
- iree/test/e2e/xla_ops/concatenate.mlir
- Lowers the op to multiple subtensor_insert ops
- Add support for lowering subtensor_insert op to subview + fill/copy
- Propagate buffer uses for result tensor when the tensor is subtensor_insert
This only support static shapes for now because there are issues in builder and verifier. The canonicalize pass doesn't infer all the shapes for linalg.init_tensor and subtensor_insert. If the `linalg.init_tensor` can be created an inferred type with "OpFoldResult", we don't have to limit it to static shapes.
> Adapt mhlo.concatenate lowering to Linalg on tensors

- iree/compiler/Conversion/HLOToLinalg/test/concatenate.mlir
The printer or canonicalization pattern of subtensor_insert changed, so
it embedded constants directly if the offsets/sizes/strides are
constants.
> Fix concatenate test due to upstream change.

- bindings/python/pyiree/compiler2/xla.py
- bindings/python/tests/compiler_xla_test.py
- bindings/python/tests/testdata/generate_xla.py
- bindings/python/tests/testdata/xla_sample.hlo
- integrations/tensorflow/build_tools/bazel/iree-tf.bazelrc
- integrations/tensorflow/iree_tf_compiler/BUILD
- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
* New binary argument `--xla-format=hlo_text`
* Argument to `pyiree.compiler2.xla.compile(import_format="hlo_text")`
* It might be nice to add some hinting to eliminate the need to specify import_format. Also can probably drop text proto parsing at this point.
> Support HLO Text format for the XLA importer.

- experimental/runners/LinalgComprehensiveBufferizePass.cpp
- experimental/runners/LinalgTensorCodegenStrategy.cpp
- experimental/runners/LinalgTileToGeneric.cpp
- experimental/runners/README.md
- experimental/runners/Transforms.h
- experimental/runners/mlir-opt.cpp
- experimental/runners/test/matmul_f32_base.mlir
- experimental/runners/test/matmul_i8_i8_i32_base.mlir
- experimental/runners/test/test_matmul_f32_000.mlir
- experimental/runners/test/test_matmul_f32_000_exec.mlir
- experimental/runners/test/test_matmul_f32_001.mlir
- experimental/runners/test/test_matmul_f32_001_exec.mlir
- experimental/runners/test/test_matmul_f32_002.mlir
- experimental/runners/test/test_matmul_f32_002_exec.mlir
- experimental/runners/test/test_matmul_f32_003.mlir
- experimental/runners/test/test_matmul_f32_003_exec.mlir
experimental/runners is a sandbox for abstractions and transformations
aiming at making linalg on tensors executable end-to-end with batteries
included.
Such abstractions are staged here and aim at graduating to core once they
have matured.
Additional support should strive to be the absolute minimum set of abstractions
required to execute. For larger scale usage, proper integration into IREE
should be considered first.
Depends on LLVM @0ee4bf151c0985027e82ec0036a655d68b4d6c37.
> Create a sandbox for end-to-end linalg on tensors

- CMakeLists.txt
- docs/get_started/getting_started_linux_cmake.md
- docs/get_started/getting_started_macos_cmake.md
- docs/get_started/getting_started_windows_cmake.md
- experimental/bindings/java/build.gradle
Also don't redundantly set CMP0079. This is already done by
`cmake_minimum_required`
(https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html)
> Note supported CMake version in various places

- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
- Add llvm flags to enable/disable llvm auto vectorization and loop optimizations.
- All disabled by default only enable loop-auto-vectorize.
```
$ bech_mark_mobileber.sh --iree-llvm-loop-vectorization=false
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
BM_serving_default/process_time/real_time       1016 ms         1012 ms            1
$ bech_mark_mobileber.sh --iree-llvm-loop-vectorization=true
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations …
```
> Add LLVM flags for controlling various llvm-opt options

- experimental/runners/CMakeLists.txt
- experimental/runners/LinalgComprehensiveBufferizePass.cpp
- experimental/runners/LinalgTensorCodegenStrategy.cpp
- experimental/runners/LinalgTileToGeneric.cpp
- experimental/runners/mlir-opt.cpp
This patch adds a self-contained CMakeLists.txt to build
this mlir-opt (renamed to linalg-opt) that includes the
passes to test linalg on tensors.
TEST: Compiles
In this runners directory run,
cmake -GNinja -B build -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12
-DMLIR_DIR=<Path to MLIRConfig.cmake>
> Add CMakeLists.txt to build linalg-opt

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/test/reduce_window.mlir
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/SplitDispatchFunctionPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_gpu.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/linalg_tile_and_fuse.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/split_dispatch_function.mlir
- iree/test/e2e/xla_ops/reduce_window.mlir
- Only supports 2D NHWC pooling ops.
- Adapt tests in reduce_window.mlir to be 2D NHWC cases
- Replaces all tests in GPU pipeline with linalg_nhwc_*
This depends on https://github.com/llvm/llvm-project/commit/b47c6c686c860483e6f48f80741836ab242e4baa
> Migrate pooling ops to TC ops.

- iree/compiler/Dialect/VM/Target/C/CMakeLists.txt
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.h
- iree/compiler/Dialect/VM/Target/C/TranslationFlags.cpp
- iree/compiler/Dialect/VM/Target/C/TranslationFlags.h
- iree/compiler/Dialect/VM/Target/C/TranslationRegistration.cpp
- iree/compiler/Translation/IREEVM.cpp
This adds a command line switch to print the mixed VM / EmitC IR in the c module target. That should become handy once more logic is moved into the VM to EmitC conversion.
Depends on #5026.
> Add command line options for c module target

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
- iree/compiler/Conversion/HLOToLinalg/BUILD
- iree/compiler/Conversion/HLOToLinalg/CMakeLists.txt
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensorPasses.h
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/Passes.cpp
- iree/compiler/Conversion/HLOToLinalg/test/pad_tensor_to_tensor.mlir
- iree/compiler/Conversion/LinalgToSPIRV/VectorToGPUPass.cpp
- iree/compiler/Conversion/init_conversions.h
- iree/compiler/Dialect/Flow/IR/BUILD
- iree/compiler/Dialect/Flow/IR/CMakeLists.txt
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/IR/test/tensor_folding.mlir
- iree/compiler/Dialect/Flow/Transforms/DestructiveUpdateUtils.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
linalg.pad_tensor cannot be represented as a structured
operation. Instead it is lowered to
%b = linalg.fill(%dest, %pad_val)
%c = subtensor_insert %source into %b[%low_pad_0, %low_pad_1, ...]
This requires handling subtensor_insert when converting from tensors
to buffers. This can be done effectively only when it is possible to
do in-place updates within dispatch regions. So currently only support
this on CPU side.
> Support PadOp on Linalg on tensors.

- scripts/git/fix_copybara_export.sh
We don't want to try to create merge commits from things that don't
have the Copybara tag or are already merge commits, but we do still
want to fix submodules. Probably if it's a merge commit it shouldn't
have messed up submodules anyway, but we want to exit successfully if
it doesn't have the Copybara tag. Otherwise we will fail on every
google export (like https://github.com/google/iree/runs/2071416701).
TESTED=yolo
> Check for merge commit after checking Copybara tag

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops_i64.mlir
- iree/vm/ops.h
Allows to remove the header only implementations from `iree/vm/ops.h`.
Depends on #5026.
> Implement vm to emitc.const conversions

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/linalg_tensor_to_buffer.mlir
- iree/compiler/Conversion/HLOToLinalg/test/reduce_window.mlir
This also introduces the concept of bufferization of shape-only operand.
If an init_tensor op can not map to a buffer, a fake/temp memref will be
allocated. And we rely on later passes to delete the alloc op. This is
similar to what we did to lower mhlo.reduce_window to linalg.pooling_*.
> Adapt pooling ops lowering to Linalg on tensors.

- iree/compiler/Conversion/LinalgToSPIRV/test/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/test/CMakeLists.txt
Midair collision between https://github.com/google/iree/pull/4999
and https://github.com/google/iree/pull/5063
> Fix enforce_glob midair collision

- iree/tools/CMakeLists.txt
Required to call `mlir::registerLLVMDialectTranslation()`.
Unbreaks upgrading the IREE submodule in iree-template-cpp.
> Add missing CMake dep

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/torch_index_select.mlir
According to the documentation, the output shape is:
`params.shape[:axis] + indices.shape[batch_dims:] + params.shape[axis + 1:]`
E.g., if the varibles are:
params.shape = [16, 2, 3]
indices.shape = [16, 5]
axis = 2
batch_dims = 1
Then the output shape is `[16, 2] + [5] + [] = [16, 2, 5]`.
See https://www.tensorflow.org/api_docs/python/tf/gather for more details.
> Create InitTensorOp based on input operand shapes.

- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions2.cpp
- iree/compiler/Dialect/IREE/IR/IREEInterfaces.td
getTiedResultOperandIndices() returns indices into the full operand
range, while the underlying storage attribute expects indcies
into the operand range returned by getTiedOperandsIndexAndLength().
Also makes the doc clear.
> Use correct tied operand index when creating DispatchWorkgroupsOp

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/stream_ops.mlir
Results with tied operands won't have bindings in the descriptor
set layout. So we need to be consistent when creating push
descriptor updates.
> Skip results with tied operands when creating push descriptor updates

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
For each resultant tensor, DispatchWorkgroupsOp now can indicate
to which operand it ties to, in order to share the underlying
buffer storage. This can be used for subtensor_insert ops, where
we insert into the target tensor and also return the target
tensor as the result, which can happen as in-place update on
the buffer down the layers.
Addresses https://github.com/google/iree/issues/5042
> Tie operands and results when creating DispatchWorkgroupsOp

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/FoldTensorExtractOp.td
- iree/compiler/Conversion/LinalgToLLVM/FoldTensorExtractOpPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/test/BUILD
- iree/compiler/Conversion/LinalgToLLVM/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/test/fold_tensor_extract_op.mlir
- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir
- iree/test/e2e/linalg_tensor_ops/add.mlir
- iree/test/e2e/models/fullyconnected.mlir
- iree/test/e2e/xla_ops/constant.mlir
This PR plumbs through support for lowering small constants that are
inlined into flow.dispatch.workgroups. It requires
1) Making constants survive bufferization by using tensor_to_memref
2) On the LLVM path, this requires
a) using TensorConstantBufferization pass
b) A pass to fold away tensor.extract operations before lowering to
LLVM
3) On SPIR-V side, only need to pull in the TensorToSPIRV conversion
patterns
> Support lowering of small non-splat on Linalg on tensors path.

- experimental/runners/LinalgComprehensiveBufferizePass.cpp
- experimental/runners/test/test_dot.mlir
- experimental/runners/test/test_matmul_f32_000.mlir
- experimental/runners/test/test_matmul_f32_000_exec.mlir
- experimental/runners/test/test_matmul_f32_001.mlir
- experimental/runners/test/test_matmul_f32_002.mlir
- experimental/runners/test/test_matmul_f32_002_exec.mlir
- experimental/runners/test/test_matmul_f32_003_exec.mlir
- experimental/runners/test/test_matmul_f32_004.mlir
- experimental/runners/test/test_matmul_f32_004_exec.mlir
Also improve tests: with the landing of LLVM c86d3c1a38392d429c3038a8565df7334d2b0f5b, hoist padding is now correct
and we can generalize the tests to take non-square sizes as well as full hoisting of the padding out of the loops.
> Improve and document linalg-on-tensors sandbox bufferization

- build_tools/cmake/iree_installed_test.cmake
`TEST_TMPDIR` was being set based on an undefined variable `_NAME`,
which I guess we maybe happened to set in every invocation of this
function or something.
`WORKING_DIRECTORY` was being set twice in the invocation of `add_test`
and I think ignoring the argument being passed. It also was being set
to `CMAKE_BINARY_DIR` by default, which is different than the default
specified for `add_test`, which seemed weird, since that behavior
wasn't mentioned anywhere.
I hate CMake.
> Fix some issues in installed_test

- build_tools/mako/configuration.py
This produces more stable numbers because it can amortize overhead in batch mode.
Due to issues on Pixel 4 GPU, we can't let it run more than two seconds. Otherwise it will get killed. Thus, the batch mode is not enabled for Pixel 4 GPU.
MobileBert - CPU: ~660 ms
MobileBert - GPU: ~952 ms (unchanged)
MobileNetV2 - CPU: ~380 ms
MobileNetV2 - GPU: ~1024 ms (unchanged)
MobileBert - CPU: ~750 ms
MobileBert - GPU: ~270 ms 
MobileNetV2 - CPU: ~266 ms
MobileNetV2 - GPU:  ~55 ms
> Enable batch mode benchmarking on iree-android-benchmark

- experimental/runners/LinalgComprehensiveBufferizePass.cpp
- experimental/runners/LinalgTensorCodegenStrategy.cpp
- experimental/runners/test/test_constant.mlir
- experimental/runners/test/test_dot.mlir
- experimental/runners/test/test_matmul_f32_000.mlir
- experimental/runners/test/test_matmul_f32_001.mlir
- experimental/runners/test/test_matmul_f32_002.mlir
- experimental/runners/test/test_matmul_f32_003.mlir
- experimental/runners/test/test_matmul_f32_004.mlir
This needs a rebase on top of LLVM b661788b77e570dc82fe2f89a355713c144407f1.
Also fix the MemRef dialect introduced mismatches.
> Add support for bufferization of ConstantOp.

- .github/ISSUE_TEMPLATE/bug_report.md
Hardcode the default assignee to me and add the "help wanted" label. I
also added a note asking team members to do more specific triage
themselves. At our current volume of issues, I think I can handle this,
and I'll complain if that changes :-D
> Make it easier for external folks to file issues

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToLLVM/LLVMCodeGenOptions.cpp
- iree/compiler/Conversion/LinalgToLLVM/LLVMCodeGenOptions.h
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/UnfuseFMAOps.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/BUILD
- iree/compiler/Conversion/LinalgToLLVM/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/test/unfused_fma.mlir
- iree/compiler/Conversion/init_conversions.h
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- Creates LLVMCodeGenOptions  to configure LLVM compilation passes. its initited from llvm:opt flags.
- Overrides target specific options before translation  (e.g wasm target triggers unfuse-fma-ops pass).
> LLVMCodegenOptions with target specific overrides

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
This should hopefully avoid exhausting GPU memory while testing.
Unfortunately, it will also slow down testing. 
https://github.com/google/iree/issues/5162 for more robust handling.
> Limit CTEST_PARALLEL_LEVEL to 8 for GPU tests

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops_i64.mlir
The IR `%v1 = "emitc.const"() {value = "{0}"} : () -> !emitc.opaque<"iree_vm_ref_t">` is translated into the C snippet `iree_vm_ref_t v1 = {0};`. Further fixes VM to EmitC conversion tests.
> Add conversion for const.ref.zero to EmitC

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
Part of https://github.com/google/iree/issues/5162. Let's just try
*no* parallelism. But we can also limit to only vulkan tests, which is
about one tenth the number of tests, so this shouldn't actually slow
things down *too* much. Thanks to @phoenix-meadowlark for pointing out
that we didn't need to be running a bunch of these tests :grin:
> Limit tests and disable parallelism in integrations GPU build

- iree/compiler/Conversion/LinalgToNVVM/ConvertToNVVM.cpp
- iree/compiler/Conversion/LinalgToNVVM/Passes.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToSPIRV/test/elementwise_vectorization.mlir
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir
- iree/compiler/Dialect/HAL/Target/CUDA/BUILD
- iree/compiler/Dialect/HAL/Target/CUDA/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- iree/test/e2e/xla_ops/add.mlir
Recommit 156f0bbe972992fa48ea223d0b035cef23a03c35 after fixing the
problem with vectorization. Skip vectorization for single element tiles
to avoid problem with vector<1> not supported in SPIR-V conversion. 
Also add a test to exercise vectorization path.
> Re-commit Tile and distribute linalg.generic in DispatchLinalgOnTensors

- integrations/tensorflow/iree_tf_compiler/TF/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/FlattenTuplesInCFG.cpp
- integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TF/Passes.h
- iree/compiler/Bindings/SIP/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Conversion/StandardToFlow/ConvertStandardToFlow.cpp
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/PrePostPartitioningConversion.cpp
- iree/compiler/Dialect/Flow/Transforms/test/export_benchmark_funcs.mlir
- iree/test/e2e/models/fullyconnected.mlir
- iree/test/e2e/models/unidirectional_lstm.mlir
- iree/test/e2e/xla_ops/while.mlir
This also allows us to receive HLO in SCF form as input, similar to how
TOSA is being imported.
The current HLO->SCF pass is only partially working, though, so we'll
still be going to CFG in all but the simple case it handles. I'd still
rather be working towards SCF as input, though, and this is a fine
placeholder.
> Moving HLO tuple/control flow handling up to the TF importer.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensorPasses.h
- iree/compiler/Conversion/HLOToLinalg/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
This allows us to separate the common work (fusion, etc) from the HLO
specific work and eventually hoist HLO up and out of this pipeline.
> Moving non-HLO linalg-on-tensors passes out of the HLO helpers.

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/PrePostPartitioningConversion.cpp
We've built up enough ahead of it that it never kicks in.
> Removing the post-partitioning conversion pass as it is unused.

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
- integrations/tensorflow/iree_tf_compiler/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TF/Passes.h
- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
In https://github.com/google/iree/pull/5101 I accidentally removed
bindings/python tests from the CI because I assumed that they would be
covered not in the integrations build. It turns out that we have
tests depending on the TF integrations living under bindings/python
(gross. https://github.com/google/iree/issues/5181). So when
https://github.com/google/iree/pull/5104 moved MHLO tuple and control
flow legalization out of core, we didn't catch the test failure for
JAX.
This adds passes to convert from MHLO as produced by XLA->MHLO
translation to the form accepted by IREE. As we move more towards
making linalg on tensors our input and push more MHLO out of IREE core
the pipeline here will likely grow.
> Fix and re-enable jax testing

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/elementwise_vectorization.mlir
Core now supports vectorization with more input maps but the transfer
read lowering associated is not supported yet. We just skip
vectorization in this case.
> Add restrictions for enabling generic op vectorization.

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/TileAndVectorizeInOneWorkgroupPass.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/test/e2e/xla_ops/convolution.mlir
Supports general 2D depthwise convolution in Linalg on tensors.
Previously, only the case of channel_multiplier=1 was supported.
This sets `linalg::DepthwiseConvInputNHWCFilterHWCFOp` to be
root op. And adds an end-to-end test case.
> Plumb depthwise convolution in Linalg on tensors.

- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- iree/compiler/Translation/BUILD
- iree/compiler/Translation/CMakeLists.txt
- iree/compiler/Translation/IREEVM.cpp
- iree/compiler/Utils/BUILD
- iree/compiler/Utils/CMakeLists.txt
- iree/compiler/Utils/TracingUtils.h
Thanks to [this tip](https://discord.com/channels/689900678990135345/760577505840463893/772892255106105365) way back on Discord :D
Sample instrumented trace: 
That trace is measuring a debug compile of this model/flag combination: https://github.com/google/iree/blob/789689dd12a7d17292e2371945d72e56447f53f6/iree/test/e2e/models/CMakeLists.txt#L54-L65
> Add runtime tracing support to passes under IREE's PassManager usage.

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
This improves mobileBert by 6%
> Increase K tile size for small matrices.

- iree/compiler/Conversion/LinalgToLLVM/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/hal_interface_bindings.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/hal_interface_constants.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/hal_interface_workgroup_info.mlir
- iree/compiler/Dialect/HAL/Target/LLVM/BUILD
- iree/compiler/Dialect/HAL/Target/LLVM/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LibraryBuilder.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LibraryBuilder.h
- iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.h
- iree/compiler/Dialect/HAL/Target/LLVM/internal/AndroidLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/WasmLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/WindowsLinkerTool.cpp
- iree/hal/local/executable_library.h
- iree/hal/local/loaders/legacy_library_loader.cc
- iree/schemas/dylib_executable_def.fbs
The flatbuffers are still present (and we may always need some kind of
descriptor to help the runtime load) but all reflection is now performed
through the interface.
Fixes #3580.
> Generate and use the iree_hal_executable_library_t metadata.

- iree/compiler/Utils/TracingUtils.h
> Revise compiler tracing to enable statistics aggregation.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Target/C/CMakeLists.txt
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/test/add.mlir
- iree/compiler/Dialect/VM/Target/C/test/calling_convention.mlir
- iree/compiler/Dialect/VM/Target/C/test/control_flow.mlir
- iree/compiler/Dialect/VM/Target/C/test/global_ops.mlir
- iree/vm/BUILD
- iree/vm/CMakeLists.txt
- iree/vm/ops.h
- iree/vm/test/BUILD
- iree/vm/test/CMakeLists.txt
- iree/vm/test/arithmetic_ops.mlir
- iree/vm/test/arithmetic_ops_i64.mlir
- iree/vm/test/assignment_ops.mlir
- iree/vm/test/assignment_ops_i64.mlir
- iree/vm/test/comparison_ops_i64.mlir
- iree/vm/test/conversion_ops.mlir
- iree/vm/test/conversion_ops_i64.mlir
- iree/vm/test/emitc/CMakeLists.txt
- iree/vm/test/emitc/module_test.cc
- iree/vm/test/shift_ops.mlir
- iree/vm/test/shift_ops_i64.mlir
> Add support for control flow lowering in the VM to emitc target

- docs/developing_iree/benchmarking.md
- docs/developing_iree/developer_overview.md
- docs/get_started/getting_started_android_cmake.md
- docs/get_started/getting_started_linux_bazel.md
- docs/get_started/getting_started_linux_cmake.md
- docs/get_started/getting_started_linux_vulkan.md
- docs/get_started/getting_started_macos_bazel.md
- docs/get_started/getting_started_macos_cmake.md
- docs/get_started/getting_started_windows_bazel.md
- docs/get_started/getting_started_windows_cmake.md
- docs/get_started/getting_started_windows_vulkan.md
* Redirect `test/simple.mlir` to `test/iree-run-[module,mlir].mlir` in docs (split in https://github.com/google/iree/commit/32b3101ba74d0283b49304d1e8062ba9a2db2585, https://github.com/google/iree/issues/4667 has other ideas for how to address this)
* Use `../iree-build/` consistently in getting started linux cmake doc.
* Fix link to moved file and delete old RenderDoc instructions. (integration was dropped as part of https://github.com/google/iree/issues/4369)
Fixes https://github.com/google/iree/issues/4667
Fixes https://github.com/google/iree/issues/4704 (as filed - there are likely more outdated docs)
> Tidying up a few pages of documentation.

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
If a tensor value for an operand is coming from a read-only tensor,
then the buffer used for the result can be an alias of that used for
the operand since all values derived from a "read-only" tensor is
never written to within the dispatch region.
Fixes #5206
> Avoid allocating temporary buffer for tensors derived from read-only tensors

- build_tools/cmake/build_docs.sh
- scripts/prepare_doc_publication.py
Fixes https://github.com/google/iree/issues/5124
* Set utf8 encoding explicitly for doc file read/write.
* Wrap IR snippet code blocks in raw/endraw tags.
> Fix doc publication by escaping our IR snippets in markdown.

- build_tools/bazel/iree.bazelrc
- configure_bazel.py
make
```
bazel build //iree/...
```
work on both macOS x86_64 and arm64 machine
1. use `macos_clang` in configure_bazel.py, so that there will be `build --config=macos_clang` in `configured.bazelrc` after running `python configure_bazel.py`
2. make iree/tools/utils/ build by per_file_opt `-Wno-range-loop-analysis`
> make bazel build on macOS work again

- iree/base/internal/dynamic_library_win32.c
- iree/base/internal/file_io.cc
- iree/hal/local/loaders/legacy_library_loader.c
- iree/tools/utils/vm_util.cc
This gets us per-tile statistics for llvm aot functions in instrumentation mode:
> Fixing tracing on Windows and improving the dylib tracing statistics.

- iree/base/api.c
Using unbalanced malloc + system allocator free was breaking tracy.
> Fixing status allocation to use the system allocator.

- bindings/python/iree/runtime/CMakeLists.txt
- bindings/python/iree/runtime/function_abi.cc
- bindings/python/iree/runtime/host_types.cc
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- iree/hal/vulkan/BUILD
- iree/hal/vulkan/CMakeLists.txt
- iree/hal/vulkan/util/BUILD
- iree/hal/vulkan/util/CMakeLists.txt
- iree/hal/vulkan/util/intrusive_list.h
- iree/hal/vulkan/util/intrusive_list_unique_ptr_test.cc
- iree/hal/vulkan/vulkan_device.cc
- iree/modules/vmla/BUILD
- iree/modules/vmla/CMakeLists.txt
- iree/modules/vmla/op_kernels_ruy.h
We use `std::make_unique` throughout the project. If we needed compatibility with older compilers, we could switch to `absl::make_unique` ([source](https://github.com/abseil/abseil-cpp/blob/9fde5a6eb081ea080f5aa895102a9154c3a2d09f/absl/memory/memory.h#L96-L103)) or add our own implementation without a dep on abseil (see https://github.com/google/iree/issues/3848).
> Replace remaining uses of absl::make_unique with std::make_unique.

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
In general the operations cloned into a dispatch region could form a
DAG. These operations have to be cloned while keeping the order
amongst them consistent to not violate use-def chains. This changes
adds a method to clone the operations in the right order. Also cleans
up the dispatch region creation code.
Fixes #5151.
> Fix operation ordering issue during inlining of operations into dispatch region

- iree/vm/ref.c
When moving the target must be released regardless of whether the pointers
match in order to keep things balanced. This could happen in cases where
a register contained a ref ptr and a function call returned the same
pointer with the move bit set, leaking the release and failing to clobber.
Fixes #5141.
> Removing a sketchy check that was preventing releases of ref ptrs.

- iree/hal/command_buffer.c
- iree/hal/command_buffer.h
- iree/hal/cts/command_buffer_test.cc
- iree/hal/cts/event_test.cc
- iree/hal/cts/semaphore_submission_test.cc
- iree/hal/cuda/cuda_device.c
- iree/hal/cuda/graph_command_buffer.c
- iree/hal/cuda/graph_command_buffer.h
- iree/hal/device.c
- iree/hal/device.h
- iree/hal/local/task_command_buffer.c
- iree/hal/local/task_command_buffer.h
- iree/hal/local/task_device.c
- iree/hal/vulkan/direct_command_buffer.cc
- iree/hal/vulkan/direct_command_buffer.h
- iree/hal/vulkan/vulkan_device.cc
- iree/modules/hal/hal_module.c
This is needed for the CPU backend and vulkan tracing. It's a somewhat
unfortunate dependency issue and ideally we wouldn't need to track the
queue during recording however for one shot recordings we know at
compile-time what queue a stream will be submitted to. We can always
change the behavior to ignore/treat as suggestion the affinity when
recording reusable command buffers.
> Adding command buffer queue affinity.

- iree/vm/list.c
This prevents bad push behavior leading to many reallocs.
Before:
After:
> Changing iree_vm_list_resize to grow by 2x.

- iree/base/tracing.h
- iree/hal/vulkan/vma_buffer.cc
This does not match the amount of memory allocated from Vulkan itself as
VMA does magic. There may be ways of inserting ourselves between VMA and
Vulkan to more easily see what it's doing, but this at least gets us into
the ballpark of what we are requesting.
The allocations show under the "VMA" pool in the memory tool:
The addresses are meaningless, unfortunately, but size/timing/callstacks are all valid.
> Add tracing to allocations made from VMA.

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
numParrallelLoops -> numParallelLoops
> [NFC] Fix typos in variable names.

- iree/compiler/Dialect/HAL/Target/LLVM/internal/WasmLinkerTool.cpp
Sanity checked that generated .wasm/.wat files have exported functions in them with names that look about right, but didn't test fully.
> Set wasm-export-name attributes on exported functions again.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
This dramatically reduces the lifetime of the clones.
Fixes #5291.
> Insert clones prior to mutation and not where it originates.

- iree/hal/vulkan/BUILD
- iree/hal/vulkan/CMakeLists.txt
- iree/hal/vulkan/api.h
- iree/hal/vulkan/command_queue.h
- iree/hal/vulkan/direct_command_buffer.cc
- iree/hal/vulkan/direct_command_buffer.h
- iree/hal/vulkan/direct_command_queue.cc
- iree/hal/vulkan/direct_command_queue.h
- iree/hal/vulkan/dynamic_symbol_tables.h
- iree/hal/vulkan/extensibility_util.cc
- iree/hal/vulkan/extensibility_util.h
- iree/hal/vulkan/native_executable.cc
- iree/hal/vulkan/native_executable.h
- iree/hal/vulkan/registration/driver_module.cc
- iree/hal/vulkan/serializing_command_queue.cc
- iree/hal/vulkan/serializing_command_queue.h
- iree/hal/vulkan/tracing.cc
- iree/hal/vulkan/tracing.h
- iree/hal/vulkan/vulkan_device.cc
This is heavily inspired by the upstream TracyVulkan.hpp and
https://nikitablack.github.io/post/how_to_use_vulkan_timestamp_queries/.
Significant reworking was done to better support incremental collection,
use host query reset when available (extension or vulkan 1.2), and use
external source locations so we can provide the original executable
information.
This is enabled by default when IREE tracing is enabled but can be turned
off with `--vulkan_tracing=false`.
Only tested on Windows - there may be some timestamp mapping required on
linux/android where VK_TIME_DOMAIN_CLOCK_MONOTONIC_EXT is present. There
are likely corner cases with exhausted buffers but since this is a
debug-only codepath the worst that will happen is that the trace gets
corrupted.
Each Vulkan queue will appear as a …
> Implementing Vulkan dispatch tracing.

- build_tools/mako/config/mobilenet-v2-pixel4.config
- build_tools/mako/config/mobilenet-v2-s20.config
- build_tools/mako/configuration.py
Add Linalg on tensors path to Mako benchmarks.
GPU target is only added to S20, and CPU target is added to both S20 and Pixel 4.
> Add new metrics to MobileNetV2 benchmarks.

- integrations/tensorflow/iree_tf_compiler/TF/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TF/Passes.h
- integrations/tensorflow/iree_tf_compiler/TF/StripAsserts.cpp
- integrations/tensorflow/iree_tf_compiler/TF/test/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/test/strip_asserts.mlir
- integrations/tensorflow/iree_tf_compiler/dialect/tf_tensorlist/conversion/convert_tf_to_tf_tensorlist.cc
- integrations/tensorflow/iree_tf_compiler/dialect/tf_tensorlist/conversion/test/convert_tf_to_tf_tensorlist.mlir
* Both issues found when porting a non-trivial model.
* We may eventually want to do something with the asserts, but between IREE missing functionality to implement them properly and my observation that they are often incidental in TF programs (i.e. TF has no global control for them so it is down to the whims of library and model authors), stripping is likely a good default, even if we had good support for them.
* Should fix #5290 and #4865
> Add StripAsserts pass and handle tf.Identity ops on tensor lists.

- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertBufferOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/buffer_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/constant_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/test/buffer_ops.mlir
- iree/compiler/Dialect/HAL/hal.imports.mlir
- iree/modules/hal/exports.inl
- iree/modules/hal/hal_module.c
Neither are used anymore (and should never be). The implementation of these relies on host-visible memory that may not be available on all backends - and even if it was may incur significant performance penalties (metal needs to dispatch command buffers, vulkan requires HOST_VISIBLE mappings from limited memory pools, etc). It'd be nice to remove these from the HAL API too but there are legit uses and it's easier to diagnose user C code calling into C APIs than it is compiler output.
> Removing hal.buffer.fill and hal.buffer.copy.

- iree/compiler/Conversion/CodegenUtils/FunctionUtils.cpp
- iree/compiler/Conversion/CodegenUtils/FunctionUtils.h
- iree/compiler/Conversion/LinalgToLLVM/MaterializeCPULaunchConfigurationPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/CodeGenOptionUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/CodeGenOptionUtils.h
- iree/compiler/Conversion/LinalgToSPIRV/ConcretizeTileAmongWorkgroupsPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/LinalgTileAndDistributePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/TileAndVectorizeInOneWorkgroupPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/BUILD
- iree/compiler/Conversion/LinalgToSPIRV/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToSPIRV/test/concretize_tile_among_workgroups.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/concretize_tile_among_workgroups_dynamic.mlir
The refactoring silos everything required for removing unit-trip loop
counts under a flag with future changes trying to use the affine min
canonicalization without removing the loop itself. Goal is to verify
performance overhead that keeping the unit loop around adds.
Lot of the complication in this pass was introduced to get the types
of the outputs and inputs in this pass and propogating that
information to the launch configuration computation. Instead use of
the ViewOpInterface allows the operation itself to get the types of
the untiled operands using a simple traversal. Cleans up the pass
quite a bit.
Also cleanup some of the command line options handling in
configuration computation, i.e. override the default configuration
picked using the tiles sizes/workgroup sizes specified on …
> NFC: Cleanup ConcretizeTileAmongstWorkgroupsPass.

- iree/modules/vmla/op_kernels_generic.h
Addressing a performance regression introduced by https://github.com/google/iree/pull/5302
> Patch VMLA performance by reserving vector size before pushing to it.

- build_tools/mako/config/mobile-bert-f16-s20.config
- build_tools/mako/configuration.py
This only runs on S20 GPU. The batch_size=1 because the current benchmarking mechanism does not reflect real performance. See https://github.com/google/iree/issues/5248
> Add mobile-bert f16 version to Mako benchmark.

- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/compiler/Dialect/Flow/Transforms/test/hlo_to_hlo_preprocessing.mlir
The padding attribute can be extracted if all the dilation values are 1
or not set.
> Fix bugs in ExtractReduceWindowOpPaddingAttributes.

- build_tools/mako/configuration.py
See https://github.com/google/iree/pull/5282 for more details.
The Linalg on tensors path should work with `-iree-spirv-enable-vectorization`, also added the forgotten flag.
> Fix benchmarking MobileNetV2 on S20 GPU in Linalg on tensor path.

- iree/hal/vulkan/vulkan_device.cc
More fallout from https://github.com/google/iree/pull/5302 :/
Actually caught by validation layer warnings about `pQueuePriorities` being null when it must not be.
In debug builds, this incorrect use of references sometimes allocated crazy amounts of memory by using uninitialized memory as the size to resize to... ouch.
> Fix vulkan_device struct manipulation issue with std::vector.

- integrations/tensorflow/e2e/keras/applications/BUILD
- integrations/tensorflow/e2e/keras/applications/CMakeLists.txt
More discussions in https://github.com/google/iree/issues/5268.
Disable it for now to avoid hiding other failures.
> [vulkan] Disable ResNet50 test failing on NVIDIA GPUs

- experimental/bindings/java/com/google/iree/native/context_wrapper.cc
Remove an extra comma that jumped in due to bad autoformatting 😞
> Remove extra comma from context_wrapper.cc

- bindings/python/iree/compiler/core.py
- bindings/python/iree/compiler/tf.py
- bindings/python/iree/compiler/tflite.py
- bindings/python/iree/compiler/xla.py
- bindings/python/tests/compiler_tf_test.py
- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-tf-import-main.cpp
- Update `iree-import-*` to use `--mlir-print-op-generic` and `--mlir-print-debuginfo` to control formatting and debuginfo.
- Update the python bindings to control these via `CompilerOptions.output_generic_mlir=False` and `CompilerOptions.output_mlir_debuginfo=True`.
- Small changes for formatting consistency between `core.py`, `tf.py` `xla.py` and `tflite.py`.
> Control TF MLIR print options via flags

- integrations/tensorflow/e2e/keras/applications/BUILD
- integrations/tensorflow/e2e/keras/applications/CMakeLists.txt
- iree/hal/vulkan/vma_allocator.cc
- iree/test/e2e/models/BUILD
- iree/test/e2e/models/CMakeLists.txt
After removing copy/fill from the compiler the only users are now C code
that can be easily changed to do the right thing.
Fixes #5268.
> Removing hack that forced all Vulkan buffers to be host-visible.

- iree/samples/simple_embedding/BUILD
- iree/samples/simple_embedding/CMakeLists.txt
- iree/samples/simple_embedding/simple_embedding_test.cc
1. VMLA is going to be deprecated.
2. The flow pipeline will be different between VMLA and Vulkan. One will
go with legacy path, and another will go with `iree-flow-dispatch-linalg-on-tensors`
Fixes https://github.com/google/iree/issues/5373
> Switch simple_embeddding to test on DyLib + Vulkan

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
It shouldn't be needed there as buffers are allocated top-down.
> Removes tied transient buffer assignment propagation.

- iree/compiler/Dialect/Flow/Conversion/TypeConverter.cpp
- iree/compiler/Dialect/Flow/Transforms/test/legalize_input_types.mlir
Although mhlo.constant can take unsigned integers, std.constant requires integer result types to be signless.
Legalize all to i32 for consistency, and it will make things easier. E.g., we do not have to handle lowering mhlo.constant on ui64 to
std.constant.
Part of https://github.com/google/iree/issues/5383
> Legalize ui64 to i32 in Flow type converter

- iree/compiler/Conversion/LinalgToLLVM/LinalgTileAndVectorizePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/MaterializeCPULaunchConfigurationPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- Move materlialize configs to be the first thing to run.
- Move distributed affine.min and other canoncalization passes to run as
post materialization step.
Depends on #5369
> MaterializeCPULaunch configurations before bufferization

- iree/compiler/Conversion/HLOToLinalg/FusionOfTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
The upstream fusion pass is greedy. It will fuse two operations based
only on whether they can be fused or not. This means there are cases
where operations are fused even if the original producer has other
uses that make the original producer non-dead. The side-effect is that
you end up with cases where the same computation is done many times
using multiple generic/indexed_generic operation.
It also has the side-effect of
1) Increasing the number of arguments to the dispatch region.
2) Increasing life-times of tensors.
3) Make dispatch regions non-dedupable.
Also add pass-statistics to `DispatchLinalgOnTensors` to get the number of dispatch regions created.
> Limit fusion of linalg.generic/indexed_generic ops to avoid redundant computation

- iree/compiler/Conversion/LinalgToLLVM/LLVMCodeGenOptions.cpp
- iree/compiler/Conversion/LinalgToLLVM/LLVMCodeGenOptions.h
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/IR/test/BUILD
- iree/compiler/Dialect/Flow/IR/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/IR/test/dispatch_tensor_folding.mlir
- Adds a builder to `dispatch.tensor.load` to accept mixedOperands.
- Canonicalizes `dispatch.tensor.load` operands with upstream pattern.
> Canonicalizations for dispatch.tensor.load

- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
The class name of the pass should end with `Pass`, and `createXXXPass`
should match the filename.
> [NFC] Make HLOToHLOPreprocessing pass follow naming convention.

- iree/compiler/Dialect/HAL/Transforms/InlineDeviceSwitches.cpp
- iree/compiler/Dialect/IREE/IR/IREEOps.td
- iree/compiler/Dialect/VM/Conversion/IREEToVM/ConvertIREEToVM.cpp
- iree/compiler/Dialect/VM/Conversion/IREEToVM/test/hint_ops.mlir
Much more useful message at runtime when running with a mismatched
compilation target and runtime support.
> Adding an error message to iree.unreachable.

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/BUILD
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/CMakeLists.txt
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/stream_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALOpFolders.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/test/allocator_op_folding.mlir
- iree/compiler/Dialect/HAL/IR/test/allocator_ops.mlir
- iree/compiler/Dialect/HAL/Transforms/BUILD
- iree/compiler/Dialect/HAL/Transforms/CMakeLists.txt
- iree/compiler/Dialect/HAL/Transforms/PackAllocations.cpp
- iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- iree/compiler/Dialect/HAL/Transforms/Passes.h
- iree/compiler/Dialect/HAL/Transforms/test/BUILD
- iree/compiler/Dialect/HAL/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/HAL/Transforms/test/pack_allocations.mlir
- iree/compiler/Dialect/HAL/Utils/TypeUtils.cpp
- iree/compiler/Dialect/HAL/Utils/TypeUtils.h
Transient buffers used within a stream are now analyzed for liveness ranges and structured into a `hal.allocator.pack` op that computes offsets and a total length that minimizes the peak memory consumption of all of the buffers. This `hal.allocator.pack` op supports both static and dynamic sizes and is currently performing the same logic tflite is using as a baseline.
Though now all transients end up in the same storage buffer at runtime we are still binding each transient tensor uniquely to avoid non-zero binding offsets inside of executables. Future changes will combine bindings in the `-iree-hal-materialize-interfaces2` pass such that all transients share a single binding.
This was the lowest hanging fruit for allocation and dramatically drops the number of allocations we perform and …
> Adding simple transient buffer packing.

- iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/VectorizeMemref.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_spirv.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/memref_vecrotization.mlir
This pattern was originally placed in ConvertToSPIRVPass, where
we generate mixed MemRef and SPIR-V ops. Moving it earlier to
after MemRef vectorization and let it generate pure vector ops.
This is a better layering.
This addresses the failure [here](https://buildkite.com/iree/iree-android-benchmark/builds/2281#86930fce-a0f0-4fc7-8e74-e85e028345c8).
> [spirv] Move vector.transfer_read scalarization earlier

- build_tools/mako/configuration.py
We set Linalg on tensors path pipeline by default, so the configurations
should map to Linalg on tensors.
Part of https://github.com/google/iree/issues/5443
> Fix benchmark configuration to Linalg on tensors setting.

- iree/modules/strings/BUILD
- iree/modules/strings/CMakeLists.txt
- iree/modules/tensorlist/BUILD
- iree/modules/tensorlist/CMakeLists.txt
- iree/samples/custom_modules/BUILD
- iree/samples/custom_modules/CMakeLists.txt
VMLA is going to be deprecated, so the PR uses dylib-llvm-aot instead.
Fixes https://github.com/google/iree/issues/5449
> Speicify -iree-hal-target-backends in some iree_bytecode_module targets

- iree/base/api.c
iree_status_to_string needs to send the "buffer_length + 1" capacity to
the underlying snprintf to account for the terminating null charactor.
Without it, the last charactor will get dropped.
> Fix the last charactor drop in iree_status_to_string

- build_tools/mako/configuration.py
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_elementwise.mlir
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_fusion.mlir
To use tile+distribute the tile size configuration needs to be selected so as to not have significant perf regressions.
> Disable tile+distribute for elementwise operations due to regressions on CPU

- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_gpu.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/convert_to_spirv.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/memref_vecrotization.mlir
This is a step towards killing `iree.placeholder`. Along the way,
also trimmed `spv.target_env` a bit.
> [spirv] NFC: replace PlaceholderOp with InterfaceSubspanOp

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
This reverts https://github.com/google/iree/pull/5163 and
https://github.com/google/iree/pull/5166 as now buffer usage
is improved on Vulkan.
Related to https://github.com/google/iree/issues/5162
> [ci] Allow parallel testing on NVIDIA GPUs

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
Removing this attribute allows deduping executables to kick in.
> Remove attribute that is pass internal.

- iree/task/task.c
Right shift by >=32 bits requires the input is 64-bit.
> Fix task.c failure on 32-bit systems.

- iree/hal/local/loaders/BUILD
- iree/hal/local/loaders/CMakeLists.txt
- iree/hal/local/loaders/static_library_loader.c
- iree/hal/local/loaders/static_library_loader.h
This allows applications to inject a set of static libraries that can be resolved at runtime by name. This only includes the runtime portion: there's nothing in the compiler actually generating static libraries yet.
Future improvements to the driver API as part of #4298 will make it easier to inject these loaders. For now an application would need to duplicate this code (touching internals they should not) in order to supply the loader:
https://github.com/google/iree/blob/6ef847398348eb967063f019de73fb6d0e40f9eb/iree/hal/dylib/registration/driver_module.cc#L80
Fixes #4679.
> Adding a static library loader.

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
I'm suspicious that this is the proximate cause of crashes we're seeing
while destroying the Vulkan device. We think
https://github.com/google/iree/issues/2659 and
https://github.com/google/iree/issues/2900 are the root cause, but
reverting for now to try to get us back to green.
Example failure, starting at the PR being reverted:
https://source.cloud.google.com/results/invocations/a3093172-ae55-43bb-956c-256bb726006f/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-turing%2Fmain/log
Reverts google/iree#5467
> Revert "[ci] Allow parallel testing on NVIDIA GPUs"

- iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/MetalSPIRV/MetalSPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/VMLA/VMLATarget.cpp
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- iree/compiler/Dialect/VM/Conversion/ImportUtils.cpp
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/ConstantEncoder.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/ConstantEncoder.h
- iree/compiler/Dialect/VM/Transforms/HoistInlinedRodata.cpp
- iree/compiler/Utils/FlatbufferUtils.cpp
- iree/compiler/Utils/FlatbufferUtils.h
This required a minor tweak to start_as_root the flatbuffer root tables
prior to recording any data. This was discovered thanks to the gracious
help (and patience) of of the flatcc author:
https://github.com/dvidelabs/flatcc/issues/179
With this all of our binary blobs embedded into the flatbuffers are now
16-byte aligned with the option to tweak it further via a vm.rodata
attribute. We don't need utf8 strings to be 16-byte aligned, for example.
> Specify an alignment on `vm.rodata` and use it in flatbuffers.

- iree/compiler/Dialect/Flow/Transforms/OutlineLargeConstants.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/hal/buffer_view.h
- iree/modules/check/native_module.cc
#5493 can return the inlining behavior once we have better ringbuffer
support and can measure the benefits.
> Force all constants to be outlined and stored in the constant pool.

- iree/hal/BUILD
- iree/hal/CMakeLists.txt
- iree/hal/allocator_heap.c
- iree/hal/buffer_heap.c
- iree/hal/buffer_heap_impl.h
Halves the allocation count for buffers, keeps the handle and storage memory close by to hopefully get some caching benefits on initial use, and reduces the noise in allocation traces.
> Combining allocations of HAL heap buffer's handle and storage.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/test/tensor_folding.mlir
If the ranks mismatch, we can `return false` ealier. It would cause
crash when the rank of lhs is greater than the rnak of rhs.
> Fix rank-mismatch issue in flow.tensor.reshape folders.

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/pad_tensor_to_tensor.mlir
Currently, the mhlo.pad will be lowered to linalg.pad_tensor and then
lowered to `linalg.init_tensor + linalg.fill + subtensor_insert`. The
init_tensor op will produce a dynamic shape even if the shape is static.
This leads a `tensor.cast` op added and relies on further patterns to
fix them. This is not needed to static shape and will hit some issues
related to https://github.com/google/iree/issues/5385.
> Create ops with static shapes in PadTensorOpConversion if they're static

- scripts/git/summarize_changes.sh
A linear listing of the history including both parents of a merge
commit is confusing (especially with the default sort order). Merge
commit messages should contain the relevant summary of their commits,
and this avoids situations like
https://github.com/google/iree/pull/5526 where the synchronize
submodules commit message is listed twice.
> Use --first-parent when summarizing branch merge changes

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/stream_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALBase.td
- iree/compiler/Dialect/HAL/Transforms/MaterializeConstantPoolBuffers.cpp
- iree/hal/command_buffer.c
- iree/hal/command_buffer.h
- iree/hal/cuda/graph_command_buffer.c
- iree/hal/device.c
- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
- iree/hal/local/inline_command_buffer.c
- iree/hal/local/inline_command_buffer.h
- iree/hal/local/local_executable.c
- iree/hal/local/local_executable.h
- iree/hal/local/task_command_buffer.c
- iree/hal/vulkan/direct_command_buffer.cc
Adds the `IREE_HAL_COMMAND_BUFFER_MODE_ALLOW_INLINE_EXECUTION` mode to the HAL API.
This information can be useful for just about any backend (not just local single-threaded CPU) and it's carefully defined here to allow us to use it in remote/sandbox, async accelerator, and the task system backends as well. The intent is that future compiler passes that introduce asynchronous overlapping execution will be optional and when disabled all command buffers can carry this flag (or have an alternate code path generated for them).
To test this I've added `iree_hal_inline_command_buffer_t` - a simple command buffer that just executes as it records and does not persist the recorded commands. This can be used for one-shot primary command buffers in the task system when we start to use secondary …
> Adding inline command buffers to the HAL API and a basic implementation.

- iree/base/api.h
- iree/hal/cts/command_buffer_test.cc
- iree/hal/cts/cts_test_base.h
- iree/hal/cts/event_test.cc
- iree/hal/cts/semaphore_submission_test.cc
- iree/hal/cts/semaphore_test.cc
- iree/hal/device.h
- iree/hal/drivers/BUILD
- iree/hal/drivers/CMakeLists.txt
- iree/hal/drivers/init.c
- iree/hal/dylib/registration/BUILD
- iree/hal/dylib/registration/CMakeLists.txt
- iree/hal/dylib/registration/driver_module_sync.c
- iree/hal/dylib/registration/driver_module_sync.h
- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
- iree/hal/local/executable_library.h
- iree/hal/local/sync_device.c
- iree/hal/local/sync_device.h
- iree/hal/local/sync_driver.c
- iree/hal/local/sync_driver.h
- iree/hal/local/sync_event.c
- iree/hal/local/sync_event.h
- iree/hal/local/sync_semaphore.c
- iree/hal/local/sync_semaphore.h
- iree/hal/local/task_semaphore.c
- iree/hal/semaphore.h
This is mostly just the plumbing to enable #4680 by defining a new `dylib-sync` runtime driver (pending #4298 to cleanup drivers).
This driver does not support recording/replaying command buffers and has some gotchas with semaphores (no deadline waits, probably corner cases for things not covered in the CTS, etc). It should get us something that builds easier on tiny systems, though.
This uses `iree/base/synchronization.h` for the semaphore implementation. The intent is that for bare-metal systems we can implement a version of `iree/base/synchronization.h` observing the specific requirements of the platform while still preserving the semaphore semantics - it's still useful to use this driver with systems with multiple threads (lots of dual-core MCUs/MPUs) or to enable pipelining. Systems …
> Adding experimental synchronous executor using inline command buffers.

- iree/base/api.h
- iree/base/attributes.h
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/hal/local/executable_library.h
- iree/modules/hal/BUILD
- iree/modules/hal/CMakeLists.txt
- iree/modules/hal/hal_module.c
- iree/samples/emitc_modules/CMakeLists.txt
- iree/vm/BUILD
- iree/vm/CMakeLists.txt
- iree/vm/api.h
- iree/vm/shims.c
- iree/vm/shims.h
- iree/vm/shims_emitc.h
- iree/vm/test/emitc/CMakeLists.txt
These will be reused by the VMVX module. For now I moved the existing shims that emitc is using to prevent that from breaking until we can combine them.
> Moving the HAL module shims into `iree/vm/`.

- iree/hal/local/elf/elf_module.c
Otherwise we get an error about narrowing from 64 to 32 bit on 32-bit
architectures. This wasn't caught because we don't have any tests of
32-bit architectures in OSS (but we do internally at Google).
```
iree/hal/local/elf/elf_module.c:157:11: error: format specifies type
'size_t' (aka 'unsigned int') but the argument has type
'iree_elf64_off_t' (aka 'unsigned long long') [-Werror,-Wformat]
phdr->p_offset, phdr->p_offset + phdr->p_filesz,
```
So longer term fixes are to add a 32-bit build bot and create format
specifiers for IREE's types (so we don't just have to widen
everywhere), but this unblocks integration for now.
> Fix format specifiers for 32-bit architectures

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark.yml
We can see the regression on Mako webpages. It's annoying to see badges
being red because of "regressions". Turn it off for now. It will still
complain about it if it fails at other stages.
> Allow mako upload failure not to fail the Github commit.

- iree/compiler/Conversion/LinalgToSPIRV/test/split_dispatch_function.mlir
I fixed linalg.conv_2d_input_nhwc_filter_hwcf cases with 1x3x3x512xf32, 3x3x512x1xf32 -> 1x1x1x512xf32. According to the definition of linalg.conv_2d_input_nhwc_filter_hwcf, the output shape should be 1x1x1x1xf32.
> Fixed one testcase file

- iree/base/target_platform.h
This wasn't working on our internal 32-bit arm architecture for some
reason. Unlike many methods one can find on the internet, the one used
here doesn't require listing every possible architecture. It has the
disadvantage (like the one used previously) that it requires uintptr_t,
which is not technically required by the standard and it requires that
`uintptr_t` be the size of a void pointer, which is also not
technically required. Both these properties are checked at compile time
though, so if we ever have to deal with some weird architecture where
that isn't true, I guess we can find some other way.
> Fix pointer size detection

- iree/compiler/Dialect/HAL/Target/LLVM/LibraryBuilder.cpp
- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
- iree/hal/local/elf/arch.h
- iree/hal/local/elf/arch/arm_32.c
- iree/hal/local/elf/arch/arm_64.c
- iree/hal/local/elf/arch/riscv.c
- iree/hal/local/elf/arch/x86_32.c
- iree/hal/local/elf/arch/x86_64.c
- iree/hal/local/elf/arch/x86_64_msvc.asm
- iree/hal/local/elf/elf_module_test.cc
- iree/hal/local/executable_library.h
- iree/hal/local/executable_library_demo.c
- iree/hal/local/executable_library_demo.h
- iree/hal/local/executable_library_test.c
- iree/hal/local/loaders/embedded_library_loader.c
- iree/hal/local/loaders/legacy_library_loader.c
The current shared objects we produce from the LLVM AOT backend match
the same ABI as written by hand here in _demo.c.
> Adding a little demo library to show both sides of the ABI.

- iree/base/internal/flags.h
- iree/testing/BUILD
- iree/testing/CMakeLists.txt
- iree/testing/benchmark.h
- iree/testing/benchmark_full.cc
- iree/testing/benchmark_main.c
This will let us substitute other benchmarking frameworks for use on
bare-metal platforms or other places the full benchmark library can't run.
This initial pass exposes what we use in iree-benchmark-module today and
additional features can be added as needed (like range parameters).
> Defining a C-compatible benchmark header.

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
The bufferization pass on the linalg on tensors path was an arbitrary
set of methods put in place to connect linalg on tensors to the post
tile+distribute codegeneration on CPU and GPU. This PR cleans up the
logic to better handle the tensor -> memref conversion.
In particular
1) Adds an analysis step to figure out which tensors can be mapped to
the same memref object. This also provides information of what
tensors are eventually mapped to the output of the dispatch
region. In such cases, the output is used to compute the values in
place reducing the need for copies and intermediate allocations.
2) Use this analysis step to convert operations from tensors to memrefs.
3) Use the `readonly`, `readwrite` and `writeonly` attributes to avoid
copies when possible.
All of this uses logic similar …
> Rework LinalgBufferize pass.

- build_tools/cmake/iree_copts.cmake
Without it, we can see failures like:
```
CMake Error at build_tools/cmake/iree_copts.cmake:297 (string):
string sub-command REPLACE requires at least four arguments.
```
> [cmake] Add missing quote to ${CMAKE_CXX_FLAGS}

- build_tools/embed_data/build_defs.bzl
- build_tools/embed_data/generate_embed_data_main.cc
- iree/vm/bytecode_dispatch_test.cc
In C, we've got no namespaces, and in particular in Google's internal
source, something in the toolchain links in an alternative definition
for this struct which causes *extremely* confusing errors.
> Rename FileToc struct to iree_file_toc_t

- integrations/tensorflow/build_tools/testdata/generate_errors_module.py
- integrations/tensorflow/iree_tf_compiler/TF/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/Passes.h
- integrations/tensorflow/iree_tf_compiler/TF/PrettifyDebugInfo.cpp
- integrations/tensorflow/iree_tf_compiler/iree-import-tflite-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-tf-import-main.cpp
* This is a strict improvement over not having a diagnostic handler.
* Also introduces a stub pass for cleaning up TensorFlow locations but I have not yet found an algorithm I like so just leaving it as a stub for later.
* Progress on #5295
> Enable SourceMgrDiagnosticHandler in importers.

- build_tools/mako/configuration.py
It was a mistake to migrate to benchmark executables. Eventually, we
would like to have both benchmarks. One is for end-to-end, and another
is for CodeGen kernels. The PR disables batch mode because:
- There is an issue in GPU benchmarks with batch mode. See https://github.com/google/iree/issues/5248
- Make CPU and GPU benchmarks consistent. It is weird that one is in
batch mode and another is not. Plus, this can make mako tags have same
naming rule if we'd like to enable the executables benchmarks in the
future. (Otherwise, "cpu" tag would be with batch mode, and "gpu"
would not.)
note: this will introduce "regression" on Mako dashboard.
> Drop batch mode for Mako benchmarks.

- build_tools/mako/benchmark_modules_on_android.py
- build_tools/mako/compile_android_modules.py
- build_tools/mako/config/mobile-bert-pixel4.config
- build_tools/mako/config/mobile-bert-s20.config
- build_tools/mako/config/mobilenet-v2-pixel4.config
- build_tools/mako/config/mobilenet-v2-s20.config
- build_tools/mako/configuration.py
IREE recently introduced new driver `dylib-sync` which is used for
single threaded. After discussion, this should run with `taskset 80`,
and the multithreaded version should run with `taskset f0`. The PR
also makes taskset configurable.
This is a step towards https://github.com/google/iree/issues/4752
> Handle CPU single threaded with updated driver.

- CMakeLists.txt
The flag is off by default, so the runtime build will not have the
dependency of the compiler.
To use the flag, the users also need to specify the
IREE_HOST_BINARY_ROOT path or build the compiler.
> Turn off IREE_BUILD_EMBEDDING_SAMPLES

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- An alternative is to apply img2col after dispatching into workgroup tiles, but its running through multiple hops of issues related to introduced reshapes semantics.
Benchmarking resent50 (a model with lots of conv) on Pixel4:
```
BM_predict/process_time/real_time       8384 ms         8361 ms            1
```
``` …
```
> Optionally apply Conv -> Img2col transformation at the flow level

- iree/hal/local/elf/platform/generic.c
- iree/hal/local/elf/platform/linux.c
* On our GCC builds, __has_builtin appears to not be feature detecting this.
* Should fix #5617
> Enable use of __builtin_clear_cache for GCC.

- iree/compiler/Conversion/HLOToLinalg/FusionOfTensorOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/Transforms/ConvertToFlowTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/test/convert_to_flow_tensor_ops.mlir
The following operations can be lowered to `flow.tensor.` ops.
1) `linalg.tensor_reshape` -> `flow.tensor.reshape` : Once all reshapes can be folded away, the remaining reshapes only exist at the boundaries of dispatch regions. These are better off converted to `flow.tensor.reshape` so that they could become no-ops when lowered to the `hal` layer.
2) `subtensor` -> `flow.tensor.slice`. A `subtensor` operation can be lowered to a `flow.tensor.slice` operation in some cases. This can become a no-op in many cases.
3) `subtensor_insert` -> `flow.tensor.update`. A `subtensor_insert` operation can be lowered to a `flow.tensor.update` operation which will allow for doign in-place updates.
This will eliminate some dispatch regions that do not need to be created.
> Add more patterns to lower to `flow.tensor` ops

- iree/hal/local/elf/platform/apple.c
Apple doesn't document how to safely use this API so this was pieced
together from what qemu does.
Fixes #5649.
> Guessing at making MacOS happy.

- iree/hal/executable_cache.h
- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
- iree/hal/local/executable_library_benchmark.c
- iree/hal/local/loaders/BUILD
- iree/hal/local/loaders/CMakeLists.txt
- iree/hal/local/loaders/embedded_library_loader.c
- iree/testing/benchmark.h
Lots of improvements for configurability are possible; this is the bare minimum.
This tool lets you take an executable library and invoke a single entry point with a flag-defined set of parameters.
Note that it's intentionally low level: you must specify all of the push constant/binding parameters precisely as
they are expected by the executable. `iree-benchmark-module` is the user-friendly version while this favors
direct access to the executables (bypassing all of the IREE VM, HAL APIs, task system, etc).
An example flagfile:
```
--executable_format=EX_ELF
--executable_file=D:\Dev\iree\iree\hal\local\elf\testdata\simple_mul_dispatch_x86_64.so
--entry_point=0
--workgroup_count_x=1
--workgroup_count_y=1
--workgroup_count_z=1
--workgroup_size_x=1
--workgroup_size_y=1
--workgroup_size_z=1 …
```
> Adding initial executable library benchmarking tool.

- iree/compiler/Conversion/LinalgToNVVM/VectorizationPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/TileAndVectorizeInOneWorkgroupPass.cpp
Add vector transfer lowering to handle the IR generated by the vectorization after:
https://reviews.llvm.org/D101165
> Prepare handling for relaxed vectorization for SPIR-V and CUDA backends

- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.cpp
- iree/vm/bytecode_dispatch.c
- iree/vm/native_module.c
- iree/vm/ref.c
- iree/vm/ref.h
- iree/vm/test/list_ops.mlir
- iree/vm/test/list_variant_ops.mlir
> Fixing unsafe vm.list.alloc CSE and bad returns in bytecode dispatch.

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.cpp
For a given matmul shape this selects the largest integer multiple of the vector size that fits in the workgroup or L1 sizes.
Doing that there is no regression in MobileBert (because its 2^n so max is the default sizes) 
and > 2x improvement in MobileNetV2,V3
MobileNetV2:baseline
```
BM_predict/process_time/real_time        411 ms          410 ms            2
```
MobileNetV2:after
``` …
```
> Select matmul tile sizes based on static shape information

- bindings/tflite/interpreter.c
- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/base/alignment.h
- iree/base/api.h
- iree/base/attributes.h
- iree/base/config.h
- iree/base/status.c
- iree/hal/buffer.h
- iree/hal/buffer_heap.c
- iree/hal/driver_registry.c
- iree/hal/local/arena.c
- iree/hal/vulkan/descriptor_set_arena.cc
- iree/task/pool.c
- iree/vm/bytecode_dispatch.c
- iree/vm/bytecode_dispatch_util.h
- iree/vm/bytecode_module.c
- iree/vm/list.c
- iree/vm/stack.c
This follows the common technique of config.h with defaults + an
optional user config file override (this is what VMA, imgui, stb, etc use).
We may want to move some of these around or create subsystem-specific
config files but for now this should at least let us start paring things
down for tiny IREE.
> Adding an iree/base/config.h and splitting out some of iree/base/api.h.

- iree/hal/buffer_view.cc
The buffers containing the parsed tensor elements are typically
used as initial inputs and bound to pipelines in our various
command-line tools. Marking them as suitable for dispatch fixes
the Vulkan validation issue:
[ VUID-VkWriteDescriptorSet-descriptorType-00331 ]
Attempted write update to buffer descriptor failed due to:
Buffer with usage mask 0x3 being used for a descriptor update
of type VK_DESCRIPTOR_TYPE_STORAGE_BUFFER does not have
VK_BUFFER_USAGE_STORAGE_BUFFER_BIT set..
The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_STORAGE_BUFFER
or VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC, the buffer member
of each element of pBufferInfo must have been created with
VK_BUFFER_USAGE_STORAGE_BUFFER_BIT set.
> Mark the buffer created from parsing tensors as dispatchable

- iree/samples/simple_embedding/BUILD
- iree/samples/simple_embedding/CMakeLists.txt
- iree/samples/simple_embedding/simple_embedding_run.c
- iree/samples/simple_embedding/simple_embedding_run_local_sync.c
This adds `simple_embedding_run_local_sync` which is similar to
`simple_embedding_run`, but skips the driver registration and instead
directly creates a `dynlib-sync` device.
> Add simple_embedding_run_local_sync

- docs/get_started/getting_started_python.md
These instructions are taken from https://google.github.io/iree/get-started/getting-started-linux-cmake#build. If we can build the project without changing the directory it feels better in browsing source code.
> Minor change in build instructions of getting_started_python.md

- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.cpp
Otherwise very narrow matmul problems with dim < matmulVectorSize won't get vectorized.
Helps MobileNet V3:
```
BM_predict/process_time/real_time       93.1 ms         92.8 ms            7
```
```
BM_predict/process_time/real_time       76.5 ms         76.2 ms            9
```
> Tile matmul with at least matmulVectorSize

- bindings/python/iree/runtime/CMakeLists.txt
- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/hal.cc
- bindings/python/iree/runtime/hal.h
- bindings/python/iree/runtime/system_api.py
- bindings/python/iree/runtime/vm.cc
- bindings/python/iree/runtime/vm.h
* The code is much more straight-line, directly using low level VM facilities instead of indirecting through custom C++ structures. The dispatch itself is in Python but could be hoisted to C++ if it ever became a performance bottleneck (given the type manipulation and switchiness, may not be much faster).
* No tests yet and can only be triggered with modules compiled with as-yet-uncommitted flags and patches. Need to resolve the chicken-and-egg to take it further.
* Once complete, we can fully delete SIP, function_abi.[h|cc], host_type.[h|cc], and old code in system_api.py.
* Provides the bones to fix #5359 correctly (partially fixed now, will be fully fixed once the type converters are fully in place).
* Verified with manually compiled static workloads without nesting.
> Re-implements IREE function dispatch in python on top of the native ABI.

- build_tools/mako/configuration.py
First failure: https://buildkite.com/iree/iree-android-benchmark/builds/2428
```
subprocess.CalledProcessError: Command '['build-host/iree/tools/iree-translate', 'mobilenet-v2/iree_input.mlir', '--iree-mlir-to-vm-bytecode-module', '--iree-hal-target-backends=vulkan-spirv', '-o', 'mobilenet-v2_S20_vlk.vmfb', '--iree-vulkan-target-triple=valhall-g77-unknown-android10', '--iree-flow-inline-constants-max-byte-length=16', '--iree-flow-dispatch-formation-enable-operand-fusion']' returned non-zero exit status 1.
```
Tested at https://buildkite.com/iree/iree-android-benchmark/builds/2447
> Disable mobilenet-v2 benchmark while it fails to compile.

- iree/compiler/Dialect/Shape/Conversion/ConvertShapeToShapex.cpp
- iree/compiler/Dialect/Shape/Conversion/test/shape_to_shapex.mlir
Add missing `shape` to `shapex` conversion for `from_extent_tensor`. Also, add test for `broadcast` operation on ranked extent tensors.
> [MLIR][IREE] Add `shape.from_extent_tensor` to `shapex.*` conversion

- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertExecutableOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/MetalSPIRV/MetalSPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/VMLA/VMLATarget.cpp
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.h
- iree/compiler/Dialect/VM/Target/Bytecode/ConstantEncoder.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/ConstantEncoder.h
- iree/compiler/Dialect/VM/Target/Bytecode/TranslationFlags.cpp
- iree/compiler/Utils/FlatbufferUtils.h
This allows .vmfb outputs to be opened/unzipped as if they were .zip files.
The behavior isn't required by the runtime and this is just to make getting binary blobs out of the flatbuffers easier. Release outputs that would strip debug symbols would likely also want to disable this as it adds a few KB.
Specifically, it's now possible to extract the executable binaries in ELF format. SPIR-V and PTX still have flatbuffer wrappers so they aren't directly usable yet but that will be fixed in the future.
> Adding `-iree-vm-emit-polyglot-zip` flag.

- scripts/check_tabs.sh
Tested:
`./scripts/check_tabs.sh "$(git rev-list --max-parents=0 HEAD)"`
AKA run on all files in the repo (that subcommand gets the first commit)
> Exclude binary files from tab checks rather than listing extensions

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/concatenate.mlir
All this does is plumb through the type converter.
Part of https://github.com/google/iree/issues/5383
> Add unsigned support for lowering mhlo concatenate and constant

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/ConvertToFlowTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/DeduplicateExecutables.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchabilityAnalysis.cpp
- iree/compiler/Dialect/Flow/Transforms/ExpandVariableDynamicDims.cpp
- iree/compiler/Dialect/Flow/Transforms/ExportBenchmarkFuncs.cpp
- iree/compiler/Dialect/Flow/Transforms/FoldCompatibleDispatchRegions.cpp
- iree/compiler/Dialect/Flow/Transforms/FormStreams.cpp
- iree/compiler/Dialect/Flow/Transforms/HLOToHLOPreprocessing.cpp
- iree/compiler/Dialect/Flow/Transforms/HoistUnstreamableOps.cpp
- iree/compiler/Dialect/Flow/Transforms/IdentifyDispatchRegions2.cpp
- iree/compiler/Dialect/Flow/Transforms/InjectDispatchTracing.cpp
- iree/compiler/Dialect/Flow/Transforms/LegalizeInputTypes.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions2.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineLargeConstants.cpp
- iree/compiler/Dialect/Flow/Transforms/PassDetail.h
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/PrePostPartitioningConversion.cpp
- iree/compiler/Dialect/Flow/Transforms/StripAndSplatConstantVariables.cpp
* Eliminates static registration from the flow dialect.
* While a good idea to do everywhere, this was done while triaging a startup crash in release mode with assertions enabled that appeared to be static initializer based (it was not - and now still happens at registration time).
* We should do this to all passes in the system eventually (but it would be nice to delete old cruft first).
> NFC: Upgrade the Flow dialect to use tablegen-based pass declarations.

- iree/compiler/Dialect/Flow/Conversion/TypeConverter.cpp
- iree/compiler/Dialect/Flow/Transforms/test/legalize_input_types.mlir
This is dangerous and not necessary. The proper fix is to add support for lowering
unsigned ints from mhlo to linalg and dropping the signedness there along with
encoding it in the operations used. I've sent patches to do this for the lowerings we
currently care about to avoid regression on ASR.
Fixes https://github.com/google/iree/issues/5383
> Don't drop signedness semantics when narrowing 64-bit ints

- build_tools/docker/cmake-riscv/Dockerfile
- build_tools/docker/manage_images.py
- build_tools/docker/prod_digests.txt
The docker image has the RISC-V crosscompile toolchain and QEMU
installed. It is used to run RISC-V CI checks.
The first PR for https://github.com/google/iree/issues/5751
> Add cmake-riscv docker image

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
- iree/compiler/Dialect/Flow/Transforms/DestructiveUpdateUtils.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/test/e2e/regression/BUILD
- iree/test/e2e/regression/CMakeLists.txt
- iree/test/e2e/regression/linalg_ops.mlir
- The dispatch region creation is updated to handle multiple operations.
- Handling multi-result operations seems to hit some issues with destructive update rewrites. Simplifying the logic used for those.
- Change the bufferization pass to handle multi-result linalg operations
- Add an e2e for codegen backends.
Fixes #5538
> Add support for compilation of Linalg ops with multiple results

- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
This fixes the %15 mobilebert perf regression cased by the follwing canonicalization:
```
%86 = vector.outerproduct %84, %85, %83 {kind = #vector.kind<add>} : vector<4xf32>, vector<4xf32>
%87 = vector.shape_cast %86 : vector<4x4xf32> to vector<1x4x4xf32>
scf.yield %87 : vector<1x4x4xf32>
```
```
%86 = vector.outerproduct %84, %85, %83 {kind = #vector.kind<add>} : vector<4xf32>, vector<4xf32>
%87 = vector.insert %86, %cst_0 [0] : vector<4x4xf32> into vector<1x4x4xf32>
scf.yield %87 : vector<1x4x4xf32>
```
While this isn't actually fixing why LLVM is generating bad code for the
snippet above, but it makes both LLVM/SPIR-V backends applies the same
canonicalization for the vector loops.
> Applies ForOpCanonicalizationPass after LinalgTileAndVectorizeWorkgroupsPass

- build_tools/mako/configuration.py
The current flag `iree-flow-dispatch-formation-enable-operand-fusion` fails compilation.
> Update MobileNetV2 mako compilation flags for cpu

- bindings/tflite/README.md
No diff in the rendered html. This just makes the source a bit easier to read by aligning
the columns.
> Clean up tflite docs table formatting a bit

- iree/samples/simple_embedding/BUILD
- iree/samples/simple_embedding/CMakeLists.txt
Fixes `compiler limit: string exceeds 65535 bytes in length` on MSVC.
> Add -iree-llvm-debug-symbols=false to simple_embedding sample.

- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
This is the output we need to repro in IREE core and matches the behavior of the other
import tools:
https://github.com/google/iree/blob/5f36903a3638424d68b5acbba611988e4b17320e/integrations/tensorflow/iree_tf_compiler/iree-tf-import-main.cpp#L227-L240
Maybe saving the the temp input from before the pipeline would also be useful, as we
do for for tf-import:
https://github.com/google/iree/blob/5f36903a3638424d68b5acbba611988e4b17320e/integrations/tensorflow/iree_tf_compiler/iree-tf-import-main.cpp#L215-L217
But that's a separate change :-)
> Save IREE input for XLA import after running passes

- build_tools/bazel/iree.bazelrc
- build_tools/cmake/iree_copts.cmake
This flag is enabled by default
(https://clang.llvm.org/docs/DiagnosticsReference.html#wincompatible-pointer-types).
The reason we only hit it on integration into google source
is that we don't have a 32-bit build in OSS (yet).
Reverts google/iree#5676
> Revert "Enabling `-Wincompatible-pointer-types` warning."

- bindings/tflite/interpreter.c
- iree/base/internal/atomics.h
- iree/compiler/Dialect/VM/IR/VMBase.td
- iree/compiler/Dialect/VM/IR/VMOpcodesCore.td
- iree/compiler/Dialect/VM/IR/VMOpcodesF32.td
- iree/compiler/Dialect/VM/IR/VMOpcodesF64.td
- iree/compiler/Dialect/VM/IR/VMOpcodesI64.td
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/schemas/bytecode_module_def.fbs
- iree/vm/BUILD
- iree/vm/CMakeLists.txt
- iree/vm/api.h
- iree/vm/buffer.c
- iree/vm/buffer.h
- iree/vm/buffer_test.cc
- iree/vm/builtin_types.c
- iree/vm/builtin_types.h
- iree/vm/bytecode_dispatch.c
- iree/vm/bytecode_module.c
- iree/vm/bytecode_module_benchmark.cc
- iree/vm/bytecode_module_benchmark.mlir
- iree/vm/generated/bytecode_op_table.h
- iree/vm/list.c
- iree/vm/list.h
- iree/vm/test/BUILD
- iree/vm/test/CMakeLists.txt
- iree/vm/test/buffer_ops.mlir
Previously the VM had a special builtin for read-only buffers and it was always just a placeholder for something more meaningful. This is the start of that. This implementation will undergo a lot of changes as VMVX is brought up but is the first wave of work to unblock that exploration.
`vm.list`/`iree_vm_list_t` are useful for storing reference-counted objects and heterogeneous element types and supports resizing, and this new `vm.buffer`/`iree_vm_buffer_t` is useful for fast access to fixed-length sets of primitive values with the ability to bitcast the storage. The buffer is access checked (preventing writes to read-only memory), origin checked (preventing inadvertent lifetime extension), bounds checked/alignment-enforced, and is a ref object like any other so that proper lifetime is …
> Generalizing the VM buffer type and adding VM buffer ops.

- iree/compiler/Conversion/Common/VectorTransferOptimization.cpp
- iree/compiler/Conversion/Common/test/BUILD
- iree/compiler/Conversion/Common/test/CMakeLists.txt
- iree/compiler/Conversion/Common/test/transpose_canonicalization.mlir
- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
- iree/compiler/Conversion/LinalgToSPIRV/TileAndVectorizeInOneWorkgroupPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/VectorToGPUPass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/pipeline_matmul_vectorization.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/tile_and_vectorize_batch_matmul.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/tile_and_vectorize_conv.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/tile_and_vectorize_matmul.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/vector_to_gpu.mlir
- iree/compiler/Conversion/LinalgToSPIRV/test/vectorize_matmul.mlir
Run vector unroll right after vectorization, that allows unrolling
transfer op before they get lowered. This way the broadcast and
transpose ops generated by lowering are already in the right vetor size.
Start using mlir core onversion for contract ops and remove our ad hoc
lowering.
> Improve the vector flow for SPIR-V codegen

- build_tools/kokoro/gcp_ubuntu/cmake/linux/riscv64/main.cfg
We missed this in https://github.com/google/iree/pull/5762 and now the Kokoro build is
failing because it can't find the config file.
> Add missing config file for riscv64 build on main branch

- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/vm.cc
- docs/developers/design_docs/function_abi.md
- integrations/tensorflow/bindings/python/iree/tf/support/module_utils.py
- integrations/tensorflow/iree_tf_compiler/TF/SavedModelToIreeABI.cpp
- integrations/tensorflow/iree_tf_compiler/TF/test/saved_model_to_iree_abi.mlir
* Add arg/return details to Python error messages.
* Also provides a no-op implementation of get_serialized_values() pending doing something better.
* Add more numpy->HAL types.
* Add VM -> numpy dtype mappings.
> Misc Python API cleanups to support native ABI uses encountered.

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
linalg.pad_tensor will be converted into:
allocation + fill + copy(src, sub_view_interior_region)
> Support linalg.pad_tensor bufferization

- .github/ISSUE_TEMPLATE/bug_report.md
- docs/developers/design_docs/hal_driver_features.md
- docs/developers/developing_iree/e2e_benchmarking.md
- docs/developers/developing_iree/testing_guide.md
- integrations/tensorflow/e2e/README.md
- iree/test/e2e/tosa_ops/BUILD
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/partial/BUILD
- scripts/get_e2e_artifacts.py
- scripts/git/update_to_llvm_syncpoint.py
Updated some links to point to the new website (GitHub Pages) and others to point to pages directly on GitHub that are no longer published.
> Remap hyperlinks following website migration.

- build_tools/cmake/iree_cc_binary.cmake
- build_tools/cmake/iree_cc_test.cmake
- iree/base/testing/CMakeLists.txt
- iree/tools/CMakeLists.txt
This is never used to set except to set the binary name explicitly to the default, it's not
supported by bazel_to_cmake, and it's not even parsed as an argument in the case of
`iree_cc_test`.
> Remove OUT option from iree_cc_[binary/test]

- bindings/python/iree/compiler/core.py
* This eliminates a huge amount of the spew that comes from usage of the Python API.
* For most of these that I have seen, additional triage would be needed anyway, and the excess printing doesn't actually help.
* Related to #5295
> Disable printing op on diagnostics in user tools by default.

- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/vm.cc
- bindings/python/iree/runtime/vm.h
- integrations/tensorflow/iree_tf_compiler/TF/SavedModelToIreeABI.cpp
* IREE's compiler still has trouble compiling forms that return structured results, so some hacked tests were used to verify.
* Once compiler support is complete, existing tests should be sufficient.
* Keyword argument support was not fully tested because existing tests for it also return structured outputs.
* Also fixes indexing mismatch in null padding of TF nested arguments.
> Implement python argument decoding for list/tuple/dict nests.

- iree/base/internal/BUILD
- iree/base/internal/CMakeLists.txt
- iree/base/internal/inline_array.h
- iree/hal/vulkan/direct_command_buffer.cc
- iree/hal/vulkan/native_executable.cc
- iree/modules/hal/hal_module.c
The absl::InlinedVector->std::vector change introduced an alloc per barrier recorded. This adds a fixed-size stack/heap array (as that's our common usage of these stack vectors) and returns to 0 allocations during command buffer recording in the steady state.
> Replacing std::vector use with a simple stack/heap allocated array.

- iree/samples/simple_embedding/BUILD
- iree/samples/simple_embedding/CMakeLists.txt
Re-enables building IREE with VMLA only.
> Move check for backends used in simple_embedding

- build_tools/bazel/iree_check_test.bzl
- build_tools/cmake/iree_check_test.cmake
Following https://github.com/google/iree/pull/5806
See https://gist.github.com/ScottTodd/548adea41b07002b03dadedb24a3ffdc for sample build output when several generated targets fail compilation before/after this change.
> Disable printing op on diagnostics in iree_check_test targets.

- docs/website/overrides/404.html
In https://github.com/google/iree/pull/5824 I only tested a non-existent page at the root.
Whoops! Currently it can't find the image if the non-existent page is nested, e.g.
https://google.github.io/iree/foo/404
Live preview with this PR available at https://gmngeoffrey.github.io/iree/foo/404
> Use full path to ghost in 404 page

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
This reverts commit d573c3dbb4eef8044764ae6d80ca79e37e8de522.
The original commit is suspected to cause regressions in KWS streaming tests
> Revert "Fix how to get the orignal shape in generic op launch config" (#5603)

- iree/compiler/Conversion/LinalgToSPIRV/VectorizeMemrefLoadStorePass.cpp
- iree/compiler/Conversion/LinalgToSPIRV/test/vectorize_memref_load_store.mlir
When we fail to vectorize memref we need a fallback to avoid failing
compilation. Convert all the vector transfer left after memref
vectorization to scalar load/store
> Extend vector transfer scalarization fallback

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops_f32.mlir
> Add conversions for f32 vm.const ops to EmitC

- iree/vm/bytecode_dispatch.c
- iree/vm/ops.h
Makes sure we use `int32_t` as function arguments and for return types
as in the other header only implementations in the shared `ops.h`
header. EmitC always emits `int32_t`.
> Harmonize integer types of in- and outputs

- build_tools/embed_data/build_defs.bzl
This should allow it to be used from outside the IREE workspace.
Context: I would like to use `cc_embed_data` for tests in this library:
https://github.com/google/distributed_point_functions/
> Fix dependency paths in cc_embed_data

- build_tools/mako/configuration.py
This reverts commit 871d203660818dff00d252c1351d4b3eee6bafd8 because
it causes segfault. See https://github.com/google/iree/issues/5857
> Revert " Update MobileNetV2 mako compilation flags for cpu (#5755)"

- iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
This causes a miscompile on the following input:
https://gist.github.com/GMNGeoffrey/97a4c4be1471e7258c04ccf2ea014705.
When run through iree-translate and then iree-run-module on the vulkan backend with
parameters from this flagfile: https://gist.github.com/cea66f9fefb703e8203ebe3a97d10c1f
Reverts google/iree#5853
> Re-Revert #5603 "Fix getting original shape in launch config" (#5868)

- iree/samples/vision/CMakeLists.txt
Collision between https://github.com/google/iree/pull/5655 making use of
`iree_bytecode_module` and https://github.com/google/iree/commit/24fbc70911 modifying
it.
> Add C_IDENTIFIER to fix breakage from midair collision

- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.cpp
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.h
- iree/compiler/Conversion/LinalgToLLVM/PadLinalgWorkgroupTiles.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/test/BUILD
- iree/compiler/Conversion/LinalgToLLVM/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/test/materialize_launch_configuration.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/pad_linalg_workgroup_tiles.mlir
- iree/compiler/Conversion/init_conversions.h
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
This pass adds `linalg.pad_tensor` to pad matmul qualified (not an integer multiple of target tiling) workgroup tile operands to the next integer multiple of target tiling-size (vector or workgroup) which enables vectorization for all matmul shapes.
This is a medium term solution to get vectorization enabled for performance until we do tile+pad+hoist on tensors.
With this pass all `img2col` matmul are running with good performance for all conv models we are tracking: 
- MobileNetV2:
```
BM_predict/process_time/real_time        180 ms          180 ms            4 …
```
> Add a pass to pad linalg workgroup ops

- iree/compiler/Dialect/Flow/Transforms/ConvertToFlowTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/test/convert_to_flow_tensor_ops.mlir
- iree/test/e2e/xla_ops/dynamic_slice.mlir
This fully generalizes the lowering of subtensor/subtensor_insert to
flow.dispatch.slice/update and also accounts for the case where
dynamic values of the offsets/sizes result in host-roundtripping.
Fixes #5876
> Rework the lowering of subtensor/subtensor_insert to flow.dispatch.slice/update

- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
This causes segfault on Android devices:
https://buildkite.com/iree/iree-android-arm64-v8a/builds/4235
> Disable CPU workgroup padding

- iree/test/e2e/tosa_ops/BUILD
- iree/test/e2e/tosa_ops/CMakeLists.txt
Disables the test until https://github.com/google/iree/issues/5885 is fixed
> Exclude flakey TOSA reduce test on VMVX

- bindings/python/iree/compiler/core.py
- bindings/python/iree/runtime/__init__.py
- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/hal.cc
- bindings/python/iree/runtime/system_api.py
- bindings/python/iree/runtime/system_api_test.py
- bindings/python/iree/runtime/vm.cc
- bindings/python/iree/runtime/vm.h
- bindings/python/iree/runtime/vm_test.py
- integrations/tensorflow/bindings/python/iree/tf/support/module_utils.py
* Some vm_test rework.
* Swap away from vmla.
* Implement non-reflection invocations.
* Handle scalar int/float arguments.
* Handle tensor<i1>.
> More pre-factoring for native ABI swap.

- build_tools/mako/config/benchmark_template.config
- build_tools/mako/config/mobile-bert-pixel4.config
- build_tools/mako/config/mobile-bert-s20.config
- build_tools/mako/config/mobilenet-v2-pixel4.config
- build_tools/mako/config/mobilenet-v2-s20.config
- build_tools/mako/configuration.py
VMVX MobileBERT is disabled for now until it can be sped up.
> Swapping benchmarks to use VMVX instead of VMLA.

- build_tools/cmake/iree_python.cmake
The `bindings_python_iree_runtime_runtime` target tries to
depend on `::PyExtRt`. It requires to have a namespaced alias
for `bindings_python_iree_runtime_PyExtRt`.
By default `if()` in CMake dereferences the variable, after the
normal `${}` evaulation. If we have `if($SOME_VAR)`, it will
dereference twice. More details can be seen at:
https://cmake.org/cmake/help/latest/command/if.html#variable-expansion
`IREE_MULTIPY_VERSIONS_EFFECTIVE` is already gone.
> Fix iree_py_library and iree_pyext_module dependency issue

- iree/compiler/Dialect/HAL/Transforms/BenchmarkBatchDispatches.cpp
- iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- iree/compiler/Dialect/HAL/Transforms/test/benchmark_batch_dispatches.mlir
Add a barrier after each clone. If the original dispatch has a small
problem size, simply duplicating without barrier will increasing the
number of subgroups and thus "help" filling the GPU. In the end we
will have an over optimistic result. Put in barriers avoids that,
but it assumes the input model is linear.
With this, the reported number reflects the kernel execution time
for MobileNetv2 with
```
iree-translate ... --iree-hal-benchmark-dispatch-repeat-count=32
iree-benchmark-module ... --batch_size=32
```
This is a step towards https://github.com/google/iree/issues/5248.
Next is working on duplicating the command buffer submission
as a whole.
> Add barrier after duplicated dispatches for benchmarking

- third_party/.clang-format
This makes older clang-format do the right thing as disableFormat wasn't
disabling include sorting.
> Explicitly disable include sort for third_party

- colab/README.md
- colab/tensorflow_hub_import.ipynb
- docs/website/docs/ml-frameworks/tensorflow.md
Preview: https://colab.research.google.com/github/scotttodd/iree/blob/tensorflowhub-colab/colab/tensorflow_hub_import.ipynb
This walks through the process of importing a model from [TensorFlow Hub](https://tfhub.dev/) step by step, including debugging and fixing missing serving signatures. At the end of the notebook it zips up compilation artifacts and downloads them to the user's machine.
See also https://github.com/google/iree/issues/5556 for ways to make the debugging shown here less necessary or at least more user friendly.
Progress on https://github.com/google/iree/issues/5591
> Add a Colab notebook demonstrating TensorFlow Hub import.

- colab/edge_detection.ipynb
- colab/low_level_invoke_function.ipynb
add_module was renamed to add_vm_module in https://github.com/google/iree/pull/5697, so this PR updates the usage in colab
> Update colabs to use renamed python function

- iree/compiler/Conversion/Common/BUILD
- iree/compiler/Conversion/Common/CMakeLists.txt
- iree/compiler/Conversion/Common/Passes.h
- iree/compiler/Conversion/Common/SetNumWorkgroupsPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/BUILD
- iree/compiler/Conversion/LinalgToLLVM/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.cpp
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.h
- iree/compiler/Conversion/LinalgToLLVM/LowerExecutableTargetPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVM/Passes.h
- iree/compiler/Conversion/LinalgToLLVM/test/materialize_launch_configuration.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/matmul_vectorization.mlir
- iree/compiler/Conversion/init_conversions.h
- iree/compiler/Dialect/HAL/IR/BUILD
- iree/compiler/Dialect/HAL/IR/CMakeLists.txt
- iree/compiler/Dialect/HAL/IR/HALBase.td
- iree/compiler/Dialect/HAL/IR/HALDialect.td
- iree/compiler/Dialect/HAL/IR/LoweringConfig.cpp
- iree/compiler/Dialect/HAL/IR/LoweringConfig.h
- iree/compiler/Dialect/HAL/IR/LoweringConfig.td
- iree/compiler/Dialect/Modules/VMVX/Transforms/Passes.cpp
The lowering of linalg operations to scalar/vector code is modified to
use dynamic pass pipelines. A new pass `LowerExecutableTargetPass` is
added that lowers an executable to the scalar/vector code. This pass
sets the configuration to use when lowering the module within the
target operation. At the time of setting the configuration, the pass
to use is also decided. This is used to dynamically select the pass
pipeline to use for the lowering.
Currently only two pipelines exist. One for vectorization based
lowering and other to lower to scalar code directly. The existing
pipeline is reordered to make the distinction between lowering a
Linalg operation to scalar/native-vector operations and the pipeline
needed to convert those into LLVM Dialect. The latter must be
re-usable across all …
>  Use dynamic pass pipelines while lowering on CPU backends.

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
- iree/test/e2e/xla_ops/reduce.mlir
For the case of multiple operands, the tracking to reuse the buffer
for the dispatch region output for the operations needs to be updated
to track across linalg ops that have multiple results.
Fixes  #5838
> Fix tracking of result buffer to use if the buffer eventually maps to low dispatch output.

- .github/workflows/build_package.yml
- .github/workflows/copybara_fixup.yml
- .github/workflows/publish_website.yml
- .github/workflows/schedule_snapshot_release.yml
- .github/workflows/update_llvm_dependent_submodules.yml
GitHub tokens switched to a new format. I tried to update us in a
seamless way by generating a new token and updating our existing
secret, but apparently since (by a new rule) they don't want repository
secrets to use the `GITHUB_` prefix, it silently didn't take my update,
which I only noticed after deleting the old token...
> Update workflows to use new token

- iree/hal/vulkan/dynamic_symbols.cc
The vulkan dynamic library name is libvulkan.dylib in macos platform.
> Fix vulkan dynamic library name for MacOS

- build_tools/docker/cmake-bazel-frontends-nvidia/Dockerfile
- build_tools/docker/cmake-python-nvidia/Dockerfile
- build_tools/docker/manage_images.py
- build_tools/docker/manage_prod.py
- build_tools/docker/prod_digests.txt
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build_kokoro.sh
We have had repeated issues where we cannot update our docker images
because the version we're using has disappeared from the apt
repository. We pin to a specific version because it has to match
*exactly* with the version on the underlying VM. For similar reasons,
updating the version is extremely painful.
So instead, let's fetch the deb from somewhere we know isn't going
away. If someone wants to experiment with an official stable source for
these that would be most welcome, but this was something I had high
confidence would work, and currently the inability to update these
images is blocking us updating basically *any* image.
I obtained these debs by running our current docker image and using
`dpkg-repack` to recreate the debs.
This should unblock further work on our docker images.
> Use nvidia deb files that we control

- iree/compiler/Dialect/Flow/IR/FlowInterfaces.td
- iree/compiler/Dialect/Flow/IR/FlowOpUtils.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups_folding.mlir
The canonicalization pattern to remove a result produced by the
ClosureInterfaceOp needs to make sure that all uses within the
dispatch region are write-only and that these operations are erased
before dropping the arguments.
Add an interface method to check if an argument to the
ClosureInterfaceOp region has any read uses. This is used to determine
if the result/operand can be dropped.
> Handle removing unused results of a CloseureInterfaceOp

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
The main idea is to break loop cyclic dependency (not the case in the buffer case) and forward `init_arg` tensors from outer most loop to inner most loop, because all these tensors are going to be mapped to the same buffer by construction this forwarding allows the `PostOder` walk to replace all tensors in the inner most loops which are in this case they won't depend on any of the operands / arguments of the `scf.for`. As a result all tensors arguments and results are going to be unused and `canonicalize` will create a tensor free `scf.for` (there is no need to create clone new scf.forOp` YaY!!!)
> Bufferization support for scf.for

- iree/compiler/Conversion/LinalgToLLVMGPU/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/ConvertToLLVM.h
- iree/compiler/Conversion/LinalgToLLVMGPU/ConvertToNVVM.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/ConvertToROCDL.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/test/scalarize.mlir
This patch pulls out the scalarization pass and shares
it between CUDA and ROCM. With this change, Mobilenet
now compiles on ROCM.
> Share scalarization pass between CUDA and ROCM

- integrations/tensorflow/bindings/python/iree/tf/support/module_utils.py
> Use 'vulkan-spirv' as the compiler target for consistency

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
I think this code was written before walking could signal a failure.
This change was important in reproducing
https://github.com/google/iree/issues/5989
> Propagate diagnostics instead of asserting in stream conversion

- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups_folding.mlir
The index should be for the old block arguments and all excluded*
indices are for the old ones. Thus, we should compute base result index
based on old operands.
Fixes https://github.com/google/iree/issues/6009
> Fix base result index in DispatchWorkgroupsOp patterns.

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/VerifyCompilerInputLegality.cpp
- iree/compiler/Dialect/Flow/Transforms/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/test/verify_compiler_input_legality.mlir
* Not used yet: will be added as part of the input pipeline rework.
> Add a pass to verify that input to the compiler is legal.

- iree/compiler/Dialect/Flow/Conversion/StandardToFlow/ConvertStandardToFlow.cpp
- iree/compiler/Dialect/Flow/Conversion/StandardToFlow/ConvertStandardToFlow.h
- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/PrePostPartitioningConversion.cpp
- iree/compiler/Dialect/Flow/Transforms/PromoteTensorLoads.cpp
- iree/compiler/Dialect/Flow/Transforms/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/test/promote_tensor_loads.mlir
* In the new input pipeline, the only part of
PrePartitioningConversionPass which survives is the
tensor.extract_element -> flow.tensor.load conversion.
* This conversion actually needs to be done at a couple of points during
lowering, first promoting any extracts that are introduced as part of
control flow (in the input pipeline), then allowing most of the program
to be loaded onto the device, and finally converting any remaining,
otherwise unrecognized extract elements.
* As such, I opted to make it a very specific pass that does exactly
what it says on the label. We may want to do something more
sophisticated later, and at least having one thing to see and replace
will help.
* Once the new input pipeline lands, PrePostPartitioningConversion.cpp
will be deleted.
> Create new pass PromoteTensorLoads.

- iree/compiler/Conversion/HLOToLinalg/BUILD
- iree/compiler/Conversion/HLOToLinalg/CMakeLists.txt
- iree/compiler/Conversion/HLOToLinalg/ConvertComplexToReal.cpp
- iree/compiler/Conversion/HLOToLinalg/test/BUILD
- iree/compiler/Conversion/HLOToLinalg/test/CMakeLists.txt
- iree/compiler/Conversion/HLOToLinalg/test/convert_complex_to_real.mlir
- iree/compiler/Conversion/Passes.h
- iree/compiler/Conversion/Passes.td
* The original HLO patterns were quite dated, and upon hacking on them a little bit, I determined that a rewrite was called for.
* These new patterns presume a pipeline where CHLO and MHLO are legal and they correctly handle complex broadcasting.
* The MHLO side patterns had issues in this respect.
* Also added a dedicated test pass and patterns to make the conversion self contained so that it can be run as part of a full multi-step dialect conversion.
* When used in this way, the error messages for unsupported conversions are much better.
> Re-implement algebraic complex tensor patterns.

- iree/compiler/Dialect/HAL/Conversion/StandardToHAL/ConvertStructuralOps.cpp
- iree/compiler/Dialect/HAL/Conversion/StandardToHAL/test/structural_ops.mlir
We are able to run select operations in VM. This PR adds missing
lowering for select op to HAL.
Part of https://github.com/google/iree/issues/6034
> Add support for lowering select op to HAL.

- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/constant_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/executable_ops.mlir
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- iree/compiler/Dialect/HAL/Target/VMVX/test/linking.mlir
- iree/compiler/Dialect/VM/Conversion/MemRefToVM/ConvertMemRefToVM.cpp
- iree/compiler/Dialect/VM/Conversion/MemRefToVM/test/load_store_ops.mlir
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/test/const_folding.mlir
- iree/compiler/Dialect/VM/IR/test/const_ops.mlir
- iree/compiler/Dialect/VM/Target/Bytecode/test/constant_encoding.mlir
- iree/compiler/Dialect/VM/Transforms/test/hoist_inlined_rodata.mlir
- iree/compiler/Translation/test/do_not_optimize.mlir
- iree/vm/test/buffer_ops.mlir
- iree/vm/test/list_variant_ops.mlir
Executable linking merges multiple modules together into a single module. If a symbol name already exists in the merged module, we previously skipped over it assuming the contents of those symbols were identical. This now resolve conflicts by
* renaming different private symbols
* merging equivalent private symbols
* emitting an error for public symbol conflicts
Fixes https://github.com/google/iree/issues/5946.
Includes a step towards https://github.com/google/iree/issues/4670 that should be made generic in some way.
Issues like https://github.com/google/iree/issues/4897 will still need to use MLIR symbol visibility (not some special visibility) or ensure uniqueness prior to this pass.
> Handle symbol name conflicts during executable linking.

- build_tools/android/common/__init__.py
- build_tools/android/common/benchmark_description.py
- build_tools/android/post_benchmarks_as_pr_comment.py
- build_tools/android/run_benchmarks.py
- build_tools/android/upload_benchmarks_to_dashboard.py
IREE was relicenced previously with
https://github.com/google/iree/commit/552d3f888e46f96c8227b1bd2e4600b85338237b.
These files were from pull requests before that.
> Update license headers for recently landed scripts

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOpUtils.cpp
Pulling in operations from a different basic blocks into `flow.ex.stream.fragment` operation seems to create a ssa use-def violation issue. For now just disable this for operations crossing blocks.
A better fix would be to pull the inlining into a different pass and use dominator information to pull things in legally.
> Fix SSA use-def violation created by canonicalization of `flow.ex.stream.fragment` op.

- build_tools/cmake/iree_copts.cmake
- iree/base/status.c
- iree/iree.natvis
This adds some visualizers for IREE runtime types that can be used to display the types in visual studio, vscode, and windbg (and maybe other tools). I'm not sure how it works with gdb in vscode but it'd be cool if it worked.
The initial set covers many base/ API types like status, timeout, and string_view. It also has coverage for the VM types like list, buffer, and the ref types and values. Some select HAL types - namely buffer and buffer_view - are supported with more to come in the future.
Example of an iree_status_t (that has a message as well as an annotation):
Example of various timeouts:
Example of vm.buffer (with various typed accessors; they're even mutable!):
Example of vm.list, here showing a variant list that gets proper type decoding of each element:
Example of buffer_view + …
> Adding initial `iree.natvis` for runtime types.

- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/IREE/IR/IREETypes.cpp
If an operand is tied to a result, there won't be a block argument
for the operand; so we cannot use the number of operand as the
start index for result block arguments.
And, `getTiedResultOperandIndices()` returns indices into the full
range of the op, but in the attribute, we expect to store ranges
into the range returned by `getTiedOperandsIndexAndLength`.
This is a spin-off from #6049.
> Fix two indexing issues regarding TiedOpInterface

- build_tools/cmake/build_android.sh
We have seen several benchmark artifacts generation issues in
the benchmark pipeline thus far. It's because the benchmark pipeline
is totally detached from the normal CI testing flow and it's not
run pre-submit. This is a step towards addressing the issue.
Right now we aren't covering all models we are benchmarking with
the current pipeline. That will be brought up to equality with
future pull requests, aiming as examples for registering new
benchmarks.
> [ci] Test benchmark artifact generation during cross-compilation

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
For an unknown reason this pass is causing a failure on the pixel tests. Disabling
while triaging.
> Disable i1 to i8 passes causing failures on pixel.

- build_tools/cmake/iree_mlir_benchmark_suite.cmake
- iree/test/model_benchmarks/CMakeLists.txt
This commit enables putting multiple benchmark modes in the same
`iree_mlir_benchmark_suite` call. This is very useful for CPU-based
IREE HAL drivers where we want to test both big and little cores.
As part of that, enabling dylib-sync benchmarking on big/little cores,
dylib benchmarking on 1/3 thread x big/little cores.
> Allow multiple benchmark modes and enable more dylib(-sync) cases

- build_tools/mako/configuration.py
- iree/test/model_benchmarks/CMakeLists.txt
They are causing segfault. Looks it's the same issue as
https://github.com/google/iree/issues/5857.
> Disable operand fusion for CPU benchmarks

- build_tools/cmake/iree_mlir_benchmark_suite.cmake
This was dropped accidentally in previous changes.
But CMake seems quite happy without it and functions properly.
I cannot say I know CMake now..
> [cmake] Fix uninitialized variable

- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
- iree/compiler/Conversion/HLOToLinalg/test/BUILD
- iree/compiler/Conversion/HLOToLinalg/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLinalg/BUILD
- iree/compiler/Conversion/LinalgToLinalg/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLinalg/PadTensorToSubTensorInsert.cpp
- iree/compiler/Conversion/LinalgToLinalg/Passes.h
- iree/compiler/Conversion/LinalgToLinalg/test/BUILD
- iree/compiler/Conversion/LinalgToLinalg/test/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLinalg/test/pad_tensor_to_tensor.mlir
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/test/e2e/tosa_ops/BUILD
- iree/test/e2e/tosa_ops/CMakeLists.txt
- iree/test/e2e/tosa_ops/pad.mlir
This is currently done on the HLO to Linalg conversion, which meant
the TOSA path didnt get this conversion. This is needed for the vulkan
codegen to handle pad operation.
Fixes #6077
> Move linalg.pad_tensor conversion to subtensor_insert into a separate pass

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
Original commit from #6005:
Make the traversal order pre-order since for ops with nested regions,
it is necessary to process the op before the region.
Changing to pre-order also means that regions of cloned ops dont get
processed during the work to convert tensor to memrefs. As a result,
move the conversion of ops that are just using the tensor value, and
not creating a tensor to be processed in a separate walk.
In this PR:
Move `scf.for` operands forwarding as a post processing step.
> Rebase and work PR #6005:

- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
sync_driver doesn't depend on the task executor. Remove the dependency
in BUILD and CMakeLists.txt.
Cleanup for https://github.com/google/iree/issues/6027
> Cleanup libiree_hal_local_sync_driver dependency

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
- Reuse the same result buffer for scf.for
- Handle subtensor inserts that alise result buffer.
> Remove extra unnecessary allocations

- iree/test/model_benchmarks/CMakeLists.txt
On Snapdragon SoC we can see device lost after 2 seconds.
Our kernels for Adreno GPUs aren't well optmized like Mali GPUs.
So they take longer time to run. Reduce the iterations to avoid
seeing device lost and fail the pipeline.
For more context see https://github.com/google/iree/issues/5052
> Reduce benchmarking iterations for Adreno GPU kernel execution

- build_tools/android/run_benchmarks.py
- build_tools/cmake/iree_mlir_benchmark_suite.cmake
- iree/test/model_benchmarks/CMakeLists.txt
Previously we just simply generate a new vmfb file for each benchmark
configuration. This is fine for a small number of benchmarks but
it's becoming problematic as we have more and more models, IREE
drivers, modes that we want to generate products over. It will
bloat the total size of vmfb files. We use buildkite to build in
the cloud and then download to run on the phone. It would mean
downloading probably GBs data per run.
This commit changes to hash according to the input MLIR module name
and all the translation flags, and generate one single copy of vmfb
file. Flagfiles for all the benchmark cases are pointing to the
unique copy.
> Deduplicate artifacts in generated benchmark suites

- build_tools/cmake/iree_mlir_benchmark_suite.cmake
- iree/test/model_benchmarks/CMakeLists.txt
This is from #6108 but I let it auto-submit before it could be fixed.
> Moving back the iree-input-type flag to TRANSLATION_FLAGS.

- iree/compiler/Conversion/LinalgToLLVMGPU/ConvertToLLVM.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/test/convert_to_nvvm.mlir
- iree/hal/cuda/graph_command_buffer.c
The previous implementation relied on the bindings being a dense set
being in order.
The new logic implements a new convention that the binding are mapped
are ordered and compressed based on binding index and mapped to kernel
arguments.
> [CUDA] Remove assumptions that bindings are a dense set

- build_tools/android/run_benchmarks.py
Just in case there are leftovers from manual or failed runs.
Also uses the relative path to flagfile to simplify the command.
> Pre-clear benchmark directory before running benchmarks

- iree/test/e2e/vulkan_specific/dot_general.mlir
Right now we don't have a good way to disable per GPU vendor,
but that would be nice to have. For now just disable for all
to avoid marking all commits as failing.
> Disable large_dot_general2 test case until it gets fixed
