iree-org/iree

- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- iree/compiler/Conversion/HLOToLinalg/BUILD
- iree/compiler/Conversion/HLOToLinalg/CMakeLists.txt
- iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnTensors.cpp
This fixes some FFT tests that are using complex types on my machine (Windows/MSVC):
```
[build] FAILED: iree/test/e2e/vulkan_specific/check_vulkan-spirv_vulkan_fft.mlir_module.vmfb 
[build] cmd.exe /C "cd /D D:\dev\projects\iree-build\iree\test\e2e\vulkan_specific && D:\dev\projects\iree-build\iree\tools\iree-translate.exe -iree-mlir-to-vm-bytecode-module -mlir-print-op-on-diagnostic=false --iree-hal-target-backends=vulkan-spirv -iree-input-type=mhlo D:/dev/projects/iree/iree/test/e2e/vulkan_specific/fft.mlir -o check_vulkan-spirv_vulkan_fft.mlir_module.vmfb"
[build] LLVM ERROR: Building op `complex.create` but it isn't registered in this MLIRContext
```
Not sure why this wasn't needed on Linux...
> Add ComplexDialect to DialectRegistry where it was missing.

- iree/vm/bytecode_dispatch.c
- iree/vm/ref.h
- iree/vm/test/assignment_ops.mlir
Previous behavior would lead to (safe) null access violations if the
non-selected value was moved into the same register:
```
%0 = vm.select.ref %cond, %t, %f
```
where: `%0` and `%t`/`%f` alias a register and one or both `%t`/`%f` are moves.
> Fixing vm.select.ref for moves into the same register.

- build_tools/bazel/iree_check_test.bzl
- iree/test/e2e/models/BUILD
The mobile bert fake weights test times out about 3% of the time
internally.
> Extend timeout for vulkan model tests

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
A few minor adjustments to scf.for bufferization.
- When tracking number of uses, specifically look for destructive
update patterns to treat than as "non real" uses since these uses
are due to tensor abstraction limitations.
- Refactor the walk to store and also stop the walk at the
subtensor_insert that is a destructive update.
- During scf.for conversion, replace the operands of the scf.yield
with the values for the arg that represent the initArg of the
loop. This effectively marks the (result, initArg, regionArg) set as
a no-op that is canonicalized later.
- Remove the now unecessary loop manipulation added previously to make
the loop dead.
> Revisit scf.for bufferization.

- build_tools/mako/configuration.py
- iree/test/model_benchmarks/CMakeLists.txt
The breakage at https://github.com/google/iree/issues/6086
cannot be reproduced now and was fixed by some previous commit.
> Re-enable operand fusion for Vulkan GPU benchmarks

- iree/compiler/Conversion/CodegenUtils/FunctionUtils.cpp
- iree/compiler/Conversion/CodegenUtils/FunctionUtils.h
- iree/compiler/Conversion/Common/SetNumWorkgroupsPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.cpp
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.h
- iree/compiler/Conversion/LinalgToLLVM/LinalgTileAndVectorizePass.cpp
- iree/compiler/Conversion/LinalgToLLVM/LowerExecutableTargetPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/materialize_launch_configuration.mlir
- iree/compiler/Conversion/LinalgToLLVM/test/matmul_vectorization.mlir
- iree/compiler/Dialect/HAL/IR/LoweringConfig.h
One advantage of using dynamic pass pipelines is that the translation
of the executable to scalar/native code can be done using a pass
pipeline that itself might be specified as a command line option. The
LowerExecutableTranslation now has an options `use-lowering-pipeline`
that can take a list of passes and then lower them to code that can
then be translated to LLVM using the standard LLVM lowering passes.
The lowering pipeline specified as command line only makes sense if
there is just one executable. If there are multiple executables, then
the same pipeline will be used for all of them.
Also clean up some of the default configuration. This is done by
adding a struct `IREE::HAL::TranslateExecutableInfo` which is right
now a C++ struct. This is mostly staging, since it could potentially …
> Allow CPU translation to be specified using command line options.

- iree/compiler/Dialect/Flow/Transforms/PromoteI1ToI8Pass.cpp
It turns out the first use is not guaranteed to be the first use in order.
Updated so that we can insert just before the first use.
> Fix promote i1 to i8 order to avoid invalid IR

- build_tools/android/post_benchmarks_as_pr_comment.py
We are accumulating more and more benchmarks. Posting all of the
results to the pull request can be a daunting amount of raw data.
Instead, we should categorize and sort them and just provide
abbreviated tables, leaving the full tables somewhere else.
This commit adjusts the pull request comment script with above
improvements. The full benchmark tables are posted as Github Gists,
which is still on GitHub infrastructure and provides nice markdown
rendering and such.
> Abbreviate benchmark results posted to pull requests

- build_tools/android/post_benchmarks_as_pr_comment.py
This is a follow up to https://github.com/google/iree/pull/6124,
where we categorized and sorted benchmark result tables.
But it's still noisy given we are posting many abbreviated
summary tables. This tries to reduce that by trying to find
the last previous comment from the bot's account and
update that.
Also, using issue API endpoints instead of pull request ones,
in the hope to avoid putting the bot as a "reviewer".   
Only the last commit matters.
> Create or update comments for benchmark results

- iree/benchmark/TensorFlow/CMakeLists.txt
This commit is meant to be an example for showing how to register
benchmark cases for a new model that cannot be folded into the
common list of models. In addition to the changes in CMake, one
would also need to generate the input model and place it in a
cloud storage.
> Add benchmark cases for MobileBERT

- iree/compiler/Dialect/VM/Analysis/RegisterAllocation.cpp
- iree/vm/bytecode_dispatch.c
This works today by chance but with coming native ABI changes needs fixing.
> Fixing top-level vm.return of multiple of the same ref type.

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/VerifyCompilerInputLegality.cpp
This was dropped in the dynamic shapes refactor in favor of adding back when needed.
> Add back passes for legalizing shape->standard.

- iree/compiler/Translation/IREEVM.cpp
Fixes passing `InputDialectOptions` when translating to a VM C module.
> Fix passing input options

- iree/base/internal/call_once.h
- iree/base/internal/synchronization.c
Put iree_run_once() as a no-op with the macro defined. Also fix some
no-op API interfaces.
Part of the cleanup for https://github.com/google/iree/issues/6027
> Fix missing no-ops under IREE_SYNCHRONIZATION_DISABLE_UNSAFE

- iree/compiler/Conversion/CodegenUtils/FunctionUtils.cpp
- iree/compiler/Conversion/CodegenUtils/FunctionUtils.h
- iree/compiler/Conversion/Common/SetNumWorkgroupsPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.cpp
- iree/compiler/Conversion/LinalgToLLVM/KernelDispatch.h
- iree/compiler/Conversion/LinalgToLLVM/LowerExecutableTargetPass.cpp
- iree/compiler/Conversion/LinalgToLLVM/test/materialize_launch_configuration.mlir
- iree/compiler/Dialect/HAL/IR/LoweringConfig.cpp
- iree/compiler/Dialect/HAL/IR/LoweringConfig.h
- iree/compiler/Dialect/HAL/IR/LoweringConfig.td
The decision of the lowering pipeline to use is currently returned as
a value to the caller. This isnt scalable since it would not handle
cases of multiple entry point functions as cleanly. Instead add
another attribute that the configuration selection should add on the
`hal.executable.entry_point` op to defines the pipeline to use for
lowering as well as the workload per workgroup value.
Some cleanups to use `workloadPerWorkgroup` instead of `workgroupSize`
which has overloaded meaning.
Also on the CPU side, only the root operation needs a lowering
configuration. Eventually that should be true for all backends since
the root op should drive the compilation.
> Add TranslationInfo Attribute.

- iree/samples/variables_and_state/main.c
Initialize the counter value to avoid sometimes-uninitialized warning.
> Fix the initial value in `iree/samples/variables_and_state`

- iree/compiler/Conversion/LinalgToLLVM/LowerExecutableTargetPass.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/BUILD
- iree/compiler/Conversion/LinalgToLLVMGPU/CMakeLists.txt
- iree/compiler/Conversion/LinalgToLLVMGPU/KernelConfig.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/KernelConfig.h
- iree/compiler/Conversion/LinalgToLLVMGPU/LowerExecutableTargetPass.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/Passes.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/Passes.h
- iree/compiler/Conversion/LinalgToLLVMGPU/TileAndDistribute.cpp
- iree/compiler/Conversion/LinalgToLLVMGPU/test/distribute_to_thread.mlir
- iree/compiler/Conversion/LinalgToLLVMGPU/test/nvvm_pipeline_test.mlir
- iree/compiler/Conversion/LinalgToLLVMGPU/test/rocdl_pipeline_test.mlir
- iree/compiler/Dialect/HAL/IR/LoweringConfig.td
Add infrastructure to enable dynamic pipeline. Currently There are only
two different pipelines with and without vectorization. This will allow
adding different pipelines for differnt ops like convolutions.
> [CUDA] Enable dynamic pipeline

- iree/test/e2e/xla_ops/dynamic_update_slice.mlir
Thanks to Lei's https://github.com/google/iree/pull/6174, updating into
a constant now works.
Confirmed that before that commit, this test case reproduces the issue I
was hitting in https://github.com/google/iree/issues/5989.
Fixes https://github.com/google/iree/issues/5989
> Add test case for dynamic-update-slice into constant

- build_tools/android/run_benchmarks.py
Avoid `cd`ing into the `ANDROID_TMP_DIR` directory,
which may not even exist.
> Clear the whole temporary directory before/after benchmarking

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/stream_ops.mlir
A flow.tensor.clone op by definition should have its operand and
result of the same shape. However, when mapping to buffers, we
could have the case where the operand is a constant subspan. Then
the source buffer will be the constant pool buffer, which can be
larger than the result buffer.
> Use the result buffer's length when converting flow.tensor.clone

- bindings/tflite/java/README.md
- bindings/tflite/java/build.gradle
- bindings/tflite/java/org/tensorflow/lite/AndroidManifest.xml
- bindings/tflite/java/org/tensorflow/lite/Interpreter.java
- bindings/tflite/java/org/tensorflow/lite/native/CMakeLists.txt
- bindings/tflite/java/settings.gradle
Process for building the AAR:
1. Start AndroidStudio. Select "Open File or Project" then choose `iree/bindings/tflite/java/gragle.build`.
2. AndroidStudio should sync the project and setup gradlew uner `iree/bindings/tflite/java`.
3. Make the project using android studio or run the build directly in terminal:
```shell
./gradlew build
```
This produces two libraries under `iree/bindings/tflite/java/build/outputs/aar`: 
* `iree-tflite-bindings-debug.aar` 
*  `iree-tflite-bindings-release.aar` 
AAR contents:
Include either library in another gradle project for iree tflite binding support. 
Addresses #6198
> Update gradle to build TFLilte Java bindings AAR library

- .github/workflows/build_package.yml
- build_tools/github_actions/build_dist.py
* This is the first pure python package and thus warrants its own build step.
* It only runs on Linux since platform independent.
> Add release step to build iree_jax package.

- .github/workflows/build_package.yml
* cibuildwheel was helpful enough to say that it shouldn't be used for this and give the command that should be used instead.
> Update iree_jax packaging step.

- integrations/tensorflow/build_tools/testdata/generate_dynamic_samples.py
- integrations/tensorflow/iree_tf_compiler/MHLO/BUILD
- integrations/tensorflow/iree_tf_compiler/MHLO/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/MHLO/Passes.h
- integrations/tensorflow/iree_tf_compiler/MHLO/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/PromoteI1ToI8Pass.cpp
The IREE license headers were updated in
https://github.com/google/iree/pull/6020. These files were committed
afterwards with the incorrect license header (likely because there was
in-progress work when the PR went in).
> Fix incorrect license headers

- iree/hal/local/executable_library_benchmark.md
> Adding notes for how to use executable_library_benchmark.

- bindings/python/iree/compiler/CMakeLists.txt
- bindings/python/iree/compiler/README.md
- bindings/python/iree/compiler/__init__.py
- bindings/python/iree/compiler/core.py
- bindings/python/iree/compiler/debugging.py
- bindings/python/iree/compiler/setup.py.in
- bindings/python/iree/compiler/tf.py
- bindings/python/iree/compiler/tflite.py
- bindings/python/iree/compiler/xla.py
- bindings/python/tests/compiler_core_test.py
- integrations/tensorflow/bindings/python/iree/tf/support/module_utils.py
- integrations/tensorflow/bindings/python/iree/tf/support/tf_test_utils.py
* This is done at a lower level than the TF test framework and happens automatically if env variables are set (can be customized).
* Intended for debugging and getting dumps of foreign systems where the high level should not be altered to manually pass in artifact retention.
* I'm sure folks will write scripts around this, but the intent is for humans to have a less miserable time when dealing with an arbitrary system.
* To shortcut everything, just set the env var IREE_SAVE_TEMPS to something like "/tmp/ireedumps/{pid}/{id}".
> Add a facility so that the Python API will save off all temporaries.

- bindings/python/iree/compiler/setup.py.in
- bindings/python/iree/tools/core/CMakeLists.txt
- bindings/python/iree/tools/core/scripts/iree_translate/__main__.py
- build_tools/cmake/iree_python.cmake
- integrations/tensorflow/bindings/python/iree/tools/tf/CMakeLists.txt
- integrations/tensorflow/bindings/python/iree/tools/tf/scripts/iree_import_tf/__main__.py
- integrations/tensorflow/bindings/python/iree/tools/tf/setup.py.in
- integrations/tensorflow/bindings/python/iree/tools/tflite/CMakeLists.txt
- integrations/tensorflow/bindings/python/iree/tools/tflite/scripts/iree_import_tflite/__main__.py
- integrations/tensorflow/bindings/python/iree/tools/tflite/setup.py.in
- integrations/tensorflow/bindings/python/iree/tools/xla/CMakeLists.txt
- integrations/tensorflow/bindings/python/iree/tools/xla/scripts/iree_import_xla/__main__.py
- integrations/tensorflow/bindings/python/iree/tools/xla/setup.py.in
After this patch, if you install the corresponding python packages, you will (on all platforms) have the above tool binaries on your path.
> Add python console_scripts for iree-translate, iree-import-tf, iree-import-tflite, iree-import-xla.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops_f32.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops_i64.mlir
Fixes the lit tests as `emitc.const` was renamed to `emitc.constant` in
upstream.
> Fix VM constants to EmitC conversion tests

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/test/calling_convention.mlir
- iree/compiler/Dialect/VM/Target/C/test/control_flow.mlir
- iree/compiler/Dialect/VM/Target/C/test/global_ops.mlir
- iree/samples/emitc_modules/CMakeLists.txt
- iree/samples/emitc_modules/add.mlir
- iree/samples/emitc_modules/add_module_test.cc
- iree/vm/shims_emitc.h
- iree/vm/test/BUILD
- iree/vm/test/CMakeLists.txt
- iree/vm/test/call_ops.mlir
- iree/vm/test/emitc/CMakeLists.txt
- iree/vm/test/emitc/module_test.cc
This adds support for internal function calls in the CModuleTarget.
* This only supports function with zero or one integer results for now.
Co-authored-by: Marius Brehler <marius.brehler@iml.fraunhofer.de>
> Support calls to internal function in EmitC

- integrations/tensorflow/e2e/resource_ops_test.py
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertVariableOps.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/variable_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/test/BUILD
- iree/compiler/Dialect/HAL/IR/test/CMakeLists.txt
- iree/compiler/Dialect/HAL/IR/test/invalid.mlir
* This shows up in simple programs that attempt to store the result of a buffer_view function arg (or result of a custom op) to a variable that has been materialized with the usual mechanics.
> Allow an implicit cast from buffer_view to buffer on variable store.

- iree/tools/CMakeLists.txt
cmake on windows does not like executables in target link libraries (as
it shouldn't anywhere, but apparently it only checks on windows...).
> Properly using DATA to depend on lld.

- CMakeLists.txt
Please, everyone, hold your noses. No one likes this state but we do need to have a way to reliably strip -DNDEBUG flags for release builds when opting in to enable assertions. It isn't awesome that LLVM gates so much on NDEBUG, but reality is what it is.
With this patch, setting -DIREE_ENABLE_ASSERTIONS=ON in Release mode gets us assertions and LLVM `-debug`. Some non-scientific observations lead me to believe that this is not that much slower than a real Release build - which matches my upstream expectations (i.e. if it is, some assert is too expensive).
I want to be able to generate release binaries with assertions/debug enabled in special packages. And developing this way is my normal mode of operation when I'm not using a debugger.
> Add an IREE_ENABLE_ASSERTIONS option and make it interop with LLVM.

- BUILD.bazel
- CMakeLists.txt
- bindings/python/iree/runtime/CMakeLists.txt
- bindings/python/iree/runtime/binding.h
- bindings/python/iree/runtime/vm.cc
- bindings/python/iree/runtime/vm.h
- build_tools/bazel/iree.bazelrc
- build_tools/bazel/workspace.bzl
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- build_tools/cmake/iree_copts.cmake
- build_tools/cmake/iree_python.cmake
- build_tools/embed_data/BUILD
- build_tools/embed_data/CMakeLists.txt
- build_tools/embed_data/generate_embed_data_main.cc
Python abseil is still used within IREE and the tensorflow tools use
the C++ one for interop but that's fine as it's restricted to that
workspace and fetched using bazel magic.
Assuming this works the next change will remove the submodule.
> Removing usage of the abseil c++ library from IREE.

- integrations/tensorflow/iree_tf_compiler/MHLO/test/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/LLVM/StaticLibraryGenerator.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/StaticLibraryGenerator.h
IREE was moved to the LLVM license with
https://github.com/google/iree/pull/6020
> Fix license headers with the old license

- CMakeLists.txt
They need to update their rule to be compatible with the new policy.
> LLVM's tblgen causes hundreds of cmake warnings. This quiets them.

- docs/website/docs/ml-frameworks/tensorflow.md
Also wrap some lines to 80 characters.
> Fix broken links in TensorFlow framework doc.

- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
`-iree-hal-target-backends=dylib-llvm-aot` must also be passed.
Outputs something like:
```
Registered Targets:
aarch64    - AArch64 (little endian)
aarch64_32 - AArch64 (little endian ILP32)
aarch64_be - AArch64 (big endian)
arm        - ARM
arm64      - ARM64 (little endian)
arm64_32   - ARM64 (little endian ILP32)
armeb      - ARM (big endian)
riscv32    - 32-bit RISC-V
riscv64    - 64-bit RISC-V
thumb      - Thumb
thumbeb    - Thumb (big endian)
x86        - 32-bit X86: Pentium-Pro and above
x86-64     - 64-bit X86: EM64T and AMD64
```
> Adding -iree-llvm-list-targets to list registered targets.

- iree/compiler/Conversion/Common/LinalgBufferizePass.cpp
- iree/compiler/Conversion/Common/test/linalg_bufferize.mlir
When a read-only tensor is passed as an `initArg` to an `scf.for`, it
cannot be tied to the result to do in-place updates. Plumbing this
through prompted some more cleanups.
1) Make the destructive update pattern recognizer more strict, and to
have separation of concerns, do a separate walk to find destructive
updates and tie operands accordingly.
2) Make the walk of use-def chains (which walks uses), utilize the
`BufferizationPlan` to figure out which result uses to walk next.
3) Also add support for `scf.if`, `tensor.insert` operations to
bufferization pass.
> Handle read-only tensors as `initArgs` of `scf.for`.

- iree/vm/bytecode_dispatch.c
- iree/vm/ops.h
This groups the f32 functions in `ops.h` as in the dispatcher and VM to
EmitC conversion pass. Further moves the f32 cast ops in the dispatcher
to the appropriate position.
> Restructure ops and bytecode dispatcher

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/assignment_ops_f32.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/conversion_ops_f32.mlir
- iree/vm/test/assignment_ops_f32.mlir
- iree/vm/test/conversion_ops_f32.mlir
Enables the conversion of VM f32 select and f32 cast ops to EmitC.
> Add further VM f32 ops to EmitC conversions

- build_tools/kokoro/gcp_ubuntu/cmake/linux/riscv64/test.sh
- iree/samples/simple_embedding/BUILD
- iree/samples/simple_embedding/CMakeLists.txt
- iree/samples/simple_embedding/device_dylib.c
- iree/samples/simple_embedding/device_embedded_sync.c
- iree/samples/simple_embedding/device_vmvx_sync.c
- iree/samples/simple_embedding/simple_embedding.c
The device should support all architectures and the bare-metal config.
> Add vmvx_sync HAL device in `iree/samples/simple_embedding`

- docs/developers/design_docs/cuda_backend.md
`-iree-flow-dispatch-linalg-on-tensors` is not an option of `iree-translate`.  
Or should I use `-iree-flow-dispatch-linalg-on-tensors-tile-sizes=<>` instead?
> Fix cuda_backend.md

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/vm/bytecode_dispatch.c
- iree/vm/ops.h
- iree/vm/test/global_ops_f32.mlir
- iree/vm/test/global_ops_i64.mlir
Implements global load and store ops for f32 and i64 types in `ops.h`
and changes the dispatcher to use them. Fruther adds the corresponding
VM to EmitC conversions.
> Add VM to EmitC support for f32/i64 global ops

- integrations/tensorflow/e2e/BUILD
- integrations/tensorflow/e2e/CMakeLists.txt
* Still some remaining dynamic shape issues/burn down needed, but these full model tests are working now.
> Enable dynamic shaped MLP tests on LLVM AOT.

- iree/samples/simple_embedding/BUILD
- iree/samples/simple_embedding/CMakeLists.txt
Add `f` extension support to avoid soft_fp library resolution in dylib.
> Update RISC-V 32bit simple_embedding bytecode codegen flag

- iree/compiler/Dialect/VM/Conversion/ConversionTarget.cpp
The implicit outer MLIR module cannot have conversion patterns applied so
prior to conversion we create _another_ module and nest it for the
module->vm.module conversion to work. If trying to run VM conversion on
an already converted module with both the implicit outer module and
vm.module nested within this would cause module>module>vm.module to be
converted to module>vm.module>vm.module.
Fixes #6307.
> Avoid nesting modules in modules for VM conversion if not needed.

- bindings/python/iree/runtime/tracing.py
- bindings/python/iree/runtime/vm.cc
- build_tools/third_party/libyaml/CMakeLists.txt
- iree/hal/cuda/cuda_device.c
- iree/hal/local/sync_device.c
- iree/hal/local/task_device.c
- iree/hal/vulkan/vulkan_device.cc
- iree/tools/BUILD
- iree/tools/CMakeLists.txt
- iree/tools/iree-run-module-main.cc
- iree/tools/iree-run-trace-main.c
- iree/tools/utils/BUILD
- iree/tools/utils/CMakeLists.txt
- iree/tools/utils/yaml_util.c
- iree/tools/utils/yaml_util.h
This processes yaml trace files from the python tracing mechanism.
There's limited support for binary data encoding that we can extend as needed (for example, allowing string-form tensors instead of base64-encoded values). Things like `element_type` would also be good to make more user-friendly (supporting the same types available on `iree_hal_parse_element_type`).
Outputs are in iree-run-module format today but we could use libyaml's emitter to output in the same format as the trace inputs. This could allow for easy in-place updates of files. Future improvements could add `--verify-results` to read the results from the input yaml and ensure the outputs are equal.
Would be nice to get an end-to-end test in place for this somehow. For now this is still just a first-pass at a dev tool and …
> Adding iree-run-trace binary.

- iree/tools/iree-run-module-main.cc
Running `iree-run-module` with single dash flags are silently ignored while it waits to accept a module file via `stdin`. This leads to the program spinning endlessly without warning on inputs like:
```
./iree-run-module -module_file=/path/to/module.vmfb --entry_function=my_function --function_input=some_input ...
```
`iree-run-module` doesn't consume positional arguments but single dash arguments are treated as such. This will prevent users from hitting confusing error cases with ignored flags. 
Adresses #5931
> Update iree-run-module to error out with more than one positional argument.

- iree/hal/local/loaders/embedded_library_loader.c
- iree/hal/local/loaders/legacy_library_loader.c
- iree/hal/local/loaders/static_library_loader.c
Fixes https://github.com/google/iree/issues/6302
> Fix use of `IREE_TRACE_ZONE_APPEND_TEXT` in library loaders.

- build_tools/cmake/build_riscv.sh
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/common.cfg
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/google.cfg
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/main.cfg
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/presubmit.cfg
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/test.sh
Test IREE build with riscv 32-bit for the bare-metal configuration. It tests
* 32-bit code-gen flow.
* build with the bare-metal config without threading and system library
support.
* Execute the 32-bit codegen workload with 32-bit linux user-space QEMU
emulator.
The CI setup for https://github.com/google/iree/issues/6322
> Add riscv-32 baremetal kokoro scripts

- build_tools/cmake/build_riscv.sh
- build_tools/docker/cmake-riscv/Dockerfile
- build_tools/docker/prod_digests.txt
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/baremetal/riscv32/test.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/riscv64/build_kokoro.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/riscv64/test.sh
Update the environment variables to distinguish the toolchains in
`RISCV_<arch>_<platform>_TOOLCHAIN_ROOT` naming style.
Also setup the `QEMU_<arch>_BIN` environment variables in the docker image
instead of hard-coded them in the kokoro testing scripts.
> Update cmake-riscv docker image

- integrations/tensorflow/build_tools/overlay/mlir-hlo/BUILD.bazel
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir
- iree/compiler/Dialect/LinalgExt/IR/test/roundtrip.mlir
- iree/compiler/InputConversion/MHLO/BUILD
- iree/compiler/InputConversion/MHLO/CMakeLists.txt
- iree/compiler/InputConversion/MHLO/ConvertAndDistributeMHLOToLinalgExt.cpp
- iree/compiler/InputConversion/MHLO/Passes.h
- iree/compiler/InputConversion/MHLO/Passes.td
- iree/compiler/InputConversion/MHLO/test/BUILD
- iree/compiler/InputConversion/MHLO/test/CMakeLists.txt
- iree/compiler/InputConversion/MHLO/test/convert_and_distribute_mhlo_to_linalg_ext.mlir
The pass creates flow.dispatch.workgroups ops and pull the lowered sort op into the body. The workgroup counts are all set to one. Also adds a build method to flow.dispatch.tensor.store.
This is a step towards https://github.com/google/iree/issues/6154
> Add support for lowering mhlo.sort to linalg_ext ops and distrubute them

- iree/compiler/Dialect/LinalgExt/Transforms/ConvertToLoops.cpp
Still annoys me that clang accepts this no problem.
> Fixing build break in MSVC from wrong type used.

- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtInterfaces.h
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtInterfaces.td
Since LinalgExtInterface is a subset of LinalgInterface, we can use
template in convertAnyLinalgOp. analyseLinalg*Ops function has different
implementation because we don't define indexing maps in LinalgExtOp.
Also adds a interface method -- clone.
This is a step towards https://github.com/google/iree/issues/6154
> Add support for bufferizing LinalgExt ops.

- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- iree/compiler/Codegen/CMakeLists.txt
- iree/compiler/Dialect/Flow/IR/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/HAL/IR/CMakeLists.txt
- iree/compiler/Dialect/IREE/IR/CMakeLists.txt
- iree/compiler/Dialect/LinalgExt/IR/CMakeLists.txt
- iree/compiler/Dialect/LinalgExt/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Modules/Check/IR/CMakeLists.txt
- iree/compiler/Dialect/Modules/VMVX/IR/CMakeLists.txt
- iree/compiler/Dialect/Shape/IR/CMakeLists.txt
- iree/compiler/Dialect/VM/IR/CMakeLists.txt
- iree/compiler/Dialect/Vulkan/IR/CMakeLists.txt
- iree/compiler/InputConversion/Common/CMakeLists.txt
- iree/compiler/InputConversion/MHLO/CMakeLists.txt
- iree/compiler/InputConversion/TOSA/CMakeLists.txt
- iree/samples/custom_modules/dialect/CMakeLists.txt
This was a special carveout in service of ALWAYSLINK, which we've gotten
rid of.
While I was here I cleaned up and moved the target conversion logic for
internal targets to bazel_to_cmake_targets.py and removed the hardcoded
subdirectory names.
Fixes https://github.com/google/iree/issues/6363
> Don't exclude gen targets in bazel->cmake

- iree/compiler/Codegen/LLVMGPU/BUILD
- iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
This also enables mhlo.sort testing on cuda backend.
> Add LinalgExt -> loops transform to cuda backend.

- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/stream_ops.mlir
Works around illegal IR that was being generated when size calculations via a tied operand depend on a constant defined in the stream. Since it is an arbitrary choice to copy constants out late, there is no reason to just not copy them out early and save the trouble.
> Hoist constants early during stream lowering.

- iree/compiler/Dialect/LinalgExt/Transforms/ConvertToLoops.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/test/convert_to_loops.mlir
- iree/test/e2e/xla_ops/sort.mlir
According to XLA operation semantics:
> Formally, after the array is sorted, it holds for all index positions
> i, j with i < j that either
>   comparator(v[i], v[j]) = comparator(v[j], v[i]) = false
> or
>   comparator(v[i], v[j]) = true
In this context, the pairs should swap only if the comparison result is
false.
The PR also fixes tests to match the semantics -- replacing `GT` with
`LT`.
> Fix bugs in sort op lowering.

- iree/compiler/InputConversion/MHLO/LegalizeInputTypes.cpp
- iree/compiler/InputConversion/MHLO/test/legalize_input_types.mlir
Ideally we can apply it to all the Linalg ops including structure ops. However, it could break some poly ops like linalg.matmul. The region could be different from native poly ops, since the pass does not know exactly how to handle the body of Linalg structured ops. For now only apply it on non-structured ops which could be created by some direct lowering pass.
This is a step toward https://github.com/google/iree/issues/6399
> Relax LegalizeInputTypesPass to work on non-structured Linalg ops.

- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir
- iree/compiler/Dialect/LinalgExt/IR/test/roundtrip.mlir
The index depth could be others than one. E.g.,
```
%0 = "mhlo.scatter"(%arg0, %arg1, %arg2) ( {
^bb0(%arg3: tensor<f32>, %arg4: tensor<f32>):  // no predecessors
"mhlo.return"(%arg4) : (tensor<f32>) -> ()
}) {indices_are_sorted = false,
scatter_dimension_numbers = {
...
},
unique_indices = false
} : (tensor<1x24x512xf32>, tensor<1x2xi32>, tensor<1x512xf32>)
-> tensor<1x24x512xf32>
}
```
This is a step toward https://github.com/google/iree/issues/6403
> Redefine iree_ext.scatter for having index depth information.

- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/Transforms/BUILD
- iree/compiler/Dialect/LinalgExt/Transforms/CMakeLists.txt
- iree/compiler/Dialect/LinalgExt/Transforms/ConvertToLoops.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/Passes.td
- iree/compiler/Dialect/LinalgExt/Transforms/test/convert_to_loops.mlir
This supports both scalar and slice cases. For slice cases, we will
create a linalg.generic op with parallel loops to handle slices. It also
works for cases that index_depth > 1.
This is a step towards https://github.com/google/iree/issues/6403
> Add support for lowering linalg_ext.scatter to loops + Linalg ops.

- iree/compiler/InputConversion/MHLO/BUILD
- iree/compiler/InputConversion/MHLO/CMakeLists.txt
- iree/compiler/InputConversion/MHLO/ConvertAndDistributeMHLOToLinalgExt.cpp
- iree/compiler/InputConversion/MHLO/test/convert_and_distribute_mhlo_to_linalg_ext.mlir
- iree/test/e2e/xla_ops/scatter.mlir
This will make IREE use linalg_ext path instead of mhlo patterns. It
adds more end-to-end tests and also supports dynamic shapes.
Fixes https://github.com/google/iree/issues/6403
> Add support for lowering mhlo.scatter to LinalgExt ops.

- bindings/python/iree/runtime/hal.cc
- bindings/python/iree/runtime/vm.cc
- iree/base/allocator.c
- iree/base/allocator.h
- iree/base/internal/arena.c
- iree/base/internal/file_path_test.cc
- iree/base/internal/flags.c
- iree/base/time.h
- iree/hal/testing/driver_registry.h
- iree/tools/iree-run-mlir-main.cc
- iree/vm/buffer.c
- iree/vm/buffer_test.cc
- iree/vm/stack.c
This saves 4-8 bytes of stack/heap in any place an allocator is used.
The smaller size (`2*sizeof(void*)`) aids in triggering register-passed
struct arguments in certain calling conventions. Having a generic control
function will also allow us to add new commands in the future for
import/export, queries, etc.
> Switching iree_allocator_t to a single control function ptr.

- docs/developers/get_started/getting_started_riscv_cmake.md
- docs/website/docs/building-from-source/android.md
- docs/website/docs/building-from-source/riscv.md
- docs/website/mkdocs.yml
Update the RISC-V getting started doc to add the rv32-baremetal config.
Add a user-facing doc of RISC-V cross-compile flow.
Part of https://github.com/google/iree/issues/6327
> Update RISC-V docs

- iree/compiler/Codegen/LLVMGPU/BUILD
- iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
The code generated will still be sub-optimal but this fix functionality.
Heuristics for this will come in future patches.
> [CUDA] Fix copy distribution for sizes not aligned on 4

- iree/compiler/Dialect/Flow/Transforms/ConvertConv2DToImg2ColPass.cpp
- iree/compiler/Dialect/Flow/Transforms/test/conv2d_to_img2col.mlir
A pattern to rewrite depthwise convolution with `depth_multiplier = 1` into a `linalg.batch_matvec`. The pattern transposes the input and the filter so channels are outer most dimension . After the transpose inner most dims are separable convolutions where each is a matrix-vector product.
> linalg.depthwise_conv2d -> img2col with batch_matvec

- iree/compiler/Dialect/HAL/Conversion/ConversionTarget.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
- iree/compiler/Dialect/HAL/Conversion/FlowToHAL/test/stream_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALBase.td
- iree/compiler/Dialect/HAL/IR/HALInterfaces.td
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/HALTypes.cpp
- iree/compiler/Dialect/HAL/IR/HALTypes.h
- iree/compiler/Dialect/HAL/IR/test/device_ops.mlir
- iree/compiler/Dialect/HAL/Target/VMVX/test/linking.mlir
- iree/compiler/Dialect/HAL/Transforms/InlineDeviceSwitches.cpp
- iree/compiler/Dialect/HAL/Transforms/MaterializeResourceCaches.cpp
- iree/compiler/Dialect/HAL/Transforms/MemoizeDeviceQueries.cpp
- iree/compiler/Dialect/HAL/Transforms/test/inline_device_switches.mlir
- iree/compiler/Dialect/HAL/Transforms/test/materialize_resource_caches.mlir
- iree/compiler/Dialect/HAL/Transforms/test/memoize_device_queries.mlir
- iree/compiler/Dialect/HAL/Utils/DeviceSwitchBuilder.h
This makes each switch case implicitly capture dominating values and
switches to tablegen-defined match attributes and an attribute interface.
This removes the boilerplate that was associated with queries as now adding
a query is just adding an attribute.
Progress on #6452.
> Simplifying the hal.device.switch and match attribute infra.

- iree/compiler/Dialect/Flow/Transforms/PadLinalgOps.cpp
- iree/compiler/Dialect/Flow/Transforms/test/pad_linalg_ops.mlir
- Use correct result element type and padding value type.
- Allow padding of padded operands if the size isn't an integer
multiple of the padding size.
>  Fix a couple of bugs in PadLinalgOps

- scripts/ir_to_markdown.py
Progress on https://github.com/google/iree/issues/5958, and could be generally useful.
Sample output: https://gist.github.com/ScottTodd/a9de0470eb4cead7a84712c18bff9426.
Note: I get 73 MB from compiling `bert_encoder_unrolled_fake_weights.mlir`, which fails to upload to a gist :P
> Add ir_to_markdown.py utility script.

- iree/hal/vulkan/direct_command_buffer.cc
This adds a command buffer wrapping scope to allow for measuring the total time spent executing commands:
A cool somewhat hidden feature of Tracy is that then if you click on that command buffer zone and check the "group" box you can see a nice summary of which dispatches are taking time within that command buffer:
> Improving tracing of vulkan command buffers/dispatches.

- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/TiledOpInterface.td
- iree/compiler/Dialect/LinalgExt/Transforms/Passes.h
- iree/compiler/Dialect/LinalgExt/Transforms/Passes.td
- iree/compiler/Dialect/LinalgExt/Transforms/Tiling.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/Transforms.h
- iree/compiler/Dialect/LinalgExt/Transforms/test/tiling.mlir
This PR implements an interface to `tensor::InsertSliceOp` by
inheriting from the `TiledOpInterface::ExternalModel` to allow for
tiling `tensor.insert_slice` operation using this interface.
Also change the interface method `getTiledImplementation` to allow the
interface implementation to explicitly also return the sizes of the
tiles. This is required for handling tiling of rank-reduced subtensor
inserts and also cleans up the generated code a bit.
> Add an interface to `tensor::InsertSliceOp` to implement the `TiledOpInterface`

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/InterchangeGenericOp.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/test/interchange.mlir
During dispatchLinalgOnTensor we only tile outer parallel loops so if
the parallel loops are not outer loop we may skip tiling some ops which
will prevent them from being distributed onto several workgroups.
> Interchange linalg generic op to move reduction loops to inner loops

- iree/base/tracing.cc
Splitting this off from working on https://github.com/google/iree/issues/6404.
Sanitizers define these functions, so tracing needs to not define them (or wrap them somehow).
> Make tracing compatible with sanitizers.

- iree/task/task.c
This would lead to a single shard executing more tiles than it should in
a single iteration leading to unbalanced distribution when the tile count
was low.
Fixes #5568.
before (~410ms total for bert):
after (~376ms total for bert):
> Fixing task system off-by-one that was preventing proper distribution.

- iree/samples/static_library/CMakeLists.txt
`static_library_demo` is not a test, so it can't depend on a `TESTONLY` target. We don't check this in CMake, outside of `-DIREE_BUILD_TESTS=OFF` builds, which will fail at configure time.
> Drop TESTONLY from sample target.

- iree/base/time.c
This was all that was needed to build `iree_samples_simple_embedding_simple_embedding_vmvx_sync` using emscripten.
> Use clock_gettime on emscripten.

- docs/website/docs/deployment-configurations/bare-metal.md
Links to the static library documentation and highlights the additional flag necessary to generate a static bare-metal library.
> Documentation Reference for Bare-Metal Static Library

- iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMGPU/test/convert_to_nvvm.mlir
- iree/hal/cuda/descriptor_set_layout.c
- iree/hal/cuda/descriptor_set_layout.h
- iree/hal/cuda/executable_layout.c
- iree/hal/cuda/executable_layout.h
- iree/hal/cuda/graph_command_buffer.c
If multiple sets are used by a kernel the arguments needs to be first
ordered based on the set index.
> [CUDA] Fix mapping of binding to kernel argument with multiple sets.

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/InsertConstantClones.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/test/insert_constant_clones.mlir
This is required for correctness until #5492 properly implements this with
a DFA and hal.stream exists to allow for insertions of efficient clones.
> Inserting a workaround for constant tensors escaping blocks.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/test/tensor_folding.mlir
DenseElementsAttr requires static shape; we will hit assertions
when trying to fold dynamic shaped flow.tensor.splat.
> Don't fold flow.tensor.splat with dynamic shape

- iree/vm/bytecode_dispatch.c
The message used to live in rodata but now may come from any buffer and
we need to ensure that the returned status remains live independently.
> Cloning the status message generated in vm.fail.

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
Vectorization is still disabled for cases where there is a transpose on
the output to workaround a bug in core. This will be expended once the
fix is integrated.
> [CUDA] Unify contraction op config and enable vectorization

- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
Test https://github.com/google/iree/pull/6507 failed after commit due to change in https://github.com/google/iree/pull/6456
> Fix NVVM pipeline test after adding outdates test

- iree/compiler/InputConversion/Common/ConvertUpstreamToIREE.cpp
- iree/compiler/InputConversion/Common/test/convert_upstream_to_iree.mlir
- Adds a conversion pattern to convert single-element tensors that
result from a `tensor.from_elements` op to a `flow.tensor.splat` op.
- This is a step towards cleaning-up the IR after running it through the
detensoring pass.
- In particular, it sets the stage for a canonicalization pattern within
the `flow` dialect that can fold `flow.tensor.splat`, `flow.tensor.load`
pairs of ops into the underlying primitive value (TODO).
See: https://github.com/google/iree/issues/1159.
> Add a pattern to convert tensor.from_elements to flow.tensor.splat.

- iree/hal/cuda/cuda_allocator.c
- iree/hal/cuda/dynamic_symbol_tables.h
- iree/hal/cuda/dynamic_symbols.c
Allocation marked as device local with hoist visible flag were
incorrectly allocation on the host. This improves performance.
> [CUDA HAL] Fix allocation for device local hoist visible case

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/DestructiveUpdateUtils.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/LinalgExt/Transforms/Tiling.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/Transforms.h
Using the pattern to tile + distribute operations that implement the
TiledOpInterface, this change extends dispatch region creation logic
to handle `LinalgExpOp` that implement the tiled op interface.
Also a few clean ups
- Add utility functions to interpret the root and fusion attributes to
make the intent clearer.
- Modify the logic that decides the loops to be partitioned to be more
configurable
- Make the analysis to find tied operands of the dispatch region run
after destructive updates are resolved to use
`flow.dispatch.tensor.load/store`. This seems to be a bug, that
would disallow having any `LinalgOp` not have tied operands either.
- Remove the use of `AffineMinSCFCanonicalizationPattern`. It seems to
hit an assertion (see Issue #6520), also since all loop bounds are
dynamic, …
> Make Dispatch region formation handle `LinalgExtOp`s that implement `TiledOpInterface`.

- iree/hal/local/elf/CMakeLists.txt
Avoids sending C flags to MASM resulting in issues while building with MSVC/MASM.
> C flags were being passed to assembler (masm)

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/IR/TiledOpInterface.h
- iree/compiler/Dialect/LinalgExt/IR/TiledOpInterface.td
- iree/compiler/Dialect/LinalgExt/Transforms/Tiling.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/Transforms.h
- Adds an interface method to get the operands that can be used as
destination for the operation. This allows better structuring of the
patterns for tiling and unifies the way they are applied for both
operations and external models that implement the interface.
- Add an interface to get the loops to be partitioned, along with
default implementation of this.
- Remove duplicate registration.
> NFC: Cleanups to TiledOpInterface and LinalgExtOps.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/IR/test/tensor_folding.mlir
- Adds a canonicalization pattern the fold pairs of such ops into the
primitive value used in the splat op.
- Motivation for adding this is cleaning up after detensoring pass.
See: https://github.com/google/iree/issues/1159.
> Add a pattern to fold flow.tensor.splat-.load pairs into primitives.

- bindings/python/iree/compiler/xla.py
- integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
This can help debugging MHLO import failures. We already do this in the
TF import, but weren't doing it here, probably because MHLO input used
to be synonymous with IREE input.
> Save MHLO input in iree-import-xla

- experimental/rocm/descriptor_set_layout.c
- experimental/rocm/descriptor_set_layout.h
- experimental/rocm/direct_command_buffer.c
- experimental/rocm/dynamic_symbol_tables.h
- experimental/rocm/executable_layout.c
- experimental/rocm/executable_layout.h
- experimental/rocm/rocm_allocator.c
Following CUDA backend updates:
-Fix mapping of bindings to kernel argument with multiple sets.
-Fix allocation for device local hoist visible case.
> [ROCM] bindings with kernels and device local host

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/IR/test/tensor_folding.mlir
Another step towards https://github.com/google/iree/issues/1159 (cc @KareemErgawy-TomTom)
I can fully translate xla_while using this + some pass applications:
```cpp
passManager.addNestedPass<FuncOp>(mlir::createLinalgDetensorizePass());
passManager.addNestedPass<FuncOp>(createConvertUpstreamToIREE());
passManager.addNestedPass<FuncOp>(mlir::createCanonicalizerPass());
```
(and `createConvertToFlowTensorOpsPass`)
collatz and tosa_if are failing and I'm not sure why yet (needs more investigation)
> Add canonicalizer for flow.tensor.splat+reshape -> splat.

- build_tools/bazel/build_core.sh
- build_tools/cmake/test.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build.sh
- iree/samples/simple_embedding/BUILD
- iree/samples/simple_embedding/CMakeLists.txt
We only need one variable to disable CUDA execution tests.
> Remove redundant variable to enable CUDA test

- iree/base/alignment.h
- iree/base/internal/threading_darwin.c
- iree/base/internal/threading_pthreads.c
- iree/base/internal/threading_win32.c
- iree/base/internal/wait_handle_poll.c
- iree/base/internal/wait_handle_win32.c
- iree/hal/allocator_heap.c
- iree/hal/buffer_heap.c
- iree/hal/cuda/cuda_device.c
- iree/hal/cuda/cuda_driver.c
- iree/hal/driver_registry.c
- iree/hal/local/loaders/embedded_library_loader.c
- iree/hal/local/loaders/legacy_library_loader.c
- iree/hal/local/loaders/static_library_loader.c
- iree/hal/local/sync_device.c
- iree/hal/local/task_device.c
- iree/hal/local/task_driver.c
- iree/hal/vulkan/native_descriptor_set_layout.cc
- iree/samples/custom_modules/module.cc
- iree/vm/buffer.c
- iree/vm/bytecode_module.c
- iree/vm/bytecode_module_impl.h
- iree/vm/context.c
- iree/vm/instance.c
- iree/vm/list.c
- iree/vm/native_module.c
Several places where we were doing trailing struct allocations were
not padding to ensure the trailing structs would be properly aligned.
Some could have been VLAs and were switched (woo less pointer math).
Partial fix for #6566.
> Fixing/eliminating/clarifying some runtime struct alignment issues.

- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/SimplifyVariableAccesses.cpp
- iree/compiler/Dialect/Flow/Transforms/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/test/simplify_variable_accesses.mlir
Since there's nothing like this upstream (I know about) this is a naive
result of an afternoon of hacking to solve our immediate problem (variable
accesses interleaved with logic we want to dispatch). This only operates
within basic blocks and does no fancy dataflow analysis leaving a lot of
potential optimizations on the table.
Programs are still correct if this pass is not used but for any model
with a lot of variable updates it's a big win.
CUDA nlp_learn_linalg before (86 submissions, 393ms):
After (1 submission, 269ms):
Additional work on #1124 would be nice as then we could rework
this pass to cover more cases and generalize it to work across HAL too.
Fixes #3883.
> Adding -iree-flow-simplify-variable-accesses pass.

- CMakeLists.txt
- scripts/git/check_submodule_init.py
Checking if git submodules have been initialized and printing warning messages.
Added a python script in `scripts/git/check_submodule_init.py` which will run inside the CMake: `CMakeLists.txt `
- The script won't check for the status of the submodules if not a git repository
- This will only run if python/python3 is available
Fixes #6434
> Run a check_submodule_init script during CMake configure

- iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Codegen/SPIRV/test/convert_to_spirv.mlir
This is a followup to https://github.com/google/iree/pull/6509. 
`hal.interface.binding.subspan` to `spv.GlobalVariable` conversion
is tricky due to their different scopes (function vs. module),
SSA values vs. symbols, and the need to attach `alias` decorations.
Previously we create `spv.GlobalVariable` in the middle of the
conversion procedure, it requires us to pass down a few data
structures to the pattern so that we can access the alias
status. Notably, it requires us to pass in a `SymbolTable` so
that we can unique symbols. The `SymbolTable` needs to be created
before the conversion; otherwise we will see errors. It's relying
on `SymbolTable` and conversion framework implementation details;
so quite opaque.
This commit changes to create the global variables earlier, at the
alias …
> [spirv] Create variables early for conversion and deduplication

- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/test/module_encoding_smoke.mlir
- iree/compiler/Translation/test/smoketest.mlir
- iree/vm/bytecode_dispatch_util.h
This is a hack for #6566 but not a bad idea in general. Future revisions
of the bytecode format will take this into account natively such that
we don't need any unaligned loads at runtime.
> Forcing 2-byte alignment on VM register lists.

- CMakeLists.txt
- build_tools/cmake/build_tracing.sh
- docs/developers/developing_iree/profiling_with_tracy.md
- docs/developers/get_started/cmake_options_and_variables.md
- iree/compiler/Utils/CMakeLists.txt
- iree/compiler/Utils/TracingUtils.cpp
- iree/compiler/Utils/TracingUtils.h
General improvement and workaround for issues like https://github.com/google/iree/issues/6404.
I opted to keep this change pretty localized by making `IREE_ENABLE_COMPILER_TRACING` simply extend `IREE_ENABLE_RUNTIME_TRACING`. If we wanted to support _just_ tracing the compiler without also tracing the runtime, that would require some deeper changes to C defines and checks.
> Add a separate option for enabling compiler tracing.

- iree/compiler/Codegen/LLVMCPU/BUILD
- iree/compiler/Codegen/LLVMCPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUVectorization.cpp
- iree/compiler/Codegen/Utils/BUILD
- iree/compiler/Codegen/Utils/CMakeLists.txt
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/Transforms/ConvertToLoops.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/test/convert_to_loops.mlir
- iree/compiler/Dialect/LinalgExt/Transforms/test/tiling.mlir
- iree/test/e2e/xla_ops/scatter.mlir
This change enables the end-to-end execution of ops that implement the
`TiledOpInterface` on CPU. To enable this
- Change the CPU lowering configuration to treat `LinalgExtOp`s as
"compute" ops as well (in additional to `LinalgOp`). Use a default
for all ops that are not explicitly set.
- Change the `TiledOpInterface` implementation of `linalg_ext.scatter`
by specifying number of loops to be same as the number of dimensions
of the `update`. This allows tile + distribution of dimensions that
are not scattered as well. This is needed for effective
parallelization (especially on GPU that is to come)
- The above necessitated changes to `ConvertToLoops` pass to not have
patterns per op, but rather use the interface to lower all ops that
implement the `generateScalarImplementation` method.
Also …
> End-to-end CPUexecution of ops implementing `TiledOpInterface`.

- iree/compiler/Dialect/LinalgExt/IR/LinalgExtInterfaces.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir
- iree/compiler/Dialect/LinalgExt/IR/test/roundtrip.mlir
The linalg_ext.fft ops take `stage` as input where is an index type.
Like other Linalg ops, we relax the limitation to make LinalgExt ops
allow scalar operand.
A step toward https://github.com/google/iree/issues/6477
> Introduce linalg_ext.fft to LinalgExt dialect.

- iree/hal/cuda/stream_command_buffer.c
This is a new check in clang that is going to be enabled globally
internally soon. It's not yet available in a released clang. If it ends
up being annoying, we could disable it for all of IREE internally. We
could also do that now.
Regardless, I think this fix is probably good, since we've identified
the issue. This is currently the only failure in IREE core.
> Fix cuda hal for `-Wunused-but-set-parameter`

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
Progress on https://github.com/google/iree/issues/1159
With this pass enabled, some programs do not yet compile fully through IREE's full mlir-to-vm pipeline. I think it would still be useful to wire up this way so others can more easily experiment.
> Add linalg detensorizing behind a flag.

- iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMGPU/test/convert_to_nvvm.mlir
- iree/compiler/Codegen/LLVMGPU/test/convert_to_rocdl.mlir
HAL always ensure that buffer are 16 bytes aligned, this is needed to be
able to infer load/store alignment to generate load4/store4
> [CUDA] Mark argument pointers as align16

- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/IR/test/roundtrip.mlir
- iree/compiler/Dialect/LinalgExt/Transforms/test/convert_to_loops.mlir
- iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- iree/compiler/InputConversion/MHLO/test/convert_mhlo_to_linalg_ext.mlir
- Allow linalg_ext.fft takes optional coefficients inputs. If
coefficients are given, it will load the value from them when lowering
to loops.
- Since the fft length is static most of time, we create constant
coefficients tensors when lowering from MHLO to LinalgExt.
This improves RFFT kernels from 14.5 ms to 5 ms on tensor<325x1024xf32>
inputs.
This is a step toward https://github.com/google/iree/issues/6477
> Precompute coefficients for FFT kernels at compile time.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/test/dispatch_ops.mlir
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups.mlir
- iree/compiler/Dialect/Flow/IR/test/stream_folding.mlir
- iree/compiler/Dialect/Flow/IR/test/stream_ops.mlir
The ops have always held the types/dims but they were elided when printing.
Now type and dimension changes can be fully specified and round-tripped.
This allows streams and dispatch regions to change types/shapes.
Reverts #6188.
Fixes #6075.
Fixes #6185.
Fixes #6420.
> Change tied operand formatting to allow type changes.

- build_tools/cmake/iree_copts.cmake
- iree/vm/bytecode_dispatch.c
- iree/vm/bytecode_dispatch_util.h
> Fixing gcc/clang builds when i64/f32 VM extensions are disabled.

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
- build_tools/cmake/test.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
Hanging forever is extremely unhelpful. Setting test-specific timeouts,
which could be derived from the Bazel timeouts as part of Bazel->CMake
would be helpful, but in the meantime, just setting a reasonable upper
bound should get us a lot of mileage. This matches the Bazel timeout for
"long" tests, which is the maximum timeout we have for all of our tests
that we run in our CI.
Part of https://github.com/google/iree/issues/5121
> Add 15 minute test timeout to all ctest invocations

- bindings/python/iree/runtime/CMakeLists.txt
- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/function_test.py
- docs/developers/design_docs/function_abi.md
- integrations/tensorflow/iree_tf_compiler/TF/SavedModelToIreeABI.cpp
- integrations/tensorflow/iree_tf_compiler/TF/test/saved_model_to_iree_abi.mlir
* Has the effect that V1 saved models just use regular args (vs vm.list) for their implicit keyword arguments.
* Also "inlines" the first level result (tuple/list/dict) so that simple, one level nests (i.e. dict of keyword results) is compiled as just a normal multi-result function.
* Breaking change: The python API will not be able to process structured invocations across this commit.
* Still working on unit test coverage, which is non trivial.
> Flatten first structure level of tensorflow args and results.

- bindings/python/iree/compiler/tf.py
- integrations/tensorflow/iree_tf_compiler/TF/BUILD
- integrations/tensorflow/iree_tf_compiler/TF/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TF/Passes.h
- integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp
Tosa can import more than TFLite models, being able to import directly from
Tensorflow itself. Support this path as an option instead of importing via HLO.
> Add a tf-to-tosa option for the tensorflow importer

- iree/compiler/Codegen/LLVMGPU/BUILD
- iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUDistributeSharedMemoryCopy.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPURemoveTrivialLoops.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUUtils.h
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/LLVMGPU/test/BUILD
- iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
- iree/compiler/Codegen/LLVMGPU/test/distribute_wg_copy.mlir
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- iree/compiler/Codegen/LLVMGPU/test/rocdl_pipeline_test.mlir
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
- iree/compiler/Dialect/HAL/IR/LoweringConfig.td
Move lowering of shared memory copy into a separate pass and start using
vector distribution for the cases well aligned.
Add a new pipeline for simt matmul, we will later add another one for
tensorcore one.
> [CUDA] Improve shared memory copy lowering

- build_tools/mako/configuration.py
We already have this covered in the new benchmark pipeline, which
is almost ready as the default. So this is a early step for
migration over.
> Disable old MobileBERT f16 GPU benchmarks

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- Distributes among the first two iterators (tile iterators).
- Sets KernelDispatch cpu tiling configurations.
> Tile and distribute linalg.mmt4d op

- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
Avoid inserting bariers between back to back copy to workgroup memory
> [CUDA] Optimize barier insertion

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
It got disabled by mistake during refactoring
> [CUDA] Re-enable vectorization for generic op

- benchmarks/TensorFlow/CMakeLists.txt
This commit regenerates all TensorFlow mid-level input models
using `*-import` binaries and Python bindings built from IREE
source at commit 9e4b02e4b.
> Update TensorFlow mid-level input models used for benchmarking

- iree/compiler/Translation/IREEVM.cpp
- iree/compiler/Translation/IREEVM.h
- llvm-projects/iree-compiler-api/CMakeLists.txt
- llvm-projects/iree-compiler-api/build_tools/smoketest.py
- llvm-projects/iree-compiler-api/include/iree-compiler-c/Compiler.h
- llvm-projects/iree-compiler-api/lib/CAPI/CMakeLists.txt
- llvm-projects/iree-compiler-api/lib/CAPI/Compiler.cpp
- llvm-projects/iree-compiler-api/lib/CMakeLists.txt
- llvm-projects/iree-compiler-api/python/CMakeLists.txt
- llvm-projects/iree-compiler-api/python/CompilerModule.cpp
- llvm-projects/iree-compiler-api/python/iree/compiler/api/driver.py
- llvm-projects/iree-compiler-api/setup.py
* In-memory interop with MLIR C and Python API objects.
* Exposes a low-level driver API for constructing pass pipelines, options, translating/emitting (expect a higher level user API similar to what we already have which shells out to iree-translate).
* Includes access to all dialects that IREE can input.
* Minimal options plumbed through.
* Does not yet plumb through other exits (i.e. emit-c).
* It would be nice to do some more code organization on the C++ side, but that doesn't change the C-API.
* Will create a CLI later which uses the C-API (which can dynamic link and save us space).
> Create a first-class IREE compiler C and Python API.

- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertVariableOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/allocator_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/buffer_view_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/constant_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/control_flow_ops.mlir
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/variable_ops.mlir
- iree/compiler/Dialect/HAL/Target/VMVX/test/linking.mlir
- iree/compiler/Dialect/HAL/Target/VMVX/test/smoketest.mlir
- iree/compiler/Dialect/VM/Conversion/IREEToVM/test/byte_buffer_ops.mlir
- iree/compiler/Dialect/VM/Conversion/IREEToVM/test/hint_ops.mlir
- iree/compiler/Dialect/VM/Conversion/IREEToVM/test/list_ops.mlir
- iree/compiler/Dialect/VM/Conversion/MathToVM/test/arithmetic_ops.mlir
- iree/compiler/Dialect/VM/Conversion/MemRefToVM/test/load_store_ops.mlir
- iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/arithmetic_ops.mlir
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/assignment_ops.mlir
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/comparison_ops.mlir
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/control_flow_ops.mlir
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/func_attrs.mlir
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/structural_ops.mlir
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/test/global_folding.mlir
- iree/compiler/Dialect/VM/IR/test/structural_ops.mlir
- iree/compiler/Dialect/VM/Transforms/GlobalInitialization.cpp
- iree/compiler/Dialect/VM/Transforms/test/deduplicate_rodata.mlir
- iree/compiler/Dialect/VM/Transforms/test/global_initialization.mlir
- iree/compiler/Dialect/VM/Transforms/test/ordinal_allocation.mlir
- iree/samples/custom_modules/dialect/test/conversion.mlir
hal.variable -> vm.global was not preserving visibility, and vm.func was
set as public even though they are all private by default.
There was also nasty double-spaced printing happening due to the custom
assembly format so I changed it to print the default visibility of
'public' when unspecified.
> Fixing VM symbol visibility.

- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/base/allocator.h
- iree/base/api.h
- iree/base/string_builder.c
- iree/base/string_builder.h
- iree/base/string_builder_test.cc
- iree/hal/string_util.c
This could be used in more places in the future such as the HAL
string_util to avoid so much pointer manipulation.
> Adding iree_string_builder_t.

- build_tools/cmake/iree_bytecode_module.cmake
Switches to explicitly passing the flags. The previous default flag
`-iree-mlir-to-vm-bytecode-module` wasn't a useful default as it is
required to additionaly specify backends via
`-iree-hal-target-backends=`.
> Drop FLAGS default

- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.h
- iree/compiler/Dialect/VM/Target/Bytecode/TranslationFlags.cpp
This allows for a vm dialect dump immediately prior to serialization.
Source locations in the IR are tagged with the locations in the file.
> Adding -iree-vm-bytecode-source-listing= flag.

- iree/compiler/Dialect/VM/Target/Bytecode/BUILD
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.h
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/CMakeLists.txt
- iree/compiler/Dialect/VM/Target/Bytecode/DebugDatabaseBuilder.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/DebugDatabaseBuilder.h
- iree/schemas/bytecode_module_def.fbs
These - when not stripping - will embed function bytecode locations.
These faithfully mirror the Location types in MLIR. It's up to the runtime
tooling to interpret them for presentation.
This is not a great format: it does do basic string and location deduping
but this really calls for delta-coded bytecode offsets and inlining of
file line/col values. But there's zero reason to deploy this and 95% of
the IR in our modules is folded into rodata executable blobs so this is
fine for now.
Future changes will introduce the runtime wrappers. TBD is register
mappings (simulating "locals") and type information.
Fixes #1199. (enough to call it done for now)
Progress on #55.
> Adding bytecode debug databases.

- build_tools/buildkite/samples.yml
- build_tools/docker/prod_digests.txt
- build_tools/docker/samples/Dockerfile
Expecting this to fix the https://buildkite.com/iree/iree-samples CI pipeline which has been broken since the Python 3.7 upgrade in https://github.com/google/iree/pull/6611
> Install python3.7-venv in samples Docker image.

- iree/base/config.h
- iree/vm/bytecode_module.c
- iree/vm/context.c
- iree/vm/invocation.c
- iree/vm/module.c
- iree/vm/module.h
- iree/vm/stack.c
- iree/vm/stack.h
These annotate status messages from within VM invocations with the cross-module backtrace. Bytecode modules that have a debug database embedded will include the source locations in a format closely matching the MLIR pretty printing of LocationAttr.
Users who don't care about backtraces can disable them with `-DIREE_VM_BACKTRACE_ENABLE=0` to save on binary size. Modules get debug databases by default but can be stripped with `-iree-vm-bytecode-module-strip-source-map`. Stacks are still useful if symbol names are included (you'll see func + pc), while the smallest module files stripped with `-iree-vm-bytecode-module-strip-symbols` as well will just show function ordinals/pcs that we could later symbolize offline.
Example error message showing original model source location:
```
E …
```
> Adding runtime VM backtraces.

- build_tools/cmake/iree_c_module.cmake
- iree/samples/emitc_modules/CMakeLists.txt
- iree/vm/test/emitc/CMakeLists.txt
Harmonizes `iree_c_module` with `iree_bytecode_module`. The latter
dropped setting a default flag and switched to explicitly passing the
flags.
> Harmonize `iree_c_module`: Drop default flag

- CMakeLists.txt
- build_tools/cmake/iree_third_party_cmake_options.cmake
- iree/tools/CMakeLists.txt
- llvm-projects/iree-compiler-api/CMakeLists.txt
- llvm-projects/iree-dialects/CMakeLists.txt
* Adds a cmake dep on the IREE dialect, which is enough to make sure it is building. Can't actually use it until I also do bazel nonsense.
* Reworks all of IREE to use a unified mechanism for building LLVM external projects (mlir-hlo and iree-dialects).
* Requires mlir-hlo bump to include: https://github.com/tensorflow/mlir-hlo/commit/392824379d2120460be19647952df3866efddd84
* More include hacking. Really needs to be fixed upstream and annoying until then.
> Includes the iree-dialects project in the main IREE build.

- iree/compiler/Codegen/Common/SetNumWorkgroupsPass.cpp
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/KernelDispatchUtils.cpp
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
The number of workgroups is computed in a way that is not similar to
how it is done on the tile + distribute path. Fixing that fixes the
remaining correctness issues.
> Fix bug in lowering of ops through DistributeToGlobalID pipeline.

- CMakeLists.txt
Builds the EmitC dependent code by default in CMake builds if the
compiler is built.
> Build EmitC by default

- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/VectorizeMMT4d.cpp
- iree/compiler/Codegen/Common/test/BUILD
- iree/compiler/Codegen/Common/test/CMakeLists.txt
- iree/compiler/Codegen/Common/test/vectorize_linalg_mmt4d.mlir
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUVectorization.cpp
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
- iree/test/microbenchmarks/linalg_mmt4d.mlir
This converts tiled `linalg.mmt4d` to `vector.contract and adds a microbenchmark 
that showed its 1.7x faster than linalg.matmul 
```
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
BM_mmt4d_384x384x512/process_time/real_time        3.66 ms         3.65 ms          191
BM_matmul_384x384x512/process_time/real_time       6.29 ms         6.27 ms          111
```
> Tiled linalg.mmt4d -> vector.contract conversion

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREE/IREEBase.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREE/IREEDialect.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREE/IREEDialect.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREE/IREEOps.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREE/IREEOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/IREE/IREEDialect.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/IREE/IREEOps.cpp
* A selection of types and ops that I have found useful to use from frontends.
* Mostly 1:1 with internal dialects, with the exception of cast ops, which I disaggregated to simplify.
* Stripped most builders, verifiers, canonicalizers, op interfaces, etc in favor of pure declarative.
* No tests yet. Will test as part of the transforms to lower level.
> Start to populate the IREE dialect.

- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertBufferOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/buffer_ops.mlir
Fixes https://github.com/google/iree/issues/6712
With this, the [collatz control flow test](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/control_flow_test.py) compiles fully and runs with correct results using the `-iree-flow-enable-linalg-detensorize -iree-vm-target-extension=f32` flags. One step closer to general support for https://github.com/google/iree/issues/1159.
> Bitcast int->float out of buffer load ops as needed.

- iree/hal/local/elf/platform.h
- iree/hal/local/elf/platform/apple.c
- iree/hal/local/elf/platform/linux.c
Segments may start at arbitrary locations and require that we are aligned
to the natural page size of the OS before calling into mmap/mprotect.
> Fixing loading embedded ELFs with unaligned segments on linux/mac.

- .github/workflows/lint.yml
- iree/base/internal/file_io.c
- iree/base/internal/file_io.h
- iree/tools/test/iree-benchmark-module.mlir
- iree/tools/test/iree-run-module.mlir
- iree/tools/test/multiple_args.mlir
- iree/tools/test/multiple_exported_functions.mlir
- iree/tools/test/repeated_return.mlir
- iree/tools/test/scalars.mlir
- iree/tools/utils/trace_replay.c
Now iree-benchmark-trace/iree-run-trace can be used from the
command line without the need for file paths embedded in the trace.
Just set the module path to `<stdin>` instead of a file name and pipe in
the vmfb.
Example:
```yaml
type: module_load
module:
name: module
type: bytecode
path: <stdin>
```
```bash
iree-translate -iree-input-type=mhlo -iree-hal-target-backends=vmvx -iree-mlir-to-vm-bytecode-module foo.mlir | \
iree-run-trace --driver=vmvx trace.yaml
```
> Adds support for sourcing referenced trace modules from stdin.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
> Reduce default tile size used by default to 64 from 128 to expose more parallelism

- benchmarks/TensorFlow/CMakeLists.txt
This refreshed the mid-level input models for benchmarking
using tools compiled at f47e711f679dbbdf3f515a3d233786ae155bdc5f.
> Regenerate benchmark models after breaking change

- llvm-external-projects/iree-dialects/lib/Dialect/IREE/IREEDialect.cpp
It wasn't adding any types, resulting in confusing errors.
> Fix typo in IREEDialect.cpp

- iree/compiler/Dialect/HAL/Target/CUDA/BUILD
- iree/compiler/Dialect/HAL/Target/CUDA/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- iree/compiler/Dialect/HAL/Target/CUDA/LLVMPasses.h
- iree/compiler/Dialect/HAL/Target/CUDA/NoLoopUnrollPass.cpp
- iree/test/e2e/models/BUILD
- iree/test/e2e/models/CMakeLists.txt
The bug https://bugs.llvm.org/show_bug.cgi?id=48771 happens easily from
the code generated by scf.for lowering. To workaround it we mark all the
loops as nounroll right before llvm backend. This can be removed once we
move to an older driver for all the system we care about.
This also enables model tests that are now working.
> [CUDA] Add workaround for cuda driver bug

- scripts/git/google_to_main.sh
- scripts/git/main_to_google.sh
- scripts/git/update_llvm_dependent_submodules.sh
I fixed this for update_llvm_dependent_submodules.sh in
https://github.com/google/iree/pull/4357 but missed the main<->google
scripts, which we didn't notice because all the build cops already had
that config setting.
Tested:
Ran scripts in both directions, creating
https://github.com/google/iree/pull/6783 and
https://github.com/google/iree/pull/6784
> Update how we get the fork remote name in build cop scripts

- benchmarks/TensorFlow/CMakeLists.txt
- iree/compiler/Codegen/SPIRV/KernelDispatchUtils.cpp
- iree/compiler/Codegen/SPIRV/Passes.cpp
- iree/test/e2e/regression/linalg_ops.mlir
Current configuraiton selection in presence of operand fusion relies
on getting the original problem size. The current approach works
reliably only on buffer ops. So move bufferization before
configuration selection.
> Move bufferization before configuration selection.

- bindings/python/iree/compiler/core.py
- iree/tools/iree-translate-main.cc
This is a bit hacky, but it's the best way we could determine for
debugging weird intermittent crashes with unsymbolized stack traces that
we're seeing in some integration tests (the non-hermetic tests that we
only run internally at the moment).
The stack traces we get are offet, so we need to know the offset to pass
to llvm-sybmolizer `--adjust-vma`. Printing the address of main allows
us to calculate this offset. Additionally, because of ASLR, we need the
offset for the particular run that crashed.
Reproducing the failure locally has been tricky and it has obstinately
refused to appear with manual reruns with this modification patched in.
Since, while it's hacky, this doesn't really cause any harm, we decided
to commit the change to hopefully get a usable stack trace.
> Print the address of `main` in iree-translate (optionally)

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.h
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.h
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/type_conversion.mlir
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/test/add.mlir
- iree/compiler/Dialect/VM/Target/C/test/calling_convention.mlir
- iree/compiler/Dialect/VM/Target/C/test/constant_ops.mlir
- iree/compiler/Dialect/VM/Target/C/test/control_flow.mlir
- iree/vm/ops_emitc.h
- iree/vm/test/call_ops.mlir
This moves more logic from the printer into the conversion pass.
Additionally fix initialization of `iree_vm_ref_t` variables and add basic support for function calls with arguments of ref type.
> Generate API functions in VMToEmitC conversion pass

- bindings/python/iree/runtime/status_utils.cc
- iree/base/allocator.c
- iree/base/internal/flags.c
- iree/base/status.c
- iree/base/status.h
- iree/hal/buffer_heap.c
- iree/hal/local/elf/elf_module.c
- iree/hal/local/elf/elf_module.h
- iree/hal/local/elf/platform.h
- iree/hal/local/elf/platform/apple.c
- iree/hal/local/elf/platform/generic.c
- iree/hal/local/elf/platform/linux.c
- iree/hal/local/elf/platform/windows.c
With these changes the only place using alternative allocation is the iree_status_t allocator (because that must be aligned) and that location is allowed to fail allocation gracefully (and in super embedded scenarios status allocation should be disabled entirely!). `iree_allocator_system()` is now only used during status allocation and as such when disabled the system allocator should be stripped during linking.
> Removing uses of non-iree_allocator_t allocation in the runtime.

- build_tools/cmake/iree_macros.cmake
- build_tools/cmake/iree_python.cmake
Ninja always creates the directories for its outputs, but apparently
Make doesn't.
Tested: ran a build with make and it now completes successfully.
Fixes https://github.com/google/iree/issues/6801
> Explicitly create parent directory before creating symlink

- iree/compiler/Codegen/SPIRV/Passes.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorize.cpp
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize.mlir
Now we have dynamic pipeline and ConvertToGPUPass is out of the
TileAndVectorize pipeline. So we can sort out this weird ordering!
> [spirv] Move Linalg to Loop conversion out of TileAndVectorizePass

- iree/compiler/Dialect/VM/Analysis/ValueLiveness.cpp
MSVC (at least) was evaluating the insertion prior to querying the size
leading to an off-by-one when printing.
> Fixing undefined behavior in value liveness test printing.

- integrations/tensorflow/WORKSPACE
Instead of using all of TF's configuration of dependencies, we let
IREE's take precedence. This results in less surprising behavior when
editing IREE submodules and expecting a change to the integrations build
at the cost of building TF in a configuration more different from the is
one they use.
This didn't used to be possible because none of TF was configured with
`maybe`, but https://github.com/tensorflow/tensorflow/commit/7ed9c675
added similar functionality to `tf_http_archive`. This was more recently
blocked on TF's incompatibility with the upstream build files, but with
the removal of unnecessary references to
[`mlir:subpackages`](https://github.com/tensorflow/tensorflow/commit/417639263326)
and
[`mlir:friends`](https://github.com/tensorflow/tensorflow/commit/400d63c99ffc)
that …
> Use IREE submodule dependencies in TF integrations build

- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/constant_ops.mlir
- iree/compiler/Dialect/Util/IR/UtilOps.cpp
- iree/compiler/Dialect/Util/IR/UtilOps.td
- iree/compiler/Dialect/VM/Conversion/UtilToVM/ConvertGlobalOps.cpp
- iree/compiler/Dialect/VM/Conversion/UtilToVM/test/global_ops.mlir
- iree/compiler/Dialect/VM/IR/VMBase.td
- iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Dialect/VM/IR/test/BUILD
- iree/compiler/Dialect/VM/IR/test/CMakeLists.txt
- iree/compiler/Dialect/VM/IR/test/global_folding.mlir
- iree/compiler/Dialect/VM/IR/test/structural_folding.mlir
- iree/compiler/Dialect/VM/IR/test/structural_ops.mlir
- iree/compiler/Dialect/VM/Transforms/GlobalInitialization.cpp
- iree/compiler/Dialect/VM/Transforms/test/global_initialization.mlir
The existing mechanism made it impossible to have multiple globals
initialized with the results of a single call; now one can initialize
globals with arbitrary code while preserving the invariant that each
global is initialized in an explicit order.
Additional verifiers can be added that ensure proper module initialization
ordering (no loads before initialized, etc) - filed as #6824.
Future changes will apply a similar refactoring to `util.global`.
> Adding vm.initializer and making global initialization nicer.

- iree/compiler/Codegen/SPIRV/test/BUILD
- iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- iree/compiler/Codegen/SPIRV/test/promote_workgroup_memory.mlir
This causes hangs when running ctest on Windows.
> Disabling promote_workgroup_memory.mlir run line.

- third_party/mlir-emitc/include/emitc/Target/Cpp/CppEmitter.h
- third_party/mlir-emitc/lib/Target/Cpp/TranslateToCpp.cpp
Takes over upstream changes:
* iml130/mlir-emitc@e973e19
* iml130/mlir-emitc@25c55a9
* iml130/mlir-emitc@ec53616
* iml130/mlir-emitc@5da8961
> Integrate upstream cpp emitter changes

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.h
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops_f32.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/assignment_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/assignment_ops_f32.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/assignment_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/comparison_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/comparison_ops_f32.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/comparison_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops_f32.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/conversion_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/conversion_ops_f32.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/conversion_ops_i64.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/shift_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/shift_ops_i64.mlir
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/vm/ops_emitc.h
- iree/vm/test/call_ops.mlir
- iree/vm/test/global_ops.mlir
The generated code for function calls works as follows:
On the call-site:
- create an `iree_vm_ref_t` for every ref operand and result
- populate new operand refs with `iree_vm_ref_retain_or_move(origOperand, newOperand)`
In the callee:
- populate result arguments with `iree_vm_ref_move(origResult, outArgResult)`
Additionally conversions for global ref ops were added.
> Support global ref ops and fix passing of refs on function boundaries in the C target

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
- iree/compiler/Dialect/HAL/IR/LoweringConfig.cpp
- iree/compiler/Dialect/HAL/IR/LoweringConfig.td
- iree/test/e2e/regression/BUILD
- iree/test/e2e/regression/CMakeLists.txt
- iree/test/e2e/regression/lowering_config.mlir
Changes here (along with pending LLVM/MHLO changes) allow the CPU
compilation to be controlled using lowering configuration that is
specified on the operation. To plumb this through, the lowering config
can be used to specify a pass-pipeline and workgroup size as
well.
> End-to-end example for lowering config driver lowering.

- .github/workflows/schedule_snapshot_release.yml
- .github/workflows/validate_and_publish_release.yml
An external user can track the particular branch to sync to the latest
snapshot.
This fixes https://github.com/google/iree/issues/5143
> [snapshot release]: Push the snapshot to a snapshot branch

- iree/compiler/InputConversion/Common/IREEImportPublic.cpp
- iree/compiler/InputConversion/Common/test/iree_import_public.mlir
This was resulting in `std.call` not being converted properly.
> [iree-import-public] Copy attrs in generic pattern.

- iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/Passes.cpp
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorToCooperativeMatrix.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- iree/compiler/Codegen/SPIRV/Utils.cpp
- iree/compiler/Codegen/SPIRV/Utils.h
- iree/compiler/Codegen/SPIRV/test/convert_to_spirv.mlir
- iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_matrix.mlir
- iree/compiler/Codegen/SPIRV/test/pipeline_matmul_vectorization.mlir
- iree/compiler/Codegen/SPIRV/test/set_lowering_config.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/vector_to_cooperative_matrix.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_elementwise_ops.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_matmul.mlir
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Transforms/MaterializeInterfaces.cpp
Currently the native vector size is just set through an LLVM-style
flag in the LLVMCPU backend. Instead use the llvm::TargetTransformInfo
to get this information.
Also deprecate LLVMCPUCodegenOptions. Instead annotate the necessary
information on the `hal.executable.variant` and use when necessary.
> Use llvm::TargetTransformInfo for native vector size.

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
It's approaching the 30min limit. This is to get us more grace time.
Need to look at the benchmarks and perform configuration
tweaking/pruning/cleanup.
> Increase benchmarking timeout to 40mins as we have more benchmarks

- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
To start creating the memrefs for the output (when bufferizing a
`flow.tensor.store`), the result buffer has to be allocated before any
uses of it. Replace the crufty insertion point search with just
cloning of operations. They get CSE-ed anyway.
> NFC: Remove crufty insertion point search.

- benchmarks/README.md
I haven't actually followed these steps, so please offer corrections :)
In particular, was there a gist for regenerating model files and updating the GCS bucket? I'm wondering how I would go about adding a model from [keyword_spotting_streaming_test.py](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/keras/keyword_spotting_streaming_test.py) to that gist + the bucket.
> Add README to benchmarks/.

- .github/workflows/validate_and_publish_release.yml
Fix https://github.com/google/iree/runs/3491586526?check_suite_focus=true
with a long enough fetch depth so the latest-snapshot branch can be
properly updated.
Test offline with the workflow CLIs and the testing branch can be
properly fast-forwarded.
> [snapshot] Fix checkout fetch depth to update the latest-snapshot branch

- iree/hal/allocator.c
The memory stats is shown in Bytes. Fix the printout unit.
```
EXEC @simple_mul
result[0]: hal.buffer_view
4xf32=1 4 9 16
[[ iree_hal_allocator_t memory statistics ]]
HOST_LOCAL:           32B peak /           32B allocated /           32B freed /            0B live
DEVICE_LOCAL:           16B peak /           16B allocated /           16B freed /            0B live
```
> Fix iree_hal_allocator memory statistics format

- .github/workflows/copybara_fixup.yml
- .github/workflows/publish_website.yml
- .github/workflows/schedule_snapshot_release.yml
This is mostly harmless since they hard fail pretty quickly, but
annoying for people who fork IREE.
> Don't run unnecessary workflows in people's forks

- build_tools/cmake/iree_check_test.cmake
@antiagainst noticed that https://github.com/google/iree/pull/6352 accidently disabled our check tests when cross compiling on the https://buildkite.com/iree/iree-android-arm64-v8a pipeline.
Before: https://buildkite.com/iree/iree-android-arm64-v8a/builds/4550
After: https://buildkite.com/iree/iree-android-arm64-v8a/builds/4551
That PR forced `IREE_TARGET_BACKENDS_TO_BUILD` to an empty list when `IREE_BUILD_COMPILER` is off, which led to overly aggressive filtering in `iree_check_test.cmake`.
> Fix check tests being disabled when cross compiling.

- benchmarks/TFLite/CMakeLists.txt
`MOBILENETSSD_FP32_MODULE` should be `MOBILESSD_FP32_MODULE`.
> Fix wrong `MOBILENETSSD_FP32_MODULE` and sort TFLite benchmarks

- bindings/python/iree/compiler/core.py
This shows up in jupyter notebooks with a scary red box.
> Don't print main address

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- iree/compiler/Dialect/Shape/Transforms/FunctionSignatureExpansionPass.cpp
- iree/compiler/Dialect/Shape/Transforms/Passes.h
- iree/compiler/Dialect/Shape/Transforms/test/expand_function_dynamic_dims.mlir
- iree/compiler/Dialect/Shape/Transforms/test/expand_function_ranked_shape_dims.mlir
This also makes them module passes, which they have to be since they
mutate the function signature itself (this also manifested as the
verifier not properly running).
I also filed an upstream bug because it is too hard to do these sorts of
call graph rewrites:
https://bugs.llvm.org/show_bug.cgi?id=51740
> Extend function expansion passes to support calls

- iree/compiler/Codegen/SPIRV/AdrenoConfig.cpp
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/KernelConfig.h
- iree/compiler/Codegen/SPIRV/MaliConfig.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTileAndDistribute.cpp
- iree/compiler/Codegen/SPIRV/test/BUILD
- iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- iree/compiler/Codegen/SPIRV/test/config_adreno_conv.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize.mlir
Similar to matmul, this enables tiling and vectorizing conv ops for
Adreno GPUs.
The goal is to eventually promote what's here as the default for all
targets, including Mali GPUs, so that we can remove the hardcoded
known good configurations. But for now there are stability issues
in the lab phones with Mali GPUs, making it hard to evaluate. So
start with Adreno to make sure they work fine.
Along the way, moved the "forth-level" tiling into the pattern itself.
It's really fundamentally different than the others. We don't have
four levels of compute hierarchies on GPU to map to. We just used
it as a way to materialize the loops around filter height and width.
It's required for applicability and correctness for the pattern
itself and is always the same, not tunable knobs that change …
> [spirv] Add conv CodeGen configuration for Adreno GPUs

- iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- iree/compiler/InputConversion/MHLO/test/convert_mhlo_to_linalg_ext.mlir
MHLO ops use signed (although written as signless for historical
reasons) and unsigned ops. The upstream MHLO->Linalg already handles
this and we need to handle it here as well.
In addition, this changes the approach to dealing with detensorizing,
relying more heavily on the dialect conversion framework type converter.
This leaves things as unrealized_conversion_cast ops, to be cleaned up
later after lowering the rest of MHLO. We could continue to use "real"
ops for [de]tensoring, but we need unrealized_conversion_cast for
signedness conversions anyway, so I think it's cleaner to use it
everywhere. It's perhaps unfortunate because really the correct cast
there *is* a bitcast, but like all std ops, std.bitcast does not support
[un]signed integers.
Finally, it adds a bunch of ops for …
> Extend linalg_ext lowering to handle signedness and more ops

- iree/compiler/Dialect/Shape/Transforms/FunctionSignatureExpansionPass.cpp
- iree/compiler/Dialect/Shape/Transforms/test/expand_function_ranked_shape_dims.mlir
The code was copypasted from upstream DecomposeCallGraphTypes, which is
unused and had a latent bug for materializing 1:1 conversions. It turns
out the code can be simplified.
> Correctly handle 1:1 conversions for calls in FunctionSignatureExpansionPass

- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/function_test.py
- docs/developers/design_docs/function_abi.md
I implemented minimal support here for what I needed for npcomp based on our discussions. Part of me wants to remove the `py_` from `py_homogeneous_list`, as that's a pretty general concept independent of Python. Thoughts?
Also happy to flesh out arg handling too -- just at a checkpoint now where my first e2e test passes.
> function.py: Add support for mashaling list types on returns.

- bindings/python/iree/runtime/vm.cc
- bindings/python/iree/runtime/vm_test.py
The previous code just handled the `i32` variant and would read garbage in other cases.
> [bindings/python] Correctly stringify iree_vm_variant_t

- build_tools/android/common/noisy_benchmarks.py
- build_tools/android/post_benchmarks_as_pr_comment.py
- build_tools/android/upload_benchmarks_to_dashboard.py
These benchmarks seem to suffer from phone issues so they bounce
in large ranges. So introducing a filter list to reduce the noise
to avoid confusion while waiting for fixing the phones.
> Introduce a noisy benchmark list to control threshold and comment

- iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- iree/compiler/Codegen/SPIRV/test/convert_to_spirv.mlir
- iree/compiler/Codegen/SPIRV/test/distribute_to_global_id.mlir
- iree/compiler/Codegen/SPIRV/test/pipeline_matmul_vectorization.mlir
- iree/compiler/Codegen/SPIRV/test/promote_workgroup_memory.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/vector_to_cooperative_matrix.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_copy_to_workgroup_memory.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_elementwise_ops.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_matmul.mlir
Now the CodeGen config is fetched and attached as attributes to the
ops in an early step by `SPIRVLowerExecutableTargetPass` by querying
the `spv.target_env`. We don't need the `spv.target_env` in many
of the existing tests anymore, if the test does not involve the
`SPIRVLowerExecutableTargetPass` pass.
> [spirv] Remove unnecessary `spv.target_env` attributes in tests

- docs/website/docs/building-from-source/getting-started.md
- docs/website/docs/building-from-source/optional-features.md
These are sections, not admonitions. Not really sure why they were
using the latter.
Also attempts to fix a broken tab group (based on the assumption that it
uses indented blocks).
> [docs] Use sections instead of admonitions

- iree/compiler/Dialect/VM/Conversion/UtilToVM/ConvertListOps.cpp
- iree/compiler/Dialect/VM/Conversion/UtilToVM/test/list_ops.mlir
* Upper layer dialects have this as optional but VM does not.
> Fix conversion of vm.list.alloc to not crash on missing capacity.

- llvm-external-projects/iree-dialects/docs/Dialect/IREEPyDM/LowerToIREE.md
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/CMakeLists.txt
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/IR/Dialect.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/IR/Ops.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/CMakeLists.txt
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/Passes.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/ToIREE/Patterns.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/ToIREE/TypeConverter.h
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/PassDetail.h
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/ToIREE/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/ToIREE/ConversionPass.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/ToIREE/LoweringPatterns.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/ToIREE/TypeConverter.cpp
- llvm-external-projects/iree-dialects/test/iree_pydm/to_iree/structural.mlir
- llvm-external-projects/iree-dialects/test/python/iree_pydm/to_iree/basic_structure.py
- llvm-external-projects/iree-dialects/tools/iree-dialects-opt/CMakeLists.txt
- llvm-external-projects/iree-dialects/tools/iree-dialects-opt/iree-dialects-opt.cpp
* Type conversion basics.
* Lowerings for AllocFreeVarOp, BoxOp, FuncOp, LoadVarOp, RaiseOnFailureOp, ReturnOp, StoreVarOp, UnboxOp, NoneOp
* Sufficient to lower simple functions taking arguments and returning values based on them, with or without typing.
* This is about as far as we can go without a runtime library, which comes next.
> Initial commit of PyDM to IREE lowering pipeline.

- third_party/mlir-emitc/lib/Target/Cpp/TranslateToCpp.cpp
Takes over the upstream change
* llvm/llvm-project@ec92f78
to fix printing negative integers, reported as part of #7026.
> Integrate upstream cpp emitter change

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- iree/compiler/Codegen/SPIRV/test/config_adreno_conv.mlir
- iree/compiler/Codegen/SPIRV/test/config_adreno_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/config_linalg_ext_ops.mlir
- iree/compiler/Codegen/SPIRV/test/config_linalg_ops.mlir
- iree/compiler/Codegen/SPIRV/test/pipeline_matmul_vectorization.mlir
- iree/compiler/Codegen/SPIRV/test/remove_one_trip_tiled_loop.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_matmul.mlir
- iree/compiler/Dialect/HAL/IR/LoweringConfig.cpp
- iree/compiler/Dialect/HAL/IR/LoweringConfig.h
- iree/compiler/Dialect/HAL/IR/LoweringConfig.td
Using `I32AttrEnum` is not maintainable. Adding a new pipeline enum in
the middle will have unintended consequences. String attributes are
more managable here.
Depends on PR #7006
> Change pass pipeline enum to use a StrEnumAttr. 

- build_tools/benchmarks/common/noisy_benchmarks.py
- build_tools/benchmarks/post_benchmarks_as_pr_comment.py
- build_tools/benchmarks/upload_benchmarks_to_dashboard.py
Previously we were just omit all benchmarks marked as noisy. That
can miss real regressions sometime.
> Adjust PR comment benchmark similar threshold for noisy benchmarks

- iree/compiler/Codegen/LLVMCPU/test/tile_pad_and_vectorize.mlir
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/test/dispatch_tensor_folding.mlir
This issue shows up when tile distributed linalg ops on tensors (progress towards #6973), this PR fixes the tile loop bounds.
> Fix tensor.dim + flow.dispatch.tensor.load canonicalization

- iree/base/status.c
Change the returned message_size from size_t to int, otherwise for some
compiler it will hit -Wtautological-compare since the message_size in
unsigned always >= 0.
> base:status: Fix vsnprintf return data type

- iree/compiler/Codegen/Common/VectorizeMMT4d.cpp
- iree/compiler/Codegen/Common/test/vectorize_linalg_mmt4d.mlir
- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
- iree/compiler/Dialect/Flow/Transforms/MatmulToMMT4dConversion.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/test/matmul_to_mmt4d.mlir
* Make M0,K0,N0 options of the pass converting matmul to mmt4d.
* Support cases where M0,K0,N0 are distinct.
* Expand tests.
* Renaming MMT4d -> Mmt4D for consistency.
* Consistently use the ordering: M, K, N  (and not: M, N, K).
* Add comments.
* Remove the "iree-flow-enable-matmul-to-mmt4d" pass pipeline option. For now we will use iree-opt for matmul to mmt4d conversion.
> Mmt4d: support arbitrary (M0,K0,N0) triplets and various cleanups.

- iree/hal/vulkan/native_executable.cc
Another possible dead path captured by -Wtautological-compare.
> hal:vulkan: Fix flatbuffers length check

- bindings/python/iree/compiler/core.py
- bindings/python/tests/compiler_core_test.py
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.h
- iree/compiler/Dialect/VM/Target/Bytecode/TranslationFlags.cpp
- iree/compiler/Dialect/VM/Target/Bytecode/test/module_encoding_smoke.mlir
- iree/compiler/Dialect/VM/Target/Bytecode/test/reflection_attrs.mlir
- iree/compiler/Translation/test/smoketest.mlir
- iree/schemas/bytecode_module_def.fbs
- iree/vm/bytecode_module.c
- iree/vm/stack.c
It's not useful now that we have a source map.
This also drops `-iree-vm-bytecode-module-strip-symbols` as there's no
symbols to strip now.
Fixes #7063.
> Removing the internal_functions table from the VM flatbuffer.

- iree/compiler/Codegen/SPIRV/SPIRVRemoveOneTripTiledLoops.cpp
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
This allows us to be resilient towards the implicit loop orders
in Linalg ops.
This fixes the performance problem for pooling op, which has 4
parallel loops (for N, OH, OW, OC), but as it is defined today,
the OC loop is behind some reduction loops for the window.
So it causes us only partitioning and distributing along (N,
OH, OW), which is typically small or even just 1. There are real
cases in DeepLabV3 that we have 1x1x1 for them, which means we
effectively are running everything using 1 thread on GPU.
> Change loop partition logic to consider all parallel dimensions

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/test/config_linalg_ext_ops.mlir
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/Transforms/Tiling.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/test/tiling.mlir
This implements tiling method of linalg_ext.fft op and set up the kernel
configurations for all the backends.
After tiling and distribute, the change of performance on
tensor<325x1024xf32> is:
| Backend          | Before (ms) | After (ms)|
|------------------|-------------|-----------|
| CPU (1-threaded) |    2.72 ms  |   3.72 ms |
| CPU (3-threaded) |    7.31 ms  |   2.85 ms |
| Vulkan SPIR-V    |     387 ms  |   7.13 ms |
| Cuda             |     344 ms  |   6.70 ms |
Note: tested on desktop machine.
The limitation of non-one strides in tiling is removed, and it should be
aligned in kernel configurations. The workgroup_size should be a mutiple
of M where M is 2^stage because of the merging algorithm. Currently,
only the stage of fft ops must be a constant.
After tiling, the shape of fft …
> Add tile and distribut support for linalg_ext.fft ops

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- Drop `-iree-flow-enable-1x1-conv-to-matmul` as it was true by default.
- Move the linalg -> linalg peephole optimizations passes to the top of the flow pipeline.
> Move peephole optimization at the top of the flow pipeline

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/test/microbenchmarks/linalg_mmt4d.mlir
- Set M0, N0, K0 tiles from operands shape.
- Add microbenchmark for that case.
> Adjust default mmt4d tiling

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/IR/Dialect.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/IR/Ops.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/IREEPyDM/Transforms/Passes.td
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/RTL/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/IREEPyDM/Transforms/RTL/LowerToRTLPass.cpp
- llvm-external-projects/iree-dialects/python/CMakeLists.txt
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/importer/__init__.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/importer/importer.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/importer/intrinsic_def.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/importer/test_util.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/importer/util.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/rtl/__init__.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/rtl/base.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/rtl/modules/booleans.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/rtl/modules/constants.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/rtl/modules/macros.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/rtl/modules/numerics.py
- llvm-external-projects/iree-dialects/python/mlir/dialects/iree_pydm/rtl/rtl_builder.py
- llvm-external-projects/iree-dialects/test/iree_pydm/rtl/lower_to_rtl.mlir
- llvm-external-projects/iree-dialects/test/python/iree_pydm/importer/intrinsics.py
- llvm-external-projects/iree-dialects/test/python/iree_pydm/importer/structural.py
- llvm-external-projects/iree-dialects/test/python/iree_pydm/rtl_builder.py
- llvm-external-projects/iree-dialects/test/python/iree_pydm/to_iree/basic_structure.py
- llvm-external-projects/iree-dialects/tools/iree-dialects-opt/CMakeLists.txt
* A pass to lower dynamic operations (i.e. on objects or otherwise requiring non trivial lowerings) to runtime library calls.
* A DSL for using the compiler to build low-level runtime library modules.
* Implemented basic support for dynamic AsBool and DynamicBinaryPromote, which are unavoidable in programs that do anything real.
* Missing a linker to pull it all together -- will come next.
* Studiously ignoring the poor quality of the frontend code and focusing on generality for the moment. Most of this stuff is imminently optimizable but it is important to get general correctness first.
* Example output of the RTL builder: https://gist.github.com/stellaraccident/1ff49e4a6108f22f1e82ad7934d9ab85
> [pydm] Add basics of runtime library integration.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
If there are no root operations within a dispatch region, assume all
generic ops are tiled + distributed the same way, and can therefore
use the same configuration.
> Basic handling of multiple generic ops in dispatch regions on CPU path.

- bindings/python/iree/runtime/system_api.py
Passing `driver` had no effect other than circumventing error checking.
> Fix kwarg bug in iree.runtime.load_vm_flatbuffer

- .gitignore
- CMakeLists.txt
- bindings/python/CMakeLists.txt
- build_tools/cmake/iree_macros.cmake
- llvm-external-projects/iree-compiler-api/CMakeLists.txt
- llvm-external-projects/iree-compiler-api/build_tools/build_intree.sh
* Needed for use of IREE as a sub-project that also configures pybind11.
* Enables building of IREE python bindings as part of iree-compiler-api.
* Fixes an issue with IREE data deps to make them relative to the project, not the root.
* Tweaks some settings on the compiler-api build to make it better for dev.
> Only add bundled pybind11 if not already found.

- iree/vm/bytecode_dispatch_util.h
It's got issues and needs to be reworked as part of the bytecode redesign.
This will make #5506 worse but it's better to not crash.
Fixes #7127.
> Disabling ref move in the VM.

- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/IR/test/roundtrip.mlir
- iree/compiler/Dialect/LinalgExt/Transforms/test/convert_to_loops.mlir
Defines linalg_ext.reverse op and implements basic interface methods of
the op.
The reverse op in Linalg has Linalg unfriendly affine exprs, which
blocks tile and distribute transforms. This is a short/mid term solution
for tiling and distributing reverse ops.
It's a step toward https://github.com/google/iree/issues/5045
> Introduce reverse op to LinalgExt dialect.

- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/test/BUILD
- iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- iree/compiler/Codegen/SPIRV/test/config_default_matmul.mlir
* We don't support non-16/non-32 bit element types yet.
* Don't vectorize for odd K sizes. We cannot vector load there.
> [spirv] Fix matmul vectorization corner cases

- build_tools/buildkite/cmake/build_configurations.yml
- build_tools/cmake/clean_build.sh
- build_tools/docker/cmake-gcc/Dockerfile
- build_tools/docker/manage_images.py
- build_tools/docker/prod_digests.txt
This will run post-submit as part of the Buildkite pipeline testing
various configurations. Only checks that things build, doesn't run any
tests.
This is mostly in support of releases. It uses gcc 9, even though the
latest on Ubuntu 18.04 is 7. We get some errors building with 7 and
debugging gcc errors is not high priority right now 🙂 There are also
oodles of warnings, mostly because we haven't correctly split the
diagnostic flags for gcc vs clang. Again, not a priority right now.
Tested:
Ran a build locally in the docker image. Kicked off a buildkite run
https://buildkite.com/iree/iree-build-configurations/builds/839
Fixes https://github.com/google/iree/issues/6959
> Add gcc CI build

- build_tools/benchmarks/common/benchmark_thresholds.py
These models run much faster now; we are seeing less fluctuating
benchmark numbers.
> Adjust mobile GPU model similarity thresholds

- bindings/python/iree/compiler/setup.py.in
(Untested) follow-up to https://github.com/google/iree/pull/6654 for the core tools (mainly `iree-translate`).
Attempting to fix an error demonstrated [in this notebook](https://colab.research.google.com/gist/ScottTodd/8403b5858224ad8e6e42c65c069b26af/iree-native-tools.ipynb):
```
!iree-translate --help
Traceback (most recent call last):
File "/usr/local/bin/iree-translate", line 5, in <module>
from iree.tools.core.scripts.iree_translate.__main__ import main
ModuleNotFoundError: No module named 'iree.tools.core.scripts'
```
We have validation for the pip installs and scripts now, but based on https://github.com/google/iree/issues/6638#issuecomment-893121059, they should be running from a working directory other than where the pip install is? …
> Include recursive package for core compiler tools.

- iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
Only merge duplicate broacast ops to avoid duplicating an op containing
a broacast along with expensive work
> Refine fusion heuristic

- iree/test/e2e/models/CMakeLists.txt
Bert test was disabled in bazel build but not CMake files. Updated CMake
files to match.
> Fix CMakeLists to disable bert test

- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.td
- iree/compiler/Dialect/LinalgExt/Transforms/test/tiling.mlir
To tile a linalg_ext.reverse op, we have to store the tiled result to
mirror offsets. E.g.,
Before:
```
[T_0], [T_1], [T_2], [T_3]
```
After:
```
[Rev_t3], [Rev_t2], [Rev_t1], [Rev_t0]
```
The snippet after DispatchLinalgOnTensors, which shows that the op is
tiled and distributed:
```mlir
func private @_foo(%arg0: tensor<?xi32>, %arg1: !shapex.ranked_shape<[?]>) -> (tensor<?xi32>, !shapex.ranked_shape<[?]>) {
%c0 = constant 0 : index
%c1 = constant 1 : index
%0 = shapex.ranked_dim %arg1[0] : !shapex.ranked_shape<[?]> -> index
%1 = shapex.tie_shape %arg0, %arg1 : tensor<?xi32>, !shapex.ranked_shape<[?]>
%2 = linalg.init_tensor [%0] : tensor<?xi32>
%3 = tensor.dim %1, %c0 : tensor<?xi32>
%4 = tensor.dim %2, %c0 : tensor<?xi32>
%5 = tensor.dim %1, %c0 : tensor<?xi32>
%6 = …
```
> Implement tiling method for linalg_ext.reverse ops.

- CMakeLists.txt
- build_tools/bazel/build_core.sh
- llvm-external-projects/iree-compiler-api/BUILD
- llvm-external-projects/iree-compiler-api/CMakeLists.txt
- llvm-external-projects/iree-dialects/BUILD
* We have use cases for three modes of depending:
* For deployment (i.e. as Python package, other bindings, etc), iree-compiler-api is standalone and depends on IREE properly and it has to be built with specific, project wide compile/link flags.
* For development, even though IREE cannot depend on iree-compiler-api, it is useful to build it as part of IREE so that devs have access to the whole project (i.e. can use ireec, the C and Python API, etc). It is also nice because when built this way on the CI, all of the tests run together, etc.
* When included as an LLVM external project (i.e. when building IREE into another LLVM-based compiler), it is built as a sub-project of LLVM and includes IREE (this mode is not yet implemented).
* Before too much longer, I will probably bust the …
> Adapt iree-compiler-api so it builds standalone and as part of iree.

- iree/compiler/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- iree/compiler/Dialect/LinalgExt/IR/test/invalid.mlir
- iree/compiler/Dialect/LinalgExt/IR/test/roundtrip.mlir
Having a strict type check is too restrictive. Sometimes canonicalizations need to kick in for the shapes to match exactly. A dynamic value is compatible with a static value for a dimension of input/output.
> Add folding tensor.cast patterns to LinalgExt ops.

- .github/workflows/build_package.yml
- build_tools/embed_data/generate_embed_data_main.cc
- build_tools/github_actions/build_dist.py
- build_tools/github_actions/cmake_ci.py
- llvm-external-projects/iree-compiler-api/BUILD.bazel
- llvm-external-projects/iree-compiler-api/CMakeLists.txt
- llvm-external-projects/iree-compiler-api/build_tools/build_python_wheels.sh
- llvm-external-projects/iree-compiler-api/build_tools/smoketest.py
- llvm-external-projects/iree-compiler-api/pyproject.toml
- llvm-external-projects/iree-compiler-api/python/CMakeLists.txt
- llvm-external-projects/iree-compiler-api/python/iree/compiler/tools/binaries.py
- llvm-external-projects/iree-compiler-api/setup.py
This is a relatively twisty set of changes needed to completely replace the old iree.compiler package with iree-compiler-api on Linux/Windows/Mac. You will note a fair number of shenanigans required, but it does work.
Functional changes:
* Adds ireec and iree-translate console scripts to new package.
* Allows iree-translate to alias to ireec for compatibility.
* Scopes the CMake python library build hack to just Linux.
* Removes TF builds for Windows and MacOS. I can add these back in but having a bunch of experimental/broken things was making testing much more expensive. I think we should just leave them out.
> Release the new iree-compiler-api vs the old.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.h
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUVectorization.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/SPIRVRemoveOneTripTiledLoops.cpp
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
The current configurations on CPU backends (and all backends) rely on
looking at operations within the dispatch region to pick a
default. This makes it hard to set a good default to ensure good tile
+ distribute of operations. For every op a configuration method is
needed.
Instead one can just look at the loops and get an idea of the problem
size. These loops are created by tile + distribute at the flow level
using parametric tile sizes. The bounds of the loop are already
determined from the problem sizes. Ideally we would have a loop
representation that does not immediately materialize the distributed
loop, but rather maintains the loop in undistributed form, with
additional operands that specify the id/count/size to use when
materializing the distributed loop (defering the …
> Revisit CPU lowering configuration settings.

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
Don't set thread level tile size in configuration but calculate it based
on workloadPerWorkgroup size and workgroup size. This makes it simpler
to pick a configuration.
> [CUDA] Refactor op configuration

- iree/base/internal/span.h
When IREE_HAVE_STD_SPAN is not defined, std::numeric_limits will be
used.
But std::numeric_limits is defined in <limits>, which is not included.
> missing #include <limits>

- iree/tools/iree-benchmark-module-main.cc
Can be used in CI benchmark pipeline to track the runtime memory usage
for models.
> tools:benchmark: Add runtime memory usage stat printout

- iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMGPU/test/convert_to_nvvm.mlir
Since dead symbols are currently not being removed we need to handle the
case where a binding is not used. In this case just add a dummy i32
kernel argument
> [CUDA] Fix crash when a kernel has dead binding

- iree/tools/utils/trace_replay.c
> Allow encoding_type to be optional in iree-run-trace.

- iree/tools/BUILD
- iree/tools/CMakeLists.txt
These are useful to deploy alongside `iree-run-module` and other tools, independent of `IREE_BUILD_TESTS`.
> Remove testonly label from iree-benchmark-[module,trace].

- bindings/python/iree/runtime/CMakeLists.txt
- bindings/python/iree/runtime/scripts/iree_benchmark_trace/__main__.py
- bindings/python/iree/runtime/scripts/iree_run_trace/__main__.py
- bindings/python/iree/runtime/setup.py.in
* Now users of the python script have access to iree-run-trace and iree-benchmark-trace.
* Going to be used for the new TFLite tests.
> Add iree-(run|benchmark)-trace console scripts to iree-runtime package.

- iree/hal/cts/command_buffer_test.cc
IREE_WHOLE_BUFFER isn't supported on CUDA for now. It's
unclear whether we want to support it in the long run.
This also makes the test more targeted and not testing
unrelated features.
> Use explicit buffer length in CopySubBuffer test

- iree/vm/BUILD
- iree/vm/CMakeLists.txt
- iree/vm/list.c
- iree/vm/ref.c
Reverts google/iree#7247
The original commit breaks builds on the benchmark pipeline (https://buildkite.com/iree/iree-benchmark/builds/1128#2fad7107-b8d3-4910-a7e0-b2c8aa2d0642)
<html>
<body>
Aborted
--
  | --> benchmark: MobileNetV2 [fp32,imagenet] (TensorFlow) 3-thread,little-core,full-inference with IREE-VMVX @ Pixel-4 (CPU-ARMv8.2-A) <--
  | cmd: adb push /var/lib/buildkite-agent/builds/IREE-LAB-RPI4-PIXEL4-2-ubuntu-1/iree/iree-benchmark/build-host/benchmark_suites/TensorFlow/MobileNetV2-fp32,imagenet/iree-vmvx__CPU-ARM64-v8A__3-thread,little-core,full-inference/flagfile /data/local/tmp/iree-benchmarks/TensorFlow/MobileNetV2-fp32,imagenet/iree-vmvx__CPU-ARM64-v8A__3-thread,little-core,full-inference/flagfile
  | cmd: adb shell cd …
> Revert "Fixing VM release-before-retain when the source and target alias."

- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/LinalgExt/IR/TiledOpInterface.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/Tiling.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/test/tiling.mlir
This patch adds the external model for implementing `TiledOpInterface`
into IREE during initialization so that it is always available. This
allows tile + distribute of this operation at the flow level.
To get the distribution to work correctly, the arguments for the
destination and result in the dispatch region op need to be tied. The
current logic for legalization of dispatch region and tie-ing operands
does not support this. So this PR also reworks all of that to be more
robust.
> Enable tile + distribute of tensor.insert_slice.

- iree/samples/static_library/static_library_demo.c
The function is part of `iree_runtime_session_create_with_device`
> samples:static_library: Remove redundant `iree_hal_module_create`

- iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
`InterfaceBindingSubspanOp` can return any type:
https://github.com/google/iree/blob/4f02b7e604c9/iree/compiler/Dialect/HAL/IR/HALOps.td#L2350
> Avoid crash when InterfaceBindingSubspanOp doesn't return Memref

- iree/test/e2e/xla_ops/gather.mlir
We now have a lowering for mhlo.gather to linalg so can run general
gather ops.
> Execution tests for mhlo.gather

- iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
The existing behavior was causing binding lookups to happen in inner
loops whenever it triggered.
This would have been handled by CSE but we have MemAlloc tagged on
hal.interface.binding.subspan so it's not moved/deduped. If we fix that
then this could be removed.
> Fixing binding subspan insertion to point at the entry block.

- .github/workflows/android_tflite_oneshot_build.yml
- bindings/tflite/java/build.gradle
- bindings/tflite/java/org/tensorflow/lite/Interpreter.java
- build_tools/cmake/iree_copts.cmake
- build_tools/docker/gradle-android/Dockerfile
- build_tools/docker/manage_images.py
- build_tools/docker/prod_digests.txt
- build_tools/gradle/build_tflite_android_library.sh
This implements a new Github action `.github/workflows/build_android_library.yml` that runs our workflow to build IREE's TFLite Java bindings via  `build_tools/gradle/build_tflite_android_library.sh`.
The Github Action uses a new `gradle-android/Docker` file to produce consistent repeatable builds locally and remote. 
On some systems, gradle fails to run the `externalNativeBuild` task with an unexplained NullPointer error. To get around this. We manually build the native IREE TFLite compatibility shim with [Android cross-compilation](https://google.github.io/iree/building-from-source/android/). The resulting library is copied into the `jniLibs` folder to be included directly in the final library, while native build tasks are skipped by gradle. 
Additional changes to fix recent issues with …
> Implementation of remote Android TFLite Bindings build via Github Actions with Docker

- build_tools/cmake/build_riscv.sh
- docs/website/docs/building-from-source/riscv.md
Set the host build compiler to clang. It should be a no-op for CI since
the docker image already set the {CC, CXX} environment variables to clang.
> Update RISC-V crosscompile instructions

- iree/vm/BUILD
- iree/vm/CMakeLists.txt
- iree/vm/list.c
- iree/vm/ref.c
- iree/vm/ref_test.cc
This reverts commit 567b77785b6d603d866c5dc1496dd367902e830c.
Original PR #7247. Turns out the test was wrong all along.
> Fixing VM release-before-retain when the source and target alias.

- iree/tools/iree_translate_lib.cc
https://github.com/google/iree/pull/6967 reverted the invocation of this
from Python, which was the use case (for debugging a weird crash). The
weird crash has mysteriously disappeared.
This (semantically) reverts https://github.com/google/iree/pull/6795 and
9567838acb9816027e8ce1928b63a478bce7166e
> Remove option to print address of main from iree-translate

- iree/compiler/Codegen/SPIRV/Passes.cpp
We can lower standard max/min ops directly with
https://reviews.llvm.org/D111143; no need to emulate
them.
> [spirv] Remove createStdExpandOpsPass in pass pipelines

- iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMCPU/test/hal_interface_bindings.mlir
- iree/compiler/Dialect/HAL/Target/LLVM/LibraryBuilder.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LibraryBuilder.h
- iree/hal/local/elf/arch.h
- iree/hal/local/elf/arch/arm_32.c
- iree/hal/local/elf/arch/arm_64.c
- iree/hal/local/elf/arch/riscv.c
- iree/hal/local/elf/arch/x86_32.c
- iree/hal/local/elf/arch/x86_64.c
- iree/hal/local/elf/arch/x86_64_msvc.asm
- iree/hal/local/executable_loader.c
- iree/hal/local/loaders/embedded_library_loader.c
Confirmed working with both system and embedded libraries.
This is just the low level infra for emitting the dynamic calls at codegen time and passing through the calls at runtime.
There's another layer on top of this required in the compiler to make it generally usable, tracked in #7504.
> Completing the wiring up of CPU imports.

- docs/developers/developing_iree/profiling_cpu_events.md
- iree/base/internal/dynamic_library_posix.c
This allows perf and Instruments to find the files and resolve symbols.
> Add env var to control cleanup of temp dylib files.

- iree/compiler/Dialect/Stream/Transforms/BUILD
- iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/EncodeTensors.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.h
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/encode_tensors.mlir
This takes the `stream.tensor.*` ops and using their encoding produces `stream.async.*` ops that are tensor-type erased. Today only dense tensors are supported (as with our existing code), but sparse tensor support (particularly for constants, where sparsity is going to come first) are easily added here.
> Adding -iree-stream-encode-tensors pass.

- iree/hal/cts/command_buffer_test.cc
- iree/hal/vulkan/vma_allocator.cc
I'm not sure if there is a better way to handle this, but I was observing that a 1 byte buffer would fail all writes in the polyfilled shader (even hardcoding a write into `output_elements[0]` would do nothing). `vkCmdFillBuffer`, however, _did_ correctly write into buffers of that size. By aligning the underlying buffer allocations to 4 bytes, the polyfilled shader can now write into the only byte in a 1 byte buffer, the trailing byte in a 5 byte buffer, etc.
I missed this edge case when working on https://github.com/google/iree/issues/7228.
This fixes the issues I noticed on https://github.com/google/iree/pull/7370#discussion_r732949146.
> Align Vulkan allocs to 4 bytes, fixing unaligned fill edge cases.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/IR/test/tensor_folding.mlir
- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/OutlineLargeConstants.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/test/outline_large_constants.mlir
This reverts commit c4e0f3b01a874e1bb0b3d3b71d54d5b70f3129e6 to roll forward https://github.com/google/iree/pull/6816, now that https://github.com/google/iree/pull/7370 has landed and unaligned buffer fills are supported by the compiler and runtime.
I tested this sequence of changes with the person_detect program mentioned at https://github.com/google/iree/pull/7370#issuecomment-952379671 and https://github.com/google/iree/pull/7462#issuecomment-952332376, but we don't yet have complete test coverage in the main IREE repo.
> Roll forward "Don't outline splat constants."

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUVectorization.cpp
- iree/compiler/Codegen/LLVMCPU/test/matmul_vectorization.mlir
- iree/compiler/Codegen/LLVMCPU/test/tile_and_vectorize.mlir
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- iree/compiler/Codegen/LLVMGPU/test/rocdl_pipeline_test.mlir
- iree/compiler/Codegen/SPIRV/SPIRVTileAndDistribute.cpp
- iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- iree/compiler/Codegen/SPIRV/test/pipeline_matmul_vectorization.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_distribute_scatter.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_distribute_sort.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_matmul.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_to_cooperative_ops.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_elementwise_ops.mlir
- iree/compiler/Codegen/Utils/MarkerUtils.cpp
- iree/compiler/Codegen/Utils/MarkerUtils.h
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
The "workgroup" marker has a really long lifetime in IREEs compilation
stack. It is produced by the dispatch region formation and is consumed
all the way during executable translation. THere is also some
weirdness about when the tiling patterns trigger. This was relevant
when not all ops were tiled and distributed. Since this isnt the case
any more, the "workgroup" marker can be dropped.
Fixes #5045
> Drop "workgroup" marker.

- benchmarks/TFLite/CMakeLists.txt
- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
- build_tools/cmake/build_android.sh
- build_tools/cmake/build_android_benchmark.sh
- build_tools/cmake/iree_benchmark_suite.cmake
- build_tools/kokoro/gcp_ubuntu/cmake/android/arm64-v8a/build_kokoro.sh
This replaces the three benchmarks derived from TFLite flatbuffers to
use the original flatbuffer source rather than a pre-compiled MLIR
file. These benchmarks are updated in place since the original source
is exactly the same. Using flatbuffers avoids a few issues:
1. The MLIR IR formats do not offer any backward compatibility
guarantees. When MLIR syntax changes in a backward-incompatible way,
the benchmark pipeline breaks.
2. Updates to the frontend compilation are not captured in real time.
They are only incorporated as part of the updates above, which means
that they are realized only when updating the MLIR files due to
syntax changes.
This adds a dependency on the TFLIte frontend to benchmark generation.
In the automated pipeline, the additional Bazel compilation uses the
remote …
> Enable benchmarks from TFLite flatbuffers on benchmark pipeline

- iree/compiler/Dialect/Stream/IR/StreamOpFolders.cpp
- iree/compiler/Dialect/Stream/Transforms/BUILD
- iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/ElideAsyncCopies.cpp
- iree/compiler/Dialect/Stream/Transforms/MaterializeCopyOnWrite.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.h
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/elide_async_copies.mlir
- iree/compiler/Dialect/Stream/Transforms/test/materialize_copy_on_write.mlir
- iree/compiler/Dialect/Util/Analysis/DFX/Solver.cpp
- iree/compiler/Dialect/Util/Analysis/DFX/Solver.h
- iree/compiler/Dialect/Util/Analysis/DFX/State.h
- iree/compiler/Dialect/Util/Analysis/Explorer.cpp
- iree/compiler/Dialect/Util/Analysis/Explorer.h
- iree/compiler/Dialect/Util/IR/UtilTypes.cpp
This pass, along with the associated `-iree-stream-elide-async-copies` cleanup pass, implements the copy-on-write logic in the stream dialect. The first pass conservatively inserts copies to tensors that are mutated with remaining uses and the cleanup pass tries to perform some basic analysis to elide them.
> Adding -iree-stream-materialize-copy-on-write pass.

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
- build_tools/cmake/build_android.sh
- build_tools/kokoro/gcp_ubuntu/cmake/android/build.sh
Turns out the Buildkite Android build was using a script under the
Kokoro directory. https://github.com/google/iree/pull/7494 switched
that script to build the TFLite importer with Bazel to allow verifying
that we can build benchmark artifacts for Android (the least-bad option
available at the moment, see
https://github.com/google/iree/pull/7494#issuecomment-959710770). We
don't want to be doing that as part of the Buildkite pipeline though.
So we pull the Bazel stuff into the Kokoro script and make the
Buildkite pipeline not use it.
> Avoid using Bazel in the Buildkite Android pipeline

- iree/compiler/Dialect/Util/IR/UtilBase.td
- iree/compiler/Dialect/VM/IR/VMOps.td
This was added in https://reviews.llvm.org/D109359 and is showing up as
log spam. Looks like it caught a real bug though!
> Fix or suppress tablegen unused template warnings

- iree/compiler/Codegen/Common/OptimizeVectorTransferPass.cpp
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/test/BUILD
- iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- iree/compiler/Codegen/LLVMCPU/test/test_config_mmt4d.mlir
- Add vector transform patterns needed to get better performance.
Baseline:
```
--------------------------------------------------------------------------------------------
Benchmark                                                  Time             CPU   Iterations
--------------------------------------------------------------------------------------------
BM_mmt4d_384x384x512_8x1x8/process_time/real_time       7.54 ms         7.52 ms           93
```
This PR:
```
--------------------------------------------------------------------------------------------
Benchmark                                                  Time             CPU   Iterations
--------------------------------------------------------------------------------------------
BM_mmt4d_384x384x512_8x1x8/process_time/real_time …
```
> - Move linalg.mmt4d to the tensor -> vector pipeline

- benchmarks/TFLite/CMakeLists.txt
This benchmarks on 2-4 little cores. I did not include any benchmarks
with multiple big cores, as I understand this to not be a particularly
realistic scenario.
> Add multi-threaded benchmarking of TFLite models

- bindings/python/iree/runtime/function.py
Makes parsing mismatched arity errors easier for large inputs by calling out the discrepancy up front. I also added newlines because they make it easier for me to parse long error messages like this, but could remove them if desired.
I think it would also be better to log the signature of the passed input instead of logging the input itself, since no shape information is provided in the logs (see below), but I'm not sure how best to implement that using the runtime bindings.
```python
array([[0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 3.17000e+02,
3.18000e+02, 3.19000e+02],
[3.20000e+02, 3.21000e+02, 3.22000e+02, ..., 6.37000e+02,
6.38000e+02, 6.39000e+02],
[6.40000e+02, 6.41000e+02, 6.42000e+02, ..., 9.57000e+02,
9.58000e+02, 9.59000e+02],
...,
[1.62880e+05, 1.62881e+05, 1.62882e+05, …
```
> Make mismatched arity error easier to parse

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPURemoveTrivialLoops.cpp
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/SPIRVRemoveOneTripTiledLoops.cpp
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
The logic behind rediscovering the loop tiling and distribution
information is quite dense. This makes at least the API clearer.
> NFC: improve naming and doc for tiled and distributed loop info

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.h
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.h
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/VMAnalysis.h
- iree/vm/test/call_ops.mlir
- iree/vm/test/control_flow_ops.mlir
This was broken by upstream changes to the conversion framework and hence some vm tests were disabled in #7488 for the C backend.
> Fix vm to emitc conversion for ref types

- iree/samples/static_library/CMakeLists.txt
- iree/samples/static_library/README.md
- iree/samples/static_library/static_library_demo.c
Switches over to use the synchronous local CPU driver instead of using
the asynchronous task driver.
> Use `sync_driver` instead of `task_driver`

- iree/compiler/Dialect/Stream/Transforms/BUILD
- iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.h
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/PropagateTimepoints.cpp
- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/propagate_timepoints.mlir
This does a relatively mechanical transformation of a module to expand all `!stream.resource` values (and globals) into a (`!stream.timepoint`, `!stream.resource`) pair. Ops that consume resources and timepoints attempt to dereference those expanded timepoints and bypass waits, effectively chaining execution across asynchronous ops.
> Adding -iree-stream-propagate-timepoints pass.

- iree/compiler/Dialect/HAL/Transforms/PackAllocations.cpp
- iree/compiler/Dialect/HAL/Transforms/test/pack_allocations.mlir
- iree/compiler/Dialect/Util/IR/UtilOps.td
- iree/compiler/Dialect/Util/IR/UtilTypes.cpp
- iree/compiler/Dialect/Util/IR/UtilTypes.h
- iree/compiler/Dialect/Util/IR/test/BUILD
- iree/compiler/Dialect/Util/IR/test/CMakeLists.txt
- iree/compiler/Dialect/Util/IR/test/alignment_ops.mlir
- iree/compiler/Dialect/VM/Conversion/UtilToVM/BUILD
- iree/compiler/Dialect/VM/Conversion/UtilToVM/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/UtilToVM/ConvertAlignmentOps.cpp
- iree/compiler/Dialect/VM/Conversion/UtilToVM/ConvertUtilToVM.cpp
- iree/compiler/Dialect/VM/Conversion/UtilToVM/test/BUILD
- iree/compiler/Dialect/VM/Conversion/UtilToVM/test/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/UtilToVM/test/alignment_ops.mlir
Adds a Util.Align op to `UtilOps.td`. Align accepts two arguments, the value to align and the alignment to return the newly aligned value. 
`--iree-hal-pack-allocations` pass produces `Util::Align` ops instead of arithmetic ops for the alignment. The `--iree-vm-conversion` pass concerts the alignment ops directly to VM arithmetic/const ops (bypassing the arithmetic ops altogether). 
#5405
> Implementation of Util::AlignOp with tests and integration into compiler passes

- benchmarks/TFLite/CMakeLists.txt
- build_tools/cmake/iree_benchmark_suite.cmake
I'm just doing a couple of these to start. This is going to factor into
the benchmark name, which means it will create new series. I also want
to rename the tuned configurations, but that would turn them to
different series in Dana. I don't see any way to rename series from the
Dana web UI, at least. I think we would have to reupload all the data
under a different name.
> Add benchmarks with default flag configurations

- integrations/tensorflow/iree_tf_compiler/TFL/BUILD
- integrations/tensorflow/iree_tf_compiler/TFL/ConvertMetadata.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/LowerGlobalTensors.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/PassDetail.h
- integrations/tensorflow/iree_tf_compiler/TFL/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/Passes.h
- integrations/tensorflow/iree_tf_compiler/TFL/Passes.td
- integrations/tensorflow/iree_tf_compiler/TFL/RetainCallOnceFuncs.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/StripMetadata.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/VerifyFullyConverted.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/test/BUILD
- integrations/tensorflow/iree_tf_compiler/TFL/test/lower_global_tensors.mlir
- integrations/tensorflow/iree_tf_compiler/TFL/test/retain_call_once_funcs.mlir
Adding assign/read support for lowering from TFLite to IREE's Utils operators.
This adds elementary stateful TFLite behavior to IREE's support for MLIR. This
should move to tflite-to-tosa in the future.
> Added lowering for TFLite state to IREE::Utils operations

- docs/website/docs/building-from-source/getting-started.md
- docs/website/docs/deployment-configurations/cpu-dylib.md
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.h
- iree/compiler/Dialect/HAL/Target/LLVM/internal/EmbeddedLinkerTool.cpp
This path didn't _quite_ work out of the box for development builds. This expands the search space to make automatic discovery more likely.
The LLVM backend's embedded linker requires `lld` to be discoverable and we make an attempt to build it from source:
https://github.com/google/iree/blob/222828129144c8bfb603b4647aa969afb64a5a45/iree/tools/CMakeLists.txt#L395-L401
However, the `lld` binary ends up in `iree-build\third_party\llvm-project\llvm\bin` for builds (`install` does put `lld` next to the other IREE tools). This now searches that path in the build tree and includes more information in error messages:
```
Searching environment for one of these tools: [iree-lld.exe, lld.exe, ld.lld.exe, lld-link.exe]
Searching for tool at path 'D:\dev\projects\iree\..\iree-build\iree\tools' …
```
> Expand embedded linker discovery and improve error messages.

- iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertCommandBufferOps.cpp
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/command_buffer_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALOps.td
Also added more test cases. I'm still not sure about f16. This is the current behavior, which I could put in a test:
```mlir
vm.func private @command_buffer_fill_buffer_f16(%arg0: !vm.ref<!hal.command_buffer>, %arg1: !vm.ref<!hal.buffer>, %arg2: f32) {
%c2 = vm.const.i32 2 : i32
%c200 = vm.const.i32 200 : i32
%c100 = vm.const.i32 100 : i32
%0 = vm.bitcast.f32.i32 %arg2 : f32 -> i32
%1 = vm.ext.i16.i32.u %0 : i32 -> i32
vm.call @hal.command_buffer.fill_buffer(%arg0, %arg1, %c100, %c200, %1, %c2) : (!vm.ref<!hal.command_buffer>, !vm.ref<!hal.buffer>, i32, i32, i32, i32) -> ()
vm.return
}
```
That sketches me out though, so I could instead disallow f16 for now...
> Support i1 in hal.command_buffer.fill_buffer.

- iree/compiler/Dialect/Util/Transforms/CombineInitializers.cpp
When calling mlir::inlineRegion, g++-10 tries to deduce argument types to
figure out correct inlineRegion version. The g++-10 tries to convert the
fifth arg, which is a ValueRange{}, to BlockAndValueMapping, with conversion
operator 'RangeT()'. This requires full definition of BlockAndValueMapping,
or g++-10 will complain:
"template argument must be a complete class or an unbounded array"
* Fixes #7451
> Pull in BlockAndValueMapping definition.

- iree/compiler/Dialect/Stream/IR/StreamOps.cpp
- iree/compiler/Dialect/Stream/IR/test/async_ops.mlir
- iree/compiler/Dialect/Stream/Transforms/BUILD
- iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.h
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/ScheduleAllocation.cpp
- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/schedule_allocation.mlir
This performs the `stream.async.*` -> `stream.cmd.*` conversion by allocating all resources and changing ops to act directly on the resources. After this point we can no longer reorder operations. Since only (mostly) `stream.async.execute` ops can allocate resources this makes things fairly well-scoped as only these execution ops need to be handled. The high-level behavior is to find the execution regions, allocate their local transients, allocate/setup constant uploads, and allocate their results.
This initial implementation has some low-hanging fruit, like slices and updates aren't allocating in-place yet, but is better than the current allocation we have. Future changes could also refactor this to reduce code complexity and possibly be split into multiple passes, but at least now by …
> Adding -iree-stream-schedule-allocation pass.

- iree/compiler/Dialect/Flow/Transforms/DestructiveUpdateUtils.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/LinalgExt/IR/TiledOpInterface.cpp
- iree/compiler/Dialect/LinalgExt/Transforms/test/tiling.mlir
Forwarding the implementation of `TiledOpInterface` to methods in
`linalg.pad_tensor` that implement the `TilingInterface` in MLIR
allows IREE to pick up the tiling transformations that exist on this
operation. This PR just checks that the pad tensor operation is tiled
during dispatch region formation. It isnt connected end-to-end yet
till the effects downstream can be evaluated.
> Enable tiling of linalg.pad_tensor operations.

- iree/compiler/Dialect/Stream/Transforms/BUILD
- iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.h
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/PropagateSubviews.cpp
- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/propagate_subviews.mlir
- iree/compiler/Dialect/Stream/Transforms/test/propagate_timepoints.mlir
This does a relatively mechanical transformation of a module to expand
all resource values (and globals) into (resource, size, offset, length)
tuples.
This is designed to be composed with generic optimization passes like
global fusion/folding and IPO and as such performs all transformations
locally. For example, calls are always updated to take/return subview
ranges and results are always wrapped in a stream.resource.subview, with
the elision/deduplication/etc left until cleanup.
(this is nearly identical to -iree-stream-propagate-timepoints, just with subviews)
> Adding -iree-stream-propagate-subviews pass.

- iree/hal/command_buffer_validation.c
The validation checks that the bits are all set so _ANY is not really a good value to pass. Since any check we could do would always be true I just removed it.
> Fixing unneeded command buffer validation on barriers.

- iree/compiler/Dialect/Stream/Transforms/BUILD
- iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/ConvertToStream.cpp
- iree/compiler/Dialect/Stream/Transforms/test/convert_to_stream.mlir
- iree/test/e2e/tosa_ops/while.mlir
This would be triggered only if the tensor used by the external dialect
was directly captured from a block argument. I added a more complete
test for the convert to stream pass taken from the tosa while.mlir that
covers this and more.
> Fixing a case of stream/tensor interop.

- iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/test/outline_dispatch_regions.mlir
This was always adding on some extra operands before that were harmless,
however in the streams world we actually optimize things and need the
interfaces to match on both sides.
(also dropped the 2 in the pass name)
> Fixing dispatch region outlining with tied operands with dynamic shapes.

- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
Fix a bug where the bufferization pass would miss constructing
subviews for in-place updates in nested loops.
Fixes #7631
> Make bufferization get result buffer from tensor.insert_slice.

- iree/compiler/Dialect/Stream/Analysis/Partitioning.cpp
- iree/compiler/Dialect/Stream/Analysis/Partitioning/ReferencePartitioning.cpp
- iree/compiler/Dialect/Stream/Transforms/ScheduleExecution.cpp
- iree/compiler/Dialect/Stream/Transforms/test/schedule_execution.mlir
This is conservative and uses any side-effecting non-streamable op
as a barrier. We could use memory effects to do better things but
this at least should keep us correct. It's assumed that asserts should
be hoisted higher up in the IR during canonicalization.
> Prevent partitioning from moving ops across side-effecting ops.

- iree/vm/test/emitc/module_test.cc
This attempts to do the right thing from a C/C++ namespace perspective and then works around brokenness in old versions of libstdc++ that keep us from doing the complete right thing.
Fixes #7603
> Rework the way std math ops are used from C and C++.

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/test/BUILD
- iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- iree/compiler/Codegen/SPIRV/test/config_default_conv.mlir
- iree/compiler/Codegen/SPIRV/test/config_default_matmul.mlir
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
This commit changes the existing logic for figuring out the untiled
result shapes to use tiled and distributed loop nest. This is needed
for tensor cases where we can have the root op consumed by some
element-wise ops. Those element-wise ops will intervene with the
connection to `flow.dispatch.tensor.store` ops. Additionally walking
use chains and recognizing consumer ops can be unwieldy and fragile.
So this instead uses the surrounding tiled and distributed loops to
get back the original untiled shapes.
It might not matter that much for matmul, given we can query M, N, K
via inputs through `flow.dispatch.tensor.load` ops. But for conv ops,
we cannot and we need to query the result.
> Figure out untiled shapes from tiled and distributed loop nest

- benchmarks/TFLite/CMakeLists.txt
- benchmarks/TensorFlow/CMakeLists.txt
- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
Following up on https://github.com/google/iree/pull/7553, this adds
default flag configurations for the remaining TFLite models. Now that
we've got timestamps in the Buildkite runs, we can see what this does
to artifact transfer time via the presubmit:
https://buildkite.com/iree/iree-benchmark/builds/1447
I'm contrasting with the run at the merge base on main:
https://buildkite.com/iree/iree-benchmark/builds/1445
For this PR's run, downloads took 1:35 and 4:12 for the two RPIs,
compared to 2:06 and 3:30 before. That looks like it's basically in
the noise. We could do more detailed analysis, but that doesn't seem
worth it to me. Just spot-checking a few, it seems the RPI connected
to the Pixels consistently downloads faster than the ones connected
to the Samsungs.
As for the benchmarks …
> Add default-flags configurations for all TFLite benchmarks

- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileFuseAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/test/tile_fuse_and_vectorize.mlir
Vectorization will turn Linalg ops to vector ops and arith ops. Since we
don't propagate information through arith ops during bufferization. We
can't unconditionally vectorize all the ops. To prevent creating extra
memref.alloc ops, we can't tile along reduction dims.
The next step is to get unroll vector pass in, so we can vectorize more
ops.
This PR improves the performance of transformer-benchmark from 58 ms to
33 ms.
> Enable more vectorizations in LLVMCPUTileFuseAndVectorizePass

- integrations/tensorflow/iree_tf_compiler/TFL/BUILD
- integrations/tensorflow/iree_tf_compiler/TFL/LowerGlobalTensors.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/Passes.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/VerifyFullyConverted.cpp
- integrations/tensorflow/iree_tf_compiler/TFL/test/lower_global_tensors.mlir
Global tensors assume they contain pure floats / integers. This results in
quantized cases failing to lower. Updated the lowering to support quantized
types during the lowering process.
> Support global variables with quantized types

- iree/compiler/Codegen/BUILD
- iree/compiler/Codegen/CMakeLists.txt
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/BUILD
- iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- iree/compiler/Codegen/LLVMCPU/test/illegal_configuration.mlir
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/Passes.cpp
- iree/compiler/Codegen/Passes.h
This PR allows for checking if the `#iree_codegen.translation.info`
and `#iree_codegen.lowering.config` on an operation are valid for a
given pipeline. Apart from verifying existing configurations, it also
allows a search to prune out illegal configurations.
> Add verification hooks for lowering configuration.

- CMakeLists.txt
Fixes https://github.com/google/iree/issues/6575
`git submodule status` is slow, so running it every cmake configure is annoying. This caches the latest git commit that the submodule init check ran successfully at. The check is also a no-op if git or python are not installed, or the source tree is not a git repository.
> Only check submodule status once per git commit.

- iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
- iree/compiler/Codegen/Utils/Utils.cpp
The number of implicit loops in a Linalg op can be greater than
the shape rank of the result. We can tile loops not corresponding
to the result dimension. Guard against such cases.
> Avoid out-of-bound access when setting shape dimension size

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileFuseAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/Passes.h
- iree/test/e2e/cpu_specific/BUILD
- iree/test/e2e/cpu_specific/CMakeLists.txt
Also delete unnecessary flags for the pass since everything should be
lowered to vectors if possible.
> Use TileFuseAndVectorize pipeline for x86 by default.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
The matmulVectorSize flag is actually unsued in LLVM CPU codegen because
the native_vector_size attribute will always be set in entry point
function. However, we can not expect every entry point function has the
attribute. Because VMVX backend uses the config and does not have the
attribute. In this case, the PR merges matmulVectorSize into
clNativeVectorSizeInBytes.
Also fixes a typo in error message.
> [Cleanup] Delete unused flags.

- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
This may be triggering bad codegen behavior.
> Disabling streams dispatch region specialization.

- .pylintrc
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_presentation.py
- build_tools/benchmarks/run_benchmarks_on_android.py
This is not the prettiest Python I've ever written, but it does allow
restarting benchmark runs rather than losing all progress after a
single failure. This makes the workflow of starting a benchmarking run
and then coming back when it is finished far more workable.
I tried out incremental output of the final json results and reloading
from that, but decided against it because I had to manually construct
json (no native incremental support) and use context handlers to ensure
structures were closed even on a failure exit. Overall it ended up
being pretty gross. Since we were already using temporary files for
captures, this seemed like a reasonable way to go.
> Make benchmarking script more fault-tolerant

- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/illegal_configuration.mlir
When configuration is verified outside of compilation, the operation
might be the one that is eventually distributed. So there is no way of
getting the partitioned loops. For now disable checking for exact
match for these cases.
> Address spurious error when verifying configuration outside of compilation

- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/Input/InputOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Passes.td
- llvm-external-projects/iree-dialects/lib/Dialect/Input/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/Input/InputOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/PadContractionToBlockSize.cpp
- llvm-external-projects/iree-dialects/test/iree_linalgext/pad_contraction_to_block_size.mlir
* Unlike the existing POC pass in the flow dialect, this handles both static and dynamic shapes. It also uses walk vs a pattern so as to better control once-only rewriting in the dynamic case.
* Only pads row major matmul right now but should be extensible to other contractions relatively easily.
* Will be followed by a pass to propagate padding.
> Adds a new pad-contraction-to-block-size pass.

- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
Implement `BufferiableOpInterface` on `DispatchTensorLoadOp` and
`DispatchTensorStoreOp`, so that these ops can be bufferized directly. Configure and run Comprehensive Bufferize via `runComprehensiveBufferize` without leaking internals of the bufferization.
Note: This change is dependent on MLIR D113723 and D113726.
> IREEComprehensiveBufferize: Use new op interface

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
These don't change between runs and just waste time, bandwidth, and
storage space.
> Don't upload tflite files as part of benchmark artifacts

- iree/compiler/Codegen/Common/RemoveTrivialLoops.cpp
- iree/compiler/Codegen/Common/test/remove_trivial_loops.mlir
Now we can also recognize tiled loops that are distributed to
workitems, `getTiledAndDistributedLoopInfo` can return loops
distributed both to workgroups and workitems. We need to filter
only those for workgroups in order to deduce workgroup count.
> Fix workgroup count deduction in RemoveTrivialLoops

- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
Missed by https://github.com/google/iree/commit/ee91353ec3089ea793b90d8203572aea471fb5f2 since this isn't building with Bazel yet.
> Fixes for CModuleTarget after LLVM update.

- iree/compiler/Codegen/LLVMCPU/test/vector_contract_to_aarch64_asm.mlir
There are some extra ops in the input here that aren't required for the
test.
> Clean up lit test for vector.contract -> aarch64 asm

- iree/compiler/Codegen/Common/CleanupBufferAllocViewPass.cpp
- iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.h
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/Transforms/MaterializeInterfaces.cpp
- iree/compiler/Dialect/HAL/Transforms/MaterializeInterfaces2.cpp
- iree/compiler/Dialect/Stream/IR/StreamOps.cpp
- iree/compiler/Dialect/Stream/IR/StreamOps.td
- iree/compiler/Dialect/Stream/Transforms/AnnotateDispatchArguments.cpp
- iree/compiler/Dialect/Stream/Transforms/BUILD
- iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.h
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/annotate_dispatch_arguments.mlir
- iree/compiler/Dialect/Util/IR/UtilTypes.h
This adds `stream.alignment` attributes to `!stream.binding` and `index`
operands in dispatch functions and `stream.values` attributes to integer
operands. The alignment on bindings indicates the base binding offset
alignment while the alignment on index operands indicates the alignment
of any offset into a binding they may represent. The values are all
potential values that may be passed in the operand when knowable.
The final piece required is to use this information in the codegen
backends, however the `memref.assume_alignment` op doesn't seem to do
anything today. This would in theory plumb the information through
but there are likely better ways to use this information:
```cpp
auto alignment = baseBuffer.calculateAlignment();
b.create<memref::AssumeAlignmentOp>(op->getLoc(), …
```
> Adding alignment analysis and propagation into codegen.

- iree/compiler/Dialect/Stream/Transforms/FuseDispatchBindings.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/fuse_dispatch_bindings.mlir
- iree/compiler/Dialect/Stream/Transforms/test/fuse_dispatch_bindings_noalias.mlir
Inducing aliasing of mutable bindings breaks autovectorization in LLVM
and may have issues in other backends as well. This workaround disables
fusing any mutable resources such that they remain unique looking to
the compiler.
This is not ideal: it results in a lot more bindings being tracked that
otherwise would not need to be. Hopefully once we stop using the
autovectorizer we can flip this back on. At least with this change we
have a way to compare the performance on various backends while we try
to get them working.
> Disabling fusion of mutable resource bindings.

- iree/compiler/Translation/IREEVM.cpp
The majority of the previous regressions are fixed with #7716 - mostly looking like aliasing of mutable bindings disabling vectorization.
> Turning on streams by default.

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
Change to use `git clean -fdx`. This will also remove stuff ignored
in `.gitignore` files, particularly the `build-*` directories.
We are seeing out of space issues on Raspberry Pi devices due to
that we download build artifacts from the cloud and unzip them.
> Perform deep clean for benchmark steps

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileFuseAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/test/tile_fuse_and_vectorize.mlir
This PR enables tiling reduction loop in L1 tiling, and unrolls the
loops with native vector sizes.
Vector unrolling could introduce register pressure issue. To prevent
regression at this moment, we explicitly set default L1 tile sizes to
16,16,16 for x86. Vector unrolling does nothing in this case. I tested
with different tile sizes (e.g.,16,16,32), there were differences. As
mentioned. we use 16,16,16 as default to prevent big regressions.
The next steps is to figure out different configurations between sandbox
and IREE. Might have to set up different vector.contract lowering
strategies, and tune with different tile sizes.
Before unrolling:
```
----------------------------------------------------------------------------------------
Benchmark …
```
> Hook vector unrolling in LLVMTileFuseAndVectorizePass.

- iree/hal/vulkan/descriptor_pool_cache.cc
- iree/hal/vulkan/descriptor_pool_cache.h
The descriptor count is not per descriptor set but a sum of all available
in the entire pool - whoops. Most drivers seem to ignore the specific
typed pool sizes and just use the maxSets but Mali drivers do not and
this was causing the pool to run out of memory after nearly every single
use.
Before:
After:
> Fixing VK descriptor pool initialization for push descriptor fallback.

- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
No need to link dynamic libraries or discover + use a `LinkerTool` when using the static library path.
> Clean up branching in LLVM serializeExecutable function.

- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/set_android_scaling_governor.sh
- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
The aim is that this will reduce variance in benchmarks. Notably, this
reduces our ability to capture important real-world scenarios, like
running across threads with different clock speeds. We are deliberately
making a tradeoff right now to get variance under control and we may
revisit this in the future. Pinning to max clock speed is safe and
consistent only because the benchmark phones are on cooling plates so
thermal throttling won't be a problem.
Only the Pixel phone is pinned because we don't have the Samsung phones
rooted (because Samsung makes this a PITA and doing so caused the phone
to randomly reboot all the time).
> Set CPUs to max frequency before running benchmarks

- iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRPasses.cpp
Local variables are constructed in their order of declaration and destructed in the reverse order at end of scope. As `passManager` references `ostream`, it should be constructed after it so it gets destructed before it.
ASan report:
```
==1714714==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fff59769760 at pc 0x0000097d0cbb bp 0x7fff59769490 sp 0x7fff59769488
READ of size 8 at 0x7fff59769760 thread T0
#0 0x97d0cba in llvm::formatted_raw_ostream::releaseStream() /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/Support/FormattedStream.h
#1 0x1159f056 in llvm::formatted_raw_ostream::~formatted_raw_ostream() /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/Support/FormattedStream.h:116:5
#2 0x1159f056 in …
```
> Fix use-after-free of ostream in the passManager dtor

- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/SPIRV/CMakeLists.txt
- iree/compiler/Dialect/HAL/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Shape/IR/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/MemRefToVM/CMakeLists.txt
LLVM integration caused some failures for our OSS builds. Fixed the CMake files to correct.
> Fix CMakeList files caused by the most recent integrate

- iree/hal/buffer_view.c
- iree/samples/variables_and_state/main.c
This should fix the failure at https://buildkite.com/iree/iree-samples/builds/161#a9112912-550a-4e09-847a-afb3c4d56c5b
`[2021-11-25T00:25:28Z] ../iree/modules/hal/module.c:688: INVALID_ARGUMENT; tensor shape rank mismatch; expected 0 but have 1; expected shape , actual shape 1; while invoking native function hal.buffer_view.assert; while calling import;`
> Fix rank 0 buffer view usage in variables and state sample.

- docs/website/docs/deployment-configurations/bare-metal.md
- iree/compiler/Dialect/Stream/Analysis/Partitioning/ReferencePartitioning.cpp
- iree/compiler/Dialect/Stream/IR/StreamBase.td
- iree/compiler/Dialect/Stream/IR/StreamTypes.cpp
- iree/compiler/Dialect/Stream/Transforms/test/schedule_concurrency.mlir
The `#stream.partitioning_config` attribute can be added to the module/functions/etc to control this explicitly and otherwise the `-iree-stream-partitioning-favor=` flag will be used as a default.
- `debug` disables all partitioning for concurrency (and in the future when partitioning command buffers for concurrency).
- `min-peak-memory` attempts to preserve the debug-level memory consumption by only optimistically scheduling work concurrently.
- `max-concurrency` reorders ops to try to extract the maximum amount of concurrency allowed by the program - it's not a fantastic algorithm and in the future we can reduce the memory consumption with better clustering/SCC.
Models primarily designed for single-threaded execution should favor `min-peak-memory` while those for multithreaded/GPU …
> Exposes control over the partitioning favor mode on the command line.

- iree/hal/dylib/registration/driver_module.c
- iree/hal/dylib/registration/driver_module_sync.c
- iree/hal/local/sync_device.c
- iree/hal/local/sync_device.h
- iree/hal/local/sync_driver.c
- iree/hal/local/sync_driver.h
- iree/hal/local/task_device.c
- iree/hal/local/task_device.h
- iree/hal/local/task_driver.c
- iree/hal/local/task_driver.h
- iree/hal/vmvx/registration/driver_module.c
- iree/hal/vmvx/registration/driver_module_sync.c
- iree/samples/simple_embedding/device_cuda.c
- iree/samples/simple_embedding/device_dylib.c
- iree/samples/simple_embedding/device_embedded_sync.c
- iree/samples/simple_embedding/device_vmvx_sync.c
- iree/samples/simple_embedding/device_vulkan.c
- iree/samples/simple_embedding/simple_embedding.c
- iree/samples/static_library/static_library_demo.c
This allows shims or non-heap allocators to be used.
> Making local HAL devices to take a device allocator as an argument.

- iree/hal/cuda/executable_layout.c
- iree/hal/cuda/executable_layout.h
- iree/hal/cuda/graph_command_buffer.c
- iree/hal/cuda/native_executable.c
- iree/hal/cuda/native_executable.h
This is needed as push constant command may not be sent again
> [CUDA] Fill out push constant kernel arguments at dispatch time

- iree/hal/cuda/cuda_allocator.c
- iree/hal/cuda/cuda_driver.c
My device (2080Ti/Windows) does not have this feature and this allows me
to run things even if device-local + host-visible buffers will be slower.
The streams-enabled compiler puts most things in device-local memory
besides I/O and that's something we can fix (stage inputs parsed from
the command line and annotate outputs to be device-local).
> Enabling CUDA on devices without CONCURRENT_MANAGED_ACCESS.

- build_tools/cmake/iree_copts.cmake
Adding `-DIREE_SIZE_OPTIMIZED=1` should now turn off most extra features.
> Adding some of the new size-optimized flags to the config.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileFuseAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
It speeds up matmul perf 10% ~ 20% on x86. This also splits x86 and ARM
configurations into two methods to have better structure.
The tile sizes for x86 are not well-tuned. This is a demonstration that
how vector unrolling helps performance in IREE.
Before:
```
----------------------------------------------------------------------------------------
Benchmark                                              Time             CPU   Iterations
----------------------------------------------------------------------------------------
BM_dot_384x384x512/process_time/real_time           2.78 ms         2.79 ms          249
BM_dot_384x128x128/process_time/real_time          0.153 ms        0.153 ms         4561
BM_dot_384x128x512/process_time/real_time          0.596 ms        0.598 ms         1183 …
```
> Truely apply vector unrolling in TileFuseAndVectorize pipeline.

- iree/compiler/InputConversion/MHLO/MHLOToLinalgOnTensors.cpp
- iree/compiler/InputConversion/MHLO/test/BUILD
- iree/compiler/InputConversion/MHLO/test/CMakeLists.txt
- iree/compiler/InputConversion/MHLO/test/broadcasting.mlir
- iree/compiler/InputConversion/MHLO/test/convert_structural_types.mlir
* This allows us to to type conversion for unsigned types (among other things) at the boundaries.
* I may break this out to a separate pass a bit later when I attempt to collapse the XLA-unweirding into the core pipeline.
* Mostly copy and paste from the global input conversion.
* Fixes #7708
> Teach the MHLO->Linalg conversion how to handle functions, blocks and CFG.

- iree/compiler/InputConversion/MHLO/Passes.cpp
This pass is horribly broken, and LegalizeControlFlow actual does a reasonable job of lowering to CFG.
Will follow up to delete the pass upstream.
> Remove mhlo control flow to SCF.

- iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
This should fix the build failure reported at https://github.com/google/iree/pull/7662#discussion_r761391994
(Logs: https://buildkite.com/iree/iree-build-configurations/builds/1496#91c054cd-df7a-4758-84bd-91a621668581)
> Disambiguate call to LinalgTransformationFilter constructor.

- docs/website/mkdocs.yml
See https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
(Broken since around October?)
> Fix content tabs on website.

- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/fold_globals.mlir
- iree/compiler/Dialect/Util/Transforms/FoldGlobals.cpp
When the folded constant global is not buildable with arith/std.constant
the dialect owning the attribute will be asked to materialize it.
If it's not possible then we bail gracefully and don't try to inline
the global.
Fixes #7808.
> Fixing iree-util-fold-globals to materialize custom constants.

- benchmarks/TFLite/CMakeLists.txt
This adds multi-threaded big-core benchmarks for the full configuration
matrix. We are optimizing performance primarily on big cores right now.
This also includes switching our single VMVX benchmark to use big cores
instead of little. This benchmark is mostly for reference and big cores
are more useful for this, plus the benchmark will take less time. Note
that this will mean we are starting a new series for this and won't be
able to easily compare with previous history. I don't think we care.
Fixes https://github.com/google/iree/pull/7807
> Add big-core multi-threaded benchmarks

- iree/compiler/Dialect/Stream/IR/StreamDialect.cpp
- iree/compiler/Dialect/Stream/IR/StreamDialect.h
- iree/compiler/Dialect/Stream/IR/test/resource_folding.mlir
- iree/compiler/Dialect/Stream/Transforms/test/convert_to_stream.mlir
Most are pruned by construction as the conversion consumes the original
values but any op that is handled generically may leave them around
(such as selects).
> Cleanup unrealized_conversion_casts that survive stream conversion.

- iree/compiler/Dialect/Stream/IR/StreamOpFolders.cpp
- iree/compiler/Dialect/Stream/IR/test/resource_folding.mlir
This changes the selects from controlling a resource to controlling an
offset which removes the need for runtime subview tracking and allows for
better binding utilization.
Example (which wouldn't exist for this particular case if #7816 was done, but is valid and likely to arise in other cases):
(the additional timepoint joins will go away with #7822)
Fixes #7821.
> Sink subviews across select ops.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileFuseAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/LLVMCPU/test/tile_fuse_and_vectorize.mlir
- iree/compiler/Codegen/Passes.h
- Add an option to not vectorize in TileFuseAndVectorizeLinalgTensorOps,
which is required by VMVX backend.
- Tile reduction loops if the tile size is greater than dim size.
- Add another level of tiling when ops are not vectorizable.
Configurations: taskset 80 + dylib-sync on local Pixel 4
| Model            | Before  | After   |
| ---------------- | ------- | ------- |
| DeepLabV3        | 956 ms  | 955 ms  |
| MobileBertSquad  | 682 ms  | 679 ms  |
| MobileNetV2      | 173 ms  | 173 ms  |
| MobileNetV3Small | 44.8 ms | 47.3 ms |
| MobileSSD        | 365 ms  | 375 ms  |
| PoseNet          | 873 ms  | 884 ms  |
Before:
```
----------------------------------------------------------------------------------------
Benchmark                                              Time             CPU …
```
> Switch matmul default CPU codegen to use TileFuseAndVectorize pipeline.

- iree/compiler/Dialect/Stream/Analysis/Partitioning.cpp
- iree/compiler/Dialect/Stream/Analysis/Partitioning/ReferencePartitioning.cpp
- iree/compiler/Dialect/Stream/IR/StreamDialect.cpp
- iree/compiler/Dialect/Stream/Transforms/test/schedule_execution.mlir
Fixes #7813. The issue reported was an overaggressive verification but immediately behind that was a real issue.
> Fixing partitioning when ops are cloned across partitions in various orders.

- llvm-external-projects/iree-compiler-api/lib/CAPI/CMakeLists.txt
After
https://github.com/llvm/llvm-project/commit/9e3552523ebd3385487e01e3e7af37b8c0efaf57
this dependency no longer exists.
> Remove lldDriver dependency

- iree/hal/cuda/registration/driver_module.c
- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
As we currently don't support command buffer caching using CUDA streams
allows us to avoid runtime overhead related to graph creation. We will
pick based on the command buffers once we support caching.
> [CUDA HAL] Use CUDA streams by default

- build_tools/bazel/build_core.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build.sh
- build_tools/pytype/check_diff.sh
xargs will partition the args it passes through based on some limit.
The default limit configured in xargs is generally much much lower than
the actual upper limits for the system. For instance, on my system:
```shell
$ xargs --show-limits
Your environment variables take up 4819 bytes
POSIX upper limit on argument length (this system): 2090285
POSIX smallest allowable upper limit on argument length (all systems): 4096
Maximum length of command we could actually use: 2085466
Size of command buffer we are actually using: 131072
Maximum parallelism (--max-procs must be no greater): 2147483647
```
(system limit is 16x configured limit). We don't want multiple Bazel
invocations because a) it's unnecessarily slow, and b) a `bazel test`
invocation that doesn't contain any test targets will fail, …
> Raise xargs limits

- README.md
The previous version had non-functional URLs. See #7832
> Update IREE Runtime Design talk slides

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.h
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.h
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/VMAnalysis.h
This moves the VM analysis cache into the EmitC type converter in preparation for switching to target materializations.
> [NFC] EmitC analysis cleanup

- iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- iree/compiler/Dialect/HAL/Target/VMVX/test/linking.mlir
* Tests for vmvx since this is in common code.
> Adapt linking to rename symbols in any FunctionLike op.

- iree/compiler/Dialect/HAL/Target/VMVX/test/smoketest.mlir
- iree/compiler/Dialect/VM/Conversion/ConversionTarget.cpp
- iree/compiler/Dialect/VM/Conversion/ConversionTarget.h
- iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/BUILD
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/CMakeLists.txt
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/nesting.mlir
- iree/compiler/Dialect/VM/Conversion/StandardToVM/test/structural_ops.mlir
Introduces an explicit `vm.toplevel` attribute when setting up the nesting and then uses this as a signal that a nested module should be considered legal and left alone. The heuristic previously in use was to attempt to infer this based on parents. This turned out to be fragile if nesting a new module in an existing module (i.e. to extract a partial program and compile it without intending to create a layering issue).
I was going to clean the attribute up at the end but opted to leave it there as it was a good debugging aid as I tried to figure out what was going on.
Moved the one nesting test to a new nesting.mlir test case and reworked it to use a non-root based pipeline, which is more realistic for this scenario. Also, verified that what this test was doing was wrong (checks on …
> Rework module nesting in VM conversion.

- iree/test/e2e/xla_ops/partial/BUILD
- iree/test/e2e/xla_ops/partial/CMakeLists.txt
These tests aren't supported on many platforms (in particular,
swiftshader) and it's nice for wildcard runs to succeed.
> Mark f16 vulkan tests as manual

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
sort op shouldn't go through the vectorization path as it generate
linalg copy ops that need to be fully serialized and would create large
vectors. For simplicity we just use the basic pipeline for sort op.
> [CUDA] Add config for sort op

- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Stream/Conversion/FlowToStream/ConvertFlowToStream.cpp
Stops #7897 earlier in the pipeline with a nice message:
`dynamic_iota.mlir:6:10: error: 'flow.dispatch.workgroups' op I/O type 'tensor<index>' is invalid: index types must not cross the dispatch boundary`
> Verifying that index types do not cross dispatch boundaries.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
The comprehensive bufferization would create alloca ops, so we moved to
use IREE bufferization.
| Model            | Before  | After   |
| ---------------- | ------- | ------- |
| DeepLabV3        | 964 ms  | 954 ms  |
| MobileBertSquad  | 682 ms  | 682 ms  |
| MobileNetV2      | 177 ms  | 176 ms  |
| MobileNetV3Small | 47.6 ms | 47.5 ms |
| MobileSSD        | 365 ms  | 368 ms  |
| PoseNet          | 884 ms  | 884 ms  |
There is a slightly improvement (10ms) in DeepLabV3.
> Fixes builds and comments for SingleTilingExpert pipeline.

- CMakeLists.txt
- build_tools/cmake/iree_third_party_cmake_options.cmake
- build_tools/third_party/spirv-tools/CMakeLists.txt
- build_tools/third_party/tint/CMakeLists.txt
- iree/tools/utils/BUILD
- iree/tools/utils/CMakeLists.txt
Part of https://github.com/google/iree/issues/7840
`IREE_HAL_DRIVERS_TO_BUILD` and `IREE_TARGET_BACKENDS_TO_BUILD` now use "default" instead of "all".
The new WebGPU compiler target is included in the list of all targets but is _not_ enabled by default, and the Metal+CUDA targets similarly disable themselves on incompatible platforms. Developers must explicitly opt in to building the WebGPU compiler target or the Metal/CUDA targets in unsupported configurations. I'm using `-DIREE_TARGET_BACKENDS_TO_BUILD=CUDA;Dylib-LLVM-AOT;WASM-LLVM-AOT;Vulkan-SPIRV;VMVX;WebGPU`, for example.
Thanks to being conditionally enabled, we can also use CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) instead of git submodules for some dependencies, which will _hopefully_ …
> Add WebGPU dependencies and refactor *_TO_BUILD CMake options.

- iree/compiler/InputConversion/TOSA/Passes.cpp
Tosa to linalg defines a series of passes for conversion. We shoul use
the entire pipeline.
> Use the entire TosaToLinalg pass chain

- iree/compiler/Dialect/HAL/Target/WebGPU/WebGPUTarget.cpp
(forgot about this when merging the initial implementation of WebGPUTarget)
This now uses the new serialization control provided by https://reviews.llvm.org/D115531. I didn't see much of an effect on simple_abs, but this may do more for complex programs.
> Plumb through spirv serialization options in WebGPUTarget.

- iree/compiler/ConstEval/BUILD
- iree/compiler/ConstEval/CMakeLists.txt
- iree/compiler/ConstEval/JitGlobals.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Util/Transforms/BUILD
- iree/compiler/Dialect/Util/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Util/Transforms/FixedPointIterator.cpp
- iree/compiler/Dialect/Util/Transforms/Passes.h
- iree/compiler/Translation/BUILD
- iree/compiler/Translation/CMakeLists.txt
- iree/compiler/Translation/IREEVM.cpp
- iree/compiler/Translation/IREEVM.h
- iree/compiler/Utils/BUILD
- iree/compiler/Utils/CMakeLists.txt
- iree/compiler/Utils/PassUtils.cpp
- iree/compiler/Utils/PassUtils.h
- llvm-external-projects/iree-compiler-api/lib/CAPI/Compiler.cpp
* Adds two new compiler flags: -iree-const-eval and -iree-const-expr-hoisting. The former will be a permanent flag and the latter will be retired once stable and enabled by default.
* Reworks the flow pipeline to have its high level optimizations run through a dynamic fixed-point iteration pass pipeline. The const-eval pass is capable of signalling additional iterations, allowing progressive program simplification. By default, there will only be one cycle.
* Neither of these passes work for a sizable portion of programs, and they represent some fairly extensive compiler fuzzing that I will need to triage to completion before enabling by default.
> Plumb through const-expr hoisting and const-eval pipelines.

- iree/compiler/ConstEval/JitGlobals.cpp
- iree/compiler/ConstEval/test/jit_globals.mlir
Was causing an error due to an empty program.
> When evaluating globals, do nothing if none are undefined.

- CMakeLists.txt
Makes the error on uninitialized submodules optional. With this,
external projects that use IREE are no longer forced to initialize all
submodules. E.g. if a project only uses the runtime and does not reply
on the TensorFlow integration, these submodules don't have to be cloned
at all. This is especially convenient in CI pipelines.
> Allow to turn of error on uninitialized submodules

- benchmarks/TFLite/CMakeLists.txt
See discussion at
https://github.com/google/iree/pull/7807#issuecomment-985790882 and
onwards. This disables a number of benchmarks that aren't super useful,
and in particular aren't worth delaying presubmit (and in some cases
per-commit postsubmit) runs.
1. All little-core experimental-flags benchmarks: we are not currently 
optimizing little-core.
2. 2 and 3 thread CPU benchmarks. 1 and 4 threads give us basically
everything we need.
Drops benchmarking phone time from
[54 minutes](https://buildkite.com/iree/iree-benchmark/builds/1703)
to [35 minutes](https://buildkite.com/iree/iree-benchmark/builds/1706)
> Disable less-used benchmarks

- iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp
- iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.h
- iree/compiler/Dialect/Util/Analysis/Constant/OpOracle.cpp
- iree/compiler/Dialect/Util/Analysis/Constant/OpOracle.h
- iree/compiler/Dialect/Util/Transforms/HoistIntoGlobals.cpp
- iree/compiler/Dialect/Util/Transforms/test/hoist_into_globals.mlir
* Also reworks the hoisting transformation to consider the producer tree from the analysis authoritative vs relying on creating a backward slice.
* This is needed to handle implicit captures correctly and has the byproduct of making a more precise clone (the prior version would sometimes materialize extra dead ops for odd const-expr tree shapes).
> Treat nested implicit captures as producers for const-expr analysis.

- build_tools/cmake/iree_copts.cmake
There seems to be a version dependency on whether this flag gates all C11 related features, which is causing the CI releases to fail on missing support for _Generic.
Setting this option per the recommendation at https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/ as a first step. That post also indicates a tie-in to a Windows update (??? - really, for a pre-processor change), but starting here.
This will now hard fail on older versions of MSVC (<16.9 iiuc). This is deemed better than soft failures due to unsupported compiler features.
> Enable /std:c11 for MSVC builds.

- benchmarks/TFLite/CMakeLists.txt
This flag does not seem to actually be doing what it was supposed to be doing. Dropping this flag from benchmarks makes no difference (all differences seem to be noise).
> Drop -iree-flow-inline-constants-max-byte-length flag usage from benchmarks.

- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups_folding.mlir
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/test/e2e/xla_ops/fft.mlir
Inlining constants into dispatch regions causes type mismatches with
`flow.dispatch.tensor.load`/`flow.dispatch.tensor.store`
operations. These could be traiaged, but it is better to anyway inline
during dispatch region formation anyway.
Somehow this PR also seems to expose another bug in testing `fft` on
SPIR-V backend. The `xla_ops/fft.mlir` has two functions. Running each
of them in isolation passes, but run together it fails. Comment out
one of the functions since its a separate issue (#7919 )
> Move inlining constants into dispatch regions out of canonicalization.

- iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp
- iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.h
- iree/compiler/Dialect/Util/Analysis/Constant/OpOracle.cpp
- iree/compiler/Dialect/Util/Transforms/HoistIntoGlobals.cpp
- iree/compiler/Dialect/Util/Transforms/test/hoist_into_globals.mlir
* Adds a policy/decision layer on top of the analysis.
* Reworks the transformation to be based purely on the policy with no inline decisions.
* Tightens up the policy a bit to better handle:
* Never hoisting a standalone init_tensor
* Working properly with a chain of non-hoistable leaves (i.e. several broadcast or metadata ops which should not hoist)
> Rework global hoisting to be policy based.

- iree/compiler/ConstEval/JitGlobals.cpp
- iree/compiler/ConstEval/Runtime.cpp
- iree/compiler/ConstEval/Runtime.h
- iree/compiler/ConstEval/test/jit_globals.mlir
- iree/compiler/Translation/IREEVM.cpp
Supported: i8/16/32/64, f32/f64, i1
Unsupported: Non byte-aligned integer, f16, bf16
There are still some VM bugs with i1 which I will need to address separately. Also sub-byte aligned still seems to need a fair bit of work in the system so just punting on that for now.
> Implement all feasible types in JitGlobals.

- docs/developers/developing_iree/testing_guide.md
- iree/compiler/Dialect/Flow/IR/test/executable_ops.mlir
- iree/compiler/Dialect/Flow/IR/test/tensor_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/experimental_ops.mlir
- iree/compiler/Dialect/HAL/IR/test/semaphore_ops.mlir
- iree/compiler/Dialect/VM/IR/test/arithmetic_ops.mlir
- iree/compiler/Dialect/VM/IR/test/assignment_ops.mlir
- iree/compiler/Dialect/VM/IR/test/comparison_ops.mlir
- iree/compiler/Dialect/VM/IR/test/control_flow_ops.mlir
- iree/compiler/Dialect/VM/IR/test/conversion_ops.mlir
- iree/compiler/Dialect/VM/IR/test/debug_ops.mlir
- iree/compiler/Dialect/VM/IR/test/global_ops.mlir
- iree/compiler/Dialect/VM/IR/test/shift_ops.mlir
- iree/compiler/Dialect/VM/IR/test/structural_ops.mlir
The file path/name conventions already convey this information.
Unrelated, but I also checked for any .mlir files with `// RUN` lines that don't include `| IreeFileCheck` using this regex: `//\srun[^|]+\n`. The only matches either intentionally disable testing or test for expected errors.
> Remove "Tests printing and parsing of" comments.

- iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp
- iree/compiler/Dialect/Util/Analysis/Constant/OpOracle.cpp
- iree/compiler/Dialect/Util/Transforms/test/hoist_into_globals.mlir
This is certainly necessary as a temporary measure, given that layers below this cannot support i1 globals. But I also suspect this is the right long term answer as well (for once we insert appropriate casts).
> Disable hoisting of sub-byte aligned leaf values into globals.

- integrations/tensorflow/iree_tf_compiler/TF/SavedModelToIreeABI.cpp
- iree/compiler/Codegen/Common/ForOpCanonicalizationPass.cpp
- iree/compiler/Codegen/Common/OptimizeVectorTransferPass.cpp
- iree/compiler/Codegen/Common/RemoveTrivialLoops.cpp
- iree/compiler/Codegen/Common/VectorizeMMT4d.cpp
- iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMCPU/VectorContractToAArch64InlineAsmOp.cpp
- iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp
- iree/compiler/Codegen/LLVMGPU/ConvertToNVVM.cpp
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUDistributeSharedMemoryCopy.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUPipelining.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorToCooperativeOps.cpp
- iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- iree/compiler/Codegen/Transforms/AffineMinCanonicalization.cpp
- iree/compiler/Codegen/Transforms/AffineMinDistributedSCFCanonicalization.cpp
- iree/compiler/Codegen/Transforms/RemoveSingleIterationLoop.cpp
- iree/compiler/Dialect/Flow/Conversion/TensorToFlow/ConvertTensorToFlow.cpp
- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
- iree/compiler/Dialect/Flow/Transforms/DestructiveUpdateUtils.cpp
- iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/InterchangeGenericOps.cpp
- iree/compiler/Dialect/Flow/Transforms/PadLinalgOps.cpp
- iree/compiler/Dialect/Flow/Transforms/PadTensorToSubTensorInsert.cpp
- iree/compiler/Dialect/Flow/Transforms/VerifyInputLegality.cpp
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/PyDM/Transforms/ToIREE/LoweringPatterns.cpp
This does _not_ exhaustively update all of the project or add any new automated linting.
clang-tidy can check for this: https://clang.llvm.org/extra/clang-tidy/checks/readability-braces-around-statements.html
I just used regex and manual editting (looking for `if` or `else` without open/close braces) though:
* `if\s[^\{;]*\n`
* ``\s[^\}]+\selse\s[^\{]+``
Style discussions:
* https://google.github.io/styleguide/cppguide.html#Conditionals
* https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements
> Add braces to `if`s where it helps readability and/or debugging.

- iree/compiler/README.md
- iree/hal/README.md
- iree/hal/cts/README.md
- iree/runtime/README.md
- iree/samples/README.md
These parts of the project's architecture are relatively stable and could benefit from some cross referencing and overview documentation.
> Add READMEs to some top level directories.

- iree/hal/driver_registry.c
- iree/hal/driver_registry.h
Users can alloc at startup/free on shutdown to manage the lifetime
and scope of the driver registry. The default registry can still be
used when scoped registries are not required to keep things simpler.
> Adding explicit alloc/free of the HAL driver registry.

- iree/compiler/ConstEval/Runtime.cpp
Avoids conflicts when used from tools that have other uses for the process global registry.
> Use a private driver registry for const eval.

- CMakeLists.txt
Docs:
* https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html
* https://cmake.org/cmake/help/latest/command/option.html
These options will now all automatically be forced to `OFF` when `IREE_BUILD_COMPILER` is `OFF`, rather than use previously cached/configured values.
> Use cmake_dependent_option for options that require IREE_BUILD_COMPILER.

- bindings/python/iree/runtime/function.py
- llvm-external-projects/iree-compiler-api/python/iree/compiler/tools/core.py
- llvm-external-projects/iree-compiler-api/unittests/tools/compiler_core_test.py
* There was a bug with tfs and compiling to in memory output: it would return an empty byte array.
* Added tfs for core-input.mlir when compiling from a string.
* Added tfs for core-command-line.txt to capture the command line.
* On exception the trace will finalize the record it is working on (the call was being completely ommitted, which is not what you want, considering this is often for failure repros).
> Some fixes to python temp file saving and tracing.

- iree/hal/allocator.h
- iree/hal/buffer.h
- iree/hal/command_buffer.h
- iree/hal/descriptor_set.h
- iree/hal/descriptor_set_layout.h
- iree/hal/device.h
- iree/hal/driver.h
- iree/hal/event.h
- iree/hal/executable.h
- iree/hal/executable_cache.h
- iree/hal/executable_layout.h
- iree/hal/resource.h
- iree/hal/semaphore.h
This enables type-generic resource pooling.
> Adding iree_hal_resource_retain/release.

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
We cannot pin down GPU frequency on these phones reliably, even
with rooting. The numbers reported by these phones fluctuate to
a greate extent, rendering them basically unless. Having them
is brininging more confusion than help now given we can use
Pixel 6 Pro for Mali GPU benchmarking.
> Stop benchmarking on Galaxy S20

- experimental/rocm/rocm_allocator.c
- experimental/rocm/rocm_device.c
- iree/hal/allocator.c
- iree/hal/allocator.h
- iree/hal/allocator_heap.c
- iree/hal/cuda/cuda_allocator.c
- iree/hal/cuda/cuda_device.c
- iree/hal/device.c
- iree/hal/device.h
- iree/hal/local/sync_device.c
- iree/hal/local/task_device.c
- iree/hal/vulkan/vma_allocator.cc
- iree/hal/vulkan/vulkan_device.cc
- iree/modules/hal/module.c
- iree/runtime/session.c
- iree/runtime/session.h
- iree/task/executor.c
- iree/task/executor.h
- iree/vm/bytecode_module.c
- iree/vm/context.c
- iree/vm/context.h
- iree/vm/module.h
- iree/vm/native_module.c
- iree/vm/native_module_cc.h
This routes notifications to both system and user modules in the VM on suspend/resume and low memory warnings. System modules can implement a notify method for internal handling and here the HAL is extended to trim its pools. The compiler will be able to add a `__notify` export to generated modules that handles end-user resources (computed state from initializers, compiler-owned pools, etc) and we could extend this all the way up to the frontend as a discardable attribute.
> Plumbing a user-level memory trimming and notification API.

- iree/base/internal/arena.c
- iree/base/status.c
- iree/hal/utils/BUILD
- iree/hal/utils/CMakeLists.txt
- iree/hal/utils/resource_set.c
- iree/hal/utils/resource_set.h
- iree/hal/utils/resource_set_benchmark.c
- iree/hal/utils/resource_set_test.cc
- iree/testing/benchmark_full.cc
This utility allows for efficient tracking of resource lifetime by
relying on false negatives on set insertion being valid. Basically we
only need to ensure that each resource is inserted at least once and
the only cost to inserting it multiple times is a retain/release and
sizeof(void*). By relying on a block pool and inlining the sets into
the first block acquired we also stay (steady-state) allocation-free
and in the cases where the compiler does a good job will never grow
at all (once we canonicalize interfaces). That puts us in the nice
place of being able to reduce the overhead of this with compiler
tweaks.
A big design point here was to make this possible to implement with
SIMD operations. We're already in the double-digit nanosecond territory
and can go even faster (~20 cycles per …
> Adding iree_hal_resource_set_t.

- iree/base/internal/arena.c
- iree/compiler/Bindings/Native/Transforms/WrapEntryPoints.cpp
- iree/compiler/Bindings/Native/Transforms/test/wrap_entry_points.mlir
- iree/compiler/Bindings/TFLite/Transforms/WrapEntryPoints.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
- iree/compiler/Dialect/HAL/IR/test/tensor_ops.mlir
- iree/compiler/Dialect/Stream/Conversion/HALToStream/ConvertHALToStream.cpp
- iree/compiler/Dialect/Stream/Conversion/HALToStream/test/abi_ops.mlir
- iree/compiler/InputConversion/Common/IREEImportPublic.cpp
- iree/hal/local/task_command_buffer.c
- iree/modules/hal/module.c
- iree/task/api.c
- iree/tools/utils/trace_replay.c
- iree/tools/utils/vm_util.cc
- iree/tools/utils/vm_util_test.cc
- iree/vm/list.c
This allows frontends to control the storage for exported tensors by
tying arguments to results. Today it's required that these do not alias
but we could do fun things in the future with providing slabs to place
multiple results into.
The native bindings have been updated to support iree.abi.output arg
attrs indicating the result an argument provides storage for. Other
bindings may decide this on their own however they want.
There's still inefficiencies here (a copy is almost always performed)
but this allows us to avoid the allocation and eliding the copy is
something that we eventually need to do anyway.
Output buffers can now be passed to tools as inputs with leading `&`
(indicating storage reference), ex: `--function_input=&4x8xf32`.
> Adding optional target_storage to hal.tensor.export.

- experimental/rocm/rocm_device.c
- iree/hal/command_buffer.h
- iree/hal/cuda/BUILD
- iree/hal/cuda/CMakeLists.txt
- iree/hal/cuda/cuda_device.c
- iree/hal/cuda/graph_command_buffer.c
- iree/hal/cuda/graph_command_buffer.h
- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
- iree/hal/local/task_command_buffer.c
- iree/hal/utils/BUILD
- iree/hal/utils/CMakeLists.txt
- iree/hal/utils/deferred_command_buffer.c
- iree/hal/utils/resource_set.c
- iree/hal/utils/resource_set.h
- iree/hal/vulkan/BUILD
- iree/hal/vulkan/CMakeLists.txt
- iree/hal/vulkan/direct_command_buffer.cc
- iree/hal/vulkan/direct_command_buffer.h
- iree/hal/vulkan/vulkan_device.cc
- iree/modules/hal/module.c
Command buffers that execute asynchronously now need to ensure the lifetime of all referenced resources extends for as long as the command buffer lives. Future changes will extend this to device queues/semaphores.
By tracking lifetime on command buffers we can remove the deferred release list that was performing lifetime tracking on the HAL VM module - it was using a generic VM list (24 bytes per entry vs 8 on 64-bit) and limited us to a single device/command buffer and synchronous submission: now when we get around to attaching lifetime to timepoints we can correctly track lifetime in asynchronous programs 🎉 
An important user-visible reason we bring the lifetime tracking into the HAL is that when we start to mix asynchronous host application code, compiler-generated code, and custom …
> Moving resource lifetime tracking to command buffers.

- docs/website/docs/reference/optimization-options.md
- docs/website/mkdocs.yml
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Translation/IREEVM.cpp
- iree/compiler/Translation/IREEVM.h
* Prefixes other high level optimization options with "--iree-opt".
* Adds optimization-options.md and backfills with existing options.
> Add --iree-opt-numeric-precision-reduction option.

- iree/samples/vulkan/vulkan_inference_gui.cc
- iree/testing/vulkan/vulkan_gui_util.cc
This sample compiles and runs again now, though it has validation layer errors about leaks on shutdown. We might also move this out of the core repo soon anyways (https://github.com/google/iree/issues/8011).
* `$async` ABI was removed in https://github.com/google/iree/pull/6200
* timeline semaphore feature must be enabled during device creation (IREE itself does this already, but the device created by the hosting application in the sample was not)
* removed `iree_allocator_system()` extra argument to `iree_hal_buffer_view_allocate_buffer`
> Fix vulkan_inference_gui sample after HAL and ABI changes.

- build_tools/benchmarks/common/benchmark_thresholds.py
Now we have removed Galaxy S20 and rely on Pixel 6 Pro,
which gives stable numbers. The threshold should be adjusted.
> Adjust benchmark threshold for mobile GPUs

- experimental/rocm/cts/CMakeLists.txt
- iree/hal/cts/CMakeLists.txt
- iree/hal/cts/command_buffer_dispatch_test.h
- iree/hal/cts/command_buffer_test.h
- iree/hal/cts/cts_test_template.cc.in
- iree/hal/cts/descriptor_set_test.h
- iree/hal/cts/testdata/command_buffer_dispatch_test.mlir
- iree/hal/cuda/cts/CMakeLists.txt
- iree/hal/vulkan/cts/CMakeLists.txt
~~Depends on https://github.com/google/iree/pull/7982, should be rebased on https://github.com/google/iree/pull/7900~~
Fixes https://github.com/google/iree/issues/5678 (actually runs executable code now!)
The new test currently just computes `abs(f32)` and checks the result, but we can plug more test cases in using push constants, other computations, dispatch workgroups other than 1x1x1, etc.
> Add command_buffer_dispatch_test to the HAL CTS.

- .github/workflows/schedule_candidate_release.yml
- .github/workflows/validate_and_publish_release.yml
- benchmarks/README.md
- colab/edge_detection.ipynb
- colab/low_level_invoke_function.ipynb
- colab/mnist_training.ipynb
- colab/resnet.ipynb
- colab/tensorflow_hub_import.ipynb
- colab/tflite_text_classification.ipynb
- docs/api_docs/python/requirements.txt
- docs/developers/get_started/getting_started_tensorflow.md
- docs/website/docs/bindings/python.md
- docs/website/docs/deployment-configurations/cpu-dylib.md
- docs/website/docs/deployment-configurations/gpu-vulkan.md
- docs/website/docs/ml-frameworks/tensorflow-lite.md
- docs/website/docs/ml-frameworks/tensorflow.md
* Renames the job that kicks it off to use "candidate" instead of "snapshot".
* Keeps the latest-snapshot branch in order to retain compatibility with any workflows depending on it.
> Remove the "-snapshot" release suffix.

- llvm-external-projects/iree-dialects/lib/Dialect/Input/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/PyDM/IR/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/PyDM/Transforms/ToIREE/CMakeLists.txt
Some targets were missing transitive dependencies.
> Add missing transitive dependencies to some targets

- iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
I'd still like to rewrite the pass, but at least now we can get rid of
globals only used for a single store->load - like all descriptor set
layouts in the HAL that are only used in initializers.
> Reordering global simplification to happen before folding.

- iree/hal/cuda/api.h
- iree/hal/cuda/cuda_device.c
- iree/hal/cuda/registration/driver_module.c
This allows command buffers with the
IREE_HAL_COMMAND_BUFFER_MODE_ALLOW_INLINE_EXECUTION flag set to execute
directly against a CUDA stream to lower latency.
Disabled by default because this is slower in almost all cases where the
model actually uses the GPU to do work. simple_embedding_test (a single
dispatch) for example goes 39.47us -> 39.32us with this enabled, while
mobilessd (GPU-bound) goes 2.56s -> 2.69s.
> Adding `--cuda_allow_inline_execution` flag.

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
We dropped S20 for benchmarking. Better to be
consistent here for testing.
Also perform artifacts clean up before each step.
> Replace Galaxy S20 with Pixel 6 for Android testing

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/iree_linalgext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/tiling.mlir
This pass adds the first version of the scan op in
the linalg_ext dialect. Currently, the op requires specifying
the dimension, whether the scan is inclusive or not as well
as body specifying the operator for scan.
The current patch adds code to lower the op to loops
using the naive sequential implementation. The tiled implementation
is borrowed from the sort op.
Finally, some unit tests have also been added to test the passes.
> First pass at linalg_ext.scan op

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/iree_linalgext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/tiling.mlir
This patch removes identity from linalg_ext.scan
and moves it to the inputs variable. This is to
ensure that the op bufferizes with the linalg
comprehensive bufferization.
TEST: Unit tests pass, iree-translate compiles
> Remove identity from linalg_ext.scan arguments

- build_tools/embed_data/generate_embed_data_main.cc
(open to other fixes here, but this seemed like the obvious one to me)
```
[1/4] Building C object experimental/sample_web_...web_static.dir/generated/simple_mul_bytecode.c.o
../experimental/sample_web_static/generated/simple_mul_bytecode.c:38:5: warning:
initializing 'const char *' with an expression of type 'const uint8_t[3991]' (aka 'const unsigned char[3991]')
converts between pointers to integer types where one is of the unique plain 'char' type and the other is
not [-Wpointer-sign]
file_0,
^~~~~~
```
generated code before (note the `const char* data` and `uint8_t`):
```c
typedef struct iree_file_toc_t {
const char* name;             // the file's original name
const char* data;             // beginning of the file
size_t size;                  // length of the file
} …
```
> Cast from uint8_t* to char* in generate_embed_data, fixing warning.

- iree/test/e2e/linalg_ext_ops/BUILD
- iree/test/e2e/linalg_ext_ops/CMakeLists.txt
- iree/test/e2e/linalg_ext_ops/scan.mlir
This patch adds e2e tests for linalg_ext.scan.
The tests validate inclusive/exclusive, add and mul,
and 1d and 2d scans along different dimensions.
> Add e2e tests for linalg_ext.scan op

- docs/website/docs/reference/optimization-options.md
- iree/compiler/Dialect/Util/IR/UtilBase.td
- iree/compiler/Dialect/Util/IR/UtilTraits.h
- iree/compiler/Dialect/Util/Transforms/BUILD
- iree/compiler/Dialect/Util/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Util/Transforms/Passes.h
- iree/compiler/Dialect/Util/Transforms/StripDebugOps.cpp
- iree/compiler/Dialect/Util/Transforms/test/BUILD
- iree/compiler/Dialect/Util/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Util/Transforms/test/strip_debug_ops.mlir
- iree/compiler/Translation/IREEVM.cpp
- iree/compiler/Translation/IREEVM.h
This removes any op with the DebugOnly trait and std.assert.
This is exposed as part of the optimization pipeline stage as
`-iree-opt-strip-assertions`. We may want to run this later on as
well (such as after we insert new assertions in stream/hal/vm) but
the bulk of things that hurt us come from the inputs.
We may want an interface instead of a trait (so we can register on
ops in upstream dialects) but this is all just a workaround for assert
having no optimizations and can change later.
(#8034 and #8074 are the assertion optimizations that we need to do)
> Adding `-iree-util-strip-debug-ops` pass.

- iree/base/internal/threading_pthreads.c
Docs: https://emscripten.org/docs/porting/pthreads.html
[`emscripten_set_thread_name` source](https://github.com/emscripten-core/emscripten/blob/b212beb0171d2f173cd2cc4340b269ebc6f20f38/system/include/emscripten/threading.h#L268-L273):
```c
// Sets the name of the given thread. Pass pthread_self() as the thread ID to
// set the name of the calling thread.
// The name parameter is a UTF-8 encoded string which is truncated to 32 bytes.
// When thread profiler is not enabled (not building with --threadprofiler),
// this is a no-op.
void emscripten_set_thread_name(pthread_t threadId, const char *name);
```
> Emscripten patches for threading_pthreads.c.

- build_tools/bazel/iree.bazelrc
This is triggering in a TensorFlow dep which is building with -Werror.
> Disable bazel warning for GCC 10.

- .github/workflows/build_package.yml
- build_tools/github_actions/build_dist.py
- integrations/tensorflow/python_projects/iree_tf/setup.py
- integrations/tensorflow/python_projects/iree_tflite/setup.py
- integrations/tensorflow/python_projects/iree_xla/setup.py
TensorFlow python packages are now "pure" in that they are built by invoking setup.py and not as part of some larger build. Reworks the release to build them all at once. Will adapt further depending on how the next candidate looks.
> Fixing releases for tensorflow packages

- iree/compiler/Codegen/Common/test/canonicalize_interface_load_store.mlir
- iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
- iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/compiler/Dialect/Flow/IR/test/dispatch_tensor_folding.mlir
- iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups.mlir
- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/CaptureDispatchDynamicDims.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/test/BUILD
- iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/test/capture_dispatch_dynamic_dims.mlir
- iree/compiler/Dialect/Stream/Conversion/FlowToStream/ConvertFlowToStream.cpp
- iree/compiler/Dialect/Stream/Transforms/OutlineConstants.cpp
- iree/compiler/Dialect/Stream/Transforms/PackConstants.cpp
- iree/compiler/Dialect/Util/IR/UtilAttrs.cpp
This ensures that all dynamic dims are available for future passes to
look up without needing to compute them. This is a workaround for
`flow.dispatch.workgroups` (and the outlined variants) not encoding
shape information (which is itself a workaround for `builtin.func` being
used for various reasons). When we can represent the shape dimension
relationships properly we can remove this pass.
This has the benefit of letting us disambiguate shape dims that were
captured as unique values during dispatch region formation. When we
allow user-controlled dispatch regions this will make it easier to form
them. We may also be able to remove the `flow.dispatch.tensor.load/store`
shape captures with this however I'm going to wait until the bigger
reworking to change any more (and have to update a few …
> Fixing dynamic dimension capturing in `flow.dispatch.workgroups`.

- experimental/rocm/rocm_buffer.c
- iree/hal/buffer.c
- iree/hal/buffer.h
- iree/hal/buffer_heap.c
- iree/hal/cuda/cuda_allocator.c
- iree/hal/cuda/cuda_buffer.c
- iree/hal/cuda/native_executable.c
- iree/hal/vulkan/vma_buffer.cc
- iree/modules/hal/module.c
- iree/tools/iree-benchmark-trace-main.c
- iree/tools/iree-e2e-matmul-test.c
- iree/tools/iree-run-trace-main.c
- iree/tools/utils/trace_replay.c
- iree/tools/utils/trace_replay.h
If the HAL module was the last retainer of a buffer (such as those
whose last use was in a command buffer) it was bypassing the device
allocator and directly destroying the buffer. CUDA (and ROCM) require
the allocator to free their buffer memory and this resulted in them
leaking device memory even if it appeared that memory was freed from
our side.
> Ensuring buffer deallocation always routes through allocators.

- build_tools/cmake/build_android_benchmark.sh
The Buildkite benchmark pipeline now fails compilation due to
that it cannot find the `iree-import-tflite` binary after
https://github.com/google/iree/pull/8078.
> Fix benchmark compilation script after TensorFlow de-integration

- .github/workflows/lint.yml
GitHub actions are failing to apt-get install this right
now. I filed a ticket, but disabling so people aren't
blocked.
> Disable clang-format GitHub action

- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- iree/compiler/Codegen/Sandbox/Passes.h
Add a struct that mirrors all the options specified for the
`LinalgSingleTilingExpert` in codegen. This allows the pass pipeline
to control these options.
https://github.com/llvm/llvm-project/issues/53145 is the feature
request to auto-generate the struct (and potentially constructors as
well).
> Struct for controlling all codegen driver options from pass pipeline.

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
Frontends can introduce these and they don't work with our async
execution model. We could support them in the future using the same
kind of mechanism as #8015: pass in a system buffer to dispatches that
could assert and atomic rmw a failure flag we can then lazily check on
the host to indicate device loss.
> Stripping assert ops from within flow.executables.

- iree/base/status.c
- iree/base/status.h
- iree/base/status_cc.h
- iree/compiler/Dialect/Util/IR/UtilTypes.h
- iree/compiler/Dialect/VM/IR/VMOps.cpp
- iree/compiler/Dialect/VM/IR/VMOps.td
- iree/compiler/Dialect/VM/IR/test/control_flow_ops.mlir
- iree/vm/bytecode_disasm.c
- iree/vm/bytecode_dispatch.c
Updating `vm.yield` so that it has a resume branch and returns `IREE_STATUS_DEFERRED` when encountered.
Progress on #8093.
> Preparing for VM coroutine yields via `vm.yield`.

- .github/workflows/lint.yml
This appears to be "fixed" insofar as the hour-long syncs that apparently break GitHub
actions are not happening right now
Reverts google/iree#8098
> Revert "Disable clang-format GitHub action"

- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
1. Flow tiling already selects three shape dimensions and distributes
them to X/Y/Z. Even if some of those dimensions have size one, we
cannot ignore them when deducing the concrete configuration.
Otherwise, we create discrepancy.
2. Avoid vectorization when not all threads in a subgroup is active.
Vectorization patterns (e.g., hoisting) implicitly assume full
subgroup activeness and may perform transforms across loop
boundary.
> [spirv] Fix two issues in default op configuration

- iree/compiler/Codegen/Dialect/LoweringConfig.td
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/BUILD
- iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- iree/compiler/Codegen/LLVMCPU/test/materialize_double_tiling_expert_configuration.mlir
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Sandbox/BUILD
- iree/compiler/Codegen/Sandbox/CMakeLists.txt
- iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- iree/compiler/Codegen/Sandbox/Passes.h
- Add a DoubleTilingExpert pipline which uses sandbox codegen driver
approaches.
- Add a struct that mirrors all the options specified for the
LinalgVectorLowering in codegen. This allows the pass pipeline
to control these options.
- This enables vectorization for other cases that the dim sizes are not
multiples of tile sizes.
- Verified that the final LLVM IRs are almost identical for some matmul
cases, but there still are performance gaps. Thus, the option is not
on by default. We might have to re-pick L1 tile sizes because they are
larger than workgroup sizes in IREE, which is always a one-trip loop.
> Create an e2e DoubleTilingExpert pass pipeline for CPU gemms.

- iree/compiler/Codegen/Dialect/LoweringConfig.cpp
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
- iree/compiler/Dialect/Flow/IR/PartitionableLoopsInterface.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_elementwise.mlir
- iree/compiler/Dialect/Flow/Transforms/test/test_partitionable_loops_interface.mlir
For now revert back to take the innermost parallel dimensions
to match existing behavior. Avoiding bundling the configuration
change together makes infrastructure migration easier.
This also makes all SPIR-V tests to pass.
> Replace getPartitionedLoops with getPartitionableLoops

- docs/website/docs/bindings/python.md
- docs/website/docs/building-from-source/python-bindings-and-importers.md
- docs/website/docs/deployment-configurations/cpu-dylib.md
- docs/website/docs/deployment-configurations/gpu-vulkan.md
- docs/website/docs/ml-frameworks/tensorflow-lite.md
- docs/website/docs/ml-frameworks/tensorflow.md
Part of https://github.com/google/iree/issues/8086
* Drop `--find-links https://github.com/google/iree/releases` / `-f https://github.com/google/iree/releases` from install commands, now that PyPI packages are published. Include a note about nightly releases on just the "Python bindings" page
* Samples and Colab notebooks are still using the nightlies - might keep that for now
* Remove old docs for building the TensorFlow importers and just point to https://github.com/google/iree/tree/main/integrations/tensorflow#readme for now
Just updating this documentation quickly for now. These pages are due for a more dedicated review pass soon (within a month, after a few more pieces stablize?).
> Quick refresh for TensorFlow importer and Python package documentation.

- iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
It was triggering if there were non-constant offsets/sizes/strides but
constant shape dimensions, causing a 1:1 replacement and success return
that caused the canonicalizer to loop forever.
> Fixing check of flow.dispatch.tensor.load constant canonicalization.

- iree/compiler/Dialect/Stream/Conversion/FlowToStream/ConvertFlowToStream.cpp
- iree/compiler/Dialect/Stream/Conversion/FlowToStream/test/BUILD
- iree/compiler/Dialect/Stream/Conversion/FlowToStream/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Conversion/FlowToStream/test/executable_ops.mlir
- iree/compiler/Dialect/Stream/Transforms/test/convert_to_stream.mlir
Now we use the `flow.dispatch.tie_shape` ops to insert the subspan ops where all dynamic dimension SSA values are guaranteed to be valid. Less magic use-def walks, more structure.
> Fixing insertion location of `stream.binding.subspan` ops.

- build_tools/cmake/iree_c_module.cmake
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/samples/emitc_modules/CMakeLists.txt
- iree/samples/static_library/CMakeLists.txt
- iree/vm/module_impl_emitc.c
- iree/vm/test/emitc/module_test.cc
This basically implements the proposal in #7605. The library identified
by `NAME` now contains the implementation whereas a the headers without
implementation are provided by the suffixed target `NAME`_hdrs.
> Generate header-only style libraries with EmitC

- iree/test/e2e/linalg_ext_ops/scan.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/iree_linalgext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/tiling.mlir
This patch modifies the linalg_ext.scan op to
reuse the initial passed identity tensor to contain
the most recent result of the scan operation. This is
to enable a more composable transform during tiling.
Furthermore, this op no longer accepts scalars and
hence scalars must be expressed as rank-0 tensors
or memrefs.
TEST: Added tests in convert_to_loops.mlir, tiling.mlir
and e2e tests in scan.mlir.
> Second version of linalg_ext.scan

- iree/compiler/Codegen/Common/OptimizeVectorTransferPass.cpp
This fixes the codegen for the 2d vector transfers that we need to do
in matmul kernels targeting 2D (matrix) simd operations, for instance
allowing PR #7778 to achieve nice codegen such as:
```
11a14: ad 05 00 f1      subs    x13, x13, #1
11a18: f8 66 c1 ac      ldp    q24, q25, [x23], #32
11a1c: 7a 6f c1 ac      ldp    q26, q27, [x27], #32
11a20: 41 e3 98 4f      sdot    v1.4s, v26.16b, v24.4b[0]
11a24: 60 e3 98 4f      sdot    v0.4s, v27.16b, v24.4b[0]
11a28: 43 e3 b8 4f      sdot    v3.4s, v26.16b, v24.4b[1]
11a2c: 62 e3 b8 4f      sdot    v2.4s, v27.16b, v24.4b[1]
11a30: 46 eb 98 4f      sdot    v6.4s, v26.16b, v24.4b[2]
11a34: 64 eb 98 4f      sdot    v4.4s, v27.16b, v24.4b[2]
11a38: 53 eb b8 4f      sdot    v19.4s, v26.16b, v24.4b[3]
11a3c: 70 eb b8 4f      sdot    v16.4s, v27.16b, …
```
> Enable vector transfer flattening.

- iree/compiler/InputConversion/MHLO/BroadcastingToLinalgPatterns.cpp
- iree/compiler/InputConversion/MHLO/test/broadcasting.mlir
Dynamic shape for MHLO is usually an i32 so include an IndexCastOp to make compatible with flow.tensor.reshape.
> Fix mhlo.dynamic_reshape lowering to Flow dialect

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
The previously generated code discarded const qualifiers.
> Don't emit const qualifier

- iree/compiler/Dialect/Stream/IR/StreamOps.td
- iree/compiler/Dialect/Stream/Transforms/AnnotateDispatchArguments.cpp
- iree/compiler/Dialect/Stream/Transforms/test/annotate_dispatch_arguments.mlir
- iree/compiler/Dialect/Util/Analysis/Explorer.cpp
- iree/compiler/Dialect/Util/Analysis/Explorer.h
This allows the potential value set analysis to integrate initial
global values and properly derive alignment from resource offsets that
may vary at runtime.
Fixes #8162.
> Adding support for globals in AnnotateDispatchArguments.

- iree/compiler/Dialect/HAL/Analysis/BindingLayout.cpp
- iree/compiler/Dialect/Stream/IR/StreamOps.cpp
- iree/compiler/Dialect/Stream/IR/StreamOps.td
- iree/compiler/Dialect/Stream/Transforms/AnnotateDispatchArguments.cpp
- iree/compiler/Dialect/Stream/Transforms/BUILD
- iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/DumpStatistics.cpp
- iree/compiler/Dialect/Stream/Transforms/FoldUniformOperands.cpp
- iree/compiler/Dialect/Stream/Transforms/FuseDispatchBindings.cpp
- iree/compiler/Dialect/Stream/Transforms/PassDetail.h
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.h
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/SpecializeDispatches.cpp
- iree/compiler/Dialect/Stream/Transforms/test/BUILD
- iree/compiler/Dialect/Stream/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/Stream/Transforms/test/dump_statistics.mlir
- iree/compiler/Translation/IREEVM.cpp
- iree/compiler/Translation/IREEVM.h
- llvm-external-projects/iree-compiler-api/lib/CAPI/Compiler.cpp
This dumps scheduling information derived from the program after the full
stream dialect transformation pipeline has run. This is before HAL target
backends have had a chance to translate executables and still contains
the post-flow ops (linalg, etc).
Use in iree-translate with
`-iree-scheduling-dump-statistics-format=csv` (or `pretty`, TBD)
By default things go to stderr but can be directed to a file with
`-iree-scheduling-dump-statistics-file=path` for easier automation.
Use in iree-opt with
`-pass-pipeline=iree-stream-transformation-pipeline{dump-statistics-format=csv}`.
The pretty output is designed with leading `//` so that it can be put into
the MLIR output and still have a valid file (using `...-file=-`).
Many parts still TODO but the most requested information (dispatches,
copies, …
> Adding `-iree-scheduling-dump-statistics-*` flag and pass.

- CMakeLists.txt
- build_tools/bazel/cc_binary_benchmark.bzl
- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- build_tools/cmake/iree_cc_binary_benchmark.cmake
- iree/base/internal/BUILD
- iree/base/internal/CMakeLists.txt
- iree/builtins/device/tools/BUILD
- iree/builtins/device/tools/CMakeLists.txt
- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
- iree/hal/utils/BUILD
- iree/hal/utils/CMakeLists.txt
- iree/vm/BUILD
- iree/vm/CMakeLists.txt
The same justification as
https://github.com/google/iree/commit/48896123d, but this time I went
to the extra trouble of creating a rule, so hopefully that will reduce
the overhead and people will use this for new benchmarks. I frequently
run all tests, so these really slow ones are painful.
> Avoid running long benchmarks as tests

- docs/developers/get_started/getting_started_riscv_cmake.md
- docs/website/docs/building-from-source/riscv.md
Reflect https://github.com/llvm/llvm-project/commit/3cf15af2 and update
binutils-gdb source path.
> Update RISC-V doc

- experimental/rocm/rocm_allocator.c
- iree/hal/allocator.c
- iree/hal/allocator.h
- iree/hal/allocator_heap.c
- iree/hal/cuda/cuda_allocator.c
- iree/hal/vulkan/vma_allocator.cc
These are just stubs on all but the heap allocator today.
This will allow us to plumb import/export higher up into frontends
and concurrently start implementing it in backends.
Progress on #3379.
> Adding iree_hal_allocator_t APIs for buffer import/export.

- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/EmbeddedLinkerTool.cpp
Still not fully diagnosed but starting with https://github.com/llvm/llvm-project/commit/83d59e05b201760e3f364ff6316301d347cbad95 the same lld passed the same inputs and flags will succeed on clang/linux and fail on msvc/win with:
```
lld: error: duplicate symbol: iree_hal_executable_library_query
>>> defined at _dynamic_tensor_dispatch_0
>>>            ..\iree-tmp\linking\_dynamic_tensor_dispatch_0-79113a.o:(iree_hal_executable_library_query)
>>> defined at _dynamic_tensor_dispatch_0
>>>            ..\iree-tmp\linking\_dynamic_tensor_dispatch_0-79113a.o:(.text.iree_hal_executable_library_query+0x0)
```
This may be undefined behavior or reliance on implementation-specific CRT behavior and needs to be triaged with the lld team.
> Work around LLD breakage by allowing multiple symbol defs.

- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__reduce_all.run
- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/TypePropagationPass.cpp
- iree/compiler/Codegen/Common/test/BUILD
- iree/compiler/Codegen/Common/test/CMakeLists.txt
- iree/compiler/Codegen/Common/test/type_propagation.mlir
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
- iree/compiler/Codegen/SPIRV/Passes.cpp
- iree/compiler/Dialect/Modules/VMVX/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- iree/compiler/Dialect/Stream/Transforms/test/encode_device_tensors.mlir
With PR #8155, the buffer for `tensor` with unsupported element types
(like `i1`, `i2`, etc.) are converted to use a supported element type
through widening (and truncation if needed in future). This introduces
`arith.trunci` and `arith.extui` operations to convert back and forth
from the program representation in its original form. Propagate the
use of supported element type for all `tensor` operations to ensure
that the no load/stores of unsupported element types are used.
> Add a pass to propagate unsupported element type conversion.

- CMakeLists.txt
- experimental/sample_web_static/CMakeLists.txt
- experimental/sample_web_static/README.md
- experimental/sample_web_static/build_static_emscripten_demo.sh
- experimental/sample_web_static/device_multithreaded.c
- experimental/sample_web_static/device_sync.c
- experimental/sample_web_static/index.html
- experimental/sample_web_static/local_server.py
- experimental/sample_web_static/main.c
This is a proof of concept for deploying to the web using IREE. See the README for more details.
Rough structure:
* `build_static_emscripten_demo.sh` compiles an MNIST sample model targeting WebAssembly (`--iree-hal-target-backends=llvm --iree-llvm-target-triple=wasm32-unknown-unknown -iree-llvm-link-static`), compiles the runtime using Emscripten, then starts a local webserver for the provided index.html
* Parts of this could be folded into the CMakeLists.txt, but I think this split is easier to follow
* `index.html` has the web demo code (`<canvas>` for drawing, javascript for interfacing between the UI and the Wasm module)
* `main.c` has the native demo code (using IREE's high level `runtime/` API)
* `device_sync.c` and `device_multithreaded.c` implement CPU devices using the static …
> Add an experimental static library web demo using Emscripten.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
The sandbox approach is designed for the cases that element types match.
There are timing issues in e2e_matmul_direct test suites compilation.
Because some vector.broadcast ops will be created in some cases. This is
not the area that we're targeting in sandbox codegen driver at this
moment, so we limit the use case of sandbox codegen driver based
approach.
> Fallback matmul codegen to TileFuseAndVectorize when types not match.

- .github/workflows/advance_upstream_forks.yml
This keeps all the things in one place, rather than having to go to the
separate fork repository to manage the action. It also will allow us to
completely disable actions on the fork, which is probably good.
We were seeing some permissions issues with this running over in the
fork because it doesn't want to allow the action to update the workflow
files, and we think maybe disabling actions for that repo entirely will
remove that restriction (or maybe not).
> Move workflow for advancing iree-llvm-fork to the IREE repo

- iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- iree/compiler/InputConversion/MHLO/test/mhlo_to_mhlo_preprocessing.mlir
LLVM patch adds custom support for the math log1p and expm1 operations for the SPIRV backends. Remove the MHLO
to MHLO lowerings as they are no longer needed.
https://reviews.llvm.org/D118081
> Remove custom decomposition for MHLO decomposition lowering

- iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- iree/compiler/InputConversion/MHLO/MHLOToLinalgOnTensors.cpp
- iree/compiler/InputConversion/MHLO/test/convert_mhlo_to_linalg_ext.mlir
Unsigned integers result in conversion failures during the mhlo.sort
conversion. Updated the type-convert to handle unsigned/signed for
additional cases.
They are cleaned up during the final conversion to linalg.
> Updated linalg_ext sort conversion for unsigned integers

- iree/compiler/Codegen/Common/BufferizationAnalysis.cpp
- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/Common/test/linalg_bufferize.mlir
Current bufferization heuristics for handling destructive updates
relies on loops. This can be decoupled to look at just the uses of the
`dest` of `tensor.insert_slice`/`vector.transfer_write` operations.
> Decouple destructive update handling from loops.

- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/base/api.h
- iree/base/internal/BUILD
- iree/base/internal/CMakeLists.txt
- iree/base/internal/wait_handle.c
- iree/base/internal/wait_handle.h
- iree/base/internal/wait_handle_impl.h
- iree/base/internal/wait_handle_null.c
- iree/base/internal/wait_handle_posix.c
- iree/base/internal/wait_handle_posix.h
- iree/base/internal/wait_handle_test.cc
- iree/base/internal/wait_handle_win32.c
- iree/base/wait_source.c
- iree/base/wait_source.h
Wait sources add an abstraction between the platform primitives such
that core code can pass them around. Wait sources can be implemented
with the platform wait handles or with custom types (such as HAL
semaphores) and enable deferred handle creation. In this way we can
pass around the wait sources and only if/when the consumer of them
wants to perform a system wait will we need to materialize the wait
handle.
This also works to move more out from behind the IREE_ENABLE_THREADING
flag: wait handles are not related to threading.
> Adding iree_wait_source_t and cleaning up iree_wait_handle_t.

- iree/compiler/Translation/test/BUILD
- iree/compiler/Translation/test/CMakeLists.txt
- iree/compiler/Translation/test/streams.mlir
This lets us verify that we can handle ingesting them and acts as an
example for someone trying to more directly see the execution model.
In the future as we move tiling from flow to the codegen backends this
will be simplified and changed to use the public iree dialect instead.
> Adding some sample flow/stream uses.

- iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- iree/compiler/InputConversion/MHLO/test/mhlo_to_mhlo_preprocessing.mlir
Adding reshapes to indices and updates allows the default mhlo-to-linalg
lowering to handle the rank-0 use.
> Add mhlo-to-mhlo decomposition of rank-0 mhlo.scatter

- .github/CODEOWNERS
Adds just a bare bones CODEOWNERS file with just owner for Codegen
directory. To be filled in by people who want to own different parts
of the codebase.
> Add CODEOWNERS to IREE repository.

- .github/workflows/build_package.yml
- build_tools/github_actions/build_dist.py
- llvm-external-projects/iree-compiler-api/setup.py
* Release docker container has CUDA dev packages installed on it.
* Main releases platform detect and enable CUDA integration.
* Compiler wheel uses an environment variable that is set by the release pipeline.
> Enable CUDA release builds.

- .github/workflows/build_package.yml
- llvm-external-projects/iree-compiler-api/pyproject.toml
* The Windows and MacOS compiler builds have been failing on a Python detection race. CMake has gotten less buggy in this area over time so in lieu of root causing, just bumping to current as a first step.
* Also rolls back the pip version hack now that the official version has the patch we need.
* Marks Windows/MacOS builds experimental so that they do not block Linux builds and we can get a clean release out tomorrow (fingers crossed).
> Bump CMake version to 3.22.2 to build compiler wheels.

- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/function_test.py
* This was caught when attempting to explicitly use DeviceArrays, since they are setup by default to raise an exception on an implicit transfer to host.
* Added a test to verify.
> Remove accidental device->host transfer on function dispatch.

- CMakeLists.txt
* Falls back to the simplest possible thing so long as CUDAToolkit_ROOT is specified.
* This seems to help with situations where we have installed a subset of SDK packages.
> Further escalate the CUDA detection arms race.

- iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp
- iree/compiler/Utils/CustomKernelsTargetInfo.h
This makes MMTCustomKernelPattern generic in what kernel it's
generating, in a way that should suffice for the next few kernels that
we need to add (first motivation: float32/aarch64).
MMTCustomKernelPattern now takes the kernel-specific details from a
MMTKernel struct, including the asm code and information about the shape
and data types. The inline asm constraints string becomes
auto-generated.
All this automation had the effect of making it "too magical" for the
inline asm to continue to refer to its register operands by fixed
indices like "$12" as the llvm inline asm syntax allows, so we introduce
a pre-processing step allowing us to write kernels using placeholders
like "$(lhs:0)" for the 0-th register of the LHS, and that gets
"allocated" as the pre-processed code and the …
> Generalize the asm kernel pattern.

- bindings/python/iree/runtime/CMakeLists.txt
- bindings/python/iree/runtime/__init__.py
- bindings/python/iree/runtime/flags.py
- bindings/python/iree/runtime/flags_test.py
- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/initialize_module.cc
* Exposes one python flag `iree.runtime.flags.FUNCTION_INPUT_VALIDATION` (default True), which can be used to disable some expensive validation checks.
* Adds `iree.runtime.flags.parse_flags("--flag1", "--flag2")` to set native flags from Python.
> Add python-only and native flag parsing to the Python API.

- bindings/python/iree/runtime/CMakeLists.txt
- build_tools/cmake/iree_python.cmake
- iree/base/tracing.cc
- iree/base/tracing.h
* I've generally found that hooking the operator new/delete in arbitrary C++ programs does not produce balanced allocations that make Tracy happy (ahem, LLVM).
* Something about pybind code exhibits these issues, so disable the C++ hooking there.
* While in there, brings this up to C++11 compliance by handling both the throwing and non-throwing overloads properly (this was failing to compile if exceptions were enabled).
* I'm not an expert on this -- just did some digging and trying to fix the issue I see.
Fixes #8263
> Disable C++ allocation tracing for Python bindings.

- experimental/sample_web_static/build_static_emscripten_demo.sh
- experimental/sample_web_static/index.html
- experimental/sample_web_static/iree_api.js
- experimental/sample_web_static/iree_worker.js
New structure:
* `iree_api.js` exposes a Promise-based API to the hosting application in `index.html`
* `iree_api.js` creates a worker running `iree_worker.js`, which includes Emscripten's JS code and instantiates the WebAssembly module
* messages are passed back and forth between `iree_api.js` and `iree_worker.js` internally
This is still running synchronously on the worker for now, but sets us up for running multiple concurrent invocations in the future.
This _does_ complicate multithreading a bit, since Emscripten (which we're using to bootstrap) makes some sketchy assumptions about what code is/isn't running in workers and how messages are sent/received. The hope is that once we implement our own threading (instead of using Emscripten's pthreads implementation) that won't be an issue. …
> Refactor web sample into a Promise-based API using a Web Worker.

- iree/tools/iree_translate_lib.cc
When no translation is set this would have resulted in nullptr
dereference.
> Avoid null dereference for missing translation

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
In the translation of `vm.return` ops we need to move the ref operands into the result arguments of the function. As these two sets may alias we first move the operands into temporaries.
> [EmitC] Save refs into temporaries before returning

- iree/base/internal/synchronization.c
- iree/base/internal/synchronization.h
- iree/base/internal/synchronization_test.cc
- iree/base/internal/threading_pthreads.c
- iree/base/internal/threading_test.cc
- iree/base/time.c
- iree/hal/local/sync_semaphore.c
- iree/task/poller.c
- iree/task/scope.c
- iree/task/worker.c
Reverts google/iree#8278
Causes flake:
```
[ RUN      ] TaskBarrierTest.IssueJoinFailure
../iree/task/task_test_barrier.cc:220: Failure
Value of: SubmitAndWaitIdle(&submission, &task_d.header)
Expected: error code OK
Actual: 0x4, whose error code is DEADLINE_EXCEEDED: DEADLINE_EXCEEDED
```
> Revert "Adding support for timeouts on iree_notification_t."

- iree/compiler/Dialect/HAL/Target/LLVM/internal/WasmLinkerTool.cpp
Fixes https://github.com/google/iree/issues/4019 (the compiler backend is stable enough for demos and this seems to be all that is needed to enable SIMD in our codegen).
> Add note about how to use Wasm SIMD.

- iree/base/internal/synchronization.c
- iree/base/internal/synchronization.h
- iree/base/internal/synchronization_test.cc
- iree/base/internal/threading_pthreads.c
- iree/base/internal/threading_test.cc
- iree/base/time.c
- iree/hal/local/sync_semaphore.c
- iree/task/list.c
- iree/task/poller.c
- iree/task/scope.c
- iree/task/scope.h
- iree/task/scope_test.cc
- iree/task/task.c
- iree/task/task_test_barrier.cc
- iree/task/task_test_call.cc
- iree/task/task_test_dispatch.cc
- iree/task/task_test_fence.cc
- iree/task/task_test_nop.cc
- iree/task/task_test_wait.cc
- iree/task/worker.c
Relanding #8278 reverted in #8280.
After some thorough stress testing and tracing I believe the root issue has been fixed (potential unordered task cleanup).
> Adding support for timeouts on iree_notification_t + fixes.

- iree/base/internal/BUILD
- iree/base/internal/CMakeLists.txt
- iree/base/internal/synchronization.h
- iree/base/internal/wait_handle_impl.h
- iree/base/internal/wait_handle_inproc.c
- iree/base/internal/wait_handle_posix.c
- iree/base/internal/wait_handle_posix.h
- iree/base/internal/wait_handle_win32.c
- iree/base/wait_source.h
This allows for bare-metal/embedded/tiny/wasm platform targets to still
use wait handles with multi-wait capabilities even with no system support.
Configurations that do not use any external waits and have very low
utilization could use this to reduce overheads associated with
platform event creation.
> Adding an in-process wait handle implementation.

- iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/LLVMGPU/test/BUILD
- iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/test/illegal_configuration.mlir
- iree/compiler/Codegen/Passes.cpp
- iree/compiler/Codegen/Passes.h
Implementation of a verifier for the GPUMatmulSimtPassPipeline. Currently checks for the workgroupsize <=1024. Exposes verifier to both the `GPULowerExecutableTarget` as well as external verification.
> Implementation of the GPUMatmulSimtPassPipeline verifier

- build_tools/cmake/iree_copts.cmake
- experimental/sample_web_static/CMakeLists.txt
- experimental/sample_web_static/README.md
- experimental/sample_web_static/build_static_emscripten_demo.sh
- experimental/sample_web_static/device_multithreaded.c
- experimental/sample_web_static/index.html
- experimental/sample_web_static/iree_api.js
- experimental/sample_web_static/iree_worker.js
Multithreading is using IREE's task system, which creates one thread as a "poller" and multiple worker threads (hardcoded to 4, but could use `emscripten_num_logical_cores()`/`navigator.hardwareConcurrency`):
I've also started a custom implementation of threading using Web Workers without Emscripten's pthreads, since configuring Emscripten for our usage was tricky. By moving away from Emscripten we'll also be able to cut down on binary size, startup time, and build complexity. Well, that's the hope, anyways. This works for now :D
Tested on Chrome 98, Windows 10 desktop. SharedArrayBuffer and SIMD may require feature flags on other/older browsers.
> Enable multithreading and SIMD in static web demo.

- build_tools/cmake/build_android.sh
- build_tools/cmake/build_android_benchmark.sh
- build_tools/cmake/build_host_install.sh
- build_tools/cmake/build_riscv.sh
- build_tools/cmake/build_runtime.sh
- build_tools/cmake/build_runtime_emscripten.sh
- build_tools/cmake/build_runtime_small.sh
- build_tools/cmake/build_tracing.sh
- build_tools/cmake/rebuild.sh
- build_tools/cmake/test.sh
- build_tools/kokoro/gcp_ubuntu/cmake/android/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build.sh
- build_tools/third_party/swiftshader/build_vk_swiftshader.sh
- experimental/sample_web_static/build_static_emscripten_demo.sh
- iree/samples/dynamic_shapes/test.sh
- iree/samples/variables_and_state/test.sh
These are primarily used in CI, where it's useful to learn what all the
failures are up front. We already have the `--keep-going` option set in
the Bazel build.
> Add 'keep going' option to CMake CI builds

- experimental/sample_web_static/build_static_emscripten_demo.sh
The regex I used in https://github.com/google/iree/pull/8302 neglected
the case of line continuations within the invocation of CMake (which
tbf, were only present in this experimental script). Reverting rather
than moving the arg to the right place because we agreed it's not
really useful in this non-CI script.
Partial revert of https://github.com/google/iree/commit/0f80995367c3
> Revert malformed change to emscripten demo script

- build_tools/cmake/iree_check_test.cmake
- iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp
- iree/compiler/Codegen/LLVMCPU/test/vector_contract_to_arm_asm.mlir
- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
- iree/compiler/Dialect/Flow/Transforms/test/matmul_to_mmt4d.mlir
- iree/compiler/Utils/CustomKernelsTargetInfo.cpp
- iree/compiler/Utils/CustomKernelsTargetInfo.h
* matrix-matrix and matrix-vector kernels
* f32, i8-without-dotprod, and i8-with-dotprod
* automatic transformation of vector-times-matrix into matrix-times-vector so it reuses the same kernels
* bye bye power-of-two arithmetic, basically reworked the Kernel struct so we're doing only muls not divs.
> More asm kernels for vector.contract on ARM

- bindings/python/iree/runtime/CMakeLists.txt
- bindings/python/iree/runtime/binding.h
- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/function_test.py
- bindings/python/iree/runtime/hal.cc
- bindings/python/iree/runtime/initialize_module.cc
- bindings/python/iree/runtime/invoke.cc
- bindings/python/iree/runtime/invoke.h
- bindings/python/iree/runtime/vm.cc
- bindings/python/iree/runtime/vm.h
* This is a first step towards implementing all hot path code in C++.
* With the Python code, I didn't have great performance baselines, but I estimate it was taking ~80-100us to do argument packing for a 3 item call. This patch:
* Average of 3us total for argument packing for this case.
* Average of 300ns per DeviceArray.
* Both numbers are for invocations with static reflection data (which is also now layered for easier access to it can be added at runtime if desired to make things faster). The dynamic case does a bit more work.
* Once more of this is ported to C++, we can eliminate a lot more overhead by intercepting the tp_call protocol directly (vs doing list/dict manipulation).
* This also fixes a critical bug where the Python "DEVICE_VISIBLE" enumeration value was actually set to …
> Rewrite Python function argument packing in C++.

- iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
This is a step forward to further consolidate and unify how
MemRef generated from HAL subspan ops are converted.
Previously we already flatten 0-D and n-D (n > 1) MemRefs
into 1-D of dynamic size. This commit extends it to also
convert 1-D static sized MemRefs. After this effectively
all MemRefs from subspan ops are treated the same.
It matches IREE's view of buffers---all are just views of
some underlying unknown sized 1-D data array. It also
helps to perform further transformations to eventually
turn multiple subspan ops bound to the same descriptor
to one.
This helps to avoid generating aliased arrays in SPIR-V like
```
spv.GlobalVariable @... bind(0, 0) {aliased}
: !spv.ptr<!spv.struct<(!spv.array<8 x f32, stride=4> [0])>, StorageBuffer>
spv.GlobalVariable @... bind(0, 0) {aliased}
: …
```
> Convert 1-D static subspan to 1-D dynamic sized subspan

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/illegal_configuration.mlir
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/test/e2e/regression/lowering_config.mlir
We tried to handle padding issue and came out with a workaround which
might generates redundant one-trip loops. After prototype more, we found
that there are non-trivial amount of work, see
https://github.com/google/iree/issues/8228.
The PR disable padding options and make it have same behaviors as
sandbox.
> Apply tiling on parallel dims and reduction dims separately.

- CMakeLists.txt
I ran into an SDK install today which puts the libdevice files in a
non-standard place and realized we were not able to override.
> Fix IREE_CUDA_LIBDEVICE_PATH to work even when SDK is found.

- .github/CODEOWNERS
It turns out that getting added as a reviewer every time someone
updates a test or the LLVM submodule is annoying.
> Drop some frequently-changed general directories from CODEOWNERS

- iree/test/e2e/xla_ops/scatter.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/iree_linalgext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/invalid.mlir
Scatter can be performed by now allowing additional dimensions on the update
tensor. This supports the existing tiling method but requires slight
modifications to validators and the scalar computation.
> Redo linalg_ext.scatter to support explicitly defined index update sizes

- iree/compiler/Codegen/LLVMGPU/ConvertToNVVM.cpp
- iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp
populateLowerHALInterfaceOp is a convertion pattern so it needs a type
converter.
> [LLVMGPU] Fix asan failure in convertToNVVM/convertToROCDL

- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
There are redundant memcpy (with linalg.generic form) ops created, which
can be deleted by canonicalizer. We have to run canonicalization patterns again
because the memrefs are unified in CSE pass, so we can truely remove
redundant memcpy.
Fixes https://github.com/google/iree/issues/8283
> Delete redundant memcpy ops right after bufferization.

- iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
Just trying to see if we still need this flag and if this still cause perf regressions.
> Turn fusion of generic op with reduction producer on by default

- .github/CODEOWNERS
Git considers these files, not directories. Note that matches happen on
an entire path segment, so codeowners would still be set for a
hypothetical third_party/tensorflow_foo submodule.
> Fix CODEOWNERS patterns for submodules

- integrations/tensorflow/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- integrations/tensorflow/iree-dialects/test/iree_linalgext/convert_to_loops.mlir
- integrations/tensorflow/iree-dialects/test/iree_linalgext/invalid.mlir
- integrations/tensorflow/iree-dialects/test/iree_linalgext/roundtrip.mlir
- integrations/tensorflow/iree-dialects/test/iree_linalgext/tiling.mlir
- iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- iree/compiler/Codegen/SPIRV/test/tile_and_distribute_scatter.mlir
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- iree/compiler/InputConversion/MHLO/test/convert_mhlo_to_linalg_ext.mlir
- iree/test/e2e/xla_ops/scatter.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
- llvm-external-projects/iree-dialects/test/iree_linalgext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/invalid.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/roundtrip.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/tiling.mlir
There are cases that the op may update the same indices multiple times.
In this context, we can not parallize updates. Instead, we have to
execute them sequentially. Adding a boolean attribute to control the
behavior.
This also adds a test to DispatchLinalgOnTensors to make sure repeated indices cases won't get tiled and distributed.
Fixes https://github.com/google/iree/issues/8318
> Extend linalg_ext.scatter op semantic to carry unique_indices attribute.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
Instead of defining pointer types via opaque attributes, we now use the
emitc pointer type and get the type attribute from the type.
> Replace opaque attributes with type attributes

- integrations/tensorflow/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- integrations/tensorflow/iree-dialects/test/iree_linalgext/convert_to_loops.mlir
- integrations/tensorflow/iree-dialects/test/iree_linalgext/invalid.mlir
- integrations/tensorflow/iree-dialects/test/iree_linalgext/roundtrip.mlir
- integrations/tensorflow/iree-dialects/test/iree_linalgext/tiling.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/iree_linalgext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/invalid.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/roundtrip.mlir
- llvm-external-projects/iree-dialects/test/iree_linalgext/tiling.mlir
The attribute was not required when the rank of operand is one. Forcing
the op to require the attribute to have less confusion.
> Update linalg_ext.sort op to require the dimension attribute.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
`iree_vm_ref` pointer types will be emitted via `!emitc.ptr` types in a
follow up. This was the reason for #8382 was failing.
> Do not yet emit VM ref types via emitc.ptr type

- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- build_tools/cmake/iree_cc_test.cmake
- build_tools/cmake/iree_hal_cts_test_suite.cmake
- iree/hal/cuda/cts/CMakeLists.txt
* `iree_hal_cts_test_suite()` now supports a `VARIANT_SUFFIX`, which creates a new test suite for the same `DRIVER_NAME`, but with the flexibility to change the other arguments (`DRIVER_REGISTRATION_FN`, `COMPILER_TARGET_BACKEND`, etc.)
* This also adds an `ARGS` argument, which contains a list of strings to pass to any underlying `cc_test`s when run under `ctest`
Together, these features are used to create a `cuda_graph` variant test suite that sets the `--cuda_use_streams=0` CLI flag.
Note: this can create duplicate test binaries and the flag passing is only enforced by CTest, so running the tests directly (e.g. under a debugger) won't pass the flags :/
> Add HAL CTS 'variants' support and cuda_graph CTS test suite.

- iree/hal/vulkan/vma_allocator.cc
- iree/hal/vulkan/vma_allocator.h
- iree/hal/vulkan/vulkan_device.cc
VmaRecordSettings (and the whole Record&Replay feature, which we did not use, was deleted).
> Update third_party/vulkan_memory_allocator to latest.

- iree/compiler/Codegen/LLVMGPU/BUILD
- iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/LLVMGPU/Verifiers.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/LLVMGPU/test/illegal_configuration.mlir
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- iree/compiler/Codegen/Passes.h
Implements verifiers for the `LLVMGPUMatmulSimt` and `LLVMGPUMatmulTensorCore` pipelines with tests. 
Adds `Verifiers.cpp` to the `LLVMGPU` module for more thorough  verification.
> Implementation of Verifiers.cpp for linalg.matmul.

- iree/base/BUILD
- iree/base/CMakeLists.txt
- iree/base/api.h
- iree/base/internal/synchronization_test.cc
- iree/base/internal/wait_handle.c
- iree/base/internal/wait_handle.h
- iree/base/internal/wait_handle_inproc.c
- iree/base/internal/wait_handle_poll.c
- iree/base/internal/wait_handle_test.cc
- iree/base/internal/wait_handle_win32.c
- iree/base/loop.c
- iree/base/loop.h
- iree/base/loop_inline.c
- iree/base/loop_inline.h
- iree/base/loop_inline_test.cc
- iree/base/loop_sync.c
- iree/base/loop_sync.h
- iree/base/loop_sync_test.cc
- iree/base/loop_test.h
- iree/base/time.h
- iree/hal/cts/semaphore_test.h
- iree/task/poller.c
This ioctl-like interface exposes an event loop that can run deferred tasks and perform aggregated waits: it's effectively the browser event loop (call = setImmediate, wait_until = setTimeout, etc) as a virtual interface. The API has some requirements such as mandatory forward progress that allow for a variety of implementations including those not owned by IREE (hosting application job systems, the browser event loop when running on the web, an RTOS scheduler, etc).
The intent is that each VM context will be assigned a loop where all invocations against the context run cooperatively. Multiple contexts may share the same underlying loop and run their invocations concurrently while still preserving proper ordering within their own scopes. All waits the context wants to perform - such as …
> Adding iree_loop_t and the basic inline and synchronous implementations.

- iree/compiler/Bindings/Native/Transforms/WrapEntryPoints.cpp
- iree/compiler/Bindings/Native/Transforms/test/wrap_entry_points.mlir
> Fixup symbol names when wrapping exported functions.

- scripts/lint.sh
Because this script first checks that there are no uncommitted changes,
this line was actually doing nothing as it was comparing against the
default HEAD.
> Make lint script run clang-format against main

- iree/samples/static_library/static_library_demo.c
Missed in https://github.com/google/iree/pull/8389 since this demo was disabled (re-enabled in https://github.com/google/iree/pull/8382).
> Fix allocator use in static library demo.

- build_tools/bazel/iree_trace_runner_test.bzl
- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_trace_runner_test.cmake
- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/test/e2e/regression/BUILD
- iree/test/e2e/regression/CMakeLists.txt
Per discussion with Ben, this is a hack, but it's a contained hack
where the necessary target information is just given directly to this
pass. The necessity for this information is a blocker on enabling MMT4D
as currently constructed by default. This does make it much easier to
test and benchmark though. Notably, this flag is not exposed to users
at the Python level.
> Add flag for enabling MMT4D path in iree-translate

- iree/base/tracing.h
I thought this was just a pybind problem, but I've seen instability in
the traces in other C++ programs. We aren't getting value from this
as-is and it is better removed.
> Remove C++ allocation hooks from tracing.

- benchmarks/TFLite/CMakeLists.txt
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
The reasons to not do this by default have been lost to time and it
provides a sizable speedup on single-threaded benchmarks.
> Turn on LLVM loop unrolling by default

- iree/compiler/Codegen/SPIRV/Passes.cpp
In SPIR-V, resources are represented as global variables that
are bound to certain descriptor. SPIR-V requires those global
variables to be declared as aliased if multiple ones are bound
to the same slot. Such aliased decorations can cause issues
for transcompilers like SPIRV-Cross when converting to source
shading languages like MSL. 
Running this pass helps to remove aliased resources and
unblock running models on Apple devices via Vulkan.
> [spirv] Run pass to unify aliased resources

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/type_conversion.mlir
> Use `emitc.ptr` for `iree_vm_ref_t*` type

- iree/task/task_test_wait.cc
It was possible for the event to wake the parent thread and block before
the flag was set.
> Fixing task tests to signal after setting the test flag.

- iree/compiler/Dialect/Flow/Conversion/TensorToFlow/ConvertTensorToFlow.cpp
This pass has been modified to handle the cases where `tensor.cast`
op is not converted to `flow.tensor.reshape` even after the
formation of dispatch regions.
> Modify createConvertToFlowAfterDispatchFormation Pass

- iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- iree/compiler/InputConversion/MHLO/Passes.cpp
- iree/compiler/InputConversion/MHLO/test/mhlo_to_mhlo_preprocessing.mlir
Multiplication of cast from bool is a common method for conditional
subtraction. Unfortunately it is expect that mul(inf, 0.0) -> 0.0, which is
not conformant with the IEEE floating point standard.
Added a special case to search for this substitution and perform a select
instead. It won't catch all cases but it should help track them down.
> Add special case of mul(float(bool), float)

- iree/base/status.c
- iree/compiler/Codegen/Common/RemoveTrivialLoops.cpp
- iree/compiler/Codegen/Interfaces/ProcessorOpInterfaces.cpp
- iree/hal/buffer.c
- iree/hal/command_buffer_validation.c
- iree/runtime/demo/BUILD
- iree/runtime/demo/CMakeLists.txt
- iree/vm/list.c
- iree/vm/stack.c
- iree/vm/stack.h
Minor tweaks found while digging into binary sizes with SizeBench.
> Gardening binary size/memory consumption 🎍.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCTypeConverter.cpp
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/const_ops.mlir
- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/type_conversion.mlir
- iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- iree/compiler/Dialect/VM/Target/C/TranslateToCpp.cpp
- iree/compiler/Dialect/VM/Target/C/test/control_flow.mlir
Shrinks the `static_library_demo_c`, built in release mode, by 720 bytes. The generated header `simple_mul_emitc.h` is cropped from 3858 to 3607 lines.
Supersedes #8336.
> Use `emitc.variable` and run canonicalizer

- integrations/tensorflow/WORKSPACE
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRPasses.cpp
* Reset third_party/llvm-project: ba54ebeb5eba0f63de8ce2d73a85e9bf508008f6 (2022-03-01 20:55:28 +0800): [clang-tidy] Fix `readability-const-return-type` for pure virtual function.
* Update mlir-hlo and TensorFlow to match the LLVM commit
* Delete call to llvm::AddressSanitizerPass: this pass was removed in upstream as llvm/llvm-project@b7fd30e; the functionality was already incorporated into the module pass.
> Integrate llvm-project at ba54ebeb5eba0f63de8ce2d73a85e9bf508008f6

- experimental/web/sample_dynamic/CMakeLists.txt
- experimental/web/sample_dynamic/README.md
- experimental/web/sample_dynamic/build_sample.sh
- experimental/web/sample_dynamic/index.html
- experimental/web/sample_dynamic/iree_api.js
- experimental/web/sample_dynamic/iree_worker.js
- experimental/web/sample_dynamic/main.c
Live demo: https://scotttodd.github.io/iree-llvm-sandbox/web-tools/iree-dynamic-sample/
The dynamic web sample now has a UI and supports a few different ways of loading IREE programs and specifying functions along with their arguments.
Features:
* Program path, function name, and function arguments are encoded into URL query parameters (e.g. `index.html?program=simple_abs.vmfb&function=abs&arguments=f32%3D-1.23`), for easy local iteration and settings sharing
* Drag-and-drop .vmfb files from your local machine to load them, see a bit of information about them in the console, and test calling functions on them
* Click between a few sample compiled programs with preselected inputs to try the page out without compiling on your own
Future work / other ideas:
* Populate list of function names …
> Build out dynamic web sample to behave like iree-run-module.

- iree/samples/vulkan/vulkan_inference_gui.cc
This should still be moved out of the core repo sometime soon (https://github.com/google/iree/issues/8011)
> Fix vulkan_inference_gui allocate_buffer usage.

- experimental/web/sample_dynamic/README.md
- experimental/web/sample_dynamic/build_sample.sh
- experimental/web/sample_dynamic/index.html
- experimental/web/sample_dynamic/iree_api.js
- experimental/web/sample_static/build_sample.sh
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.h
One less sharp edge to worry about when using Wasm :D
> Force embedded ELF linking off when targeting WebAssembly.

- build_tools/buildkite/cmake/build_configurations.yml
- build_tools/buildkite/samples.yml
Docs: https://buildkite.com/docs/pipelines/notifications
Referenced
https://github.com/google/iree/blob/6348e9e16b7fbc5ea8c8287efca31828504e0fe5/build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml#L53-L55
and
https://github.com/google/iree/blob/6348e9e16b7fbc5ea8c8287efca31828504e0fe5/build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml#L74-L76
(#testinprod)
> Add postsubmit failure alerts to a few buildkite pipelines.

- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
This prevent skipping tiling for cases where the workgroup tile size is
smaller than workgroup size.
> [CUDA] Fix thread tile size calculation for unaligned cases

- build_tools/cmake/build_android.sh
- build_tools/kokoro/gcp_ubuntu/cmake/android/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build.sh
Should fix `iree/gcp_ubuntu/cmake/linux/x86-turing/main[default]` and `iree/iree-android-arm64-v8a` by adding `"$CMAKE_BIN" --build . --target iree-test-deps -- -k 0` steps to each.
> Fix missing test deps after https://github.com/google/iree/pull/8423

- bindings/tflite/interpreter.c
- bindings/tflite/model.c
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
- iree/base/internal/file_io_test.cc
- iree/modules/check/check_test.cc
This gives us clean test runs with ASan. There were failures in the
following tests (all were memory leaks reported by LSan, which is folded
into ASan).
```
10 - iree/base/internal/file_io_test (Failed)
53 - iree/modules/check/check_test (Failed)
629 - bindings/tflite/smoke_test (Failed)
```
There was one leak in a non-error path, `TfLiteInterpreter` leaked its `driver`.
There was also one leak in an error path: when the model is invalid, `TfLiteModelCreate` returned `NULL` but still leaked the model it had already internally allocated.
There were additional test-only leaks.
Fixes some of https://github.com/google/iree/issues/5715
> Fix ASan test failures on linux/x86/CPU

- build_tools/bazel/iree_trace_runner_test.bzl
- iree/test/e2e/regression/BUILD
- iree/test/e2e/regression/CMakeLists.txt
- iree/test/e2e/regression/generate_e2e_matmul_tests.py
Integrates e2e matmul testing for GPUs; intended to test the compilation verifiers for `LLVMGPUMatmulSimt` and `LLVMGPUMatmulTensorCore` pass pipelines. 
Changes mainly to `generate_e2e_matmul_tests.py`: In order to support GPU testing apart from CPU:
* `ShapesId::GPU_LARGE` option to `--shapes` for gpu shapes
* `--compilation_info` allows to specify the compiling pass pipeline for generated test cases and compilation infos
GPU tests make use of additional compilation info attrs added during generation. These are committed with other tests (`--compilation_info=none`)
> e2e matmul testing for compilation infos on gpu

- iree/compiler/Dialect/Flow/Transforms/ConvertToFlow.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
Reording the passes added before dispatch region formation to do
pass + canonicalization + cse. Also instead of using the pass to fold
`tensor.dim` operations use the patterns directly where `tensor.dim`
could be introduced. That might remove the `tensor.dim` operations to
begin with.
> Cleanup flow pipeline.

- iree/compiler/InputConversion/TOSA/Passes.cpp
This saves one run of canonicalization and it also fixes a performance
regression for PoseNet on Mali GPUs.
> Save one canonicalization pass in TOSA input conversion

- iree/modules/check/check_test.cc
This is a follow-up from PR #8450 where I naively fixed ASan failures by ad-hoc refcount decrements without undertanding the root issue. This fixes the root issue as explained by @benvanik.
closes #8458.
> Fixing check-test leaks (ASan)

- iree/compiler/Dialect/Flow/Transforms/ConvertLinalgTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/ConvertToFlow.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
Motivation: these calls were data races, as pass code runs on multiple
threads concurrently on the same MLIRContext instance. This was reported
by TSan and prevented even completing a build of the tests with TSan.
This just drops those allowUnregisteredDialects calls... I expected that
to cause failures that I would then have to fix by adding dependent
dialects, but I don't see any failure ?! As if these
allowUnregisteredDialects calls were not actually necessary.
There remains one call to allowUnregisteredDialects in
iree/tools/iree_translate_lib.cc
but it is performed on a newly constructed MLIRContext so it's not going
to run afoul of the assertion being added in
https://reviews.llvm.org/D112021 .
> Don't call allowUnregisteredDialects from passes

- iree/hal/cts/allocator_test.h
- iree/hal/cts/buffer_mapping_test.h
- iree/hal/cts/command_buffer_dispatch_test.h
- iree/hal/cts/command_buffer_test.h
- iree/hal/cts/cts_test_base.h
- iree/hal/cts/descriptor_set_layout_test.h
- iree/hal/cts/descriptor_set_test.h
- iree/hal/cts/driver_test.h
- iree/hal/cts/event_test.h
- iree/hal/cts/executable_cache_test.h
- iree/hal/cts/executable_layout_test.h
- iree/hal/cts/semaphore_submission_test.h
- iree/hal/cts/semaphore_test.h
I tried to set up coverage reporting to help guide this work, but gave up after trying a few different versions of gcc/clang and still getting version mismatches between tools with unhelpful error messages >_>
> Expand HAL CTS test coverage and initialize pointers.

- experimental/rocm/native_executable.c
- experimental/rocm/native_executable.h
- experimental/rocm/nop_executable_cache.c
- iree/hal/cts/command_buffer_dispatch_test.h
- iree/hal/cts/executable_cache_test.h
- iree/hal/cuda/native_executable.c
- iree/hal/cuda/native_executable.h
- iree/hal/cuda/nop_executable_cache.c
- iree/hal/executable_cache.c
- iree/hal/executable_cache.h
- iree/hal/local/executable_library_benchmark.c
- iree/hal/local/executable_loader.c
- iree/hal/local/executable_loader.h
- iree/hal/local/loaders/embedded_library_loader.c
- iree/hal/local/loaders/static_library_loader.c
- iree/hal/local/loaders/static_library_loader.h
- iree/hal/local/loaders/system_library_loader.c
- iree/hal/local/loaders/vmvx_module_loader.c
- iree/hal/local/local_executable_cache.c
- iree/hal/vulkan/native_executable.cc
- iree/hal/vulkan/native_executable.h
- iree/hal/vulkan/nop_executable_cache.cc
- iree/modules/hal/module.c
Matches the style of other parameter structs.
> Renaming iree_hal_executable_spec_t -> .._params_t.

- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/Passes.td
Exposing two debug flags in the bufferization pass. This should speed up debugging. To get debug output run:
```
iree/tools/iree-opt iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir --iree-codegen-iree-comprehensive-bufferize="test-analysis-only print-conflicts"
```
This will show you which OpOperands were decided to bufferize out-of-place and what caused the conflict. If there is no conflict annotation, it means that the tensor is not writable, thus a copy must be created (e.g., when specifying a tensor with `readonly`).
> Expose One-Shot Bufferize debug options

- bindings/tflite/model.c
This should help with issues like https://github.com/google/iree/issues/8412
I also noticed a lot of `IREE_TRACE_MESSAGE` use in https://github.com/google/iree/blob/main/bindings/tflite/model.c, which only logs to Tracy. Those could be turned in to `IREE_LOG` or `IREE_DLOG` (or we could add a macro that does both).
> Improve and log error message for tflite bindings model init.

- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
Another step before landing #8018, which would disable
benchmarking on Pixel 4. This makes sure we have another
device tracking Adreno GPU performance.
> Enable Vulkan benchmarking on Moto Edge X30

- iree/hal/vulkan/tracing.cc
- iree/tools/iree-benchmark-module-main.cc
This allows the tracing counters a chance to flush themselves.
> Forcing a wait-idle on the HAL device after each benchmark loop.

- iree/compiler/Codegen/LLVMGPU/Verifiers.cpp
- iree/compiler/Codegen/LLVMGPU/test/illegal_configuration.mlir
Batch_Matmuls where the first dimensions isn't parallelizable should not have their first dimension tiled.
> Fix loop size of 1 for batch_matmul verification

- iree/hal/vulkan/direct_command_buffer.cc
Looks like we aren't running ASAN+vulkan - probably swiftshader?
> Fixing leak of Vulkan command buffer resource sets.

- integrations/tensorflow/test/python/iree_tf_tests/math/math_test.py
This causes overflow in TF when run internally with asan.
> Avoid overflow from repeated exponentiation of large numbers

- iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp
- iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
This is a post-fix for https://github.com/google/iree/commit/36fb4d3ee02790e23f909872cbbf231ac93a3538
Verified that there are no alloca ops in mobilenet_v3 model with the PR.
> Do not adapt Linalg ops when the input is from ReadOnly tensors.

- integrations/tensorflow/iree_tf_compiler/MHLO/EmitDefaultIREEABI.cpp
- integrations/tensorflow/iree_tf_compiler/MHLO/test/emit_default_iree_abi.mlir
This fixes some legacy Jax integration tests which were relying on this
behavior.
> Flatten tuples when generating ABI signatures.

- iree/base/internal/file_io.c
- iree/base/internal/file_io.h
- iree/base/internal/file_io_test.cc
- iree/base/internal/flags.c
- iree/hal/local/BUILD
- iree/hal/local/CMakeLists.txt
- iree/hal/local/executable_library_benchmark.c
- iree/runtime/session.c
- iree/testing/vulkan/iree-run-module-vulkan-gui-main.cc
- iree/tools/BUILD
- iree/tools/CMakeLists.txt
- iree/tools/iree-benchmark-module-main.cc
- iree/tools/iree-check-module-main.cc
- iree/tools/iree-dump-module-main.c
- iree/tools/iree-run-module-main.cc
- iree/tools/utils/BUILD
- iree/tools/utils/CMakeLists.txt
- iree/tools/utils/trace_replay.c
- iree/tools/utils/vm_util.cc
- iree/tools/utils/vm_util.h
All file buffers in memory will be aligned to 4096B at the cost of 4096 + 64B.
4096 is higher than any alignment the compiler would produce and will ensure any alignment requirements the compiler has can be satisfied.
This also replaces the uses of the old C++ helper with the C API. This isn't the best API but should get us by for longer - I still have some cross-platform memory mapping code stashed that will eventually replace this.
> Aligning read file contents in tools.

- build_tools/cmake/iree_cc_binary.cmake
- iree/tools/CMakeLists.txt
This binary takes a long time to compile, and only needs to be
compiled rarely.
> Remove iree-mlir-lsp-server from `all` target.

- iree/compiler/Dialect/Stream/IR/StreamTypes.cpp
There is a runtime issue when using flags
`-iree-llvm-target-cpu-features=host`, exposing a flag to unblock
MiniLM bert benchmark.
See https://github.com/google/iree/issues/8506 for more details.
> Expose a flag to control default stream alignment value.

- iree/base/alignment.h
- iree/base/allocator.c
- iree/base/allocator.h
- iree/base/config.h
- iree/base/status.c
- iree/hal/buffer.h
- iree/hal/buffer_heap.c
- iree/hal/buffer_heap_impl.h
- iree/hal/cts/buffer_mapping_test.h
- iree/runtime/demo/hello_world_explained.c
- iree/runtime/demo/hello_world_terse.c
- iree/samples/custom_modules/custom_modules_test.cc
This is required to make some of the SIMD code we emit happy. Given that 95% of our buffers are suballocated in the compiler the larger-than-max_align-alignment isn't a large cost relative to the simplicity and potential perf benefits it has.
This does now require all imported buffers match the alignment. There's no way to query this today from allocators beyond using the config.h value but that's fine for now as we are only ever wrapping buffers in files that should already be aligned.
Fixes #8506.
> Align HAL heap buffers to a configuration-defined minimum alignment.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
The RISC-V targets were considered as ARM configuration. This PR makes
it go through Sandbox based approach.
The commit also moves quantized matmul to use DoubleTilingExpert. They
used old pipeline because of long compilation time. Many instructions
were generated during the lowering. This is addressed in https://github.com/llvm/llvm-project/commit/1538bd518cd236f4321695e9c5f0dd24601db366
It is a step toward https://github.com/google/iree/issues/8431
> Switch all x86 and RISC-V matmul codegen to use DoubleTilingExpert.

- iree/compiler/Codegen/SPIRV/Passes.cpp
This helps to clean up IRs by using certain ops from GLSL
extended instruction set.
> [spirv] Invoke GLSL canonicalization in the pipeline

- bindings/python/iree/runtime/hal.cc
- experimental/rocm/rocm_allocator.c
- iree/hal/allocator.c
- iree/hal/allocator.h
- iree/hal/allocator_heap.c
- iree/hal/buffer.h
- iree/hal/buffer_heap.c
- iree/hal/buffer_heap_impl.h
- iree/hal/buffer_view_util.c
- iree/hal/buffer_view_util.h
- iree/hal/cts/buffer_mapping_test.h
- iree/hal/cuda/cuda_allocator.c
- iree/hal/utils/buffer_transfer.c
- iree/hal/vulkan/vma_allocator.cc
- iree/modules/hal/module.c
- iree/runtime/demo/hello_world_explained.c
- iree/runtime/demo/hello_world_terse.c
- iree/samples/custom_modules/custom_modules_test.cc
- iree/samples/dynamic_shapes/main.c
- iree/samples/variables_and_state/main.c
- iree/tools/utils/image_util.c
This removes the special case wrapping path that only made sense for local host devices.
Fixes #8535.
> Replacing iree_hal_allocator_wrap_buffer with _import_buffer.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
The assumption was that all the element types have the same bitwidth.
However, there are cases that element types do not match, e.g.,
matmul i8xi8 -> i32. It caused issues that large tiling sizes were
selected, which kicked in heavy optimization in LLVM. This commit
chooses the smallest vector size over all the element types.
The commit reduce compilation time from hours to 5 mins for
mobilebert-baseline-tf2-quant.mlir when targeting ARM.
Fixes https://github.com/google/iree/issues/8540
> Account all the element types to determine vector sizes.

- iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- iree/compiler/InputConversion/MHLO/test/mhlo_to_mhlo_preprocessing.mlir
- iree/test/e2e/xla_ops/reduce_window.mlir
Lowering mhlo.reduce_window with padding has been supported in upstream with https://github.com/tensorflow/tensorflow/commit/9050a120e161936a73e953df6619b489f2466841
This is part of the cleanup of #8347
> Remove padding preprocessing for mhlo.reduce_window.

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
Pixel 4 has an ancient Adreno GPU driver that carries a few
known bugs triggered by our tests. Use Moto Edge X30,
which as a much recent driver, for Vulkan testing.
> Use Moto Edge X30 instead of Pixel 4 for Adreno GPU testing

- iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
Currently the backend cannot bufferize in-place dispatch regions that
contain operations where the root operation like conv, etc. is fused
with an elementwise operation, where in the latter the buffer for an
output cannot be reused for the result of the root. Disable fusing
such cases as a WAR.
For now only do this for the convolution cases, more might be needed
while the proper fix is worked out down stream. (Proper fix is to
"vectorize always" even if the vector size is 1).
Issue #8411
> Do not fuse with elementwise operations that cant bufferize in-place.

- iree/hal/cuda/cuda_allocator.c
Fixes the compile warning/error reported at https://github.com/google/iree/pull/8556#discussion_r828400899
(tested locally by building and running the CUDA HAL CTS tests, triggered the CUDA CI manually as it is post-submit only by default)
> Remove extra parameter to iree_hal_cuda_buffer_wrap.

- .github/workflows/advance_upstream_forks.yml
This is stable. Doing this every hour seems reasonable, since it's not
too expensive and it means that whoever's integrating will likely have
a recent baseline to work with.
> Advance upstream forks every hour

- docs/developers/debugging/tf_integrations_test_repro.md
The log is messy. It's better to get the python command from run files.
Also, iree_tfl_tests suite and iree_tf_tests suite have different flags. This reduces the confusion about reproducing the issue.
E.g.,
```
❯ cat iree_tfl_tests/llvmaot_posenet_i8.run
❯ cat iree_tf_tests/math/llvmaot__abs.run
```
> Update instructions for reproducing TF/TFLite integration tests

- build_tools/cmake/build_runtime_emscripten.sh
- experimental/web/sample_dynamic/build_sample.sh
- experimental/web/sample_dynamic/index.html
- experimental/web/sample_static/build_sample.sh
I've been running these with `bash .\experimental\web\sample_dynamic\build_sample.sh %CD%/../iree-build/install && bash .\experimental\web\sample_dynamic\serve_sample.sh` now, and the lack of a failure exit code was continuing past the short-circuiting `&&`.
> Fix exit codes in web sample scripts and whitespace in input.

- iree/compiler/Dialect/Flow/Transforms/ConvertToFlow.cpp
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/InjectDispatchTracing.cpp
- iree/compiler/Dialect/Flow/Transforms/Passes.h
- iree/compiler/Dialect/Flow/Transforms/Passes.td
- iree/compiler/Dialect/Flow/Transforms/StripSignednessPass.cpp
- iree/compiler/Dialect/Stream/Transforms/LayoutSlices.cpp
- iree/compiler/Dialect/Stream/Transforms/PackAllocations.cpp
- iree/compiler/Dialect/Stream/Transforms/PackConstants.cpp
- iree/compiler/Dialect/Stream/Transforms/Passes.h
- iree/compiler/Dialect/Stream/Transforms/Passes.td
- iree/compiler/Dialect/Stream/Transforms/ScheduleAllocation.cpp
- iree/compiler/Dialect/Stream/Transforms/ScheduleConcurrency.cpp
- iree/compiler/Dialect/Stream/Transforms/ScheduleExecution.cpp
- iree/compiler/Dialect/Util/Transforms/SimplifyGlobalAccesses.cpp
This improves the safety and glancibility for these kinds of generic passes, which were previously just opaque `OperationPass<>` with internal checks (of dubious quality).
Also deprivileges FuncOp in a couple of ancillary places.
Made possible by: https://github.com/llvm/llvm-project/issues/52916
> Convert generic FunctionOpInterface and CallableOpInterface passes to InterfacePass<>.

- build_tools/buildkite/presubmit.yml
- build_tools/buildkite/presubmit_bootstrap.yml
Now that this is checked in to the main branch we don't have
bootstrapping problems by pointing at it.
> Switch presubmit scripts to use main branch

- llvm-external-projects/iree-compiler-api/BUILD.bazel
- llvm-external-projects/iree-compiler-api/include/iree-compiler-c/Compiler.h
- llvm-external-projects/iree-compiler-api/lib/CAPI/CMakeLists.txt
- llvm-external-projects/iree-compiler-api/lib/CAPI/Compiler.cpp
I was trying to use just the C to create a MLIR module with the MLIR API, compile with the IREE compiler API, and then run with IREE runtime API. In the process I've noticed that the registry functions contained in this PR were missing. With these functions added to the C API I was able to successfully generate a MLIR module and run it in pure C.
> Expose missing register functions in compiler CAPI

- iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/Common/MemrefCopyToLinalg.cpp
- iree/compiler/Codegen/Utils/Utils.cpp
Current callback just asserts that the copy callback can insert a
valid copy. Return a nullptr, and throw an error when copy cannot be
generated. Also update all call sites to handle the error.
> Return error instead of asserting in bufferization copy callback.

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
With the tile and distribute moved out of flow this is not needed
anymore. The normal tied operands computation works fine.
> Remove ad-hoc logic to make the dest of `tensor.insert_slice` op a tied argument in dispatch region formation.

- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/LinalgTransformOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/bufferize-in-parallel.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/in-parallel-to-async.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/in-parallel-to-sequential-for.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tile-to-in-parallel.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tile-to-sequential-for.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling-to-tile-op.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/bufferize.mlir
- llvm-external-projects/iree-dialects/tools/iree-dialects-opt/CMakeLists.txt
- llvm-external-projects/iree-dialects/tools/iree-dialects-opt/iree-dialects-opt.cpp
This PR adds unit tests related to LinalgExt parallel operations.
In the process, improve the error message for the TileToLinalgExtTileOp transformation
which used to fail silently.
This exposed a missing external model registration which is also fixed.
> [LinalgExt] Add tests related to parallel abstractions

- iree/compiler/Codegen/LLVMGPU/Verifiers.cpp
- iree/compiler/Codegen/LLVMGPU/test/illegal_configuration.mlir
The second level of tiling didn't consider the fact that we distribute N
dimension on x threads and M dimension on y threads.
> [cuda] Fix verifier for tensorcore pipeline.

- build_tools/benchmarks/run_benchmarks_on_android.py
See individual commits in this PR. The main things are:
- Support a trace-capture-only mode (no 'normal' benchmarking run).
- Enforce sets of flags that must be all specified or all unspecified simultaneously
> More benchmark android improvements

- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/InsertDistributionInfoPass.cpp
- iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- iree/compiler/Codegen/Common/test/BUILD
- iree/compiler/Codegen/Common/test/CMakeLists.txt
- iree/compiler/Codegen/Common/test/insert_distribution_info.mlir
- iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
- iree/compiler/Codegen/SPIRV/Passes.cpp
The distribution information is known when tiling sizes are set. It can
be a separate pass, and be used before different distribution mechanism.
E.g., this is needed to enable distribution in LinalgFuseExpert.
> Split setting distribution information out from TileAndDistributeToWorkgroupsPass

- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/BufferizationAnalysis.cpp
- iree/compiler/Codegen/Common/BufferizeCopyOnlyDispatchesPass.cpp
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp
- iree/compiler/Codegen/Common/LinalgBufferizePass.cpp
- iree/compiler/Codegen/Common/test/BUILD
- iree/compiler/Codegen/Common/test/CMakeLists.txt
- iree/compiler/Codegen/Common/test/bufferize_copy_only_dispatches.mlir
- iree/compiler/Codegen/Common/test/insert_distribution_info.mlir
- iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- iree/compiler/Codegen/Dialect/LoweringConfig.td
- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/Passes.cpp
- iree/compiler/Codegen/SPIRV/test/config_default_linalg_ext_ops.mlir
- iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
- third_party/llvm-project.branch-pin
For cases where the dispatches are copy only , i.e. data is transfered
from one interface binding to another, bufferizing early results in a
`linalg.generic` (i.e. a copy) operation in the dispatch. The backends
can use this to generate code.  This is the first step in dropping
`TiledOpInterface` for `tensor.insert_slice` and
`tensor.extract_slice` operations.  This commit also adds patterns to
fold these operations with the `flow.dispatch.tensor.load` and
`flow.dispatch.tensor.store` operations. Eventually these patterns
will be moved to canonicalizations when the `TiledOpInterface`
implementation for `tensor.insert_slice` and `tensor.extract_slice`
are dropped.
Fixes #8509
> Add a pass to bufferize early copy only dispatches.

- build_tools/benchmarks/run_benchmarks_on_android.py
This avoids lingering artifacts when we have failed benchmark runs,
which can use out of storage issue sometimes.
> Always remove temporary directory used for benchmarking on the host

- build_tools/bazel/iree.bazelrc
- iree/build_defs.oss.bzl
- iree/hal/drivers/BUILD
This is using the new-ish build settings configuration. With this, you
can do something like
`bazel build --iree_drivers=dylib //iree/tools:iree-run-module` to only
build with the dylib driver.
> Enable selecting which drivers to build in Bazel

- build_tools/buildkite/pipelines/presubmit.yml
Pulls in
[hasura/smooth-checkout-buildkite-plugin@24e54e7729 (#25)](https://github.com/hasura/smooth-checkout-buildkite-plugin/pull/25/commits/24e54e7729).
Previously, the fetch would pull in the remote branch but not update
the local branch and then when running checkout, because the local
branch already existed, it would check out that instead of creating a
new local branch from the remote branch.
>  Update presubmit pipeline for fixes when fetching existing branch

- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- iree/compiler/Codegen/LLVMGPU/test/vector_to_gpu.mlir
This is needed to lower these ops in the tensorcore pipeline
> [CUDA] Add pattern to collapse vector.transfer_read to 2D when possible

- build_tools/bazel/iree_bytecode_module.bzl
- build_tools/cmake/iree_bytecode_module.cmake
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.h
- iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/WasmLinkerTool.cpp
Based on discussion at https://github.com/google/iree/pull/8584 and [on Discord](https://discord.com/channels/689900678990135345/689900680009482386/954411704765276180).
This leaves `iree-llvm-system-linker-path` unset in the build system so it always uses the search code in UnixLinkerTool or WindowsLinkerTool, rather than use the generic lld driver.
When used from an install, users can still choose to either trust the automatic discovery or explicitly specify individual linker tools. Now they can also set a different tool for WebAssembly linking.
> Add wasm-linker-path options and leave system linker path unset.

- docs/developers/debugging/tf_integrations_test_repro.md
The python command can only be run under `integrations/tensorflow/test/python` directory.
> Update debugging TF integration tests instructions.

- CMakeLists.txt
- build_tools/cmake/iree_benchmark_suite.cmake
- build_tools/cmake/iree_bytecode_module.cmake
(Part 2/7 of tracy fixes, PR #8655)
This allows Tracy to see into module code in benchmarks on platforms,
at least Android and Unix, where it can't decipher embedded modules.
While the motivation here is about benchmarks, the new CMake option
added here also controls test modules (not just benchmark modules). That
is for two reasons:
* It's good to be testing the same code paths as one is benchmarking.
* Just like this is useful for Tracy, this could also conceivably be
useful for any other debugging tool, such as GDB, that one may need to
run tests in, and which unlike profilers may be useful on more than
just benchmarks.
Note: @benvanik has already sent [this comment](https://github.com/google/iree/pull/8655#issuecomment-1080877654) on an earlier draft, resulting in the current naming …
> add IREE_BYTECODE_MODULE_FORCE_SYSTEM_DYLIB_LINKER

- iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
- iree/compiler/Codegen/Common/test/insert_distribution_info.mlir
- iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- iree/compiler/Codegen/LLVMCPU/test/tile_fuse_and_vectorize.mlir
They are not used in any pipelines. They were there because of legacy
issues.
> [Cleanup] Drop native_vector_size attr from lowering_config lit tests.

- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/test/linalg_transform.mlir
- iree/compiler/Codegen/LLVMCPU/test/linalg_transform_spec.mlir
- iree/tools/BUILD
- iree/tools/CMakeLists.txt
- iree/tools/init_iree_dialects.h
- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/LinalgTransformOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/Functional.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/TilingToTileOp.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Transforms/TransformInterpreter.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling-to-tile-op.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/tile.mlir
This revision updates the linalg_transform test to use tiling to the LinalgExt parallel abstractions.
These abstractions will be later connected to the proper workgroup concepts.
In the process, the PrintOp gains an optional argument to more easily print the handles resulting from
transformations.
`tile_to_iree_linalg_ext_tile_op` is extended to return 2 values: the tiled operation and the linalg_ext.tile_op.
> Add support for calling tile_to_in_parallel from IREE.

- iree/compiler/Dialect/HAL/Target/LLVM/internal/AndroidLinkerTool.cpp
-shared is required to generate the ELF type ET_DYN, required by dlopen,
so this is required to make system-linker work on Android, which is
required to get Tracy to see into the code in IREE modules.
This adds explanations about why we're using the Android NDK, why we're
using the Clang driver, and makes it more explicit which flags are to be
passed specifically to the linker as opposed to being clang flags.
> AndroidLinkerTool: generate a -shared library and rationalize

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- iree/compiler/Codegen/LLVMGPU/test/vector_to_gpu.mlir
This will allow op coming from split k transformation to get lowered to
tensorcore operations.
> [CUDA] Enable batch matmul with permutation in tensorcore pipeline

- build_tools/benchmarks/run_benchmarks_on_android.py
- iree/base/internal/dynamic_library_posix.c
(Part 1/7 of tracy fixes, PR #8655)
Passing IREE_PRESERVE_DYLIB_TEMP_FILES allows tracy capture to read the dynamic library mappings -- otherwise, by the time tracy capture reads them, the temp file backing the mapping is gone, making it impossible to read the mapping.
It is important however to preserve the android benchmarks' ability to clean up all temporary files, otherwise the benchmarking devices get cluttered and can run out of disk space over time. This is particularly a concern with CI devices (this benchmarking script is what is used in CI).
Since the script is already deleting the entire ANDROID_TMP_DIR, the simplest was to move the dylib temp files there. That is done by extending the semantics of IREE_PRESERVE_DYLIB_TEMP_FILES so that when it's set to any other string than …
> Allow tracy to find symbols and debug info in dynamic-library modules in Android benchmarks

- iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.h
- iree/compiler/Dialect/HAL/Target/LLVM/internal/EmbeddedLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/WasmLinkerTool.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/internal/WindowsLinkerTool.cpp
(Part 4/7 of tracy fixes, PR https://github.com/google/iree/pull/8655)
While working on the next commit in this series, on UnixLinkerTool which handles both Apple and general-Unix cases, I realized that we had a bit too much magic nestled in findToolInEnvironment: having it search both our own executable dir and the environment made for confusing call sites where it wasn't clear when we're interested in one or the other. This would be useful if we actually needed to search both, but in practice, it seems that each call site knows which or the two cases it falls in (own executable dir or environment) so this makes code more explicit in this respect and allows the following commit to be less error-prone.
I had to reinstate searching the environment in EmbeddedLinkerTool because two of the …
> Explicitly find linker in either environment or own build/install dir

- iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
Try to pick a smaller tile size based on the shape dimension to prevent
vectorization failure.
> [CUDA] Improve default kernel config

- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/RewriteLinalgDestructiveUpdatesPass.cpp
- iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- iree/compiler/Codegen/Common/test/BUILD
- iree/compiler/Codegen/Common/test/CMakeLists.txt
- iree/compiler/Codegen/Common/test/rewrite_linalg_destructive_updates.mlir
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/illegal_configuration.mlir
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
- iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- iree/compiler/Codegen/Sandbox/Passes.h
- iree/compiler/Codegen/Sandbox/Passes.td
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
- iree/compiler/Dialect/Flow/Transforms/SplitReduction.cpp
- iree/test/e2e/regression/lowering_config.mlir
- iree/test/e2e/xla_ops/reduce_window.mlir
This adds RewriteLinalgDestructiveUpdates pass, and one e2e cumsum integration tests.
This also contains a fix-up for removing split-k marker.
> Use upstream tile, fuse, and distribution for codegen driver approaches.

- iree/compiler/InputConversion/Common/BUILD
- iree/compiler/InputConversion/Common/CMakeLists.txt
- iree/compiler/InputConversion/Common/IREEImportPublic.cpp
- iree/compiler/InputConversion/Common/Passes.cpp
- iree/compiler/InputConversion/Common/Passes.h
- iree/compiler/InputConversion/Common/Passes.td
- iree/compiler/InputConversion/Common/SanitizeModuleNames.cpp
- iree/compiler/InputConversion/Common/test/BUILD
- iree/compiler/InputConversion/Common/test/CMakeLists.txt
- iree/compiler/InputConversion/Common/test/sanitize_module_names.mlir
Some programs coming through the new JAX frontend are including `.` characters in module names, like:
```mlir
module @xla_computation_inference_fn.396 { func @main() }
```
This conflicts with how the IREE VM uses `.` characters for namespacing, leading to runtime name resolution errors [like this one discussed on Discord](https://discord.com/channels/689900678990135345/782059441641881630/954154767238713344).
With this PR all `.` characters in module names are replaced with `_`. I also audited the other characters supported by MLIR itself and I _think_ we're in an okay spot for handling other module and function names that frontends may generate. There is still room for frameworks and bindings to generate their own naming rules if they want to sidecar that data inside an attribute or some …
> Sanitize module names during input conversion.

- iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp
(Part 5/7 of tracy fixes, PR https://github.com/google/iree/pull/8655)
- On Apple, now that it's clear that we're only searching the environment for a system linker, it's also clear that we only need to search for ld.
- Outside of Apple, similarly to the Android situation before PR #8665, we weren't so far generating a shared object. Doing so makes us explicitly require LLD so we trim the toolnames list accordingly.
@powderluv please take a look - is this breaking some Apple target? Also I hope that #8670 didn't break anything (so if things are broken before this PR, that might be the culprit).
> UnixLinker: trim toolnames (Apple) and generate shared lib (non-Apple)

- iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
[TSAN report](https://gist.github.com/bjacob/8df729620ae119b88a060eb3e9c38c46)
This is similar to #8590. Just more similar instances in the same file -- while #8590 fixed `getProcessorType`, a similar race existed in the other functions below creating Types.
Question: is there also a potential race in `HALDispatchABI::getInputTypes`? TSAN didn't observe anything here so far.
> more data races in HALDispatchABI constructor

- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/linalg_transform.mlir
- iree/compiler/Codegen/LLVMCPU/test/linalg_transform_spec.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/LinalgTransformOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/InParallelToHAL.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
This revision adds a rewrite of InParallel to HAL and makes it available in the transform dialect.
The PR also adds a copy of the necessary HAL ops to LinalgExt to avoid using fake generic ops to transport the IR until it can be lowered to HAL.
These can be removed once the transform dialect allows external registration of ops.
The revision also disables the sequential `createSetNumWorkgroupsPass` so that the body of the real `hal.executable.entry_point` remains empty for now.
The information relevant in the body will be propagated back in a subsequent commit.
Produced IR currently resembles the following:
```
module {
hal.executable private @pad_matmul_static_dispatch_0 {
hal.executable.variant public @embedded_elf_x86_64, target = #executable_target_embedded_elf_x86_64_ { …
```
> Rewrite InParallel to HAL

- iree/base/internal/synchronization.c
This fixes a race condition reported by TSan, [TSan report](https://gist.github.com/bjacob/29dc59ccfa86bc09c5b75fe7ae933ded)
I was hoping that this would be what @ScottTodd had [observed](https://discord.com/channels/689900678990135345/689957613152239638/958508447639433287) as an intermittent failure on CI.... but Ben points out that as I'm running with TSan, [this line](https://github.com/google/iree/blob/504ec77a85996c2c9a602030ad61f343eb543f5c/iree/base/internal/synchronization.h#L61) implies that I'm on a non-default (non-futex) path, so not was CI is running 🙁
> Lock the mutex around the condvar destruction

- iree/test/e2e/xla_ops/BUILD
- iree/test/e2e/xla_ops/CMakeLists.txt
With remote execution, build and test actions may easily run on
different architectures, but these tests specifically target the
architecture on which they were built.
> Tag host-cpu tests as "local"

- iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.h
- iree/compiler/Dialect/HAL/Transforms/BUILD
- iree/compiler/Dialect/HAL/Transforms/CMakeLists.txt
- iree/compiler/Dialect/HAL/Transforms/DumpExecutableSources.cpp
- iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- iree/compiler/Dialect/HAL/Transforms/Passes.h
- iree/compiler/Dialect/HAL/Transforms/VerifyTargetEnvironment.cpp
- iree/compiler/Dialect/HAL/Transforms/test/BUILD
- iree/compiler/Dialect/HAL/Transforms/test/CMakeLists.txt
- iree/compiler/Dialect/HAL/Transforms/test/dump_executable_sources.mlir
- iree/compiler/Dialect/HAL/Transforms/test/verify_target_environment.mlir
This will dump all hal.executable files to their own mlir files, which
can then be compiled individually with `iree-translate -iree-mlir-to-hal-executable`.
Fixes #8676.
> Adding -iree-hal-dump-executable-sources-to= flag.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/LinalgTransformOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Transforms/TransformInterpreter.cpp
- llvm-external-projects/iree-dialects/python/iree/compiler/dialects/_iree_linalg_transform_ops_ext.py
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/double-tiling.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/invalid.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/scalarize.mlir
Previously, tiling with the scalarize_dyn_dims would systematically crash because it
expected `0` loops to be produced (i.e. because the tile size must be empty).
In reality, this will always produce as many loops as there are dynamic dims in the op.
Change the behavior to only return the op and always return `0` loops.
Subsequently, introduce a ScalarizeOp and move the TileOp.scalarize logic to it. 
This improves separation of concerns.
> Fix scalarize_dyn_dims composition.

- iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp
- iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_load_store.mlir
We are scalarizing the transfer write ops anyway, don't need to
require minor identity access permutation map. Weaken that to
projected permutation.
Fixes https://github.com/google/iree/issues/8580
> [spirv] Support scalarizing non-minor-identity transfer write

- iree/compiler/Dialect/VM/Transforms/BUILD
- iree/compiler/Dialect/VM/Transforms/CMakeLists.txt
- iree/compiler/Dialect/VM/Transforms/Conversion.cpp
This fixes the arith.floordivsi case in #8715, and should fix a number
of other ops if we encounter them.
Fixes #8715
> VM::Conversion: add arith::populateArithmeticExpandOpsPatterns

- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/BUILD
- iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- iree/compiler/Codegen/LLVMCPU/test/transpose_avx2_lowering.mlir
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
This PR enables AVX2 lowering for vector.transpose operations when the '+avx2' cpu
feature is provided. This lowering generates a more performant sequence of instructions
for 4x8xf32 and 8x8xf32 vector transposes.
> Enable AVX2 lowering for vector.transpose in double tile expert

- integrations/tensorflow/test/iree_tf_tests/uncategorized/llvmaot__fill.run
- integrations/tensorflow/test/iree_tf_tests/uncategorized/vulkan__fill.run
- iree/compiler/Dialect/Flow/Transforms/CaptureDispatchDynamicDims.cpp
- iree/compiler/Dialect/Flow/Transforms/test/capture_dispatch_dynamic_dims.mlir
It previously was using a ValueRange pointing into a stale
updated-in-place operand list.
Fixes #8718
> Fix rewriting logic in CaptureDispatchDynamicDims

- benchmarks/TFLite/CMakeLists.txt
In experimental mmt4d configs, we were unconditionally passing `--iree-flow-mmt4d-target-options=arch=aarch64 features=+dotprod`  AND NOT passing the corresponding `-iree-llvm-target-cpu-features=+dotprod`. That didn't matter as long as we were only testing `fp32` benchmarks, but now that we have MobileBertSquad-int8, it does matter.
Concretely at the moment our MobileBertSquad-int8 first selects the dotprod-specific tile size (because we pass `--iree-flow-mmt4d-target-options=arch=aarch64 features=+dotprod`) but then it doesn't enable the corresponding asm kernel (because we don't pass `-iree-llvm-target-cpu-features=+dotprod`) so it ends up generating slow code.
> Properly enable +dotprod in int8 benchmarks.

- build_tools/benchmarks/common/CMakeLists.txt
- build_tools/benchmarks/common/benchmark_config.py
- build_tools/benchmarks/common/benchmark_config_test.py
Add config class to load and store all benchmark settings from command arguments. This will help us pass the benchmark settings through functions without having a long list of function parameter.
> Add config class to represent the parameters of benchmark script

- CMakeLists.txt
- build_tools/cmake/iree_bytecode_module.cmake
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRPasses.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.h
- iree/hal/local/loaders/system_library_loader.c
This implements TSan instrumentation in the IREE compiler, and adds a `IREE_BYTECODE_MODULE_ENABLE_TSAN` flag, which when set causes `iree_bytecode_module` to enable TSan instrumentation. 
When `IREE_BUILD_TESTS` is on, we enforce early that `IREE_ENABLE_TSAN` and `IREE_BYTECODE_MODULE_ENABLE_TSAN` agree, as we would otherwise get test crashes anyway.
`IREE_BYTECODE_MODULE_ENABLE_TSAN` also requires `IREE_BYTECODE_MODULE_FORCE_SYSTEM_DYLIB_LINKER` to be set. That too is enforced early.
Putting all that together, with this PR, the incantation to build tests with TSan is:
```
cmake \
-DIREE_BUILD_TESTS=ON \
-DIREE_ENABLE_TSAN=ON \
-DIREE_BYTECODE_MODULE_ENABLE_TSAN=ON \
-DIREE_BYTECODE_MODULE_FORCE_SYSTEM_DYLIB_LINKER=ON \
...other flags...
cmake --build .
cmake --build . --target …
```
> TSan instrumentation of module code

- iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- iree/test/e2e/regression/trace_dispatch_tensors.mlir
The v1 flag was removed, so we can correct v2 flag name.
> Update iree-flow-trace-dispatch-tensors flag name.

- iree/compiler/Codegen/LLVMGPU/BUILD
- iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/LLVMGPUReduceBankConflicts.cpp
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/LLVMGPU/test/BUILD
- iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- iree/compiler/Codegen/LLVMGPU/test/reduce_bank_conflicts.mlir
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
Stop gap solution to reduce the number of bank conflicts in cuda gemm kernels. A better solution will be implemented later but this allows to get a performance boost on current gemm implementation.
> [CUDA] Add pass to try to reduce shared memory bank conflicts

- .github/workflows/oneshot_candidate_release.yml
Allow oneshot to build from Nod.ai's fork too.
Also remove hardcode for "main" branch
TEST=Able to build on custom shark branch
https://github.com/NodLabs/SHARK/actions/runs/2080070703
> Add a oneshot build and allow building on a branch

- .github/workflows/oneshot_candidate_release.yml
- .github/workflows/schedule_candidate_release.yml
Use the official env var ${{ github.ref_name }} referencing the current branch.
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
Tested on a local branch: https://github.com/NodLabs/SHARK/actions/runs/2097947669
> Use official github.ref_name to refer to the current branch in builds

- bindings/python/iree/runtime/array_interop.py
- bindings/python/iree/runtime/function.py
- bindings/python/iree/runtime/hal.cc
- bindings/python/iree/runtime/invoke.cc
- bindings/python/iree/runtime/vm_test.py
- bindings/tflite/tensor.c
- experimental/web/sample_static/main.c
- iree/compiler/Dialect/HAL/Conversion/HALToVM/test/allocator_ops.mlir
- iree/compiler/Dialect/HAL/IR/HALBase.td
- iree/compiler/Dialect/HAL/Transforms/test/convert_to_hal.mlir
- iree/hal/allocator.h
- iree/hal/buffer.c
- iree/hal/buffer.h
- iree/hal/buffer_view_util.c
- iree/hal/cts/allocator_test.h
- iree/hal/cts/command_buffer_dispatch_test.h
- iree/hal/cts/command_buffer_test.h
- iree/hal/cuda/cuda_allocator.c
- iree/modules/check/check_test.cc
- iree/runtime/demo/hello_world_explained.c
- iree/runtime/demo/hello_world_terse.c
- iree/samples/custom_modules/custom_modules_test.cc
- iree/samples/dynamic_shapes/main.c
- iree/samples/simple_embedding/simple_embedding.c
- iree/samples/static_library/static_library_demo.c
- iree/samples/variables_and_state/main.c
- iree/samples/vulkan/vulkan_inference_gui.cc
- iree/tools/iree-e2e-matmul-test.c
- iree/tools/utils/image_util.c
- iree/tools/utils/trace_replay.c
Future changes will remove the requirement that backends support concurrent host and device visibility and will be easier to enforce if we don't have a bunch of places asking for it when they don't need it.
The python side needs work still - it's assuming mappable memory is always available.
> Limiting buffer host visibility where not required.

- iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- iree/compiler/Codegen/SPIRV/test/vectorize_matmul.mlir
This is needed to fold `transpose(broadcast(<scalar>))` patterns
before further vector-level transformations.
Fixes https://github.com/google/iree/issues/8689
> [spirv] Invoke TransposeOp canonicalization after vectorization

- .github/ISSUE_TEMPLATE/bug_report.md
I'm going on vacation, so this system for making sure issues don't get
lost will not continue working. Issues have mostly been taken care of
without intervention from me, so I'm not sure how much this was helping
anyway.
> Remove default assignee for issues

- iree/testing/vulkan/iree-run-module-vulkan-gui-main.cc
- iree/testing/vulkan/vulkan_gui_util.cc
* Use Vulkan 1.2 now
* Filter out non-existing optional extensions
* Print out chosen GPU for clarity
> [vulkan] Improve iree-run-module with GUI

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/LLVMCPUTileFuseAndVectorizeLinalgTensorOps.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
- iree/test/e2e/cpu_specific/BUILD
- iree/test/e2e/cpu_specific/CMakeLists.txt
- iree/test/e2e/cpu_specific/tests.mlir
- iree/test/e2e/xla_ops/dot.mlir
In the past, we only considered contraction ops that have at least
three loops. The PR accounts matvec and dot cases.
For now, set the limit to having a single reduction loop and it's
expected to be the innermost loop. This condition can be relaxed if
there are needs.
Fixes https://github.com/google/iree/issues/8713
> Fixes configurations for matvec and dot. 

- iree/test/e2e/matmul/BUILD
- iree/test/e2e/matmul/CMakeLists.txt
The test currently requires mappable memory and that's not guaranteed.
> Disabling CUDA e2e matmul tests pending #8784.

- iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- iree/tools/iree-benchmark-module-main.cc
IREE is not a BLAS library, and iree-benchmark-module is not the same as a BLAS library microbenchmark.
> Adding a comment and print to iree-benchmark-module.

- iree/compiler/Codegen/Common/SetNumWorkgroupsFromLinalgExtPass.cpp
- iree/compiler/Codegen/Transforms/Transforms.cpp
- iree/compiler/Dialect/HAL/Conversion/StreamToHAL/ConvertStreamToHAL.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.cpp
- iree/compiler/Dialect/HAL/IR/HALOps.td
In particular, the usage of variadic regions seems unnecessary.
In the future when we want multiple regions, we can add them with a specific name.
This simplifies the code around region/block logic, as well as builders.
> [NFC] Apply some cleanups to HAL::EntryPointOp

- iree/compiler/InputConversion/TMTensor/Passes.td
- iree/compiler/InputConversion/TMTensor/test/BUILD
- iree/compiler/InputConversion/TMTensor/test/CMakeLists.txt
- iree/compiler/InputConversion/TMTensor/test/convert_tm_tensor_to_linalg_ext.mlir
- iree/compiler/Pipelines/Options.cpp
- iree/compiler/Pipelines/Options.h
- iree/compiler/Pipelines/Pipelines.cpp
- llvm-external-projects/iree-compiler-api/python/iree/compiler/tools/core.py
This also tidies up the identifiers throughout the codebase to be
`tm-tensor` and `tm_tensor` for consistency.
> Expose tm_tensor input type to Python

- iree/compiler/Codegen/Common/OptimizeVectorTransferPass.cpp
- iree/compiler/Codegen/SPIRV/MaliConfig.cpp
- iree/compiler/Codegen/SPIRV/Passes.cpp
- iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_elementwise_ops.mlir
- iree/compiler/Codegen/SPIRV/test/vectorize_matmul.mlir
* Use tile size 8 for matmul K to have better memory access.
* When unrolling, use different vector sizes between compute and
memory transfer ops. For the former we use 4-element vectors
at most, but for the latter we can try to use 8-element vectors
for better memory load/store performance.
* Also perform leading size-1 dimension casting immediately after
unrolling to avoid having leading size-1 dimensions in loop
carried vectors.
* Re-wire bitbast bubbling patterns to help turning vector<8xf16>
into vector<4xf32> across the function.
> [spirv] Fix fp16 vectorization flow

- iree/compiler/Codegen/SPIRV/SPIRVTileAndDistribute.cpp
- iree/compiler/Codegen/SPIRV/test/tile_and_distribute.mlir
- iree/test/e2e/cpu_specific/BUILD
- iree/test/e2e/cpu_specific/CMakeLists.txt
- iree/test/e2e/cpu_specific/tests.mlir
- iree/test/e2e/xla_ops/dot.mlir
This commit cleans up SPIRVTileAndDistribute to avoid hard
coding specific ops in configurations for tiling and distributing
to threads. We now use op interfaces there. This allows proper
tiling of all Linalg ops, which we already deduced tiling
scheme during configuration. Hardcoding specific ops might
cause only specific ops gotten recognized and thus causing
discrepancy and error. The correctness error for matvec was
due to this. It is fixed by this patch.
> [spirv] Fix SPIRVTileAndDistribute flow

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_launch_configuration.mlir
While more quantized models are added to benchmarks and the configurations are not well tuned, it takes long time to compile and execute. The PR takes the first stab at tuning configurations to have acceptable compilation time. The execution time is also improved as shown below.
The compilation time is cut from 5.5 mins to 1.3 mins.
Perf improvements (sampled from MobileBert Int8):
Before:
```
-----------------------------------------------------------------------------------------------
Benchmark                                                     Time             CPU   Iterations
-----------------------------------------------------------------------------------------------
BM_matmul_i8i8i32_384x128x128/process_time/real_time      0.954 ms        0.933 ms          738 …
```
> Improve compilation time and execution time for quantized matmul on ARM

- iree/compiler/Codegen/Common/BUILD
- iree/compiler/Codegen/Common/CMakeLists.txt
- iree/compiler/Codegen/Common/WorkGroupSwizzle.cpp
- iree/compiler/Codegen/Common/test/BUILD
- iree/compiler/Codegen/Common/test/CMakeLists.txt
- iree/compiler/Codegen/Common/test/swizzle_workgroup.mlir
- iree/compiler/Codegen/LLVMGPU/Passes.cpp
- iree/compiler/Codegen/Passes.h
- iree/compiler/Codegen/Passes.td
This PR adds a pass to swizzle workgroup ids for better cache use. 
Currently this is experimental and is done by passing a global option for the log of the swizzle tile size desired. By default the pass does not do any swizzling and will not change the generated code.
> Add workgroup swizzling for better cache reuse

- build_tools/benchmarks/run_benchmarks_on_android.py
Currently tracy capture is unconditionally printing verbose progress info and using ANSI colors. I'm fixing that in https://github.com/wolfpld/tracy/pull/362. Part of it is using `isatty` to detect whether the output is a terminal or another kind of file, such as a pipe. That can't work for us as long as we are unconditionally redirecting output to a pipe. So this implements equivalent behavior for our purposes but without using a pipe.
> redirect capture output

- build_tools/benchmarks/run_benchmarks_on_android.py
Currently, that logging (progress % information) amounts for the bulk of the size of our log files, which are over the 1M limit for viewing in buildkite.
[Example](https://buildkite-cloud.s3.amazonaws.com/logs-by-pipeline/16761a6a-9657-40e7-9bc0-04b04571c704/4349691f-b612-4a0a-9cb4-702f8c87e692/4d02f837-2910-4475-830d-ddc835522bae.log?response-content-disposition=inline&response-content-type=text%2Fplain&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQPCP3C7L6WZRU7I2%2F20220407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220407T174239Z&X-Amz-Expires=600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjECcaCXVzLWVhc3QtMSJIMEYCIQC6OW6SxplX4kRoi0FwPjrzl2bLM5tuzxfSG%2F5AcIoQHwIhAITynKZukg6CzIOdZCvUKtBFvmBjm%2FBvU3GaXcU3iqPqKoMECMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMMDMyMzc5NzA1MzAzIgyfCwHsiTboU8H …
> hide output of adb push when the output is not a TTY

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/LinalgTransformOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/double-tiling.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/pad.mlir
Previously only string padding values, that later on would be parsed to the element type of the padded operation, were supported.
After the change, it is possible to hand in a floating point attribute directly.
Co-authored-by: Tobias Gysi <gysit@users.noreply.github.com>
> Add support for non-string padding values.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/LinalgTransformOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/double-tiling.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/fuse-and-peel.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/invalid.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/pad.mlir
The FuseOp now returns a handles to the generated tile loops, which then may be used to peel of loops from the fused loop nest.
Co-authored-by: Tobias Gysi <gysit@users.noreply.github.com>
> Add peeling support to fusion.

- iree/compiler/Dialect/Util/Transforms/BUILD
- iree/compiler/Dialect/Util/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Util/Transforms/ConvertPrimitiveType.cpp
- iree/compiler/Dialect/Util/Transforms/test/demote_f64_to_f32.mlir
- iree/compiler/Dialect/Util/Transforms/test/demote_i64_to_i32.mlir
Add special patterns to handle the arith cast ops that were causing
issues here when the operand and result types are the same.
Part of #8745 (it at least fixes the immediate issues we are seeing)
> Specially handle width-sensitive arith cast ops.

- iree/compiler/Codegen/Common/BufferizeCopyOnlyDispatchesPass.cpp
- iree/compiler/Codegen/Common/DestructiveUpdateUtils.cpp
- iree/compiler/Codegen/Common/test/bufferize_copy_only_dispatches.mlir
- iree/compiler/Codegen/Common/test/rewrite_linalg_destructive_updates.mlir
- iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- iree/compiler/Codegen/Utils/Utils.cpp
- iree/compiler/Codegen/Utils/Utils.h
- iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- iree/compiler/Dialect/Flow/IR/FlowOps.td
- iree/test/e2e/regression/BUILD
- iree/test/e2e/regression/CMakeLists.txt
- iree/test/e2e/regression/strided_slice.mlir
The current rewrite of destructive updates ignores all offsets/strides
of the source flow.dispatch.tensor.load/store. Fix that to handle these
offset and strides correctly.
Fixes #8790 , #8825
> Handle offsets/strides correctly while rewriting destructive updates.

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/LinalgExtBufferization.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/bufferize-in-parallel.mlir
Copies were inserted at the wrong place and the wrong buffer was used
during bufferization.
> Fix bufferization of in_parallel

- bindings/python/iree/runtime/array_interop_test.py
- bindings/python/iree/runtime/hal.cc
I had to choose which one to be consistent with, and I chose to adjust
the "bool" type to be
`IREE_HAL_ELEMENT_TYPE_VALUE(IREE_HAL_NUMERICAL_TYPE_INTEGER, 1))`, as
this appears to be what IREE produces internally for tensor of i1 dtype.
> Make MapElementTypeToDType consistent with the enum

- iree/test/e2e/matmul/BUILD
- iree/test/e2e/matmul/CMakeLists.txt
- iree/tools/iree-e2e-matmul-test.c
This is a minimal fix for matmul test, use the host local copy for all
the reference checks as it is allows to be mapped. Since a large portion
of the code relies on mapping the buffer during verification it is
simpler to keep it that way. This could be refactored to not need the
mapping but in order to keep the fix simple this is left untouched.
> Fix memory handling problem in matmul_test and renable cuda tests

- iree/task/executor.c
- iree/task/post_batch.c
(Credits to @benvanik for guessing in [this comment](https://github.com/google/iree/pull/8710#issuecomment-1085095224))
When an executor creates a worker, it populates its data structures
such as `worker->task_queue`, creates the thread, then finally updates
the masks such as` executor->worker_live_mask` that control work-stealing
among workers.
When an executor looks for work to steal, it first looks up these masks,
such as executor->worker_live_mask, to identity the worker to steal
from. It then proceeds to stealing from that worker, which involve
accesses to its data structures such as `worker->task_queue`.
The above two do not seem to be currently ordered by anything, and TSan
reports that about once every 200 runs of `dylib_semaphore_test`: …
> Order worker initialization vs other threads stealing work

- iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
[TSan report](https://gist.github.com/bjacob/7045d80702d1ebfebc1f5351d23cd50c)
The mutexes that I had recently added in each of these functions (#8688, #8590) fixed some data races occuring when two threads were concurrently calling the same one function among those. But I didn't understand then, that the data being raced on by these different functions is the same - so even with those mutexes on each of these functions, we still have a race when different threads call different functions concurrently. The fix is to let all these functions share a single mutex.
> Fix data race: different mutexes were guarding the same data

- build_tools/benchmarks/common/benchmark_suite.py
- build_tools/benchmarks/common/benchmark_suite_test.py
The internal format of driver name should be `iree-*`, and it is better to keep the original form of the `target_arch` from benchmark suite directory name. Only normalize them when we need to do match.
> Fix the format of driver and target_arch

- build_tools/docker/base/Dockerfile
- build_tools/docker/base/fetch_cuda_deps.sh
The package and directory structure was a bit more complicated than
presumed and I opted to fetch and use nvidia's download script to manage
it. This script then trims to just the license and files we need,
bringing the cost from ~100MiB to ~1MiB. We will just add this to the
base docker image and then extend our CMake logic to probe when the
magic env var is set.
CMake updates will be made separately once images are rolled.
```
root@129bf88cd357:/# du -h /usr/local/iree_cuda_deps/
464K    /usr/local/iree_cuda_deps/nvvm/libdevice
468K    /usr/local/iree_cuda_deps/nvvm
776K    /usr/local/iree_cuda_deps/include
1.3M    /usr/local/iree_cuda_deps/
```
Progress on #8847
> Add a script to fetch and trim the CUDA toolkit deps needed to build.

- CMakeLists.txt
- build_tools/cmake/rebuild.sh
Adds a special case to detect when the stripped down CUDA deps on our CI
images are available and uses that (i.e. a full SDK will not detect in
this case).
Fixes #8847
> Always build CUDA on CI.

- .github/workflows/validate_and_publish_release.yml
This is to handle the case when downstream forks may diverge
temporarily and not be able to push from another tree.
Tested with github actions downstream
> Force push latest-snapshot

- iree/task/executor.c
- iree/task/poller.c
- iree/task/poller.h
- iree/task/worker.c
- iree/task/worker.h
This ensures that all workers (and the poller) have exited and that no
threads are live by the time we go to deinitialize their data structures.
Fixes #8863.
> Splitting worker shutdown into request+join+deinit.

- iree/hal/dylib/cts/CMakeLists.txt
This fixes some of the remaining test failures when building with TSan (not TSan errors per se! Just that TSan requires
IREE_BYTECODE_MODULE_FORCE_SYSTEM_DYLIB_LINKER).
Fixes #8879
> Make the dylib CTS support IREE_BYTECODE_MODULE_FORCE_SYSTEM_DYLIB_LINKER

- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/LLVMCPU/test/BUILD
- iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- iree/compiler/Codegen/LLVMCPU/test/pipeline_tests.mlir
It seems to cause errors in bufferization.
> Undo use of upstream pass for first level tile + distribute.

- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_driver.py
- build_tools/benchmarks/common/benchmark_driver_test.py
- build_tools/benchmarks/common/benchmark_suite.py
- build_tools/benchmarks/common/benchmark_suite_test.py
- build_tools/benchmarks/run_benchmarks_on_android.py
Refactor the Android benchmark tool to use the new benchmark framework.
It mainly moves the code from `run_benchmarks_for_category` to `AndroidBenchmarkDriver.run_benchmark_case`
> Refactor run_benchmarks_on_android.py

- build_tools/bazel/iree_bytecode_module.bzl
- build_tools/bazel/iree_check_test.bzl
- build_tools/bazel/iree_trace_runner_test.bzl
- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_trace_runner_test.cmake
That was added back when enabling mmt4d required preprocessing the input MLIR file with `iree-opt` with a custom pass. That has been unused since #8402 exposed that in `iree-translate`.
> drop `OPT_FLAGS` parameter, no longer used.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/Input/InputOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/Input/InputOps.cpp
Follow behavior (approximately) in Util dialect for these ops and verify
that the value loaded/stored matches load/store's types.
> Add verifiers for types of Input ops global load/store

- iree/compiler/Dialect/Flow/Transforms/BUILD
- iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
- iree/compiler/Dialect/Flow/Transforms/FusionUtils.cpp
- iree/compiler/Dialect/Flow/Transforms/FusionUtils.h
Current fusion heuristics seems to have degraded over time.
With the ops moved to different dialects, and changes to op semantics,
the control functions used seem to not really capture the original intent.
This PR revisits the control functions used for
- Elementwise operation fusion
- Fusion of elementwise operations with reshapes by expansion.
This change also pulls in the fusion be collapse to clean up soem
additional reshapes and replaces some of the one-off patterns that
were intending to achieve a similar effect.
See #8724 and https://discourse.llvm.org/t/rfc-next-iteration-of-fusion-of-elementwise-operations/59955/4 for discussion of impact of this change.
> Change elementwise op fusion heuristics.

- integrations/tensorflow/test/lit.cfg.py
If TEST_UNDECLARED_OUTPUTS_DIR or TEST_TMPDIR is set, use those
directories instead to write output instead of creating new temporary
directory. These directories are used by bazel and tooling around bazel
often expect output there in failing cases.
> Change lit output dir to specified dir if set.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir
Introduces an operation for computing the top K elements along a specified dimension of an N-D tensor. Can also calculate the min K elements instead. 
Defines a verifier and tests through `roundtrip.mlir`.
> TopK LinalgExt Op Implementation with roundtrip.mlir test

- CMakeLists.txt
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- iree/task/BUILD
- iree/task/CMakeLists.txt
- iree/task/topology_cpuinfo.c
When set to OFF the --task_topology_max_group_count= value will be used.
If you don't want the random default it has then make sure to specify
--task_topology_group_count=.
Progress on #8469.
> Adding IREE_ENABLE_CPUINFO to allow disabling cpuinfo usage.

- build_tools/python_deploy/build_macos_packages.sh
- build_tools/python_deploy/install_macos_deps.sh
- iree/compiler/setup.py
- runtime/setup.py
* Also adds a script to install known needed Python versions.
* Fixes setup.py files to plumb through vars needed to control MacOS arch and target versions.
* CMake hack to let cpuinfo build for universal (just guts it for all Apple targets pending more specific work).
* Build script will build universal2 wheels targeting MacOS 11.0 (matches the official Python binaries).
* Needs a couple of other local fixes for cpuinfo to actually work (will update once Ben's changes land).
> One stop scripts to build Python wheels on MacOS.

- .github/workflows/build_package.yml
- build_tools/python_deploy/build_linux_packages.sh
- build_tools/python_deploy/build_macos_packages.sh
* Temporarily removes the windows build (because I haven't written the scripts for it yet).
* Should be ~the same on Linux. On MacOS, this *should* yield us shiny new universal wheels.
* MacOS compiler build time should increase to ~4h, but this is probably still less than long tail Linux TF build time.
> Rework the build_package pipeline to use the new onestop scripts.

- iree/compiler/API/python/CMakeLists.txt
- iree/compiler/API/python/test/transforms/ireec/compile_sample_module.py
This is needed for experiments with the transform dialect.
> Activate pdl Python bindings

- experimental/rocm/rocm_device.c
- iree/hal/cts/command_buffer_dispatch_test.h
- iree/hal/cts/executable_cache_test.h
- iree/hal/cuda/cuda_device.c
- iree/hal/device.h
- iree/hal/executable_cache.c
- iree/hal/executable_cache.h
- iree/hal/local/sync_device.c
- iree/hal/local/task_device.c
- iree/hal/vulkan/vulkan_device.cc
- iree/modules/hal/module.c
Executable caches are allowed to use this to schedule async/parallel
operations that will run on an external scheduler. Future changes will
need to make the Vulkan implementation parallelize pipeline creation.
Fixes #8001.
> Adding iree_loop_t arg to executable cache creation.

- build_tools/benchmarks/CMakeLists.txt
- build_tools/benchmarks/common/CMakeLists.txt
- build_tools/cmake/iree_python.cmake
This solves #8708 by adding a test rule to support custom python paths.
> Add test rule for generic python tests.

- iree/compiler/Dialect/Stream/Transforms/ScheduleAllocation.cpp
Since the IR is mutated during this step the SSA values don't line up
with the input IR and seeing the op makes it easier to correlate.
> Printing the op when an allocation mapping fails.

- iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
Current dispatch region formation does not handle cases where the
fused operations themselves have uses outside of the ops pulled into
the same dispatch, i.e. it only handles cases where the results of the
dispatch are same as the results of the root op. Relax this to allow
for fusing with operations, where even the fused ops can have uses
outside of the dispatch. Enable this in a following commit.
> NFC refactor dispatch region formation to allow multiple results.

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/bufferize-in-parallel.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/bufferize.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/expert.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/single-tiling-full-script.mlir
* Replace usage of nested PassManager-s in BufferizeOp::apply
* Use cast instead of dyn_cast
Co-authored-by: Denys Shabalin <shabalin@google.com>
> Replace usage of nested PassManager-s in BufferizeOp::apply

- docs/website/docs/deployment-configurations/gpu-cuda-rocm.md
- iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- iree/compiler/Dialect/HAL/Target/CUDA/test/smoketest.mlir
- iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- iree/compiler/Dialect/HAL/Target/MetalSPIRV/MetalSPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.cpp
- iree/compiler/Dialect/HAL/Target/TargetBackend.h
- iree/compiler/Dialect/HAL/Target/VMVX/VMVXTarget.cpp
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.h
- iree/compiler/Dialect/HAL/Target/WebGPU/WebGPUTarget.cpp
- iree/compiler/Dialect/HAL/Target/WebGPU/WebGPUTarget.h
- iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- iree/compiler/Dialect/HAL/Transforms/Passes.h
- iree/compiler/Dialect/HAL/Transforms/SerializeExecutables.cpp
- iree/test/e2e/matmul/BUILD
- iree/test/e2e/matmul/CMakeLists.txt
- iree/test/microbenchmarks/linalg_transpose.mlir
These allow target backends to route intermediate files and final
serialized binaries to a specific path for easier user inspection.
These do not change the behavior of serialization or any other output
flags (such as where to write static library files or how binaries
are embedded in VMFBs) and are strictly for debugging.
Targets that previously had their own flags for dumping outputs now use
the new common -iree-hal-dump-executable-binaries-to= flag. Both flags
are target-dependent and may have differing behavior (for example
LLVM CPU static library output doesn't produce a binary, and the CUDA
target isn't dumping anything yet).
The LLVM CPU target needs some cleanup to allow it to use the
intermediates path and today keeps it's own flag, but that is something
we can remove in future …
> Adding -iree-hal-dump-executable-intermediates/binaries-to= flags.

- iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- iree/compiler/Codegen/LLVMCPU/test/materialize_x86_64_launch_configuration.mlir
As #8980 described, this PR changes the heuristic on the distributed size to take the vector size into account. When the vector size is provided, it tries to find `the largest multiplier of the vector size which can divide the dim size and <= dim size / 2`.
Since tiling with a multiplier of vector size doesn't always have benefits, the vector size is passed as an optional hint per dimension. This PR only enables the new heuristic for the Conv2d on output feature dimension.
On x86 with AVX512:
|                                   | Base(ms) | After(ms) | Speedup |
|-----------------------------------|----------|-----------|---------|
| MobileNetV3, dylib-sync, 1 thread | 6.13     | 5.12      | 1.19x   |
| MobileNetV3, dylib, 4 threads     | 4.27     | 3.94      | 1.08x   |
On the sample …
> Improve the heuristic on picking distributed size.

- .github/CODEOWNERS
- build_tools/cmake/build_runtime_emscripten.sh
- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/testing/test_samples.sh
- docs/developers/developing_iree/developer_overview.md
- docs/developers/get_started/building_with_emscripten.md
- docs/website/docs/bindings/c-api.md
- docs/website/docs/building-from-source/python-bindings-and-importers.md
- experimental/web/sample_dynamic/README.md
- experimental/web/sample_dynamic/build_sample.sh
- experimental/web/sample_dynamic/serve_sample.sh
- experimental/web/sample_static/CMakeLists.txt
- experimental/web/sample_static/README.md
- experimental/web/sample_static/build_sample.sh
- experimental/web/sample_static/iree_worker.js
- experimental/web/sample_static/serve_sample.sh
- samples/dynamic_shapes/README.md
- samples/dynamic_shapes/test.sh
- samples/variables_and_state/README.md
- samples/variables_and_state/test.sh
- samples/vulkan/vulkan_inference_gui.cc
Following https://github.com/google/iree/pull/8950 and https://github.com/google/iree/pull/8958. Probably more to follow with https://github.com/google/iree/issues/8955.
This should fix the failing builds on https://buildkite.com/iree/iree-build-configurations and https://buildkite.com/iree/iree-samples.
> Fix several paths following samples/ and runtime/ code moves.

- build_tools/buildkite/samples.yml
Missed this in https://github.com/google/iree/pull/8988 (and only tested the Buildkite pipeline on https://github.com/google/iree/pull/8987)
Should fix https://buildkite.com/iree/iree-samples/builds/321#645def5a-0354-4b8c-bfb4-a2a3985e9e54
```
[2022-04-27T00:05:04Z] python3: can't open file './colab/test_notebooks.py': [Errno 2] No such file or directory
```
> Fix path to samples/colab/test_notebooks.py.

- iree/test/e2e/matmul/BUILD
- iree/test/e2e/matmul/CMakeLists.txt
- iree/test/e2e/matmul/generate_e2e_matmul_tests.py
Right now only check Mali Valhall and NVIDIA Ampere on NVIDIA
GPUs.
> Enable matmul e2e tests for Vulkan

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
Implements part of the `TiledOpInterface` to lower Topk to loops through the `iree-linalg-ext-to-loops` pass.
Inner loop contents for Topk:
- Load current K values
- Apply provided block comparison for selecting TopK
- Check for equality between the N/K values and select the earliest index
- Choose and store the final K value
- Choose the loop carry values and yield.
> TopK LinalgExt Op Lowering to Loops with convert_to_loops.mlir test

- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-swiftshader/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake-bazel/linux/x86-turing/build.sh
- docs/developers/developing_iree/e2e_benchmarking.md
- docs/developers/get_started/cmake_options_and_variables.md
I noticed `MLIR_DEP_MODE` was mentioned on https://github.com/google/iree/issues/3843. That option no longer exists, but we still had references to it in our docs. Similar story for the TF/TFLITE/XLA options.
(Normally I'd go through history to find where those were removed / made obsolete, but I haven't done that in this case [yet])
> Clean up references to deleted CMake options.

- iree/compiler/Codegen/Dialect/LoweringConfig.td
- iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- iree/compiler/Codegen/LLVMCPU/Passes.cpp
- iree/compiler/Codegen/Passes.h
This pipeline is not used, and won't be used. We intend to vectorizes as
many ops as possible. In this context, we will apply second level of
tiling to avoid big vectors. The distribution level of tiling only tiles
three loops. This means that some dims are not tiled, which might result
in big tensors.
> Deprecate SingleTilingExpert pipeline.

- iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
Adds a lit test for the `vm.import.resolved` operation after converion to EmitC.
Support for converting the op to EmitC was added with google/iree@b006515.
> Add lit test for `vm.import.resolved`

- iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- iree/compiler/Codegen/Interfaces/BUILD
- iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- iree/compiler/Codegen/Interfaces/CMakeLists.txt
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtInterfaces.td
This commit provides the missing bufferizations for #9004.
Note: This implementation is largely copied from `mlir/lib/Dialect/Linalg/Transforms/BufferizableOpInterfaceImpl.cpp`.
> Support bufferization of linalg_ext.fft and reverse

- iree/compiler/Codegen/LLVMCPU/LLVMCPUCheckIRBeforeLLVMConversion.cpp
- iree/compiler/Codegen/LLVMCPU/test/check_ir_before_llvm_conversion.mlir
This also increases the limit to 32 KB. The default workgroup size is
64. There are cases that stack allocation sizes depend on workgroup
size, which produces 64x64xi64. Thus, 32 KB is a reasonable limit.
Fixes https://github.com/google/iree/issues/9020
> Improve stack allocation check to infer upper bound sizes.

- build_tools/benchmarks/common/android_device_utils.py
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_driver.py
- build_tools/benchmarks/common/benchmark_driver_test.py
- build_tools/benchmarks/common/linux_device_utils.py
- build_tools/benchmarks/common/linux_device_utils_test.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
Currently we don't have CPU microarchitecture in DeviceInfo, which is important when benchmarking on different CPUs.
On x86, we want to build benchmarks with specified `-mtune` for the target machine in order to utilize full features of the CPU (e.g. AVX512, instruction scheduling). Without CPU microarchitecture in DeviceInfo, the benchmark tool can't select the benchmark cases which are built for the target CPU.
To add CPU microarchitecture in IREE benchmark, we need to consider the items below:
1. The definition of `cpu_abi` and `cpu_microarch`.
2. How does the microarchitecture present in the benchmark suite?
3. How to present the microarchitecture in benchmark tool internally?
4. How to present the microarchitecture in the key of benchmark result? (the primary key of results in …
> [NFC] Add CPU microarchitecture to DeviceInfo

- build_tools/cmake/rebuild.sh
- build_tools/cmake/test.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader/build.sh
- build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-turing/build.sh
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/fuse-operands.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/tile-and-peel.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/tile.mlir
- llvm-external-projects/iree-dialects/test/iree_pydm/rtl/lit.local.cfg
* The ASan pipeline now includes llvm-external-projects builds+tests (`check-iree-dialects`)
* The ASan pipeline builds with asserts and the python bindings set to `OFF`, so I made some tweaks to tests that were passing only in debug builds or were depending on the python bindings
* The Turing build now reuses an existing script instead of duplicating that script's logic
Progress on https://github.com/google/iree/issues/8996
> Audit and fix inconsistencies in Kokoro build/test scripts.

- .github/workflows/advance_upstream_forks.yml
- .github/workflows/android_tflite_oneshot_build.yml
- .github/workflows/build_package.yml
- .github/workflows/copybara_fixup.yml
- .github/workflows/lint.yml
- .github/workflows/oneshot_candidate_release.yml
- .github/workflows/publish_website.yml
- .github/workflows/schedule_candidate_release.yml
- .github/workflows/validate_and_publish_release.yml
- docs/developers/debugging/releases.md
The policy we followed changed for this at some point, from allowing tagged releases to requiring specific commits: https://opensource.google/documentation/reference/github/services#actions
> When using a third-party action (one not hosted in a Google-managed org), a fixed version of the action MUST be used by [specifying a specific commit](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses), rather than a branch like "master", or a tagged release, which can be overwritten by any maintainer of the action. Docker images should always be run at a fixed version rather than "latest".
I searched each action for the commits we were using anyways (so not upgrading from v2 to v3, for example), but some drift may …
> Pin GitHub Action versions to specific commits, not tags.

- .github/CODEOWNERS
Missed this when reviewing https://github.com/google/iree/pull/9022, but these paths are absolute from the root of the repo, so just `/compiler/` won't trigger as expected.
Also add Ben back as the top level default (from back when `/iree/` covered `/iree/compiler/`)
> Fix absolute paths to compiler/ directories in CODEOWNERS.

- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
The helper function does not add a period on its own, so file names were looking like `module_mobilebert_squad_tosa_linked_llvm_system_wasm_wasm_32wasm` instead of `module_mobilebert_squad_tosa_linked_llvm_system_wasm_wasm_32.wasm`: https://github.com/google/iree/blob/e2f6c0f1deb47bee7c60e7ab37f771e935252f66/compiler/src/iree/compiler/Dialect/HAL/Target/TargetBackend.cpp#L253-L255
All other uses of this helper function already include the period, for example: https://github.com/google/iree/blob/e2f6c0f1deb47bee7c60e7ab37f771e935252f66/compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp#L288-L289 https://github.com/google/iree/blob/e2f6c0f1deb47bee7c60e7ab37f771e935252f66/compiler/src/iree/compiler/Dialect/HAL/Target/VMVX/VMVXTarget.cpp#L138-L139
> Fix LLVMAOTTarget file extensions for debug artifacts.

- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects-c/Dialects.h
- llvm-external-projects/iree-dialects/lib/CAPI/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/CAPI/Dialects.cpp
- llvm-external-projects/iree-dialects/python/IREEDialectsModule.cpp
This simplifies the use of the transform dialect in downstream python code.
> Expose and enable LinalgTransform pass registration.

- build_tools/buildkite/cmake/linux/x86_64/benchmark.yml
The comments shouldn't be posted on the merged comments.
> Fix post conditions in x86 benchmark pipeline

- build_tools/benchmarks/upload_benchmarks_to_dashboard.py
Right now we have two buildkite pipelines uploading benchmark
samples to Dana---one for Android targets and one for x86_64
CPUs. Each pipeline will try to create a new build for the
current landed commit. We need to allow overriding to make
sure both of them are accepted. (It should be the exact same
commit so no harm to override.)
> Fix dana uploading failure due to duplicated numbers

- compiler/src/iree/compiler/API/test/CMakeLists.txt
This makes IDE integration cleaner (e.g. VSCode with `"cmakeExplorer.suiteDelimiter": "/",`).
Before (test uses `-` instead of `/` as a delimiter):
After:
---
I went back and forth on the specific CMake functions used here (see the commit history), but decided to omit Bazel support and keep using base CMake functions (no IREE helpers) based on this comment: https://github.com/google/iree/blob/18b9df4ac41f7cbf86ec0e036771b39f9f3420f4/compiler/src/iree/compiler/API/CMakeLists.txt#L7-L15
> Use a consistent test name style for compile-mhlo-test.

- runtime/bindings/python/iree/runtime/CMakeLists.txt
- runtime/bindings/python/iree/runtime/scripts/iree_benchmark_module/__main__.py
- runtime/setup.py
> Add iree-benchmark-module to iree-runtime python package.

- runtime/bindings/python/iree/runtime/function_test.py
- runtime/bindings/python/iree/runtime/system_api_test.py
- runtime/bindings/python/iree/runtime/vm_test.py
- samples/colab/test_notebooks.py
This has been bugging me for a while because it adds no value and requires more deps to be installed.
Does not touch integrations/tensorflow since installing TF pulls absl-py along for the ride.
> Remove absl test and logging deps from Python unit tests.

- compiler/src/iree/compiler/Codegen/Common/GPUDistributeSharedMemoryCopy.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
Async copy can be used to form better software pipeline and reduce the pressure on register use in fp16 too.
> [CUDA] Allow async copy for fp16

- runtime/bindings/python/iree/runtime/array_interop_test.py
- runtime/bindings/python/iree/runtime/hal.cc
- runtime/bindings/python/iree/runtime/hal.h
- runtime/src/iree/hal/buffer.c
Since the device/allocator often lives for the life of whatever is being done, this was not being caught. But some Python uses were hitting it. Added a Python test to catch regressions at that level (which should also catch various Python ref-counting issues). This uses the `pybind11::keep_alive<>` facility, which I don't love, but was built for just this case. We may need to revisit the ownership when transferring outside of the current thread of control. I've left notes in hal.h on the present and potential future state.
Fixes #9033
> Makes buffers retain the backing device allocator.

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_vmvx_launch_configuration.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
A new pipeline is created because the default pipeline can not handle early bufferized kernels. This can be addressed when switching to use IREEComprehensiveBufferize in BufferizeCopyOnlyDispatchesPass. See https://github.com/google/iree/issues/9047 for more details.
This also adds missing materialization tests for VMVX target.
> Switch to use upstream comphrensive bufferization for all CPU kernels

- iree/tools/iree-benchmark-module-main.cc
- iree/tools/iree-check-module-main.cc
- iree/tools/iree-run-module-main.cc
- iree/tools/utils/trace_replay.c
- runtime/src/iree/testing/vulkan/iree-run-module-vulkan-gui-main.cc
We have a few tools that read from stdin by default. It's confusing when there is no difference in output between a correctly formatted tool invocation just taking a while (running benchmarks or compiling a program) compared to an invocation with a typo that is spinning waiting for input.
Some of these changes may be overly spammy, and https://github.com/google/iree/issues/5931 has other (complementary) suggestions on how to make these tools less error-prone.
---
I considered logging in the implementation of `iree_stdin_read_contents` itself (base/internal/file_io), but figured that each callsite can customize the message this way.
> Print whenever reading from stdin.

- iree/test/e2e/linalg_ext_ops/BUILD
- iree/test/e2e/linalg_ext_ops/CMakeLists.txt
- iree/test/e2e/linalg_ext_ops/top-k.mlir
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
In addition, resolves a bug where the return tensors were incorrectly using the input sizes for slicing instead of the output sizes.
> IREE LinalgExt TopK e2e Tests

- build_tools/benchmarks/post_benchmarks_as_pr_comment.py
- build_tools/buildkite/cmake/linux/x86_64/benchmark.yml
Escape the title before matching with the previous comment posts, so the `_` in the title won't cause the matching failed.
> Escape benchmark comment title before matching

- iree/test/e2e/linalg_ext_ops/BUILD
- iree/test/e2e/linalg_ext_ops/CMakeLists.txt
Disable e2e test while investigating vulkan failure.
> Disable TopK e2e test on Vulkan

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/pipeline_tests.mlir
There was correctness issues in vectorization on copy ops. There might be fixes from upstream, so we can't reproduce the issue. The commit adds the vectorization step back.
Fixes https://github.com/google/iree/issues/8579
> Add vectorization to CPUBufferOpsTileAndVectorizePipeline

- runtime/src/iree/base/status.c
For some reason on gcc 11, putting the [[nodiscard]] attribute after
`static` results in a parse error and attribute ignored warning. I
haven't looked into this further: I just swapped the order in the one
case where we have this.
Fixes #9025
> Move [[nodiscard]] before static.

- build_tools/cmake/iree_python.cmake
- build_tools/python_deploy/build_linux_packages.sh
- runtime/bindings/python/CMakeLists.txt
When the runtime path was flattened, the install locations were not
updated to line up. They were also going through a really old macro that
had outlived its usefulness. Just added corrected, explicit install()
calls. Also fixed a typo in the build_linux_packages.sh script noticed
when trying to build just one python version to test.
It is now possible to test/repo this exactly as the CI does:
```
override_python_versions=cp39-cp39 packages=iree-runtime
./build_tools/python_deploy/build_linux_packages.sh
pip install
build_tools/python_deploy/wheelhouse/iree_runtime-0.dev0+4020b408be725b54b0266a2a9c3388b5c704ced4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
python runtime/bindings/python/tests/array_interop_test.py
iree-run-module
```
Fixes #9108
> Fix release runtime package.

- docs/website/docs/extensions/index.md
- samples/colab/low_level_invoke_function.ipynb
https://github.com/google/iree/pull/9094 used a regex on .mlir files, but we have other types of files that include MLIR snippets. This updates a Colab notebook (.ipynb) and a page on our website (.md). There are still a few other references in Markdown files (and maybe other types of files), but I think these are the important ones to keep up to date.
The Colab update should fix this buildkite failure: https://buildkite.com/iree/iree-samples/builds/343#41eef0d9-0959-493d-8897-f53e939e5d32
> Fix a few remaining unqualified uses of func.func.

- runtime/bindings/python/iree/runtime/system_api.py
`File "/home/runner/work/iree/iree/runtime/bindings/python/iree/runtime/system_api.py", line 291, in instance: No attribute '_instance' on SystemContext [attribute-error]`
> Fix pytype attribute-error in system_api.py.

- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.h
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- runtime/src/iree/schemas/bytecode_module_def.fbs
- runtime/src/iree/vm/bytecode_module.c
- runtime/src/iree/vm/bytecode_module_impl.h
This allows for minor version bumps for backward-compatible changes
(allowing an older vmfb to be loaded on a newer runtime) and major
version bumps (disallowing older vmfbs from being loaded on a newer
runtime).
This first version 0.0 allows all existing modules to be loaded.
Future bumps will result in errors like:
```
E D:\Dev\iree\runtime\src\iree\vm\bytecode_module.c:209: INVALID_ARGUMENT;
bytecode version mismatch; runtime supports 0.0, module has 0.1
```
Note that this only versions the bytecode - the module itself is already
versioned with flatbuffers and doesn't need any version numbers. This
will also allow us to embed bytecode in other containers (ELF/etc) and
reuse the same versioning information.
> Adding simple bytecode versioning.

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.cpp
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.h
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Verifiers.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- iree/test/e2e/matmul/generate_e2e_matmul_tests.py
- Add Pipelinedepth to translation_info
- Update the verifier and kernelconfig to disallow pipelining when first level tile K is same as matmul reduction dimension size
- Modify lit tests to account for default of softwarepipelinedepth=4
> Add software pipeline depth to lowering config

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_x86_64_launch_configuration.mlir
There is an order for doing padding correctly:
1. Tile parallel loops
2. Pad operations in top-down order (i.e., topology order) for all parallel dims.
3. Tile reduction loops
4. Pad operations for all reduction dims. (In IREE's use case, there is only one operation that has reduction loops.)
Specifying the operation to pad is not easy today. We should have better
scheduling to do it. Either in transform dialect approach or creating a
new pass. This PR temporarily disables padding for other cases (e.g.,
matvec, batch_matmul, etc) because IREE puts more focus on matmul cases
for now.
> Only enable padding for linalg.matmul cases.

- compiler/src/iree/compiler/Codegen/Common/InsertDistributionInfoPass.cpp
- compiler/src/iree/compiler/Codegen/Common/SetNumWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/insert_distribution_info.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectExtensions/TransformDialectExtensions.cpp
- compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp
- compiler/src/iree/compiler/Codegen/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/TransformInterpreter.cpp
Since this pass changes the `hal.executable.entry_point`, it should
work on `hal.executable.variant` ops (instead of `func.func`) ops it
is today.
> Make `InsertDistributionInfo` operate on `IREE::HAL::ExecutableVariantOp`

- CMakeLists.txt
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- build_tools/third_party/llvm-project/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/IR/BUILD
- compiler/src/iree/compiler/Dialect/Flow/IR/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/IR/PartitionableLoopsInterface.cpp
This change tries to import the `LinalgStructuredOps.cpp.inc` from LLVM instead of keeping a copy in IREE. It will help us avoid #9036 in the future.
There is a compatibility issue between IREE and LLVM cmake system. The tablegen libraries in LLVM are only defined as custom targets and can not be used in `target_link_libraries`, so adding those targets to the `DEPS` of `iree_cc_library` breaks the build as the rule tries to link them.
I'm not sure about the best solution for this. In IREE, we can use `add_dependences` to add LLVM tablegen libraries but it will break the mapping between bazel and cmake, makes it harder to maintain. Another option is defining those targets as [Interface Libraries](https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries) in the LLVM …
> Include LinalgStructuredOps headers from LLVM

- benchmarks/README.md
- build_tools/benchmarks/README.md
The links need to refer from the repo root.
> Fix relative links in the benchmark docs.

- build_tools/benchmarks/post_benchmarks_as_pr_comment.py
Since we upload the benchmark results for two platforms separately now, the build exists in the dashboard doesn't mean the related benchmark results have been uploaded for that build. This causes the problem where some result posts can't find the previous results to compare to (e.g., https://github.com/google/iree/pull/9096#issuecomment-1124597853).
The change improves the logic to check if there are any matched records from the dashboard and skips to the next build if not.
The eventual goal is only uploading results from a single pipeline, but this is still an enhancement.
> Improve the detection of previous benchmark

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_fusion.mlir
Current heuristic to create dispatch regions has checks to fuse
producer with consumer only when the producer has a single use. This
is pessimizing. The only real requirement is that the consumer
dominates all the producers users. Use dominance info to relax this
requirement.
All the models we track currently though dont seem to benefit with
this change (they dont degrade either). The MobileBertInt8 model has
number of dispatches reduce from  1520 -> 1496.
> Allow dispatch region formation to fuse producer and consumer when producer has multiple uses.

- build_tools/buildkite/agent/configs/orchestration.cfg
- build_tools/buildkite/agent/hooks/README.md
- build_tools/buildkite/agent/hooks/pre-bootstrap-trusted-agent.py
This includes a hook for the trusted agents to limit which pipelines
and plugins they will use. The plan for now is to just deploy these
configs manually, but I think it's useful to have them checked in. Note
that I've switched to slightly "trusted" and "untrusted" naming for the
security levels, which I think is clearer.
Tested: Copied the hook to the trusted orchestration agent and the
build passes: https://buildkite.com/iree/presubmit/builds/113
> Check in configuration files for Buildkite agents

- compiler/src/iree/compiler/Codegen/Common/GPUDistributeSharedMemoryCopy.cpp
- compiler/src/iree/compiler/Codegen/Common/RemoveTrivialLoops.cpp
- compiler/src/iree/compiler/Codegen/Common/RewriteLinalgDestructiveUpdatesPass.cpp
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.h
- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/convert_to_llvm.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/convert_to_nvvm.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/convert_to_rocdl.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndPromote.cpp
- compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.h
The `func.func` code within functions not entry point were treated as
dynamically legal. This requirement is legacy. Dropping it.
> Remove legacy code that didnt lower code for `func.func` that arent public

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
The commit removes unneeded option. They are no longer needed because
CPU codegen is using upstream bufferization.
> Convert all kernels to destination passing style by default.

- build_tools/buildkite/pipelines/fragment/bootstrap-trusted.yml
- build_tools/buildkite/pipelines/fragment/bootstrap-untrusted.yml
- build_tools/buildkite/scripts/update_pipeline_configurations.py
Apparently when interpolated as the default, variables are typed as
strings, which is a bit confusing to me. We were getting
[422 errors](https://buildkite.com/iree/postsubmit/builds/412) in
the Postsubmit pipeline, which helpfully didn't include any error
message. I was able to get a more helpful message by trying to manually
update the steps in the UI.
Tested: Ran the API call to update the pipeline manually.
> Remove literal interpolation in Buildkite bootstrap pipeline

- build_tools/buildkite/pipelines/fragment/bootstrap-trusted.yml
- build_tools/buildkite/pipelines/fragment/bootstrap-untrusted.yml
Now this is
[failing](https://buildkite.com/iree/postsubmit/builds/413) when the
pipeline gets *uploaded* via `buildkite-agent pipeline upload`
whereas it wasn't before https://github.com/google/iree/pull/9208
#testinprod
> Quote interpolated string

- build_tools/buildkite/pipelines/untrusted/unregistered.yml
- build_tools/buildkite/scripts/common/buildkite_pipeline_manager.py
- build_tools/buildkite/scripts/common/buildkite_utils.py
- build_tools/buildkite/scripts/wait_for_pipeline_success.py
This introduces a pipeline that can be used to run unregistered
pipeline configuration files on presubmit. The pipeline files still
have to come from the main repository.
> Support running unregistered pipelines on presubmit

- build_tools/buildkite/pipelines/fragment/bootstrap-trusted.yml
- build_tools/buildkite/pipelines/fragment/bootstrap-untrusted.yml
- build_tools/buildkite/scripts/common/buildkite_pipeline_manager.py
- build_tools/buildkite/scripts/common/buildkite_utils.py
- build_tools/buildkite/scripts/set_buildkite_env.sh
- build_tools/buildkite/scripts/simulate_buildkite.sh
- build_tools/buildkite/scripts/update_pipeline_configurations.py
I was tearing my hair out trying to figure out what's going wrong here.
There are limitations around setting teams in the Buildkite REST API,
which is pretty annoying. The best we can do is add the trusted bot to
IREE team and then give IREE team full access. The team needs some kind
of access to be able to trigger retries and such.
Also added some quality of life improvements to the scripting.
> Set appropriate permissions when creating pipeline

- build_tools/buildkite/README.md
- build_tools/buildkite/pipelines/untrusted/unregistered.yml
- build_tools/buildkite/scripts/update_pipeline_configurations.py
I have a grumpy email thread with Buildkite support, but setting
visibility and team access through the REST API is basically broken.
This works around it, including documenting the manual steps that must
be taken.
> Adapt for inability to set pipeline visibility

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.cpp
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
We expect users to generate attributes in LoweringConfigAttr and
TranslationInfoAttr. This reduces maintenance work because we don't have
to update these builders when there are new attributes. We only have to
maintain the builders for LoweringConfigAttr and TranslationInfoAttr.
> Delete unneeded CompilationInfoAttr builders.

- build_tools/embed_data/generate_embed_data_main.cc
We had a user [asking about this on Discord](https://discord.com/channels/689900678990135345/689957613152239638/976903741116678194). They were trying to load a resnet50 model (~90MB source file), which was hitting this limit (~100MB).
> Improve error message in generate_embed_data_main.

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUMultiBuffering.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/vector_to_gpu.mlir
This path is still disable by default as it would regress performance.
Once all the patches land and we get better performance this will be
enabled by default and the wmma path can be removed.
> [LLVMGPU] Add path to use mma.sync op

- .github/workflows/process_opened_issues.yml
We're trialing using a [master project](https://github.com/orgs/google/projects/20) (not yet publicly visible) for issue tracking/organization. This workflow will automatically add issues to the project so that early adopters don't have to do this manually for every issue.
I tested this successfully on my fork. However, we could run into issues with the `github_token`.
> Add workflow to add new issues to the IREE GitHub project

- compiler/src/iree/compiler/API/python/CMakeLists.txt
- runtime/bindings/python/CMakeLists.txt
- runtime/setup.py
It turned out that this not working was a comedy of errors. Verified from both the build directory and a clean build that the binaries are now included. I will enable a test in the validate releases script after tomorrow's build.
Fixes #9231
> Fix install of Python tool binaries in iree-runtime package.

- compiler/src/iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/convert_mhlo_to_linalg_ext.mlir
- integrations/tensorflow/test/iree_tf_tests/math/llvmaot__top_k.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__top_k.run
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
Maps a CHLO TopK To LinalgExt TopK. Additional steps during the conversion: 
- `chlo::topk` always computes `k` along the final dimension. `k` is set to the rank for `linalg_ext::topk`
- an input indices tensor is to accompany the input values is generated using a `linalg::generic` loop
- Output tensors for values and indices are initialized and filled with default values
- The `linalg_ext::topk` region is defined for a max k comparison
> Convert CHLO TopK To LinalgExt TopK

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
- docs/website/docs/building-from-source/android.md
- docs/website/docs/building-from-source/getting-started.md
This argument is new since CMake 3.20, and we require at least CMake 3.21 now. Changing directories can be a source of confusion for users, so this changes some guides to stay in the repo root and be explicit with each command.
Our other uses in scripts interact with the build directory in other ways (such as "building" `check-iree-dialects` or running TF lit tests under Python), so I left them unchanged.
> Use `ctest --test-dir` instead of `cd` in a few places.

- compiler/src/iree/compiler/Codegen/Common/RemoveTrivialLoops.cpp
- compiler/src/iree/compiler/Codegen/Common/test/remove_trivial_loops.mlir
The workgroup count is set to zero when we're not able to infer the bounds.
Fixes https://github.com/google/iree/issues/9244
> Add checks for unknown workgroup count when inferring boundaries.

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/TransformInterpreter.cpp
TransformState takes the region containing the top-level transform operation as the first argument. This was not supplied correctly when the transform IR lives in a separate file with the top-level payload IR region being used instead. Fix it.
> Create TransformState correctly

- build_tools/buildkite/agent/configs/cpu.cfg
- build_tools/buildkite/pipelines/untrusted/build-runtime-cmake.yml
The name build conflicts with the existing build queue for our legacy
Buildkite pipelines, which means these agents are always getting sent
the old jobs. It's also somewhat of a misnomer, since these agents will
also be getting test jobs. I think "cpu" correctly captures the aspect
of these agents that is not captured in other tags (like os) or
features (like priority), which is that they are intended for tasks that require large amounts of CPU. When we set up GPU tests, the agents
would analogously be in the "gpu" queue.
> Switch the standard agent queue to be called "cpu"

- experimental/rocm/CMakeLists.txt
- experimental/rocm/event_semaphore.c
- runtime/src/iree/base/internal/wait_handle.c
- runtime/src/iree/base/internal/wait_handle.h
- runtime/src/iree/hal/cuda/CMakeLists.txt
- runtime/src/iree/hal/cuda/event_semaphore.c
- runtime/src/iree/hal/local/BUILD
- runtime/src/iree/hal/local/CMakeLists.txt
- runtime/src/iree/hal/local/sync_semaphore.c
- runtime/src/iree/hal/local/task_queue.c
- runtime/src/iree/hal/local/task_semaphore.c
- runtime/src/iree/hal/semaphore.c
- runtime/src/iree/hal/semaphore.h
- runtime/src/iree/hal/utils/BUILD
- runtime/src/iree/hal/utils/CMakeLists.txt
- runtime/src/iree/hal/utils/semaphore_base.c
- runtime/src/iree/hal/utils/semaphore_base.h
- runtime/src/iree/hal/utils/semaphore_base_test.cc
- runtime/src/iree/hal/vulkan/BUILD
- runtime/src/iree/hal/vulkan/CMakeLists.txt
- runtime/src/iree/hal/vulkan/native_semaphore.cc
This is a roll-up of tweaks/fixes and the groundwork for future submission management changes. The new base semaphore type helps implementations manage timepoint tracking and notification in a uniform way.
The tracking type is not part of the public API and only exposed for HAL implementations; this isn't great and may be cleaned up in the future by abstracting out timepoint logic into the semaphore vtable. Landing as-is to get out of some serious design paralysis.
There are some optimization opportunities but they'll be easier to analyze and prioritize once the higher-level layers are implemented using the tracking.
> HAL semaphore improvements and timepoint tracking support.

- experimental/rocm/rocm_device.c
- runtime/src/iree/hal/cuda/cuda_device.c
- runtime/src/iree/hal/device.c
- runtime/src/iree/hal/device.h
- runtime/src/iree/hal/local/sync_device.c
- runtime/src/iree/hal/local/task_device.c
- runtime/src/iree/hal/local/task_semaphore.c
- runtime/src/iree/hal/local/task_semaphore.h
- runtime/src/iree/hal/vulkan/native_semaphore.cc
- runtime/src/iree/hal/vulkan/native_semaphore.h
- runtime/src/iree/hal/vulkan/vulkan_device.cc
This allows for devices to report whether a semaphore is usable for
host- and device-side waits and signals. When we have semaphores from
differing devices or HAL implementations being used in submissions this
will allow us to change scheduling behavior (optimistically always doing
device-side waits/signals).
> Adding iree_hal_device_query_semaphore_compatibility.

- compiler/src/iree/compiler/Codegen/TransformDialectExtensions/BUILD
- compiler/src/iree/compiler/Codegen/TransformDialectExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/TransformDialectExtensions/TransformDialectExtensions.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectExtensions/TransformDialectExtensions.h
- compiler/src/iree/compiler/Codegen/TransformDialectExtensions/TransformDialectExtensionsOps.td
This allows dropping C++ ops in favor of the standard MLIR auto-generation tools.
> Add Tablegen support for TransformDialectExtensions

- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/ConvertMHLOToLinalgExt.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.td
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/roundtrip.mlir
- samples/simple_embedding/BUILD
- samples/simple_embedding/CMakeLists.txt
* Reset third_party/llvm-project: aed179f5f557664d6deb26ef6fdc6aa944af41af (2022-06-03 15:19:09 +0200): [lldb] [Process/FreeBSD] Do not send SIGSTOP to stopped process
* Update MHLO and TensorFlow
* MHLO: cc46221a504bd56811b76ba7fb89ef618bdf5ba0
* TensorFlow: eed69a9f9ba56ccfa9debae1b4dbc2a9cf9706fa
* Fix mhlo.scatter variadic operand/result APIs
* Rename `transform.structured.decompose` to avoid collision
> Integrate llvm-project at aed179f5f557664d6deb26ef6fdc6aa944af41af

- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
Since pooling op may have a dummy allocation we need to check for
dynamic allocation after lower of linalg to loops.
> [LLVMGPU] Fix dynamic shape pooling op code generation

- runtime/src/iree/hal/string_util.c
- runtime/src/iree/hal/string_util.h
- runtime/src/iree/hal/string_util_test.cc
- runtime/src/iree/tools/utils/vm_util.cc
- runtime/src/iree/tools/utils/vm_util.h
- tools/iree-benchmark-module-main.cc
- tools/iree-run-module-main.cc
Raw binary data read from a file can now be used to initialize buffer
view contents. No interpretation is done on the data. The shape and
element type information is still required. Works in all tools using the
VM utils (iree-run-module, iree-benchmark-module, iree-run-mlir).
Example:
```
iree-benchmark-module ... --function_input=4x2xi32=@some/file.bin
```
> Adding support for reading binary files in tool --function_input=.

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/test/BUILD
- compiler/src/iree/compiler/Dialect/Flow/IR/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/IR/test/resolve_dim_ops.mlir
> Account for rank-reduced version of `flow.dispatch.tensor.load` when resolving `tensor.dim` ops.

- build_tools/cmake/iree_copts.cmake
CMAKE_SOURCE_DIR is the top level of the source tree, which is _not_ iree/CMakeLists.txt when IREE is included by another project. In my case, I'm trying to have https://github.com/google/iree-samples fetch the primary project as part of moving a C++ sample into that repo (https://github.com/google/iree/issues/8011).
> Anchor iree.natvis path on IREE_ROOT_DIR for downstream builds.

- build_tools/buildkite/pipelines/untrusted/unregistered.yml
- build_tools/buildkite/scripts/common/buildkite_pipeline_manager.py
This will allow triggered builds to refer back to their "parents".
Also standardizes IREE's custom buildkite env vars to start with
"IREE_BUILDKITE"
> [Buildkite] Pass through information about triggering build

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/DistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/InsertDistributionInfoPass.cpp
- compiler/src/iree/compiler/Codegen/Common/SetNumWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Codegen/Transforms/Transforms.cpp
- compiler/src/iree/compiler/Codegen/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Tiling.cpp
IREE uses tile and distribute to distribute a dispatch to
workgroups. In this PR, a new way to distribute is added distributes
the work within an undistributed dispatch by splitting distributing
the result computation across workgroups. The slice is then propageted
to the producers recursively to produce only the values needed to
compute the slice mapped to a workgroup.
> Add a pass to distribute the result computation to workgroups.

- runtime/src/iree/hal/vulkan/vulkan_device.cc
- runtime/src/iree/hal/vulkan/vulkan_driver.cc
These features are needed to suppress validation warnings of:
```
vkCreateDevice: Attempting to create a VkDevice from a VkPhysicalDevice
which is from a portability driver without the
VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit in the
VkInstanceCreateInfo flags being set and the
VK_KHR_portability_enumeration extension enabled. In future versions of
the loader this VkPhysicalDevice will not be enumerated.
```
> [vulkan] Enable necessary portability features on Apple platforms

- build_tools/buildkite/agent/hooks/environment-trusted-agent.sh
- build_tools/buildkite/agent/hooks/environment-untrusted-agent.sh
- build_tools/buildkite/pipelines/trusted/postsubmit.yml
- build_tools/buildkite/pipelines/trusted/presubmit.yml
- build_tools/buildkite/pipelines/untrusted/test-runtime-cmake.yml
- build_tools/buildkite/scripts/common/buildkite_pipeline_manager.py
- build_tools/buildkite/scripts/update_pipeline_configurations.py
This avoids needing to do this in every step. So the agents will always
have their tokens and annotations will be step-specific by default.
> [Buildkite] Move the setting of environment variables to environment agent hook

- docs/developers/developing_iree/sanitizers.md
The wording for TSan assumes that #8966 is merged.  (EDIT June 2022: #8966 has been abandoned, the phrasing here is updated accordingly).
> Update sanitizers docs.

- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- build_tools/cmake/iree_cc_test.cmake
- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_lit_test.cmake
- build_tools/cmake/iree_native_test.cmake
- build_tools/cmake/iree_python.cmake
- runtime/src/iree/hal/drivers/vulkan/util/BUILD
- runtime/src/iree/hal/drivers/vulkan/util/CMakeLists.txt
- tests/e2e/models/BUILD
- tests/e2e/models/CMakeLists.txt
Included a couple of changes:
- using bazel's `timeout` arg instead of `size`
- update bazel_to_cmake_converter.py to to set TIMEOUT on cmake files
- update the appropriate CMAKE files for above
- updated cmake files to plumb TIMEOUT down to setting CTEST's timeout property
- set default TIMEOUT value on tests to 60 (shortest bazel timeout)
> Added timeout to testing infrastructure

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
These are running on devices that we have not yet updated CMake on, so the `--test-dir` flag is ignored, resulting in
```
Test project /var/lib/buildkite-agent/builds/IREE-LAB-RPI4-Pixel6Pro-1-ray-1008524145-1/iree/iree-test-android
No tests were found!!!
```
(full logs: https://buildkite.com/iree/iree-test-android/builds/6350)
Partial revert of https://github.com/google/iree/pull/9253, noticed at https://github.com/google/iree/pull/9372#discussion_r891685626. It's a shame that `No tests were found!!!` does not come with a failure exit code :/
> Revert ctest --test-dir change from Android pipeline.

- CMakeLists.txt
Allows to clone fewer submodules if (cross-)compiling for a target that
doesn't involve the HAL Vulkan driver.
> Dont' add `vulkan_headers` submodule by default

- build_tools/cmake/iree_benchmark_suite.cmake
- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_hal_cts_test_suite.cmake
- build_tools/cmake/iree_trace_runner_test.cmake
Define a custom target `${PACKAGE_NAME}_${NAME}` for the VMFB module in `iree_bytecode_module`.
Fix #9254.
> Define module target in iree_bytecode_module

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DumpDispatchGraph.cpp
It is possible that there is no defining operation for an Op.
> check if the def op is null

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/generalize.mlir
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/roundtrip.mlir
These have been upstreamed to LLVM, drop local equivalents.
> Use upstream decompose and generalize transform ops

- runtime/src/iree/hal/drivers/vulkan/vulkan_device.cc
According to ARM Mali GPU doc
https://developer.arm.com/documentation/101897/0200/cpu-overheads/command-pools-for-vulkan:
> Command pools do not automatically recycle memory from deleted command
> buffers unless created with the RESET_COMMAND_BUFFER_BIT flag. Pools
> without this flag do not recycle their memory until the application
> resets the pool.
This helps to address a memory leaking issue in `iree-benchmark-module`
where we run many repetitions/iterations of the model with the same
Vulkan device. The command pool's lifetime is associated with the
device; so it ends up we never release the resources occupied by
previous command buffers until the whole program exit.
This is not an issue for other GPUs (e.g., Adreno). However,
we will need this flag eventually anyway, given that ML …
> [vulkan] Create command pools with CREATE_RESET_COMMAND_BUFFER_BIT

- experimental/rocm/rocm_driver.c
- runtime/src/iree/hal/BUILD
- runtime/src/iree/hal/CMakeLists.txt
- runtime/src/iree/hal/cts/driver_test.h
- runtime/src/iree/hal/device.h
- runtime/src/iree/hal/driver.c
- runtime/src/iree/hal/driver.h
- runtime/src/iree/hal/driver_registry.c
- runtime/src/iree/hal/driver_registry.h
- runtime/src/iree/hal/drivers/cuda/cuda_driver.c
- runtime/src/iree/hal/drivers/local_sync/sync_driver.c
- runtime/src/iree/hal/drivers/local_task/task_driver.c
- runtime/src/iree/hal/drivers/vulkan/vulkan_driver.cc
- runtime/src/iree/tools/utils/vm_util.cc
- runtime/src/iree/tools/utils/vm_util.h
- runtime/src/iree/tools/utils/vm_util_test.cc
- tools/android/run_module_app/src/main.cc
- tools/iree-benchmark-module-main.cc
- tools/iree-check-module-main.cc
- tools/iree-run-mlir-main.cc
- tools/iree-run-module-main.cc
This adds the plumbing for creating devices by path specs in addition
to creating them by driver-specific IDs. A helper was also added to
create by ordinal to simplify tools that want to expose devices in a
canonical form with other driver-specific tools.
The creation methods also gain the ability to pass in key-value pair
parameters. Drivers can now use these parameters to refine device
selection and configure the devices during creation. The entire driver
layer is optional so the extra string handling here is only in cases that
desire it, and for devices that have no properties (like local-sync) it
doesn't add a cost.
A helper that parses a canonical device URI into the components for
create_device_by_path was added as iree_hal_driver_create_device_by_uri
and should be used by most …
> Adding iree_hal_driver_create_device_by_path & co.

- samples/vision_inference/README.md
- samples/vision_inference/convert_image.py
* Mention the C sample in the iree-samples repo
* Fix test commands :P
* Resize to 28x28 in python script, rename to just `convert_image.py`
Part of https://github.com/google/iree/issues/9374
> Update docs in samples/vision_inference.

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/outline_dispatch_regions.mlir
This completes the plumbing as the region is already supported after
outlining.
I hate the syntax, but until we settle on where distribution happens
and potentially split the op into distributed/non-distributed variants
(like the old flow.dispatch.region we had) this will suffice.
> Adding an optional workgroup count region to flow.dispatch.workgroups.

- build_tools/benchmarks/CMakeLists.txt
- build_tools/benchmarks/collect_compilation_statistics.py
- build_tools/benchmarks/collect_compilation_statistics_test.py
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_driver.py
- build_tools/benchmarks/common/benchmark_driver_test.py
- build_tools/benchmarks/common/benchmark_suite.py
- build_tools/benchmarks/common/benchmark_suite_test.py
Inspired by #9167, this tool parses the zip info of vmfb and the ninja build log to get the binary size (dispatch libraries) and the module compilation time.
There are 4 sizes to be retrieved:
1. Module file size
2. VM bytecode size in the module.
3. Const binary size in the module.
4. Total size of all dispatch libraries in the module.
The class `BenchmarkCase` now also parses the model name into the name and tags.
> Add tool to collect compilation statistics

- build_tools/cmake/iree_configure_testing.cmake
This behavior, introduced in https://github.com/google/iree/pull/9405,
is broken on Android, where we don't do this temp directory
registration:
https://buildkite.com/iree/iree-test-android/builds/6452
Triggered a run of the android test pipeline on this PR:
https://buildkite.com/iree/iree-test-android/builds/6458
> Fix case where there are no test temp directories to create
