- benchmarks/TFLite/android-adreno.cmake
- benchmarks/TFLite/android-arm64-v8a.cmake
- benchmarks/TFLite/android-mali.cmake
- benchmarks/TFLite/linux-riscv.cmake
- benchmarks/TFLite/linux-x86_64.cmake
- build_tools/bazel/iree_bytecode_module.bzl
- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- build_tools/cmake/iree_benchmark_suite.cmake
- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/cmake/iree_c_module.cmake
- build_tools/cmake/iree_hal_cts_test_suite.cmake
- build_tools/cmake/iree_microbenchmark_suite.cmake
- runtime/src/iree/vm/BUILD
- runtime/src/iree/vm/CMakeLists.txt
- runtime/src/iree/vm/test/BUILD
- runtime/src/iree/vm/test/CMakeLists.txt
- runtime/src/iree/vm/test/emitc/CMakeLists.txt
All uses of `iree-translate` were replaced with `iree-compile` and the `iree-translate` tool was removed. We still have some "translation passes" and "translation info" names in the compiler, but most language can be updated to "compile" and "compilation".
I'm separately planning on updating uses of `--iree-mlir-to-vm-bytecode-module` and related to flags to use the newer `--output-format` and `--compile-mode` flags (or just trusting the default values).
> Rename "translate" to "compile" across build systems.

- build_tools/bazel/iree_c_module.bzl
- runtime/src/iree/vm/BUILD
- runtime/src/iree/vm/test/emitc/BUILD
- samples/emitc_modules/BUILD
Also adds iree_c_module bazel rule mirroring CMake side. This does not
add the automatic generation to bazel_to_cmake.
Fixes #7345
> Add BUILD file for vm/test/emitc and samples/emitc_modules

- runtime/src/iree/hal/drivers/cuda/cuda_driver.c
- runtime/src/iree/hal/drivers/cuda/dynamic_symbol_tables.h
v2 was added in 11.4 (June 2021). We'll want to support v2 but there's
not enough dynamic symbol goo in the CUDA driver to handle fallbacks
yet and I'm not sure anyone is using MIG yet (what v2 is for).
> Switching from cuDeviceGetUuid_v2 to cuDeviceGetUuid for older CUDA.

- build_tools/bazel/iree_c_module.bzl
- build_tools/cmake/iree_c_module.cmake
- runtime/src/iree/vm/test/emitc/BUILD
- runtime/src/iree/vm/test/emitc/CMakeLists.txt
- samples/emitc_modules/BUILD
- samples/emitc_modules/CMakeLists.txt
This matches how iree_bytecode_module always passes `--output-format=vm-bytecode`.
Follow-up to https://github.com/google/iree/pull/9431
> Always pass `--output-format=vm-c` in iree_c_module.

- CMakeLists.txt
- runtime/src/iree/hal/drivers/CMakeLists.txt
Fixes https://github.com/google/iree/issues/8196
The [`ConstEval`](https://github.com/google/iree/tree/main/compiler/src/iree/compiler/ConstEval) compiler component unconditionally depends on VMVX and the `local-task` HAL driver. The compiler needs _some_ reference implementation available, but we still want to be able to prune the set of built and automatically registered drivers in the runtime.
This is one solution we liked - if the compiler is enabled, force its requirements enabled too.
> Always add local_task and VMVX if building the compiler.

- runtime/src/iree/base/string_view.c
- runtime/src/iree/base/string_view.h
- runtime/src/iree/base/string_view_test.cc
- runtime/src/iree/hal/drivers/cuda/cuda_driver.c
- runtime/src/iree/hal/drivers/vulkan/dynamic_symbol_tables.h
- runtime/src/iree/hal/drivers/vulkan/vulkan_driver.cc
Now Vulkan devices can be specified either by ordinal (`--device=vulkan://0`) or deviceUUID (`--device=vulkan://754d9ae2-8df5-f8e3-3502-182434a12876`). The UUIDs are _mostly_ stable and on nvidia parts match between Vulkan and CUDA.
> Allowing deviceUUIDs to be used in Vulkan device paths.

- .github/workflows/build_package.yml
The tarball can be used to bypass the host binary build in the
cross-compilation process.
> Add Linux iree-dist artifact back to the release asset

- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
A pattern (https://reviews.llvm.org/D127582) was added upstream to
convert math.ctlz to GLSL FindUMsb instructions.
> [spirv] Drop math.ctlz expansion given we have native conversion

- .github/workflows/lint.yml
We have to have some pinned version and there isn't really a strong
reason it has to be the same as our oldest supported version of clang.
Most devs have more recent clang versions, so the later version is
likely to be closer to what people have locally. clang-format-12 is
the newest version installed by default on the GitHub managed runners,
so it also saves us some apt nonsense.
Fixes https://github.com/google/iree/9154
> Use clang-format-12 in presubmits

- compiler/pyproject.toml
- runtime/bindings/python/iree/runtime/build_requirements.txt
- runtime/pyproject.toml
This is the version required by MLIR:
- https://github.com/llvm/llvm-project/blob/main/mlir/python/requirements.txt
- https://github.com/llvm/llvm-project/blob/68df5c5c13/mlir/cmake/modules/MLIRDetectPythonEnv.cmake#L43
Having installed from the current requirements.txt, I get an error. This
sort of thing is exactly why I think we should have CI use the oldest
versions of things that we claim to support. The current Dockerfile
installs 2.9.0. This version was bumped upstream
[5 months ago](https://github.com/llvm/llvm-project/commit/89a92fb3ba)
and we only just noticed, which means our getting started guide for new
users has been broken that entire time.
I will send a follow-up to downgrade the Dockerfile, though i expect
that may be more contentious.
> Bump pybind requirement to 2.8.0

- .github/workflows/lint.yml
clang-format-12 is only installed on the Ubuntu 20.04 containers, not
the 18.04 we are using. I thought presubmit would catch this, but looks
like git-clang-format short-circuits if it doesn't detect any relevant
changes. 
Reverts google/iree#9473
> Revert "Use clang-format-12 in presubmits"

- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
- build_tools/docker/utils.py
- build_tools/scripts/utils.py
- compiler/src/iree/compiler/API/python/iree/compiler/tools/binaries.py
- compiler/src/iree/compiler/API/python/iree/compiler/tools/core.py
- compiler/src/iree/compiler/API/python/iree/compiler/tools/tf.py
- compiler/src/iree/compiler/API/python/iree/compiler/tools/tflite.py
- compiler/src/iree/compiler/API/python/iree/compiler/tools/xla.py
- integrations/tensorflow/iree-dialects/python/iree/compiler/dialects/iree_pydm/importer/util.py
- integrations/tensorflow/python_projects/iree_tf/iree/tf/support/module_utils.py
- integrations/tensorflow/python_projects/iree_tf/iree/tf/support/tf_test_utils.py
- integrations/tensorflow/python_projects/iree_tf/iree/tf/support/trace_utils.py
- llvm-external-projects/iree-dialects/python/iree/compiler/dialects/iree_pydm/importer/util.py
- runtime/bindings/python/iree/runtime/system_api.py
This commit upgrades the python scripts to use the following features
supported since python 3.7:
- postponed type annotations
- `dataclass`
- `capture_output=` and `text=` in some `subprocess` functions
This closes https://github.com/google/iree/issues/4131
> Apply code upgrades for python >= 3.7 

- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUCheckIRBeforeLLVMConversion.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/check_ir_before_llvm_conversion.mlir
The flag is meant for quick triaging. The default value is expected to
be 32KB.
Issue #9469
> Add a flag for controlling the max stack allocation limit allowed on CPU backend

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
We currently cannot promote those kind of operations as we don't
distribute more than 3 dimensions. Skipping promotion allows to avoid a
crash.
> [LLVMGPU] Fix bug when trying to promote 4d contraction op

- runtime/bindings/python/tests/vm_test.py
- runtime/src/iree/base/tracing.cc
- runtime/src/iree/base/tracing.h
- runtime/src/iree/hal/local/loaders/vmvx_module_loader.c
- runtime/src/iree/vm/context.c
- runtime/src/iree/vm/context.h
- runtime/src/iree/vm/invocation.c
Currently off by default but our instrumentation has been updated to support it.
When enabled this makes `iree_vm_context_t` appear alongside OS threads in the Tracy UI:
This will make tracking multiple overlapping contexts much easier, especially when running on fiber loops in the task system.
> Adding support for TRACY_FIBERS.

- compiler/src/iree/compiler/Codegen/TransformDialectExtensions/TransformDialectExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
- compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.td
- tests/e2e/linalg_transform/transform_dialect_dispatch_spec.mlir
This revision introduces a helper function that populates the `workgroup_count`region by starting from a `scf::ForeachThreadOp::getNumThreads` and iteratively pulls in the "last" operation from a worklist of ops that it maintains.
The algorithm stops at any op that tries to pull in any op with non-index operands.
At this time, this is only tested for constant ops.
This allows proper parallel semantics, when previously only single-threaded execution was legal.
In the process, the Flow/Stream::ExecutableExport ops had to be made IsolatedFromAbove to avoid spurious hoistings that create verification errors.
> Outline workgroup count computing IR in a new DispatchWorkgroupsOp::workgroup_count region.

- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
- tests/e2e/matmul/large_linalg_matmul.mlir
As discussed, add back tests for large aligned matmul for cuda target
only.
> Add e2e tests for large aligned matrix for cuda only

- experimental/rocm/CMakeLists.txt
- experimental/rocm/registration/driver_module.c
I think some cmake paths need to change for rocm runtime to build as an external driver. These changes allowed me to build it in my local environment
> Some updates to build external rocm

- tests/e2e/tosa_ops/BUILD
- tests/e2e/tosa_ops/CMakeLists.txt
All other Vulkan implementations (Mali, NVIDIA, SwiftShader)
are fine with the code. Even older Adreno GPU drivers are fine..
So pretty much a driver issue. Need to investigate further;
disable it in the meanwhile.
> [vulkan] Disable clz.mlir tests due to Adreno GPU failure

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_x86_64_launch_configuration.mlir
Reducing the default max tile size used for workgroup distribution for
generic ops will reduce the amount of stack allocation
needed. (`argmax` computation that is lowered into `generic` op is the
only place we really need an allocation at this point).
Issue #9469
> Reduce default max tile size for workgroup distribution for Generic ops.

- .github/workflows/build_package.yml
- .github/workflows/schedule_candidate_release.yml
Breaks the release because the push action attempts to push to the main
branch with an older commit. We should be able to just run a simple
`git push origin "${tag_name}"` to replace that whole silly action, but
testing on my fork right now isn't working, so reverting to unbreak the
release. https://github.com/google/iree/runs/6907189012
Reverts google/iree#9506
> Revert "Update candidate release to use the latest commit that passed all checks"

- CMakeLists.txt
- build_tools/third_party/cuda/CMakeLists.txt
Reverts google/iree#9514. 
Fixes error in conditional checking for the existence of the CUDA toolkit and defined CUDA deps before falling back to CUDA fetch. Correct conditional in `CMakeLists.txt`: 
```cmake
if(NOT CUDAToolkit_FOUND AND DEFINED ENV{IREE_CUDA_DEPS_DIR})
set(CUDAToolkit_ROOT "$ENV{IREE_CUDA_DEPS_DIR}")
message(STATUS "CUDA SDK not found by CMake but using IREE_CUDA_DEPS = ${CUDAToolkit_ROOT}")
elseif(NOT CUDAToolkit_FOUND AND NOT DEFINED ENV{IREE_CUDA_DEPS_DIR})
message(STATUS "CUDA SDK not found by CMake but downloading dependencies")
add_subdirectory(build_tools/third_party/cuda EXCLUDE_FROM_ALL)
endif()
```
> Reland On Demand Downloading of CUDA Dependencies for non CI Builds

- .github/workflows/schedule_candidate_release.yml
That whole push action can be replaced with a single git command. I
think I've made this discovery before and suggest we be a bit more
judicious when deciding whether to use third party actions. The
`actions/checkout` action will persist credentials by default, so after
that there's no reason to use a custom action for something that can be
done with a git command. Also, every time an error includes a js stack
trace I die a little inside.
The impetus for this was that we really want that push to only push the
single tag we just added, but the way it's set up it *has* to push a
ref. Before, it was pushing main, which just happened to work because
we were also running the action on the tip of main, so it was generally
a noop. But with the introduction of logic to release from a green
commit …
> Use simple `git push` command instead of complex action

- build_tools/benchmarks/common/benchmark_presentation.py
Generalize functions in benchmark_presentation.py so they can be reused to generate the report for compilation statistics.
The follow-up change #9485 will add compilation statistics to the report.
> Generalize benchmark_presentation.py for compilation statistics

- tests/e2e/tosa_ops/BUILD
- tests/e2e/tosa_ops/CMakeLists.txt
This reverts commit 88be147d1ec09bfd69aabc17ce8a733daa740077
given now we have a workaround for the Adreno GPU issue.
> [vulkan] Re-enable tosa.clz tests

- compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.h
This is in preparation of recent bufferization changes that no longer
allow access to dialect state in `bufferize` interface methods.
> Remove FlowBufferizationState.

- experimental/rocm/direct_command_buffer.c
Fixing bug where the offset values were not being used in copy_buffer for rocm, for example on the CUDA side we have
https://github.com/google/iree/blob/main/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c#L261-L262
> Fix offset error in ROCM command buffer

- runtime/src/iree/base/internal/synchronization.h
The least pedantic part of this is to clarify that a "release" store only prevents reordering other stores past it -- it doesn't prevent loads from being reordered past it.  Likewise, a "acquire" load only prevents reordering other loads before it.  Also emphasized how important it is that the same `notification` object is used on both sides (release/acquire) in order to get any ordering relationship out of this (I feel that the "barrier" terminology doesn't convey that and might lead some reader to believe that just because they have a release on one side, that's somehow enough to get a barrier-like guarantee).
Did a bit more than just fixing that in-place because it's devilishly hard to phrase something that's technically correct on this topic :grin: ... provided an example to make it a …
> Fix atomic comments in synchronization.h

- runtime/src/iree/base/internal/threading.h
- runtime/src/iree/base/internal/threading_darwin.c
- runtime/src/iree/base/internal/threading_pthreads.c
- runtime/src/iree/base/internal/threading_win32.c
- runtime/src/iree/task/scope.c
- runtime/src/iree/task/scope.h
Just some test-only teardown race.
```
WARNING: ThreadSanitizer: data race (pid=2133510)
Atomic read of size 1 at 0x7b3400000068 by thread T18:
#0 pthread_mutex_lock <null> (task_tests+0x2c3748)
#1 iree_notification_post /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/synchronization.c:579:3 (task_tests+0x33c96a)
#2 iree_task_scope_end /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/scope.c:129:5 (task_tests+0x335320)
#3 iree_task_retire /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/task.c:202:5 (task_tests+0x335bbe)
#4 iree_task_call_execute /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/task.c:279:5 (task_tests+0x335cee)
#5 iree_task_worker_execute /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/worker.c:19 …
```
> fix race and replace mutex by atomic iree_task_scope

- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensions.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_vector_distribution_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_vector_distribution.mlir
This revision adds a transform dialect extension op that performs the following.
Given a target that is isolated from above, rewrite ops predicated by
`if (threadIdx.x == 0)` to distributed form running ***on a single warp***.
The warp size is determined by the `warp_size` transform op attribute (it is generally
32 but we do not want to hardcode it).
This rewrite only applies if it can be determined from the IR (i.e. from
the surrounding IREE::HAL::ExecutableExportOp) that the ***number of threads
along the warp dimension is a multiple of the warp size***.
The transformation bails on non-perfect multiples of the warp size that would not properly
distribute.
Example:
```
hal.executable.export public @foo ... { workgroup_size = [64: index, 1: index, 1: index] }
builtin.module {
func.func …
```
> [LLVMGPU] Add transform to distribute vectors along warp.

- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
Target the whole hal.executable_variant op and rewrite all scf.foreach_thread
to distributed gpu.thread_id and translation_info attribute.
The mapping of threads to gpu.thread_id is currently one-to-one and in order.
Only **bufferized** scf.foreach_thread are currently supported.
Only scf.foreach_thread distributed to *8at most 3 dimensions** are currently
supported.
Multiple scf.foreach_thread are supported per function in which case, the
max of all the threads is computed and taken for the global gpu.thread_id.
If necessary, scf.foreach_thread that do not use the whole thread range
result in predicated computations.
Barriers are inserted after each scf.foreach_thread op for now.
Example:
```
hal.executable {
hal.executable.variant {
hal.executable.export {
func @foo() { …
```
> Improve lowering of scf.foreach_thread to GPU.

- runtime/src/iree/vm/ops.h
- runtime/src/iree/vm/test/conversion_ops_f32.mlir
The current code is actually exercising undefined behavior. `lroundf`
can't be used for converting to uint32 because `long int` is only
guaranteed to be at least a 32-bit signed integer. The floats used in
the tests are also ones that can't be represented precisely in an f32.
Note that the f32->ui32 test was actually explicitly *testing*
overflow previously, as it was asserting that the rounded value ended
up being zero.
> Fix float->[u]int conversion

- runtime/src/iree/hal/drivers/vulkan/vulkan_device.cc
Removes non-fatal Validation layer error message wrt int64 shader.
> Enable Int64 Shader on Vulkan Device if available

- build_tools/third_party/cuda/CMakeLists.txt
Like `libdevice.10.bc` previously, `cuda.h` was also copied to
a nested directory `cuda.h/cuda.h`. This is because CMake
`file (COPY)` expects a destination directory.
> [cua] Fix cuda.h path for downloaded CUDA dependencies

- compiler/src/iree/compiler/Dialect/Flow/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/PadTensorToTensorInsertSlice.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/pad_tensor_to_tensor.mlir
-subtensor_insert has been replaced by tensor.insert_slice, so renaming the pass to make it more representative of current op naming.
> Rename PadTensorToSubTensorInsert to more representative PadTensorToInsertSlice

- runtime/src/iree/hal/drivers/vulkan/api.h
- runtime/src/iree/hal/drivers/vulkan/debug_reporter.cc
- runtime/src/iree/hal/drivers/vulkan/debug_reporter.h
- runtime/src/iree/hal/drivers/vulkan/registration/driver_module.cc
- runtime/src/iree/hal/drivers/vulkan/vulkan_driver.cc
Users with release builds can turn the layers on using the flags but they won't be enabled by default - which more closely matches user-intended behavior when running benchmarks/their own applications/etc in release builds.
> Adding `--vulkan_debug_verbosity=` flag and disabling debug layers in release.

- CMakeLists.txt
In this case, the default release mode can be properly set at the first
build with the proper compilation optimization level set.
> Set CMake default build type at the beginning of the cmake config

- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- runtime/src/iree/schemas/bytecode_module_def.fbs
The extended reflection metadata can be used if needed. This will make
it easier to support variadic exports (if we want).
> Removing unused VM bytecode function signature fields.

- .github/CODEOWNERS
Not sure what this is, but it should be treated like `third_party/llvm-project/`.
See https://github.com/iree-org/iree/pull/9614
> Ignore llvm-project.branch-pin in CODEOWNERS.

- docs/website/docs/assets/stylesheets/extra.css
- docs/website/mkdocs.yml
Before:
After:
(that will be `iree-org/iree` after https://github.com/iree-org/iree/pull/9635)
References:
* https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle (that lists other popular icon combinations)
* https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/ (and https://github.com/squidfunk/mkdocs-material/issues/3800#issuecomment-1090428115)
> Hide latest release from website widget and update icons.

- compiler/src/iree/compiler/Dialect/HAL/Target/WebGPU/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/test/BUILD
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/test/function_attrs.mlir
- compiler/src/iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
- runtime/bindings/python/vm.cc
- runtime/bindings/tflite/interpreter.c
- runtime/src/iree/hal/local/loaders/vmvx_module_loader.c
- runtime/src/iree/modules/hal/module.c
- runtime/src/iree/modules/vmvx/module.c
- runtime/src/iree/schemas/bytecode_module_def.fbs
- runtime/src/iree/vm/bytecode_module.c
- runtime/src/iree/vm/bytecode_module_benchmark.cc
- runtime/src/iree/vm/module.c
- runtime/src/iree/vm/module.h
- runtime/src/iree/vm/native_module.c
- runtime/src/iree/vm/native_module.h
- runtime/src/iree/vm/native_module_test.h
- tools/iree-benchmark-module-main.cc
This makes the attr queries consistent with the other API methods and
removes "reflection" from the name. Also plumbs through module attrs and
enables support for unit attrs (empty values).
Fixes #1979.
> Cleaning up function reflection attrs.

- compiler/src/iree/compiler/InputConversion/MHLO/ConvertComplexToReal.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/fft.mlir
Avoid using pattern unless there is no other patterns in rewrite set
that can. This allows reusing patterns populated from this pass with
others which handle mhlo.complex.
Related to #7621.
> Lower mhlo.complex benefit to 0

- compiler/src/iree/compiler/Codegen/Interfaces/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensions.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformDialectExtensions/TransformDialectLLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/linalg_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/TilingToForeachThreadOp.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling-to-foreach-thread-op.mlir
This revision takes advantage of the recently introduced `thread_dim_mapping` attribute to `scf.foreach_thread`.
We use it to rewrite the `transform.iree.foreach_thread_to_gpu_and_translation_info` transformation to take
the `workgroup_size` explicitly and operate at the level of a FuncOp.
All `std.foreach_thread` nested under the FuncOp are mapped to `workgroup_size` and predicated accordingly.
This revision also prefetches LLVM commits:
* a786f30c5d2a05591ba355ce1ffc05cdfb5bcfef
* ad8ae6ea170967c008a1e1c501cb8be2707a413c
> Improve control over transform dialect mapping of foreach_thread to GPU

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
Allow more broadcast and transpose support for warp reduction. Note that
the memory access patterns for transpose case may not be optimal but it
is still faster than serializing the reduction.
> [LLVMGPU] Support more cases in warp reduction

- runtime/src/iree/base/internal/threading_test.cc
Another test-only teardown race. Unless you specifically want coverage for the notification code in this test, it's easiest to fix this one by just keeping the (already existing anyway) atomic `entry_data.value` as the sole synchronization mechanism here.
Then even there there was another separate issue: the way it used to be read with `relaxed` order wouldn't construct any happens-before relationship with the way it was stored with `release` order. Changed to reading it with `acquire` order to get such a relationship. Moreover, the fetch_add storing it didn't really need to be `acq_rel` as we only care about the store part having `release` order.
```
WARNING: ThreadSanitizer: data race (pid=1706527)
Atomic read of size 1 at 0x7ffd0175deb8 by thread T3:
#0 pthread_mutex_lock <null> …
```
> Fix teardown race in threading_test

- compiler/src/iree/compiler/Dialect/VM/Conversion/MemRefToVM/ConvertMemRefToVM.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/MemRefToVM/test/BUILD
- compiler/src/iree/compiler/Dialect/VM/Conversion/MemRefToVM/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/VM/Conversion/MemRefToVM/test/memref_ops.mlir
Rebasing #9163 and updating to 64-bit VM sizes.
Fixes #9155.
> Add support for lowering memref.alloca to VM dialect.

- runtime/src/iree/base/alignment.h
- runtime/src/iree/base/target_platform.h
Splits out the ops for 64-bit types from the
`IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` flag and introduces a
`IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED_64` flag. The new flag is enabled
for Arm targets if the alignment requirements aren't specified by the
user. If the user specifies alignment requirements but doesn't
explicitly for 64-bit types, the new flag defaults to the general
alignment settings.
Fixes #9593.
> Split the alignment flag for 64-bit types

- runtime/src/iree/base/target_platform.h
Even if `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` was defined it was
always set to 0. However, it is only valid to set it to 0 if
`IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` isn't defined.
Makes progress on #9593 and allows to control the alignment behavior
via `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` instead of being
forced to pass `-mno-unaligned-access`.
> Fix setting IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED

- build_tools/embed_data/generate_embed_data_main.cc
If the compiler is misconfigured to compile the .c file as C++ this will
ensure the symbol name matches the declaration in the header.
Fixes #7327.
> Adding extern C around embedded data toc impl.

- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/ConvertTensorToFlow.cpp
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/test/cast.mlir
Since we don't handle unranked tensors there's not much tensor.cast
seems to do that tensor.reshape doesn't as it doesn't allow element
type conversion.
Closes #6418.
> Removing todo for a flow.tensor.cast equivalent.

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.h
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dialect_dispatch_spec.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.td
- tests/e2e/linalg_transform/transform_dialect_dispatch_spec.mlir
Also fixes a bug in TileToForeachOp where the outs were returned in the
wrong order.
> Add ins/outs to ForeachThreadToFlowDispatchWorkgroupsOp

- runtime/src/iree/task/poller.c
The issue was that iree_task_poller_pump_until_exit only checked
for IREE_TASK_POLLER_STATE_EXITING at the beginning of each loop
iteration, then reset wake_event, then called
iree_task_poller_commit_wait.
Meanwhile, on the main thread, iree_task_poller_request_exit could
change state to IREE_TASK_POLLER_STATE_EXITING and set wake_event.
So in a race, iree_task_poller_pump_until_exit would reset the
wake_event set by iree_task_poller_request_exit, and that would leave
iree_task_poller_commit_wait waiting infinitely.
Fixes #9723
> Fix shutdown deadlock

- runtime/src/iree/task/executor.c
- runtime/src/iree/task/executor_impl.h
- runtime/src/iree/task/post_batch.c
- runtime/src/iree/task/worker.c
This makes worker_*_mask accesses use memory_order_relaxed, making them be only fast and loose hints, and not play a role in ordering other accesses.
Some of these used to be relaxed until https://github.com/iree-org/iree/pull/8854 which made worker_live_mask use acquire/release to fix a specific race reported by TSan. This PR re-solves that in a different way: the missing ordering is now provided instead by an atomic access to worker->state.
Some accesses (in worker.c) were seq_cst even before https://github.com/iree-org/iree/pull/8854, so this new PR makes more things relaxed than were even back then.
This is part of a more general, consistent move towards this design:
* worker->state is the only memory-ordering, coherent view of workers'
state.
* worker_*_mask is only fast and loose …
> Consistently treat worker_*_masks as loose hints with relaxed accesses

- docs/website/docs/CNAME
Domain verification needs to happen first else redirect broken it seems.
Reverts iree-org/iree#9679
> Revert "Create CNAME for github serving"

- runtime/src/iree/task/executor.c
- runtime/src/iree/task/worker.c
Actually one place was already acquire/release, inconsistently with the
rest that was seq_cst. That was likely a bug, though it hadn't
manifested itself so far under TSan.
We had to standardize one way or the other: either all seq_cst or
all acquire/release.
I thought about why we might need this to be seq_cst and though actually
we probably don't. Changing to weakly ordered means that the order in
which different workers change state may be seen differently by
different threads, but that doens't seem to matter. It would have move
consequences if there were other atomics that we are accessing seq_cst
in conjunction with worker->state and we actually relied on sequential
consistency, but there don't really seem to be.
The comment in worker.h points to worker->wake_notification, and the …
> Access worker->state with acquire/release, not seq_cst.

- runtime/src/iree/task/poller.c
It was being accessed seq_cst in most places, except one place that was
acq_rel. Now it's consistent and 1000 runs of executor_test under TSan
give confidence that it's correct.
> Consistently access poller->state with acquire/release order

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/vector_to_gpu.mlir
- compiler/src/iree/compiler/Codegen/Utils/Utils.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.cpp
Also provide fixes required for those changes.
> Cherry-pick LLVM changes related to SubViewOp::inferRankReducedType and Transform::applyToOne

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOpcodesCore.td
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td
- compiler/src/iree/compiler/Dialect/VM/IR/test/arithmetic_folding.mlir
- compiler/src/iree/compiler/Dialect/VM/IR/test/arithmetic_ops.mlir
- runtime/src/iree/vm/bytecode_dispatch.c
- runtime/src/iree/vm/generated/bytecode_op_table.h
- runtime/src/iree/vm/ops.h
- runtime/src/iree/vm/test/arithmetic_ops.mlir
- runtime/src/iree/vm/test/arithmetic_ops_i64.mlir
I want these for https://github.com/google/iree/issues/5854.
Also included
* a tiny documentation change to float comparison op summaries (point out that "o" == "ordered" and "u" == "unordered" for comparisons)
* a printing/parsing test for `vm.fma.i32`
> Add vm.abs.i32 and vm.abs.i64 ops.

- runtime/src/iree/modules/vmvx/exports.inl
- runtime/src/iree/modules/vmvx/module.c
- runtime/src/iree/vm/shims.h
This gets us to a single declaration of the argument fields and
closer to what the vm.import-generated stuff will look like.
I think there's still some simplification that can be done here by
reusing the cconv signature declared on the structs to provide the
full cconv signature for the EXPORT_FN decls but I didn't try to do
that here. There's other ergonomics/cleanliness improvements that
could be done but these changes at least get us to a state of only
marginally 🤮-inducing.
> Removing the need for the ririririri fields in vmvx arg structs.

- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_driver.py
- build_tools/benchmarks/common/benchmark_driver_test.py
- build_tools/benchmarks/common/benchmark_suite.py
- build_tools/benchmarks/common/benchmark_suite_test.py
- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
Convert the driver config string to `DriverInfo` from the inputs and only use `DriverInfo` internally.
After the recent changes on the IREE driver, there are more options to config the driver. The original "driver name" string becomes an alias of a specific config. `DriverInfo` contains the structured data and makes other places easier to get the detailed info.
> Replace config string with DriverInfo

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformDialectInterpreterPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/transform_dialect_apply_pattern_op.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- tools/iree-opt-main.cc
This revision creates a transform dialect interpreter pass in IREE with
the proper dialect registrations to allow end-to-end examples from both
iree-run-mlir and iree-opt.
In the future, when the layering is right, only a single interpreter will
be needed for both codegen and non-codegen rewrites, which will allow
retiring the specialized interpreter that is used for dispatch region
creation with the transform dialect.
For now, the iree-dialects interpreter remain as a way to separate concerns
between patterns and transform ops that are IREE-specific from one that
will be upstreamed in the fullness of time.
> Decouple Transform dialect usage in IREE from iree-dialects.

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.h
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/transform_dialect_match_op.mlir
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
This revision adds a less general but more customizable match op that is easier to use than PDL's.
The feature set should grow up towards idiomatic use cases for high-level codegen.
Each feature should be carefully weighed in to ensure it does provide significantly usability gains, otherwise we should just use the PDL match op.
> Add a more intuitive transform.iree.match op

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops.mlir
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/arithmetic_ops_i64.mlir
This adds VM to EmitC tests for the ops added with commit ca51bc6.
> Add conversion tests for vm.abs ops

- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/linux_device_utils.py
- build_tools/benchmarks/common/linux_device_utils_test.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
Add CUDA support to the linux benchmark tool.
The tool has a new option `--gpu_id` to specify the target GPU. It reads the GPU info from `nvidia-smi` and gets the compute capability. Only the benchmarks match the GPU's compute capability will be run.
> Add CUDA support to benchmark tools

- integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp
This is to align tensorflow::StatusOr with absl::StatusOr in preparation
for upstream changes.
> Replace tensorflow::StatusOr::ConsumeValueOrDie with StatusOr::ValueOrDie().

- runtime/src/iree/base/internal/atomics_disabled.h
iree_atomic_store_intptr(x, y) expanded to
```
(intptr_t) * (iree_atomic_int32_t*) (x) = (y)
```
The (intptr_t) cast on the left hand side had higher precedence than the
assignment operator so the entire expression
```
(intptr_t) * (iree_atomic_int32_t*) (x)
```
was interpreted as a lvalue being assigned to, and that resulted in
compilation error. This showed up only on riscv CI on #9777.
* Why only on RISCV: presumably because it's the only place where we use atomics_disabled.
* Why only on that PR: presumably because it introduces a use of iree_atomic_store_intptr.
> Fix compile errors in atomics_disabled

- .github/workflows/build_runtime_cmake.yml
- .github/workflows/lint.yml
- .github/workflows/postsubmit.yml
- .github/workflows/test_runtime_cmake.yml
This uses GitHub's hosted runners, since they are sufficient when only
building the runtime. It mostly a step towards migrating our initial
Buildkite workflows and finding parity with those. Note that this is
not doing anything to make the entire workflow idempotent. We will
likely need to move to our own artifact storage scheme (backed by GCS)
to make that work. We definitely incur a cost from having to upload and
download the build directory rather than building and testing in the
same directory (1.5 minutes to upload. download is negligible), but I
think the modularity is worth it and we can find a way to speed it up.
> Add a workflow for building and testing the runtime post-submit

- experimental/web/sample_dynamic/CMakeLists.txt
- experimental/web/sample_dynamic/benchmarks.html
- experimental/web/sample_dynamic/device_sync.c
- experimental/web/sample_dynamic/index.html
- experimental/web/sample_dynamic/main.c
- experimental/web/sample_static/index.html
- experimental/web/testing/index_template.html
- experimental/web/testing/test-runner.html
* Use a relative path to the favicon (stable across serving from a different root)
* Add VMVX loader to dynamic sample
> Web sample tweaks for showing demos.

- build_tools/benchmarks/common/common_arguments.py
- build_tools/benchmarks/post_benchmarks_as_pr_comment.py
- build_tools/benchmarks/upload_benchmarks_to_dashboard.py
- build_tools/buildkite/cmake/linux/pipeline.yml
RISC-V benchmarks currently don't generate `benchmark-results-*.json`, so the comment step will fail because the artifacts can't be found.
This change stops the pipeline from failing if buildkite-agent can't find the artifacts and handles the wildcard in the scripts.
The dashboard upload step theoretically has the same issue, but since it only runs with full benchmarks, we don't have such a case right now. This fix is not very clean so I prefer to only fix the comment step for now.
Fix #9766
> Handle the missing results when posting comments

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/warp_reduction.mlir
Change to do vector distribution on a group instead of doing it on a
warp. That allows us to use extra parallelism. This also simplifies the
flow since we don't need to do a second level of tiling and distribute.
> [LLVMGPU] Improve reduction lowering to do group reduction

- compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
The newly added test case was lowered to an invalid memref::CastOp.
> Fix bug in FlattenMemRefSubspanPass

- .github/workflows/presubmit.yml
- .github/workflows/tsan.yml
Add a job that aggregates the results of all other presubmit jobs
into a single "Check Run" (different from the "Status" API and from
PR "checks". Very confusing). We can use this job's  to hook into the
GitHub "required checks" functionality and therefore enable dynamic
determination about which jobs need to pass before a PR can be
merged.
Demo: https://github.com/iree-org/iree/actions/runs/2694279081
> Summarize presubmit in single PR check

- runtime/src/iree/base/internal/synchronization.c
- runtime/src/iree/base/internal/synchronization.h
* Explain the weakly ordered atomics in iree_slim_mutex_t
(now that I finally understand them and while I haven't forgotten)
* NFC refactoring of iree_slim_mutex_{lock,trylock}: move the
compare_exchange op to a shared helper.
* Fix some atomic comments on iree_notification_t
(an acq/rel operation is not quite the same as a barrier, the
ordering relationship only applies on ops on the same object).
> Comments and NFC tidying on atomics in synchronization.*

- runtime/src/iree/base/internal/threading_darwin.c
- runtime/src/iree/base/internal/threading_pthreads.c
- runtime/src/iree/base/internal/threading_win32.c
This is mostly changing some unnecessary seq_cst to acquire/release consistently with what other accesses were already doing.
In some compare_exchange, the compare-failure case could use relaxed because we didn't rely on ordering in that case.
> Tweaks to atomics in `iree_thread_*` - use acquire/release consistently

- compiler/src/iree/compiler/API/python/test/tools/compiler_core_test.py
- compiler/src/iree/compiler/API/python/test/transforms/ireec/compile_sample_module.py
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/export_benchmark_funcs.mlir
- runtime/bindings/python/tests/system_api_test.py
- runtime/bindings/python/tests/vm_test.py
- runtime/src/iree/runtime/demo/README.md
- samples/static_library/README.md
- samples/static_library/simple_mul.mlir
Progress on https://github.com/iree-org/iree/issues/9667, working towards removing MHLO and other input dialects from the "core" parts of the IREE compiler. Any tests using input dialects should be organized under the relevant `compiler/InputConversion/*` or `tests/e2e/*_ops/` directories.
Notable remaining tests using mhlo in the "core" of the compiler:
* [demote_f32_to_f16.mlir](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/Util/Transforms/test/demote_f32_to_f16.mlir)
* [demote_f64_to_f32.mlir](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/Util/Transforms/test/demote_f64_to_f32.mlir)
* [demote_i64_to_i32.mlir](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Dialect/Util/Transforms/test/demote_i64_to_i32 …
> Replace mhlo ops with core dialect ops in more tests.

- docs/website/docs/building-from-source/getting-started.md
I saw test failures until I built the `iree-test-deps` target.
Also recommend the IREE flag for enabling ccache.
> [docs] Mention test dependencies

- compiler/src/iree/compiler/Dialect/Util/Transforms/test/demote_f32_to_f16.mlir
- compiler/src/iree/compiler/Dialect/Util/Transforms/test/demote_f64_to_f32.mlir
- compiler/src/iree/compiler/Dialect/Util/Transforms/test/demote_i64_to_i32.mlir
- compiler/src/iree/compiler/Dialect/Util/Transforms/test/promote_f16_to_f32.mlir
Progress on https://github.com/iree-org/iree/issues/9667
`mhlo.reduce` was being used as a simple op with a nested region. I considered using `linalg.generic` in its place, but found that `tensor.generate` was simpler. Maybe a custom op would be even simpler (if we're trying to test something purely structural and don't care about a particular op's semantics)?
> Replace mhlo ops with core dialect ops in type conversion tests.

- runtime/bindings/tflite/testdata/BUILD
- runtime/bindings/tflite/testdata/CMakeLists.txt
- runtime/src/iree/modules/check/test/BUILD
- runtime/src/iree/modules/check/test/CMakeLists.txt
- runtime/src/iree/modules/check/test/failure.mlir
- runtime/src/iree/modules/check/test/success.mlir
- runtime/src/iree/modules/check/test/unavailable.mlir
- runtime/src/iree/runtime/testdata/BUILD
- runtime/src/iree/runtime/testdata/CMakeLists.txt
- samples/simple_embedding/BUILD
- samples/simple_embedding/CMakeLists.txt
- tools/test/benchmark_flags.txt
- tools/test/multiple_exported_functions.mlir
Progress on https://github.com/iree-org/iree/issues/9667 - nearly done!
I'm now able to build and test `all` using `-DIREE_INPUT_DIALECTS_MHLO=OFF -DIREE_INPUT_DIALECTS_TORCH=OFF -DIREE_INPUT_DIALECTS_TOSA=OFF` from https://github.com/iree-org/iree/pull/9474. I haven't tried `iree-test-deps` yet, but it will take more work to get passing in that configuration (if we care).
One drawback of this is that the `--iree-input-type=` flag might be harder to discover for users/developers who browse through the repository. We should improve error messages and ergonomics anyway (see https://github.com/iree-org/iree/discussions/9759 for a recent discussion about that).
> Remove unnecessary `--iree-input-type=mhlo` flag uses.

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/BUILD
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_transform_dialect.mlir
When creating a flow.dispatch.workgroups op from an scf.foreach_thread
op, some ops are now cloned and fused into the dispatch region (as per
existing IREE heuristics).
> scf.foreach_thread lowering: Clone ops into dispatch regions

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_riscv_launch_configuration.mlir
This PR moves hard-coded workgroup tile sizes to an independent function
and pave the way for introducing more sophisticated tile size computation.
As part of this refactoring, we change the default tile sizes for RISC-V
to avoid vectorizing the dimension k, which resulted in very inefficient
code (see comments).
> Refactor matmul workgroup size computation and improve RISC-V default

- build_tools/buildkite/cmake/linux/pipeline.yml
#9845 removed the submodule update from `build_host_tools.sh` in favor of Github runner. Buildkite disabled the submodule checkout, so we need to manually do it in the Buildkite pipelines.
> Fix submodule checkout for buildkite pipeline

- benchmarks/README.md
With the new MiniLM TF models, the `iree-import-tf` is one of the requirements to build benchmark suite.
> Add iree-import-tf as requirements in the doc

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
This *should* improve the performance a bit on all the CPUs since
we go from generating an extract/insert pair of operations for each
element to generating complex shuffle that *should* be lowered to a
smarter sequence of instructions by the backend.
This PR is part of a set of changes aimed at improving reductions and
transpositions on RISC-V.
> Change default transpose lowering from eltwise to shuffle

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
The 'innerparallel' multi-reduction lowering transposes the innermost
reduction dimension with an outer parallel dimension so that the innestmost
dimension becomes parallel and each vector lane can compute an independent
reduction. The 'innerreduction' multi-reduction lowering keeps the
reduction dimension in its innermost position and generates vector
horizontal reductions as part of the computation. The horizontal
reductions are not generated very efficiently right now but transposing
a 2D vector *should* always be less efficient than computing a
horizontal reduction. If that is not the case, we should investigate
why.
This PR changes the reduction policy from 'innerparallel' to
'innerreduction'.
This PR is part of a set of changes aimed at improving reductions and
transpositions on …
> Change default multi-reduction lowering from innerparallel to innerreduction

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
The generated import shims contain an argument for the number of variadic arguments. This argument was missing in the generated call in the case the variadic part had zero arguments.
> [EmitC] Fix conversion for zero argument variadic calls

- build_tools/scripts/android_symbolize.sh
The symbolizer from the newest NDK treats `-obj` as 3 separate short
options.
> Fix android_symbolize script

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
Reduction vectorization is driven by the input tensors (i.e., the ones
that we want to reduce). Taking into account the output's map (e.g.,
(d0, d1) -> (d0) when computing the minimum tile sizes for
vectorization/unrolling leads to large unroll factors (i.e., UF=16 for i32
reductions, UF=32 for i16 and UF=64 for i8).
This PR change the logic to limit the unroll factor for reductions when computing
the minimum tile sizes. This logic should be replaced/improved to be more
generic and direct, eventually.
This PR is part of a set of changes aimed at improving reductions and
transpositions on RISC-V. This change also helps reduce the unrolling
issues that we have in IREE.
> Limit unroll factor for reductions when computing min tile sizes

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
Expands the documentation with an example. Adds helper functions for
accessing basic block arguments.
> Expand Flow WorkgroupsOp documentation and add helper functions

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/test/control_flow_ops.mlir
- runtime/src/iree/hal/local/loaders/vmvx_module_loader.c
- runtime/src/iree/runtime/session.c
- runtime/src/iree/runtime/session.h
- runtime/src/iree/vm/bytecode_dispatch.c
- runtime/src/iree/vm/bytecode_dispatch_async_test.cc
- runtime/src/iree/vm/bytecode_module.c
- runtime/src/iree/vm/bytecode_module_benchmark.cc
- runtime/src/iree/vm/bytecode_module_impl.h
- runtime/src/iree/vm/context.c
- runtime/src/iree/vm/invocation.c
- runtime/src/iree/vm/module.h
- runtime/src/iree/vm/native_module.c
- runtime/src/iree/vm/native_module.h
- runtime/src/iree/vm/native_module_cc.h
- runtime/src/iree/vm/native_module_packing.h
- runtime/src/iree/vm/native_module_test.h
- runtime/src/iree/vm/shims.h
- runtime/src/iree/vm/shims_emitc.h
This removes the unused `iree_vm_execution_result_t` that needed to be passed in to each call and changes the `iree_vm_function_call_t` struct to be passed by-value to improve compiler analysis.
> Simplifying vm call interface.

- tools/iree-benchmark-module-main.cc
Now we have some benchmarks (x86, CUDA) that take less than 10ms to run. This means the default milliseconds unit isn't precise enough to show the difference (the console output only shows 2 digits after decimal point).
This change adds a new option to specify the desired time unit: nanoseconds, microseconds, and milliseconds.
> Add time unit option to iree-benchmark-module

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
Use the recently added method to get block arguments for a result to
avoid invalid out-of-bounds accesses.
Issue #9896
> Use helper methods to get block arguments for output during tie-ing of operands/results.

- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
Move buferization to after vectorization for group reduction pipeline.
This will allow better register level fusion. Also improve distribution
interaction with hal operations and add a test to make sure this can
handle fusion with broadcast.
> [LLVMGPU] Improve reduction flow and support handled fused broadcast

- runtime/src/iree/hal/drivers/cuda/cuda_device.c
- runtime/src/iree/hal/drivers/cuda/dynamic_symbol_tables.h
Instead of creating a new context retain the primary context and use it.
This prevent running into problems if another library is using CUDA.
This may still fail if application using a context which is not the
primary context. We would need to scope the different iree entry point
to prevent that. This solution allows us to move forward in the meantime
and should cover most of the use cases.
> [hal][cuda] Use the primary context if available in hal

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- compiler/src/iree/compiler/Dialect/Util/Analysis/Attributes/Range.cpp
- compiler/src/iree/compiler/Dialect/Util/Analysis/Explorer.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/BUILD
- compiler/src/iree/compiler/Dialect/Util/IR/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Util/IR/UtilDialect.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilDialect.h
- compiler/src/iree/compiler/Dialect/Util/IR/UtilExternalModels.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilExternalModels.h
- compiler/src/iree/compiler/Dialect/Util/IR/UtilInterfaces.td
- compiler/src/iree/compiler/Tools/BUILD
- compiler/src/iree/compiler/Tools/CMakeLists.txt
- compiler/src/iree/compiler/Tools/init_iree_dialects.h
The purpose of this change is to address a TODO in `DispatchLinalgOnTensors.cpp`:
```
// TODO(antiagainst): use TiedOpInterface here instead of hardcoding ops
// when it's available in MLIR core in some form.
```
> Implement TiedOpInterface for InsertSliceOp, LinalgOp

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
`getOutputBlockArgument` uses the tied operands attribute, so it is
important to keep both in sync with every iteration.
The current implementation caused a problem in a subsequent change.
> Fix bug in tryToTieOperandsAndResults

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DetachElementwiseFromNamedOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/detach_elementwise_from_named_ops.mlir
Having a splat constant as an outs operand results in stack
allocations. The canonical way to represent these is through use of
`linalg.fill` operations. These get tiled + fused + bufferized without
having to allocate any stack allocations. This is probably needed for
all `LinalgOp`s as well, but for now just limit these to
`LinalgExtOp`s.
Issue #9896
> Detach splat constants used as outs operands for `LinalgExt` ops.

- CMakeLists.txt
This should work around a GCC bug that is causing multiple definition
errors when standards mismatch.
> Force CMAKE_CXX_STANDARD to 17 to override LLVM's mechanism.

- build_tools/benchmarks/collect_compilation_statistics.py
- build_tools/benchmarks/collect_compilation_statistics_test.py
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_presentation.py
- build_tools/benchmarks/common/benchmark_thresholds.py
- build_tools/benchmarks/post_benchmarks_as_pr_comment.py
- build_tools/benchmarks/upload_benchmarks_to_dashboard.py
The x86 and CUDA benchmarks need sub-milliseconds data to show the improvements/regressions.
This change uploads the latencies in nanoseconds to the dashboard with the new API.
It still shows milliseconds (wtih 3 digits) in the summary report.
Fix https://github.com/iree-org/iree/issues/9418
> Add unit support in benchmark tools

- .github/workflows/advance_upstream_forks.yml
- .github/workflows/android_tflite_oneshot_build.yml
- .github/workflows/build_package.yml
- .github/workflows/ci.yml
- .github/workflows/host_tools.yml
- .github/workflows/lint.yml
- .github/workflows/oneshot_candidate_release.yml
- .github/workflows/process_opened_issues.yml
- .github/workflows/publish_website.yml
- .github/workflows/schedule_candidate_release.yml
- .github/workflows/validate_and_publish_release.yml
- .yamllint.yml
- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
- build_tools/buildkite/pipelines/fragment/bootstrap-trusted.yml
- build_tools/buildkite/pipelines/fragment/bootstrap-untrusted.yml
- build_tools/buildkite/pipelines/untrusted/test-runtime-cmake.yml
- docs/website/mkdocs.yml
This formats all our yaml files with [Prettier](https://prettier.io/).
I don't think this is a really important property, but the RedHat YAML
language server, which appears to back the only YAML VSCode extension
uses this formatter and I'm really tired of getting random edits from
running the formatter. In particular, yamllint wants there to be two
spaces between code and a comment and Prettier adds only one. This is
extremely annoying and I cannot imagine why anyone would care whether
there are one or two spaces there (other than the Google Python style
guide and linter). So I've updated our yamllint config to also stop
complaining about this trivial thing.
I don't propose that we start mandating Prettier now (though we might
consider it at some point), but this formatting does increase …
> Format our yaml files

- runtime/src/iree/base/string_view.c
- runtime/src/iree/base/string_view_test.cc
Do not pass null pointers to memcpy. Found with `-DIREE_ENABLE_UBSAN=1`.
> Fix UB in iree_string_view_append_to_buffer

- docs/developers/debugging/tf_integrations_test_repro.md
- docs/website/docs/building-from-source/riscv.md
- docs/website/docs/deployment-configurations/bare-metal.md
- docs/website/docs/deployment-configurations/cpu.md
- docs/website/docs/getting-started/tflite.md
- runtime/src/iree/hal/local/executable_library_benchmark.md
Progress on https://github.com/iree-org/iree/issues/9930
> Update docs to use "llvm-cpu" and "local-task" names consistently.

- benchmarks/TF/CMakeLists.txt
- benchmarks/TF/linux-cuda.cmake
- build_tools/benchmarks/collect_compilation_statistics.py
- build_tools/benchmarks/collect_compilation_statistics_test.py
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/buildkite/cmake/linux/cuda/benchmark.yml
- build_tools/buildkite/cmake/linux/pipeline.yml
- build_tools/buildkite/cmake/linux/x86_64/benchmark2.yml
- build_tools/cmake/build_host_tools.sh
- build_tools/cmake/build_linux_benchmark_modules.sh
- build_tools/cmake/build_linux_benchmark_tools.sh
- build_tools/kokoro/gcp_ubuntu/cmake/android/build.sh
Add a new pipeline for CUDA benchmarks on A100. Also add a new CUDA benchmark for MiniLM.
Fix #9318
> Add CUDA benchmark pipeline for MiniLM

- compiler/src/iree/compiler/Codegen/SPIRV/test/vector_to_cooperative_matrix.mlir
* [mlir][spirv] Fix spv.CompositeConstruct assembly and validation
* [mlir][spirv] Unify resources of different vector sizes
> [spirv] Cherry-pick patches for aliased resource unification

- runtime/bindings/python/CMakeLists.txt
- runtime/bindings/python/hal.cc
- runtime/bindings/python/hal.h
- runtime/bindings/python/iree/runtime/__init__.py
- runtime/bindings/python/iree/runtime/_binding.py
- runtime/bindings/python/iree/runtime/system_api.py
- runtime/bindings/python/iree/runtime/system_setup.py
- runtime/bindings/python/status_utils.cc
- runtime/bindings/python/tests/array_interop_test.py
- runtime/bindings/python/tests/devices_cli_test.py
- runtime/bindings/python/tests/hal_test.py
- runtime/bindings/python/tests/system_api_test.py
- runtime/bindings/python/tests/system_setup_test.py
- runtime/bindings/python/tests/vm_test.py
- runtime/src/iree/hal/drivers/local_sync/sync_driver.c
- runtime/src/iree/hal/drivers/local_task/task_driver.c
APIs removed:
* HalDriver.create() (use iree.runtime.get_driver(driver_name) to get a
cached instance).
* Environment variable IREE_DEFAULT_DRIVER renamed to
IREE_DEFAULT_DEVICE to better reflect the new syntax.
* Config.driver attribute (no longer captured by this class)
APIs added:
* iree.runtime.query_available_drivers() (alias of HalDriver.query())
* iree.runtime.get_driver(device_uri)
* iree.runtime.get_device(device_uri)
* iree.runtime.get_first_device(device_uris)
* iree.runtime.Config(, device: HalDevice) (to configure with an
explicit device)
* HalDriver.create_device(device_id: Union[int, tuple])
* HalDriver.query_available_devices()
* HalDriver.create_device_by_uri(device_uri: str)
Both driver and device lookup is done by a device URI, as defined by the runtime (when creating a …
> Rework Python driver/device creation.

- .github/workflows/build_package.yml
Github macos runners have non-universal binary zstd that breaks
our macos universal builds. We have to remove the cmake files too.
> Nuke macos zstd cmake files in GHA

- .github/workflows/ci.yml
This is faster for compression and *way* faster for decompression. I
didn't use it before because it wasn't installed on the CI VMs, but
I've updated the image to include it.
This brings compression + upload + download + decompression time from
over 5 minutes to about 1.5 minutes.
I temporarily enabled GPU testing to ensure extraction worked there
too: https://github.com/iree-org/iree/runs/7570456284
Part of https://github.com/iree-org/iree/9855
> Switch to zstd for compression of artifacts passed between jobs

- runtime/src/iree/task/pool.c
Disable loop optimizations to avoid heap corruption.
Issue: https://github.com/iree-org/iree/issues/9953
> Fix iree_task_pool_grow miscompilation on NDK r25

- .github/workflows/ci.yml
- runtime/bindings/python/invoke.cc
This was a bit tricky to track down. It only affects structured argument
packing/unpacking. We were leaking a reference to the sub-list, which,
given that it usually contains buffers, was causing a leak of any
contained device backed memory buffers. Then much later, with asserts
enabled, the vulkan driver would notice that not all allocated memory
was freed and assert.
I am not completely sure on the cause of the non-determinism. Since the
problem manifests on shutdown, I'm (just guessing) that the normal
shutdown process may be bypassed sometimes? This does only affect a
subset of TF-specific invocation schemes, and until that was obvious, it
was difficult to see the pattern.
Fixes #9936
> Move ref vs retain when stealing pointer for structured args.

- compiler/src/iree/compiler/Bindings/Native/Transforms/WrapEntryPoints.cpp
- compiler/src/iree/compiler/Bindings/Native/Transforms/test/wrap_entry_points.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/HALToVM/ConvertExecutableOps.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/ElideAsyncCopies.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/MaterializeBuiltins.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/OutlineConstants.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/PropagateTimepoints.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/RefineUsage.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/propagate_subviews.mlir
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/propagate_timepoints.mlir
- compiler/src/iree/compiler/Dialect/Util/IR/UtilAttrs.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/test/buffer_ops.mlir
- compiler/src/iree/compiler/Dialect/Util/Transforms/FuseGlobals.cpp
- compiler/src/iree/compiler/Dialect/Util/Transforms/PropagateSubrange.cpp
- compiler/src/iree/compiler/Dialect/Util/Transforms/test/propagate_subranges.mlir
- compiler/src/iree/compiler/Dialect/VM/Conversion/ImportUtils.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/ImportUtils.h
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/test/buffer_ops.mlir
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td
- compiler/src/iree/compiler/Pipelines/Pipelines.cpp
- samples/custom_module/CMakeLists.txt
- samples/custom_module/README.md
- samples/custom_module/main.c
- samples/custom_module/module.cc
- samples/custom_module/module.h
- samples/custom_module/test/CMakeLists.txt
- samples/custom_module/test/example.mlir
This demonstrates how a user out-of-tree can use custom modules and
types with the IREE VM and includes some basic guided documentation.
There are still a lot of ergonomics improvements to be done (especially
with the C++ wrappers) but it's enough to implement the old custom
module sample but without needing any compiler changes at all (can
do all of this from a pip install of iree-compile).
> Adding custom_module sample.

- runtime/bindings/python/CMakeLists.txt
- runtime/bindings/python/binding.h
- runtime/bindings/python/initialize_module.cc
- runtime/bindings/python/iree/runtime/__init__.py
- runtime/bindings/python/py_module.cc
- runtime/bindings/python/py_module.h
- runtime/bindings/python/tests/py_module_test.py
- runtime/bindings/python/tests/vm_types_test.py
- runtime/bindings/python/vm.cc
- runtime/bindings/python/vm.h
Inspired by #9947, which shows how to extend IREE with custom C modules,
I just had to do the plumbing to also allow extension from Python. Usual
caveats apply about Python being a terrible thing to implement real
things in, but there is no escaping how easy it is -- in my experience,
people will start by defining simple Python modules and then if we line
that up seamlessly with how you do it in C, it creates a good glide
path to progressively enhance.
This is just the start. Specifically, it does not yet:
* High level sugar: this is a low level interface that is aligned with
the VM. It is TBD to add some nice-feeling decorators and such.
* Custom types not yet plugged through, but I expect that this could be
pretty nicely done and interop well with Python.
* There's likely a nice story …
> Add low level interface for defining VM modules in Python.

- runtime/bindings/python/hal.cc
- runtime/bindings/python/hal.h
- runtime/bindings/python/iree/runtime/__init__.py
- runtime/bindings/python/iree/runtime/function.py
- runtime/bindings/python/tests/function_test.py
- runtime/bindings/python/tests/vm_test.py
- runtime/bindings/python/tests/vm_types_test.py
- runtime/bindings/python/vm.cc
- runtime/bindings/python/vm.h
Previously, the VM was depending on HAL, which made this impossible.
Severs the dependency and make VmVariantList operate on generic
reference types. Refactors call sites to cast explicitly to their
expected types.
Eliminates APIs:
* VmVariantList.get_as_buffer_view() (use get_as_ref() or
get_as_object())
* VmVariantList.push_buffer_view() (use push_ref()).
Changed APIs:
* VmVariantList.get_variant() now returns a VmRef instead of a casted
object.
All of these are fairly internal APIs that users should not have likely
used yet.
* Adds Python binding for an iree_vm_buffer.
> Make HalBufferView a VM Ref object in Python.

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/IR/test/dispatch_ops.mlir
A `region` op contains all ops that form a dispatch region. Fusion
heuristics should generate `region` ops. These can then be
lowered to a dispatch region, at which point the op becomes isolated
from above.
> Add dispatch.region op to Flow dialect

- docs/website/docs/building-from-source/riscv.md
- tests/riscv32/smoke.sh
- tests/riscv64/lit.cfg.py
- tests/riscv64/smoke.sh
* Remove QEMU vector setting for non-vector emulation in rv32
* Use vlen=512 for v-ext emulation to align with `benchmarks/` setup
* Update the e2e model path to align with `benchmarks/` setup
> Clean up RISC-V CI RVV config

- build_tools/docker/manage_images.py
This is useful when the digests somehow get out of sync, as happened in
https://github.com/iree-org/iree/pull/9983. I can turn it into a lint
check too.
Also updates quote style to be consistent with all our other Python
stuff.
> Allow updating docker digests without rebuilding

- build_tools/cmake/iree_cc_library.cmake
For any generator that can handle multiple configurations (MSVC,
ninja with `-GNinja Multi-Config`, etc) the `$<CONFIG>` generator
expression must be included in the file name.
Docs:
https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html#custom-commands
> Fixing iree_cc_unified_library debug output file name aliasing.

- CMakeLists.txt
With #9474 the compiler inputs and outputs are always reported even
though the compiler might not be built (e.g. when only building the
runtime). This can be confusing for example when using a snapshot
install of the compiler that generates the workload (especially if it
should generate a C source module) which is than cross-compiled together
with the runtime (this the case in iree-bare-metal for example). With
this patch inputs and outputs (non at all in the example given before)
are only reported when building the compiler.
> Don't report compiler specifics if not built

- build_tools/cmake/build_and_test_asan.sh
Looks like the ASan Vulkan/SwiftShader crash we have in a few other tests:
https://github.com/iree-org/iree/runs/7675754080?check_suite_focus=true
```
976/998 Test   #41: iree/tests/e2e/models/fragment_000.mlir.test .............................................................................***Failed    8.92 sec
-- Testing: 1 tests, 1 workers --
FAIL: IREE :: e2e/models/fragment_000.mlir (1 of 1)
******************** TEST 'IREE :: e2e/models/fragment_000.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   iree-run-mlir --iree-input-type=mhlo --iree-hal-target-backends=vmvx /home/runner/actions-runner/_work/iree/iree/tests/e2e/models/fragment_000.mlir --function-input="f32=0" --function-input="5x1xf32=[1][-2][-3][4][-5]" --function-input="f32=1" …
```
> Exclude fragment_000.mlir.test from ASan build.

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertRegionToWorkgroups.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/region_to_workgroups.mlir
This pass converts `dispatch.region` ops into `dispatch.workgroups` ops. This can eventually replace the part of DispatchLinalgOnTensors that builds the `workgroups` ops. The op is built in one step, and there is no need for dropping operands/block arguments due to tieing etc.
What is still missing a transform that builds the `region` op based on a heuristic such as the one in DispatchLinalgOnTensors. This heuristic should put all ops that are needed in the dispatch region into the region. I.e., this transform should handle both fusion and cloning.
> Add ConvertRegionToWorkgroups pass

- tests/e2e/regression/layernorm.mlir
- tests/e2e/regression/softmax.mlir
When a function is marked as private, an inlining pass removes it
and leaves the module empty, which is not desirable for testing.
> [test] remove `private` from func.func

- tests/e2e/regression/BUILD
- tests/e2e/regression/CMakeLists.txt
Tracking issue: https://github.com/iree-org/iree/issues/10024
> [vulkan] Disable layernorm while fixing failures on Pixel 6

- build_tools/third_party/tracy/CMakeLists.txt
This fixes the build with `IREE_BUILD_TRACY` on our release Docker image. See a sample failure here: https://github.com/iree-org/iree/actions/runs/2817051970
Tested with `override_python_versions="cp39-cp39" packages="iree-runtime-instrumented" output_dir="/tmp/wheelhouse" ./build_tools/python_deploy/build_linux_packages.sh` before and after.
This check fails:
```
pkg_check_modules(TRACY_GTK_DEPS
freetype2
glfw3
gtk+-3.0
dbus-1
)
```
but we were still building the imgui sources that use `glfw3`:
```
FAILED: tracy/CMakeFiles/IREETracyIMGUI.dir/__/__/__/third_party/tracy/profiler/src/imgui/imgui_impl_glfw.cpp.o
/opt/rh/devtoolset-10/root/usr/bin/c++  -I/main_checkout/iree/build_tools/third_party/tracy/../../../third_party/tracy/imgui -I/usr/include/capstone -I/usr/include/capstone/capstone …
```
> Tweak Tracy CMake config so release build works again.

- .gitignore
We don't want these getting checked in to the repository. The
particular motivation is that the Cuda on-demand download drops the
archives in the repository root and I've been carrying them around as
untracked files. That's theoretically supposed to change, but I think
ignoring archives is probably good anyway.
> gitignore archives

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.h
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/IR/test/dispatch_workgroups_folding.mlir
Add a canonicalization pattern that removes unused results from dispatch
regions. Also exposes this canonicalization as a transform dialect ops,
such that the canonicalization can be applied without running the
GreedyPatternRewriter.
> Remove unused results from DispatchRegionOps

- tests/e2e/regression/reduction_broadcast_elementwise.mlir
As Tosa lowering is getting uppdated (https://reviews.llvm.org/D131426) we
should use maxf to hit the interesting case in IREE.
> Update reduction_broadcast test to use arith.maxf

- build_tools/buildkite/cmake/android/arm64-v8a/pipeline.yml
spotted here: https://github.com/iree-org/iree/pull/10027#discussion_r941518677
failing build: https://buildkite.com/iree/iree-test-android/builds/6875
logs: `[2022-08-09T01:33:11Z] docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "build_host_and_android.sh": executable file not found in $PATH: unknown.`
> Fix path to build_host_and_android.sh.

- runtime/src/iree/base/internal/flags.c
- runtime/src/iree/base/testing/BUILD
- runtime/src/iree/base/testing/dynamic_library_test.cc
This wasn't caught before as most flag parsing happens on the libc heap
allocations but in future changes to iree-run-mlir we parse from an
std::vector with proper instrumentation and asan catches it.
For unknown reasons the bazel CI fails the dynamic_library_test with this
change, even though the updated function is never called (confirmed with
an `abort()` in the function) and with the entire gtest->flags dependency cut 👻
> Fixing flag argv truncation.

- compiler/src/iree/compiler/Codegen/Common/DecomposeLinalgGeneric.cpp
The upstream decompose ops pattern is intended to work with
`linalg.generic` canonicalization pattern. So pull the
`linalg.generic` op canonicalization pattern with the decompose
operation pattern.
> Add `linalg.generic` op canonicalization after decomposition.

- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/IR/test/dispatch_tensor_folding.mlir
When the values in these operand lists are defined by an
`arith.constant`, the value is replaced with the integer
directly. This also fixes the `tensor.cast` ->
`flow.dispatch.tensor.store` operation folding to only fold if the
target of the cast is more dynamic than the source.
> Canonicalize offset, sizes and strides for `flow.dispatch.tensor.store`.

- compiler/src/iree/compiler/Codegen/Common/test/transform_dialect_apply_pattern_op.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_bufferize_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_vector_distribution_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_vector_warp_execute_on_lane_0_spec.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dialect_dispatch_spec.mlir
- tests/e2e/linalg_transform/transform_dialect_codegen_spec.mlir
- tests/e2e/linalg_transform/transform_dialect_dispatch_spec.mlir
This is a more lightweight way of matching for ops in the transform
dialect.
> [NFC] Replace pdl.pattern with structured.match

- .github/workflows/ci.yml
Based on calculations and discussion in
https://github.com/iree-org/iree/issues/10042, we can now run these on
presubmit without it being to long or costly.
> Turn on GPU tests on presubmit

- .github/workflows/ci.yml
This gives a switch for the big binary decision point of "I'm not 
editing code". We determined that we don't have a compelling use case
for picking and choosing which checks run, at least for now. See
https://github.com/iree-org/iree/issues/10042. Note that a status of
"skipped" still counts as "passing" for GitHub's required checks, which
seems wrong to me, but is ok for this use case (otherwise we would
still run the summary and let it compute that everything had been
skipped.
There's a lot of repetition here. Unfortunately, GitHub actions don't
have any sort of variables, not even the standard yaml anchors, and our
best proxy for them, global `env` variables, doesn't work because the
`env` context is not available in the if condition (see …
> Allow skipping CI with a label

- .github/workflows/ci.yml
Part of https://github.com/iree-org/iree/issues/10042.
https://github.com/iree-org/iree/pull/10055 lets someone manually skip
CI for their PRs, but this will make it automatic for a big chunk of
things that can't possibly (famous last words) affect the build. Note 
that this doesn't apply to lint checks.
> Ignore certain filepaths in CI

- compiler/src/iree/compiler/Codegen/Common/TransformDialectInterpreterPass.cpp
- compiler/transform_dialect/gpu/reduction/reduction.mlir
- compiler/transform_dialect/gpu/reduction/transform_dialect_codegen_spec.mlir
- compiler/transform_dialect/gpu/reduction/transform_dialect_dispatch_spec.mlir
Add and e2e CUDA transform dialect example.
This shows an example of e2e codegen driven by fine-grained transform dialect strategies.
The target is controlled warp distribution of a reduction op.
This exhibits the need to have a place to put such transform dialect IR such that we can from a
centralized place and with the same tooling:
1. write an iree-opt test that checks expectes IR without having to write HAL abstractions.
2. write an e2e execution test to check results w/ accuracy etc.
3. selectively import as an expert strategy and use without surprises in IREE, when the time comes.
A first tentative location for this is in `compiler/transform_dialect/`.
The GPU-specific transforms are relaxed to allow targeting either hal.executable or hal.executable.variant
which lets them apply …
> Add an e2e CUDA transform dialect example.

- .github/workflows/ci.yml
Using `paths-ignore` as I attempted in
https://github.com/iree-org/iree/pull/10057 doesn't work because we
need the "summary" job to run and post its status. This method will
allow us to implement arbitrary logic for whether to run (including
looking at the paths). If we want to be able to determine *which* jobs
should run dynamically, then we can have this output a JSON list
instead and test whether the job name is in the list, as I demoed in
https://github.com/iree-org/iree/pull/10044. That's a lot of repeated
checks though, so holding off until we need it (and maybe I've
implemented something to generate these files).
> Use more extensible method for determining whether to run jobs

- runtime/src/iree/hal/drivers/local_task/task_command_buffer.c
- runtime/src/iree/hal/local/inline_command_buffer.c
- runtime/src/iree/hal/local/loaders/embedded_elf_loader.c
- runtime/src/iree/hal/local/loaders/system_library_loader.c
- runtime/src/iree/hal/local/loaders/vmvx_module_loader.c
- runtime/src/iree/hal/local/local_executable.h
The inline HAL does not need them and they were always somewhat
optional for tooling like executable_library_benchmark given that
the packing of bindings is well-defined. We still need them for the
full HAL which may have sparse bindings as part of one or more
descriptor sets that are shared across many dispatches.
Part of #9945.
> Making executable layouts optional for local executables.

- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/BUILD
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/ConvertBufferOps.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/test/buffer_ops.mlir
Previously this would result in a mistyped size i64 even when index
was lowered to i32 in other parts of the program.
> Fixing util.buffer.size -> vm.buffer.size result type conversion.

- README.md
We get one status badge per workflow here, not per job. Since it's now
only one badge, I moved it up to the top instead of having a whole
section for one tiny image.
> Update status badge to use GitHub actions

- .github/workflows/ci.yml
Right now, we build every time someone pushes, which is quite wasteful.
There are some use cases for finishing in-progress runs because we
might be close to creating a cacheable artifact, but we don't have
those yet, and for now this should avoid a lot of unnecessary builds.
Tested: You can see the run for 07241b5088 was cancelled when I pushed
another commit fixing up some leftover debugging.
> Use a concurrency group to avoid unnecessary CI runs

- .github/workflows/ci.yml
There is something wrong with the GPU MIG. The machines keep
immediately shutting down. I don't have time to investigate this
evening, so disabling these until I can debug. Luckily, we still have
the Kokoro postsubmits for GPU, so we're not in any worse shape than
we were before :-)
> Disable GPU builds

- benchmarks/TF/linux-x86_64.cmake
- benchmarks/TFLite/android-arm64-v8a.cmake
- benchmarks/TFLite/linux-riscv.cmake
- benchmarks/TFLite/linux-x86_64.cmake
- build_tools/benchmarks/README.md
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_driver_test.py
- build_tools/benchmarks/common/benchmark_suite_test.py
- build_tools/benchmarks/common/benchmark_thresholds.py
- build_tools/benchmarks/comparisons/README.md
- build_tools/benchmarks/comparisons/run_benchmarks.py
- build_tools/benchmarks/comparisons/setup_desktop.sh
- build_tools/benchmarks/comparisons/setup_mobile.sh
Progress on https://github.com/iree-org/iree/issues/9930
This changes the "friendly" series names from `IREE-Dylib`/`iree-dylib` and `IREE-Dylib-Sync`/`iree-dylib-sync` to `IREE-LLVM-CPU`/`iree-llvm-cpu` and `IREE-LLVM-CPU-Sync`/`iree-llvm-cpu-sync`.
All flags and comments were also updated to the `llvm-cpu` target backend name and `local-task` HAL driver name.
---
Please review carefully - I have not ran any of these scripts or builds myself, I only made text replacements to bring these names in line with the current state of the project.
I believe **this will also need changes to the existing data backing https://perf.iree.dev/**, can someone help with that, after reviewing?
> Update benchmarks to use "llvm-cpu" and "local-task" names consistently.

- compiler/src/iree/compiler/Dialect/HAL/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/HAL/Transforms/Passes.h
This is useful to isolate the control for running HAL configuration from the triggering of codegen.
> Add a registerHALConfigurationPassPipeline

- compiler/src/iree/compiler/API/python/iree/compiler/tools/__init__.py
- compiler/src/iree/compiler/Codegen/Common/test/remove_trivial_loops.mlir
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/aarch64_dotprod_vector_lowering.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/apply_scale_lowering.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/illegal_configuration.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_aarch64_launch_configuration.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_riscv_launch_configuration.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_x86_64_launch_configuration.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/peel_and_vectorize.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/pipeline_tests.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/test_config_mmt4d.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/transpose_avx2_lowering.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/triple_tiling_expert_pipeline.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/test/cmd_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/IR/HALBase.td
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/test/smoketest_embedded.mlir
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/test/smoketest_system.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/convert_to_hal.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/dump_executable_benchmarks.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/dump_executable_sources.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/materialize_interfaces.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/materialize_resource_caches.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/verify_target_environment.mlir
Removed: `cpu`, `llvm`, `dylib`, `dylib-llvm-aot`
Use `llvm-cpu` instead
See https://github.com/iree-org/iree/issues/9930 and https://groups.google.com/g/iree-discuss/c/N-BBCURS7g4/
> Remove legacy and abbreviated llvm-cpu target name registrations.

- tests/e2e/regression/BUILD
- tests/e2e/regression/CMakeLists.txt
- tests/e2e/regression/disable_demote_f64_to_f32.mlir
Adding a test to ensure -iree-flow-demote-f64-to-f32=false flag stops demoting f64 promotions and computations to f32. This is to close https://github.com/iree-org/iree/issues/9961
> Test to disable -iree-flow-demote-f64-to-f32 and check correctness of f64-based computations

- .github/workflows/ci.yml
- build_tools/github_actions/should_ci_run.py
As noted in https://github.com/iree-org/iree/pull/10062, we can't use
the GitHub actions built-in paths-ignore feature because it doesn't
work well with required checks. Instead, we use a custom script and a
job to determine whether to run CI. This could later be extended to
determining which other jobs to run.
> Use custom script to determine whether to run CI

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dispatch_region_formation.mlir
This commit adds two new transform dialect ops:
* WrapInDispatchRegionOp: Warp an arbitrary op in a new
`dispatch.region` op.
* PullPrecedingOpIntoDispatchRegionOp: Move a preceding op into an
existing `dispatch.region` op.
These ops will be used to build heuristics for dispatch region
formation.
The implementation of both ops is purpusely inside of static functions,
such the rewrite logic could be called from C++ without using the
transform dialect, if necessary.
> Add transform dialect building blocks for dispatch region formation

- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LinkerTool.cpp
Leftover from the `iree/tools/` -> `tools/` move. I noticed this when trying to find `wasm-ld` from a regular build (i.e. without setting up the Emscripten SDK or putting a tool directly on my path).
> Fix relative path used to search for linker tools.

- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp
- experimental/web/sample_static/device_multithreaded.c
- experimental/web/sample_static/device_sync.c
Fixes https://buildkite.com/iree/iree-samples/builds/442
* Use `_` instead of `-` in names, as they will appear in C++ identifiers (a more general name sanitization might be better than this bandaid)
* Update static library name from 'llvm' to 'llvm_cpu'
```
[2022-08-13T00:19:29Z] In file included from /usr/src/github/iree/experimental/web/sample_static/device_sync.c:9:
[2022-08-13T00:19:29Z] /usr/src/github/iree/build-emscripten/experimental/web/sample_static/mnist_static.h:11:67: error: extra tokens at end of #ifndef directive [-Werror,-Wextra-tokens]
[2022-08-13T00:19:29Z] #ifndef IREE_GENERATED_STATIC_EXECUTABLE_LIBRARY_MNIST_LINKED_LLVM-CPU_
[2022-08-13T00:19:29Z]                                                                   ^
[2022-08-13T00:19:29Z] …
```
> Fix executable names for web samples.

- compiler/src/iree/compiler/Dialect/HAL/Target/WebGPU/WebGPUTarget.cpp
This fixes the build with `-DIREE_TARGET_BACKEND_WEBGPU=ON` (no CI for that yet, and I haven't tried to build it for months either)
> Used prefixed form for accessors in WebGPUTarget.

- .github/workflows/ci.yml
The GPU runners had an outdated version of the GitHub runner, which was
causing runner startup to fail and the instances too bootloop. I've
updated the image, so they are working now and we can re-enable.
Fixes https://github.com/iree-org/iree/issues/9856
> Re-enable GPU tests

- build_tools/cmake/iree_copts.cmake
- integrations/tensorflow/iree-dialects/CMakeLists.txt
- llvm-external-projects/iree-dialects/CMakeLists.txt
With llvm/llvm-project@112499f landed, `MLIR_TABLEGEN_EXE` is now set as
a cache variable by the MLIR core project. Hence, there is no need to
set it explicitly and doing so indeed breaks cross-compiling.
It might be necessary to wait for the integrate commit that lands commit
llvm/llvm-project@112499f, before this one can be merged.
> Don't explicitly set MLIR_TABLEGEN_EXE

- .github/workflows/ci.yml
- build_tools/github_actions/should_ci_run.py
As discussed in https://github.com/iree-org/iree/issues/10042, we
discovered that using a label doesn't work for the very important
case of when the PR is just created, so we're shifting to use the PR
body instead.
Tested: Created this PR with "skip-ci" as the entire body, which
resulted in correctly skipping the CI. Also added some additional lines
before and after, and CI was still correctly skipped. Finally, this PR
body as written contains the string, but not on its own line and CI is
not skipped.
Just skip-ci: https://github.com/iree-org/iree/runs/7866417853
With other content in the PR body:
https://github.com/iree-org/iree/runs/7866417853
> Use string in PR description instead of label to skip CI

- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToLinalgOnTensors.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/mhlo_to_linalg.mlir
The upstream pattern is going to be retired. It's not a proper way to
lower a mhlo.scatter op. Ideally, we should move them to LinalgExt path.
This is a workaround to not regress mhlo.scatter support in IREE.
> Copy the upstream mhlo.scatter -> Linalg pattern to IREE.

- integrations/tensorflow/iree_tf_compiler/TF/LowerGlobalTensors.cpp
Without this builds without `NDEBUG` fail with an error about defining
explicit type IDs. I think the correct fix is really to have these
passes defined with ODS instead of using the static pass registration
that has been discouraged for years, but TF doesn't do that and we
don't try to clean up TF's messes here.
This wasn't caught in OSS because TF in OSS is unbuildable without
`NDEBUG`. Internally we can still manage to do that though, so I got
failures when integrating into our internal source control.
The error is:
> LLVM ERROR: TypeID::get<mlir::iree_integrations::TF::(anonymous namespace)::LowerGlobalTensors>(): Using TypeID on a class with an anonymous namespace requires an explicit TypeID definition. The implicit fallback uses string name, which does not guarantee uniqueness in …
> Remove anonymous namespace causing TypeID failures

- runtime/src/iree/base/internal/file_io_test.cc
as in ctest --repeat-until-fail 10 -j 10
The issue was that GetUniquePath would return the same path in
multiple processes so the assumption that the path didn't actually
exist would get defeated.
> file_io_test was noisy when run on multiple parallel processes

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.h
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertRegionToWorkgroups.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertRegionToWorkgroups.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dispatch_region_formation.mlir
This op is useful in combination with
`iree-flow-dispatch-use-transform-dialect` in order to experiment with
dispatch region formation with the transform dialect, while also running
the remaining Flow transformation pipeline.
> Add region_to_workgroups transform

- build_tools/cmake/build_and_test_tsan.sh
- build_tools/cmake/ctest_all.sh
In the past I used GNU Parallel for this, but this just uses `ctest --repeat-until-fail`. The downside is that `ctest` won't use more threads than there are tests to run (it wants all tests to complete repetition N before letting any start repetition N+1). This is mitigated by running more tests than strictly needed --- this is running all `iree/base/` and `iree/task/` tests. This still completes very quickly -- each repetition adds only 1 second of real latency on my cloudtop. And by running more tests we also create more entropy which also helps hit more bugs (some TSan failures never reproduce when rerunning 1 test in a loop and only reproduce when running multiple tests concurrently). Moreover, by rounding up the set of tests to whole directories `iree/base/` and `iree/task/` we are …
> TSan testing: rerun certain cheap tests many times

- runtime/bindings/python/py_module.cc
- runtime/bindings/python/vm.h
We don't build these with Bazel in OSS, so we don't have the layering
check to catch these issues, but this came up when importing into
Google's monorepo.
> Remove vm includes in Python bindings that violate layering

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUAArch64VectorLowering.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_aarch64_launch_configuration.mlir
This is the first round of tuning for ARM normal convolution codegen. The parameters are derived from experiments for 3x3 kernel cases.
Benchmark file:
```mlir
util.global private @"__iree_flow_lhs" {noinline} = dense<1.0> : tensor<1x51x41x512xf32>
util.global private @"__iree_flow_rhs" {noinline} = dense<1.0> : tensor<3x3x512x512xf32>
func.func @conv_3x3filter() ->tensor<1x25x20x512xf32> {
%lhs_ptr = util.global.address @"__iree_flow_lhs" : !util.ptr<tensor<1x51x41x512xf32>>
%rhs_ptr = util.global.address @"__iree_flow_rhs" : !util.ptr<tensor<3x3x512x512xf32>>
%lhs = util.global.load.indirect %lhs_ptr : !util.ptr<tensor<1x51x41x512xf32>> -> tensor<1x51x41x512xf32>
%rhs = util.global.load.indirect %rhs_ptr : !util.ptr<tensor<3x3x512x512xf32>> -> tensor<3x3x512x512xf32>
%cst = …
```
> Update default tiling sizes for ARM convolution configurations.

- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/Passes.cpp
Based on discussion at https://github.com/iree-org/iree/issues/10142#issuecomment-1223107567 . This "fixes" one case of `spv.IsNan` ops getting introduced while lowering of `arith.minf`, but it does not generally address NaNs coming from other sources (user-space or internal to the compiler).
The `ArithmeticExpandOpsPass` pass (declaration [here](https://github.com/llvm/llvm-project/blob/af29db64b2c7091070dd623c81872559657e7b3d/mlir/include/mlir/Dialect/Arithmetic/Transforms/Passes.td#L31-L34) and [here](https://github.com/llvm/llvm-project/blob/af29db64b2c7091070dd623c81872559657e7b3d/mlir/include/mlir/Dialect/Arithmetic/Transforms/Passes.h#L23-L24)) is overly specific to a particular lowering to LLVM. The `minf` and `maxf` lowerings in particular generate IR like
```mlir
%8 = arith.cmpf …
```
> Remove ArithmeticExpandOpsPass from SPIRV and VMVX lowerings.

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dispatch_region_formation.mlir
Support multiple target ops in clone_preceding_op_into_dispatch_region
The target ops are sorted topoloically before cloning them one-by-one.
This is to ensure that there are no dominance violations. (Same logic as
with the existing dispatch region formation.)
This PR depends on #9985. Only review the second change.
> Support multiple target ops in clone_preceding_op_into_dispatch_region

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dispatch_region_formation.mlir
This op is symmetric to `clone_preceding_op_into_dispatch_region` and
can be used to build heuristics for dispatch region formation.
This PR depends on #9985. Only review the second commit.
> Add clone_succeeding_op_into_dispatch_region transform op

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dispatch_region_formation.mlir
Support multiple target ops in clone_succeeding_op_into_dispatch_region
The target ops are sorted topologically before cloning them one-by-one.
This is to ensure that there are no dominance violations. (Same logic as
with the existing dispatch region formation.)
This PR depends on #10022. Only review the last commit.
> Support multiple target ops in clone_succeeding_op_into_dispatch_region

- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- compiler/src/iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/BUILD
- compiler/src/iree/compiler/InputConversion/MHLO/BroadcastingToLinalgPatterns.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/ConvertComplexToReal.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/broadcasting.mlir
- compiler/src/iree/compiler/InputConversion/MHLO/test/convert_complex_to_real.mlir
- integrations/tensorflow/WORKSPACE
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/roundtrip.mlir
* Reset third_party/llvm-project: 4332b049edf6ccf98c9e31dcc983760a89f01d40 (2022-08-23 17:37:12 +0800): [docs] Add examples for printing asynchronous stack for coroutines
* Updated tensorflow/tensorflow@55791c2
* Updated tensorflow/mlir-hlo@184a76a
* Fixed mhlo/chlo enum split.
> Integrate LLVM at llvm/llvm-project@4332b049edf6

- compiler/src/iree/compiler/Dialect/VMVX/Transforms/ResolveBufferDescriptors.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/test/resolve_buffer_descriptors.mlir
This unblocks e2e matmul testing for at least float32 on vmvx/ukernels (#10193).
> Handle rank-reducing subviews in ResolveBufferDescriptors

- .github/ISSUE_TEMPLATE/config.yml
Currently clicking the "Blank Issue" button loops you back to the issue choose page because blank issues are disabled.
When disabled, the following redirect is in place:
https://github.com/iree-org/iree/issues/new  --> https://github.com/iree-org/iree/issues/new/choose
Background: I based the StableHLO issues config off this file, and noticed that the blank issues are not working on that repo because they are disabled. Flipping this boolean did the trick in openxla/stablehlo.
> Allow blank issues to be created

- tests/e2e/matmul/generate_e2e_matmul_tests.py
Thomas's version of PyYAML does not know about `sort_keys`. Maybe we don't need it?
> try to be compatible with more pyyaml versions

- build_tools/bazel/iree_trace_runner_test.bzl
- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
This is unblocked by #10192.
Other types than `float32` are blocked on vmvx ukernels support for those (#9903).  I'm interested in landing float32 support early because the path to supporting other data types goes through breaking changes in the existing vmvx ukernel interface for matmul (limiting the generality of the BLAS-inspired interface, particularly the `alpha` and `beta` parameters) so I want to have e2e tests in place at the start of that process.
> Add e2e matmul tests on vmvx+ukernels (float32-only for now)

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
This is enabled using the
`--debug-only=iree-llvm-cpu-lowering-pass-pipeline` flag.
The SPIR-V codegen path has a similar option.
> Add debug option to dump LLVMCPU/GPU pass pipeline

- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
- compiler/src/iree/compiler/Codegen/VMVX/test/lower_linalg_microkernels.mlir
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/test/matmul.mlir
- compiler/src/iree/compiler/Dialect/VMVX/IR/VMVXOps.td
- compiler/src/iree/compiler/Dialect/VMVX/vmvx.imports.mlir
- runtime/src/iree/modules/vmvx/exports.inl
- runtime/src/iree/modules/vmvx/module.c
This makes the VMVX ukernel interface for matmul somewhat sustainable and generalizable.
It's official now that the only supported case is when all operands are row-major (more general support might be wanted in the future, but would have to allow separate storage orders for each operand in order to be likely to be used).
The only flag now is one bit to tell whether to accumulate into an existing accumulator, or just zero it. At the moment we always accumulate but could soon generate calls without the accumulate flag when compiling code where the accumulator operand is known to be zero-filled. In terms of optimized runtime code, it is nearly zero overhead to support that boolean degree of generality in the ukernel.
The "reference" ukernel impl is changed to be a little more suggestive of …
> Tidy the VMVX ukernels matmul interface

- tests/e2e/regression/softmax.mlir
The e2e softmax test uses `cmpf` -> `select` for max operations. Use
`maxf`instead. This allows the op to be vectorized. The TOSA to Linalg
lowering has been recently updated to do the same (and this test was
derived from using an older TOSA to Linalg lowering).
Related to PR #10177
> Change `softmax` test to use `maxf`.

- .github/workflows/build_package.yml
- build_tools/github_actions/build_dist.py
- build_tools/python_deploy/build_linux_packages.sh
- runtime/setup.py
This speed the linux builds up a bit, bringing the time for the longest
job down from ~5 hours to ~20 minutes. Note that this is *only* the
Linux jobs. The mac ones still take about 4 hours. This should still
help when iterating on the release though and for faster failure
indicators (it was indeed helpful when I was iterating here).
I ran into issues when testing because I was using a package suffix in
the workflow dispatch, which evidently had never actually been tested
because it was totally broken. This gave me a lot of wonderful
opportunity to bash my head against bash and I reworked a lot of the
`build_linux_package.sh` script. In retrospect, I wish I'd just removed
the `package_suffix` feature.
Test run: https://github.com/iree-org/iree/actions/runs/2923210349
skip-ci
> Build Linux releases on big managed runners

- compiler/src/iree/compiler/Codegen/Common/GPUDistributeSharedMemoryCopy.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileTensor.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TilingUtils.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tensor_alloc.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/vectorization.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
Transition mamul SIMT pipeline to do vectorization before bufferization.
This relies on alloc_tensor op to model shared memory promotion and
foreach_thread for the tiling at the tensor level.
Also simplify significantly the vectorization pass by removing patterns not needed anymore.
This will allow us to do more optimizations at the tensor going forward.
> [LLVMGPU] Move bufferization after vectorization for matmulSIMT

- .github/workflows/ci.yml
RISC-V 32/64 can be called either riscv32/riscv64 or rv32/rv64. Fixed several names in the CI workflow.
> Fix the typos of riscv names in CI

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUReduceBankConflicts.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
Currently only `32x32` aligned 2D transposes are supported. Based on https://developer.nvidia.com/blog/efficient-matrix-transpose-cuda-cc/, uses a fixed tile size of `32x32` and workgroup size of `{8x32}` to preform vectorized copy for transpose. The tile is padded to `32x33` to reduce bank conflicts. Note that bank conflicts aren fully eliminated due to use of vector load/store 4.
Todo:
* Move beyond single hard coded workgroup and tile size?
* Handle non aligned transpose
* Handle dynamic sized transpose
Related to #10005
> Implementation of GPU Shared Memory Transpose Pipeline

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorization.cpp
Prevent ambigous constructor call.
> Fix gcc build

- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/cmake/iree_c_module.cmake
- build_tools/cmake/iree_static_linker_test.cmake
To make the secondary function like iree_static_linker_test cleaner.
> Add iree_bytecode_module and iree_c_module static lib support

- benchmarks/TFLite/linux-riscv.cmake
Building the benchmarks is currently the critical path in CI latency,
taking almost 25 minutes for just that job, after it waits 25 minutes
for the TF integrations binaries (was that alway so slow??).
[![ci_run_graph](https://user-images.githubusercontent.com/5732088/187279027-21137775-5a3b-4ddf-ae4d-42e39051e7b2.png)](https://github.com/iree-org/iree/actions/runs/2950708667)
Of that time, 20 minutes is spent compiling this one vmfb, which we
only do so we can get statistics on how long it takes to compile. I
sampled the ten slowest build actions from a local build of the
benchmarks:
```
1179.39 benchmark_suites/TFLite/vmfb/mobilebert-baseline-tf2-quant.tflite.mlir-22179362840f853977acc734ee75e6ce.vmfb
216.321 benchmark_suites/TFLite/vmfb/mobilebert-baseline-tf2-quant.tflite.mlir-53b16b00b …
```
> Remove RV32 Mobile Bert Compilation Benchmark

- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
- compiler/src/iree/compiler/Codegen/VMVX/test/lower_linalg_microkernels.mlir
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/ConvertVMVXToVM.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/test/BUILD
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/VMVXToVM/test/mmt4d.mlir
- compiler/src/iree/compiler/Dialect/VMVX/IR/VMVXOps.td
- compiler/src/iree/compiler/Dialect/VMVX/vmvx.imports.mlir
- runtime/src/iree/modules/vmvx/exports.inl
- runtime/src/iree/modules/vmvx/module.c
This brings an initial (unoptimized, reference code only) mmt4d ukernel - both `f32f32f32` and `i8i8i32`.
It is covered by the e2e matmul tests: if you purposefully introduce a numerical bug in the ukernel function, `iree_vmvx_mmt4d_f32f32f32` then this test fails: `iree/tests/e2e/matmul/e2e_matmul_mmt4d_f32_small_ukernel_vmvx_local-task` . Ditto for `i8i8i32`.
That the whole reference code is for now in `module.c`, as opposed to being nicely isolated in `iree/builtings/ukernel`, is temporary. I have a few questions to ask about the placeholders in this directory, but it will be so much more concrete to discuss after we are done reviewing this PR so I hope that's OK to split as a separate code move for another PR.
A couple of nontrivial decisions in this PR:
* In …
> VMVX mmt4d ukernel

- .github/workflows/ci.yml
So it turns out that the postsubmit jobs were never actually writing to
the remote cache here. How were they still getting cache hits then?
Because until last week, the *Kokoro* postsubmit jobs were still
writing that cache. So given that they were running concurrently with
the GitHub jobs, we had a pattern that was totally consistent with
GitHub actions postsubmit jobs writing the cache: an initial build that
is slow followed by fast builds from a populated cache. The last Kokoro
build of the TF integration binaries was for
https://github.com/iree-org/iree/commit/e4dc88c3d1, so everything up to
that point was cached. When we next upgraded LLVM and invalidated a big
chunk of the cache, we no longer had anything writing it and builds
became very slow as they got no cache hits. Even more …
> Pass env variable instructing CI to write Bazel cache

- build_tools/bazel/iree_bytecode_module.bzl
- build_tools/bazel/iree_c_module.bzl
- build_tools/bazel_to_cmake/bazel_to_cmake_converter.py
- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/cmake/iree_c_module.cmake
- build_tools/cmake/iree_static_linker_test.cmake
Add STATIC_LIB_PATH option instead of parsing the compiler flags
> Refactor iree_bytecode_module and iree_c_module static lib support

- experimental/web/sample_static/device_multithreaded.c
- runtime/src/iree/base/internal/synchronization.c
- runtime/src/iree/base/internal/synchronization.h
- runtime/src/iree/task/api.c
- runtime/src/iree/task/api.h
- runtime/src/iree/task/executor.c
- runtime/src/iree/task/executor.h
- runtime/src/iree/task/executor_demo.cc
- runtime/src/iree/task/executor_impl.h
- runtime/src/iree/task/executor_test.cc
- runtime/src/iree/task/post_batch.c
- runtime/src/iree/task/testing/task_test.h
- runtime/src/iree/task/tuning.h
- runtime/src/iree/task/worker.c
- runtime/src/iree/task/worker.h
- tools/iree-benchmark-module-main.cc
- tools/iree-run-module-main.cc
The major addition is the `--task_worker_spin_us=` flag (and `iree_task_executor_options_t` struct for the API) that allows users to opt in to having the workers spin before waiting. There's no good default for that value (depends on both workloads and machine) so by default it's set to 0 ("don't spin").
The utility of spinning appears almost exclusively in single-tenant latency-sensitive workloads that don't have much/any built-in concurrency (mostly old models like resnet). Even in those cases the tradeoff is usually saving hundreds of microseconds wall time for hundreds of milliseconds of burned CPU time and it's unclear how badly the spinning pessimizes the memory subsystem (as each spinning thread is hammering shared memory). Future improvements to iree-benchmark-module will allow …
> Rollup of latency improvements to the task system.

- build_tools/bazel/iree_c_module.bzl
- build_tools/cmake/iree_c_module.cmake
`iree_cc_library` has to include non-header source code to create the
static library. Add the stub source file and depenency back to ensure
the library is built.
> Fix iree_c_module function to generate the useful library

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingInterface.cpp
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
The TileAndDistributeToWorkgroups could only handle cases where fused
producer has a single use. For multiple uses, each use would introduce
new instance of the tiled producer with tile + fuse. To address this
add a `TileAndFuse` pattern that fuses the producer right after
tiling. This allows updating multiple uses of the producer and also
update the `flow.dispatch.tensor.store` operations to use tiled
versions of this operation. This also allows handling dispatches where
multiple results are returned.
Issue #10228
> Handle multi-result operations and dispatches.

- .github/workflows/ci.yml
- build_tools/cmake/build_riscv.sh
Add a CI job to build benchmark tools and upload them to GCS.
This job uses the matrix to generate build parameters for different target platforms. The RISC-V build script is also standardized so the matrix can use generic parameters to config the build.
> Add CI job to build benchmark tools

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- tests/transform_dialect/cuda/reduction.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
Add a new option so that we can run transformer dialect after tile and
distribute on workgroup. This allows bypassing the problem of setting
the number of workgroups. For now we just pass a tile size through
command line.
This will then allow writing transform dialect pipelines decided by
KernelConfig. Later the transform dialect can evolve to do the tile and
distribute to workgroup.
> Add experimental path to use transformer dialect only in the codegen

- experimental/web/testing/index_template.html
- experimental/web/testing/test-runner.html
Still more to do around running batches of tests, but this makes the test runner a bit nicer to work with.
Before (wide, note the overflow and whitespace on the sides):
After (wide):
After (narrow, note the wrapping):
> Refine web test runner style (text wrapping, console colors, etc.).

- build_tools/github_actions/runner/config/register.sh
Makes runners indicate their environment (prod/testing), the config
version they're using, and the GitHub runner version they're using. We
can use these to differentiate runners in testing clusters, which
allows safely creating them without affecting normal runs. Of course,
for testing this, I had to spin up the test runners and they can
potentially get used by normal runs.
Tested: https://github.com/iree-org/iree/pull/10298 targets the testing
runners.
skip-ci
> Add labels identifying runner release and environment

- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
Now that we upgraded our CI we don't need to have this workaround by default. We can later remove the code altogether once we are sure we don't need to support older CUDA versions.
> Disable nounroll workaround for CUDA 11.3

- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_vector_distribution_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_vector_warp_execute_on_lane_0_spec.mlir
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_dispatch_spec.mlir
Add softmax transform dialect spec and run it e2e.
This revision adds a transform dialect spec that allows more advanced intermixing
of tiling to threads using `scf.foreach_thread` and later mapping an `scf.if(threadIdx.x)`
region to warps.
This ordering requires a legalization phase that ensures no value that
transitively depends on `threadIdx.x` is used in the region.
Atm this legalization is brittle, a more powerful analysis related to a scoped SCCP is
left for future work.
This e2e exploration also exhibited a bug in `clone_preceding_op_into_dispatch_region`
which did not properly propagate empty handles.
The whole example runs end to end, nvprof shows:
```
EXEC @max_sub_exp
==4061710== Profiling application: iree-run-module --entry_function=max_sub_exp --device=cuda
==4061710== …
```
> Add softmax transform dialect spec and e2e test

- .github/workflows/ci.yml
Tested: configuration with environment specified is in canary and
presubmits for this PR will run on those runners. I'll roll it out to
100% before submitting this.
> Specify runner environment that jobs should target

- build_tools/github_actions/runner/config/chown_workdir.sh
- build_tools/github_actions/runner/config/cleanup_workdir.sh
- build_tools/github_actions/runner/config/deregister.sh
- build_tools/github_actions/runner/config/github-actions-runner-deregister.service
- build_tools/github_actions/runner/config/github-actions-runner-start.service
- build_tools/github_actions/runner/config/register.sh
- build_tools/github_actions/runner/config/runner.env
- build_tools/github_actions/runner/config/setup.sh
- build_tools/github_actions/runner/config/start.sh
- build_tools/github_actions/runner/config/validate_trigger.postsubmit.sh
- build_tools/github_actions/runner/config/validate_trigger.releaser.sh
- build_tools/github_actions/runner/gcp/startup_script.sh
The installation is just extracting an archive, so is not costly. This
makes the runner more decoupled from its boot disk. It allows us to
upgrade the runner version (which we'll need to do frequently) without
creating a whole new VM image (which is a pain and requires full VM
replacement to update). The tmpfs also gives us better IO performance,
which should speed a few things along (though we already give Docker a
tmpfs, so the difference won't be huge). It should allow us to switch
to a much simpler base image that just has a few dependencies
installed, rather than the current image, which I accidentally made 1TB
and is the product of much messing around.
Tested: https://github.com/iree-org/iree/pull/10298 targets the testing
runners which are using this config.
skip-ci
This is the …
> Install GitHub runner on startup in a tmpfs

- build_tools/cmake/build_and_test_asan.sh
See https://github.com/iree-org/iree/issues/5716. I just excluded all lit tests from here: https://github.com/iree-org/iree/blob/db6b68773e4daab4da2de1e835c16c4323b583ec/tests/e2e/models/CMakeLists.txt#L13-L24
As there are other tests in that file using runners other than `lit` that have _not_ crashed (that I'm aware of), I did not exclude the entire directory.
Most recent failure: https://github.com/iree-org/iree/runs/8146877750?check_suite_focus=true
```
1030/1030 Test   #46: iree/tests/e2e/models/resnet50_fake_weights.mlir.test ....................................................................***Failed   63.16 sec
-- Testing: 1 tests, 1 workers --
FAIL: IREE :: e2e/models/resnet50_fake_weights.mlir (1 of 1)
******************** TEST 'IREE :: e2e/models/resnet50_fake_weights.mlir' …
```
> Exclude more tests from ASan test configuration.

- .gitignore
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_bufferize_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
- tests/e2e/linalg_transform/transform_dialect_codegen_spec.mlir
- tests/transform_dialect/cpu/matmul_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
This is necessary as bufferize uses replaceOp and old ops get destroyed. Although all examples use bufferize as a barrier for transforms, certain transform dialect sanity checks do not like ops not being properly tracked.
Invalidating and recreating the handle is significantly easier than tracking with a Listener atm.
> Add target and result to transform.iree.bufferize

- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transpose_pipeline_test.mlir
Test cases isolated to just the `LLVMGPULowerExecutableTargetPass`. Will be used for future transpose shared memory lit tests. 
Part of #10005
> Add Transpose Pipeline Test for LLVMGPULowerExecutableTargetPass

- build_tools/github_actions/runner/gcp/update_instance_groups.py
Dry-run is always a nice feature.
The existing filtering scheme using '.*' for group and type was
matching other components of the MIG name and picking up testing MIGs
even when environment was set to "prod".
Having a filter for region allows limiting to regions where we actually
have instance groups, which speeds things up quite a bit. We *could*
just list them in the script, which would avoid the call to list
regions entirely. I avoided this because I didn't want to bake too many
assumptions into the script, but IDK if that was the right call.
skip-ci
> Add dry-run and expanded filtering options to update script

- .github/workflows/ci.yml
- build_tools/cmake/build_host_and_riscv.sh
- build_tools/cmake/build_riscv.sh
- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_native_test.cmake
- build_tools/cmake/test_riscv64.sh
- tests/riscv64/smoke.sh
* Add the cross compile support to compile RISC-V compatible vmfb modules for iree_check_test
* Attach RISC-V QEMU Linux emulator to iree_native_test
* Extend riscv64 smoke test to cover tests/e2e/{tosa_ops, xla_ops, models} tests
> Add RISC-V cross compile/run support for iree_check_test

- benchmarks/TF/CMakeLists.txt
- benchmarks/TF/linux-cuda.cmake
- benchmarks/TF/linux-x86_64.cmake
As the offline discussion, we care more about the MiniLM performance with seqlen=128 instead of the current seqlen=512.
This change will create a new series of MiniLM with seqlen=128, and the old one will be inactive and hidden.
> Replace MiniLM benchmark with seqlen=128 version.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertConv2DToImg2Col.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/conv2d_to_img2col.mlir
This would require to create another batch dimension when performing the matrix multiplication. However the batch dimension only exists for input and output. Therefore we cannot use existing linalg named ops like linalg.batch_matmul; doing it with a linalg.generic instead.
>  Add support for non-1 batch cases in img2col convolution pass

- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/mhlo_to_mhlo_preprocessing_canonicalize_dot_general.mlir
Missed the case where there are no contraction dimensions for general_dot
converting to mhlo.mul. Needed to rework and guarantee we don't run the
dot general lowering before mul (produces excess code).
> Rework GeneralDot lowerings for mul/general_dot conversion

- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/cmake/iree_cc_test.cmake
- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_native_test.cmake
- build_tools/cmake/riscv.toolchain.cmake
- build_tools/cmake/run_riscv64_test.sh
- build_tools/cmake/test_riscv64.sh
- runtime/src/iree/base/internal/BUILD
- runtime/src/iree/base/internal/CMakeLists.txt
- runtime/src/iree/base/testing/CMakeLists.txt
- runtime/src/iree/tooling/BUILD
- runtime/src/iree/tooling/CMakeLists.txt
* Add RISCV cross compile flags in `iree_bytecode_module.cmake`
* Attach QEMU emulator to `iree_cc_test.cmake`
Qemu userspace emulator doesn't support fileIO. Disable tests that read/write files.
RISC-V doesn't have a specific FPU subnormal behavior listed (follows IEEE754-2008). Disable the fpu_state_test for RISCV.
> Add RISC-V 64-bit Linux unit tests

- compiler/src/iree/compiler/Dialect/Stream/IR/StreamOps.cpp
- compiler/src/iree/compiler/Dialect/Stream/IR/StreamTypes.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/PackConstants.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/pack_constants.mlir
- compiler/src/iree/compiler/Dialect/Util/IR/UtilAttrs.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilBase.td
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/ArchiveWriter.cpp
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp
This allows size queries as used in most of the compilation flow to ask
the attributes for their size and verify on attribute types. It's not
currently serializing the contents and will fail, but now we also
properly emit the error instead of crashing.
Instead of assertions as before failures now look like:
```
invalid_constants.mlir:7:3: error: constant attribute failed to serialize: unsupported format or encoding
vm.rodata private @elided_resource dense_resource<__elided__> : tensor<768x3072xi8>
```
For the special case of elided attributes a new opt-in flag allows zeros
to be written: `--iree-util-zero-fill-elided-attrs`. This should make it easier
to get repros for compilation errors even if at runtime the results will be
wrong.
Fixes #10345.
> Starting support for resource attribute serialization.

- integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp
`ValueOrDie()` is deprecated and will be removed soon
> Update TF code from ValueOrDie() to value().

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transpose_pipeline_test.mlir
Updates transpose detection and shared mem promotion to support fusion with non transposed operands.
KernelConfig now identifies transposes based on individual operands that meet the criteria for shared mem usage then chooses the TransposeSharedMem pipeline. 
LLVMGPUTileAndDistribute only supports a hard coded list of "operandsToPromote" for promtion filter applied to the entire funcOp. This is problematic if we want to single out individual operands for each linalg generic within a funcOp. The solution is to walk the funcOp for linalg ops and create individual filters specific to promote each linalg op, then add them all to the pattern and apply.
> Generalize TransposeSharedMem Pipeline to Fusion with Other ElementWise

- build_tools/github_actions/runner/gcp/create_image.sh
- build_tools/github_actions/runner/gcp/image_setup.sh
Note that I'm using Ubuntu 22.04 as the base image here. We're currently
using Debian, but I think it's probably better to switch to Ubuntu
because a) that's what GitHub's managed runners use and b) that's what
our Docker images use. This is configurable though.
The image setup script is based on the steps I took when manually
setting up the VM as well as scripts shared by another Googler working
on GitHub runner VMs, who demonstrably knows more about Linux than I do.
I do pretty much understand everything the script is doing, so it's not
just copy-pasta though.
Tested: Created an image using this script and deployed it to test
runners. All jobs succeed:
https://github.com/iree-org/iree/actions/runs/3049238365
skip-ci
> Script the creation of a new VM image

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dispatch_region_formation.mlir
- tests/transform_dialect/cuda/softmax_dispatch_spec.mlir
This op is split into two parts: One op that clones and one op that moves.
> Split clone_preceding_op_into_dispatch transform op

- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertRegionToWorkgroups.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertRegionToWorkgroups.h
Add an optional builder function parameter for populating the workload region of a newly created DispatchWorkgroupsOp.
This change will be utilized in a future when creating DispatchWorkgroupsOps from DispatchRegionOps.
> [Flow] ConvertRegionToWorkgroups: Add workload builder callback

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.h
This makes these helper functions usable from transform dialect op implementations and the Flow/Transforms.
> [Flow][NFC] Move cloning/moving helpers to RegionOpUtils

- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
- tests/transform_dialect/cuda/softmax.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_fused_codegen_spec.mlir
This revision adds a second type of strategy that runs at peak on GPU. The strategy consistes in fusing both at the block and thread level.
This uncovered few issues that the PR also fixes:
- improve tracking support by implementng a `findSingleOpDefiningAll` for the general non-Linalg, non-scf::For case.
- add support to distribute a 0-D load during vector distribution, for which a specific pattern is added. This requires a gpu.synchronize and cannot go upstream atm.
- apply vector distribution patterns iteratively and only when convergence is obtained lower to scf.if.
- various issues around vector distribution have been fixed upstream and integrated.
Additionally, this prefetches the following LLVM commits:
0b77a6734c294d60c37617c4010c803e92191b65 …
> Add a fused softmax strategy on GPU

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
Otherwise jobs try to write to the wrong attempt directory. See
https://github.com/iree-org/iree/actions/runs/3049599084/jobs/4926961709
where on attempt 6 it's writing to the directory of attempt 2, which is
when the setup job passed (reruns were only for failures). Would be
really cool if we just had proper variables and didn't have to hack
around with job outputs like this...
> Make sure GCS dir changes with run attempt

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.h
This is in preparation of adding a new pass
DispatchLinalgOnTensorsViaRegionOp. `orderOperations` is needed in that pass and this change avoids duplicating the code.
> [NFC] Move orderOperations to RegionOpUtils

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.h
This is in preparation of adding a new pass
DispatchLinalgOnTensorsViaRegionOp. `getLoopRanges` is needed in that
pass and this change avoids duplicating the code.
> [NFC] Move getLoopRanges to RegionOpUtils

- compiler/src/iree/compiler/Dialect/Flow/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensorsViaRegionOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.h
- tests/e2e/models/fullyconnected.mlir
This refactoring changes the way how DispatchWorkgroupsOps are created
in C++: Instead of creating workgroups ops directly, ops are first moved
into dispatch region ops. These region ops are then made isolated from
above, at which point they turn into workgroups ops.
Note: Fusion groups are still annotated with op attributes at the
moment. This can be improved (e.g., by incremetally building region ops
or by maintaining C++ data structures) in a separate change.
Note: The order of the operands of the DispatchWorkgroupsOps changed,
but there is no functional change.
This change leaves the original DispatchLinalgOnTensors.cpp unchanged
and adds a new variant DispatchLinalgOnTensorsViaRegionOps.cpp that can
eventually replace the original variant.
> Create DispatchWorkgroupsOps via DispatchRegionOps

- runtime/src/iree/builtins/ukernel/tools/BUILD
- runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt
- runtime/src/iree/builtins/ukernel/tools/mmt4d_benchmark.c
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test.cc
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test_utils.cc
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test_utils.h
Comes on top of #10339. The actual diff (without that diffbase) is
```
benoitjacob@cloud:~/iree$ git diff mmt4d-kernels-dotprod-i8mm --stat
runtime/src/iree/builtins/ukernel/tools/BUILD               |  16 +++++-
runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt      |  19 ++++++-
runtime/src/iree/builtins/ukernel/tools/mmt4d_benchmark.c   | 167 ++++++++++++++++++++++++++++++++++++++++++++++++---------
runtime/src/iree/builtins/ukernel/tools/mmt4d_test.cc       | 298 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----
runtime/src/iree/builtins/ukernel/tools/mmt4d_test_utils.cc | 162 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
runtime/src/iree/builtins/ukernel/tools/mmt4d_test_utils.h  |  63 ++++++++++++++++++++++
6 files …
```
> Mmt4d test and benchmark

- compiler/src/iree/compiler/Codegen/Common/LinalgOpInfo.cpp
We should check if the map is a projected permutation before inversing it.
> Add a check before inverse an affine_map.

- compiler/src/iree/compiler/Codegen/Common/GPUDistributeSharedMemoryCopy.cpp
- compiler/src/iree/compiler/Codegen/Common/test/distribute_gpu_shared_memory.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transpose_pipeline_test.mlir
Remove usage of the old vector distribution framework that is depracted in MLIR and will be removed. Instead rely on tiling + loop unrolling to generate the right distribution.
This will allow extending this pass in the future to handle fused operations more complex than copies.
> Refactor shared memory distribution pass

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DetachElementwiseFromNamedOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/detach_elementwise_from_named_ops.mlir
This pass needs to be deprecated eventually. This is really working around a front-end/input issue. For now only trigger the pattern to detach `outs` from named ops when the `outs` operand is defined by a `LinalgOp` that is not a `FillOp`.
Issue #10406
> Restrict places where `DetachElementwiseFromNamedOps` triggers.

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/TargetMLTransformInfo.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/TargetMLTransformInfo.h
We have been trying to selectively limit unrolling on RISC-V for those
cases that lead to register spilling. Unfortunately, it's becoming a
never-ending problem so this PR is limiting unrolling to 8 by default on
RISC-V while keeping unrolling of transpose operations disabled. That
seems to get rid of register spilling altogether. This sets a good
starting point for further unrolling tuning.
> [RISCV] Limit max unroll factor to 8 by default

- build_tools/cmake/iree_hal_cts_test_suite.cmake
- build_tools/cmake/run_riscv64_test.sh
- build_tools/cmake/test_riscv64.sh
The tests can actually be run via QEMU
* Fix iree_hal_cts_test_suite to support RISC-V cross compile
* Need to disable tests/e2e/regression/check_regression_llvm-cpu_lowering_config.mlir in the CI because it hangs indefinitely
> Fix RISC-V 64 Linux test script

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
- tests/transform_dialect/cuda/reduction.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_dispatch_spec.mlir
This revision reactivates the reduction unit test and provides the necessary fixes to both upstream and IREE to
get a good mapping.
The strategy introduced in this PR weak scales up to ~92% of memset BW at 39.84 MB as illustrated below.
The key there is to ensure `load4` instructions are emitted in addition to the `shfl` instructions.
```
==355359== Profiling result:
Start  Duration            Grid Size      Block Size     Regs*    SSMem*    DSMem*      Size  Throughput  SrcMemType  DstMemType           Device   Context    Stream        Unified Memory  Virtual Address  Name
479.92ms  74.341us                    -               -         -         -         -  39.844MB  523.40GB/s      Device           -  NVIDIA GeForce          1        13                     -                -  [CUDA …
```
> Reactivate reduction test and improve strategy.

- benchmarks/TF/CMakeLists.txt
Since we included the CUDA benchmarks into our benchmark suites, CUDA backend became a dependency to build the benchmark suites, while it is not enabled by default.
This change added a check to only include CUDA benchmarks if IREE_TARGET_BACKEND_CUDA is enabled. This makes the target `iree-benchmark-suites` can be built when the CUDA backend is disabled.
Fix #10455
> Only enable CUDA benchmarks when IREE_TARGET_BACKEND_CUDA is enabled

- benchmarks/TF/CMakeLists.txt
Reverts iree-org/iree#10457 that breaks the benchmark pipeline.
> Revert "Only enable CUDA benchmarks when IREE_TARGET_BACKEND_CUDA is enabled"

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transpose_pipeline_test.mlir
Updates the tile size to account for more than two dimensions. Shared mem transpose is only applied if the fastest moving dimension is altered.
> Generalize Transpose to Support 3D Shapes with Batch Dimensions

- compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/fusion_of_tensor_ops.mlir
Add the option to enable elementwise fusion on multiuse ops.
The code is guarded by `iree-flow-enable-aggressive-fusion` and disabled by default. We need some fixes in the backends to make this work.
> Add elementwise fusion on multiuse ops

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/Transforms.h
- compiler/src/iree/compiler/Codegen/Common/UserConfig.cpp
- compiler/src/iree/compiler/Codegen/Common/UserConfig.h
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_user.mlir
- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
- tests/e2e/matmul/generate_e2e_matmul_tests.py
This patch adds support to have config coming from higher level IR (to enable search).
It reuses the functionality from the LLVMGPU pipeline.
> [SPIRV] Add support for lowering specified in IR

- runtime/src/iree/hal/drivers/vulkan/builtin_executables.cc
- runtime/src/iree/hal/drivers/vulkan/native_pipeline_layout.cc
BuiltinExecutables would need to create dummy descriptor sets as placeholders. For such sets, we can set them to have zero bindings. This gives us a singal to avoid turning on push VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR bit when creating descriptor sets. Otherwise we would create multiple descriptor sets all with that bit and thus causing validation errors:
```
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00293 ]
vkCreatePipelineLayout() Multiple push descriptor sets found. The Vulkan
spec states: pSetLayouts must not contain more than one descriptor set
layout that was created with VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR set
```
Fixes https://github.com/iree-org/iree/issues/10414
> [vulkan] Create zero binding for dummy sets in BuiltinExecutables

- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
With the addition of AsyncCopyOp with Zfill to MLIR, IREE can now create GEMMs :-  
- Epilogue : Unpeeled and shorter (with less instructions, i.e., no peeled Shared Memory loads and math into Epilogue) 
- Mainloop : Uses AsyncCopyOp with Zfill to handle out-of-bounds Global Memory accesses. 
This PR reduced the dispatch size by **19%** without any performance regressions on [MiniLML12H384Uncased [int32,seqlen128]](https://perf.iree.dev/serie?IREE?MiniLML12H384Uncased%20%5Bint32,seqlen128%5D%20(TF)%20GPU-CUDA-SM_80%20full-inference,default-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D)
> Unpeeled Epilogue for WMMA-based GEMMs 

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_x86_64_launch_configuration.mlir
We want the tile sizes not greater than maxSizes. If they are greater than maxSizes at the last level of tiling, it could introduces big unroll factors.
> [LLVMCPU] Do not return the dim size if it is greater than maxSize.

- runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_tile_arm_64_i8mm.S
This comes on top of #10475, the only actual diff here is in runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_tile_arm_64_i8mm.S.
I noticed that google benchmark was incorrectly running only 1000 iterations of this benchmark. Debugging, its floating point code computing elapsed time got wrong arithmetic in determining whether it was time to cut the benchmark short. Eventually I realized my mistake: this kernel uses all 32 SIMD registers, including v8--v15 whose bottom 64bit are callee-saved.  We were overwriting the google-benchmark code's timestamp value stored in one of those!
The standard fix would be to push these 8 x 64bit to stack an pop at the end, which could be done in a total of 4 store-pair + 4 load-pair = 8 instructions, but we save those instructions by instead just not …
> mmt4d i8mm kernel register fix

- compiler/src/iree/compiler/Codegen/Common/RemoveTrivialLoops.cpp
- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/remove_trivial_loops.mlir
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.cpp
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.h
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/Dialect/test/lowering_config_attr.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/apply_scale_lowering.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/illegal_configuration.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute_scatter.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute_sort.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_to_cooperative_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/test/cmd_ops.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/convert_to_hal.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/dump_executable_benchmarks.mlir
- compiler/src/iree/compiler/Dialect/HAL/Transforms/test/dump_executable_sources.mlir
Remove `workload_per_wg` in `TranslationInfo`.
In lowering exportOp in the tiling process, the shape of the root tensor is checked and if the shape is static, the workgroup count info is calculated and directly exposed as arith.constant, which can be used in `RemoveTrivialLoops`.
> Remove workload per workgroup

- runtime/src/iree/builtins/ukernel/common.h
- runtime/src/iree/builtins/ukernel/elementwise.h
- runtime/src/iree/builtins/ukernel/elementwise_impl.c.inc
- runtime/src/iree/builtins/ukernel/mmt4d.c
- runtime/src/iree/builtins/ukernel/mmt4d_select_tile_generic.c
- runtime/src/iree/builtins/ukernel/mmt4d_types.h
- runtime/src/iree/builtins/ukernel/tools/mmt4d_benchmark.c
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test.cc
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test_utils.cc
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test_utils.h
This type is rightly signed, so its name shouldn't end in `_size_t`.
> rename iree_ukernel_size_t to iree_ukernel_ssize_t

- build_tools/cmake/iree_bytecode_module.cmake
`iree_bytecode_module` internally uses `_ARGS` variable to pass down the `iree-compiler` flags.
> Fix iree_bytecode_module RISCV crosscompile flags

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
The remaining markers may cause some transformations to be skipped in the following passes.
> Cleanup markers at the end of TileAndDistribute pass

- build_tools/github_actions/runner/gcp/create_image.sh
- build_tools/github_actions/runner/gcp/image_setup.sh
- build_tools/github_actions/runner/gcp/update_instance_groups.py
The main substantive changes have to do with the configuration of
`gcloud`. There was a recent change turning on Parallel Composite
Upload by default for large files, which unfortunately broke us. This
highlighted the need to use a stable version of gcloud on the runners
and the fact that snap makes it impossible to disable automatic
updates. gcloud is literally the only thing installed with snap for
some reason, and snap seems to kind of just suck in general, so I
purged the whole thing. I didn't use the SDK versioned archives from
https://cloud.google.com/sdk/docs/downloads-versioned-archives because
it turns out that getting something onto the path for systemd is
actually pretty tricky. I tried a few things and figured out how to do
it (in several different ways), but then decided it …
> Update VM image setup scripting

- compiler/src/iree/compiler/Dialect/Stream/Analysis/ResourceUsage.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/PackDispatchOperands.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/RefineUsage.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/ScheduleAllocation.cpp
Due to the missing override the solver would mark states as resolved even when invalid and then later consumers of the analysis results would get really confused.
> Fixing stream resource usage refinement to properly reject invalid state.

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_fused_codegen_spec.mlir
MLIR's transform dialect now has capability to map `scf.foreach_thread` to GPU threads. https://reviews.llvm.org/D133950
This PR makes iree specific transform dialect operation (iree.foreach_thread_to_gpu_and_translation_info) to use mlir's new feature.
> Use mlir's map_nested_foreach_thread_to_gpu_threads

- compiler/src/iree/compiler/Codegen/SPIRV/test/vector_to_cooperative_matrix.mlir
Particularly `Float16Buffer` implies `Kernel` capability. It will trigger patterns for OpenCL. We should not have it.
> [spirv] Remove wrong/unused capabilities in tests

- runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_tile_arm_64_i8mm.S
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test.cc
This was regressed by #10485.
Also, report the skipped/ran status on stdout not stderr, because GTest output goes there so that's how we get it consistently interleaved.
Also, fix a numerical bug in the i8mm kernel introduced in #10476. It was caught by mmt4d_test, not sure how I didn't notice.
> Fix mmt4d_test: actually dont use unsupported instructions.

- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
The WarpOpToScfIfPattern captures a const& to the options but since this function takes them by value that ends up referencing a stack variable past its lifetime. This was causing stack corruption on MSVC and I confirmed this fixes it.
> Passing WarpExecuteOnLane0LoweringOptions by ref.

- runtime/src/iree/base/config.h
- runtime/src/iree/hal/drivers/local_sync/registration/driver_module.c
- runtime/src/iree/hal/drivers/local_task/registration/driver_module.c
- runtime/src/iree/hal/local/executable_library_benchmark.c
- runtime/src/iree/hal/local/executable_loader.c
- runtime/src/iree/hal/local/executable_loader.h
- runtime/src/iree/hal/local/loaders/registration/init.c
- runtime/src/iree/hal/local/loaders/registration/init.h
- runtime/src/iree/tooling/context_util.c
This allows applications to specify an import provider that works in the generic driver factories. Applications wanting more control over the provider should create their executable loaders themselves and pass the provider in.
> Adding IREE_HAL_EXECUTABLE_IMPORT_PROVIDER_DEFAULT_FN config.

- build_tools/cmake/iree_benchmark_suite.cmake
Note: the reason why iree-test-deps wasn't failing similarly was that `iree_single_backend_generated_trace_runner_test` and `iree_check_single_backend_test_suite` were already performing a similar check, but they do it on the `DRIVER`, not on the `TARGET_BACKEND`. They can do so because these targets are built in the device build dir, where `IREE_HAL_DRIVER_*` variables are set and drivers are built, because drivers are part of the runtime, so they're built in the device build dir.
Unlike those targets, `iree-benchmark-suites` is built in the host build dir, so we shouldn't enable or disable benchmarks based on `IREE_HAL_DRIVER_*` here. Instead, what is relevant (and to the point of fixing the module compile error that caused me to look into this) is a check on `IREE_TARGET_BACKEND_*`. …
> Make iree-benchmark-suites buildable with some backends disabled.

- runtime/src/iree/base/internal/synchronization.c
This loop is already handling EAGAIN. It looks like it should handle EINTR the same way.
I'm trying to guess what might cause the intermittent crash #10337. One thing that would explain it is if the iree_task_scope_wait_idle done at the end of SubmitTasksAndWaitIdle wasn't doing its job. It calls iree_notification_await, which assumes that
iree_notification_commit_wait never returns false unless the deadline is exceeded. But iree_notification_commit_wait does return false if the futex syscall returns an expected error code, so we need to handle the exhaustive list of return codes that might come out of this syscall. The manual page lists only very few possible return codes for the particular FUTEX_WAIT op we're doing here (there are plenty of error cases, but few apply to FUTEX_WAIT). …
> Accept EINTR (interrupted by signal) futex return code

- build_tools/github_actions/runner/gcp/create_templates.sh
This is the image created by `create_image.sh`. It's one-hundredth the
size of the current image, created from scratch by a documented script,
and has other goodies, like turning off apt auto-update (see the
script for everything the image does).
Tested: deployed in test cluster ->
https://github.com/iree-org/iree/actions/runs/3107500759
skip-ci
> Use new VM image for runner CPU VMs

- compiler/src/iree/compiler/Codegen/Common/LinalgOpInfo.cpp
- compiler/src/iree/compiler/Codegen/Common/LinalgOpInfo.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransposeUtils.h
Cleanup to consolidate code and improve readability. 
Related to #10005
> Move Shared Mem Transpose Detection Logic to LinalgOpTrait

- .github/workflows/ci.yml
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/fusion_of_tensor_ops.mlir
Previously the fuse pass didn't check if the marks on consumer and producer are the same, which will fuse incorrect ops.
This change adds the check and also removes the markers to make sure the next iteration won't see the old markers.
> [fusion_heuristics] Check on fusable markers in FusionOfTensorOps

- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- runtime/src/iree/base/string_builder.c
- runtime/src/iree/base/string_builder.h
- runtime/src/iree/base/string_builder_test.cc
- runtime/src/iree/hal/string_util.c
- runtime/src/iree/hal/string_util.h
- runtime/src/iree/tooling/BUILD
- runtime/src/iree/tooling/CMakeLists.txt
- runtime/src/iree/tooling/buffer_view_matchers.c
- runtime/src/iree/tooling/buffer_view_matchers.h
- runtime/src/iree/tooling/buffer_view_matchers_test.cc
- runtime/src/iree/tooling/comparison.cc
- runtime/src/iree/tooling/comparison.h
- runtime/src/iree/tooling/comparison_test.cc
- runtime/src/iree/tooling/vm_util.cc
- tools/BUILD
- tools/CMakeLists.txt
- tools/iree-run-module-main.cc
- tools/test/BUILD
- tools/test/CMakeLists.txt
- tools/test/iree-run-module-expected.mlir
This allows for super basic blackbox testing of compiled modules by way of iree-run-module that does not require any input changes like iree-check-module does. The flag accepts the same values as `--function_input` (including npy files) in addition to `(ignored)` for when a value is not of interest.
When the flag is provided the normal output printing is disabled and instead a comparison runs and prints detailed information about any diffs, for example:
```
[FAILED] result[0]: element at index 49 (0) does not match the expected (123); expected that the view is equal to contents of a view of 5x1x10xf32
expected:
5x1x10xf32=[[0.743973 ... 0 0 123]]
actual:
5x1x10xf32=[[0.743973 ... 0 0 0]]
```
The matching utilities are intended to be wrapped in gtest C++ matchers so that they can be used …
> Adding `--expected_output=` flag to iree-run-module.

- runtime/src/iree/builtins/ukernel/mmt4d.c
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test.cc
Take care of cases where one of the M, N or K dimension is 0, in early-return paths.
This is motivated by loop pipelining optimizations that I want to do soon in asm kernels, which will have to either assume K>=1 or add an additional conditional branch for that case.
The compiler might help optimize away those degenerate cases with static shapes, but not with dynamic shapes anyway.
The other motivation here, alluded to in a comment, is that conversations with hardware folks suggest that there's a need to specialize the whole mmt4d loop nest, not just the innermost loop as we are currently doing with the tile_func on CPU. This provides an explicit placeholder for that.
> mmt4d ukernel: early return paths for degenerate cases

- compiler/src/iree/compiler/Dialect/HAL/Target/VMVX/test/smoketest.mlir
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/ConvertBufferOps.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/test/buffer_ops.mlir
- compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/test/arithmetic_folding.mlir
- compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeEncoder.h
- runtime/src/iree/vm/bytecode_dispatch.c
- runtime/src/iree/vm/bytecode_module_benchmark.mlir
- runtime/src/iree/vm/bytecode_module_impl.h
- runtime/src/iree/vm/test/buffer_ops.mlir
This should remove a lot of the *4 ops we need whenever we access buffers and prevents the opportunity for unaligned accesses.
In combination with #10510 this speeds things up quite a bit, for example in resnet (where we are running all convs with scalar vm code):
> Making >1B wide VM buffer load/stores implicitly scale.

- compiler/src/iree/compiler/Codegen/Common/GPUDistributeSharedMemoryCopy.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUMultiBuffering.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/vector_to_gpu.mlir
Promoting C matrix allows better memory access patterns for the store to global memory. This allows simplify handling fusion with ops when tensorcore is used since we go through shared memory and don't have to rely on the register layout of tensorcores.
> [LLVMGPU] Turn on C promotion by default for tensorcore gemm

- compiler/src/iree/compiler/Codegen/Common/GPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileTensor.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/conv_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tile_on_tensor.mlir
This enable vectorization for some convolution in order to improve performance. This will still generate very sub optimal code but gives a better baseline.
> [LLVMGPU] Enable vectorization for convolution

- runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_tile_arm_64_i8mm.S
@silvasean you were right, the "max streaming" idea from ruy kernels still helps, even on big OOO cores that "should" be able to make that optimization by themselves.
This is a 2x partial unrolling + pipelining of the inner loop that allows using all of the available registers to maximize load-to-use distance.
It might be counterproductive on cores that care foremost about minimum loop code size such as the Cortex-X1, but I don't have one here to test. Will be a good use case for tuning.
On the 3 core types in the Snapdragon 8gen1 in my Moto Edge x30:
  | Gop/s before | Gop/s after | Gop/s peak | Speedup | %peak before | %peak after
-- | -- | -- | -- | -- | -- | --
Cortex-A510 | 83.4 | 103.0 | 114.24 | 1.24 | 73% | 90%
Cortex-A710 | 307.7 | 308.0 | 319.49 | 1.00 | 96% | 96%
Cortex-X2 | …
> simple streaming kernel for the i8mm case

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_adreno_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_mali_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/vectorize_matmul.mlir
This pull request updates SPIR-V convolution CodeGen to use
upstream vectorization patterns. It requires us to tile one of
the output window dimension by 1 first because the upstream
patterns require 1xn window dimensions for downsizing.
We further unroll that loop in order to get the same vector
IR as before. 
Fixes https://github.com/iree-org/iree/issues/9653
> [spirv] Migrate to use upstream convolution CodeGen patterns

- CMakeLists.txt
- runtime/src/iree/hal/local/loaders/registration/CMakeLists.txt
Libraries in this list are linked in to the loader registration and it can be used for custom import provider libraries.
Fixes #10548.
> Adds `IREE_HAL_EXECUTABLE_LOADER_DEPS` cmake var.

- .github/workflows/ci.yml
Attempts to address #9537 
Has the same workflow inputs as validate_and_publish_release.yml, but I wasn't sure what the intended place in the existing workflows this was meant to plug into.  All it currently does is download the generated packages from the build_package.yml workflow and use them to run shark model zoo. Happy to configure to spec.
I think the custom runners are still up in the air per #9432 , so this will have to be edited later to account for how those are used.
> shark model testing for iree

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
This was causing perf regression on some cases and was an unnecessary restriction.
> [LLVMGPU] Remove restriction on shared memory promotion

- compiler/src/iree/compiler/Dialect/Flow/Transforms/OutlineDispatchRegions.cpp
Noticed [on Discord here](https://discord.com/channels/689900678990135345/689906000043573354/1024146087738617906):
```
//--- summarizing 'forward_dispatch_116' ---//
// linalg.fill cost: 3906816
// new best op: 'linalg.fill', cost: 3906816
// linalg.matmul cost: 3000434688
// linalg.generic cost: 3906816
// new best op: 'linalg.generic', cost: 3906816
// best op summary: 'generic_128x30522'
//--- opSummary: 'generic_128x30522' ---//
```
> Fix integer overflow in summarizeDispatchWorkgroupsOp.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/ConvertToLoops.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir
Start revisiting the `linalgx.relayout` operation in lights of the discussions we had. The semantics I would like to have is: `tensor.expand_shape + tensor.transpose`
TODO: 
1. Dropping the affine map and use attributes only?
2. Do we want to add also `tensor.pad` semantics?
3. Operation name: `pack` or `relayout`?
> Add Pack operation to LinalgExt dialect

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
This commit enable upstream patterns that are useful for tiling and fusing `tensor.pad`.
> Add ApplyPatternsOp support for padding

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/vectorize_load_store.mlir
This makes sure that we can vectorize the given memref can be vectorized given the vector.
Also adds a bunch of debug prints to make debugging easier.
> [spirv] Check memref innermost dim is a multiple of vector size

- .github/workflows/ci.yml
The tests added in https://github.com/iree-org/iree/pull/9748 started failing (see https://github.com/nod-ai/SHARK/issues/373), so this moves the tests to postsubmit so they don't block PRs. We could also disable them pending a fix.
See also: https://github.com/iree-org/iree/issues/9537
> Move test_shark_model_suite job to postsubmit only.

- .github/workflows/ci.yml
Follow-up to https://github.com/iree-org/iree/pull/10576 (see https://github.com/nod-ai/SHARK/issues/373).
This PR should be reverted once the job succeeds again.
> Disable test_shark_model_suite while it is failing.

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
The innermost loop dimensions of the `pack` operation deal with the packing the data into a tile. These loops cannot be tiled. The loops that iterate over the different data tiles of the output can be tiled. Change the iteration space description to only specify the loops that iterate over the data tiles of the output. The intra-data tile loops are generated as part of the scalar implementation of the `pack` operation.
> Modify `pack` op iteration space description to make it amenable to Tiling.

- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- runtime/src/iree/hal/local/executable_library.h
- runtime/src/iree/hal/local/executable_loader.c
- runtime/src/iree/hal/local/executable_loader.h
- runtime/src/iree/hal/local/loaders/embedded_elf_loader.c
- runtime/src/iree/hal/local/loaders/system_library_loader.c
This will allow for imports to carry state that doesn't require TLS or globals. Also sprinkling in a reserved pointer in case we need more stuff in the future.
> Extending imports to have a context pointer.

- .github/workflows/publish_website.yml
- build_tools/scripts/generate_release_index.py
This is incorporated into the docs pipeline and served on the website.
This isn't really the ideal place to serve it and we should probably
create a new subdomain and host a PEP 503 compliant index there. But
this will unbreak people for now.
Part of https://github.com/iree-org/iree/issues/10479
> Generate a page for `pip --find-links` from the GitHub releases API

- .github/workflows/publish_website.yml
Noticed on the manually triggered https://github.com/iree-org/iree/actions/runs/3147382998/jobs/5116836059 after https://github.com/iree-org/iree/pull/10581
`/home/runner/work/_temp/9c9745e9-f606-4f3a-9d32-6aab1aa7e3fa.sh: line 2: build_tools/scripts/generate_release_index.py: No such file or directory`
skip-ci
> Fix relative path to generate_release_index.py script.

- .github/workflows/ci.yml
Now that https://github.com/nod-ai/SHARK/pull/374 is merged, re-enable SHARK.
> Re-enable Shark post-submit

- .github/workflows/publish_website.yml
I messed up the action part of this with the paths. Going to revert and
iterate by triggering the publication on my fork.
This partially reverts commits 7d53e568109d19ca00427e399a4c95f8191b75fa
(https://github.com/iree-org/iree/pull/10581) and
10a3b04950528af67dfba8f9ac125be37959c597
(https://github.com/iree-org/iree/pull/10585).
Part of https://github.com/iree-org/iree/issues/10479
skip-ci
> Revert inclusion of pip index generation in docs publication workflow

- .github/workflows/publish_website.yml
This is incorporated into the docs pipeline and served on the website.
This isn't really the ideal place to serve it and we should probably
create a new subdomain and host a PEP 503 compliant index there. But
this will unbreak people for now.
Note that this includes a change to make docs publication run on forks.
I did this initially to enable testing, but I actually think it's a
reasonable change to make. The workflow is fast and cheap and this
makes testing it easier. GitHub already provides a way for people to
disable all actions or specific actions in their repository and I think
it makes more sense to let them handle it that way. I am open to being
convinced otherwise though. The fork most likely to be doing something
else with their gh-pages branch is Nod, and I've checked that they …
> Publish release pip index as part of website

- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.cpp
- tests/e2e/linalg_ext_ops/BUILD
- tests/e2e/linalg_ext_ops/CMakeLists.txt
- tests/e2e/linalg_ext_ops/pack.mlir
Currently the operation is executed serially since the operation does not implement the `getTiledImplementation` method needed to distribute the `pack` operation.
> Add end to end tests for `linalg_ext.pack` operations.

- benchmarks/README.md
- docs/api_docs/python/requirements.txt
- docs/developers/debugging/tf_integrations_test_repro.md
- docs/website/docs/bindings/python.md
- experimental/web/generate_web_metrics.sh
Fixes https://github.com/iree-org/iree/issues/10479
skip-ci
> Update references to using `--find-links` for new index

- compiler/src/iree/compiler/Codegen/Common/TestPartitionableLoopsInterface.cpp
- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/.#test_partitionable_loops_interface.mlir
- compiler/src/iree/compiler/Codegen/Common/test/test_partitionable_loops_interface.mlir
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.td
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
With the `TilingInterface` being used for first-level tile and
distribute, the additional methods in `PartitionableLoopsInterface`
are no longer necessary. Drop these.
> Drop unnecessary methods from `PartitionableLoopsInterface`.

- compiler/src/iree/compiler/InputConversion/MHLO/test/missing_legalizations.mlir
Those shift ops are now supported. They were using wrong element
types, which makes it looking like missing.
> Remove now supported legalizations in missing case tests

- compiler/src/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/mhlo_to_mhlo_preprocessing.mlir
- integrations/tensorflow/test/iree_tf_tests/layers/llvmcpu__dynamic_dims_MultiHeadAttention.run
- integrations/tensorflow/test/iree_tf_tests/layers/vulkan__dynamic_dims_MultiHeadAttention.run
I was going to extend this to address failing case, but noticed it seems
to be redundant with pattern that comes later. Disabling for dynamic
shapes at the moment. In follow up I'll remove to verify that it is
redundant.
> Disable pattern not safe for dynamic shapes

- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/cmake/iree_c_module.cmake
- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_hal_cts_test_suite.cmake
- build_tools/cmake/iree_macros.cmake
- build_tools/cmake/iree_static_linker_test.cmake
- docs/developers/developing_iree/testing_guide.md
Enable cross compile flags in `iree_bytecode_module` and `iree_c_module`, and allow `iree_static_linker_test` to build and test in cross compile platforms.
> Enable iree_static_linker_test for cross compile

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.h
This limits the references to this to place that only need it.
> Remove dead references to `LoopTilingAndDistributionInfo`.

- tests/transform_dialect/cpu/BUILD
- tests/transform_dialect/cpu/CMakeLists.txt
Else running into
```
required embedded linker tool (typically `lld`) not found
```
> Add lld dep to transform test

- build_tools/cmake/iree_bytecode_module.cmake
- build_tools/cmake/iree_c_module.cmake
- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_hal_cts_test_suite.cmake
- build_tools/cmake/iree_macros.cmake
- build_tools/cmake/iree_static_linker_test.cmake
- docs/developers/developing_iree/testing_guide.md
Reverts https://github.com/iree-org/iree/pull/10620 and re-introduce https://github.com/iree-org/iree/pull/10589
Enable cross compile flags in `iree_bytecode_module` and `iree_c_module`, and allow `iree_static_linker_test` to build and test in cross compile platforms.
> Re-enable iree_static_linker_test for cross compile

- runtime/src/iree/tooling/vm_util.c
Follow-up to https://github.com/iree-org/iree/pull/10563
```
[build] D:\dev\projects\iree\runtime\src\iree\tooling\vm_util.c(67): error C2059: syntax error: '}'
```
> Fix vm_util.c build on MSVC.

- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
- compiler/src/iree/compiler/Tools/iree_compile_lib.cc
The HAL target backends are registered outside of the typical flags system, so `--help` output just appears as
```
--iree-hal-target-backends=<string>                          - Target backends for executable compilation.
```
This adds a new flag with sample usage:
```
λ iree-compile.exe --iree-hal-list-target-backends
Registered target backends:
cuda
llvm-cpu
metal
metal-spirv
vmvx
vmvx-inline
vulkan
vulkan-spirv
webgpu
webgpu-wgsl
```
Part of addressing https://github.com/iree-org/iree/issues/10432
---
I think we should also plumb something similar through to the Python bindings. This is what we have today:
```python
_ = compile_str(asm)
ValueError: Expected a non-empty list for 'target_backends'
_ = compile_str(asm, target_backends=["unknown"])
CompilerToolError: Error invoking IREE …
```
> Add `--iree-hal-list-target-backends` flag.

- compiler/src/iree/compiler/Dialect/Stream/Transforms/PackDispatchOperands.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/pack_dispatch_operands.mlir
- compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
Since the offsets are unsigned value we need to do a zero extend when index is a wider type.
> Use IndexCastUIOp in pack_dispatch_operand

- compiler/src/iree/compiler/API/python/iree/compiler/tools/core.py
- compiler/src/iree/compiler/API/python/test/tools/compiler_core_test.py
Depends on https://github.com/iree-org/iree/pull/10629. Part of addressing https://github.com/iree-org/iree/issues/10432.
```python
import iree.runtime
iree.runtime.query_available_drivers()
['cuda', 'local-sync', 'local-task', 'vulkan']
import iree.compiler
iree.compiler.query_available_targets()
['llvm-cpu', 'metal', 'metal-spirv', 'vmvx', 'vmvx-inline', 'vulkan', 'vulkan-spirv']
```
Since the Python compiler API is just a wrapper around the CLI tools, this runs `iree-compile --iree-hal-list-target-backends` and parses the output.
> Add iree.compiler.query_available_targets() Python utility.

- docs/website/docs/community/index.md
Adding a few projects that I'm aware of (both "official" and community driven). Trying to connect more dots between frontends (e.g. JAX, PyTorch) and other projects, where lots of exciting work is happening, and the core project. We're split across so many repositories, forums, mailing lists, etc. that having an index page is nice :)
> Expand list of community projects on the website.

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
Refactor the `TileAndDistributeToWorkgroups` code to better separate out
- The logic to retrieve the configuration to use for tile + distribute
- The computation to lower the operations in the region for number of workgroups. Seperate out the logic of lowering ops like `flow.dispatch.workgroup_count_from_dag_root` into its own pattern. This is the only op of its kind today, but this region could have any sequence of operations. Using the pattern based approach to lower these operations instead of hardwiring the implementation to look for such ops.
> NFC: Better separate out configuration selection and lowering number of workgroups computation.

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileTensor.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TilingUtils.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tile_on_tensor.mlir
This prevents vectorizing large linalg ops. We tile with serial loops the extra dimension that are not handled by tileAndDistribute to workgroup.
> [LLVMGPU] Tile extra parallel dimensions not distributed

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
The inner_tiles matches the inner sizes of the output. We should use the value directly if they are dynamic.
> Update PackOp::reifyResultShapes to take account of inner_tiles.

- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
MLIR added GPU transform dialect. The functionality existed before but lived in linalg. IREE was using functions of the transform dialect from linalg. https://reviews.llvm.org/D134800 actually created a gpu transform dialect and moved gpu related fucntions there.
This PR make IREE use of GPU transform dialect. We do not expect any functionality changes.
The PR includes the cherry pick llvm below:
```
[mlir][transform][nfc] typo fix
78305720f387ba5c86810a02155bd6c58d22c97c
[mlir][transform] Create GPU transform dialect
89bb0cae46f85bdfb04075b24f75064864708e78
```
> [mlir][transform] Use MLIR's GPU transform dialect

- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
- compiler/src/iree/compiler/Codegen/VMVX/test/lower_linalg_microkernels.mlir
When the accumulator argument to a `linalg.matmul` or `linalg.mmt4d` is filled with constant zeros, we can drop that fill and instead tell the `vmvx.matmul` or `vmvx.mmt4d` to overwrite the output buffer instead of loading and accumulating into the existing values.
This wasn't the top performance bottleneck --- slow packing code was --- but it was a good thing to work on independently while @MaheshRavishankar and @hanhanW are bringing up the new packing ops. And it still was significant: here this makes a 128x128, `i8` matmul over 20% faster. Okay, to put this into some perspective, we are talking about going from 1.8 Gop/s to 2.2 Gop/s (peak is 760 Gop/s, the mmt4d ukernel part does 730 Gop/s so all the remaining slowness is the packing/unpacking code. To put that in perspective, current …
> Skip zero-filling accumulators, let ukernels overwrite

- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtInterfaces.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/canonicalize.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
Along the way
- Fix an error in canonicalization that generates a clone of the op without accounting for non input and output operands
- Some minor fixes to comment styles.
> Enable parallel execution of `linalg_ext.pack` operations.

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_riscv_launch_configuration.mlir
This PR enables peeling for matmul and element-wise ops on RISC-V. Now that we have most of the unrolling limits in place, peeling becomes beneficial on RISC-V! This PR improves DeepLabV3 performance by 43%.
Along the way, this patch also introduces debug dumps in KernelDispatch.cpp that is useful to follow how the tile size computation evolves. I used them to study the current tile size computation and I also tried to improve the code a bit while figuring out what it does.
> [CPU] Enable peeling by default on RISC-V

- build_tools/cmake/iree_run_module_test.cmake
Remove the absolute path in flagfile, module_file, and expected_output to make the test more portable.
Also update the `file(STRING)` --> `file(READ)` usage in the function.
> Fix `iree_run_module_test` setting to make it portable

- tools/test/CMakeLists.txt
Android on device test does not run at the directory where the CTestTestfile.cmake sits, so it can't find the module file at the current directory. Need to revisit the flow to have a proper fix.
> Mark iree_run_module_test in Android test as WILL_FAIL

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir
It also changes unpack op to verify input type against inferred type. We're able to infer packed type based on source type and inner_tiles.
> Relax UnPackOp to handle incomplete tiles.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/StripAndSplatConstantVariables.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/strip_and_splat_constant_variables.mlir
We can see `arith.constant` carrying model weights in models prepresented at the Linalg level.
> Support arith.constant in StripAndSplatConstantVariablesPass

- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
Use it to lower ceil/floor division in the SPIR-V CodeGen pipeline.
> Cherry-pick llvm/llvm-project@d32df0f6 for SPIR-V

- compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingInterface.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/BUILD
- compiler/src/iree/compiler/Dialect/Flow/IR/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.h
These utility functions were upstreamed as part of llvm/llvm-project@bd81524e.
> NFC: Use upstream version for foldOffsetsSizesAndStrides

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul.mlir
The limitation on thread count per workgroup if using workgroup memory is some leftover from previous iterations. Remove it.
> [spirv] Fix matmul configuration deduction w.r.t. shared memory

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
Breaking down the long function into multiple smaller utility functions to make the logic clear and easier to read.
> [spirv] NFC: Refactor SPIRVTilePass to be more readable

- benchmarks/README.md
- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
Rename the historical `buildkite:benchmark` to `buildkite:benchmark-android`.
Github label will be renamed once this change is merged. The condition on old `buildkite:benchmark` isn't removed to avoid interruption during the migration.
Was planning to get rid of these when migrating to the Github-based benchmark CI, but this seems to be too confusing and easy to fix.
> Rename label buildkite:benchmark to buildkite:benchmark-android

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/vectorize_conv.mlir
This commit adjusts the unrolling configuration for convolution to tile the output innermost dimension by compute size. This allows to avoid generating innermost unit dimensions after unrolling NCHW convolution, which now has `affine_map<(d0, d1, d2, d3) -> (d0, d2, d1)>` after merging accumulator/result transpose ops. This cleans up the extract/insert ops generated from lowering transpose ops.
Towards https://github.com/iree-org/iree/issues/10536
> [spirv] Avoid extract/insert due to NCHW convolution transpose

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
This commit adjusts the ordering of various vector patterns in SPIRVVectorizePass to be more consistent w.r.t. their dependency: Certain patterns would generate new vector ops; we need to run patterns handling the new ops in a later step.
> [spirv] Adjust vector pattern order in SPIRVVectorizePass

- compiler/src/iree/compiler/Codegen/Common/GPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileTensor.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/conv_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tile_on_tensor.mlir
Enable more vectorization for convolution and reverse the order of tiling back to tile reduction shapes after second level of distribution.
> [LLVMGPU] Enable vectorization for ncw convolutions

- compiler/src/iree/compiler/Dialect/Flow/TransformExtensions/FlowExtensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.h
This fixes a bug where a tensor dims were reified after their use (op dominance error).
> Fix insertion point issue in appendDispatchRegionResult

- .github/workflows/ci.yml
The archive step of `build_all` job uses up almost all RAM disk space. In addition to enlarging the RAM disk, we can also remove the unused files before the archive step.
This only takes 1s to run and saves about 10G disk space for the following archive step:
```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            50G   35G   16G  69% /runner-root
```
> Remove unused files before archiving build dir

- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- compiler/src/iree/compiler/InputConversion/MHLO/BUILD
- compiler/src/iree/compiler/InputConversion/MHLO/CMakeLists.txt
- compiler/src/iree/compiler/InputConversion/MHLO/Passes.cpp
- compiler/src/iree/compiler/InputConversion/MHLO/test/transformation_pipeline.mlir
- compiler/src/iree/compiler/Tools/BUILD
- compiler/src/iree/compiler/Tools/init_input_dialects.cc
Should be NOP except where StableHLO is in input and there it should
convert to the equivalent MHLO.
> Add StableHLO to MHLO legalization to input pipeline

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_adreno_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_adreno_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_linalg_ext_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_mali_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_mali_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_user.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute_scatter.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_distribute_sort.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_batch_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_conv.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_to_cooperative_ops.mlir
- tests/e2e/matmul/generate_e2e_matmul_tests.py
This is a prelimiary step to help adding configuration verifiers for autotuning and searching.
> [spirv] NFC: Rename existing pipelines to be consistent

- build_tools/cmake/iree_run_module_test.cmake
- tools/test/CMakeLists.txt
Android test pushes the files to the device to the test-specific directory w.r.t the top temp IREE directory. We need to update the `iree-run-module` file flags with such.
> Update `iree_run_module_test` to set flags for on-device tests

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
Add a static class method to `Pack` operation that allows getting the shape of the expected result. Such methods helps to lower into pack operations that is destination passing style.
Also add a custom `build` method to `Pack` ops to hide a lot of bioler plate.
Fix a lit test along the way.
> NFC: Add static method to `Pack` op to get result shape.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
Also add a static method, `getPackedType`, to `pack` op to get the
type of the result based on the pack op parameters.
> Add helper build methods to `pack` and `unpack`.

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
Originally `inner-dims-pos` and `outer-dims-perm` had to agree on the dimension to tile and interchange, meaning that the vector must have the same elements. This patch relaxes the restriction and allows `outer-dims-perms` to target any tiled loop.
We also fix a bug in the interchange routine. `outer-dims-pos` represents the new position for the tile loops. For example, given the dimension [1, 55, 56, 2] and the interchange vector [0, 3, 1, 2] we expect: [1, 2, 55, 56]. Dimension `2` in the old position `3` is now expected at position `1.
> Relax verifier restrictions for `outer-dims-perm`.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/PadLinalgOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/pad_linalg_ops.mlir
For linalg.batch_matmul we still only pad along M, N, K dimensions.
> Extend PadLinalgOps to support batch matmul

- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
We don't actually use workgroup memory for mobile GPUs; so no copy there. For desktop GPUs where we may use workgroup memory, the pass pipeline handles barrier already. However there are cases allocation might be generated unexpectedly; just be conservative to avoid numeric issues.
> [spirv] Add barrier when performing copy involving workgroup memory

- build_tools/github_actions/runner/config/register.sh
- build_tools/github_actions/runner/config/setup.sh
- build_tools/github_actions/runner/gcp/create_templates.sh
This is somewhat of a stop-gap. I think we should really switch to
using local SSD. tmpfs seemed easiest at the time because the CPU
machines had so much RAM, but I didn't realize how little the GPU
machines have.
Part of https://github.com/iree-org/iree/issues/10739
> Increase tmpfs size for CPU runners

- tests/e2e/linalg_ext_ops/unpack.mlir
The tests are mapped to pack.mlir. For large tests, we pass the result of the pack op to unpack op, and check if the result match the original input.
> Add e2e unpack tests for large cases and dynamic cases.

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/GPUTileReduction.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/tile_reduction.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/conv_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- tests/e2e/regression/large_reduction.mlir
Add a pass to tile reductions when the dimension is larger than the maximum number of threads in a group. This allows supporting larger reductions efficiently.
Currently we disable the case where the reduction is fused with a broadcast as we need to improve distribution to handle it.
> Support large reduction in group reduction path

- build_tools/bazel/iree.bazelrc
- llvm-external-projects/iree-dialects/BUILD
Also combine LinalgExt transforms and passes which has backref.
Makes warning default & removes failure case from #9827
> Enable & make backref warnings errors

- compiler/src/iree/compiler/API/python/IREECTransforms.cpp
- llvm-external-projects/iree-dialects/python/IREEDialectsModule.cpp
It breaks windows builds when it is included.
Similar fix went into torch-mlir https://github.com/llvm/torch-mlir/pull/1397
> Remove Interop.h which is no longer needed

- compiler/src/iree/compiler/Codegen/SPIRV/AMDConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/AdrenoConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/AppleConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/MaliConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_promotion.mlir
This requires us to choose a tiling configuration that has some multiple of 8 as the innermost dimension, so that we can properly tile and vectorize with 8-element vectors for memory load/store. Computation still happens as `vector<4xf16>` due to SPIR-V requirements.
Towards https://github.com/iree-org/iree/issues/10718
> [spirv] Enable using fp16 in matmul promotion pipeline

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp
Specialization helped the performance too and now the sharemem promotion actually slows down the partial tile portion. Needs a broad evaluation.
For example, distillbert shows improvement from 6.21ms to 5.29ms.
> Do not promote to sharemem for dynamic tensors

- compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUTileReduction.cpp
- compiler/src/iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_reduction.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/reduction_lowering.mlir
Add pass to tile reduction dimension when it is bigger than the workgroup size.
This requires relaxing flatten memref pass.
> Enable group reduction on SPIRV for large reduction

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/single-tiling-full-script.mlir
Canonicalization in the canonicalized sequence transform op may replace payload operations associated with the transform dialect handles. Post-canonicalize reassociation is fragile and may fail. To make this less likely, drop any association that are no longer necessary, i.e., if the operand is no longer used in the sequence or elsewhere or if the result is never read. This is a more robust but IREE-specific alternative to the obsolete functionality in upstream MLIR that wouldn't associate unread results.
Closes #10785
> [iree-dialects][transform] drop unnecessary handle associations

- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Codegen/SPIRV/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVEmulateI64.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/test/emulate_i64.mlir
- tests/e2e/vulkan_specific/BUILD
- tests/e2e/vulkan_specific/CMakeLists.txt
- tests/e2e/vulkan_specific/add_i64.mlir
- tests/e2e/vulkan_specific/mul_i64.mlir
The pass is conditionally enabled when the SPIR-V target does not declare I64 capabilities. The `demote-i64-to-i32' needs to be disabled for Wide Integer Emulation (WIE) to have any i64 ops to emulate. These default will be changed once the WIE implementation is robust enough.
Locally, I tested this by changing the `demote-i64-to-i32` default to false and all tests passed.
Issue: #8702
> [spirv] Add initial I64 emulation pass

- compiler/src/iree/compiler/Codegen/SPIRV/AMDConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/AdrenoConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/AppleConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.h
- compiler/src/iree/compiler/Codegen/SPIRV/MaliConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
This is just a preliminary refactoring step for upcoming changes to better utilize shared memory for matmul. Keep it separate to make code reviews easier.
> [spirv] RFC: Pass in the entire resource limits for matmul

- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- tests/e2e/linalg_ext_ops/BUILD
- tests/e2e/linalg_ext_ops/CMakeLists.txt
This is in preparation for actually writing a microkernel.
This is only pack for now, not unpack, because of https://github.com/iree-org/iree/issues/10796 .
I had to introduce a new compiler command-line flag, `--iree-vmvx-enable-microkernels-decompose-linalg-generic`, defaulting to `true` (the current behavior), so that I could set it to `false` in this test. The problem is that when `--iree-vmvx-enable-microkernels` is passed, we use a DecomposeLinalgGenericPass. The `pack.mlir` test here contains `linalg.generic` which, when decomposed by this pass, are split into a chain of multiple `linalg.generic` with temporary buffers in between. These temporary buffers are `memref.alloca` in the IR, resulting in compilation failures:
```
error: failed to legalize operation 'memref.alloca' that …
```
> Enable e2e `linalg_ext.pack` test on VMVX + ukernel

- compiler/src/iree/compiler/Codegen/VMVX/LowerLinalgMicrokernels.cpp
This is a more common occurrence than you'd think because of what's discussed in #10813.
> Avoid assert failure with `index` as elem type.

- .github/workflows/ci.yml
- build_tools/cmake/build_android.sh
Consolidate cross-compile CI targets (andoird, rv64, rv32-baremetal, rv32-linux) into a matrix.
Emscripten is currently standalone because it is in postsubmit only.
> Consolidate cross-compile targets in CI

- .github/workflows/build_package.yml
This catches all variations of libzstd in the GHA runners. We noticed some runners now have an unversioned dylib https://github.com/iree-org/iree/actions/runs/3264207153/jobs/5364477219#step:9:4794 so expanding this workaround.
> Delete non-universal binaries from macOS

- compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
The subspan op is expected to have an offset of 0 after the pass. Add an assert in convertion to SPIRV since the pass makes the assumption.
> Fix bug in flatten memref pass

- compiler/src/iree/compiler/API/python/iree/compiler/tools/tf.py
Preserves current usage model with UTF-8. In the future we can expose other formats.
> [TF] use mlir-ir as output format by default

- experimental/web/sample_static/device_multithreaded.c
- runtime/src/iree/hal/drivers/local_task/registration/driver_module.c
- runtime/src/iree/hal/drivers/local_task/task_device.c
- runtime/src/iree/hal/drivers/local_task/task_device.h
- runtime/src/iree/hal/drivers/local_task/task_driver.c
- runtime/src/iree/hal/drivers/local_task/task_driver.h
- runtime/src/iree/hal/drivers/local_task/task_queue.c
- runtime/src/iree/hal/drivers/local_task/task_queue.h
- runtime/src/iree/task/executor.c
- runtime/src/iree/task/executor.h
- runtime/src/iree/task/executor_impl.h
- runtime/src/iree/task/worker.c
- runtime/src/iree/task/worker.h
- samples/simple_embedding/README.md
- samples/simple_embedding/device_embedded.c
Queues may share executors or have their own dedicated executors.
Progress on #10765.
> Adding support for multiple queues on the local-task device.

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_matmul.mlir
This commits adjusts the matmul configuration deduction logic to
* Make sure we don't use more shared memory than what's allowed
by the target environment, by scaling back the number of
threads in a workgroup.
* Try to adjust to allow perform vector load into shared memory
for both LHS and RHS when possible.
> [spirv] Utilize shared memory better for MatmulPromoteVectorize

- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/FoldIntoPackAndUnpackOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/fold_into_pack_unpack_ops.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/materialize_encoding.mlir
This PR adds utility methods and patterns that convert a program with ops involving encoding into programs that explicitly materialize the encoding and operations that operate on the materialized data layout. While most of the functionality is implemented as utility functions, the driver pass is written using DialectConversion framework since that avoids having to introduce fake casts for inter-op with existing ops. Ideally these patterns can be pulled in directly within IREE backend with some additional patterns for type conversion of the ABI.
Also added is a pass to fold operations like
`tensor.pad`/`tensor.extract_slice` into `linalg_ext.pack` and `linalg_ext.unpack` operations, respectively since the semantics of these ops can subsume them.
> Add methods to materialize the encoding of tensor types.

- build_tools/python/benchmark_suites/iree/adreno_benchmarks.py
- build_tools/python/benchmark_suites/iree/armv8_a_benchmarks.py
- build_tools/python/benchmark_suites/iree/cuda_benchmarks.py
- build_tools/python/benchmark_suites/iree/mali_benchmarks.py
- build_tools/python/benchmark_suites/iree/riscv_benchmarks.py
- build_tools/python/benchmark_suites/iree/vmvx_benchmarks.py
- build_tools/python/benchmark_suites/iree/x86_64_benchmarks.py
- build_tools/python/e2e_test_framework/cmake_rule_generator.py
- build_tools/python/e2e_test_framework/cmake_rule_generator_test.py
- build_tools/python/e2e_test_framework/definitions/iree_definitions.py
- build_tools/python/e2e_test_framework/iree_tf_import_template.cmake
Add an extra layer to represent the model importing step when generating e2e test modules.
This provides a place to put the MLIR dialect information of imported model.
> Add IREE imported model layer to e2e test framework

- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
`linalg.generic` implements LinalgOp interface and may go through tiling path like other Linalg ops. This may have unexpected consequences---tiling and other marker-based patterns would handle the op and remove the `copy_to_workgroup_memory` marker before we reach GPUDistributeSharedMemory passs. And we will fail to distribute then.
> Use memref.copy instead of linalg.generic for shared memory copy

- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/transform_dispatch_region_formation.mlir
Generate tensor.dim ops if an op implements none of the supporting interfaces (e.g., ReifyRankedShapedTypeOpInterface).
> RegionOpUtils: Fix reification of dynamic dims

- compiler/src/iree/compiler/Codegen/LLVMCPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUAssignImportOrdinals.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/assign_import_ordinals.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/hal_executable_constants.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/hal_interface_bindings.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/hal_interface_constants.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/hal_interface_workgroup_info.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LibraryBuilder.h
- runtime/src/iree/hal/local/elf/arch.h
- runtime/src/iree/hal/local/elf/arch/arm_32.c
- runtime/src/iree/hal/local/elf/arch/arm_64.c
- runtime/src/iree/hal/local/elf/arch/riscv.c
- runtime/src/iree/hal/local/elf/arch/x86_32.c
- runtime/src/iree/hal/local/elf/arch/x86_64.c
- runtime/src/iree/hal/local/elf/arch/x86_64_msvc.asm
- runtime/src/iree/hal/local/loaders/embedded_elf_loader.c
During conversion to the LLVM dialect any `func.call` to an extern function or a function emitted during conversion will be lowered into an import call with a placeholder ordinal. This uses a technique like executable constants whereby imports get an attributed global placeholder for the ordinal that is assigned in the new LLVMCPUAssignImportOrdinals pass after linking. During serialization the import table built during assignment is used to declare the imports on the executable library data structure.
The automatic conversion comes courtesy of @nicolasvasilache and should handle most basic arg/result packing.
Minor fixes were required in the runtime for MSVC compatibility with embedded ELFs.
Fixes #7504.
> Adding CPU import conversion and ordinal assignment machinery.

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
It creates a placeholder to kick in vectorization and other transforms for pack ops.
> Add a CodeGen pipeline for data tiling ops.

- build_tools/cmake/iree_check_test.cmake
- build_tools/cmake/iree_native_test.cmake
- build_tools/cmake/iree_trace_runner_test.cmake
Use `{{}}` file locator to parse the file path and handle portability.
> Retire `TEST_INPUT_FILE_ARG` in `iree_native_test`

- docs/website/docs/getting-started/pytorch.md
Follow-up to https://github.com/iree-org/iree/pull/10757
* Fix table formatting (single column table needs `| text here |` instead of `text here`)
* Fix note formatting (https://squidfunk.github.io/mkdocs-material/reference/admonitions/)
* Fix numbered list formatting (https://squidfunk.github.io/mkdocs-material/reference/lists/#using-ordered-lists)
* Wrap some lines at 80 characters (purely a style choice, some formatters do this automatically)
* Tweak some phrasing / grammar
(steps to preview changes to the website locally are here: https://github.com/iree-org/iree/tree/main/docs/website)
> Cleanup PyTorch getting started page.

- build_tools/cmake/build_and_test_asan.sh
Seeing this test flake on a few presubmits:
https://github.com/iree-org/iree/actions/runs/3316089449/jobs/5477477103
https://github.com/iree-org/iree/actions/runs/3316263166/jobs/5477856081
Looks like https://github.com/iree-org/iree/issues/5716
```
FAIL: IREE :: e2e/regression/globals.mlir (1 of 1)
******************** TEST 'IREE :: e2e/regression/globals.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   iree-run-mlir --iree-input-type=mhlo --iree-hal-target-backends=vmvx /work/tests/e2e/regression/globals.mlir | FileCheck /work/tests/e2e/regression/globals.mlir
: 'RUN: at line 2';   [[ $IREE_VULKAN_DISABLE == 1 ]] || (iree-run-mlir --iree-input-type=mhlo --iree-hal-target-backends=vulkan-spirv /work/tests/e2e/regression/globals.mlir | FileCheck …
```
> Disable iree/tests/e2e/regression/globals.mlir.test under ASan.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Utils/Utils.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
- tests/e2e/linalg_ext_ops/pack.mlir
The iteration space is on the leading dimensions of output, where there are inputRank loops. The tiling sizes are set to tile on the order of iteration space. In this context, the input of getTiledImplementation is interchanged. We have to undo it before creating the slice for input.
This PR also adds an e2e test for the pack op with outer_dim_perms.
Fixes https://github.com/iree-org/iree/issues/10902
> Fix a bug in tiling pack op that has outer_dim_perms attribute.

- runtime/bindings/python/iree/runtime/build_requirements.txt
When we build for CUDA and there is no CUDA SDK we download the CUDA binaries using requests. Add this to prevent failures such as https://github.com/nod-ai/SHARK-Runtime/actions/runs/3325644038/jobs/5498545756
> Add requests to pip requirements for CUDA download

- runtime/pyproject.toml
Just like we added to the build_requirements.txt we need requests in pyproject.toml when building release builds with CUDA on (like on Windows) without IREE docker images.
> Add requests for PyProject.toml

- tests/e2e/tosa_ops/CMakeLists.txt
- tests/e2e/xla_ops/CMakeLists.txt
Copied over manually for now, but if the WebGPU target was supported in the Bazel build we could use `enforce_glob` with `exclude`.
Just compilation tests for now (like with llvm-cpu / wasm), but I'm hoping to also test execution once the WebGPU HAL is working and I have it running on CI in some form.
> Add WebGPU compilation tests for xla_ops/ and tosa_ops/.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Transforms.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Utils/Utils.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/Tiling.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
The main issue is about incomplete tile. Since all the dimensions are orthogonal, discussing 1-d unpack case is enough. The core idea is to make the input slice have complete tiles. In this case, a larger unpacked tile will be created. We'll need an extract_slice op to shift and truncate the output.
Let's take Nn_to_N as an example. Say that N=32, n=8, and tiling_size=15. The coordinates of second tile (i.e., `result[15..31]`) are `[(1, 7), (2, 0,), (2, 1) ... (3, 6), (3, 7)]`. The first row and the last row are incomplete in terms of inputs. It's impossible to represent an unpack op using the coordinates. Because the input has higher rank and the math computation of coordinate is using mod and ceilDiv. That's very tricky.
To represent the unpack op, we have to complete the rows. I.e., …
> Add support for tiling LinalgExt::UnPackOp.

- build_tools/third_party/swiftshader/build_vk_swiftshader.sh
There seem to be a lot of deprecation warnings generated with the latest compilers during build of swiftshader. Just ignoring the warnings seems to be fine for now.
> Switch off WARNINGS_AS_ERROR for swiftshader builds.

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/GPUPatterns.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUPatterns.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUVectorToGPU.cpp
This commit moves FlattenTransferReadOp to a common place in preparation for reuse in the SPIR-V CodeGen pipeline.
> NFC: Move FlattenTransferReadOp in preparation for reuse

- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
The UnifyAliasedResourcePass is actually only necessary for targeting
Apple GPUs via MoltenVK, where we need to translate SPIR-V into MSL.
The translation has limitations--no support of aliased resources.
There is a hidden bug in the UnifyAliasedResourcePass yet to be
identified. So for now limiting it to only Apple platforms to avoid
further disruption.
Fixes https://github.com/iree-org/iree/issues/10850
> [spirv] Only unify aliased resources on Apple platforms

- compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/flatten_memref_subspan.mlir
This commit extends the existing pattern for folding subspan offsets
into load/store ops to cover GPU subgroup MMA load/store in
`FlattenMemRefSubspanPass`.
> Extend subspan byte offset folding to GPU MMA load/store

- runtime/src/iree/base/status_cc.h
Following #10946 we have this error with GCC 12.2:
```
/usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/status_cc.h:113:17: error: standard attributes in middle of decl-specifiers
113 |   static inline IREE_MUST_USE_RESULT std::string ToString(
|                 ^~~~~~~~~~~~~~~~~~~~
/usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/status_cc.h:113:17: note: standard attributes must precede the decl-specifiers to apply to the declaration, or follow them to apply to the type
```
> Fix GCC build error with IREE_MUST_USE_RESULT attribute placement

- benchmarks/TFLite/CMakeLists.txt
- benchmarks/TFLite/android-adreno.cmake
- benchmarks/TFLite/android-arm64-v8a.cmake
- benchmarks/TFLite/android-mali.cmake
- benchmarks/TFLite/linux-riscv.cmake
- benchmarks/TFLite/linux-x86_64.cmake
#10748 has been resolved. Re-enables the benchmarks.
> Re-enable the benchmarks disabled due to #10748

- runtime/src/iree/builtins/ukernel/BUILD
- runtime/src/iree/builtins/ukernel/CMakeLists.txt
- runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_tile_arm_64.S
- runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_tile_arm_64_dotprod.S
- runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_tile_arm_64_i8mm.S
- runtime/src/iree/builtins/ukernel/common.h
- runtime/src/iree/builtins/ukernel/elementwise.h
- runtime/src/iree/builtins/ukernel/elementwise_generic.c
- runtime/src/iree/builtins/ukernel/elementwise_impl.c.inc
- runtime/src/iree/builtins/ukernel/mmt4d.c
- runtime/src/iree/builtins/ukernel/mmt4d_select_tile_generic.c
- runtime/src/iree/builtins/ukernel/mmt4d_types.h
- runtime/src/iree/builtins/ukernel/pack.c
- runtime/src/iree/builtins/ukernel/pack_types.h
- runtime/src/iree/builtins/ukernel/tools/mmt4d_benchmark.c
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test.cc
- runtime/src/iree/builtins/ukernel/tools/mmt4d_test_utils.cc
- runtime/src/iree/modules/vmvx/module.c
* Complete rewrite of the big comment at the start of ukernel/common.h. Please read carefully as I might be saying things that are incorrect.
* Ukernel local types prefixed to disambiguate from standard types, e.g. `int32_t` --> `iree_ukernel_int32_t`.
* This caught a place in `vmvx/module.c` that now requires an explicit cast from `unsigned long*` to `unsigned long long*`. I know these are always the same 64bit stuff in practice, but it's worth an explicit cast.
* Actually no longer including various platform headers in ukernels. In ukernel/common.h, we were including iree/base/attributes.h, which was including target_platform.h, which was including windows.h etc.
* Now ukernels that need a RESTRICT keyword can use IREE_UKERNEL_RESTRICT, forked from IREE_RESTRICT.
* We can almost, but …
> Tightening ukernel common definitions

- compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndPromote.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_cooperative_matrix.mlir
To make this happen, we need to adjust various passes to recognize
and handle matmul-like generic ops properly.
> [spirv] Enable cooperative matrix flow for matmul-like generic 

- build_tools/github_actions/runner/gcp/create_templates.sh
This matches the firewall rule that should hopefully be coming online
soon. Health checks require a special firewall rule for...some reason.
Tested: deployed new templates to test clusters.
skip-ci: template creation for the runners
> Tag runners to allow health checks

- build_tools/github_actions/runner/README.md
- build_tools/github_actions/runner/config/register.sh
- build_tools/github_actions/runner/gcp/create_templates.sh
- build_tools/github_actions/runner/gcp/update_instance_groups.py
This makes it possible to run production templates on testing runners,
which is useful to enable testing of something that has already been
committed and avoids mistakes (that I've made frequently) around the
environment metadata field. It's a bit hacky, but I think will make
updating these significantly easier.
This also names templates with non-prod modifications with a "testing"
suffix. To accomplish this, I had to shorten the template names quite a
bit. I think the result is actually much more readable.
Tested: Deployed new templates to testing runners -> 
https://github.com/iree-org/iree/actions/runs/3364878153/jobs/5579737086
skip-ci: configuration of the runners themselves
> Rework usage of testing templates

- .github/workflows/ci.yml
- .github/workflows/run_shark_tank.yml
- build_tools/github_actions/configure_ci.py
We already generally treat the PR description as a commit description
with title and body in this way (e.g. in our [squash and] merge commit
messages). I could've added any dummy title string, but this seemed
more understandable. We could also write our own parsing instead of
relying on interpret-trailers, but I think it's good to use a standard
tool.
Tested: https://github.com/iree-org/iree/actions/runs/3364878153/jobs/5579737086
> Fix parsing trailers when they're the only thing in the PR body

- tests/transform_dialect/cpu/BUILD
- tests/transform_dialect/cpu/CMakeLists.txt
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
A recent integration regression prompted the disabling of those tests. Reenable them.
> Reenable transform dialect tests.

- compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- tests/e2e/linalg_transform/BUILD
- tests/e2e/linalg_transform/CMakeLists.txt
- tests/e2e/linalg_transform/linalg_transform.mlir
- tests/transform_dialect/cpu/BUILD
- tests/transform_dialect/cpu/CMakeLists.txt
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
The nested pass pipeline and extra level of transform op indirection creates significant and
unnecessary registration complexities.
Instead, just make the transform op do what it needs.
This will need to be factored out better in the future to reuse code.
> Make the iree.bufferize transform op not call the IREEComprehensiveBufferizePass

- runtime/src/iree/hal/drivers/vulkan/api.h
- runtime/src/iree/hal/drivers/vulkan/registration/driver_module.cc
- runtime/src/iree/hal/drivers/vulkan/vma_allocator.cc
- runtime/src/iree/hal/drivers/vulkan/vma_allocator.h
- runtime/src/iree/hal/drivers/vulkan/vulkan_device.cc
`--vulkan_large_heap_block_size=0`: default today (64MB)
`--vulkan_large_heap_block_size=4294967295`: max for most desktops (4GB)
Valid values are based on device limits:
https://vulkan.gpuinfo.org/displaydevicelimit.php?name=maxStorageBufferRange&platform=all
> Adding flag for setting VMA preferredLargeHeapBlockSize.

- tests/e2e/linalg_ext_ops/unpack.mlir
The pack/unpack chain could be folded away. Updating the tests to not rely on pack ops is more stable. The commit also adds `static_` prefix to static test cases.
> Update e2e unpack tests to not rely on pack ops.

- compiler/src/iree/compiler/Dialect/Util/Transforms/IPO.cpp
- compiler/src/iree/compiler/Dialect/Util/Transforms/test/ipo.mlir
> Updating IPO to preserve base duplicate arguments.

- compiler/src/iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul_cooperative_ops.mlir
We cannot just take the minimal value there; need to make sure tile sizes properly divide.
> [spirv] Fix K tile size deduction for cooperative matrix

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/vectorize_load_store.mlir
This change enables vectorizing memref types used by GPU subgroup MMA ops so that we can be coherent and allow casting vector<8xf16> values into vector<4xf32> throughout.
> [spirv] Support GPU subgroup MMA ops in SPIRVVectorizeLoadStore

- .github/workflows/process_opened_issues.yml
(Untested)
Hoping this fixes errors like those on https://github.com/iree-org/iree/actions/runs/3380006187:
> [Adding issue to the IREE GitHub project](https://github.com/iree-org/iree/actions/runs/3380006187/jobs/5612284349#step:2:6)
Request failed due to following response errors: - The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement.
skip-ci: this workflow isn't covered by CI
> Bump actions/add-to-project version to use new API.

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Utils/Utils.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Utils/Utils.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/vectorization.mlir
It generalizes the unpack op into extract_slice + copy + insert_slice
ops. Because the outer dim sizes are all 1s, we're able to extract the
inner tiles from input, apply the transposition, and insert it back to a
tensor. It enables the vectorization for unpack op.
The vector ops are not generated if there is no transposition. Because
it is on tensor semantics, the linalg.generic op (i.e., copy op) is
folded away in this case.
For outer dim sizes that are not all 1s, we have to update the upstream
`scf::tileUsingSCFForOp` method to accept multi operations created
during tiling. That would be the next step after landing this commit.
The commit also moves `computeInterchangeFromDimPos` to utils.
> Add support for generalizing unpack op when outer dim sizes are all 1s. 

- compiler/src/iree/compiler/Codegen/SPIRV/NVIDIAConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_to_cooperative_ops.mlir
This commits enables us to have multiple tiles along M and N dimension
per warp when going through the cooperative matrix pipeline.
> [spirv] Allow multiple tiles on M/N dimension for cooperative matrix

- build_tools/github_actions/runner/gcp/remove_stuck_runners.sh
I was avoiding doing this because I was just going to add health checks,
but that has been dragging on due to obnoxious Google policies around
firewalls. This script just deletes runner instances that have had
sufficient time but for whatever reason haven't managed to register.
skip-ci: scripting
> Add script for removing instances that failed to register with GitHub

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/SetEncoding.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/set_encoding.mlir
- compiler/src/iree/compiler/Dialect/Stream/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Stream/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Stream/Transforms/EncodeTensors.cpp
- integrations/tensorflow/iree-dialects/test/Dialect/iree_linalg_ext/resolve-shaped-type-result-dims.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
This change adds a pass to set encoding for operations, and adapts dispatch region formation to put these operations into dispatches.
- `set_encoding` operations go into a separate dispatch. Any `pad` producers are fused with this operation.
- `unset_encoding` operations go into a separate dispatch. Any `extract_slice` consumer gets fused with this operation.
- `set_encoding` operations that are producers for the `outs` operands of `linalg` operations are pulled into the same dispatch as the `linalg` op.
Since the number of workgroups computation varies from the default used today, a new op
`flow.dispatch.workgroup_count_from_set_encoding_op` is added. This can be materialized once the `set_encoding` operation is converted to the `pack` operation in the backend based on machine …
> Flow changes for enabling data tiling.

- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/Patterns.cpp
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/Utils.cpp
- compiler/src/iree/compiler/Dialect/Flow/Conversion/TensorToFlow/Utils.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/ConvertLinalgTensorOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensorsViaRegionOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
This is an improvement to DispatchLinalgOnTensorsViaRegionOps.cpp: Certain tensor.insert_slice ops are lowered to flow.tensor.update ops. (Same as DispatchLinalgOnTensors.cpp.)
This is in preparation of #10719.
> dispatch-on-tensors-via-region-ops: Generate tensor.update ops

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndPromote.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_cooperative_matrix.mlir
When there is only one compute ops in the dispatch region, we don't need to promote C matrix to shared memory at all.
> [spirv] Avoid promoting C matrix if no fused elementwise ops

- compiler/src/iree/compiler/Pipelines/Pipelines.cpp
- compiler/src/iree/compiler/Pipelines/Pipelines.h
- compiler/src/iree/compiler/Tools/iree_compile_lib.cc
`--verify=false` disables verification similar to setting `-verify-each=0` in iree-opt. This can be useful when compiling models in debug builds as verification can often take 2-5x longer than actual compilation.
`--compile-to=` allows for early-exit of the compilation pipeline based on well-known stages: `input`, `abi`, `flow`, `stream`, `hal`, `vm`. Defaults to `end` which runs the entire pipeline to completion. Now if someone wants to see what their program looks like in the stream dialect they can just add `--compile-to=stream` and get the IR vs needing to slice/mangling print-ir-after commands.
> Adding `--verify` and `--compile-to=` flags to iree-compile.

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorizeLoadStore.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/vectorize_load_store.mlir
These transfer ops should be scalarized to avoid causing issues. We actually have tests for such cases but unfortunately they are all using odd-number as the innermost dimension so it ends up not catching the issue.
> [spirv] Avoid vectorizing non-minor-identity transfer ops

- build_tools/benchmarks/collect_compilation_statistics.py
- build_tools/benchmarks/common/benchmark_config_test.py
- build_tools/benchmarks/common/common_arguments.py
- build_tools/benchmarks/common/common_arguments_test.py
- build_tools/python/e2e_test_artifacts/cmake_generator/iree_rule_generator.py
- build_tools/python/e2e_test_artifacts/cmake_generator/iree_rule_generator_test.py
- runtime/src/iree/base/internal/wait_handle_win32.c
Most of these were comparing paths using string comparison, which breaks when comparing Unix paths with Windows paths or comparing symlinks with realpaths.
> Fix several tests on Windows.

- compiler/src/iree/compiler/Dialect/HAL/IR/HALBase.td
- compiler/src/iree/compiler/Dialect/HAL/IR/HALTypes.cpp
This allows unit tests to specify an executable target on a local function scope without requiring a full variant in order to get config.
Example:
```mlir
#some_target = #hal.executable.target<
"llvm-cpu", "embedded-elf-x86_64", {
data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128",
native_vector_size = 16 : index,
target_triple = "x86_64-unknown-unknown-eabi-elf"
}
>
func.func @set_encoding_op() attributes {
hal.executable.target = #some_target
} {
// IR that during transformation may want to lookup the target
return
}
```
> Adding `IREE::HAL::ExecutableTargetAttr::lookup` helper.

- runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_select_tile_arm_64.c
- runtime/src/iree/builtins/ukernel/common.h
- runtime/src/iree/builtins/ukernel/mmt4d.c
- runtime/src/iree/builtins/ukernel/mmt4d_select_tile_generic.c
- runtime/src/iree/builtins/ukernel/mmt4d_select_tile_generic.h
- runtime/src/iree/builtins/ukernel/mmt4d_types.h
Total code size (AArch64, Release) for iree_uk_mmt4d* symbols excluding tile funcs (`iree_uk_mmt4d_tile*`; the size of these is unaffected by this PR).
```
Before: 996 bytes
After:  704 bytes
```
So that's a -30% shrink! Now in practice, this code would be used together with one of the tile funcs, ~300 bytes in average. So the effective code size shrink (from e.g. a CPU L1 instruction cache perspective) would be from ~1,300 bytes to ~1,000. Still pretty good.
The over all size of *all* tile funcs is bigger (~2,700 bytes) but only one of them tends to be used on a given machine, in a given workload.
Part of this is carefully using `__builtin_unreachable`. Another part is ensuring that all validation is localized in `iree_uk_mmt4d_validate`, and disabling all that if `NDEBUG`. So there's a …
> Optimize code size of the mmt4d ukernel.

- runtime/src/iree/hal/drivers/vulkan/vulkan_driver.cc
The instance is not owned by the driver and must remain live after the driver has been destroyed.
> Fixing iree_hal_vulkan_driver_create_using_instance ownership.

- build_tools/cmake/iree_python.cmake
- runtime/src/iree/builtins/ukernel/tools/pack_test.cc
- samples/simple_embedding/BUILD
- samples/simple_embedding/CMakeLists.txt
Progress on https://github.com/iree-org/iree/issues/11009 (see some test runs of a `build_test_all_windows` CI job on https://github.com/iree-org/iree/pull/11050)
* Tag `simple_embedding_vulkan_test` as using Vulkan, so it can be filtered
* Initialize a struct in pack_test.cc
* Fix PYTHONPATH separator for iree_local_py_test on Windows (while keeping CMake happy)
> Assorted fixes for tests on Windows.

- tests/microbenchmarks/CMakeLists.txt
- tests/microbenchmarks/shared_mem_transpose.mlir
Set of microbenchmarks for validated shared mem transpose. 
Separated out from the existing `linalg_transpose.mlir` benchmarks since focusing on very large shapes for GPU. 
Part of https://github.com/iree-org/iree/issues/10005
> Adding Transpose Microbenchmarks

- compiler/src/iree/compiler/Codegen/Common/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/Common/test/warp_reduction.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_reduction_subgroup.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/reduction_lowering.mlir
- tests/e2e/regression/large_reduction.mlir
Instead of doing vector.reduction after obtaining warp reduction results, we apply another warp reduce to obtain the final reduction results.
This shouldn't give much perf boost on it's own,
but will give flexibility to enable warp reduction on fp16 and int8 down the line.
> [GPU] Apply warp reduce to intermediate warp reduce results.

- compiler/lit.cfg.py
- tests/lit.cfg.py
Progress on https://github.com/iree-org/iree/issues/11009
This fixes these two tests on Windows:
* `iree/compiler/Dialect/HAL/Target/LLVM/test/smoketest_system.mlir.test`
* `iree/tests/e2e/regression/libm_linking.mlir.test`
Developers should run vcvarsall before ctest, or configure their IDE as needed. For VSCode, I have this set:
```json
"cmakeExplorer.extraCtestEnvVars": {
"VCTOOLSINSTALLDIR": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\MSVC\\14.31.31103\\",
"UNIVERSALCRTSDKDIR": "C:\\Program Files (x86)\\Windows Kits\\10\\",
"UCRTVersion": "10.0.19041.0",
},
```
> Forward vcvarsall env vars through lit.cfg.py.

- runtime/src/iree/base/config.h
- runtime/src/iree/vm/bytecode_dispatch_util.h
It's a fairly marginal benefit to very heavy scalar VMVX workloads (~10-20%) but adds 20-30KB to the binary size and most users care more about that. Leaving the code path around so we can turn it back on if needed as workloads change.
```
ben@noxa-pc:/mnt/d/Dev/iree$ ../iree-build-wsl/runtime/src/iree/vm/bytecode_module_benchmark_switch --benchmark_min_time=10
2022-11-08T15:25:08-08:00
Running ../iree-build-wsl/runtime/src/iree/vm/bytecode_module_benchmark_switch
Run on (64 X 3700 MHz CPU s)
Load Average: 0.52, 0.58, 0.59
---------------------------------------------------------------------------------
Benchmark                                       Time             CPU   Iterations
---------------------------------------------------------------------------------
BM_ModuleCreate …
```
> Changing default bytecode dispatch away from computed goto.

- runtime/src/iree/builtins/ukernel/common.h
- runtime/src/iree/builtins/ukernel/elementwise_impl.c.inc
Before:
```
3.4%  22.7Ki    /mnt/d/Dev/iree/runtime/src/iree/builtins/ukernel/elementwise_generic.c
0.0%  2.23Ki   0.3%  2.20Ki    iree_uk_pack
0.0%  1.53Ki   0.2%  1.49Ki    iree_uk_x32b_shrsi_2d
0.0%  1.53Ki   0.2%  1.49Ki    iree_uk_x32b_shrui_2d
0.0%  1.49Ki   0.2%  1.44Ki    iree_uk_x32u_ctlz_2d
0.0%  1.24Ki   0.2%  1.19Ki    iree_uk_x32b_shli_2d
0.0%  1.20Ki   0.2%  1.16Ki    iree_uk_x32b_muli_2d
0.0%  1.16Ki   0.2%  1.11Ki    iree_vm_shim_ukernel_x32b_2d_v
0.0%  1.13Ki   0.2%  1.08Ki    iree_uk_x32b_addi_2d
0.0%  1.13Ki   0.2%  1.08Ki    iree_uk_x32b_andi_2d
0.0%  1.12Ki   0.2%  1.08Ki    iree_uk_x32b_ori_2d
0.0%  1.13Ki   0.2%  1.08Ki    iree_uk_x32b_subi_2d
0.0%  1.13Ki   0.2%  1.08Ki    iree_uk_x32b_xori_2d
0.0%     852   0.1%     797    iree_vm_shim_ukernel_x32u_2d_v
0.0% …
```
> Prevent inlining of ukernel elementwise ops into shims.

- samples/dynamic_shapes/Makefile
- samples/dynamic_shapes/README.md
- samples/dynamic_shapes/main.c
This is just intended as an example of how to construct a makefile that can compile and link a binary against a build of the IREE runtime unified library. Users in other build systems or with their own cmake utilities can use it to see what linking looks like. There are a lot of caveats with this approach and not using IREE as a cmake subproject is still YMMV.
> Adding a makefile to the dynamic_shapes sample.

- runtime/src/iree/base/internal/math.h
- runtime/src/iree/tooling/BUILD
- runtime/src/iree/tooling/CMakeLists.txt
- runtime/src/iree/tooling/trace_replay.c
- runtime/src/iree/tooling/trace_replay.h
- runtime/src/iree/vm/value.h
- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
- tests/e2e/matmul/generate_e2e_matmul_tests.py
- tools/BUILD
- tools/iree-e2e-matmul-test.c
This pull request adds support for testing e2e GEMM on a CUDA backend for F16 input and F16 accumulation. 
- Functional testing of F16 GEMMs requires setting the right tolerance value to ensure correctness checks.  
- Tolerance-based testing is fragile and finding tolerances is hard. 
- Instead we fill the buffers as small integers centered at zero and test for equivalence. 
This pull requests adds `e2e_matmul_direct_f16_gpu_large_LLVMGPUMatmulTensorCore_cuda_cuda` more e2e GEMM test to CUDA backend. We have not total 4 e2e GEMM tests on CUDA backend.
```bash
manigupta@manigupta-gpu-a100 ~/cpu_machine_workspace/repos/iree/iree_tree_1/iree-build-debug $ ctest -j96 -R e2e_matmul.*cuda
1/4 Test #41: iree/tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_LLVMGPUMatmulTensorCore_cuda_cuda ... …
```
> Add support for GEMM e2e Test For CUDA backend on F16 input

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/reduction_lowering.mlir
This is meant to be a temporary fix  failing tests before more proper ones land.
> [spirv] Disable subgroup reduction for SwiftShader

- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: 625796f408cc733f64aadd76171f13390217c201 (2022-11-09 13:03:39 +0100): Fix an unused-variable warning in release build, NFC.
* mlir-hlo: 7d65228690a5ce6a0f456507a831819590add4b7
* tensorflow: 224533a07a07fa72868727305e159a8d8bdd9a7d
> Integrate llvm-project at 625796f408cc and bump dependencies

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/GPUMultiBuffering.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Codegen/SPIRV/AMDConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.h
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/BUILD
- compiler/src/iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/illegal_configuration.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/lowering_matmul_promotion.mlir
1. Moves LLVMGPUMultiBuffering to Common
2. Enables specifying a pipeline depth in the SPIRV promotion matmul lowering pipeline
Depends on #11058 to guarantee shared memory promotion in the pipeline. The current defaults will prioritize shared memory promotion over pipeline depth, so if we can fit in shared memory by reducing the pipelining depth it will choose to do that over reducing the tiling sizes. Next step is to enable different pipelining schedules. Currently only enabled for AMD, picking good pipelining depths other platforms can come one at a time after more control over the pipeline scheduling is added (e.g. store in stage 0).
> [spirv] Enable multi-buffering for simt matmuls

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingPass.cpp
- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/TypePropagationPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/materialize_encoding.mlir
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
Under the data tiling approach, at the `Flow` level an `iree_linalg_ext.encoding` attribute is added to tensors to capture the need for a data layout transformation. During executable translation this encoding + information about backend can be used to decide how the encoding is to be materialized (using `pack` and `unpack` operations). This PR adds a pass to materialize the encoding for the CPU backends. It uses patterns from a similar pass in `IREE::LinalgExt::LinalgExtDialect`, in addition to adding legalizations for `hal.interface.binding`,
`flow.dispatch.tensor.load/store` and type conversion for `!flow.dispatch.tensor` type. To facilitate this
- A new class called `MaterializeEncodingTypeConverter`, that derives from `TypeConverter`, is added that is meant to be used with patterns …
> Add a pass to materialize the encoding during executable translation.

- build_tools/cmake/ctest_all.sh
Progress on https://github.com/iree-org/iree/issues/11009 (see other implementation ideas for filtering at https://github.com/iree-org/iree/issues/11009#issuecomment-1310942657)
> Exclude tests failing on Windows in ctest_all.sh.

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
https://github.com/iree-org/iree/pull/10529 updated the default so now we can drop this temorary workaround.
> [spirv] Drop workaround for reduction after changing default

- .github/workflows/ci.yml
Progress on https://github.com/iree-org/iree/issues/11009
Sample successful run: https://github.com/iree-org/iree/actions/runs/3448018286/jobs/5754640528
At first this will only run on postsubmit, then we can move this to presubmit if it is stable and we have enough resources. We should also keep an eye on how long this takes to run (checkout seems to take substantially longer than on Linux), and also consider using Docker to manage the dependencies and environment.
Notes:
* This does not test Vulkan or CUDA - we'd want a runner with a physical GPU (or SwiftShader) for that
* This downloads CUDA deps on demand via CMake (so there's some additional network activity)
> Add build_test_all_windows CI job.

- build_tools/cmake/iree_copts.cmake
- runtime/src/iree/hal/local/elf/platform/generic.c
- runtime/src/iree/hal/local/elf/platform/linux.c
`-Wpointer-arith` brings Clang and GCC in line with MSVC
`-fno-lax-vector-conversions` brings Clang in line with GCC.
> Some strictness to bring Clang, GCC and MSVC more in line with each other

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
> Typo in `linalg_ext.unpack` documentation

- compiler/src/iree/compiler/Codegen/Common/TransformDialectJitterPass.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileTensor.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/distribute_foreach.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/tile_on_tensor.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
- tests/transform_dialect/cpu/matmul_codegen_custom_dispatch_formation_spec.mlir
- tests/transform_dialect/cpu/matmul_codegen_default_spec.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_partial_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_v2_codegen_spec.mlir
`scf.foreach_thread` previously expressed thread mapping via an integer array, that was very confusing. To make mapping descriptive, the upstream MLIR implemented device mapping interface in https://reviews.llvm.org/D137413 . It provides a device mapping interface and two attributes GPUBlockMappingAttr and GPUThreadMappingAttr.
IREE uses upstream MLIR's transform dialect. This PR integrates new attributes to IREE's transform dialect examples.
Cherry-picks the following LLVM 
@6663f3470417523141ee87923840d17b35d6b4c7
@b7162e136edfbe7157e9341d4322705e50601796
@07665e78cb6008537e1ce6f5606d9838612d32fe
@0d845660f4e2c3dc3c1afc3db4c723db4bd32f01
> Use Device Mapping Interface for Transform Dialect Ops

- compiler/src/iree/compiler/Codegen/Common/TransformDialectJitterPass.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/Listener.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/TransformInterpreter.cpp
- llvm-external-projects/iree-dialects/lib/Transforms/Listener.cpp
- llvm-external-projects/iree-dialects/lib/Transforms/ListenerCSE.cpp
- llvm-external-projects/iree-dialects/lib/Transforms/ListenerGreedyPatternRewriteDriver.cpp
- llvm-external-projects/iree-dialects/test/lib/Transforms/TestListenerPasses.cpp
The new op is introduced in LinalgExt for now as it cannot be dynamically registered into the transform dialect atm. With this op, canonicalized_sequence does not DCE the SSA values introduced by ConfigExtractPartOp.
This is necessary to allow the next part of the config to be extracted without either DCE or dropped attributes under transforms limiting us.
With the existing ListenerGreedyPatternRewriteDriver.cpp, the new op would still be DCE'ed (!!!). 
So we also adapt the code to its recent upstream evolution.
> Introduce a transform.do_not_dce_operands

- .github/workflows/benchmarks.yml
Excludes TF model directories from benchmark suite archive.
It's not ideal to keep growing the exclusion rules, but the way the current benchmark suite is structured makes it not easy to select the required files. We will soon replace this part with the new benchmark suite so I think it's fine to have a temporary solution for now.
Fixes #11158
> Excludes TF model directories from benchmark suite archive

- build_tools/bazel/iree.bazelrc
- build_tools/cmake/iree_copts.cmake
- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- integrations/tensorflow/build_tools/bazel/iree-tf.bazelrc
- integrations/tensorflow/iree-dialects/lib/Dialect/Input/InputOps.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgExt/Passes/SplitReduction.cpp
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/Input/InputOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/SplitReduction.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
We can turn them back off if there's big integrates blocked by them but in the steady state having them off just leads to lazy inconsistency. TF is not warning-free and so the flag is moved so that we only ignore the deprecation warnings when building TF-related tooling. For IREE-owned code we are now clean.
> Fixing current deprecation warnings and re-enabling them.

- compiler/src/iree/compiler/Codegen/Common/TransformDialectJitterPass.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
This commit allows using the extracted config values for the second level tiling.
In the process, we add the ability to dynamically extract list of operations from pdl::OperationType values, both here and upstream.
This greatly simplifies manipulating pdl::Operation that capture lists of operations, interspersed with regular Values and Attr.
> Add support for extracting second-level tiling from config.

- .github/workflows/ci.yml
- build_tools/cmake/build_all.sh
- build_tools/cmake/ctest_all.sh
This fixes a build failure of the Python bindings on Windows. We were testing Python 3.10.8, but now we are testing Python 3.11.0.
* Old 3.10.8 success: https://github.com/iree-org/iree/actions/runs/3452338984/jobs/5762178428
* Old 3.11.0 failure: https://github.com/iree-org/iree/actions/runs/3461697554/jobs/5779634638
This pins the Python version used on the CI to 3.10. We can also fix the break by updating pybind11 to >= 2.10.1 (which will require rebuilding our Docker images, see https://github.com/iree-org/iree/pull/11155).
Successful run: https://github.com/iree-org/iree/actions/runs/3473912159/jobs/5806499215 (except for 1 new test failure)
> Set python-version to 3.10 in Windows CI job.

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
`consumerOp` can have more iterators than `tileSizes`'s size. So only look at the loops we want to tile.
This is still fine for now because iterators are strings, so that when we use `applyPermutationToVector`, a new vector will be created with only `tileSizes.size()` iterators permuated and copied over; the rest will be empty strings. Later `find_if_not` will stop properly. But later the iterators will be integer values. Then suddenly all redundant (and not copied over) iterators will become 0 (parallel) so causing out of bound issue.
> Fix indexing out of range in tileConsumerAndFuseProducers

- build_tools/benchmarks/CMakeLists.txt
- build_tools/benchmarks/collect_compilation_statistics.py
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_suite.py
- build_tools/benchmarks/common/benchmark_suite_test.py
- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
- build_tools/cmake/iree_python.cmake
- build_tools/python/e2e_test_artifacts/artifacts.py
- build_tools/python/e2e_test_artifacts/iree_artifacts.py
- build_tools/python/e2e_test_artifacts/iree_artifacts_test.py
Adds `load_from_run_configs` to `BenchmarkSuite` to load the exported benchmark run configs from e2e test framework.
This change also adds `get_module_path` to `iree_artifacts`, which is a simple way to get the compiled module path without building the whole structure of the artifact directory. I'm thinking the `iree_artifacts.ArtifactsRoot` (which is to help get all paths in the artifact directory) might be over-complicated and can be replaced by simple helper functions (like the `get_moule_path` in this change). Will clean up that part if eventually we find such design is unnecessary.
> Support loading run config to BenchmarkSuite

- .github/workflows/ci.yml
Wheeeee! Let's make things fast.
More seriously: these are now an option for us and I've set some up. We
also have more at the enterprise level. This removes the need for us to
managed our own self-hosted runners for CPU tasks. I'll work on moving
over the bigger jobs (more complicated because I need to change the
artifact passing).
> Execute runtime build on bigger managed runners

- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
This is to allow i64 emulation to pick up new 64-bit ops produced during `tosa.apply_scale` lowering.
Issue: https://github.com/iree-org/iree/issues/10996
> [spirv] Lower `tosa.apply_scale` before i64 emulation

- compiler/src/iree/compiler/Codegen/Common/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/Common/test/warp_reduction.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/reduction_lowering.mlir
Even though all the lanes write the same value it may be slower to the same location from multiple threads.
> [GPU] Prevent race condition when writing to shared memory in reduction

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
Since we only support 32bits type this is NFC but this pave the way to support more types efficiently.
> [NFC] Generalize reduction vector size calculation

- runtime/src/iree/hal/drivers/webgpu/pipeline_layout.c
- runtime/src/iree/hal/drivers/webgpu/pipeline_layout.h
- runtime/src/iree/hal/drivers/webgpu/staging_buffer.c
- runtime/src/iree/hal/drivers/webgpu/staging_buffer.h
- runtime/src/iree/hal/drivers/webgpu/webgpu_device.c
This fixes an error I was seeing when trying to initialize a posenet program:
```
The entry-point uses bindings in group 3 but [PipelineLayout] doesn't have a BindGroupLayout for this index
- While calling [Device "IREE WebGPU device"].CreateComputePipeline([ComputePipelineDescriptor]).
```
---
The next error message is this:
```
The buffer type in the shader (BufferBindingType::Storage) is not compatible with the type in the layout (BufferBindingType::Uniform).
- While validating that the entry-point's declaration for @group(3) @binding(0) matches [BindGroupLayout]
- While validating the entry-point's compatibility for group 3 with [BindGroupLayout]
- While calling [Device "IREE WebGPU device"].CreateComputePipeline([ComputePipelineDescriptor]).
```
That should be fixed with …
> [WebGPU] Use staging_buffer->bind_group_layout during pipeline creation.

- build_tools/cmake/iree_macros.cmake
- runtime/src/iree/base/CMakeLists.txt
- runtime/src/iree/base/loop_emscripten.c
- runtime/src/iree/base/loop_emscripten.h
- runtime/src/iree/base/loop_emscripten.js
- runtime/src/iree/base/loop_emscripten_test.cc
This is the start of an implementation of the [`iree_loop_t`](https://github.com/iree-org/iree/blob/main/runtime/src/iree/base/loop.h) interface (added back in https://github.com/iree-org/iree/pull/8329) for web browsers, using `setTimeout()`, Promises, and other JavaScript APIs for working with asynchronous operations and the browser event loop.
This only handles `IREE_LOOP_COMMAND_CALL` for now, but I'd like some feedback on the architecture / implementation style.
Some details that were tricky to figure out:
* This uses a JavaScript library that implements a C API: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript. We may end up with a few of these.
* The JavaScript library uses `dynCall_iiii` to call a provided …
> Initial iree_loop_t implementation for web browsers.

- runtime/src/iree/base/status.c
- runtime/src/iree/base/status.h
To avoid a circular dependency this takes an allocator by reference.
> Exporting iree_status_to_string.

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUDistribute.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
Now GPU transform dialect works with any attribute, but the attributes must be defined outside of the code generator. In this way, iree can define own mappers. This PR integrates this change into iree.
Cherry pick the following llvm. The PR and llvm should go together. @beaffb041c689deb30d9b06fb3a68a1a4bae48a4
> Decouple `GPUThreadMappingAttr` from GPU transform dialect

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/Tiling.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
This is a preparation for https://github.com/iree-org/iree/pull/11231, and we'll be able to upstream these tests easier.
The upstream tiling method is more robust about simplified affine ops and static shapes.
> Partially switch LinalgExt tiling tests to use scf::tileUsingSCFForOp.

- build_tools/cmake/build_and_test_asan.sh
Fixes #11203.
This PR started out as a tentative massaging of LSAN to avert some issue on CI bots, but that didn't work and it later appeared that there was a rich history of LSAN issues with Swiftshader and the correct course of action was to disable the LSAN part of ASAN when running ASAN tests on Vulkan.
Reusing this PR so we keep the motivating history in one place. See the below https://github.com/iree-org/iree/pull/11206#issuecomment-1320578288
> Disable LSAN in the ASAN tests on Vulkan

- build_tools/cmake/build_and_test_asan.sh
- tests/e2e/models/BUILD
- tests/e2e/models/CMakeLists.txt
- tests/e2e/regression/BUILD
- tests/e2e/regression/CMakeLists.txt
- tests/e2e/tensor_ops/BUILD
- tests/e2e/tensor_ops/CMakeLists.txt
- tools/test/BUILD
- tools/test/CMakeLists.txt
This PR reenables all tests that were disabled under ASan!
The LSAN failures that motivated the current exclude list should all be fixed by #11206.
Yet, simply dropping the exclude-list doesn't work, because some of the entries in that list are Lit tests that exercise multiple drivers in a way that's encoded as `//RUN` comments within the test source, opaque to the build and test system --- there was no way to tell which of those tests involved Vulkan.
It would be nice to only disable LSAN for the Vulkan part of these tests, but this isn't feasible as things are currently structured, with the multiple driver runs conflated withing a single Lit test source.
At first I introduced a new tag/label, `multi-driver-including-vulkan`, to label those tests, so that `build_and_test_asan.sh` could …
> ASan tests: account for multi-driver Lit tests

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/convert_to_loops.mlir
The correct permutation for the tiled loop is `outerDimsPerm` as the loop are already in the canonical form ABCabc.
> Fix conversion to loop for `unpack`

- build_tools/github_actions/runner/config/register.sh
- build_tools/github_actions/runner/config/setup.sh
I was planning to do this as health check, which integrates with the
actual MIG infrastructure, but that has ended up being a laborious
process due to Google security rules and I still haven't gotten it to
work. In the meantime, we've been having frequent issues with server
errors from the GitHub actions control plane, which mean that the
runners are never registered and the instances just sit around
counting as "running" according to the autoscaler.
This is a really simple method to just shut down the runners if setup
fails. We should also add retries and stuff, but this works for now and
should hopefully avoid us ending up with half our instance pool just
sitting idle.
Tested:
I added a non-deterministic failure in the setup script (see reverted
commit) and confirmed that some of the …
> Shut down runner VM if startup fails

- build_tools/python/e2e_test_artifacts/cmake_generator/iree_rule_generator.py
- build_tools/python/e2e_test_artifacts/cmake_generator/model_rule_generator.py
- tests/e2e/test_artifacts/generated_e2e_test_fetch_models.cmake
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
Remove redundant comments in generated CMake files, which are already described in the CMake rules themselves.
> Remove redundant comments in generated CMake files

- compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingPass.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/Passes.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
While making the `e2e/matmul` tests to use the data tiling path, some minor issues were discovered. Address those in this PR. THey will be exercised once the tests get flipped.
> Minor fixes to enable compilation of e2e matmul tests.

- build_tools/benchmarks/collect_compilation_statistics.py
- build_tools/benchmarks/common/benchmark_config.py
- build_tools/benchmarks/common/benchmark_config_test.py
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_driver.py
- build_tools/benchmarks/common/benchmark_driver_test.py
- build_tools/benchmarks/common/benchmark_presentation.py
- build_tools/benchmarks/common/benchmark_suite.py
- build_tools/benchmarks/common/benchmark_suite_test.py
- build_tools/benchmarks/common/common_arguments.py
- build_tools/benchmarks/diff_local_benchmarks.py
- build_tools/benchmarks/post_benchmarks_as_pr_comment.py
- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
- build_tools/benchmarks/upload_benchmarks_to_dashboard.py
Replace string paths with pathlib in benchmark tools. To help review, this change is bascially:
- Replace `str` with `pathlib.Path`
- Replace `os.path.join` with `/` operator
- Replace other `os.path` functions (https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module)
- Replace `open(file_path, x)` with `file_path.open(x)`
- In `run_benchmarks_on_android.py`, all paths on Android devices are marked as `pathlib.PurePosixPath`, to make sure the path format is correct in commands on Android devices. 
Fix #11055
> Replace string path with pathlib in benchmark tools

- compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
* [mlir][bufferization] Support general Attribute as memory space
> Cherry-pick llvm/llvm-project@9bb63374

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
The pass has been renamed on open source in expand-strided-metadata.
Cherry-picked the LLVM change that did the rename as part of this PR as well.
> Change the attributes and APIs around simplify-extract-strided-metadata

- compiler/src/iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- compiler/src/iree/compiler/Codegen/Sandbox/Passes.h
- compiler/src/iree/compiler/Codegen/Sandbox/Passes.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/CodegenStrategy.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
Use the upstream SCF tiling to replace `LinalgTilingPattern`.
This change also removes the `peeled-loops` option from `LinalgSingleTilingExpert`, which is unused and unsupported in the upstream (and we have a separate pass for peeling).
> Use upstream SCF tiling in CPU codegen

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
- tests/transform_dialect/cuda/vecadd2d.mlir
- tests/transform_dialect/cuda/vecadd2d_codegen_spec.mlir
`tile_to_foreach_thread_and_workgroup_count_region` explicitly maps dimensions to GPU thread blocks via attribute. This PR assigns workgroup size according to given dimensions of `scf.foreach_thread`
Take a look at a 2D vectoradd example with 'linalg.generic' and transform dialect.
```
linalg.generic {...} ins(%x: tensor<512x4xf32>) outs(%y: tensor<512x4xf32>) {...}
```
here is the transform dialect
```
transform.iree.tile_to_foreach_thread_and_workgroup_count_region %generic tile_sizes [4, 2] (
mapping = [#gpu.block<z>, #gpu.block<y>] )
```
Current iree launches the following which is wrong.
```
CUDA kernel <<< (gridDim.x=2, gridDim.y=128, gridDim.z=1), ...>>> -> Wrong!
```
This PR changes the kernel launch as below:
```
CUDA kernel <<< (gridDim.x=1, gridDim.y=2, gridDim.z=128), ...>>> …
```
> Fix setting of workgroup size for `tile_to_foreach_thread_and_workgroup_count_region` 

- build_tools/github_actions/configure_ci.py
- build_tools/github_actions/runner/gcp/update_instance_groups.py
Right now the check fires regardless of the command, but "version"
isn't set when promoting or rolling back a canary.
> Fix script for promotion of canary runners

- compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingInterface.cpp
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
The tiling sizes are set to multiple of inner tile sizes. In this context, we don't need stack buffer allocation for holding temp results.
Test case:
```mlir
%result = iree_linalg_ext.unpack %result_4d inner_dims_pos = [0, 1] inner_tiles = [8, 8] into %result_init
: (tensor<32x32x8x8xi32> tensor<256x256xi32>) -> tensor<256x256xi32>
```
The commit gives us 1.86x improvements (93.63 us -> 49.44 us).
> Enable tile+distribute+vectorize for unpack ops.

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
- tests/transform_dialect/cuda/reduction_eltwise.mlir
- tests/transform_dialect/cuda/reduction_eltwise_codegen_spec.mlir
Add a handwritten and a generated transform dialect schedule to support codegen for reduction+elementwise targeting CUDA. Unlike standalone reduction, this needs additional fusion into the trailing elementwise. The transform dialect generated on-the-fly differs when the elementwise is present. This should be eventually expressed in the dialect itself, but we are currently lacking the necessary ops.
> Support reduction+elementwise in transform dialect strategies

- compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingPass.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
This makes it an implementation detail of the `MaterializeEncodingFn` to actually use target info and element type to determine real (useful) tile sizes. See how the `iree/compiler/` side does a `IREE::HAL::ExecutableTargetAttr::lookup` from #11057 to get the `target` attribute. Meanwhile, #11291 will make it easy to obtain the details that we need based on that attribute (the existing codebase is still wired to deal with `ExecutableVariantOp`'s, needs to be adapted post #11057).
The element type is passed as a function argument, while the target info is not. Accordingly, when we want to actually depend on target info, at the place where we construct a `MaterializeEncodingTypeConverter` passing it a `MaterializeEncodingFn`, we can pass a function that itself depends on target info, as …
> Allow encoding info to depend on elem type and target info.

- compiler/src/iree/compiler/API2/CMakeLists.txt
- compiler/src/iree/compiler/API2/test/CMakeLists.txt
* Since it depends on a DLL, it must be placed properly.
Tested: Locally on Windows
See for a better solution: https://github.com/iree-org/iree/issues/11297
> Move the api-test binary to the project wide binary directory.

- docs/website/docs/bindings/c-api.md
Correct the usage of iree_vm_invoke in the exampl.
> Correct the usage of iree_vm_invoke in the example

- build_tools/cmake/iree_cc_binary.cmake
- build_tools/github_actions/build_dist.py
* Explicitly configures distribution to build lib/ directory (some OS's will default this to lib64 and we like consistency)
* Adapt install rpath logic to account for CMAKE_INSTALL_LIBDIR
> Add lib/ directory to dist tarball.

- .github/workflows/run_mmperf.yml
- build_tools/benchmarks/mmperf/build_mmperf.sh
- build_tools/benchmarks/mmperf/run_mmperf.sh
- build_tools/docker/context/setup_mmperf.sh
- build_tools/docker/dockerfiles/mmperf.Dockerfile
- build_tools/docker/manage_images.py
- build_tools/docker/mmperf/Dockerfile
- build_tools/docker/prod_digests.txt
Adds a Github workflow and Docker image for running mmperf (https://github.com/mmperf/mmperf). mmperf benchmarks matrix-multiply workloads on IREE and other frameworks such as RUY, TVM, Halide, etc. Reports are uploaded to the mmperf-benchmark-artifacts GC bucket.
> Add mmperf workflow

- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
This fusion interferes with further work on detecting and implementing fusion of elementwise operations in the transform dialect-driven codegen.
> [DONOTMERGETOMAIN] Add a flag to disable tensor fusion in flow

- build_tools/benchmarks/collect_compilation_statistics.py
- build_tools/benchmarks/common/benchmark_definition.py
This is a part of migrating benchmarks to the new e2e test framework.
In the e2e test framework, we have a clear separation between compile configs and run configs. Each of them has its own tags to describe the config. Previously we only have a single list `bench_mode` to represent the configs of each benchmark.
The `bench_mode` is part of the current primary key to identify each benchmark. Eventually we will deprecate this way and use artificial ids instead, but it won't happen soon. Right now we need to embed the tags in the primary key from both the compile configs and run configs, during the migration stage.
This change extends the `<bench_mode>` section in the benchmark key `MobileNetV2 ... <bench_mode> with IREE-LLVM-CPU ...` into `MobileNetV2 ... [<compile_tags>][<run_tags>] with …
> Separate bench_mode into bench_mode and compile_tags

- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td
- compiler/src/iree/compiler/Dialect/VM/IR/test/arithmetic_speculation.mlir
In MLIR, the `Pure` attribute entails `AlwaysSpeculatable`. This is not a good default for arithmetic VM ops because they are implemented in terms of C functions that may invoke Undefined Behavior (UB) on some inputs, e.g., on signed integer overflow in `vm.add.i32`:
```c
static inline int32_t vm_add_i32(int32_t lhs, int32_t rhs) { return lhs + rhs; }
```
Update LICM-based speculation LIT test for arithmetic ops.
Next, we should update the C implementation of some ops affected by this change and make them speculatable.
Issue: https://github.com/iree-org/iree/issues/11179
> [vm] Do not define all arithmetic ops as `Pure`

- build_tools/third_party/spirv-tools/CMakeLists.txt
- build_tools/third_party/tint/CMakeLists.txt
* Fixes https://github.com/iree-org/iree/issues/10908
* I still see this error: https://github.com/iree-org/iree/issues/10906
* There are new errors with `exp`, `log`, `sigmoid`: `error: value cannot be represented as 'f32': -inf` (not totally unexpected given the current policy on NaN/Inf, but good to keep tracking: https://github.com/iree-org/iree/issues/10142)
I did add some relevant tests before (https://github.com/iree-org/iree/pull/10909), but we had to revert that change because of an incomplete CMake cross compilation configuration: https://github.com/iree-org/iree/pull/10918. It's worth trying that again.
> Bump Tint, spirv_headers, and spirv-tools to latest.

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVEmulateI64.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/emulate_i64.mlir
Later SPIR-V conversion passes assume that n-D vectors have already been lowered to 1-D vectors. Add a vector flattening steps immediately after running upstream i64 emulation patterns that are known to increase vector dimensionality.
> [spirv] Do not introduce 2-D vectors in i64 emulation

- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/TargetMLTransformInfo.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/TargetMLTransformInfo.h
- compiler/src/iree/compiler/Codegen/Utils/Utils.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.h
#11057 added a `IREE::HAL::ExecutableTargetAttr::lookup` function which should be the preferred way to get a `ExecutableTargetAttr`, since it honors the overrides made possible by that PR.
It's also neatly shrinking code at call sites, and better conveys intent: before, we were querying a `ExecutableVariantOp` only to get at the `ExecutableTargetAttr`, now we query directly the latter.
The Utils are updated to all take a `ExecutableTargetAttr`, and since they were already implementing logic to handle optionally present fields, this further simplifies logic at call sites.
Some Utils implementation functions, which were internal, are now exposed in `Utils.h`. Particularly `getConfigStringAttr`. There seemed to be no point having various place in the code reimplement that boilerplate …
> Consistently query `ExecutableTargetAttr`

- integrations/tensorflow/iree-dialects/BUILD
- integrations/tensorflow/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/PassDetail.h
- integrations/tensorflow/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.td
- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/PassDetail.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.td
Pass explicitly performs vectorization and fails when runnign independent of the vector dialect. Added a dep to avoid crashing during run.
> Fix dependency on VectorDialect

- compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingPass.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
In #11290 I assumed that the element type was the only part of the shaped type that the EncodingInfo would need to depend on, but I was forgetting that in certain narrow-shape cases, the narrow dimension values are actually relevant. The idea is that we can avoid padding a very narrow matrix to the kernel tile size, by adjusting the kernel tile size accordingly. The prime example is in matrix-times-vector products: we don't want to turn the vector into a matrix of width say 8 just because that's the width of our matrix-times-matrix kernel. The existing matmul-to-mmt4d pass has code for this, generating narrow kernel tile shapes, here, Compare `m0k0n0`, `m0k0n0ForMatVec`, `m0k0n0ForWhenRhsHas2Columns`: https://github.com/iree-org/iree/blob/7723971eb7ecabfe8cda394de1e474e23b89a38c/compiler/s …
> EncodingInfo may depend on the shape, not just on the element type

- integrations/tensorflow/test/iree_tf_tests/uncategorized/vulkan__fill.run
This should make the the CI green again.
Issue: https://github.com/iree-org/iree/issues/11277
> [vulkan] Disable flakey test (`vulkan__fill`)

- compiler/src/iree/compiler/Codegen/Common/VectorReductionToGPU.cpp
- compiler/src/iree/compiler/Codegen/Common/test/warp_reduction.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/lowering_reduction.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_reduction_subgroup.mlir
The last merge potentially doesn't need to reduce across all the lanes.
> [GPU] Reduce the number of warp shuffles needed for reduction

- CMakeLists.txt
- compiler/src/iree/compiler/API2/CMakeLists.txt
This is enabled by default and tools link in the fancy shared library. When disabled the tools link in the static library version. This can be useful when wanting to build standalone binaries. It's also useful to work around MSVC's link.exe issues with ilk files >4GB that we run into with the shared library enabled.
> Adding IREE_LINK_COMPILER_SHARED_LIBRARY cmake flag.

- compiler/src/iree/compiler/Dialect/Util/Conversion/MemRefToUtil/Patterns.cpp
- compiler/src/iree/compiler/Dialect/Util/Conversion/MemRefToUtil/test/memref_ops.mlir
- compiler/src/iree/compiler/Dialect/Util/IR/UtilInterfaces.td
- compiler/src/iree/compiler/Dialect/Util/IR/UtilOpFolders.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.td
- compiler/src/iree/compiler/Dialect/Util/IR/UtilTypes.h
- compiler/src/iree/compiler/Dialect/Util/IR/test/buffer_folding.mlir
- compiler/src/iree/compiler/Dialect/Util/IR/test/buffer_ops.mlir
- compiler/src/iree/compiler/Dialect/VM/Conversion/UtilToVM/test/buffer_ops.mlir
- compiler/src/iree/compiler/Dialect/VMVX/Conversion/HALToVMVX/ConvertHALToVMVX.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/MaterializeConstants.cpp
- compiler/src/iree/compiler/Dialect/VMVX/Transforms/test/materialize_constants.mlir
- compiler/src/iree/compiler/Modules/HAL/Inline/Conversion/HALToHALInline/Patterns.cpp
- compiler/src/iree/compiler/Modules/HAL/Inline/Conversion/HALToHALInline/test/buffer_ops.mlir
- compiler/src/iree/compiler/Modules/HAL/Inline/Conversion/StreamToHALInline/Patterns.cpp
- compiler/src/iree/compiler/Modules/HAL/Inline/Conversion/StreamToHALInline/test/resource_ops.mlir
- compiler/src/iree/compiler/Modules/HAL/Inline/Transforms/test/inline_executables.mlir
This will allow ops outside of the util dialect to have subranges updated by generic canonicalization patterns.
Progress on #11027, VMVX ops need to implement these interfaces.
> Adding SubrangeOperandOpInterface to better fold util.buffer.subspan.

- runtime/src/iree/task/poller.c
It was possible for the wait retire to wake the task owner and have them yank it out from under the poller while it was still cleaning up.
Fixes #11317.
> Fixing race in task wait poller timeout handling.

- build_tools/cmake/iree_check_test.cmake
- tests/e2e/tosa_ops/CMakeLists.txt
- tests/e2e/xla_ops/CMakeLists.txt
This reverts https://github.com/iree-org/iree/pull/10918 to roll forward https://github.com/iree-org/iree/pull/10909, adding a hack to skip WebGPU testdata compilation when cross compiling. The right way to add this test coverage is likely either
* Adding a new test macro that just tests compilation without even considering runtime/execution
* Adding the `IREE_HAL_DRIVER_WEBGPU` option and running tests with it (this won't really work until I have more tests working, and the tools are updated to somehow handle async readback... so I'm not hopeful about this approach for at least several months)
> [WebGPU] Add compilation tests for xla_ops/ and tosa_ops/ (again).

- build_tools/cmake/iree_copts.cmake
- build_tools/cmake/iree_hal_cts_test_suite.cmake
- runtime/src/iree/vm/BUILD
- runtime/src/iree/vm/CMakeLists.txt
- runtime/src/iree/vm/test/BUILD
- runtime/src/iree/vm/test/CMakeLists.txt
- tools/CMakeLists.txt
* Remove explicit compile_tool arg when set to the default
* Remove unsupported/spurious PUBLIC option
* Remove no longer used IREE_TARGET_GUI_LINKOPTS
> Cleanup unused variables from a few build system files.

- build_tools/buildkite/cmake/build_configurations.yml
- build_tools/cmake/setup_ccache.sh
There's some write error configuring ccache:
https://buildkite.com/iree/iree-build-configurations/builds/5522
This should be fixable, but really the right fix is to just create
GitHub actions build and delete these Buildkite ones:
https://github.com/iree-org/iree/issues/9855
> Turn off ccache in buildkite configurations build

- compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/materialize_encoding.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/SetEncoding.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/set_encoding.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtBase.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/materialize_encoding.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/resolve-shaped-type-result-dims.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir
`TensorEncoding` is used to determine tile sizes in `MaterializeEncoding`. These depend on which SIMD instructions we want to use to perform a matmul, which in turn depends on the (LHS, RHS, RESULT) element type triple of the matmul --- not just one tensor's element type in isolation.
While updating `SetEncoding`, I found some opportunity to tidy up. The pattern was performing some rewrites (padding) before it was done potentially returning failure, so I have reordered that. And the local variables are renamed to be more explanatory.
> Encode the matmul type triple in `TensorEncoding` 

- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUCheckIRBeforeLLVMConversion.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/check_ir_before_llvm_conversion_not_fail_unbound.mlir
- tests/e2e/regression/BUILD
- tests/e2e/regression/CMakeLists.txt
All the necessary changes have landed to enable aggressive fusion on a softmax input. This compiles, but results in a stack allocation that is more than the allowed bounds. For now this test is added with the bound check relaxed, but that will need to be addressed as well.
> Add a test that compiles softmax under aggressive fusion.

- compiler/src/iree/compiler/Codegen/Common/GPUPipelining.cpp
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.cpp
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.h
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/Verifiers.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/SPIRV/AMDConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.h
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/lowering_matmul_promotion.mlir
Depends on #11086. Enables putting vector.transfer_write ops in stage 0 of the pipeline along with reading from global memory.
> Enable GPU pipeline schedule with shared memory stores in stage 0

- compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/data_tiling_pipeline.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_default.mlir
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
It also updates the LinalgExtVectorization to use tile+fuse, so we can
tile+fuse the generic ops.
Some metric data w/ mobilebert fp32:
The number of dispatches:
- Legacy mmt4d: 39
- data tiling w/o fusion: 57
- data tiling w/ pack fusion: 59
It's reasonable for having more different dispatches because some of different set_encoding ops could be folded into same producer dispatches. E.g., we could have dispatch_A, LHS_encoding, RHS_encoding in the beginning. After more aggressive fusion, we could get `dispatch_A + LHS_encoding` + `dispatch_A + RHS_encoding` + `LHS_encoding` + `RHS_encoding`. There would be 4 dispatches after fusion. We should use the metric about the number of kernel launch.
The number of `flow.dispatch` launch:
- Legacy mmt4d: 1980
- data tiling w/o fusion: 2871
- data …
> Enable fusion for elementwise Linalg op + pack op

- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
This avoids triggering validation failures when printing in verbose debugging mode.
> [spirv] Use a placeholder pointer type when creating resources

- .github/workflows/run_mmperf.yml
- build_tools/benchmarks/mmperf/build_mmperf.sh
- build_tools/docker/context/setup_mmperf.sh
- build_tools/docker/dockerfiles/mmperf.Dockerfile
- build_tools/docker/prod_digests.txt
Fixes how the github repo is cloned according to comments in https://github.com/iree-org/iree/pull/10956#discussion_r1029856233
> Fixes how the mmperf repo is cloned in the mmperf workflow

- .github/workflows/advance_upstream_forks.yml
- .github/workflows/android_tflite_oneshot_build.yml
- .github/workflows/benchmarks.yml
- .github/workflows/build_package.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/oneshot_candidate_release.yml
- .github/workflows/publish_website.yml
- .github/workflows/run_mmperf.yml
- .github/workflows/run_shark_tank.yml
- .github/workflows/schedule_candidate_release.yml
- .github/workflows/validate_and_publish_release.yml
- Upgrade actions/checkout to version 2.5.0
- Upgrade actions/setup-python to version 2.3.3
Unfortunately these haven't started using the newer Node version, so
we're still stuck with a bunch of warnings about using Node 12 from
GitHub's own actions :roll_eyes:
Fixes https://github.com/iree-org/iree/issues/10547
> Bump actions to versions using environment files

- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
- compiler/src/iree/compiler/Dialect/Vulkan/Utils/TargetEnvironment.cpp
* [mlir][spirv] Check GlobalVariableOp result to be of pointer types
* [mlir][spirv] Improve vector extract/insert element conversion
* [mlir][spirv] Allow controlling subgroup size
* [mlir][spirv] Fix missing parameter usage
> Cherry-pick some SPIR-V related MLIR commits

- compiler/src/iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- integrations/tensorflow/WORKSPACE
- integrations/tensorflow/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
LLVM: 61aed52c9ec0bca9979922ed2762785ec1f39755
MHLO: 00cbb603af9179ab6b792b583f4eb7999c0c7cc8
TF: cfe950a3f9b48555816aeece894ed6a7a2271749
carried cherry-pick:
4c23f93b2fae3fb76dc841d6e875ac598100c074
78c792324c5ecf32e1ddd44ce306429667c2cec5
dd6655376816622ffa9a344c651c7ea7be5cb2e7
Additional change:
remove usage of enableLowerPermutationMaps
> Integrate at llvm/llvm-project@61aed52c and bump dependencies

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_default_linalg_ops.mlir
- compiler/src/iree/compiler/Codegen/Utils/BUILD
- compiler/src/iree/compiler/Codegen/Utils/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Utils/Utils.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.h
- integrations/tensorflow/test/iree_tf_tests/layers/vulkan__dynamic_dims_Softmax.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_log_softmax.run
- integrations/tensorflow/test/iree_tf_tests/math/vulkan__dynamic_dim_softmax.run
So far we were not distributing higher level dimensions for operations with more than 3 parallel dimensions. This delinearize the z dimension for case with more than 3 dimension and allow better distribution if the kernel config asks for it.
Also change the default config of llvmgpu and spirv backend to take advantage of that.
> Support distribution to more than 3 dimension at the workgroup level

- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToNVVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToROCDL.cpp
Subviews and other view like operations will soon require to be expanded via expand-strided-metadata before being able to be converted to the LLVM dialect (convert-memref-to-llvm).
This change is a little bit ahead of the LLVM open source curve because the expansion is not yet required, but it doesn't hurt to do right now.
By adopting this change early we avoid holding the LLVM integration when this requirements will be enforced (i.e., when https://reviews.llvm.org/D136377 lands in LLVM.)
This PR is built on top of https://github.com/iree-org/iree/pull/11257, i.e., you can ignore the first commit.
> Adopt the new memref lowering process

- compiler/src/iree/compiler/Codegen/Common/UserConfig.cpp
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.cpp
- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.h
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
This makes various helper functions more targeted and cleaned up some duplicated logic.
> NFC: Separate setting translation info and dispatch configuration

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/illegal_configuration.mlir
This allows us to override deduction and stick to the specified configuration for testing purposes. Using normal lowering_config would be ignored and we are still going through deduction to figure out the configuration; so if the deduction logic changes, these test can silently change or fail.
> [spirv] Change illegal configuration test to use user control

- build_tools/buildkite/samples.yml
Copy of https://github.com/iree-org/iree/pull/11363 for the samples pipeline.
---
There's some write error configuring ccache: https://buildkite.com/iree/iree-samples/builds/555#0184cb06-ee2f-434b-8325-c9383f526a73
This should be fixable, but really the right fix is to just create GitHub actions build and delete these Buildkite ones.
skip-ci: buildkite only
> Turn off ccache in buildkite samples build.

- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
Some metric data w/ mobilebert fp32:
Legacy mmt4d: 39
data tiling w/ pack fusion: 59
data tiling w/ pack + unpack fusion: 57
The number of `flow.dispatch` launch:
Legacy mmt4d: 1980
data tiling w/ pack fusion: 2750
data tiling w/ pack + unpack fusion: 2390
Note that there are 361 `pack(constant)` kernel launches. The number of dispatch launches in data tiling approach is close to legacy mmt4d if we subtract pack(constant) from it.
> Enable fusion for unpack + elementwise ops.

- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/test/smoketest.mlir
PTX programming models provides some performance tuning directives; see https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#performance-tuning-directives The downstream compiler namely ptxas leverages these information for better register allocation or to handle other resource management that improves the performance.
As far as I understand, iree always knows the number of threads. This PR sets `maxntid` to CUDA kernel.
> Set maximum number of threads in the thread block for CUDA

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- tests/e2e/linalg_ext_ops/BUILD
- tests/e2e/linalg_ext_ops/CMakeLists.txt
This patch adds SPIRV support for the winograd output op. It reuses the same config and pipeline as the winograd input op.
> Add SPIRV backend support for Winograd output op

- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
This helps to avoid later bufferization problems coming from converting a convolution with bias. e.g. before we would see this
```mlir
func.func @forward_dispatch_195_matmul_256x65536x512(%arg0: !flow.dispatch.tensor<readonly:tensor<256x512xf16>>, %arg1: !flow.dispatch.tensor<readonly:tensor<512x65536xf16>>, %arg2: !flow.dispatch.tensor<readonly:tensor<256x65536xf16>>, %arg3: !flow.dispatch.tensor<readonly:tensor<256x65536xf16>>, %arg4: !flow.dispatch.tensor<readonly:tensor<256xf16>>, %arg5: !flow.dispatch.tensor<writeonly:tensor<256x65536xf16>>) {
%0 = flow.dispatch.tensor.load %arg0, offsets = [0, 0], sizes = [256, 512], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<256x512xf16>> -> tensor<256x512xf16>
%1 = flow.dispatch.tensor.load %arg1, offsets = [0, 0], sizes = [512, …
```
> [Flow] Move Convert1x1FilterConvToMatmul to come after DetachElementwiseFromNamedOps

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- tests/transform_dialect/cuda/eltwise_reduction.mlir
- tests/transform_dialect/cuda/eltwise_reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/eltwise_reduction_dispatch_spec.mlir
- tests/transform_dialect/cuda/eltwise_reduction_eltwise.mlir
- tests/transform_dialect/cuda/eltwise_reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/eltwise_reduction_eltwise_dispatch_spec.mlir
Depends on #11314
IREE will automatically fuse the leading elementwise into a reduction,
so we need to instruct it otherwise via the CLI option and to form the
dispatch region manually using another transform dialect snippet.
> Add strategy+test for reduction(elementwise)

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/TransformMatchers.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/TransformMatchers.h
- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/reductions.mlir
- compiler/src/iree/compiler/Codegen/Common/test/reductions_codegen_spec.mlir
Instead of relying on the fragile matching of all payload operations of
the same kind and splitting them in the fixed number of singleton
buckets, use the C++ callback to match the reduction structure. Now, the
exact same callback is used to find the case where the transform
dialect-based pipeline applies and to identify the ops that are
transformed later on. This is still suboptimal as the matching is done
twice, but further integration is left to future work. So are
integration tests via C++ builder API for the transform dialect.
> Use C++ callbacks to match reductions inside the transform dialect

- compiler/src/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
- runtime/src/iree/hal/drivers/vulkan/extensibility_util.cc
- runtime/src/iree/hal/drivers/vulkan/extensibility_util.h
- runtime/src/iree/hal/drivers/vulkan/native_executable.cc
- runtime/src/iree/hal/drivers/vulkan/vulkan_device.cc
- runtime/src/iree/schemas/spirv_executable_def.fbs
This commit plumbs through support for VK_EXT_subgroup_size_control in Vulkan HAL driver. The extension is marked as optional and requested when available. SPIR-V executable FlatBuffer gains a field to encode the requested subgroup size from CodeGen, 0 meaning no requirement.
This is to be used in a later commit to enable selecting wave32 mode for AMD RDNA architectures.
> [vulkan] Add support for VK_EXT_subgroup_size_control

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndPromote.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Utils.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Utils.h
- compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/illegal_configuration.mlir
This commit connects previous changes for supporting VK_EXT_subgroup_size_control and enables it for AMD architectures with cooperative matrix support.
> [spirv] Enable use wave32 mode for AMD architectures

- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp
Fixes https://github.com/iree-org/iree/issues/9319 in preparation of impending switch to use opaque pointers
> Move IREE LLVM backends to use opaque pointers.

- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndPromote.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Utils.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Utils.h
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_cooperative_matrix.mlir
For cases like linalg.matmul + arith.extf, bufferization inserts an allocation because of the different element type of those two ops. Here we already have the C matrix in workgroup memory; there is no need to promote it again. Though we need to make sure to use the proper marker so that we can insert barriers and enable following steps to distribute to SIMT threads.
> [spirv] Fix C matrix promotion with bufferization allocations

- benchmarks/TFLite/android-arm64-v8a.cmake
- build_tools/benchmarks/comparisons/setup_mobile.sh
- build_tools/python/benchmark_suites/iree/armv8_a_benchmarks.py
- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
Not switching `vmvx` e2e tests for now because that has to wait until we implement tile size selection for the VMVX backend.
> Switch e2e tests and benchmarks to `--iree-flow-enable-data-tiling` on `llvm-cpu`

- benchmarks/TFLite/android-arm64-v8a.cmake
- build_tools/benchmarks/comparisons/setup_mobile.sh
- build_tools/python/benchmark_suites/iree/armv8_a_benchmarks.py
- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
Due to the #11434, I think we can revert iree-org/iree#11411 first.
> Revert "Switch e2e tests and benchmarks to `--iree-flow-enable-data-tiling` on `llvm-cpu`"

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- tests/transform_dialect/cuda/eltwise_reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/eltwise_reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v2_codegen_spec.mlir
Suppressing all errors in the top-level sequence significantly worsens the debugging experience, especially in the current integration setup where some passes will still apply and some IR will be emitted. Localize error suppression around the only op that we actually expect to fail.
> Avoid suppressing all failures in transform scripts

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/ConvertConv2DToWinograd.cpp
When doing constant folding for weights in fp16,
we do the folding in f32 and then cast to fp16
at the very end.
> Fix Winograd constant folding for F16 weights

- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMBase.td
- compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td
- compiler/src/iree/compiler/Dialect/VM/Tools/VMOpEncoderGen.cpp
This is in preparation for upstream deprecation of raw accessor formats.
> Change VM dialect to generate and use prefixed accessors

- benchmarks/TFLite/android-arm64-v8a.cmake
- build_tools/benchmarks/comparisons/setup_mobile.sh
- build_tools/python/benchmark_suites/iree/armv8_a_benchmarks.py
- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
This relands
https://github.com/iree-org/iree/commit/044017ff9af0bb94128fe0fc1e533952a7a9c013
except flipping the pipeline for MobileBertInt8.
> Relands "Switch e2e tests and benchmarks to `--iree-flow-enable-data-tiling` on `llvm-cpu`"

- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/gpu_set_num_workgroups.mlir
Remove hardcoded check for sm_80 and start basic target structure to keep track of the hardware feature supported.
> [LLVMGPU] Add basic support for target feature checks

- benchmarks/TFLite/android-mali.cmake
- build_tools/python/benchmark_suites/iree/mali_benchmarks.py
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
Start tracking performance of i8 models before we start generating integer dot product ops.
> [vulkan] Enable MobileBERT i8 benchmark on Mali

- compiler/src/iree/compiler/Dialect/Stream/Analysis/Partitioning/ReferencePartitioning.cpp
> Avoid mutating stream partition op infos while testing.

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- tests/transform_dialect/cuda/vecadd2d.mlir
- tests/transform_dialect/cuda/vecadd2d_codegen_spec_partial_tile.mlir
The permutation of tile sizes based on `mapping` was computed incorrectly before.
> Fix bug in tile_to_foreach_thread mapping computation

- samples/native_training/native_training.py
This is no longer necessary, and the symbol name was changed recently, causing the build to break: https://buildkite.com/iree/iree-samples/builds/563#0184e9f1-f3e6-415f-81d7-d9b8d088cb25
> Remove strip_overloads from native_training example.

- compiler/src/iree/compiler/Codegen/Common/GPUPatterns.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUPatterns.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
This is in preparation to be used by SPIR-V CodeGen flow.
> NFC: Move CombineTransferReadOpBroadcast to Common/GPUPatterns

- .github/workflows/advance_upstream_forks.yml
GitHub has new personal access tokens that allow finer-grained controls
over what can be accessed. We've been asked to migrate to these new
tokens. I've created a new secret with such a token. I'm trying it out here first, since this workflow is not particularly critical. Once all
workflows are migrated to this token, I may duplicate it as
`WRITE_ACCESS_TOKEN` and switch them all back to that, so that we can
keep the old name, but I didn't want to update the value all at once
and break everything.
skip-ci: Doesn't affect CI workflows.
> Update 'advance upstream forks' action to use new fine-grained tokens

- .github/workflows/publish_website.yml
Part of https://github.com/iree-org/iree/issues/11479
skip-ci: Doesn't affect CI workflows
> Update 'publish website' action to use new fine-grained tokens

- .github/workflows/build_package.yml
- .github/workflows/oneshot_candidate_release.yml
- .github/workflows/schedule_candidate_release.yml
- .github/workflows/validate_and_publish_release.yml
- docs/developers/debugging/releases.md
Part of https://github.com/iree-org/iree/issues/11479
The last two workflows worked fine. Let's see if we can just switch
everything over. I'll roll back if this messes up the release.
skip-ci: doesn't affect CI workflows
> Update release workflows to use new fine-grained tokens

- CMakeLists.txt
We should use FILEPATH as the type there and check whether the file exists. Also we don't need to download if only building the compiler with IREE_CUDA_LIBDEVICE_PATH supplied.
> Fix CUDA libdevice checking in CMake

- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Codegen/SPIRV/AMDConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.h
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVLowerExecutableTargetPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_vectorize_to_cooperative_ops.mlir
Multibuffering needs to happen after thread-level tiling but before vectorization. This is solved here by splitting up the createSPIRVTileAndVectorizeToCooperativeOpsPass and then puts multibuffering between the tiling and vectorization passes.
> [SPIRV] Add multibuffering and pipelining to cooperative matrix

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
- tests/e2e/linalg_ext_ops/pack.mlir
The distribution does not happen along inner tile sizes. This commit adds a variable to MaterializeEncodingInfo, which indicates the rank of the source. This helps determine how many dimensions can be distributed when materializing encoding ops in TileAndDistribute pass.
The vectorization is skipped on llvm-cpu side when inner tile sizes are dynamic. Because vectorization requires all dimensions being static, and we don't tile on inner tiles at all.
It also adds two e2e tests for dynamic inner tiles cases.
> Plumb e2e support for packing on dynamic inner tiles.

- .github/workflows/advance_upstream_forks.yml
- .github/workflows/build_package.yml
- .github/workflows/oneshot_candidate_release.yml
- .github/workflows/publish_website.yml
- .github/workflows/schedule_candidate_release.yml
- .github/workflows/validate_and_publish_release.yml
- docs/developers/debugging/releases.md
The transition to the new token style was successful and I'll be
deleting the old-style token, so there's no need for the disambiguating
prefix. I've already changed the value of the secret to be a new
fine-grained token.
Fixes https://github.com/iree-org/iree/issues/11479
skip-ci: Does not affect presubmit workflows
> Rename FG_WRITE_ACCESS_TOKEN back to WRITE_ACCESS_TOKEN

- .github/workflows/ci.yml
Remove `--gzip-in-flight-all` when uploading e2e test artifacts, which reduces the uploading time from 5mins to 18s.
Tried to compress with ZSTD first but it increased the whole process to 24s. ZSTD also only saves the total size by 12%, so I think it isn't worth compressing the artifacts right now.
Fix #11356
> Don't compress e2e test artifacts when uploading

- compiler/src/iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
There can be non DPS operands for LinalgExt ops, this is a more general fix that was landed in https://github.com/iree-org/iree/pull/11487
> Proper fixes for bufferizing LinalgExt ops that have non DPS operands.

- build_tools/buildkite/cmake/linux/cuda/benchmark.yml
- build_tools/buildkite/cmake/linux/x86_64/benchmark2.yml
Fix the paths of benchmark directory broke by #11397
> Fix benchmark directory paths in buildkite pipeline

- compiler/src/iree/compiler/Codegen/SPIRV/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_amd_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/config_nvidia_matmul_cooperative_ops.mlir
Removes single trip loops before multi-buffering and makes sure not to multi-buffer if the inner reduction loop is single trip.
> [spirv] Add cleanup before multibuffering in wmma

- build_tools/github_actions/runner/config/health_server/health_server.py
- build_tools/github_actions/runner/config/setup.sh
- build_tools/github_actions/runner/gcp/create_instance_group.sh
For now, it literally always returns an HTTP 200 response. All this does
is confirm that the startup script has completed and nothing has killed
the health server. Unlike the current approach that traps an ERR signal
and shuts down the instance, this is extensible to more sophisticated
examination of whether the GitHub runner is actually functioning. This
puts the recreation of the instance in the hand of the instance group,
which makes it more visible and doesn't work at cross-purposes with the
infrastructure we're using.
Tested: Deployed to test environment (recreated with health check via
script) and confirmed expected behavior.
> Add simple Python webserver for GitHub runner health check

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.h
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_bufferize_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
- tests/transform_dialect/cpu/matmul_codegen_default_spec.mlir
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
- tests/transform_dialect/cuda/eltwise_reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/eltwise_reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_eltwise.mlir
- tests/transform_dialect/cuda/reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v2_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v2_uneven.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_partial_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_v2_codegen_spec.mlir
- tests/transform_dialect/cuda/vecadd2d_codegen_spec.mlir
Extract reassociative reshape patterns and empty tensor elimination from `iree.bufferize`. Add `fold_reassociative_reshapes` and `erase_unnecessary_tensor_operands` to `apply_patterns`.
Splitting the bufferization op allows for other canonicalizations to kick in in-between.
> Split iree.bufferize_op and cherry-pick linalg patterns

- compiler/src/iree/compiler/Codegen/Common/test/tile_and_distribute_to_workgroups.mlir
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
This is similar to what is done in PackOp::getTiledImplementation.
Thanks @hanhanW for suggesting the fix.
> Fix `UnPackOp::getTiledImplementation` missing innerTile operands

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Utils/Utils.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Utils/Utils.cpp
Callers of `PackOp::getResultShape` often pass the result to `dispatchIndexOpFoldResults`, making it matter which `OpFoldResult` contain a `Value`.
But the implementation of `PackOp::getResultShape` calls `makeComposedFoldedAffineApply`, which folds arith.constant values.
This resulted in compilation errors in test cases with dynamic tile sizes with `arith.constant` size values.
>  Make `PackOp::{getResultShape,getPackedType}` agree on dynamic dims.

- .github/workflows/ci.yml
As https://github.com/iree-org/iree/pull/11511#discussion_r1046542347, right now we only upload the IREE imported MLIR files. But when the source model is in MLIR format, `e2e_test_artifacts` doesn't import the model but directly uses the `model_*.mlir` file. This change also uploads those source models in MLIR format.
It's useful to upload all imported MLIRs and source models in MLIR format since those files are helpful for debugging and local run. Having all MLIR files uploaded makes it easier to download all of them from one place and keeps the version consistent.
We don't have the source model in MLIR currently, so this change has no effect right now.
> Upload all MLIR files in e2e test artifacts

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.h
- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
- tests/transform_dialect/cuda/reduction_v2.mlir
Emit the reduction schedule splitting the reduction directly to "scf.for" rather than to a generic over inputs with expanded shape. This allows us to ensure the generation of vector loads and stores, and to target the vector size appropriate to the input. Also plug in the matcher into the schedule instead of the fragile reliance on the order of operations.
> Emit better reduction schedule from JIT

- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Utils/Utils.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.h
- compiler/src/iree/compiler/Dialect/HAL/Target/VMVX/VMVXTarget.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Utils/Utils.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Utils/Utils.cpp
We need that information in `MaterializeEncodingPass`, as we need to switch to dynamic tile sizes in that case.
> Make "having microkernels" a target attribute.

- compiler/src/iree/compiler/Codegen/Common/FlattenMemRefSubspanPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/ConvertToSPIRVPass.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndPromote.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorToGPUSubgroupMMAOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/pipeline_matmul_cooperative_ops.mlir
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_and_promote_cooperative_matrix.mlir
This commit changes the logic to avoid performing C matrix promotion if the fused elementwise ops are directly allowed in cooeprative matrix spec. This saves us workgroup memory and copies with it.
> [spirv] Improve cooperative matrix elementwise op fusion

- tests/e2e/tosa_ops/BUILD
- tests/e2e/tosa_ops/CMakeLists.txt
- tests/e2e/xla_ops/BUILD
- tests/e2e/xla_ops/CMakeLists.txt
Context:
* https://github.com/iree-org/iree/pull/6846
> Lowering of std.bitcast to spirv is not yet done, but that's further down the pipeline.
* https://github.com/iree-org/iree/issues/11081
> Enable a few tests that are passing now.

- compiler/src/iree/compiler/Dialect/VM/IR/VMDialect.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMOps.td
- compiler/src/iree/compiler/Modules/Check/IR/CheckOps.td
- compiler/src/iree/compiler/Modules/Check/test/ops.mlir
- runtime/src/iree/hal/command_buffer_validation.c
- runtime/src/iree/modules/check/module.cc
- tests/e2e/xla_ops/batch_norm_inference.mlir
- tests/e2e/xla_ops/select.mlir
These all predate our open source release and point at an internal bug tracker. I checked each to see if the corresponding bugs had extra context, and most of these are obsolete, as MLIR and IREE have both evolved significantly since that code was written.
> Update some very old TODOs.

- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
- tests/transform_dialect/cuda/reduction_v3.mlir
- tests/transform_dialect/cuda/reduction_v3_codegen_spec.mlir
This is a rebase of #11497 on main post-LLVM-integrate changes.
> Add a reduction-v3 strategy for dynamic cases.

- build_tools/github_actions/runner/config/setup.sh
This is no longer necessary with health checks added in
https://github.com/iree-org/iree/pull/11526 which has now been rolled
out to all instance groups.
> Remove shutdown error trap from runner setup

- compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/StandardToVM/test/conversion_ops.mlir
The consumption of si of small width is already handled successfully by
consumers of this op (at least in limited trial). This was not true for the ui version ---although I suspect consumer op there, but keeping it more restricted until
checked.
> [vmvx] Relax requirement on fptosi lowering

- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Utils/Utils.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/ConvertConv2DToWinograd.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/TileAndDecomposeWinogradPass.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/conv2d_to_winograd.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tile_and_decompose_winograd.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
- tests/e2e/linalg_ext_ops/winograd_input.mlir
- tests/e2e/linalg_ext_ops/winograd_output.mlir
This patch adds support for NCHW convolutions.
In order to avoid the cost of additional transposes, the winograd input op is modified so that regardless of whether the input is (N, H, W, C) or (N, C, H, W), the output is always (T, T, N, H, W, C). Similarly, the winograd output op is modified to have the input always be (T, T, N, H, W, C), but have the output be either (N, H, W, C) or (N, C, H, W) depending on the specified image dimensions. The tiling and decomposition passes are also modified to account for this.
> Add Winograd support for NCHW convolutions

- compiler/src/iree/compiler/Dialect/Vulkan/IR/VulkanAttributes.cpp
- compiler/src/iree/compiler/Dialect/Vulkan/IR/VulkanBase.td
- compiler/src/iree/compiler/Dialect/Vulkan/IR/test/target_env.mlir
Extensions are now proper attributes; not IntegerAttr anymore. Also corrected the test for cooperative matrix attribute syntax.
Fixes https://github.com/iree-org/iree/issues/11532
> [vulkan] Fix target environment attribute parsing/printing

- build_tools/benchmarks/common/benchmark_config.py
- build_tools/benchmarks/common/benchmark_config_test.py
- build_tools/benchmarks/common/common_arguments.py
- build_tools/benchmarks/common/common_arguments_test.py
- build_tools/benchmarks/run_benchmarks_on_android.py
- build_tools/benchmarks/run_benchmarks_on_linux.py
The e2e test artifacts directory is self-contained for benchmark artifacts. Benchmark tools should no longer need the whole build directory.
Thie change adds a new option `--e2e_test_artifacts_dir` to specify the e2e test artifacts directory. This option will eventually replace the current positional argument `<build-dir>`.
> Support using e2e test artifacts directory path in benchmark tool

- tests/transform_dialect/cuda/reduction_v3.mlir
- tests/transform_dialect/cuda/reduction_v3_codegen_spec.mlir
The required changes in llvm-project have been cherry-picked in #11550.
> Enable rank_reducing patterns in reduction_v3_codegen_spec

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/BUILD
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.h
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_bufferize.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_bufferize_spec.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_codegen_foreach_to_gpu_spec.mlir
- tests/transform_dialect/cpu/matmul_codegen_default_spec.mlir
- tests/transform_dialect/cuda/BUILD
- tests/transform_dialect/cuda/CMakeLists.txt
- tests/transform_dialect/cuda/eltwise_reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/eltwise_reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction.mlir
- tests/transform_dialect/cuda/reduction_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_eltwise.mlir
- tests/transform_dialect/cuda/reduction_eltwise_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v2_codegen_spec.mlir
- tests/transform_dialect/cuda/reduction_v2_uneven.mlir
- tests/transform_dialect/cuda/reduction_v3_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_partial_codegen_spec.mlir
- tests/transform_dialect/cuda/softmax_v2_codegen_spec.mlir
- tests/transform_dialect/cuda/vecadd2d_codegen_spec.mlir
This is to avoid copies inside in case split-k does not divide the input size evenly (`reduction_v2_uneven.mlir`).
Also add additional patterns to ApplyPatternsOp and run them before bufferization in `reduction_v2_uneven.mlir`.
This change includes #11495, which was dropped at some point.
> Split iree.bufferize_op to enable additional canonicalization

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.h
- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
- tests/transform_dialect/cuda/reduction_v2.mlir
- tests/transform_dialect/cuda/reduction_v3.mlir
- tests/transform_dialect/cuda/reduction_v3_codegen_spec.mlir
Using `TileReductionUsingForeachThreadOp` in `createReductionStrategyThreadDistribution` allows a
much more general mapping of reductions on GPU.
This PR additionally performs a few refactorings to generalize the control of the transformation
to gracefully degrade from vector<4> to vector<2> to scalar.
> Port reduction-v3 to C++

- CMakeLists.txt
- compiler/src/iree/compiler/Dialect/HAL/Conversion/StreamToHAL/Patterns.cpp
- runtime/src/iree/hal/drivers/cuda/CMakeLists.txt
- runtime/src/iree/hal/drivers/cuda/cuda_allocator.c
- runtime/src/iree/hal/drivers/cuda/cuda_device.c
- runtime/src/iree/hal/drivers/cuda/cuda_driver.c
- runtime/src/iree/hal/drivers/cuda/cuda_headers.h
- runtime/src/iree/hal/drivers/cuda/dynamic_symbol_tables.h
- runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c
- runtime/src/iree/hal/drivers/cuda/dynamic_symbols.h
- runtime/src/iree/hal/drivers/cuda/dynamic_symbols_test.cc
- runtime/src/iree/hal/drivers/cuda/dynamic_symbols_test_for_nccl.cc
- runtime/src/iree/hal/drivers/cuda/nccl_channel.c
- runtime/src/iree/hal/drivers/cuda/nccl_channel.h
- runtime/src/iree/hal/drivers/cuda/registration/driver_module.c
- runtime/src/iree/hal/drivers/cuda/status_util.c
- runtime/src/iree/hal/drivers/cuda/status_util.h
- runtime/src/iree/modules/hal/module.c
This integration enables basic NCCL features in the CUDA runtime. This enables a minimum test to run. Many more things should be done on top of this.
To enable a build with NCCL, use `-DIREE_HAL_DRIVER_CUDA_NCCL=ON` for your cmake command. The same string is used for the macro to guard the C source code.
The public NCCL source is modified to specify the `NCCL_COMM_ID` using an environmental variable, and this PR does not cover that part.
Two environmental variables are introduced to set the number of processes and process ID.
1. `IREE_SPMD_NPROCS`
2. `IREE_SPMD_PROCID`
The GPU ID can be set using `--device=cuda://<index>` or `--device=cuda://GPU-<uuid>` for `iree-run-module`.
The NCCL dynamic library is loaded when users set `IREE_SPMD_NPROCS` to >= 1.
There are many things to be done …
> Integrate NCCL

- compiler/src/iree/compiler/InputConversion/Common/BUILD
- compiler/src/iree/compiler/InputConversion/Common/CMakeLists.txt
- compiler/src/iree/compiler/InputConversion/Common/ImportMLProgram.cpp
- compiler/src/iree/compiler/InputConversion/Common/test/import_ml_program.mlir
As part of importing ml_program, generate accessors for public global
variables. This just handles the simple case get and (if mutable) set
methods that take or return the full value. The naming convention is
configurable to avoid implicit linkage until/if convention is fixed.
If accessors are not specified, then the generation is skipped.
> Generate accessors for public global variables

- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- tests/transform_dialect/cuda/reduction_v3.mlir
MLIR does not model parallel contexts yet and hoisting buffer transfers may or may not be safe, depending on which semantics we decide on in the future. Disable it for now to be safe. Transfers should be hoisted on tensors when possible.
> CanonicalizedSequenceOp: Do not hoist buffer transfers

- build_tools/benchmarks/export_benchmark_config.py
NFC: To support benchmarking with some benchmark presets, we need to define the presets at somewhere. So there are two places:
1. Defines the presets in workflow/bash script and call export tool with some proper filters to select the benchmarks.
2. Defines the presets in the export tool.
This change chooses 2. since in order to implement 1., the export tool needs to provide a flexible way to filter benchmarks since the definitions of preset is kinda ad-hoc, there are many fields in benchmark configs can be filtered (see the definitions in code). To me adding those fields as separated filter arguments looks a little messy. Maybe we need a query language to properly do that.
And even if the export tool supports the filters, we still need an extra bash script to define and translate those …
> Add benchmark preset to benchmark config export tool

- benchmarks/TFLite/android-arm64-v8a.cmake
- build_tools/python/benchmark_suites/iree/armv8_a_benchmarks.py
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_aarch64_launch_configuration.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_vmvx_launch_configuration.mlir
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
Fixes https://github.com/iree-org/iree/issues/11434 and switch MobileBertInt8 benchmark to use data-tiling approach
> Limit tiling sizes for unpack op kernels

- compiler/src/iree/compiler/Codegen/Common/MaterializeEncodingPass.cpp
- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/materialize_encoding.mlir
- compiler/src/iree/compiler/Codegen/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Utils/Utils.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/Passes.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Utils/Utils.cpp
This is for now just creating constant value 1 instead of actually creating a vmvx.get_tile_sizes op.  (This makes the lit test look a bit odd as that gets folded, but that will change very soon).
That's enough to migrate the vmvx+ukernel e2e matmul tests to --iree-flow-enable-data-tiling, done in the next PR.
A follow-up PR will then be able to implement actual vmvx.get_tile_sizes providing more interesting Values than just arith.constant's.
> Implement dynamic tile size selection for VMVX+ukernels.

- experimental/rocm/rocm_allocator.c
- runtime/src/iree/hal/allocator_heap.c
- runtime/src/iree/hal/drivers/cuda/cuda_allocator.c
- runtime/src/iree/hal/drivers/vulkan/vma_allocator.cc
Buffers should have compatibility IREE_HAL_BUFFER_COMPATIBILITY_QUEUE_TRANSFER if their usage is either
IREE_HAL_BUFFER_USAGE_TRANSFER_SOURCE or
IREE_HAL_BUFFER_USAGE_TRANSFER_TARGET.
Buffers should have compatibility IREE_HAL_BUFFER_COMPATIBILITY_QUEUE_DISPATCH if their usage is either
IREE_HAL_BUFFER_USAGE_DISPATCH_STORAGE_READ or
IREE_HAL_BUFFER_USAGE_DISPATCH_STORAGE_WRITE.
(fixes #11463; authored by @sogartar)
> Fix implementations of allocators' query_compatibility

- compiler/src/iree/compiler/Codegen/Common/test/materialize_encoding.mlir
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
Dynamic inner tile sizes currently trigger infinite application of tile-and-distribute on the unpack op, each time calling `getTiledImplementation` -> `getSlice` creating more and more `extract_slice`. As a temporary work-around, we annotate unpack ops with a custom already_tiled attribute to keep track of what's already been tiled.
For some reason this causes errors in non-dynamic-shape cases, but it's not needed there anyway, so we simply check for dynamic inner tiles before applying this tweak.
> Work around infinite application of tile-and-distribute on `linalg_ext.unpack` with dynamic tile sizes

- compiler/src/iree/compiler/API2/Internal/IREEOptToolEntryPoint.cpp
- compiler/src/iree/compiler/API2/Internal/LLDToolEntryPoint.cpp
- compiler/src/iree/compiler/Tools/iree_compile_lib.cc
- integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-import-tflite-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-import-xla-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-opt-tflite-main.cpp
- integrations/tensorflow/iree_tf_compiler/iree-tf-opt-main.cpp
- tools/iree-opt-main.cc
- tools/iree-run-mlir-main.cc
Avoids recommending filing bugs with LLVM project for IREE project tooling.
> Set error message for where to report bugs

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp
- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Transforms/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
To avoid performance bugs, we have been checking that the matcher captured all operations in a function / dispatch region via an ad-hoc mechanism. Move that into a matcher predicate and make it more robust to duplicate captures.
> Add a matcher predicate checking for completeness

- .gitignore
- build_tools/github_actions/runner/config/health_server/health_server.py
- build_tools/github_actions/runner/instance_deleter/main.py
- build_tools/github_actions/runner/instance_deleter/main_test.py
- build_tools/github_actions/runner/instance_deleter/requirements.txt
- build_tools/pytype/check_diff.sh
A Cloud Functions proxy enabling GCE VMs in a Managed Instance Group to
delete themselves. GCE Managed instance groups don't have any good way
to handle autoscaling for long-running workloads. With the autoscaler
configured to scale in, instances get only 90 seconds warning to shut
down. So we set the autoscaler to only scale out and have the VMs tear
themselves down when they're down with their work. This is the approach
suggested by the managed instance group team:
https://drive.google.com/file/d/1XlwxF_0T7pUnbzhL5ePDoW-Q3GAaLO11. But
anything that brings down the VM other than a delete call to the
instance group manager API makes the VM get considered "unhealthy",
which means it gets recreated in exactly the same configuration,
regardless of any update or autoscaling settings. Making …
> Cloud Run Function for instance self-deletion

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/materialize_encoding.mlir
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/MaterializeEncoding.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/materialize_encoding.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
During `TileAndDistributeToWorkgroups`, in the case of dynamic tile sizes, the `LowerDispatchWorkgroupCountFromSetEncodingOp` pattern needs to call `materializeEncodingValueFn`, passing it a tensor type, expecting that tensor type to have a `TensorEncodingAttr`. The problem is that `MaterializeEncodingPass` has already run, rewriting the `SetEncoding` op and its result tensor, which used to hold the `TensorEncodingAttr`, into a `PackOp` op, whose new result tensor does not anymore have a `TensorEncodingAttr`.
As a work-around for that, we make `MaterializeEncoding` preserve the `TensorEncodingAttr` as an attribute on the `PackOp` itself, so `TileAndDistributeToWorkgroups` can read it and reconstruct a `tensorTypeWithEncoding`, so `LowerDispatchWorkgroupCountFromSetEncodingOp` can call …
> Preserve `encoding` attr on `PackOp` for `TileAndDistributeToWorkgroups`

- runtime/src/iree/hal/drivers/cuda/cuda_allocator.c
- runtime/src/iree/hal/drivers/vulkan/vma_buffer.cc
The memory map/range is invalid because we are only tracking VkBuffer handles but the reporting and plots are all correct.
Adds a new plot to the main tracy display under the default heap memory plot:
Adds escaping allocations to zone hierarchies (here showing an escaping 16b buffer):
Adds memory view - note to use this you need to turn on the memory range limit and drag the end to where you want to see the state of things (here the end is in the middle of execution and shows us buffers live during execution):
> Adding tracy memory pool visualization for Vulkan VMA buffers.

- CMakeLists.txt
- build_tools/benchmarks/common/benchmark_suite_test.py
- build_tools/python/benchmark_suites/iree/benchmark_collections.py
- build_tools/python/e2e_test_artifacts/cmake_generator/iree_rule_generator.py
- build_tools/python/e2e_test_artifacts/cmake_generator/iree_rule_generator_test.py
- build_tools/python/e2e_test_framework/definitions/common_definitions.py
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
Generates the modules for compilation statistics from all benchmark modules.
A new cmake target `iree-e2e-compile-stats-suites` is added to only build all compilation statistics, and `iree-benchmark-suites` only builds modules for benchmark runs.
> Generate compile statistics modules in e2e test artifacts

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.h
- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesCPU.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
- tests/transform_dialect/cuda/benchmark_linalg_reductions.stub.mlir
This revision introduces a 3 stage stategy for mapping reductions
along with a simple heuristic that finds the right tile sizes and vector sizes as a function
of the reduction size, the max number of threads and the warp shuffle size.
This provides a first set of tunable knobs for this strategy that can evolve into something more general in the future.
A simple benchmarking stub file is added that can be used with `sed`-based commands.
It is currently unclear where the control for such benchmarking should live and what relevant sizes should be.
Example of usage using the current IREE pipeline:
```
cat tests/transform_dialect/cuda/benchmark_linalg_reductions.stub.mlir | \
sed "s/\${SZ1}/1024/g" | \
sed "s/\${SZ2}/1024/g" | \
iree-compile - --iree-hal-target-backends=cuda …
```
> Fix performance bugs and add a benchmarking stub

- build_tools/github_actions/runner/config/delete_self.sh
- build_tools/github_actions/runner/config/deregister.sh
- build_tools/github_actions/runner/config/functions.sh
- build_tools/github_actions/runner/config/github-actions-runner-start.service
- build_tools/github_actions/runner/config/register.sh
- build_tools/github_actions/runner/config/setup.sh
- build_tools/github_actions/runner/gcp/create_templates.sh
As described in https://github.com/iree-org/iree/commit/d985a1b8fa,
managed instance group autoscaling does not behave well when instances
shut themselves down. Instead, we've introduced a proxy service that
allows them to delete themselves through the API without giving them
broad permissions.
Tested: Deployed to test cluster and verified instance behavior with
https://github.com/iree-org/iree/actions/runs/3743529186/jobs/6358175336
> Make runners call into deletion proxy rather than shutting down

- benchmarks/README.md
- build_tools/benchmarks/README.md
- build_tools/benchmarks/collect_compilation_statistics.py
- build_tools/benchmarks/collect_compilation_statistics_test.py
- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/benchmarks/common/benchmark_suite_test.py
- build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml
- build_tools/buildkite/cmake/linux/pipeline.yml
- build_tools/buildkite/cmake/linux/x86_64/benchmark.yml
- build_tools/python/e2e_test_artifacts/cmake_generator/iree_rule_generator.py
- build_tools/python/e2e_test_framework/definitions/common_definitions.py
Adds the `--generation_config` to `collect_compilation_statistics.py` and supports collecting from e2e test artifacts. Two extra options `--build_log` and `--e2e_test_artifacts` are added to support using without a build directory.
I try to use the subparser to separate the legacy usage and the new usage. With that the logic and usage look simpler to me:
Legacy option:
```sh
build_tools/benchmarks/collect_compilation_statistics.py \
--output=compile-stats.json \
legacy \
./iree_build_dir
```
New option:
```sh
build_tools/benchmarks/collect_compilation_statistics.py \
--output=./compile-stats.json \
alpha \
--generation_config=./generation_config.json \
--build_log=./iree_build_dir/.ninja_log \
--e2e_test_artifacts_dir=./iree_build_dir/e2e_test_artifacts 
```
> Support e2e test artifacts in compilation stats collection tool

- .github/workflows/benchmarks.yml
- build_tools/benchmarks/CMakeLists.txt
- build_tools/benchmarks/export_benchmark_config.py
- build_tools/benchmarks/export_benchmark_config_test.py
Adds a new command `compile-stats` to export module generation configs which are defined for compilation statistics. The exported JSON is designed to be used with `build_tools/benchmarks/collect_compilation_statistics.py`
benchmarks: cuda
> Support exporting configs for compilation statistics

- CMakeLists.txt
- compiler/src/iree/compiler/Tools/BUILD
- compiler/src/iree/compiler/Tools/CMakeLists.txt
- compiler/src/iree/compiler/Tools/init_iree.cc
- compiler/src/iree/compiler/Tools/init_iree.h
- compiler/src/iree/compiler/Tools/iree_compile_lib.cc
- compiler/src/iree/compiler/Tools/version.cc
- compiler/src/iree/compiler/Tools/version.h
Create helper to set debug message and version info. Version is not
embedded by default. Follow up will add option to easily create from
GitHub rev.
Fixes #11574
> Add version method and init helper

- compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilOps.td
- integrations/tensorflow/WORKSPACE
* Reset third_party/llvm-project: 2916b99182752b1aece8cc4479d8d6a20b5e02da (2022-12-20 01:01:46 +0100): [ADT] Alias llvm::Optional to std::optional
* Cherry-pick some MLIR commits
* llvm/llvm-project@41e731f2a4328f37b5d4e14d912814493e206f32
* llvm/llvm-project@d0766c0861c6f9ab4ec286a695ae8e161f418b2f
* llvm/llvm-project@6b76c4eafde8cc72133c752c05fa479c33221e61
* llvm/llvm-project@1a0453eb44cdf82df292d2da93092f0fa64043b9
* Updated to tensorflow/tensorflow@02e19522148c27b982d9f5cb1b7660dd3b7dd970
* Updated to tensorflow/mlir-hlo@c71041af3fa77f39c959cb31642161f56b4152de
* Deleted ambiguous IREE::Util::GlobalOp builder
> Integrate llvm/llvm-project@2916b9918275

- compiler/src/iree/compiler/Codegen/Common/TransformDialectInterpreterPass.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
Introduce an additional targeting mechanism to the transform dialect interpreter pass. 
The purpose of this addition is to greatly improve debugging velocity by navigating more smoothly between:
1. C++ builders that produce transform IR
2. Transform IR textual manipulation and local application with the interpreter.
3. Re-injection of manually altered transform IR in the system to run end-to-end and prove/disprove a hypothesis.
Note that steps 2 and 3 above create an interpreted sandbox in which one can very efficiently modify strategies and produce IR at any point without either recompiling the compiler or sifting through walls of text from `print-ir-after-all`.
This mechanism makes the pass walk the operation it is running on to find another operation, marked with the …
> [Transform][Debug] Extra transform interpreter targeting with attributes

- CMakeLists.txt
- build_tools/bazel/iree.bazelrc
- build_tools/bazel/workspace.bzl
- build_tools/bazel_to_cmake/bazel_to_cmake_targets.py
- build_tools/third_party/tracy/README.md
- build_tools/third_party/tracy_client/BUILD.overlay
- build_tools/third_party/tracy_client/CMakeLists.txt
- runtime/src/iree/base/BUILD
- runtime/src/iree/base/CMakeLists.txt
- runtime/src/iree/base/tracing.cc
- runtime/src/iree/base/tracing.h
- runtime/src/iree/hal/drivers/vulkan/BUILD
- runtime/src/iree/hal/drivers/vulkan/CMakeLists.txt
- runtime/src/iree/hal/drivers/vulkan/tracing.cc
* Can be enabled with one of:
* The long-hand flag: --@tracy_client//:runtime_enable=true
* Short-hand: --iree_enable_runtime_tracing (matches CMake option naming)
I don't love how the Tracy headers are laid out and how Bazel forces us into relativising them. I don't see an easy way to get around this, though (without recreating the sub-module with an additional layer of nesting).
Note for Google integrators: No-op'ing this for internal builds should just require removing the "@tracy_client//:runtime_impl" dep from `runtime/src/iree/base:tracing` (or importing Tracy and redirecting that appropriately).
> Support runtime tracing with Tracy in bazel builds.

- build_tools/bazel/workspace.bzl
- build_tools/embed_data/build_defs.bzl
- build_tools/third_party/cuda/BUILD.template
Somehow the way Label is evaluated differs if your Bazel macro is in
the main repository, in which case it gets evaluated relative to the
BUILD file's repository vs if the macro is being used as part of an
external repository, in which case it is evaluated relative to the
macro's repository (which is the documented behavior).
Hardcoding the repo alias would break anyone using this function from
an external repository who doesn't call the IREE repo "iree_core".
Removing `clean_dep` would break anyone using `iree_c_embed_data` from
an external repository. The latter isn't really supported, but it
doesn't make things any harder in the end.
> Make Bazel Cuda work for dependencies on IREE

- integrations/tensorflow/python_projects/iree_tf/iree/tf/support/tf_test_utils_test.py
- integrations/tensorflow/python_projects/iree_tf/iree/tf/support/tf_utils.py
- integrations/tensorflow/test/python/iree_tf_tests/math/math_test.py
- runtime/bindings/python/iree/runtime/system_api.py
This change replaces references to a number of deprecated NumPy type
aliases (np.bool, np.int, np.float, np.complex, np.object, np.str) with
their recommended replacement (bool, int, float, complex, object, str).
NumPy 1.24 drops the deprecated aliases, so we must remove uses to
support that version.
Also includes fixing or silencing some pre-existing pytype errors which
presumably came from someone ignoring the lint check.
> [NumPy] Remove references to deprecated NumPy type aliases.

- build_tools/github_actions/runner/config/setup.sh
- build_tools/github_actions/runner/gcp/create_templates.sh
While there is plenty of RAM on the CPU runners, the GPU runners are
pretty limited. We unfortunately would need to mount a silly number of
disks for CPU instances, so we stick with a ramdisk there.
Fixes https://github.com/iree-org/iree/issues/10739
Tested: deployed to test runners and ran on test PR:
https://github.com/iree-org/iree/actions/runs/3791229247
> Use local SSDs instead of ramdisks on GPU runners

- .github/workflows/ci.yml
This turns out to be a million times easier than sending emails. I don't
love it, but it's a whole lot better than the current situation.
The result currently looks like this (the bot avatar and name as well as
the channel it posts to can be configured on the Discord side):
Another option would be creating an issue on each failure. I like that
a lot better for tracking purposes, but I don't think it has the same
visibility and there's still no way to create rotations on GitHub, so
we couldn't auto-assign the issue easily. It would also be quite noisy.
We could always post to the same issue, but then the issue isn't that
useful for tracking.
My intent is to start this out in the #github channel and then graduate
it to the #builds channel if everything seems to be working. For now I
also …
> Post to Discord when CI fails

- build_tools/python/e2e_test_artifacts/cmake_generator/iree_rule_generator.py
- build_tools/python/e2e_test_artifacts/cmake_generator/model_rule_generator.py
- build_tools/python/e2e_test_artifacts/iree_artifacts.py
- build_tools/python/e2e_test_framework/serialization.py
- build_tools/python/e2e_test_framework/serialization_test.py
Originally I used `OrderedDict` to clearly indicate that the order is preserved. But now it seems to be redundant and a little annoying to me.
The `dict` is ordered since Python 3.7 (https://mail.python.org/pipermail/python-dev/2017-December/151283.html, https://docs.python.org/3/library/stdtypes.html#mapping-types-dict), which is our lowest supported python version.
> Replace OrderedDict with dict

- .github/workflows/benchmark_execution.yml
- .github/workflows/ci.yml
- build_tools/benchmarks/export_benchmark_config.py
Add CI job to collect compilation statistics from e2e test artifacts.
The compilation statistics job isn't in the sub-workflow `benchmarks.yaml` because that workflow depends on the unnecessary 4mins job `build_benchmark_tools`. And if there's no execution benchmark, `build_benchmark_tools` can be skipped.
So I decided to rename `benchmarks.yaml` to `benchmark_execution.yaml` and let the compilation statistics job stay in the main CI workflow for better workflow run time. The compilation statistics job also runs very fast (26s) so we run it unconditionally and can always post the results in comments. 
Fix #11071
benchmarks: cuda
> Add CI job to collect compilation statistics

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategies.h
- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
This revision adds a new strategy for the small reduction domain.
For small reductions, we rely on L1 cache locality and do not try to parallelize individual reductions: every thread performs the full reduction locally.
This is empirically determined profitable up until a reduction size of 64.
This can be fine-tuned later when we have better support for filtering and profitability considerations.
Running the iree-samples/transform_dialect script:
```
(  benchmark-transform-create -r  ../iree-samples/transform_dialect/benchmark_linalg_reductions.stub.mlir   reduction_2d_static 1234567 15 )
```
before:
```
With transform dialect: reduction_2d_static --function_input="1234567x15xf32" P50: 1278300.0000 ns 14.48682234217319877962 GElements/s
Without transform dialect: reduction_2d_static …
```
> Add a second CUDA transform reduction strategy for small reduction sizes

- CMakeLists.txt
Results in phony rules generated for both tools and Python to refer to those in tools/ in short form. That is, iree-compile phony target now refers to tools/iree-compile rather than the one inside _mlir_libs:
```sh
$ rg -e "build iree-dump-module" -e "build iree-lld" -e "build iree-compile"  build.ninja
211387:build iree-compile: phony tools/iree-compile
211391:build iree-dump-module: phony tools/iree-dump-module
211397:build iree-lld: phony compiler/bindings/python/iree/compiler/_mlir_libs/iree-lld
```
Fixes #9329.
> [cmake] Move inclusion of tools directory up

- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
This makes it easier to understand failures-to-match. It required splitting the implementation of some function templates into a public template and private non-template part with the latter emitting the debug output to avoid polluting the header with debug-related includes. Note that this starts approaching the point where turning matchers into operations in a dialect would be preferable.
> Add debug output to transform dialect matchers

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp
- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
Code under llvm-external-projects follows LLVM coding style and should
not have include directives in headers if they are only used
transitively.
> Transform cleanup

- compiler/src/iree/compiler/Codegen/Common/TransformDialectStrategiesGPU.cpp
- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/reductions.mlir
- compiler/src/iree/compiler/Codegen/Common/test/reductions_match_spec.mlir
- llvm-external-projects/iree-dialects/BUILD
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/StructuredTransformOpsExt.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
Add a mechanism for testing the result of transform dialect-related
matchers as follows. A new transform op emits remarks at the location of
payload ops associated with the given handle. This op is used to each
handle produced by `match_callback` to mark the matched payload ops.
Thus iree-opt-based tests can check the matcher directly with the
`-verify-diagnostics` flag.
> Transform match test

- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/eliminate_empty_tensors.mlir
- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
Operands of `flow.dispatch.tensor.store` need to be added to `neededValues` when doing empty tensor elimination; otherwise the insertion point of load op might not be correctly dominated by the operands.
This was found when compiling MiniLM model with `--iree-flow-enable-aggressive-fusion`, related issue #9348
> Check dependent values of StoreOp in EliminateEmptyTensorsPass

- build_tools/cmake/iree_cc_binary.cmake
- build_tools/embed_data/CMakeLists.txt
These are needed for cross compiling to iOS, which requires building app bundles.
Part of https://github.com/iree-org/iree/discussions/11716
> [cmake] Add BUNDLE DESTINATION for runtime binaries

- build_tools/cmake/iree_external_cmake_options.cmake
We are calling into libraries; we don't need these binaries. Building them causes issues for iOS cross compilation, as right now cpuinfo are missing BUNDLE DESTINATION for MACOSX_BUNDLE for `install(TARGETS ..)`.
Part of https://github.com/iree-org/iree/discussions/11716
> [cmake] Disable building cpuinfo binaries

- .github/workflows/ci.yml
`build_benchmark_tools` doesn't need to depend on `build_tf_integrations`.
> Remove build_tf_integrations dep from build_benchmark_tools

- build_tools/benchmarks/run_benchmarks.sh
- build_tools/github_actions/configure_ci.py
- build_tools/github_actions/runner/gcp/create_templates.sh
Adds templates and support for x86_64 benchmarks on c2-standard-16 machines.
`github-runner-testing-presubmit-cpu-c2-standard-16-us-west1` is too long for the name of an instance group, so I choose `github-runner-testing-presubmit-cpu-c2-std-16-us-west1`.
benchmarks: x86_64
runner-env: testing
> Adds MIG template for x86_64 benchmarking in Github CI

- compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/convert_to_nvvm.mlir
We pack all the allocations into 1 to be able to use dynamic shared memory, we need to respect the alignment of each allocation.
> [LLVMGPU] Fix shared memory allocation when packing

- build_tools/github_actions/runner/gcp/update_instance_groups.py
- build_tools/github_actions/runner/instance_deleter/main.py
This used 'proactive refresh' previously to get around the bug/feature
in MIGs that recreation of VMs because they are unhealthy doesn't apply
any pending updates. Now that we have our workaround to have the VMs get
deleted through the MIG API, updates actually will get applied.
Replacing the VM is necessary for several update operations (e.g. stuff
with disks and policies). Our most common changes are just metadata
changes so they can be applied with refresh, but they actually don't take
effect until the VM restarts, so it's misleading to show the update as
having been applied.
Also fixed some comments and help text in this and the instance_deleter.
> Default instance group updates to 'opportunistic replace'

- compiler/src/iree/compiler/Dialect/Flow/Transforms/FormDispatchRegions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/fusion_of_tensor_ops.mlir
Currently under aggressive fusion, elementwise parallel ops are fused with consumer that are reductions. When the parallel op has other uses the fused op also returns the reduced and non-reduced values. This results in operations that are reductions returning results that have shape similar to the entire iteration space of the op. Such ops are hard to handle in the backend.  This patch avoids creating such ops, but adapts the fusion heuristics to still pull these ops into the same dispatch.
> Modify aggressive fusion heuristics to not create ops where reduction ops also return intermediate results.

- docs/website/mkdocs.yml
We don't bump the copyright year for source code files, but this is useful to keep current and show that the project is under active development.
See also: https://github.com/iree-org/iree/commit/6f4112eb79c8b1a730da333200638ac09611f1f5 for 2022, and the discussion about that [here on Discord](https://discord.com/channels/689900678990135345/692052262494797835/1026729012095107082).
> Bump website copyright year to 2023.

- build_tools/cmake/iree_cc_binary.cmake
These properties are needed to generate `Info.plist` associated with macOS/iOS apps.
Fixes https://github.com/iree-org/iree/issues/11733
> [cmake] Set macOS/iOS app bundle properties

- compiler/src/iree/compiler/Codegen/Common/GPUDistributeSharedMemoryCopy.cpp
- compiler/src/iree/compiler/Codegen/Common/GPUVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/vector_masking.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTileAndVectorizeToCooperativeOps.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVVectorize.cpp
- compiler/src/iree/compiler/Codegen/Sandbox/LinalgTensorCodegenDriver.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/CodegenStrategy.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Transforms/Transforms.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
Enable vector masking for elementwise ops with dynamic shapes and no
reductions. More cases will be added incrementally.
> [CPU] Vector masking integration in IREE

- build_tools/cmake/iree_cc_library.cmake
This fixes the following error when configuring CMake with `-G Xcode`
```
CMake Error at build_tools/cmake/iree_cc_library.cmake:333 (file):
Error evaluating generator expression:
$<TARGET_OBJECTS:iree_runtime_impl.objects>
The evaluation of the TARGET_OBJECTS generator expression is only suitable
for consumption by CMake (limited under Xcode with multiple architectures).
It is not suitable for writing out elsewhere.
```
With it, now we can use the `Xcode` generator for CMake.
> [cmake] Disable debug print with generator expression for Xcode

- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp
See https://github.com/iree-org/iree/pull/11757#discussion_r1065040317. Maybe CI will be happier with this.
> Replace `1ll` with `int64_t()`.

- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/Common.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp
Note that `ll` is the suffix for int64_t, not `l`. When forward declaring the types must match (AbstractReductionStrategy was defined as struct but declared elsewhere as class).
> Fixing MSVC build breaks in transform dialect code from PR #11738.

- docs/website/docs/building-from-source/index.md
- docs/website/docs/deployment-configurations/cpu.md
Follow-up to https://github.com/iree-org/iree/pull/11758
Edits are to these pages:
* https://iree-org.github.io/iree/building-from-source/#reference-pages
* https://iree-org.github.io/iree/deployment-configurations/cpu/#build-compiler-from-source
> Add a few links to the new iOS documentation page.

- compiler/src/iree/compiler/Dialect/Util/Transforms/FuseGlobals.cpp
- compiler/src/iree/compiler/Dialect/Util/Transforms/test/fuse_globals.mlir
Previously the fusion pass was being conservative when there was divergence but that can cause issues with downstream IR that requires at least some level of global fusion.
Fixes #11652.
> Allow partial subsets of correlated globals to fuse.

- runtime/src/iree/base/allocator.h
- runtime/src/iree/base/internal/threading.h
- runtime/src/iree/base/internal/threading_pthreads.c
- runtime/src/iree/hal/drivers/local_task/registration/driver_module.c
- runtime/src/iree/task/api.c
- runtime/src/iree/task/api.h
- runtime/src/iree/task/executor_demo.cc
- runtime/src/iree/task/topology.h
- runtime/src/iree/task/topology_cpuinfo.c
- runtime/src/iree/task/topology_test.cc
- samples/simple_embedding/README.md
- samples/simple_embedding/device_embedded.c
This allows for multiple executors to be created from flags that can then be passed into the local-task creation routines. Topology queries are slightly extended to allow for specifying which node the physical cores are selected from when initializing with that mode but otherwise the programmatic control by users not using flags remains the same.
The new `--task_topology_nodes=` flag can be used to control which NUMA nodes get executors. By default (or if `current` is specified) the node is inherited from the calling thread but `all` can be specified to create one executor per NUMA node. In addition a comma-separated list of node IDs can be passed to subset the nodes (`0,1,4`). The inheritance is kind of sketchy as the node is queried at driver creation time (usually just during startup) …
> Reworking task API to provide iree_task_executors_create_from_flags.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/BUILD
- compiler/src/iree/compiler/Dialect/Flow/Transforms/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/Flow/Transforms/CollapseDimensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FormDispatchRegions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.td
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/collapse_linalg_generic_on_tensors.mlir
- tests/transform_dialect/cuda/vecadd2d.mlir
This is a follow-up PR. #11295 had already implemented the collapsing logic for `linalg.generic` operations in `dispatch.region`. This PR extracts that logic in a new Collapse Pass.
The new pass performs the following steps. The first and third steps here are new compared to the previous one as we are creating the Pass.
1. Finds `linalg.generic` that has no producer in `dispatch.region`, which means there will only be one `linalg.generic` in the region.
2. Collapse dimensions of the tensors in `linalg.generic` if possible
3. Generates new workload region for the collapsed Op and new `dispatch.region`
PR also removes collapse flag and changes a test that was using accordingly.
> Introduce Collapse Pass

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.cpp
Previously, the failed application of the internal pattern would return a definite failure without printing any message, stopping the pass without user-visible feedback.
> FuseProducersOp: emit a definite failure with a message

- CONTRIBUTING.md
* Adjusted language for "project members" / "collaborators" / "maintainers"
* Mention that squash merge messages now default to the PR description (we set that repository setting)
* Remove reference to "kokoro:run" label and link to GitHub docs for approving workflow runs
> Refresh CONTRIBUTING.md to reflect GitHub Actions CI.

- build_tools/cmake/ctest_all.sh
This test has been failing consistently on the recently re-enabled Windows CI. I can reproduce the segfault on my local Windows machine, but I haven't yet triaged/debugged it. Rather than disable the entire workflow/job, this just disables the one test that appears to have regressed, so we can continue to evaluate how stable the Windows CI is.
> Exclude failing test from Windows CI.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/CollapseDimensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FormDispatchRegions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/collapse_linalg_generic_on_tensors.mlir
Without these patterns, we end up with sequences like
```
%0 = tensor.empty ...
%1 = tensor.collapse_shape %0 ...
```
which dont get pulled into dispatch regions since
`tensor.collapse_shapes` arent pulled into dispatch regions. With the
patterns the `tensor.collapse_shape` fold away, avoiding
`tensor.empty()` being left outside.
Fixes #11770
> Add patterns to fold `tensor.empty` with `tensor.collapse_expand/shape`.

- build_tools/github_actions/runner/config/systemd/system/stop-idle-runner.timer
I suspect this is implicated in unhelpful GitHub actions server errors
that we saw when it was canaried. I didn't do a complete rollback of
https://github.com/iree-org/iree/pull/11688 because that does some
nice cleanup of systemd services and enables cloud logging for the VM
systemd, which helps a lot with debugging these sorts of issues. I have
not identified the precise cause of the issue, but my best guess is
that a race causes a runner to pick up a job and then get killed.
We need to do a rollout of the latest actions runner version in the
next couple days (https://github.com/iree-org/iree/issues/11554), so
need to push a version without this potential bug.
> Disable timer to stop idle runner

- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/Common.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/Common.h
Split reduction is subsumed by tiling reductions to foreach_thread which
is more general and can reduce temporary storage to arbitrarily small sizes.
For now we keep the SplitReduction matcher as it is used for more general testing
and the current test cannot be easily rewritten until the BubbleCollapseExpand maintains handles.
> Purge split reduction transformation from APIs

- compiler/src/iree/compiler/Dialect/HAL/Transforms/AssignTargetDevices.cpp
Avoids printing the module when invalid backend is specified and shouldPrintOpOnDiagnostic() is true.
> Don't emit op on error (NFC)

- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
This results in returning the triple that is appropriate for generating
code that can be loaded into current process rather than default target
LLVM was configured with at build time. The default configured at build
time corresponds to the host in most cases, so this is NOP in common
case.
Biggest difference (once related upstream change lands) is for cases
like universal binaries on Mac where the target at compile time of
compiler often differs from that of architecture at runtime on same
machine.
I considered excluding case where, say, IREE_DEFAULT_TARGET_TRIPLE is
set. But considered that in the cases folks are generating code for
architectures other than their own they are probably setting it
explicitly at iree-compile runtime and/or targeting multiple archs so
that the added …
> Switch to getProcessTriple when querying default target options

- .github/workflows/ci.yml
- build_tools/cmake/iree_copts.cmake
- experimental/web/testing/build_tests.sh
- runtime/src/iree/base/loop_emscripten.c
- runtime/src/iree/base/loop_emscripten.h
- runtime/src/iree/base/loop_emscripten.js
This is a roll forward of https://github.com/iree-org/iree/pull/11507
Successful CI run: https://github.com/iree-org/iree/actions/runs/3897710708/jobs/6655737094
---
I had been testing locally with [`experimental/web/testing/build_tests.sh`](https://github.com/iree-org/iree/blob/main/experimental/web/testing/build_tests.sh), which sets `-DCMAKE_BUILD_TYPE=RelWithDebInfo`. The CI uses [`build_tools/cmake/build_runtime_emscripten.sh`](https://github.com/iree-org/iree/blob/main/build_tools/cmake/build_runtime_emscripten.sh), which leaves the build type unset and defaults to `Release`. 
Release builds were failing with `SyntaxError: Unexpected token (1:72626)` in `/emsdk/upstream/emscripten/tools/acorn-optimizer.js:1852` with this code: 
While `for (const [key, value] of …
> Roll forward stateful loop_emscripten changes.

- experimental/rocm/rocm_device.c
- runtime/src/iree/hal/device.c
- runtime/src/iree/hal/device.h
- runtime/src/iree/hal/drivers/cuda/cuda_device.c
- runtime/src/iree/hal/drivers/local_sync/sync_device.c
- runtime/src/iree/hal/drivers/local_task/task_device.c
- runtime/src/iree/hal/drivers/vulkan/vulkan_device.cc
- runtime/src/iree/hal/utils/deferred_command_buffer.c
- runtime/src/iree/hal/utils/deferred_command_buffer.h
- runtime/src/iree/tooling/device_util.c
This allows for wrapping base device allocators in shims that can specialize allocation logic. It's a dangerous method but for drivers that have specific requirements on their base allocators such as internal dependencies on device handles (Vulkan/CUDA/etc) it's difficult to allow for pure allocator injection on device creation.
Users can now inject their own custom device allocators when managing devices themselves and as we add supported upstream ones we can use them in tools based on the new `--device_allocator=` flag.
> Adding iree_hal_device_replace_allocator API.

- build_tools/cmake/iree_import_binary.cmake
Fixes https://github.com/iree-org/iree/actions/runs/3904444915/jobs/6670814128
```
CMake Error at build_tools/cmake/iree_import_binary.cmake:54 (message):
Could not find 'iree-flatcc-cli.js' under
'/work/full-build-dir/install/bin'
(Expanded to '/work/full-build-dir/install/bin/iree-flatcc-cli.js').
```
> Define our own `_HOST_EXECUTABLE_SUFFIX` to fix Emscripten builds.

- compiler/src/iree/compiler/Codegen/Common/BUILD
- compiler/src/iree/compiler/Codegen/Common/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/TransformDialectInterpreterPass.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchWithTransformDialect.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.h
- compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/TransformInterpreterPassBase.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/TransformInterpreterUtils.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/TransformInterpreter.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Passes/TransformInterpreterPassBase.cpp
- llvm-external-projects/iree-dialects/test/Dialect/linalg_transform/failure.mlir
Factor out the common components of TransformDialectInterpreterPass in Codegen, in iree-dialects, and of DispatchWithTransformDialect into a base class template that lives in iree-dialects. This includes the logic necessary for injecting transforms from a file, maintaining those alive in a separate module, debug targeting via attributes, and transform module identification in the IR. It is currently used for IREE codegen, and will be reused for Flow and standalone interpreter.
> Commonolize implementation of transform interpreters

- compiler/src/iree/compiler/Dialect/Stream/IR/StreamOpFolders.cpp
- compiler/src/iree/compiler/Dialect/Stream/IR/test/timepoint_folding.mlir
We sort various await ops over the same timepoint according to their order in the same block, but the list was pulling in await ops in other blocks too. This caused crash.
In general, unifying ops across the blocks is triky given we need to consider dominance and referened values in each op. Prefer to be conservative for now.
> [stream] Don't group timepoint awaits in different blocks

- build_tools/github_actions/runner/gcp/create_templates.sh
The `-` in the MIG type name is ambiguous since it's used to split parts in the full name.
Rename `cpu-c2-16` to `c2s16` (the abbreviation of `cpu-c2-standard-16`).
> Rename CPU benchmark MIG

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Transforms.cpp
This PR fixes the lowering_config and calls to transform higher-dimensional pooling ops to single dimensional ones.
> Supporting pooling vectorization in IREE

- benchmarks/TFLite/android-arm64-v8a.cmake
- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
This is part 5/9 of #11755: Finish the transition to `--iree-flow-enable-data-tiling`.
This switches the last holdout e2e tests that were exercisting the old mmt4d pass, making it unused.
> Switch e2e/matmul tests on vmvx+ukernel to data-tiling

- build_tools/cmake/iree_copts.cmake
One step towards enabling [ccache](https://ccache.dev/) on our Windows CI, but there are a few details to still work through: https://github.com/iree-org/iree/issues/11009#issuecomment-1382597509.
On my machine, I see these results (sample size 1):
> clean build (no cache): 528 seconds
> ```
> λ ccache --show-stats
> Cacheable calls:   3942 / 3943 (99.97%)
>   Hits:               2 / 3942 ( 0.05%)
>     Direct:           0 /    2 ( 0.00%)
>     Preprocessed:     2 /    2 (100.0%)
>   Misses:          3940 / 3942 (99.95%)
> Uncacheable calls:    1 / 3943 ( 0.03%)
> Local storage:
>   Cache size (GB): 2.21 / 5.00 (44.21%)
>   Cleanups:          16
> ```
> clean build (with cache): 96 seconds
> ```
> λ ccache --show-stats
> Cacheable calls:   3942 / 3943 (99.97%)
>   Hits:            3939 / …
```
> Disable `/Zi` when using ccache on Windows/MSVC.

- compiler/src/iree/compiler/API2/Embed.h
- compiler/src/iree/compiler/API2/Internal/Embed.cpp
- compiler/src/iree/compiler/API2/Stub/Loader.cpp
- compiler/src/iree/compiler/API2/Stub/LoaderTest.c
What was there was not able to take a known-binary buffer that we do not know whether it is null terminated or not (nor do we care). This is a more explicit API which at least has the benefit or letting us represent known-null-terminated buffers or known-binary buffers without having LLVM try to probe one past what may be owned memory.
This is a breaking API change, but we are not yet stable so just making it vs versioning the entrypoint.
> Rework null-terminator handling in ireeCompilerSourceWrapBuffer.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/DetachElementwiseFromNamedOps.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/detach_elementwise_from_named_ops.mlir
This change replaces the `outs` operands of Linalg ops that are splat constants with `fill` of that value. Having constants operands for `outs` causes bufferization issues downstream (which are harder to fix, though in theory whether the outs is a constant or not it shouldnt matter. The general case fix looks very similar to what happens here anyway).
Fixes #11830
> Replace constant `outs` operands of Linalg ops as well.

- benchmarks/TFLite/android-arm64-v8a.cmake
According to https://github.com/iree-org/iree/pull/10458#issuecomment-1307621087, the padding fusion flags are missing for local-sync benchmark.
> Fix compile flags of ARM padding fusion experiments

- build_tools/third_party/tracy/CMakeLists.txt
- docs/developers/developing_iree/profiling_with_tracy.md
This tool provides information about the trace in machine-readable form. This tool loses a lot of context from the trace, so it is recommended to only use this tool in reference to a particular trace that has been already examined manually or otherwise controlled so that the extracted numbers are known to be meaningful.
> [tracy] Add support for `csvexport` tool.

- runtime/src/iree/hal/command_buffer_validation.c
- runtime/src/iree/hal/drivers/cuda/cuda_allocator.c
- runtime/src/iree/hal/drivers/cuda/cuda_buffer.c
- runtime/src/iree/hal/drivers/cuda/cuda_buffer.h
- runtime/src/iree/hal/drivers/cuda/dynamic_symbol_tables.h
Note that registering host memory is an expensive operation (likely synchronizes with the device just like alloc/free, can result in cache clears, etc).
Example:
```c
static float heap_buffer[1 * 224 * 224 * 3] = {5};
iree_hal_external_buffer_t external_buffer = {
.type = IREE_HAL_EXTERNAL_BUFFER_TYPE_HOST_ALLOCATION,
.flags = IREE_HAL_EXTERNAL_BUFFER_FLAG_NONE,
.size = sizeof(heap_buffer),
.handle.host_allocation.ptr = heap_buffer,
};
iree_hal_buffer_t* buffer = NULL;
IREE_CHECK_OK(iree_hal_allocator_import_buffer(
buffer_allocator, buffer_params, &external_buffer,
iree_hal_buffer_release_callback_null(), &buffer));
```
> Supporting host memory registration in CUDA via external buffers.

- compiler/src/iree/compiler/Codegen/SPIRV/Verifiers.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/illegal_configuration.mlir
Removes a check in the verifier that required at least two tiles per workgroup as the motivating case has since been fixed.
> [spirv] Allow single tile configurations for cooperative matrix

- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUMaterializeEncodingPass.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_encoding.mlir
- compiler/src/iree/compiler/Codegen/Utils/Utils.cpp
- compiler/src/iree/compiler/Codegen/Utils/Utils.h
Note - explicitly x86_64 not just x86, as 32-bit x86 has typically 2x fewer SIMD registers at equal SIMD feature (e.g. SSE) resulting in different kernel tile size choices -- so if and when we care about 32-bit x86, it'll have to be treated as a separate  architecture for this purpose.
Note: we also need #11850 to get the intended effect on benchmarks builds.
> Implement x86-64 tile size selection

- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/BUILD
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/CMakeLists.txt
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
There are 2 ways to pass sub-target features: by specifying a target CPU as in `--iree-llvm-target-cpu=cascadelake` (that's what our benchmarks do) or by specifying an explicit list of CPU features as in  `--iree-llvm-target-cpu-features=avx512vnni`.
The 2 are so far merged only when we go into the LLVM back-end here: https://github.com/iree-org/iree/blob/d91712bf4d32c44f6075620293e638418a47d78f/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRPasses.cpp#L36-L38
This means that any IREE compiler code trying to act on CPU features is so far sensitive to which way CPU features are passed. Current code is reading the list of individual CPU features, not the specified CPU, e.g.: https://github.com/iree-org/iree/blob/d91712bf4d32c44f6075620293e638418a47d78f/compiler/src/iree/compiler/Co …
> Populate CPU features from CPU (on X86)

- runtime/src/iree/base/string_view.h
This pleases Clang when cross compiling towards iOS (simulator).
Fixes https://github.com/iree-org/iree/issues/11865
Fixes https://github.com/iree-org/iree-samples/issues/93
Thanks to @wangkuiyi for discovering the issue and fix.
> Use nested initializer list for iree_string_pair_t

- .github/workflows/ci.yml
- build_tools/benchmarks/upload_benchmarks_to_dashboard.py
Add job to upload benchmark results to dashboard. Disabled for now until we migrate the database.
Tested with local dashboard instance
> Add job to upload benchmark results to dashboard

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_aarch64_launch_configuration.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_x86_64_launch_configuration.mlir
The default function aims to returns the number of workloads per workgroup, but it does not know that it is working on packed domain. We need to take inner tile sizes into account and adjust the distribution tile sizes. This avoids a huge amount of workloads per workgroup.
> [LLVMCPU] Add a fixup for selecting pack ops distribution tiling sizes.

- build_tools/python/benchmark_suites/iree/mali_benchmarks.py
- build_tools/python/benchmark_suites/iree/module_execution_configs.py
- build_tools/python/e2e_test_framework/device_specs/moto_edge_x30_specs.py
- build_tools/python/e2e_test_framework/device_specs/pixel_4_specs.py
- build_tools/python/e2e_test_framework/device_specs/pixel_6_pro_specs.py
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
Later I decided to only use `[a-z0-9-]` in the ID. Rename some ids to follow this rule before we actually start using them.
The follow-up task will have validator to check this #10556
> Fix ID format in benchmark framework

- docs/developers/developing_iree/profiling_with_tracy.md
Add a paragraph on what to do when hitting the file descriptors limit that `tracy` may run into while benchmarking on a machine with a lot of CPUs.
NFC
> [docs] Document the workaround for RESOURCE_EXHAUSTED

- build_tools/github_actions/runner/config/systemd/system/gh-runner-deregister.service
- build_tools/github_actions/runner/config/systemd/system/gh-runner.service
- build_tools/github_actions/runner/config/systemd/system/health-check.service
- build_tools/github_actions/runner/config/systemd/system/stop-idle-runner.service
- build_tools/github_actions/runner/gcp/create_image.sh
- build_tools/github_actions/runner/gcp/image_setup.sh
It turns out that systemd doesn't use /etc/environment because that's a
pam login thing (I think I have discovered this before). We use
/etc/environment to add things to the PATH for all users. This just
sets /etc/environment as the environment file for all our services.
Also fixed quoting of a sed command for the GPU image so that it does
variable expansion.
Tested: Created new images and templates and deployed them to the
testing cluster then ran presubmit against it:
https://github.com/iree-org/iree/actions/runs/3955202440/jobs/6792181962
> Fix GitHub Actions Runners for new image

- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/test/smoketest.mlir
We can use `-iree-hal-dump-executable-binaries-to=` instead, which is consistent across all compiler backends.
> [cuda] Remove `-iree-hal-cuda-dump-ptx`

- compiler/src/iree/compiler/Codegen/Dialect/LoweringConfig.td
- compiler/src/iree/compiler/Codegen/LLVMCPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUMmt4dVectorLowering.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/aarch64_dotprod_vector_lowering.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/aarch64_vector_lowering.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_aarch64_launch_configuration.mlir
- compiler/src/iree/compiler/Codegen/Passes.cpp
- compiler/src/iree/compiler/Codegen/Passes.h
- compiler/src/iree/compiler/Codegen/Passes.td
A number of things in LLVMCPU/ unnecessarily have references to AArch64 in their names.
It's most obvious in the `setRootConfig` overload taking a `Mmt4dOp`: this function is called regardless of architecture for any `Mmt4dOp`, and yet it ends up selecting `CPUAArchDoubleTilingExpert`: https://github.com/iree-org/iree/blob/a9227685614999b4de7ee53b3843ef1c7b409489/compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp#L993-L1038
So the chain of renamings in this PR starts here. There are multiple problems in the name `CPUAArchDoubleTilingExpert`:
1. It's suggesting something specific to ARM architectures ("AArch") even though it's used everywhere.
2. Just `AArch` alone without a 64 or 32 suffix is not a common term.
3. The `Double` part is out of sync with what the code actually …
> Rename away from `AArch`-everything

- compiler/src/iree/compiler/Codegen/Interfaces/BufferizationInterfaces.cpp
- compiler/src/iree/compiler/Codegen/Interfaces/PartitionableLoopsInterface.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilExternalModels.cpp
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtOps.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.h
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/Passes/Passes.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Passes/DecomposeSoftmax.cpp
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/decompose_softmax.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/invalid.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir
- llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tiling.mlir
- tests/e2e/linalg_ext_ops/BUILD
- tests/e2e/linalg_ext_ops/CMakeLists.txt
- tests/e2e/linalg_ext_ops/softmax.mlir
This patch adds the softmax op to the linalg ext dialect. It also adds a lowering that decomposes the softmax into a sequence of linalg generic ops. Finally, we add the pass into the CPU and CUDA pipeline along with an e2e test to validate functional accuracy.
> Add softmax op to linalg_ext

- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/test/smoketest.mlir
This reverts commit 8c303aabb2374ae79526b27a669f06cd455be263.
Based on this issue we will wait for this commit:
https://github.com/iree-org/iree/issues/11917
This flag is still useful in debug flow.
> Revert "[cuda] Remove `-iree-hal-cuda-dump-ptx` (#11908)"

- compiler/src/iree/compiler/Codegen/Common/BufferizationAnalysis.cpp
- compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
This refactors bufferization analysis of Linalg ops and LinalgExt ops. The implementation can be reused if DestinationStyleOpInterface is implemented.
Also adds tests for tensor.pack and tensor.unpack ops.
> Adapt IREE ConvertToDPS pass to support DPS interface generally.

- compiler/src/iree/compiler/Dialect/VMVX/IR/VMVXOps.td
> Make `vmvx.query_tile_sizes` op `PURE`.

- compiler/src/iree/compiler/Dialect/Flow/IR/FlowBase.td
- compiler/src/iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
- compiler/src/iree/compiler/Dialect/HAL/IR/HALDialect.td
- compiler/src/iree/compiler/Dialect/HAL/IR/HALOpFolders.cpp
- compiler/src/iree/compiler/Dialect/Stream/IR/StreamBase.td
- compiler/src/iree/compiler/Dialect/Stream/IR/StreamOpFolders.cpp
- compiler/src/iree/compiler/Dialect/Util/IR/UtilBase.td
- compiler/src/iree/compiler/Dialect/Util/IR/UtilOpFolders.cpp
- compiler/src/iree/compiler/Dialect/VM/Conversion/VMToEmitC/EmitCBuilders.cpp
- compiler/src/iree/compiler/Dialect/VM/IR/VMBase.td
- compiler/src/iree/compiler/Dialect/VM/IR/VMOpFolders.cpp
- compiler/src/iree/compiler/Dialect/VMVX/IR/VMVXBase.td
- compiler/src/iree/compiler/Modules/Check/IR/CheckOps.td
- compiler/src/iree/compiler/Modules/HAL/Inline/IR/HALInlineBase.td
- compiler/src/iree/compiler/Modules/HAL/Inline/IR/HALInlineOps.cpp
- compiler/src/iree/compiler/Modules/HAL/Loader/IR/HALLoaderBase.td
The latest integrate pulled in the deprecation of the default and this fixes the warnings generated by the IREE dialects.
> Switching IREE dialects to useFoldAPI = kEmitFoldAdaptorFolder.

- .github/workflows/post_benchmark_comment.yaml
By default the job listing API only returns 30 jobs (while the workflow has 33 jobs in my sample), which might not contain `process_benchmark_results`.
Increases to 100 when searching the benchmark results for posting comments.
> Search more CI jobs to check benchmark results

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_x86_64_launch_configuration.mlir
Without either pre-padding or masking not having the tile sizes divide the problem size for all tiling levels will result in un-vectorized code that has the side-effect of stack allocation. Even though this stack is bounded it is within the inner most loop and dynamic which will result in stack overflow. The matmul path is supposed to use pad + hoist, but that doesnt seem to kick in for non x86 or non f32 paths. 
This workaround addresses this in the short-term, avoid stack allocations. A proper fix will need to either deprecate this pipeline completely, use vector masking or use pre-padding/data tiling.
Issue #11880
> Make sure the selected workgroup size divides the problem size.

- compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp
- compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingInterface.cpp
- compiler/src/iree/compiler/Codegen/Common/Transforms.h
- compiler/src/iree/compiler/Codegen/SPIRV/test/lowering_matmul_promotion.mlir
The core functionality is moved into a utility method and called by walking over the function, instead of relying on GreedyPatternRewriter + Transformation Filter for applying the pattern only once.
Fixes #11607
> NFC: Remove use of GreedyPatternRewriter for first-level tile and distribute

- compiler/src/iree/compiler/Codegen/SPIRV/SPIRVTile.cpp
- compiler/src/iree/compiler/Codegen/SPIRV/test/tile_linalg_ops.mlir
The existing logic to count scf.if ops for fast and slow path didn't handle the case where scf.if exists in linalg.generic, which should be excluded in the analysis for tiling
> Fix SPIRVTile pass to handle linalg with scf.if

- compiler/src/iree/compiler/Codegen/Common/RematerializeParallelOps.cpp
- compiler/src/iree/compiler/Codegen/Common/test/rematerialize_parallel_ops.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- tests/e2e/regression/BUILD
- tests/e2e/regression/CMakeLists.txt
The rematerialization avoids use of stack allocations, instead of using a temporary buffer for one of the intermediate. This allows aggressive fusion herusitcs to be used without requirement of a intermediate stack buffer.
> Pull in the rematerialization pass into CPU lowering pipeline.

- compiler/src/iree/compiler/Codegen/LLVMCPU/BUILD
- compiler/src/iree/compiler/Codegen/LLVMCPU/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/DispatchABI.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/DispatchABI.h
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/convert_to_llvm.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/hal_interface_workgroup_info.mlir
- compiler/src/iree/compiler/Codegen/Passes.td
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.h
This restores line table information that had been dropped due to upstream MLIR changes by adding DISubprogramAttr to dispatch functions. In addition the arguments commonly used within dispatch functions are annotated with value information for use by debuggers. Additional debug information can be added in the future but hopefully with a way to more automatically keep it in sync with the runtime definitions. Since all of the debug information is strictly informational it's ok for them to get desynchronized (similar to our natvis file). Only ABI debug information is included here but others who may want to play with producing higher-level debug information can give that a try if they'd like though it's difficult to make anything at the higher-levels to make any sense by the time things …
> Adding debug information to LLVM CPU codegen outputs.

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/set_transform_strategy.mlir
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/CPU/ReductionStrategy.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/Common.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/Common/Common.h
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/StagedReductionStrategy.cpp
Add transformation to do store to load forwarding and remove extra alloc to store the partial reduction data.
This removes rank reduction for tensor/memref as those are currently creating extra copies that would prevent removing the allocations. This also changes how we distribute the merge reduction to be done across all threads of the group and fuse the fill op coming from reduction tiling with the reduction merge.
> [LLVMGPU] Remove allocations in reduction codegen using shared memory.

- runtime/src/iree/task/api.c
- runtime/src/iree/task/executor.c
- runtime/src/iree/task/executor.h
- runtime/src/iree/task/worker.c
- runtime/src/iree/task/worker.h
This explicitly requests (and on Windows commits) the per-worker stack memory such that we can assume it is valid when executing dispatch work. Prior to this we were using the executable default which will vary across platforms and compiler/linker configurations and make it difficult to reproduce stack issues.
The 128KB number is chosen as a conservative value based on what we currently produce in the compiler (<=32KB), what the VM+VMVX may require, and how much stack the task system itself may require on the workers (today ~8KB in x64 debug builds). The option/flag is exposed for users wanting to increase the limit along with larger compiler settings but the default is kept to something reasonable for smallish systems. For specific platforms that are looking to minimize fixed memory …
> Adding --task_worker_stack_size= flag and defaulting to 128KB.

- compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUCheckIRBeforeLLVMConversion.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/check_ir_before_llvm_conversion.mlir
Earlier checks were ensuring that the stack allocation sizes are bounded, but without enforcing that these are hoisted all the way to the top this could still lead to explosion of stack allocations. Add this check. This gives LLVM codegeneration a static stack frame. With that is guaranteed to be bounded.
Issue #11880
> Make stack allocations checks in generated code on LLVMCPU more stringent

- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/LLVMCPUTarget.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/internal/EmbeddedLinkerTool.cpp
- compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/internal/WindowsLinkerTool.cpp
- runtime/src/iree/base/internal/dynamic_library_win32.c
- runtime/src/iree/hal/local/elf/arch.h
- runtime/src/iree/hal/local/elf/arch/arm_32.c
- runtime/src/iree/hal/local/elf/arch/arm_64.c
- runtime/src/iree/hal/local/elf/arch/riscv.c
- runtime/src/iree/hal/local/elf/arch/x86_32.c
- runtime/src/iree/hal/local/elf/arch/x86_64.c
- runtime/src/iree/hal/local/elf/elf_module.c
The exports are not used and we normally omit them to reduce binary size. When disassembling/decompiling, though, having the exported symbols makes it much easier to find the dispatches and correlate them to the original program.
Example:
> Exporting LLVM CPU functions when debug symbols are enabled.

- runtime/src/iree/hal/string_util_test.cc
In C++20, iree::span is replaced with std::span, which is not identical.
Notably, std::span cannot be created from a temporary underlying data
structure, so these cases no longer compile.
(exporting change)
> Create spans from non-temporaries.

- compiler/src/iree/compiler/Dialect/Flow/Transforms/CollapseDimensions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/FormDispatchRegions.cpp
- compiler/src/iree/compiler/Dialect/Flow/Transforms/test/collapse_linalg_generic_on_tensors.mlir
This relands #11771.
Without these patterns, we end up with sequences like
```
%0 = tensor.empty ...
%1 = tensor.collapse_shape %0 ...
```
which dont get pulled into dispatch regions since
tensor.collapse_shapes arent pulled into dispatch regions. With the patterns the tensor.collapse_shape fold away, avoiding tensor.empty() being left outside.
Fixes #11770
> Add patterns to fold tensor.empty with tensor.collapse_expand/shape.

- runtime/src/iree/hal/drivers/cuda/tracing.c
- runtime/src/iree/hal/drivers/cuda/tracing.h
Not sure what specifically was the issue (maybe C vs C++), but removing inline helps.
```
[988/5107] Linking CXX executable runtime/src/iree/hal/drivers/cuda/cts/cuda_event_test
FAILED: ...
ld.lld: error: undefined symbol: iree_hal_cuda_tracing_context_allocate
```
> Fix CUDA tracing build in Debug build mode.

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.h
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp
This allows generating smaller allocations for reduction code generation. Without that we may generate allocation based on the original size rather than the tiled size.
> Add pattern to fold tensor.empty used by extract in transform dialect

- compiler/src/iree/compiler/Codegen/LLVMGPU/test/reduction_pipeline_transform.mlir
- compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/StagedReductionStrategy.cpp
If the op following the reduction doesn't broadcast it can be fused with the reduction to avoid having to go through memory.
> [LLVMGPU] Fuse trailing op if it doesn't broadcast

- docs/website/docs/getting-started/jax.md
Progress on https://github.com/iree-org/iree/issues/5454.
This updates https://iree-org.github.io/iree/getting-started/jax/
> Add placeholder JAX integration documentation.

- compiler/src/iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir
- compiler/src/iree/compiler/Dialect/HAL/IR/HALTypes.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/FuseDispatchBindings.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/Passes.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/annotate_dispatch_arguments.mlir
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/fuse_dispatch_bindings.mlir
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/fuse_dispatch_bindings_noalias.mlir
By moving dispatch argument annotation earlier we ensure that the annotations we provide are available before the dispatch ABI packing pass that uses them. Previously the annotation analysis was not able to make it past the new ops introduced by the packing pass. The alignment lookup was tweaked to be able to walk across `arith.index_castui` as that's the common case we encounter - it's not strictly required as dispatch ABI packing adds attributes, but this makes the lookup more robust to intermediate IR optimization.
Fixes #11969.
> Improving `hal.interface.constant.load` alignment propagation.

- integrations/tensorflow/test/python/iree_tf_tests/layers/layers_test.py
An upcoming change in Keras will enforce the API contract of Convolutional layers, which states that either `stride` or `dilation_rate` can have values greater than 1, but not both. See Keras docs e.g. [here](https://keras.io/api/layers/convolution_layers/convolution1d/)
> Update dilation rate in test of Keras convolutional layers

- tests/e2e/linalg/BUILD
- tests/e2e/linalg/CMakeLists.txt
* Use Vulkan as test name suggests
* Remove redundant compiler flags
> Fixup tests/e2e/linalg/ test definitions.

- runtime/src/iree/builtins/ukernel/arch/arm_64/pack_tile_arm_64.c
- runtime/src/iree/builtins/ukernel/common.h
- runtime/src/iree/builtins/ukernel/elementwise_impl.c.inc
- runtime/src/iree/builtins/ukernel/mmt4d.c
- runtime/src/iree/builtins/ukernel/pack.c
- runtime/src/iree/builtins/ukernel/pack.h
- runtime/src/iree/builtins/ukernel/pack_generic.c
- runtime/src/iree/builtins/ukernel/tools/pack_benchmark.c
- runtime/src/iree/builtins/ukernel/tools/pack_test.cc
- runtime/src/iree/builtins/ukernel/unpack.c
- More correct: the old code was incorrect for really large padding (test expanded).
- Faster: padding is handled with an intermediate buffer, which allows padded tiles to still be packed by the fast target-specific tile func, as opposed to a super slow generic fallback. Moreover, we optimize the common case where the padding byte pattern is a single-byte pattern so we can use memset.
Even with that, padding is still surprisingly slow. This means that compiler-level ways to remove padding overhead (pad fusions) are important in a way that is not diminished by the ability to call microkernels. @MaheshRavishankar @hanhanW 
Note: in ruy and XNNPACK, padding is handled by having separate source pointers for N strided rows being packed (so padding rows can just have their pointer point at some …
> pack microkernel padding improvements

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensionsOps.td
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_vector_to_mma.mlir
- compiler/src/iree/compiler/Codegen/Utils/GPUUtils.cpp
- compiler/src/iree/compiler/Codegen/Utils/GPUUtils.h
Change the transform dialect op to unroll vector ops to the right size before converting to mma.
> Add pattern to unroll vector ops before converting to mma

- compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
With multi-result dispatches a store could be encountered even before walking the entire use-def change. That is enough to replace the `tensor.empty` with a destination buffer.
> Fix ConvertToDestinationStylePassing to handle multi-result dispatches.

- runtime/src/iree/base/internal/flags.c
- runtime/src/iree/base/internal/flags_test.txt
- tests/transform_dialect/cpu/matmul.mlir
Not noticable when there's a handful of repeated flags but when there are 100+ things get sad.
> Fixing runtime flag string lists to not grow exponentially.

- runtime/src/iree/builtins/ukernel/tools/pack_benchmark.c
Fixes #12008
Regression introduced in #11987
I had tweaked the strides in the benchmark as I thought for a moment that it was more realistic to benchmark round (power of two) strides even when padding makes sizes a little smaller. But now I'm not so sure anymore what's the more important case in practice, so this just reverts to the old state.
The crash was because instead of the correct ` out_size1 * out_size3` (value for `in_size1` before adjustment for padding) I had incorrectly typed `out_size0 * out_size2`.
> fix bad stride in pack_benchmark

- build_tools/third_party/nccl/BUILD.overlay
- runtime/src/iree/hal/drivers/cuda/BUILD.bazel
- runtime/src/iree/hal/drivers/cuda/CMakeLists.txt
- runtime/src/iree/hal/drivers/cuda/cuda_driver.c
- runtime/src/iree/hal/drivers/cuda/cuda_headers.h
- runtime/src/iree/hal/drivers/cuda/dynamic_symbols.c
- runtime/src/iree/hal/drivers/cuda/dynamic_symbols.h
- runtime/src/iree/hal/drivers/cuda/nccl_channel.c
The nccl.h now is picked up from the repo even when the system has a NCCL library installed. The version is dynamically checked at runtime.
> Check the nccl version compatibility

- .github/workflows/advance_upstream_forks.yml
- .github/workflows/schedule_candidate_release.yml
This was to prevent workflows, especially scheduled ones, from running
in people's forks. GitHub now has functionality for fork owners to
disable a workflow and scheduled workflows are disabled by default in
forks. Having this repeated in every job is extra cruft and there are
cases where a fork owner who's using the fork as a site of active
development (as opposed to just for upstreaming) may want to do their
own releases and such and pull from upstream without maintaining a
patch. It seems like having everyone use the repository option is the
better way to support this.
https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
skip-ci: Doesn't affect CI workflows.
> Remove conditionals restricting workflows to a specific repo

- experimental/rocm/rocm_allocator.c
- runtime/bindings/python/hal.cc
- runtime/bindings/python/tests/hal_test.py
- runtime/src/iree/base/bitfield.c
- runtime/src/iree/base/bitfield.h
- runtime/src/iree/base/bitfield_test.cc
- runtime/src/iree/base/string_view.c
- runtime/src/iree/base/string_view.h
- runtime/src/iree/base/string_view_test.cc
- runtime/src/iree/hal/allocator.c
- runtime/src/iree/hal/allocator.h
- runtime/src/iree/hal/allocator_heap.c
- runtime/src/iree/hal/buffer.c
- runtime/src/iree/hal/buffer.h
- runtime/src/iree/hal/buffer_view_util.c
- runtime/src/iree/hal/command_buffer_validation.c
- runtime/src/iree/hal/cts/allocator_test.h
- runtime/src/iree/hal/cts/buffer_mapping_test.h
- runtime/src/iree/hal/drivers/cuda/cuda_allocator.c
- runtime/src/iree/hal/drivers/cuda/cuda_device.c
- runtime/src/iree/hal/drivers/vulkan/vma_allocator.cc
The new `iree_hal_allocator_query_memory_heaps` API allows allocators to expose the available memory heaps to external layers that need to make decisions based on the characteristics of the underlying allocator.
The update to `iree_hal_allocator_query_buffer_compatibility` provides pooling layers the ability to ask implementations to adjust the parameters and allocation size of a request without performing the allocation. A pooling layer that was trying to find an appropriate bucket or virtual addressing layer that needed to query for reservation ranges can take the user params, have the implementation adjust them, and assume that any allocations made would have those exact parameters.
To aid flag/configuration utilities some bitfield parsing has been added for HAL memory types that can …
> Extending `iree_hal_allocator_t` with memory heaps and compat queries.

- compiler/src/iree/compiler/Codegen/Dialect/IREECodegenDialect.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/Input/InputBase.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgExt/IR/LinalgExtBase.td
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/LinalgExtOps.cpp
- third_party/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/TMTensor/IR/TMTensorBase.td
- third_party/torch-mlir-dialects/lib/Dialect/TMTensor/IR/TMTensorOps.cpp
This fixes issues in LinalgExt and TM_Tensor. Other warnings currently are from MHLO repo.
> Fix warning spew related to default value of `useFolderAPI` being `kEmitRawAttributeFolder`.

- compiler/src/iree/compiler/Codegen/Common/TileDispatchUsingInterface.cpp
During tiling of iree_linalg_ext tiling it is possible for cleanup to only partially determine static shapes due to only partial shape propagation. Guaranteeing that offsets/shapes are used as static values when possible seems to correct the issue.
> Fix iree_linalg_ext.scatter tiling failure due to static shapes #11877

- runtime/src/iree/tooling/vm_util.c
- runtime/src/iree/tooling/vm_util.h
- samples/simple_embedding/simple_embedding_test.mlir
- tools/iree-run-mlir-main.cc
- tools/iree-run-module-main.cc
- tools/test/BUILD
- tools/test/CMakeLists.txt
- tools/test/echo_npy.py
- tools/test/iree-run-module-outputs.mlir
This allows for ignoring outputs, routing them to stdout, or writing them to numpy .npy files that can be easily loaded in python.
Example writing two outputs to an npy file:
`iree-run-module ... --output=@file.npy --output=+file.npy`
```py
with open('file.npy', 'rb') as f:
print(numpy.load(f))
print(numpy.load(f))
```
The `@` sigil will create/overwrite a file while the `+` sigil will create/append. This allows for multiple outputs to route to the same file even across runs (so you could run several times and accumulate the results in a single npy to process later). Shorthand for writing all outputs to an npy would be useful but is not yet implemented. We can extend this in many ways in the future by supporting binary payload writing (ala `--input=2xf32=@file.bin`), merging functionality …
> Add `--output=` flag to iree-run-module/iree-run-mlir.

- runtime/src/iree/vm/invocation.c
Future changes will handle dynamic growth - for now this at least provides user-serviceable errors.
> Properly erroring out when spilling VM result stack storage.

- compiler/src/iree/compiler/Dialect/Stream/Transforms/EmplaceAllocations.cpp
- compiler/src/iree/compiler/Dialect/Stream/Transforms/test/emplace_allocations.mlir
As is common in concat patterns it's possible for more than one result of a single dispatch to be placed into the same allocation. Previously this wouldn't check that a result had been placed and create cycles as we'd try to place a subsequent result into another result.
Fixes #11981.
> Handle multi-result dispatches that all route into update ops.

- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/IR/CMakeLists.txt
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Utils/CMakeLists.txt
This PR adds a few missing CMake dependencies.
IREE is built by default with [`BUILD_SHARED_LIBS=OFF`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html), so most libraries are built as static libraries. This means that not all symbols referenced by a particular library need to be present -- it is sufficient if some other library that is used in the same final executable also imports them. Some missing dependencies can therefore go unnoticed for some time. Building IREE with `BUILD_SHARED_LIBS=ON` reveals (some of) them.
I have recently fixed these dependencies in `mlir-hlo` (see [PR](https://github.com/tensorflow/tensorflow/pull/59421) and [integration commit](https://github.com/tensorflow/mlir-hlo/commit/ed069b6e)) and the dependency has now been updated, such that …
> Add a few missing CMake dependencies required for building shared libs.

- benchmarks/TFLite/linux-riscv.cmake
- build_tools/cmake/riscv.toolchain.cmake
- build_tools/python/e2e_test_artifacts/cmake_generator/iree_rule_generator.py
- docs/website/docs/building-from-source/riscv.md
- tests/e2e/test_artifacts/generated_e2e_test_iree_artifacts.cmake
LLVM is moving towards using the `+zvl*b` target feature instead of using the flag.
> Replace `riscv-v-vector-bits-min` with `+zvl*b` in RISC-V configs

- build_tools/benchmarks/common/benchmark_definition.py
- build_tools/cmake/iree_benchmark_suite.cmake
- runtime/src/iree/base/tracing.cc
- runtime/src/iree/base/tracing.h
- runtime/src/iree/hal/utils/BUILD
- runtime/src/iree/hal/utils/CMakeLists.txt
- runtime/src/iree/hal/utils/caching_allocator.c
- runtime/src/iree/hal/utils/caching_allocator.h
- runtime/src/iree/tooling/BUILD
- runtime/src/iree/tooling/CMakeLists.txt
- runtime/src/iree/tooling/device_util.c
This provides bounded or unbounded device buffer allocation caching and can be enabled in tooling with `--device_allocator=caching` - it can also be customized (changing pool sizes and types, etc) via some more flags or the API. Most usage that would benefit today falls into benchmarks and those are fine with unbounded. Since this style of allocator can easily lead to out-of-memory situations it's off by default and something a user needs to opt into based on their usage patterns and configuration needs. User binding layers can decide how they want to expose allocator configuration; some may want their own defaults and simple enums while others may want to expose deep configuration. This is like clang/gcc not forcing tcmalloc/jemalloc/mimalloc and requiring users to opt-in based on their …
> Adding iree_hal_caching_allocator_t.

- compiler/src/iree/compiler/Codegen/LLVMGPU/test/transform_dialect_promote_operands.mlir
There is a mid-air collision in the test added by https://github.com/iree-org/iree/commit/21e5ddf416c580e5fe1f8ed881e8c990dbc69ffc. This fixes the issue.
> Fix tests for mid-air collision

- compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToLLVM.h
- compiler/src/iree/compiler/Codegen/LLVMGPU/ConvertToNVVM.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/BUILD
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/convert_to_nvvm_error.mlir
- compiler/src/iree/compiler/Tools/BUILD
- compiler/src/iree/compiler/Tools/CMakeLists.txt
- compiler/src/iree/compiler/Tools/init_mlir_dialects.h
Eliminates the crash for #12067 (but does not make it pass). This should give us time to have a better way of handling these high level types.
> Fix compiler crash on unsupported LLVM types at interface boundary.

- compiler/src/iree/compiler/Codegen/Common/test/BUILD
- compiler/src/iree/compiler/Codegen/Common/test/CMakeLists.txt
- compiler/src/iree/compiler/Codegen/Common/test/repeated_matcher_use.mlir
- llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/TransformMatchers.h
- llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp
- llvm-external-projects/iree-dialects/lib/Transforms/TransformMatchers.cpp
When running the transform dialect-related matcher recursively, check if
a corresponding payload operation has been already captured. If so,
check whether the inspected operation is the same as already captured
instead of rechecking the predicates. This allows matchers to be used
repeatedly in a recursive structure to indicate that the same operation
must be used in several places.
> Transform: avoid rematching ops when already captured

- compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorCoreVectorization.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_mma_sync_pipeline_test.mlir
- tests/e2e/matmul/BUILD
- tests/e2e/matmul/CMakeLists.txt
**Adds native Tensor Core (F32) support for NVIDIA A100 GPU** 
The PR targets`mma.sync.aligned.m16n8k8.row.col.f32.tf32.tf32.f32`, `ldmatrix` for operandA and `ld.shared` for operandB on NVIDIA A100 GPUs. For now, these instructions are not enabled by default and are behind iree-compile flag `--iree-codegen-llvmgpu-use-mma-sync=true`.
IREE runs row-row matmul, the native Tensor Core support is enabled through `ldmatrix` for operandA. However, 
`ldmatrix.trans` for operandB can only work at 16-bit granularity. Thus, `ld.shared` instruction is used for operandB to transposes the data while loading data into register. This allows the use of Tensor Core `mma.sync*row.col*` instruction.
> Functional support mma.sync.1688.f32.tf32 for F32 datatype

- compiler/src/iree/compiler/Codegen/LLVMGPU/test/nvvm_mma_sync_pipeline_test.mlir
Fixing the `MMASYNC` to `CHECK` in F32 `mma.sync` lit tests. We have moved `mma.sync` lit test checking linalg-to-nvvm-pipeline in a separate file. Thus, using the default `CHECK` macro to run the lit tests. 
Also, making `mma.sync` verification more verbose. It now checks for instruction shape, datatype, and layout.
> Fix F32 `mma.sync` lit test 

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.h
- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensionsOps.td
- tests/transform_dialect/cpu/BUILD
- tests/transform_dialect/cpu/CMakeLists.txt
- tests/transform_dialect/cpu/contraction-packing-and-dispatch.mlir
- tests/transform_dialect/cpu/contraction-packing.mlir
This revision demonstrates how the generalized packing transformation is a one-size fits all implementation
for tiling linalg ops of rank N to linalg ops of higher rank.
The tensor.pack / tensor.unpack representation allows us to complete our panoply of composable linalg transformations.
Now, one can either:
1. lower a linalg op to loops and use classical loop-based tiling techniques (e.g. Allen&Kennedy, polyhdral/affine etc)
2. tile an N-D linalg op to N-D loops surrounding an N-D linalg op. This often preserves the name of the linalg op and is at the basis of the TilingInterface.
3. (this PR) tile an N-D linalg op to a 2*N-D linalg.generic. This step requires that the tile dimensions divide the problem dimension. tensor.pack / tensor.unpack provide this guarantee.
Step 3. can easily be …
> Add an example of generalized packing

- runtime/src/iree/builtins/ukernel/BUILD
- runtime/src/iree/builtins/ukernel/CMakeLists.txt
- runtime/src/iree/builtins/ukernel/arch/CMakeLists.txt
- runtime/src/iree/builtins/ukernel/arch/arm_64/BUILD
- runtime/src/iree/builtins/ukernel/arch/arm_64/CMakeLists.txt
- runtime/src/iree/builtins/ukernel/arch/arm_64/common_arm_neon.h
- runtime/src/iree/builtins/ukernel/arch/arm_64/pack_arm_64.c
- runtime/src/iree/builtins/ukernel/arch/arm_64/unpack_arm_64.c
- runtime/src/iree/builtins/ukernel/arch/arm_64/unpack_arm_64.h
- runtime/src/iree/builtins/ukernel/pack.c
- runtime/src/iree/builtins/ukernel/pack.h
- runtime/src/iree/builtins/ukernel/tools/BUILD
- runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt
- runtime/src/iree/builtins/ukernel/tools/pack_test.cc
- runtime/src/iree/builtins/ukernel/tools/ukernel_test_utils.cc
- runtime/src/iree/builtins/ukernel/tools/ukernel_test_utils.h
- runtime/src/iree/builtins/ukernel/tools/unpack_benchmark.c
- runtime/src/iree/builtins/ukernel/tools/unpack_test.cc
- runtime/src/iree/builtins/ukernel/unpack.c
- runtime/src/iree/builtins/ukernel/unpack.h
- runtime/src/iree/builtins/ukernel/unpack_tile.c
- runtime/src/iree/builtins/ukernel/unpack_tile.h
`unpack` ukernel:
- ARM64 code (NEON intrinsics - good enough for now but boy did I have to wrestle clang / settle for suboptimal perf for the sake of simplicity).
- test and benchmark (close ports of the `pack` ukernel test and benchmark).
`pack` ukernel:
- Sharing NEON routines with `unpack`
- Improvements, keeping aligned with the `unpack` code.
> unpack ukernel (ARM64 code, test, benchmark) + pack improvements

- CMakeLists.txt
Progress on https://github.com/iree-org/iree/issues/11994 (tested on Windows, not Linux)
I've been seeing this "Connection lost!" error when tracing the compiler (specifically using sampling or instrumentation with memory profiling - basically anything that increases the amount of data that Tracy needs to pull across): 
We've had similar errors before with other dynamic libraries and have this patch in IREE's _runtime_: https://github.com/iree-org/iree/blob/eadd7498d7cbe4564ab5f12321dfeb882f7ff1d7/runtime/src/iree/base/internal/dynamic_library_win32.c#L268-L284
I don't see how to make an equivalent change in https://github.com/iree-org/iree/tree/main/compiler/src/iree/compiler/API2, so just making `IREE_LINK_COMPILER_SHARED_LIBRARY` and `IREE_ENABLE_COMPILER_TRACING` mutually exclusive …
> Require compiler static linking when using compiler tracing.

- CMakeLists.txt
- build_tools/cmake/build_all.sh
- build_tools/cmake/build_and_test_asan.sh
- build_tools/cmake/build_and_test_tsan.sh
- build_tools/cmake/build_android.sh
- build_tools/cmake/build_host_and_android.sh
- build_tools/cmake/build_riscv.sh
- build_tools/cmake/build_runtime_emscripten.sh
- build_tools/cmake/rebuild.sh
This is so that running all tests with `ctest` does not require building both `iree-test-deps` and `iree-sample-deps`. At the same time, it is still possible to build samples without building all the other test dependencies.
Update all build scripts so that they build `iree-test-deps` only.
> [cmake] Build iree-sample-deps with iree-test-deps

- runtime/src/iree/vm/list.c
- runtime/src/iree/vm/list.h
- runtime/src/iree/vm/list_test.cc
- runtime/src/iree/vm/ref.c
This covers the C implementation of these routines and adds a bunch of tests. Future changes will expose these to the compiler as VM ops.
Progress on #7014.
> Adding iree_vm_list_swap_storage and iree_vm_list_copy.

- compiler/src/iree/compiler/Dialect/Vulkan/IR/VulkanBase.td
- llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/LinalgTransformOps.td
We are not actually having op folders in these two dialects. So just switch it over.
> Switch to use adaptor folder API to silence deprecation warnings

- compiler/src/iree/compiler/Dialect/Util/Conversion/MemRefToUtil/Patterns.cpp
The `getBufferOffsetAndLength` helper struck me as a cleanup opportunity:
* Returning a `pair` suggested wanting to be broken into 2 helpers. Still avoiding redundant `SizeOfOp`'s, as the second helper can get that from the first.
*  The words `Length` and `byteLength` were used in a context that suggested that they were referring to the buffer's length, when actually they meant the element type's size.
* assertions looked like they should rather be `emitError` - less confusing in no-asserts release builds so we get errors instead of silently continuing there.
* The computation assumed that the 1D memref stride was 1, but wasn't checking that.
* Helpers that take a fancy sub-class of `PatternRewriter` but actually only use it to build an op may as well take it as an `OpBuilder` (base …
> Clean up MemRefToUtil internal helper

- runtime/src/iree/base/internal/flags.h
`IREE_FLAGS_ENABLE_FLAG_FILE` only works when file IO is enabled. For generic platforms with `IREE_FILE_IO_ENABLE=0` it could cause build failure. Add additional checks for the default setting.
> Fix `IREE_FLAGS_ENABLE_FLAG_FILE` file IO support

- compiler/src/iree/compiler/Codegen/Common/TransformExtensions/CommonExtensions.cpp
This patch makes the error message for the transform dialect `TileToForeachThreadAndWorkgroupCountRegionOp` a little bit more actionable/understandable.
NFC
> Improve error messages around the expectation of the input IR

- compiler/src/iree/compiler/Dialect/Util/Conversion/MemRefToUtil/Patterns.cpp
- compiler/src/iree/compiler/Dialect/Util/Conversion/MemRefToUtil/test/memref_ops.mlir
Anyone who's tried to use VMVX has encountered the dreadful `error: failed to legalize operation 'memref.alloca'`. Users have run into and reported it multiple times, e.g.  #10859, #10855.
I had been working under the assumption that there was some fundamental difficulty here between VMVX and `memref.alloca`; after all, I thought, it made sense that the VM wouldn't support that.
Apparently, I wasn't alone: https://github.com/iree-org/iree/issues/10859#issuecomment-1329840940 says
> _In this context, we allocate a stack buffer, which is not allowed in VMVX backend [...] There are couple ways to fix it. [...] a.) Tile dynamic dims with size 1, so we can always vectorize it._
The resulting fix #11323 has helpfully unblocked users since, but more recently, as ukernels have started to make …
> support dynamic size in ConvertMemRefAllocaOp

- compiler/src/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp
- compiler/src/iree/compiler/Codegen/LLVMCPU/test/materialize_vmvx_launch_configuration.mlir
- tests/e2e/regression/BUILD
- tests/e2e/regression/CMakeLists.txt
- tests/e2e/regression/dynamic_matmuls_on_same_accumulator_issue_12060.mlir
- tests/e2e/regression/dynamic_tosa_clamp.mlir
- tests/e2e/regression/dynamic_tosa_quantized_fully_connected_issue_10859.mlir
Fixes #12073.
This is essentially a rollback of #11323, but keeping the useful test that it introduced, and adding known testcases as e2e regression tests (compilation only).
This is a gigantic performance improvement in my case -- two orders of magnitude on large (1024x1024) matmul benchmarks on VMVX + ukernels on ARM64 (which is where we currently have optimized ukernels). The reason is that while the ukernel is happy to handle a dispatch of any size, with VMVX there is a high reward for having larger ukernel dispatches, since anything outside of ukernels is very slow in VMVX.
> Undo special-case 1x1 tiling for VMVX

- build_tools/buildkite/cmake/linux/pipeline.yml
This has just happened to work so far because the Buildkite builders
save the old repository. Discovered when testing for
https://github.com/iree-org/iree/issues/12102. Because the repo has a
different name, Buildkite uses a different directory and then no
submodules.
https://buildkite.com/iree/iree-benchmark-linux-openxla-test/builds/2#0186331f-16c6-4268-bd7e-9ef546fd4319
> Initialize runtime submodules before building benchmark binaries

- docs/website/docs/bindings/python.md
- docs/website/docs/building-from-source/android.md
- docs/website/docs/building-from-source/getting-started.md
- docs/website/docs/building-from-source/python-bindings-and-importers.md
- docs/website/mkdocs.yml
https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs
Now clicking "Windows" on one page will update all content tabs across the website to default to "Windows" too. Note that labels must match exactly, so I've also split apart all of our "Linux and MacOS" content sections to "Linux" and "macOS".
> Link content tabs across the website.

- compiler/src/iree/compiler/Codegen/Common/BufferizationAnalysis.cpp
- compiler/src/iree/compiler/Codegen/Common/BufferizationAnalysis.h
- compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp
- compiler/src/iree/compiler/Codegen/Common/test/convert_to_destination_passing_style.mlir
- compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp
- compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp
For dispatches with
```
%r = <some compute op>
%store = linalg.generic ... ins(%r, ...) outs(%empty :)
```
where the value of `%store` is the final result of the dispatch, to avoid creation of stacks for `%r` when vectorization does not kick in, the user is converted to
```
%store = linalg.generic ... ins(, ...) outs(%r :)
```
This is a very specific change to work around something that really should be handled later on during bufferization (but is outside scope of bufferization today). This change needs to kick in very specific conditions (since its a work-around, and really the created `linalg.generic` is somewhat of an anti-pattern), using a pattern rewrite to make this change does not allow controlling the transformation. Change this to use a walk and trigger only when needed.
Fixes …
> Redo handling of operand reuse to prevent stack allocation.

- tests/e2e/linalg_ext_ops/BUILD
- tests/e2e/linalg_ext_ops/CMakeLists.txt
Least-hacky way I could think of to disable building the `iree_tests_e2e_linalg_ext_ops_check_llvm-cpu_local-task_attention.mlir` target on Emscripten while we work on a fix.
See https://github.com/iree-org/iree/pull/12041#discussion_r1101777536 and https://github.com/iree-org/iree/actions/runs/4130706149/jobs/7137719751
```
[14/350] Generating check_llvm-cpu_local-task_attention.mlir_module.vmfb from attention.mlir
FAILED: tests/e2e/linalg_ext_ops/check_llvm-cpu_local-task_attention.mlir_module.vmfb /work/build-emscripten/tests/e2e/linalg_ext_ops/check_llvm-cpu_local-task_attention.mlir_module.vmfb 
cd /work/build-emscripten/tests/e2e/linalg_ext_ops && /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false …
```
> Disable some linalg_ext_ops tests on Emscripten while failing.
